### ISSUE TITLE
A problem with __attribute__

### ISSUE THREAD

**Issue by lvc** [universal-ctags/ctags#1001]
Hello,

The universal ctags (using f6dafc0609db8a478c9791eb39a65494ec0ac921) failed to detect a function that use \_\_attribute__ statement for a parameter.

In the header libcryptsetup.h from cryptsetup-1.4.2.tar.xz package:

    int crypt_repair(struct crypt_device *cd,
		 const char *requested_type,
		 void *params __attribute__((unused)));

This command returns empty output:

    ctags -x --c-kinds=fpvx libcryptsetup.h | grep crypt_repair

What -I flag should I provide to detect this function?

Thank you.

**Comment by masatake** [comment]
I want `__attribute__` support, too. These are used widely in linux kernel.

**Comment by pragmaware** [comment]
With the pull request above I get:
```
$ ctags -x --c++-kinds=fpvx /usr/include/libcryptsetup.h | grep crypt_repair
crypt_repair     prototype   491 /usr/include/libcryptsetup.h int crypt_repair(struct crypt_device *cd,
```
