### ISSUE TITLE
Broken detection of functions and prototypes

### ISSUE THREAD

**Issue by lvc** [universal-ctags/ctags#1002]
Hello,

The latest ctags (56612cfbcd1baaa4e8f04ded6aac57cac01fd136) can't detect any functions.

Using this command to list functions and prototypes:

    ctags -x --c-kinds=fpvx libcryptsetup.h

The tool lists macroses, enumerators, enums, structs and typedefs instead of functions and prototypes.

Seems that something was broken (or changed incompatibly) between 56612cfbcd1baaa4e8f04ded6aac57cac01fd136 (doesn't work) and e5b7a2508db6e1374ea78a300cc9b45f4b26b02a (works) commits.

Thank you.

**Comment by masatake** [comment]
Thank you for reporting this.

Could you try following command line?

```
ctags -x --c++-kinds=fpvx libcryptsetup.h
```
or

```
./ctags -x --langmap=C:.h --c-kinds=fpvx ./libcryptsetup.h
```

Could you read "Kinds separation" section in docs/parser-cxx.rst.
(http://docs.ctags.io/en/latest/parser-cxx.html)

@pragmaware, this is the first report of incompatibility. I feel we need the way to share the kinds between C and C++. If you agree with me, I will try to implement the sharing mechanism. (after rewriting python parser.)

**Comment by pragmaware** [comment]
Yes, this is a problem. *.h files are always parsed as C++ and I think we can't do in any other way.
We either (1) go back to a single kind set for C and C++ or (2) implement some method for partial kind sharing between languages. (2) is probably nicer, especially if we want to add objective-C support to the cxx parser some time in the future.

**Comment by masatake** [comment]
O.k. I will inspect (2) more.
@lvc, we need more time to accept the original command line that you reported.
I think this is important because `make tags` of linux kernel expects this.

**Comment by lvc** [comment]
Hello,

Both

    ctags -x --c++-kinds=fpvx libcryptsetup.h

and
    
    ctags -x --langmap=C:.h --c-kinds=fpvx libcryptsetup.h

commands work fine (using 56612cfbcd1baaa4e8f04ded6aac57cac01fd136) and return the same output as `ctags -x --c-kinds=fpvx libcryptsetup.h` (using old e5b7a2508db6e1374ea78a300cc9b45f4b26b02a).

Also works:
    
    ctags --language-force=c -x --c-kinds=fpvx libcryptsetup.h

Doesn't work:

    ctags --language-force=c++ -x --c-kinds=fpvx libcryptsetup.h

C++ allows to declare function prototypes outside classes and therefore ctags should list them when specifying `--language-force=c++`. Isn't it?

Thank you.

**Comment by lvc** [comment]
I've also checked ctags 56612cfbcd1baaa4e8f04ded6aac57cac01fd136 on a standalone variable declaration from cmdline.h of MySQL++ 3.2.2 library:

    extern MYSQLPP_EXPORT const char* db_name;

The

    ctags --language-force=c++ -x --c-kinds=fpvx cmdline.h | grep db_name

command doesn't detect the variable. However the old version (e5b7a2508db6e1374ea78a300cc9b45f4b26b02a) does.

Should I for now run ctags twice (one time with `--language-force=c++` and another with `--language-force=c`) to detect full list of prototypes?

Thank you.

**Comment by masatake** [comment]
> extern MYSQLPP_EXPORT const char* db_name;

This is a different issue. What you should add to `-I MYSQLPP_EXPORT`.

**Comment by b4n** [comment]
Ideally I guess the C/C++ parser would be so clever it'd try to make sense of such statements trying to skip some tokens (generally ones in full caps or starting with `__`) when a statement doesn't seem to make too much sense, as it's common for many libraries to declare custom `EXPORT` or similar macros.
However, that might be too much effort on the parse side for not always much gain, and a less predictable behavior.  But for the end user it'd probably be nice.

**Comment by masatake** [comment]
>  (2) implement some method for partial kind sharing between languages

Finally I found a good and interesting way to implement "shared kind".

**Comment by masatake** [comment]
I add new concenpt master/slave to kinds.
Now all C kinds are master in C parser and slave in C++ parser.
After some code cleanup, I will submit a PR.

```
[yamato@x201]~/var/ctags-github%  ./ctags --kinds-C++=+de --list-kinds-full=C | head -5
#LETTER NAME            ENABLED  REFONLY NROLES MASTER     DESCRIPTION                   
d       macro           on       FALSE   1      .          macro definitions             
e       enumerator      on       FALSE   0      .          enumerators (values inside an enumeration)
f       function        on       FALSE   0      .          function definitions          
g       enum            on       FALSE   0      .          enumeration names             
[yamato@x201]~/var/ctags-github%  ./ctags --kinds-C++=-de --list-kinds-full=C | head -5
#LETTER NAME            ENABLED  REFONLY NROLES MASTER     DESCRIPTION                   
d       macro           off      FALSE   1      .          macro definitions             
e       enumerator      off      FALSE   0      .          enumerators (values inside an enumeration)
f       function        on       FALSE   0      .          function definitions          
g       enum            on       FALSE   0      .          enumeration names             
[yamato@x201]~/var/ctags-github%  ./ctags --kinds-C=+de --list-kinds-full=C++ | head -5
#LETTER NAME            ENABLED  REFONLY NROLES MASTER     DESCRIPTION                   
d       macro           on       FALSE   1      C          macro definitions             
e       enumerator      on       FALSE   0      C          enumerators (values inside an enumeration)
f       function        on       FALSE   0      C          function definitions          
g       enum            on       FALSE   0      C          enumeration names             
[yamato@x201]~/var/ctags-github%  ./ctags --kinds-C=-de --list-kinds-full=C++ | head -5
#LETTER NAME            ENABLED  REFONLY NROLES MASTER     DESCRIPTION                   
d       macro           off      FALSE   1      C          macro definitions             
e       enumerator      off      FALSE   0      C          enumerators (values inside an enumeration)
f       function        on       FALSE   0      C          function definitions          
g       enum            on       FALSE   0      C          enumeration names             
```

**Comment by masatake** [comment]
@lvc, could you try the latest code? 
If the issue is not fixed, please, reopen this. Thank you.
