### ISSUE TITLE
JavaScript: functions not recognized if wrapped

### ISSUE THREAD

**Issue by caneta** [universal-ctags/ctags#1014]
Hi everybody.
If I have some JavaScript literal functions with one wrap level inside a global function, universal-ctags works perfectly.
With test1.js file:
```
function (A){
  var Test;
  Test.func1 = function func1(){ console.log('func1'); };
  Test.func2 = function func2(){ console.log('func2'); };
}
```
`ctags test1.js` produces
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/5ab7c69/
func1	test1.js	/^  Test.func1 = function func1(){$/;"	f
func1	test1.js	/^  Test.func1 = function func1(){$/;"	f	function:Test
func2	test1.js	/^  Test.func2 = function func2(){$/;"	f
func2	test1.js	/^  Test.func2 = function func2(){$/;"	f	function:Test
```
But if I add another wrap level, having these definitions passed like a method parameter (test2.js):
```
AUI().use(
  function funcGen(A){
    var Test;
    Test.func1 = function func1(){ console.log('func1'); };
    Test.func2 = function func2(){ console.log('func2'); };
  }
);
```
universal-ctags doesn't work anymore (`ctags test2.js`):
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/5ab7c69/
```
Is there some special configurations or tricks to get things works in the second case?
Thanks.

**Comment by masatake** [comment]
Could you try #1014?

**Comment by caneta** [comment]
Yay, it works!
I've recompiled ctags using branch [jscript-capture-function-block-in-arglist in your forked repo](https://github.com/masatake/ctags/tree/jscript-capture-function-block-in-arglist), and this is what I get now:
```
user@host:~$ ctags test2.js 
user@host:~$ cat tags 
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/f5ee5f8/
func1	test2.js	/^    Test.func1 = function func1(){ console.log('func1'); };$/;"	f
func1	test2.js	/^    Test.func1 = function func1(){ console.log('func1'); };$/;"	f	function:Test
func2	test2.js	/^    Test.func2 = function func2(){ console.log('func2'); };$/;"	f
func2	test2.js	/^    Test.func2 = function func2(){ console.log('func2'); };$/;"	f	function:Test
funcGen	test2.js	/^  function funcGen(A){$/;"	f
```
Awesome! Now I can use [tagbar](https://github.com/majutsushi/tagbar) to see the file outline:
![nvimctagsjavascript](https://cloud.githubusercontent.com/assets/4066659/16635650/a8b2f4a6-43d3-11e6-8224-1bce60de4961.png)

**Comment by mitermayer** [comment]
@caneta was wondering what is your .ctags file in order to parse javascript files ? Are you just using the default universal-ctags ?

**Comment by caneta** [comment]
For this example I've used universal ctags at the repo and branch reported above. Whta is the .ctags file? It's a configuration file? I don't have one...

**Comment by masatake** [comment]
ctags load ~/.ctags. However, my understanding is that .ctags is nothing to do with this issue.
