### ISSUE TITLE
lregex parser broken?

### ISSUE THREAD

**Issue by tarzanek** [universal-ctags/ctags#1062]
Hi guys
It seems one of last commits in 
https://github.com/universal-ctags/ctags/commits/master/main/lregex.c
broke the selection of type for matched line
Expected(from ctags 5.9svn ):
```
Sample  Sample.pas      /^unit Sample;$/;"      unit    line:22
uses    Sample.pas      /^uses$/;"      Section line:23
interface       Sample.pas      /^interface$/;" Section line:26
TSample Sample.pas      /^    TSample = class$/;"       Class   line:28
GetId   Sample.pas      /^      function GetId : integer;$/;"   function        line:33
SetId   Sample.pas      /^      procedure SetId(const aValue : integer);$/;"    procedure       line:34
GetClassName    Sample.pas      /^      class function GetClassName: string;$/;"        function        line:36
GetIdAndDescriptionString       Sample.pas      /^      function GetIdAndDescriptionString: string; virtual;$/;"        function        line:37
GetUser Sample.pas      /^      function GetUser: TUser;$/;"    function        line:38
Id      Sample.pas      /^      property Id: integer read GetId write SetId;$/;"        property        line:40
Description     Sample.pas      /^      property Description: string read FDescription write FDescription;$/;"  property        line:41
implementation  Sample.pas      /^implementation$/;"    Section line:44
uses    Sample.pas      /^uses$/;"      Section line:45
GetId   Sample.pas      /^function TSample.GetId: integer;$/;"  function        line:48
TSample.GetId   Sample.pas      /^function TSample.GetId: integer;$/;"  function        line:48
SetId   Sample.pas      /^procedure TSample.SetId(const aValue: integer);$/;"   procedure       line:53
TSample.SetId   Sample.pas      /^procedure TSample.SetId(const aValue: integer);$/;"   procedure       line:53
TSample.GetClassName    Sample.pas      /^class function TSample.GetClassName: string;$/;"      function        line:58
GetUser Sample.pas      /^function TSample.GetUser: TUser;$/;"  function        line:63
TSample.GetUser Sample.pas      /^function TSample.GetUser: TUser;$/;"  function        line:63
```

What I get using universal ctags:
```
Sample  Sample.pas      /^unit Sample;$/;"      Section line:22
uses    Sample.pas      /^uses$/;"      Section line:23
interface       Sample.pas      /^interface$/;" Section line:26
TSample Sample.pas      /^    TSample = class$/;"       Class   line:28
GetId   Sample.pas      /^      function GetId : integer;$/;"   function        line:33
SetId   Sample.pas      /^      procedure SetId(const aValue : integer);$/;"    procedure       line:34
GetClassName    Sample.pas      /^      class function GetClassName: string;$/;"        function        line:36
GetIdAndDescriptionString       Sample.pas      /^      function GetIdAndDescriptionString: string; virtual;$/;"        function        line:37
GetUser Sample.pas      /^      function GetUser: TUser;$/;"    function        line:38
Id      Sample.pas      /^      property Id: integer read GetId write SetId;$/;"        procedure       line:40
Description     Sample.pas      /^      property Description: string read FDescription write FDescription;$/;"  procedure       line:41
implementation  Sample.pas      /^implementation$/;"    Section line:44
uses    Sample.pas      /^uses$/;"      Section line:45
GetId   Sample.pas      /^function TSample.GetId: integer;$/;"  procedure       line:48
TSample.GetId   Sample.pas      /^function TSample.GetId: integer;$/;"  function        line:48
SetId   Sample.pas      /^procedure TSample.SetId(const aValue: integer);$/;"   procedure       line:53
TSample.SetId   Sample.pas      /^procedure TSample.SetId(const aValue: integer);$/;"   procedure       line:53
TSample.GetClassName    Sample.pas      /^class function TSample.GetClassName: string;$/;"      function        line:58
GetUser Sample.pas      /^function TSample.GetUser: TUser;$/;"  procedure       line:63
TSample.GetUser Sample.pas      /^function TSample.GetUser: TUser;$/;"  function        line:63
```

**Comment by tarzanek** [comment]
note the Section Vs unit type
and property Vs function and procedure

langmap used: https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/Ctags.java#L167
(unescape "\" before using)
and file used for test:
https://github.com/OpenGrok/OpenGrok/blob/master/testdata/sources/pascal/Sample.pas

I run something like:
./universal-ctags/ctags -f"-" --options=./ctags-pascal.options  Sample.pas

below for ref (it's a bit different from above, since I thought the matchers are bad, but truth is that selection of type on ctag side is bad)
```
 cat ./ctags-pascal.options
--fields=-anf+iKnS
--c-kinds=+l
--file-scope=yes
-u
--C++-kinds=+l
--langdef=pascal
--langmap=pascal:.pas
--regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*\([[:space:]]*[[:alnum:]_][[:space:]]*\)/\1/t,Type/
--regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*class[[:space:]]*[^;]*/\1/c,Class/
--regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*interface[[:space:]]*[^;]*/\1/c,interface/
--regex-pascal=/^constructor[[:space:]]+([a-zA-Z0-9_]+(<[a-zA-Z0-9_,]+>)?\.)([a-zA-Z0-9_<>,]+)[[:space:]]*/\1\3/n,Constructor/
--regex-pascal=/^destructor[[:space:]]+([a-zA-Z0-9_]+(<[a-zA-Z0-9_,]+>)?\.)([a-zA-Z0-9_<>,]+)[[:space:]]*/\1\3/d,Destructor/
--regex-pascal=/^procedure[[:space:]]+[a-zA-Z0-9_<>,]+\.([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/m,procedure/
--regex-pascal=/^function[[:space:]]+[a-zA-Z0-9_<>,]+\.([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/m,function/
--regex-pascal=/property[[:space:]]+([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/m,property/
--regex-pascal=/(uses|interface|implementation)[[:space:]]*/\1/s,Section/
--regex-pascal=/unit[[:space:]]+([a-zA-Z0-9_<>,][a-zA-Z0-9_<>, ]+)[;(]/\1/s,unit/
```

**Comment by masatake** [comment]
u-ctags doesn't allow using the same letter for different log names.
I introduced this rule. 

```
m,procedure
m,function
m,property
```

Now I know I did wrong. However, I would like to hear why you use `m` for 3 different kinds?

The same comment is applicable to `interface` and `class`.
The same comment is applicable to `section` and `unit`, too.

Let's use different kind letters for different things. This is the basic rule.

The exception is that a parser has too many (> 26 * 2) kinds.
The current u-ctags cannot handle this situation. However, I think this is a different topic.

**Comment by tarzanek** [comment]
hmm, nice
so just using proper kind gets this working properly

so for my situation with this pascal analyzer fixing kinds is perhaps the easiest thing to do

Do you have some list of kinds ?
(longer than in https://github.com/universal-ctags/ctags/blob/master/docs/format.rst#proposal ?)
Or one can assign whatever label to a kind?
How can you create more than 26*2 kinds? I thought there are just 25 alphabet letters, anything else can be used too?

**Comment by tarzanek** [comment]
fwiw - will you be restoring previous behaviour? (or it makes no sense and kind letter label should be strictly not overriden?)

**Comment by masatake** [comment]
A parser is the namespace of the kind letters. So you can assign any letter in your pascal parser.
There is one exception: dont ues `F`. It is reserved since Exuberant-ctags. 

> How can you create more than 26*2 kinds? I thought there are just 25 alphabet letters, anything else can be used too?

I recommend you to use a lettern in [A-EG-Z][a-z].  As far as I can remember Universal-ctags doesn't force this rule to parsers. However, I'm afraid that client tools reading tags don't work well with the other letters. 

Anyway, 26*2 -1 is enough for the pascal parser. I think this limitation will be an issue only on lisp family.

> fwiw - will you be restoring previous behaviour? (or it makes no sense and kind letter label should be strictly not overriden?)

I wonder why you want to use the same letter for different language objects.

You are using `c` for `class` and `interface`. I wonder why you want to use `c` for both; class and interface is different things.

My guessing is that you wan to control enabling and disabling the both kind(class and interface) with `c` letter.  I can call it as grouping class and interface kinds with `c`. This is an interesting idea. However, I think ctags should not do such rich things. The command line interface of Universal-ctags is already too complex. Such a control using `c` should be done in caller side.

This is my current thought. Do I make sense?

**Comment by masatake** [comment]
BUT, if ctags detects a letter overriden, ctags should make a warning.

**Comment by tarzanek** [comment]
yes, I agree with the warning, that makes sense
regarding the pascal parser - I merely fixing it so it works with uctags ;)
so I didn't have any intentions with it, original author did (albeit his tests were not that big as my farm and didn't catch this)
so yes, warning is definitely something to move over the legacy of exuberant ctags

**Comment by masatake** [comment]
... you are not the special.

In serefpolicy-3.13.1/Makefile I found:

```
$(tags):
	@($(CTAGS) --version | grep -q Exuberant) || (echo ERROR: Need exuberant-ctags to function!; exit 1)
	@LC_ALL=C $(CTAGS) -f $(tags) --langdef=te --langmap=te:..te.if.spt \
	 --regex-te='/^type[ \t]+(\w+)(,|;)/\1/t,type/' \
	 --regex-te='/^typealias[ \t]+\w+[ \t+]+alias[ \t]+(\w+);/\1/t,type/' \
	 --regex-te='/^attribute[ \t]+(\w+);/\1/a,attribute/' \
	 --regex-te='/^[ \t]*define\(`(\w+)/\1/d,define/' \
	 --regex-te='/^[ \t]*interface\(`(\w+)/\1/i,interface/' \
	 --regex-te='/^[ \t]*template\(`(\w+)/\1/i,template/' \
...
```
`i` is used both in interface and template.

**Comment by masatake** [comment]
I guess these misuse ( from u-uctags standpoint) are popular...

**Comment by masatake** [comment]
Letters or long names(strings), I wonder which should be used as primary identifiers for kinds.
In historical reason, I chose the letters. However, extensible languages like lisp may need many kinds(lambda (n) (> n (- (* 26 2) 1))). In such case long names will be better.

I would like to think this in u-ctags 7.0.

**Comment by tarzanek** [comment]
thank you @masatake !
