### ISSUE TITLE
Python: use getInputLineNumber()?

### ISSUE THREAD

**Issue by b4n** [universal-ctags/ctags#1063]
The new parser uses `getSourceLineNumber()`, but the old used `getInputLineNumber()`, maybe it should be changed? (although I don't think it can have any actual effect on Python)

**Comment by masatake** [comment]
Yes, you should use getInputLineNumber.


The difference between "Input" and "Source" is written in
http://docs.ctags.io/en/latest/internal.html#inputfile-type-and-the-functions-of-input-group

"Source" is used when parsing a file generated by a tool like c preprocessor.
It is nothing todo with python.
