### ISSUE TITLE
no tags for exported variables in JavaScript ES6 code

### ISSUE THREAD

**Issue by hoschi** [universal-ctags/ctags#1068]
Example code:

```
let localLet = "";
function localFunction () {

}
export let namedExport = {};
export function functionExport () {

}

let defaultExport = {};
export default defaultExport;
```

Generated tags file:

```
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL       https://ctags.io/       /official site/
!_TAG_PROGRAM_VERSION   0.0.0   /e7cdc72/
localFunction   test.js /^function localFunction () {$/;"       f
localLet        test.js /^let localLet = "";$/;"        v
```

I expect to get tags also for:
- namedExport
- functionExport
- defaultExport

**Comment by masatake** [comment]
(It seems that u-ctags has not supported ES6 yet. Any volunteers are welcome:)

This is a workaround:

```
diff --git a/parsers/jscript.c b/parsers/jscript.c
index 7540205..1336dfe 100644
--- a/parsers/jscript.c
+++ b/parsers/jscript.c
@@ -71,7 +71,9 @@ typedef enum eKeywordId {
 	KEYWORD_catch,
 	KEYWORD_finally,
 	KEYWORD_sap,
-	KEYWORD_return
+	KEYWORD_return,
+	KEYWORD_default,
+	KEYWORD_export,	
 } keywordId;
 
 typedef enum eTokenType {
@@ -158,7 +160,9 @@ static const keywordTable JsKeywordTable [] = {
 	{ "catch",		KEYWORD_catch				},
 	{ "finally",	KEYWORD_finally				},
 	{ "sap",	    KEYWORD_sap    				},
-	{ "return",		KEYWORD_return				}
+	{ "return",		KEYWORD_return				},
+	{ "default",		KEYWORD_default				},
+	{ "export",		KEYWORD_export				},	
 };
 
 /*
@@ -1940,6 +1944,10 @@ static void parseJsFile (tokenInfo *const token)
 	{
 		readToken (token);
 
+		if (isType (token, TOKEN_KEYWORD)
+		    && (token->keyword == KEYWORD_default || token->keyword == KEYWORD_export))
+			continue;
+
 		if (isType (token, TOKEN_KEYWORD) && token->keyword == KEYWORD_function)
 			parseFunction (token);
 		else if (isType (token, TOKEN_KEYWORD) && token->keyword == KEYWORD_sap)
```

**Comment by hoschi** [comment]
> It seems that u-ctags has not supported ES6 yet. Any volunteers are welcome

Perhaps it is a good idea to create a list with all not supported cases, so people have a better overview what needs to be fixed for ES6 support. If you can/willing to include other projects as language parsers, you can checkout https://github.com/ramitos/jsctags for JavaScript. I come to this project when researching for an alternative which fixes ramitos/jsctags#45 ;)

**Comment by masatake** [comment]
Though jsctags is interesting, I would like to maintain the ctags built-in javascript parser.
That doesn't mean I don't have interest in jsctags.

> Perhaps it is a good idea to create a list with all not supported cases, so people have a better overview what needs to be fixed for ES6 support. 

We have a good way to make the list. Could you look at http://docs.ctags.io/en/latest/units.html ? 
`*.b` test cases are for filing bugs. If you are interested in filing bugs, I will show an example based on this (your) bug report.  You can add more test cases related to ES6.

>  If you can/willing to include other projects as language parsers, you can checkout https://github.com/ramitos/jsctags for JavaScript. I come to this project when researching for an alternative which fixes ramitos/jsctags#45 ;)

This is also interesting. Do you know universal-ctags has a facility for running an external tag generator called xcmd ?  If you don't know, look at http://docs.ctags.io/en/latest/xcmd.html?highlight=xcmd

Basically in the current implementation u-ctags cannot utilize jsctags well because it conflicts with the built-in javascript parser.

The situation is very similar to ruby.
https://github.com/universal-ctags/ctags/issues/408

Ctags has a built-in ruby parser. Ripper-tags is an external tag generator.
Ripper-tags generates better tags for ruby input. So people may want to use ripper-tags as a xcmd.
However, they are conflicted.

I know what I should do for solving it. We should provide the way to "langauge" and "parser".
Currently these two are not distinguished in ctags implementation. If they are separated, we can 
do "Using ripper-tags *parser* for parsing input file written in ruby *language*".

About java script we can do both "Using built-in javascript parser for parsing input file written in Javascript language" and "Using jsctags external javascript parser for parsing input file written in
Javascript language".  I call this parser/language binding. I would like to do this in version 1.5.

Even i we use jsctags, the test cases are still very useful.

**Comment by masatake** [comment]
I looked at  ramitos/jsctags#45.

Basically ctags(family) captures definitions. 

```
import {foo, bar} from './myModule';
```

Here foo and bar are not definitions. The definitions of foo and bar may be in myModule.
In universal-ctags these foo and bar are called references. Though not used widely, universal-ctags has ability to capture reference tags. See http://docs.ctags.io/en/latest/news.html#reference-tags .
Actually built-in python parser can capture these import lines:

```
[yamato@x201]~/var/ctags-github% cat /tmp/foo.py
import x,y from z

[yamato@x201]~/var/ctags-github% ./ctags -o - --extra=+r --fields=+rK /tmp/foo.py
x	/tmp/foo.py	/^import x,y from z$/;"	module	role:imported
y	/tmp/foo.py	/^import x,y from z$/;"	module	role:imported
```

**Comment by hoschi** [comment]
> If you are interested in filing bugs, I will show an example based on this (your) bug report. You can add more test cases related to ES6.

I'm interessted to get tags for ES6 code, so I'm interessted in contributing to this project. I try to make a failing test for my bug report and see if I could it get to work without an example, the docs are pretty good :+1: 
After this, I would check the current ES6 tests (`const` already works, I saw) and add more tests for things not working yet.

> This is also interesting. Do you know universal-ctags has a facility for running an external tag generator called xcmd ?

Interesting, not saw this before. However, I would prefer the built-in JS parser of u-tags, because it is *a lot* faster than jsctags. jsctags uses tern-js to gather more information, but this is nothing I trade with performance.

> Here foo and bar are not definitions. The definitions of foo and bar may be in myModule.

This is also what I thought.

**Comment by b4n** [comment]
According to MDN (https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export) export is basically unsupported, even if in ES6.
Indeed, neither `gjs` (Mozilla's) nor `nodejs` seem to understand the `export` keyword, which makes writing a *valid* test case harder.  What do you use that does understand this properly?

**Comment by hoschi** [comment]
> export is basically unsupported, even if in ES6

It is in the spec: http://www.ecma-international.org/ecma-262/6.0/#sec-exports
I use babel at my project, because its a web project.

**Comment by b4n** [comment]
If we just want to avoid getting confused by exports and not do something special with them, we can use a variant on @masatake's like 2dc78f1b974f438fcaec12d63e9c2adaccc39969

**Comment by masatake** [comment]
@b4n, where can I get the branch(?) which includes 48df535?
It seems that you are using git's feature that I don't know.

**Comment by b4n** [comment]
> @b4n, where can I get the branch(?) which includes 48df535?

https://github.com/b4n/fishman-ctags/commits/jscript/es7
I can make a PR, too.  It doesn't yet include most ES6/7 features that would be good to support (e.g. classes syntax), but it includes that one.

> It seems that you are using git's feature that I don't know.

What do you mean?

**Comment by masatake** [comment]
Oh, I see. The commit is on your repository.
When I clicked the link `48df535`, a page on `https://github.com/universal-ctags/ctags/` is opend. So
I thought you merged  your commit to our(universal-ctags) repository. However, I could not find your change in `git log` of our repository after `git pull`. So I wondered why and I guessed you used  git's feature that I don't know.

I would like to make  the PR.

**Comment by Aaronik** [comment]
For anyone in the future coming here looking for es6 support for ctags, which will be happening more and more as es6 becomes more normalized and widely adopted, consider using https://github.com/okcompute/es-ctags ([npm es-ctags](https://www.npmjs.com/package/es-ctags)), which works out of the box for me.
