### ISSUE TITLE
Incompatible behavior: "typeref" field of C

### ISSUE THREAD

**Issue by htfy96** [universal-ctags/ctags#1082]
### Source`test.c`

``` c
static int f(int x) { return 42; }
static bool wakeup_spi = false;
```
### Universal Ctags result

``` tags
f   test.c  /^static int f(int x) { return 42; }$/;"    f   typeref:typename:int    file:
wakeup_spi  /tmp/test-spi.c /^  static bool wakeup_spi = false;$/;" v   typeref:typename:bool   file:
```
#### Version

```
Universal Ctags 0.0.0(c984455), Copyright (C) 2015 Universal Ctags Team
```
### Exuberant Ctags result

``` tags
f   test.c  /^static int f(int x) { return 42; }$/;"    f   file:
wakeup_spi  /tmp/test-spi.c /^  static bool wakeup_spi = false;$/;" v   file:
```
## Expected behavior

According to man page of Universal Ctags and Exuberant Ctags:

> t   Type and name of a variable or typedef as "typeref:" field [enabled]

It seems that both the two forks don't conform to man page:
-  Exuberant Ctags only prints this field for definition of variable of struct type
-  Universal Ctags even prints it for functions

**Comment by masatake** [comment]
Related to https://github.com/universal-ctags/ctags/issues/862 .
Maybe we should decide the meaning of fields and update the man page.
