### ISSUE TITLE
Add JSX support

### ISSUE THREAD

**Issue by Wilfred** [universal-ctags/ctags#1086]
JSX is a variant of JS that looks like this:

```jsx
var CommentBox = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        Hello, world! I am a CommentBox.
      </div>
    );
  }
});
ReactDOM.render(
  <CommentBox />,
  document.getElementById('content')
);
```

Documentation is here: https://facebook.github.io/jsx/ and files typically have a .jsx extension.

ctags could probably get away with just treating .jsx files as .js files.

**Comment by Wilfred** [comment]
Yep, adding ` --map-javascript=.jsx` seems to pick up function definitions in JSX files.

**Comment by masatake** [comment]
Does `http://jsx.github.io/` tell the same language as you are talking about?

**Comment by dkearns** [comment]
@masatake, not it's this one: https://facebook.github.io/react/docs/jsx-in-depth.html

**Comment by masatake** [comment]
I am wondering just adding "jsx" to the extension list is enough or not...

**Comment by Wilfred** [comment]
It worked when I tested it.

JSX lets you define literals using `<Foo>`, which gets desugared to `React.createElement(Foo, null);`. JSX files still contain normal JS function definitions, so I think the patch in #1087 is sufficient.

**Comment by zerubeus** [comment]
hey can please add tsx as well :)

**Comment by radiantshaw** [comment]
@zerubeus `--map-typescript=.tsx` does the job for me.
