### ISSUE TITLE
c++ destructor appears in class definition list.

### ISSUE THREAD

**Issue by amosbird** [universal-ctags/ctags#1096]
When doing go to definition over a class name, its destructor is also listed in the jump list. Is it a corner case of c++ parser or do I use it wrong?

**Comment by masatake** [comment]
I'm bad in C++ so could you tell me more with an example.

```
[jet@localhost tmp]$ cat /tmp/foo.cpp 
class A
{
  int i;
  A();
  ~A();
};

A::A()
{
  i = 0;
}

A::~A()
{
  i = 0;
}
[jet@localhost tmp]$ ~/var/ctags/ctags --fields=+K  -o - foo.cpp 
A	foo.cpp	/^A::A()$/;"	function	class:A
A	foo.cpp	/^class A$/;"	class	file:
i	foo.cpp	/^  int i;$/;"	member	class:A	typeref:typename:int	file:
~A	foo.cpp	/^A::~A()$/;"	function	class:A
```

In my knowledge of C++, `~A` is a destructor. As you wrote,  the destructor is tagged.
Do you mean this is wrong behaviour?

**Comment by amosbird** [comment]
I mean like this ![](https://ptpb.pw/f1HP.jpg)

I expect action `GoTo class Coordinator` should be done unambigously, however the destructor also shows up in the result list.

**Comment by masatake** [comment]
@amosbird, thank you.

It seems that you are using a frontend(a client tool) which reads tags file generated by ctags.
ctags maintained here is a low level tool. It just tags *names* as much as possible and records them into tags file. Basically ctags should be stupid. Intelligence like hiding destructor in the name list from users should be in  client tools.

So I would like to say the issue you reported here is not issue of Universal-ctags. Rather I would like to say it is issue of the client tool. So I would like you to contact the developer community of the client tool.



It is better that Universal-ctags provides enough information to client tools. About this issue, it is better that Universal-ctags provides the way to distinguish whether a name specifies a destructor or not to
the client tool you are using.

I think it is not difficult with following algorithm: if a name includes character `~` and its language is C++, we can say the name specifies a destructor.

**Comment by amosbird** [comment]
@masatake yes, I was thinking the same. The client tool I'm using is gnu global. I will submit an issue there.

**Comment by masatake** [comment]
Feel free to reopen this.
