### ISSUE TITLE
javascript: NULL tag warning

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#1099]
This corresponds to this Geany issue:

https://github.com/geany/geany/issues/357

and can be reproduced with the input here:

http://pastebin.com/Cbc73X0V

I investigated a bit and it looks to be caused by 'name' token getting copied here

https://github.com/universal-ctags/ctags/blob/master/parsers/jscript.c#L1355

without any check whether it's actually an identifier so it can be a completely different token with empty string which is then passed to makeClassTag() and generates the warning.

**Comment by techee** [comment]
Eh, forget about it, it's fixed in universal-ctags here:

https://github.com/universal-ctags/ctags/blob/master/parsers/jscript.c#L1412

we just don't have it in Geany.

**Comment by masatake** [comment]
I'm very sorry that I don't report this to geany project.
However, it is hard for me to track both project.

**Comment by techee** [comment]
No need to be sorry, it's our task to get the parsers and ctags in sync (we are slowly working on a complete sync).
