### ISSUE TITLE
rspec describe blocks whose titles include `:` are not discovered

### ISSUE THREAD

**Issue by NewAlexandria** [universal-ctags/ctags#11]
[The matcher for describe blocks](https://github.com/fishman/ctags/blob/f692e3ba6c52aa8cd35d3aaed9af41e039030119/ruby.c#L192) is imprecise.  

Including a `:` in this list causes other errors (incorrect nesting).  I tested this by rebuilding with such a change.  Probably a regex matcher is needed somewhere.

Pardon I didn't research further.

**Comment by masatake** [comment]
In the list `:` is not included.

**Comment by masatake** [comment]
Now I understand what you mean.

**Comment by NewAlexandria** [comment]
Thank you

**Comment by masatake** [comment]
RSpec parser is remiplemented as a regex based subparser running on Ruby base parser.
If the issue is still reproduced, reopen this with an example input.
