### ISSUE TITLE
make units VG=1 not interruptable

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#1100]
When running

```
make units VG=1
```

one cannot stop its execution by pressing Ctrl+C and there doesn't seem to be any way (except for looking at processes which run and killing them) to stop its execution.

**Comment by masatake** [comment]
@techee, could you try the change I submitted in #1106 ?

**Comment by techee** [comment]
@masatake Seems to work great, thanks!

**Comment by masatake** [comment]
Thank you for testing.
