### ISSUE TITLE
Python: "member" kind vs. "method"

### ISSUE THREAD

**Issue by blueyed** [universal-ctags/ctags#1101]
With the Python parser, `K_METHOD` is used for class methods only (https://github.com/universal-ctags/ctags/blob/55d068620ed8f74c8e706cb7fbaeab78dcd0fc69/parsers/python.c#L243-L245).

It is referred / mapped to as 'member' though (https://github.com/universal-ctags/ctags/blob/55d068620ed8f74c8e706cb7fbaeab78dcd0fc69/parsers/python.c#L127).

Whereas non-function class members are referred to as "variables".

This seems to have changed recently (probably with the big refactor of the Python parser), since I used to exclude the "v" kind (which referred to local variables then before probably)?!

Also the long description for "variables" should be "class variables" to make it clearer.
I suggest changing the "member" in `PythonKinds` to "method" / "class method".

**Comment by blueyed** [comment]
How does universal-ctags' list of kinds compare to Exuberant ctags' list here?

**Comment by b4n** [comment]
> This seems to have changed recently (probably with the big refactor of the Python parser), since I used to exclude the "v" kind (which referred to local variables then before probably)?!

I'm not totally sure, but it's very possible that all variables were tagged as `variable`, where now there's a distinction between `variable` and `local`.  However, `local` is disabled by default.

> Also the long description for "variables" should be "class variables" to make it clearer.

Mmmyeah, but it's also used for root variables AFAIK, isn't it?

> I suggest changing the "member" in `PythonKinds` to "method" / "class method".

Wile it sounds better indeed, I didn't do it because it changes the kinds for not much reason (as `member` is the old name).

If we were to change all that, I'd suggest
 * `variable`: global variable
 * `member`: class variable
 * `local`: (function) local variable

**Comment by blueyed** [comment]
> I'm not totally sure, but it's very possible that all variables were tagged as `variable`, where now there's a distinction between `variable` and `local`.  However, `local` is disabled by default.

Ok.

>> Also the long description for "variables" should be "class variables" to make it clearer.

> Mmmyeah, but it's also used for root variables AFAIK, isn't it?

Ah, forgot about that.

> If we were to change all that, I'd suggest
 * `variable`: global variable
 * `member`: class variable
 * `local`: (function) local variable

Makes sense.  But let's then not change it for now, since it will break the API for no good reason.

**Comment by blueyed** [comment]
FWIW: exuberant-ctags has:
```
c  classes
f  functions
m  class members
v  variables
i  imports
```

Where we have:
```
c  classes
f  functions
m  class members
v  variables
I  name referring a module defined in other file
x  name referring a class/variable/function/module defined in other module
z  function parameters [off]
l  local variables [off]
```

The `i` for imports is `referenceOnly` here: https://github.com/universal-ctags/ctags/blob/b373af2299c4690075265bf0b751ba49c3ea26fb/parsers/python.c#L130-L131.

So with universal-ctags a `from os import path` is not reflected in the output, while it is with exuberant-ctags:
```
path  t.py  /^from os import path$/;" i language:Python
```
