### ISSUE TITLE
Pass --tag-relative to coffeetags

### ISSUE THREAD

**Issue by maxnordlund** [universal-ctags/ctags#1122]
Hi, I have a setup for automatically run ctags on changes in my git repos and I use the multiple worktree setup, which means that the files (including the TAGS file) live somewhere else.

For normal tags it works just fine, but for the coffeescript tags it points into oblivion. After a bit of digging, I realized that the --tag-relative flag wasn't propagated to coffeetags (which supports it). It would be pretty handy if it did though.

**Comment by masatake** [comment]
@maxnordlund, thank you for reporting. I have nerver thought about this.
I will take a look at this.

**Comment by masatake** [comment]
Could you try following patch?

```
diff --git a/main/lxcmd.c b/main/lxcmd.c
index 328f896..d47a37c 100644
--- a/main/lxcmd.c
+++ b/main/lxcmd.c
@@ -1167,6 +1167,8 @@ static boolean invokeXcmdPath (const char* const fileName, xcmdPath* path, const
                        if (parseXcmdPath (line, path, &entry) )
                        {
                                entryAddField (&entry, "language", getLanguageName (language));
+                               entry.file = getInputFileTagPath ();
+
                                if (makeTagEntryFromTagEntry (path, &entry))
                                        result = TRUE;
                                freeTagEntry (&entry);
```

Do you use coffeescript? As far as I can remember this is the first bug report about xcmd.

**Comment by maxnordlund** [comment]
Yes I do use CoffeeScript at work. I'm using homebrew, so how do I apply that patch?

**Comment by masatake** [comment]
> Yes I do use CoffeeScript at work.
You may be the first REAL user of xcmd :-P.

> I'm using homebrew, so how do I apply that patch?

O.k.  I will merge this patch to the official source tree. Please, wait for awhile.

**Comment by maxnordlund** [comment]
I just tested this on my machine, and it works beautifully, thanks 😸
