### ISSUE TITLE
Include line in excmd to help Vim with duplicate patterns

### ISSUE THREAD

**Issue by blueyed** [universal-ctags/ctags#1125]
See https://github.com/vim/vim/issues/1057.

I could imagine that the output could contain the line number in the excmd (to go there before searching for the pattern), when using `--excmd=pattern` or `--excmd=mix`.

What do you think?

**Comment by masatake** [comment]
How about this one?
```
[yamato@x201]~/var/ctags-github% ./ctags -o - -x --_xformat='%{name}    ${input}        %{line};%{pattern};"    %k' main/main.c | head
CLOCKS_PER_SEC	${input}	360;/^#  define CLOCKS_PER_SEC	/;"	d
CLOCKS_PER_SEC	${input}	364;/^# define CLOCKS_PER_SEC	/;"	d
CLOCK_AVAILABLE	${input}	358;/^# define CLOCK_AVAILABLE$/;"	d
CLOCK_AVAILABLE	${input}	363;/^# define CLOCK_AVAILABLE$/;"	d
Totals	${input}	87;/^static struct { long files, lines, bytes; } Totals = { 0, 0, 0 };$/;"	v
__anonae81ef0f0108	${input}	87;/^static struct { long files, lines, bytes; } Totals = { 0, 0, 0 };$/;"	s
addTotals	${input}	100;/^extern void addTotals ($/;"	f
batchMakeTags	${input}	436;/^static void batchMakeTags (cookedArgs *args, void *user CTAGS_ATTR_UNUSED)$/;"	f
bytes	${input}	87;/^static struct { long files, lines, bytes; } Totals = { 0, 0, 0 };$/;"	m
clock	${input}	365;/^static clock_t clock (void)$/;"	f
```

**Comment by blueyed** [comment]
Nice.
But the line needs to be decremented by 1 AFAICS:

> 	1;/that		the first line after line 1 containing "that"

**Comment by masatake** [comment]
I may have to add `%{lineMinusOne}` field.

**Comment by masatake** [comment]
See also #774.

**Comment by masatake** [comment]
I think I should add --excmd=both.

**Comment by sshsu** [comment]
> See and try -excmd=combined introduced in #1959.
> How do you think the name "combined"? "combine" is better?

I think combined is ok, it is consistent with option "mixed" , right?

**Comment by blueyed** [comment]
@masatake 
Thank you very much, it works great!
