### ISSUE TITLE
ctags crashes on a UTF-16 (big endian, with signature (BOM)) encoded file

### ISSUE THREAD

**Issue by legends2k** [universal-ctags/ctags#1135]
`ctags -e --verbose temp.cpp` crashes when `temp.cpp` is a

> utf-16be-with-signature-dos (alias: utf-16-be-dos)

Here's the verbose output:

```
Reading command line arguments
Get file language for temp.cpp
        pattern: temp.cpp
                #candidates: 1
                        0: C++ (extension: "cpp")
                #candidates after sorting and filtering: 1
                        0: C++ (extension: "cpp")
OPENING temp.cpp as C++ language file
Initialize parser: C++
```

**Comment by masatake** [comment]
Can we get the `temp.cpp` ?

**Comment by legends2k** [comment]
```

void hello()
{
}
```

is the contents of the file. GitHub doesn't allow it to be attached.  However, I noticed that two things silences the issue:

* Removing the first empty line
* Not passing the `-e` option

**Comment by masatake** [comment]
```
[yamato@x201]~/var/ctags-github% ./ctags --version
./ctags --version
Universal Ctags 0.0.0(c21fa6d), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 20 2016, 21:02:37
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc, +xpath, +json
[yamato@x201]~/var/ctags-github% hexdump -c /tmp/foo.cpp 
hexdump -c /tmp/foo.cpp 
0000000 376 377  \0  \r  \0  \n  \0   v  \0   o  \0   i  \0   d  \0    
0000010  \0   h  \0   e  \0   l  \0   l  \0   o  \0   (  \0   )  \0  \r
0000020  \0  \n  \0   {  \0  \r  \0  \n  \0   }  \0  \r  \0  \n        
000002e
[yamato@x201]~/var/ctags-github% ./ctags -e /tmp/foo.cpp
./ctags -e /tmp/foo.cpp
[yamato@x201]~/var/ctags-github% cat TAGS
cat TAGS

/tmp/foo.cpp,11
hello2,6
```

I cannot reproduce this issue with the above input.
Am I doing wrong?

**Comment by masatake** [comment]
Another representation of the same input:
```
[yamato@x201]~/var/ctags-github% od -A x -t x1z -v /tmp/foo.cpp 
od -A x -t x1z -v /tmp/foo.cpp 
000000 fe ff 00 0d 00 0a 00 76 00 6f 00 69 00 64 00 20  >.......v.o.i.d. <
000010 00 68 00 65 00 6c 00 6c 00 6f 00 28 00 29 00 0d  >.h.e.l.l.o.(.)..<
000020 00 0a 00 7b 00 0d 00 0a 00 7d 00 0d 00 0a        >...{.....}....<
00002e
```

**Comment by legends2k** [comment]
Here's the output of `ctags --version`

> Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
> Universal Ctags is derived from Exuberant Ctags.
> Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
>   Compiled: Sep 17 2016, 12:02:54
>   URL: https://ctags.io/
>   Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +multibyte

I took it from the [daily builds](https://ci.appveyor.com/project/masatake/ctags/branch/master/job/44lgb12fkt9eon6a/artifacts) on 19th September; the filename was `ctags-c21fa6d-x64.zip`.

Here's `temp.cpp` in hex:

> 00000000: feff 000d 000a 0076 006f 0069 0064 0020  .......v.o.i.d. 
> 00000010: 0068 0065 006c 006c 006f 0028 0029 000d  .h.e.l.l.o.(.)..
> 00000020: 000a 007b 000d 000a 007d 000d 000a       ...{.....}....

**Comment by masatake** [comment]
It seems that the input files are identical.  The crash is not reproduced.
However, valgrind detects an invalid memory access.

Following patch may solve the issue.

```
diff --git a/main/entry.c b/main/entry.c
index cd76add..0b547ec 100644
--- a/main/entry.c
+++ b/main/entry.c
@@ -836,7 +836,7 @@ extern int   makePatternStringCommon (const tagEntryInfo *const tag,
 
        line_len = strlen (line);
        searchChar = Option.backward ? '?' : '/';
-       terminator = (boolean) (line [line_len - 1] == '\n') ? "$": "";
+       terminator = (boolean) ((line_len == 0) || (line [line_len - 1] == '\n')) ? "$": "";
 
        if (!tag->truncateLine)
        {
diff --git a/main/output-etags.c b/main/output-etags.c
index 0c242bf..8ea65a9 100644
--- a/main/output-etags.c
+++ b/main/output-etags.c
@@ -96,7 +96,11 @@ static int writeEtagsEntry (MIO * mio, const tagEntryInfo *const tag, void *data
                if (tag->truncateLine)
                        truncateTagLine (line, tag->name, TRUE);
                else
-                       line [strlen (line) - 1] = '\0';
+                       {
+                               size_t len = strlen (line);
+                               if (len > 0)
+                                       line [len - 1] = '\0';
+                       }
 
                length = mio_printf (mio, "%s\177%s\001%lu,%ld\n", line,
                                tag->name, tag->lineNumber, seekValue);
```

I will merge this in soon. Though this will not be the ideal solution but removing this kind of crash is very important.

BTW, utf-16 is never supported in universal-ctags. We are still be in the world where the assumption  byte == char is valid. HOWEVER, universal-ctags should not crash for any (broken) input.

**Comment by masatake** [comment]
I'm working on testing the patch now. Please ,wait for awhile.

**Comment by masatake** [comment]
It passes the most of all test cases. I'm afraid this change may conflict with #1091. #1091also deals with nul char. It taks more time to fix.

**Comment by masatake** [comment]
@legends2k, sorry to be late.
Could you try the latest code?
Merging #1091 solves this in another way.

**Comment by legends2k** [comment]
I tried the exercise on [`ctags-ff6491f-x64`](https://ci.appveyor.com/project/masatake/ctags/branch/master/job/va0flv682ok8jvx9/artifacts) and the issue is irreproducible, I guess it's fixed now.

Sorry for the delayed reply, I couldn't get to it earlier.  Thanks!
