### ISSUE TITLE
C: attribute after array definition

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1145]
```
struct fb_info *registered_fb[FB_MAX] __read_mostly;
```

Above code is in linux kernel. `registered_fb` is not captured.
If I delete __read_mostly from the input, it is captured.

For ths input even OldC parser doesn't work expectedly.

**Comment by pragmaware** [comment]
Well... if __read_mostly is treated as generic identifier then this is basically a syntax error.
Should we add support for the non-standard attribute extensions?
https://www.daemon-systems.org/man/__read_mostly.3.html

**Comment by codebrainz** [comment]
Identifiers starting with double-underscore are still valid, they are just reserved for the implementation. I guess if one wanted tags for an implementation (ex. glibc, libstdc++, etc), stripping them wouldn't be good. Often they won't appear in headers (ex. compiler intrinsics) but if they do should probably not be removed by default, IMO.

**Comment by b4n** [comment]
If the attributes are common enough, we might want stock support for them.  But OTOH, it should be trivial to just ignore them with appropriate ignore tokens, so maybe we should provide default ignore patterns at most.

**Comment by pragmaware** [comment]
Well, I was talking only about the specific tokens listed in that man page, not all the tokens starting with a double underscore. However it makes sense to handle them explicitly only if we want to extract some semantic information.. say "noinline", "packed" or "aligned". If we don't care about this information then ignoring them could be a good solution.
How we could provide a default set of ignore patterns? Hardcoded in source? Or a default configuration file?

**Comment by masatake** [comment]
> Well, I was talking only about the specific tokens listed in that man page, not all the tokens starting with a double underscore. However it makes sense to handle them explicitly only if we want to extract some semantic information.

Yes! My interest is ELF section information like:
```
static void __attribute__((section(".inittext"))) serial_putchar(int ch)
{
```
Attaching  ".inittext" of section field of "serial_putchar" is very helpful for me:-P
However, it is obviously overkill.

> How we could provide a default set of ignore patterns? Hardcoded in source? Or a default configuration file?

Temporary, hardcoding is enough for me.
As I wrote before, we can do more interesting thins when we introduce mechanism  to define per-parser options.

**Comment by masatake** [comment]
@pragmaware, do you think about using isIgnoreToken?
The backend of the function is stringList. If many items are added to the stringList, we should replace it with a hashTable.

**Comment by pragmaware** [comment]
Well, if we're using ignore lists then isIgnoreToken() is the way.
The other way is to hardcode the tokens as keywords and handle them specially.

As for the string list, yes, the current implementation is quite inefficient. A hash table would be useful.
isIgnoreToken() could also take a vString pointer instead of const char * to avoid computing lengths.

**Comment by masatake** [comment]
Don't main/htable.[ch] help you?

I'm thinking about code generated by gperf as backend of main/htable.[ch].

(gperf can be used as backend for keyword.[ch], too.)

**Comment by pragmaware** [comment]
@masatake does htable handle hash collisions?

**Comment by masatake** [comment]
@pragmaware, I implemented `Separate chaining` technique. I think you expect Open addressing.
https://en.wikipedia.org/wiki/Hash_table#Collision_resolution

As far as rading quickly keyword.c does t he same of mine. I found `->next` field in the hash buacket.

If you are talking about a bug of imy implementation, give me a pull request.

**Comment by pragmaware** [comment]
Ah.. blind me... must have been too tired. Now I see.
So I almost have a pull request replacing the ignore string list with your htable then :)

**Comment by pragmaware** [comment]
See #1154.

**Comment by pragmaware** [comment]
See #1154

**Comment by masatake** [comment]
In the future we can have just another htable for handling attributes.
Why not now?  Heavy users may want to add extra attributes to the htable.
However, ctags command doesn't provide interface for adding.

We need `--opt-C=+ignore-macro:MACRO` and  `--opt-C=+ignore-attribute:ATTR`.

...Let's not talk about the things in future now. The release is already enough delayed.

**Comment by masatake** [comment]
NOTE: systemd users gperf. It uses automake, too.

**Comment by masatake** [comment]
@b4n wrote:
> If the attributes are common enough, we might want stock support for them. But OTOH, it should be trivial to just ignore them with appropriate ignore tokens, so maybe we should provide default ignore patterns at most. 

I implemented this idea: See #1190.

**Comment by b4n** [comment]
@masatake hum, IIUC #1190 is not really what I was suggesting.  My point was to simply have a default set for the `-I` option, so that there is no need for extra code.

Like that:
```console
$ cat /tmp/arrattr.c
struct fb_info *registered_fb1[FB_MAX] __read_mostly;
struct fb_info *registered_fb2[FB_MAX] __read_mostly X;
struct fb_info *registered_fb4[FB_MAX] __read_mostly X Y(1, 2);
struct fb_info *registered_fb5[FB_MAX] __read_mostly X Y(1, 2), fb6[3] _Z_;
$ cat /tmp/arrattr.ignore 
__read_mostly
X
Y+
_Z_
$ ./ctags -o - -I @/tmp/arrattr.ignore /tmp/arrattr.c
fb6	/tmp/arrattr.c	/^struct fb_info *registered_fb5[FB_MAX] __read_mostly X Y(1, 2), fb6[3] _Z_;$/;"	v	typeref:struct:fb_info * [][3]
registered_fb1	/tmp/arrattr.c	/^struct fb_info *registered_fb1[FB_MAX] __read_mostly;$/;"	v	typeref:struct:fb_info * []
registered_fb2	/tmp/arrattr.c	/^struct fb_info *registered_fb2[FB_MAX] __read_mostly X;$/;"	v	typeref:struct:fb_info * []
registered_fb4	/tmp/arrattr.c	/^struct fb_info *registered_fb4[FB_MAX] __read_mostly X Y(1, 2);$/;"	v	typeref:struct:fb_info * []
registered_fb5	/tmp/arrattr.c	/^struct fb_info *registered_fb5[FB_MAX] __read_mostly X Y(1, 2), fb6[3] _Z_;$/;"	v	typeref:struct:fb_info * []
```

**Comment by b4n** [comment]
…and if `__read_mostly` and other are common enough, include them in that default ignore list.

**Comment by masatake** [comment]
I misunderstood the comment. 
However, skipping them automatically is not so bad idea.

**Comment by masatake** [comment]
... I found following code in kernel build script:

```
exuberant()
{
        setup_regex exuberant asm c
        all_target_sources | xargs $1 -a                        \
        -I __initdata,__exitdata,__initconst,                   \
        -I __initdata_memblock                                  \
        -I __refdata,__attribute,__maybe_unused,__always_unused \
        -I __acquires,__releases,__deprecated                   \
        -I __read_mostly,__aligned,____cacheline_aligned        \
        -I ____cacheline_aligned_in_smp                         \
        -I __cacheline_aligned,__cacheline_aligned_in_smp       \
        -I ____cacheline_internodealigned_in_smp                \
        -I __used,__packed,__packed2__,__must_check,__must_hold \
        -I EXPORT_SYMBOL,EXPORT_SYMBOL_GPL,ACPI_EXPORT_SYMBOL   \
        -I DEFINE_TRACE,EXPORT_TRACEPOINT_SYMBOL,EXPORT_TRACEPOINT_SYMBOL_GPL \
        -I static,const                                         \
        --extra=+fq --c-kinds=+px --fields=+iaS --langmap=c:+.h \
        "${regex[@]}"

        setup_regex exuberant kconfig
        all_kconfigs | xargs $1 -a                              \
        --langdef=kconfig --language-force=kconfig "${regex[@]}"

}

```
