### ISSUE TITLE
main: parser programming interface (PPI)

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1146]
Currently `main/*.h` files are used from both main and parsers.
They should be separated. 

I would like to call what are declared in header files for parsrs "parser programmer interface (PPI)".

Though this separation is done yet but you can use the term for discussion. I hope this word help 
you to represent your idea about ctags.

An example of idea:

For parser programmers ctags main part is a software component provides PPI.
AND if geany provides PPI implementation, the parser may run on geany, too.

**Comment by codebrainz** [comment]
Might be better to call it "Parser Programming Interface" to mirror [Application Programming Interface](https://en.wikipedia.org/wiki/Application_programming_interface). Or even just "Parser API" since API is often used to mean "programming interface" generally.

**Comment by masatake** [comment]
`s/programmer/programming/`

@codebrainz, thank you.

**Comment by masatake** [comment]
I have the most of all header files to two categories: main part private and public to parsers.
The private ones have "_p" their file names. e.g. kind_p.h.
The next step is integrating to geany.
