### ISSUE TITLE
golang language reference tags

### ISSUE THREAD

**Issue by yanglimingcn** [universal-ctags/ctags#1176]
I can not found tags which reference one function
I use gnu global(global (GNU GLOBAL) 6.5.5) with universal-ctags backend
GTAGSLABEL=new-ctags
gtags.conf
new-ctags:\
	:tc=universal-ctags:tc=htags:

**Comment by masatake** [comment]
(Capturing reference tags, which global expects, has not been implmented in any langauge including go yet.)

**Comment by masatake** [comment]
We have no plan to implement reference tags for function (and method) calls in soon.
