### ISSUE TITLE
File-path separator bug on Windows when using '--tag-relative'

### ISSUE THREAD

**Issue by BohrShaw** [universal-ctags/ctags#1187]
In a git repository, issue two commands in Powershell:
`git ls-files | ctags -L - -f .git/tags --tag-relative`
`git ls-files | ctags -L - -f .git\tags --tag-relative`

The first generates a tags file containing wrong relative file paths, while the second works right.

**Comment by masatake** [comment]
I don't know well about Windows. Could you tell me the issue more?
As far as I know the backslash is used as file name separator on Windows.

**Comment by BohrShaw** [comment]
The tags file generated by the second command contains a line like:
`dp	../init.vim	/^pattern$/;"	m`
While by the first command, I get a wrong relative file path:
`dp	init.vim	/^pattern$/;"	m`

**Comment by b4n** [comment]
A wild guess is that we have specific Windows code that uses `\` as separator only, while it should allow both `\` and `/`.

**Comment by masatake** [comment]
```
/*
 *  Portability macros
 */
#ifndef PATH_SEPARATOR
# if defined (MSDOS_STYLE_PATH)
#  define PATH_SEPARATOR '\\'
# else
#  define PATH_SEPARATOR '/'
# endif
#endif

#if defined (MSDOS_STYLE_PATH) && defined (UNIX_PATH_SEPARATOR)
# define OUTPUT_PATH_SEPARATOR	'/'
#else
# define OUTPUT_PATH_SEPARATOR	PATH_SEPARATOR
#endif
```

ctags doesn't consider more than one separator char. These days, does windows deal both `\` and `/` as separators?

**Comment by b4n** [comment]
> These days, does windows deal both `\` and `/` as separators? 

Yes, they are synonyms AFAIK

**Comment by BohrShaw** [comment]
It's not convenient for me to play with C codes. If I get the time, I would:

1. Convert `\` to `/` upon input.
1. Only use `/` as the path-separator internally.
1. Output '/' preferably.

**Comment by masatake** [comment]
Sorry, the assignment is my mistake.

**Comment by masatake** [comment]
@BenWiederhake, could you tell me how do you build ctags?

**Comment by BenWiederhake** [comment]
I'm not related to this project.  Don't try to contact me again.

**Comment by masatake** [comment]
(@BenWiederhake, I'm very sorry.)

**Comment by masatake** [comment]
Please, reopen this if the latest code doesn't solve this.
