### ISSUE TITLE
Echo contents to stdout during debug

### ISSUE THREAD

**Issue by dfishburn** [universal-ctags/ctags#1206]
When I was developing with Exuberant tags I always used -D 9 on the command line which outputted the tags read to the window when readToken processed them.

This was extremely useful as I could quickly see where I was in the file before I got down to the right level to begin debugging.

I see in Universal Tags, the -D is now a macro.

I am running on Windows and compiled with:
`
nmake -f mk_mvc.mak DEBUG=1 ctags.exe
`

I can't see how to get the same information echoed to the screen while parsing.
Any suggestions?

Thanks,
David

**Comment by masatake** [comment]
I renamed -D option to -d option.
(See http://docs.ctags.io/en/latest/news.html#d-option)

I have been broken debugging facility because I didn't understand it well when I started working on this project.

However, C parser is completely rewritten by @pragmaware . 
What you are familiar with is now call OldC parser. As far as I know new C parser doesn't consider -d debug option. However, CXX_DEBUGGING_ENABLED flag in parsers/cxx/cxx_debug.h is available as a tuning knob. This is quite helpful for debugging the parser.

**Comment by dfishburn** [comment]
Thanks for the response.
```
$ ctags -d -f ...
ctags: -d: Invalid debug level

$ ctags -d1 -f ...
ctags: -d: Invalid debug level

$ ctags -d=1 -f ...
ctags: -d: Invalid debug level

$ ctags -d 1 -f ...
ctags: -d: Invalid debug level
```
Not sure how to specify it?
debug.h has
```
enum eDebugLevels {
	DEBUG_READ   = 0x01,  /* echo raw (filtered) characters */
	DEBUG_PARSE  = 0x02,  /* echo parsing results */
	DEBUG_STATUS = 0x04,  /* echo file status information */
	DEBUG_OPTION = 0x08,  /* echo option parsing */
	DEBUG_CPP    = 0x10,  /* echo characters out of pre-processor */
	DEBUG_RAW    = 0x20   /* echo raw (filtered) characters */
};
```

How do you use CXX_DEBUGGING_ENABLED?
Is that something I have to enable in my source and re-compile, or does it have a whole bunch of levels to it and predefined output as well?

Thanks, just trying to get up to speed on Universal Tags.  I was the maintainer on about 6 parsers for Exuberant Tags.

**Comment by b4n** [comment]
> Not sure how to specify it?

Apparently the code has to be compiled with `DEBUG` defined (see *options.h*).

> How do you use CXX_DEBUGGING_ENABLED?
> Is that something I have to enable in my source and re-compile, or does it have a whole bunch of levels to it and predefined output as well?

It's something to be defined when building, and I don't think it's controllable afterward, but I may be mistaken.

**Comment by masatake** [comment]
Following patch is needed.

```
diff --git a/main/options.c b/main/options.c
index 2649e94..c157b1e 100644
--- a/main/options.c
+++ b/main/options.c
@@ -69,7 +69,7 @@
 # define RECURSE_SUPPORTED
 #endif
 
-#define isCompoundOption(c)  (bool) (strchr ("fohiILpDb", (c)) != NULL)
+#define isCompoundOption(c)  (bool) (strchr ("fohiILpdb", (c)) != NULL)
 
 #define SUBDIR_OPTLIB "optlib"
 #define SUBDIR_PRELOAD "preload"
```

**Comment by masatake** [comment]
@dfishburn, feel free to reopen this.

**Comment by dfishburn** [comment]
Works like a charm, appreciated.
