### ISSUE TITLE
Option --tag-relative has no effect in etags mode (with -e).

### ISSUE THREAD

**Issue by otandka** [universal-ctags/ctags#1217]
I cannot get --tag-relative to work with etags.  The following commands all produce the same output.  The option does have the expected effect if I omit the -e option.
```
% ctags -e -f ../TAGS --tag-relative=no fs/fsDiskAddr.C && grep Addr.C ../TAGS
fs/fsDiskAddr.C,3647
% ctags -e -f ../TAGS --tag-relative=yes fs/fsDiskAddr.C && grep Addr.C ../TAGS
fs/fsDiskAddr.C,3647
% ctags -e -f ../TAGS fs/fsDiskAddr.C && grep Addr.C ../TAGS 
fs/fsDiskAddr.C,3647
```
Is this a bug or am I doing something wrong?

**Comment by masatake** [comment]
Thank you for reporting. This is a bug .The behaviour  is different from  Exuberant-ctags.

**Comment by masatake** [comment]
Could you try #1223?

**Comment by otandka** [comment]
Thanks for the quick response.

I'd be happy to, but I don't know how.  I have never used Github before and am pretty weak with homebrew as well.  I went to the git repository where homebrew keeps the universal-ctags code and did a git fetch, but neither commit 6b6f0b6 nor ccc1c999 are visible.  My git remote -v looks like this:
```
origin	https://github.com/universal-ctags/ctags.git (fetch)
origin	https://github.com/universal-ctags/ctags.git (push)
```
Even after getting the new code, though, I'm not sure how to make homebrew rebuild it.  Any pointers to help with these things?

**Comment by masatake** [comment]
Do you have a clone repository for universal-ctags?
If yes, with following instruction you can get the source tree to which my changes are applied.

```
git checkout -b masatake-fix-etags-relative-tag-printing master
git pull https://github.com/masatake/ctags.git fix-etags-relative-tag-printing
```

(... But is seems that my changes don't work well on Windows.)

**Comment by otandka** [comment]
Thanks for your suggestions.  I've never used a shallow repository, but it obviously make sense in this situation.  I imported your commit/branch without trouble.

It was a little more complicated to figure out home brew, but I managed to build ctags directly in the git tree and install from there.

The new version works as I expected now.

Thanks again!
