### ISSUE TITLE
SQL parser generates wrong results when PostgreSQL's CREATE CAST is used in file

### ISSUE THREAD

**Issue by karlb** [universal-ctags/ctags#1235]
When running ctags on a file containing

    CREATE CAST (type_a AS type_b)
        WITH FUNCTION type_conversion_function(type_a)
        AS IMPLICIT;

    CREATE OR REPLACE VIEW my_view AS
    SELECT 1;

the resulting tags file is

    !_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
    !_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
    !_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/
    !_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
    !_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
    !_TAG_PROGRAM_URL       https://ctags.io/       /official site/
    !_TAG_PROGRAM_VERSION   0.0.0   /6587204/
    type_conversion_function        ctags_testcase.sql   /^    WITH FUNCTION type_conversion_function(type_a)$/;"        f

This is wrong, because the view my_view is not detected (which works fine if I remove the CREATE CAST).

I'm not sure whether type_conversion_function should appear in the tags file. Is the "f" tag used for SQL function declarations only, or also for functions usages?

**Comment by masatake** [comment]
Thank you for reporting. I like this kind of well written bug report.
Please, try #1237.

**Comment by karlb** [comment]
Thanks for the quick response and your work on this! It's a pleasure to submit bug reports when they help to get the problem resolved like this.

I can confirm that you change fixes the test case, but it still fails on a slightly more complicated case. For

    CREATE OR REPLACE FUNCTION my_func()
    RETURNS void
    AS $$
        SELECT 1
    $$ LANGUAGE sql IMMUTABLE;

    CREATE CAST (type_a AS type_b)
        WITH FUNCTION type_conversion_function(type_a)
        AS IMPLICIT;

    CREATE OR REPLACE VIEW my_view AS
    SELECT 1;

the result is still missing my_view:

    !_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
    !_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
    !_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
    !_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
    !_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
    !_TAG_PROGRAM_URL	https://ctags.io/	/official site/
    !_TAG_PROGRAM_VERSION	0.0.0	/ca56ec9/
    my_func	ctags_testcase.sql	/^CREATE OR REPLACE FUNCTION my_func()$/;"	f

**Comment by masatake** [comment]
Please, try #1237 again.

**Comment by karlb** [comment]
Now all problems I've noticed so far are gone. Thanks!
