### ISSUE TITLE
Incorrect detection of a symbol in libgit2 (regression)

### ISSUE THREAD

**Issue by lvc** [universal-ctags/ctags#1241]
Hello,

The latest universal ctags incorrectly detects a symbol in the code (include/git2/zlib.h from libgit2 0.11.0):

    GIT_INLINE(size_t) deflateBound(z_streamp stream, size_t s)
    {
        return (s + ((s + 7) >> 3) + ((s + 63) >> 6) + 11);
    }

This command detected `GIT_INLINE` instead of `deflateBound`:

    ctags -x --C-kinds=fpvx --languages=+C --language-force=C include/git2/zlib.h|grep deflateBound
    GIT_INLINE       function     50 include/git2/zlib.h GIT_INLINE(size_t) deflateBound(z_streamp stream, size_t s)
    
However, universal ctags from May 7 2016 detected it properly:

    ctags -x --C-kinds=fpvx --languages=+C --language-force=C include/git2/zlib.h|grep deflateBound
    deflateBound     function     50 include/git2/zlib.h GIT_INLINE(size_t) deflateBound(z_streamp stream, size_t s)

Thank you.

**Comment by pragmaware** [comment]
Fixed via #1245

**Comment by lvc** [comment]
Verified with 6e839be606cbc750e6e6a7e6d16fe375adbef5ca. Works well.

Thank you.
