### ISSUE TITLE
Doesn't detect a symbol from httpd (regression)

### ISSUE THREAD

**Issue by lvc** [universal-ctags/ctags#1242]
Hello,

The latest universal ctags (249c3c0c2a974ab03f7c307684563239096399a8) doesn't detect the symbol `ap_os_create_privileged_process` in this code (include/ap_mpm.h from httpd 2.4.18):

    AP_DECLARE(apr_status_t) ap_os_create_privileged_process(
        const request_rec *r,
        apr_proc_t *newproc,
        const char *progname,
        const char * const *args,
        const char * const *env,
        apr_procattr_t *attr,
        apr_pool_t *p);

This command returned empty output:

    ctags -x --C-kinds=fpvx --languages=+C --language-force=C include/ap_mpm.h|grep ap_os_create_privileged_process

However, the edition of universal ctags from May 7 2016 (e5b7a2508db6e1374ea78a300cc9b45f4b26b02a) detected it properly:

    ctags -x --C-kinds=fpvx --languages=+C --language-force=C include/ap_mpm.h|grep ap_os_create_privileged_process
    ap_os_create_privileged_process prototype   107 include/ap_mpm.h AP_DECLARE(apr_status_t) ap_os_create_privileged_process(

I can't even fix this by any `-I` option. It's necessary to use `OldC` parser in this case.

Thank you.

**Comment by masatake** [comment]
Sorry to be late. I have a question. e5b7a25 is found by git bisect? or not?
I think this bug may be introduced when @pragmaware worked on attribute for function which I asked him to fix. This one and #1241 may spot the same bug.

This is a bug but may be difficult to fix, I guess.

**Comment by masatake** [comment]
I don't have time to fix now, but this bug has impacts on my daily life. I will find time anyway.

**Comment by b4n** [comment]
Maybe the parser could have heuristics for this kind of things, but well, I let @pragmaware decide if it's worth it/doable without breaking many things.

But with his new preprocessor, you can easily fix the issue with `-D 'AP_DECLARE(x)=x'`:
```console
$ ./ctags -x --C-kinds=+p -D 'AP_DECLARE(t)=t' /tmp/1242.c
ap_os_create_privileged_process prototype     1 /tmp/1242.c      AP_DECLARE(apr_status_t) ap_os_create_privileged_process(
```

**Comment by pragmaware** [comment]
Yes, that part of the parser was first too "permissive", then I made it too strict. I guess I'll have to find a way to make it go somewhere in the middle. I'll try to fix it now.

**Comment by masatake** [comment]
@pragmaware, thank you.  

Could you ask write about the powerful `-D` option to `http://docs.ctags.io/en/latest/parser-cxx.html`.
This is not the first time we let a user know `-D` option.

**Comment by pragmaware** [comment]
Closed via #1245

**Comment by lvc** [comment]
Ctags 6e839be606cbc750e6e6a7e6d16fe375adbef5ca detects this standalone symbol well. But the initial header file contains the following preamble for this symbol:
    
    AP_DECLARE_HOOK(int, mpm, (apr_pool_t *pconf, apr_pool_t *plog, server_rec *server_conf))
    
    /**
     * comment ...
     */
    
    AP_DECLARE(apr_status_t) ap_os_create_privileged_process(
        const request_rec *r,
        apr_proc_t *newproc,
        const char *progname,
        const char * const *args,
        const char * const *env,
        apr_procattr_t *attr,
        apr_pool_t *p);

And for some reason ctags doesn't detect it in this case. This issue may be related to #1251.

**Comment by pragmaware** [comment]
Hm, this case is quite hard to fix without breaking other cases.
That is, an older version of the parser caught this one but did break in other places....
