### ISSUE TITLE
etags: severe performance and file-size issue

### ISSUE THREAD

**Issue by ivanbrennan** [universal-ctags/ctags#1247]
I'm generating etags for a large Rails app. Prior to using Emacs, I was generating ctags for Vim:
```
$ git ls-files | \
  ctags --tag-relative=yes -L - -f ".git/tags" --languages=-javascript,sql
```
This took about a second and produced a 7MB file. With the `-e` flag, it takes 80 seconds and produce an ***8GB*** file.
```
$ git ls-files | \
  ctags --tag-relative=yes -L - -e -f ".git/tags" --languages=-javascript,sql
```

I initially thought it was a problem with etags in general, but I've since found that the `etags` executable that came with Emacs 25.1 takes 13 seconds and produces a 3MB file, while `exuberant-ctags` takes 2 seconds and produces a 1MB file.

I'm on a 2013 MacBook Air running macOS Sierra 10.12.1

**Comment by masatake** [comment]
Could you provide any input files? I cannot debug ctags without them

**Comment by masatake** [comment]
Which parser do you use ? ruby only?

**Comment by ivanbrennan** [comment]
It's a private (work) repo. I tried to repo on a large public Ruby project -- Rails -- and was unable to, so maybe it's something specific to the repo I'm working with.

I'm not sure which parser I'm using. How could I check that?

**Comment by masatake** [comment]
How about following command line:
```
### .ctags
real	0m0.004s
user	0m0.002s
sys	0m0.003s
-rw-rw-r--. 1 jet jet 104 Aug  5  2015 .ctags
-rw-rw-r--. 1 jet jet  11 Dec 18 13:13 tmp.TAGS
### .dir-locals.el
real	0m0.005s
user	0m0.002s
sys	0m0.003s
-rw-rw-r--. 1 jet jet 151 Dec  8 21:51 .dir-locals.el
-rw-rw-r--. 1 jet jet  19 Dec 18 13:13 tmp.TAGS
### .editorconfig
real	0m0.005s
user	0m0.002s
sys	0m0.003s
-rw-rw-r--. 1 jet jet 143 Dec  8 21:47 .editorconfig
-rw-rw-r--. 1 jet jet   0 Dec 18 13:13 tmp.TAGS
### .gdbinit
real	0m0.003s
user	0m0.002s
sys	0m0.001s
-rw-rw-r--. 1 jet jet 31 Nov 23  2014 .gdbinit
-rw-rw-r--. 1 jet jet  0 Dec 18 13:13 tmp.TAGS
### .gitignore
real	0m0.003s
user	0m0.001s
sys	0m0.003s
-rw-rw-r--. 1 jet jet 706 Dec  8 21:51 .gitignore
-rw-rw-r--. 1 jet jet   0 Dec 18 13:13 tmp.TAGS
### .indent.pro
real	0m0.003s
user	0m0.002s
sys	0m0.001s
-rw-rw-r--. 1 jet jet 740 Nov 23  2014 .indent.pro
-rw-rw-r--. 1 jet jet   0 Dec 18 13:13 tmp.TAGS
### .travis.yml
real	0m0.003s
user	0m0.000s
sys	0m0.003s
-rw-rw-r--. 1 jet jet    0 Dec 18 13:13 tmp.TAGS
-rw-rw-r--. 1 jet jet 1.8K Dec  8 21:51 .travis.yml
...
```

You can know which input files take time and output size.

**Comment by masatake** [comment]
Sorry, I cannot debug ctags well for private input.  I need the way to reproduce locally.
Could you reopen this if you can find the way to reproduce with input file public-ally available?

**Comment by ivanbrennan** [comment]
@masatake What command did you run to produce the output above (showing time and size for each file)? That would help a lot. I tried the `--verbose` flag, and while that might also help (I see some json files being processed, which may be contributing to the problem), it doesn't give the time and size breakdown.

I'll see if I can narrow the problem down to a particular type of input and reopen the issue if so. Thanks for your help.

**Comment by masatake** [comment]
Oh, sorry. Following command generates:

```
 $ for x in $(git ls-files); do echo -n "### $x"; time ./ctags --tag-relative=yes -e -f tmp.TAGS --languages=-javascript,sql $x; ls -lh $x tmp.TAGS; done
### .ctags
....
```

**Comment by ivanbrennan** [comment]
Looks like the json files are the main culprits. Adding `json` to the list of excluded languages takes the execution time down to about 4 seconds and the filesize to 282MB.

Still significantly slower and larger than `exuberant-ctags`, but nowhere near as bad as before. I'll see if I can trace the remaining difference to any particular filetypes.

**Comment by masatake** [comment]
May '--languages=-json' help you?

**Comment by ivanbrennan** [comment]
The 2nd biggest performance hit, though way less significant than the json, was `bootstrap.min.css`, which ate up most of the space (275MB) and took about 2 seconds to tag. I should probably exclude the `vendor` directory when generating tags.

There was another vendor css file whose tag was 5MB; after that the tag size dropped into orders of KB. I was surprised to see some .svg files in the list, as I didn't know those got tagged.

Anyway, @masatake thanks again for your help with this. It's good to know I can continue using `universal-ctags`, and I learned a few valuable lessons along the way.

**Comment by masatake** [comment]
@ivanbrennan, thank you for reporting.

... I wonder we should provide a new option like `--make-tags-only-when-file-is-smaller-than=10MB`.

**Comment by masatake** [comment]
This will be FAQ. I should add this to our document.

**Comment by b4n** [comment]
> Looks like the json files are the main culprits.

The JSON parser is new in *Universal-CTags*, and is likely to generate quite a bit of tags indeed (one per node).  Maybe this parser could be disabled by default as it might not be so useful when tagging a lot of things, but is rather useful as a TOC-like thing?

If you could share the JSON input though, we could possibly try and profile the parser/check the output to see if there's another problem.  Or you could do it yourself if sharing is not an option.

> There was another vendor css file whose tag was 5MB;

The CSS parser also got a fair overhaul, and it's very possible it catches a lot more tags than it used to -- or maybe it has a bug? but 5M for a complete CSS sheet doesn't seem absurd, so maybe not.

> I was surprised to see some .svg files in the list, as I didn't know those got tagged.

That's another new thing introduced by u-ctags :)

In the end, for now what you say suggests that it's "only" because u-ctags tags a lot more stuff that e-ctags did.  But if those cause issues like that, maybe we should come out with more sensible defaults set of enabled parsers or some other thing like tag size limitation as @masatake mentioned.

**Comment by ivanbrennan** [comment]
I ran some more measurements to identify which files took longest to process and resulted in the largest tag files. The top offenders by either metric (time or size) were a large json file and a minified bootstrap stylesheet.

Taking inspiration from @masatake I generated a list of performance stats:
```shell
for f in $(git ls-files)
do
  ( echo "$f"
    ( TIMEFORMAT='%R'
      time ctags -e -o tmp.TAGS --tag-relative=yes --languages=-javascript,sql $f )
    ( ls -l $f
      ls -l tmp.TAGS ) | awk '{ print $5 }'
    echo ) >> tagging.log 2>&1
  rm tmp.TAGS
done
```
This produced a list of records showing the source-file-name, time spent tagging (seconds), source-file-size (bytes), and tag-file-size (bytes). E.g.:
```
some_file.rb
0.002
2938
14934

another_file.rb
0.004
7542
20123

...
```

I used awk and sort to sort the results by time and by tag-size:
```shell
awk 'BEGIN { RS=""; FS="\n" } { print $1, $2, $3, $4 }' etagging.log | sort -nrk2 > etagging-time
awk 'BEGIN { RS=""; FS="\n" } { print $1, $2, $3, $4 }' etagging.log | sort -nrk4 > etagging-size
```
The biggest offender by both metrics was a large (267KB) json file. Next up (but far behind) was a minified bootstrap stylesheet.

```
source                time  source-size  etags-size
--------------------------------------------------
something_big.json  108.024  273517     8084569921
bootstrap.min.css     2.159  118153      288792277
```

I ran the same steps for the ctags format (without `-e` option) to compare. The json file was again the biggest offender, but on a much smaller scale. The minified stylesheet was the 2nd biggest in terms of tags-size, but well down the list in terms of time spent tagging.

```
source                time  source-size  ctags-size
--------------------------------------------------
something_big.json    0.233  273517        4458876
bootstrap.min.css     0.018  118153         384801
```

The json file is composed of a couple massive multidimensional arrays of numeric data, so not the kind of thing you'd care to tag anyway. I'll attach an obfuscated zipped version below.

[something_big.json.zip](https://github.com/universal-ctags/ctags/files/659691/something_big.json.zip)

The stylesheet can be found at [bootstrap.min.css](https://github.com/twbs/bootstrap/blob/bcf7dd38b5ab180256e2e4fb5da0369551b3f082/dist/css/bootstrap.min.css).

**Comment by b4n** [comment]
> I ran the same steps for the ctags format (without `-e` option) to compare. The json file was again the biggest offender, but on a much smaller scale. The minified stylesheet was the 2nd biggest in terms of tags-size, but well down the list in terms of time spent tagging.

Oh wait.  Does the etags output truncate the source line reference?  on minified files if it doesn't it'll likely output the whole file for each tag, which will be crazy.  We fixed that, but was it only for ctags format output? @masatake

**Comment by b4n** [comment]
@masatake I just tried and that's it: etags output has the whole line, which is way too much.  We need to do something similar as to the ctags format, that is truncate to a max length.

**Comment by ivanbrennan** [comment]
@b4n That helps explain what was happening with that json case as well. It only has 2 non-blank lines, but they're 124,548 and 148,966 characters long.

**Comment by masatake** [comment]
I'm afraid I did something wrong. @ivanbrennan, thank you for reporting. I will inspect etags output.

**Comment by masatake** [comment]
I inspected how a pattern is handled in TAGS/etags/emacs.
It seems that as a tag entry a string started from the head of line to the target language object is needed.
Let's use an example
```
int                                                              main(void) { }
```
Here I assume whitespaces between int and main is very long. tags output of u-ctags can truncate the line:
```
int          
```
In tags format a tag name(main) and pattern are separated. So incomplete pattern(pattern without tag name) is allowed.

However, in TAGS output (both in etags and u-ctags), such truncation is not allowed.
If truncating from head, "main" is lost from the tag entry. emacs may not find the tag.
If truncating from tail, "int"  is lost from the tag entry. emacs may not find the tag because emacs prepend ^at the beginning of line when searching.  "^     main" doesn't much to any line in the file.

I cannot find good truncation strategy.

**Comment by dgutov** [comment]
> If truncating from head, "main" is lost from the tag entry. emacs may not find the tag.

Have you tried this? Emacs uses the hint to look for the line, not for the position inside the line.

Anyway, if you have huge lines, it's probably a minified file. Blacklisting files with extensions like `.min.js` and `.min.css` seems like a good default.

**Comment by masatake** [comment]
> Have you tried this? Emacs uses the hint to look for the line, not for the position inside the line.

Yes, I tried. The truncation either from head or from tail, may break the hint to look for the line.

> Anyway, if you have huge lines, it's probably a minified file. Blacklisting files with extensions like .min.js and .min.css seems like a good default.

In tags, native format of ctags, u-ctags truncates such long lines. So, vi user can utilize the tags file for completion. (None may want to jump to the defintion.)  Though I'm an emacs user, not a vi user, I don't
put min files into built-in black list.

Should I put `*.min.css` and `*.min.js` to black list only when u-ctags runs in etags mode?
....or should I fix GNU emacs side?

**Comment by dgutov** [comment]
> Yes, I tried. The truncation either from head or from tail, may break the hint to look for the line.

Could you give an example of truncation from head that leads to such a problem? E.g. by attaching a pre-generated TAGS file and a file it references.

I can look into that from Emacs's side.

**Comment by dgutov** [comment]
And please clarify what do you mean exactly by "emacs may not find the tag". Never finds it, or might not find in some circumstances?

**Comment by dgutov** [comment]
> So, vi user can utilize the tags file for completion. (None may want to jump to the defintion.)

Emacs users can use TAGS for completion as well, BTW.

**Comment by masatake** [comment]
I prepared two input files: main.c and foo.c. 
main function of main.c calls foo which is defined in foo.c.
Consider an emacs user wants to jump from the place where foo is called in main to foo's definition.

```
[jet@localhost t]$ cat main.c
int main(void)
{
	return foo();
}
[jet@localhost t]$ cat foo.c
int                                                                                       
                                                                                          foo (void) {}
```

Let's consider whitespaces before foo is enough long.

Let's run GNU etags.
```
[jet@localhost t]$ etags --version
etags (GNU Emacs 25.1)
Copyright (C) 2016 Free Software Foundation, Inc.
This program is distributed under the terms in ETAGS.README
[jet@localhost t]$ etags foo.c main.c 
[jet@localhost t]$ cat TAGS

foo.c,100
                                                                                          foo 2,91

main.c,14
int main(1,0
```

Of couse, generating TAGS will work fine.

Think about two files derived  from the original TAGS file. 
```
[jet@localhost t]$ cp TAGS head-trunc.TAGS
[jet@localhost t]$ cp TAGS tail-trunc.TAGS
[jet@localhost t]$ editor-you-like head-trunc.TAGS
[jet@localhost t]$ editor-you-like tail-trunc.TAGS
[jet@localhost t]$ cat head-trunc.TAGS

foo.c,100
foo 2,91

main.c,14
int main(1,0
[jet@localhost t]$ cat tail-trunc.TAGS

foo.c,100
          2,91

main.c,14
int main(1,0
```

Let's test head-trunc.TAGS:
```
[jet@localhost t]$ emacs -Q main.c
M-x visit-tags-file
Visit tags table (default TAGS): ~/var/ctags/t/head.TAGS
;; move the point to foo in main in main.c
M-.
In #<buffer *Messages*>: user-error: Rerun etags: ‘^foo ’ not found in /home/jet/var/ctags/t/foo.c
```

Let's test tail-trunc.TAGS
```
[jet@localhost t]$ emacs -Q main.c
M-x visit-tags-file
Visit tags table (default TAGS): ~/var/ctags/t/tailTAGS
;; move the point to foo in main in main.c
M-.
In #<buffer *Messages*>: user-error: No definitions found for: foo
```

**Comment by dgutov** [comment]
> Think about two files derived from the original TAGS file.

You can't make `tail-trunc.TAGS` by simply removing text from the generated file. There's nothing left! Certainly nothing to indicate that `foo` is defined in `foo.c`.

If you are truncating the tag hint such as the implicit tag name becomes incorrect (empty, in this case), the tag entry should include the explicit tag name. It goes before `�`, separated from the hint with ``.

**Comment by masatake** [comment]
> 
> 
>     Think about two files derived from the original TAGS file.
> 
> You can't make tail-trunc.TAGS by simply removing text from the generated file. There's nothing left! Certainly nothing to indicate that foo is defined in foo.c.
> 
> If you are truncating the tag hint so that the implicit tag name becomes incorrect (empty, in this case), the tag entry should include the explicit tag name. It goes before �, separated from the hint with �.

So how u-ctags should truncate the entry for the input in TAGS output format?

**Comment by masatake** [comment]
BTW, tags output in u-ctags chooses the tail-trunc approach.

**Comment by dgutov** [comment]
> So how u-ctags should truncate the entry for the input in TAGS output format?

The way I described in my previous message. Do you need an example of the output?

**Comment by masatake** [comment]
Yes, please. As you may feel, I'm bad in English. Actual examples may help me.

**Comment by dgutov** [comment]
Here's how it should look:

```
$ cat TAGS

foo.c,96
                  foo2,4

main.c,14
int main(1,0
```

The characters surrounding `foo` are `\177` and `\001` respectively.

**Comment by masatake** [comment]
Oh, I see.

**Comment by dgutov** [comment]
Not really. The entry didn't have an explicit tag name field in the first place because the tag name could be derived from the hint implicitly.

An implicit tag entry is: hint, `\177`, numbers.
An explicit entry is: hint, `\177`, tag name, `\001`, numbers.

**Comment by b4n** [comment]
So we should just truncate the end of `hint` not to be overly long, yet allowing matching line starts (as apparently that's required), and add explicit tags basically everywhere.  Right?

**Comment by dgutov** [comment]
> and add explicit tags basically everywhere

You could. But ideally, you'd only do that where required (to save on the file size). You check whether the truncated hint includes the tag name "implicitly", and if not, add the explicit tag name. You might have this logic somewhere in the code already, then the key is to perform truncation early enough.

Here are the implicit tag name conditions, to be clear: https://github.com/emacs-mirror/emacs/blob/3ec1503374d3115651c130eaeee31181266d0863/lib-src/etags.c#L1891-L1899

**Comment by masatake** [comment]
I found u-ctags implement only explicit entry based output.
Just truncating from head approach may be enough.  I will make a PR.

**Comment by masatake** [comment]
See #1253.

**Comment by masatake** [comment]
The issue about filesize is fixed. However, it is still slow because ctags reads whole line before truncating.
If possible truncating should be done in lower layer, read.c.
