### ISSUE TITLE
No rst2man = no man page

### ISSUE THREAD

**Issue by dtikhonov** [universal-ctags/ctags#1249]
I think that requiring that `rst2man` be installed in order to generate and install a man page is too much.  Here is my story:

When I recently installed a new system, I git-cloned Universal Ctags and installed it (as I always do).  Some time later, I wanted to look up a ctags option:

- `man ctags`
- `locate ctags.1`
- `find /usr -name ctags.1`
- WTF...

I went back to the cloned git repo and found ctags.1.rst.  A few minutes later I found 15413bacefa25b8ceb3767f774726cbbd89a9641 and a few more minutes later I installed `rst2man` and had my man page.

On Ubuntu 16.04.1 LTS, installing `docutils-common` (for which I had to run a web search, as `apt search rst2man` produces no hits) installs ten packages.  They are:

- docutils-common:amd64 (0.12+dfsg-1)
- docutils-doc:amd64 (0.12+dfsg-1, automatic)
- python-chardet:amd64 (2.3.0-2, automatic)
- python-docutils:amd64 (0.12+dfsg-1, automatic)
- libpaper1:amd64 (1.1.24+nmu4ubuntu1, automatic)
- python-roman:amd64 (2.0.0-2, automatic)
- python-pygments:amd64 (2.1+dfsg-1, automatic)
- libpaper-utils:amd64 (1.1.24+nmu4ubuntu1, automatic)
- libwebpmux1:amd64 (0.4.4-1, automatic)
- python-pil:amd64 (3.1.2-0ubuntu1, automatic)

That's a lot of packages.  Also, what if the user does not have root privileges -- what is he to do for a man page?

I think it would be better to simply check in ctags.1 as changes to ctags.1.rst are made.  This way, people who want to use Universal Ctags do not have to jump through hoops just to get a fine man page.

**Comment by b4n** [comment]
IMO it's not a good idea.  IMO, the solution here is for those people to use release tarballs that contain those generated files, and to leave in Git only the actual sources.  Having generated files checked in creates noise at some point or another, e.g. if 2 contributors don't have the same version of *rst2man*, etc.
Also, where to stop?  Should *configure* be checked in, so people don't need Autoconf, Automake, Aclocal, Perl and whatnot?  Should the object files be checked in so people don't need a C compiler?  Should the executable be checked in so people don't need a linker?  Yes, I'm shamelessly using *reductio ad absurdum*, sorry :)

But well, that's my opinion :)

**Comment by dtikhonov** [comment]
It's a matter of expectations: a successful configuration and compilation of a utility from source implies that all has been build correctly, including a man page.  In addition, people expect to need a C compiler for this.  Needing a ten-package Python toolchain for a converter few people heard of is silly.  IMO, of course...

Here is a _reductio ad absurdum_ the other way: I recently installed and compiled [proto-quic](https://github.com/google/proto-quic), which is a small subset of Chrome web browser (mostly C++ code).  To build, it had to install 912! packages, including Apache, PHP, and initramfs...

Now, what was wrong with just providing a man page?

**Comment by masatake** [comment]
We cannot provide ctags.1 but we can do ctags.1.in. 

The version number and the name of executbale are written in ctags.1.
They are decided when configure script is run. Therefore we cannot provide ctags.1.
What we can provide is ctags.1.in. The document is generated from rst file; ctags1.in is generated from ctags1.in.rst. Then the developers put both ctags.1.in and ctags1.in.rst to our git repository. This is the original idea of mine: https://github.com/universal-ctags/ctags/pull/1089 .

In #1089, I got too many troubles for getting good enough ctags.1.in. So I aborted the original idea.

**Comment by dtikhonov** [comment]
> We cannot provide ctags.1 but we can do ctags.1.in.

OK -- as long as there is a man page once ctags is built. :)

**Comment by masatake** [comment]
>>    We cannot provide ctags.1 but we can do ctags.1.in.

> OK -- as long as there is a man page once ctags is built. :)

As I wrote I got too many troubles for getting good enough ctags.1.in. 
So I aborted the idea including ctags.1.in to our repository.
Feel free to reopen this if you find good solution.

**Comment by masatake** [comment]
BTW, putting the man page to docs.ctags.io is good idea.

**Comment by peanutandchestnut** [comment]
I'm not  familar with both rst2man and autotools.
It took me quite a while to to realize that i have to execute autogen.sh again after rest2man installed.

**Comment by masatake** [comment]
Yes, you have to run autogen.sh.
