### ISSUE TITLE
Handle the special case of MACRO(data_type) variable;

### ISSUE THREAD

**Issue by lvc** [universal-ctags/ctags#1252]
Trying to detect a symbol in the Python header file by the ctags 6e839be606cbc750e6e6a7e6d16fe375adbef5ca:

    PyAPI_DATA(PyTypeObject) _PyNone_Type;

The command

    ctags -x --C-kinds=fpvx --languages=+C --language-force=C test.h

returns incorrect:

    PyAPI_DATA       prototype     2 test.h          PyAPI_DATA(PyTypeObject) _PyNone_Type;

Adding of a `-D 'PyAPI_DATA(x)=x'` fixes the problem. But is it possible to improve the ctags tool to somehow detect it automatically? Also is it possible to fix this by `-I` option instead of `-D`?

Thank you.

**Comment by pragmaware** [comment]
A potential fix is #1316 . A super special case :)
The typeref is broken though (as the macro could actually expand to anything).

**Comment by pragmaware** [comment]
Fixed via #1316
