### ISSUE TITLE
Bash functions do not need to be prefixed by `function`

### ISSUE THREAD

**Issue by fidian** [universal-ctags/ctags#1261]
I have a bash script with some functions.

    #!/usr/bin/env bash

    a::test() {
        echo "test"
    }

    function a::anotherTest() {
        echo "another test"
    }

Running `ctags` on this file produces the following.

    $ ctags -f - --guess-language-eagerly a
    a::anotherTest	a	/^function a::anotherTest() {$/;"	f
    test	a	/^a::test() {$/;"	f

I would expect the second line to say `a::test` instead of `test`.  I believe this boils down to the parser's `findShTags` function not checking if the file type is `bash` somehow.  I would suggest you change line 201 of `parsers/sh.c` from this

    check_char = isIdentChar;

to something more like this

    if (strncmp(somehowGetCurrentFileType, "bash", 4)) {
        // Not bash
        check_char = isIdentChar;
    } else {
        check_char = isBashFunctionChar;
    }

I don't know how much this would break.  Another option would be to modify the area near line 263 of `parsers/sh.c` to look backwards and change the detected function name if it can be extended backwards.

**Comment by bittorf** [comment]
BTW: is "a::test" even a valid shell-function name? see http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

<code>
"consist solely of uppercase letters, digits, and the
'_' (underscore) from the characters defined in Portable
Character Set and do not begin with a digit"
</code>

**Comment by masatake** [comment]
@fidian, I made a pull request that use isBashFunctionChar as the default value of check_char.

**Comment by fidian** [comment]
@bittorf As you noticed, Bash allows more characters in function names.  I did a fairly exhaustive study of the characters and my results are posted in https://github.com/tests-always-included/tomdoc.sh/issues/8.  In case you didn't know about it, TomDoc.sh is a great way to add doc blocks to Bash scripts.

@masatake Would that cause any issues with other shells?  Or are the chances of problems so diminished that they are not worth mentioning?

**Comment by masatake** [comment]
> @masatake Would that cause any issues with other shells? Or are the chances of problems so diminished that they are not worth mentioning?

@fidian, can you find any really issue about the other shells?

I cannot find. 

Let's consider following script for the other shells:
```
a::test() {
    echo "test"
}
```

ctags introduced my change may create a tag "a::test". This identifier is not valid
as a function name in the shell. However, it means, this shell script itself is not valid
in the shell.  ctags (and its developers) tries hard to generate good tags file for good input files.
However, ctags generates bad tags file for bad input files.
(Cxx parser tries to generate good tags filr for not good input files. It is very speciall.)

Of course, I would like to hear the way to improve.

**Comment by fidian** [comment]
@masatake I do not know of any issues with other shells.  I would want to run this change past a comprehensive test suite, complete with obscure and convoluted files that work in their chosen language.  I don't know if your patch still passes all tests nor do I know about the quality of the tests in this project.  Sorry for my ignorance.

I could imagine a shell's tokenizer treating all `-` as math, `#` as the beginning of a comment, `=` as assignment, and backticks always as command substitution where as Bash could treat those as math or as a function name.  However, after experimentation with `dash`, I was unable to construct something that breaks so perhaps this is a moot point.

I'm totally in favor of the change you proposed and only was asking if it would break stuff because I don't have enough background knowledge with this tool.

**Comment by masatake** [comment]
> @masatake I do not know of any issues with other shells. I would want to run this change past a comprehensive test suite, complete with obscure and convoluted files that work in their chosen language. I don't know if your patch still passes all tests nor do I know about the quality of the tests in this project. Sorry for my ignorance.

Thank you.

> I could imagine a shell's tokenizer treating all - as math, # as the beginning of a comment, = as assignment, and backticks always as command substitution where as Bash could treat those as math or as a function name. However, after experimentation with dash, I was unable to construct something that breaks so perhaps this is a moot point.

sh parser is not token based parser. It is designed in less restricted way. It is rather line oriented.

We don't have such comprehensive test suite you mentioned, so we have to try anther approach; just applying the change and waiting for another bug report:-P.
