### ISSUE TITLE
Making release

### ISSUE THREAD

**Issue by bastien-roucaries** [universal-ctags/ctags#1272]
Hi,

I order to package for debian, I need some version and tar.gz.

could you made a release even experimental ?

Thanks

**Comment by steveno** [comment]
See #1038

**Comment by t-b** [comment]
@bastien-roucaries 
Sorry for the dump question. Byt why is an arbitrary tag better than an arbitrary commit? Can't you build a package from c27e1a5f24fcd7a4025f0d5bfe3f2d4311a53754?

**Comment by NoctuaNivalis** [comment]
@t-b many package-managers simply require you to package a versioned release.

**Comment by t-b** [comment]
@NoctuaNivalis Not sure about the term package manger here.

In debian packages from arbitrary git commits are normal. E.g. the package [libnss-securepass](https://tracker.debian.org/pkg/libnss-securepass) in debian wheezy is build from https://github.com/gplll/nss_securepass/commit/2299135d80142f0810379f3589e25b5764637815.

**Comment by NoctuaNivalis** [comment]
I wasn't sure about the term myself. Package repositories?

**Comment by masatake** [comment]
I don't make a releasae with old man page. man page must be updated.
