### ISSUE TITLE
English question: extra or extras

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1289]
I'm working on adding ``--extra-<LANG>=`` option. 
I need your help about the option names.

Though ``--<LANG>-kinds=`` and ``--fields=...`` in exuberant-ctags are represented in plural forms,
``--extra`` is singular form.

Do you think this is inconsistent?
Adding ``--extras=`` and ``--list-extras`` is bad idea?

**Comment by codebrainz** [comment]
If the value after the `=` is multiple things, like `--<LANG>-kinds=` then it should be plural, I think.

**Comment by masatake** [comment]
@codebrainz, thank you.

**Comment by codebrainz** [comment]
Sounds reasonable.
