### ISSUE TITLE
provide backward compatibility for automake without AM_SILENT_RULES

### ISSUE THREAD

**Issue by vladak** [universal-ctags/ctags#1296]
On a system with automake 1.10 I am bumping against 

```
configure.ac:12: warning: macro `AM_SILENT_RULES' not found in library
```

This is because this macro was introduced in automake-1.11: https://autotools.io/automake/silent.html

The way how to provide backward compatibility for older automake versions is to do this:

```
diff --git a/configure.ac b/configure.ac
index 1fc7dbd..0f63fd4 100644
--- a/configure.ac
+++ b/configure.ac
@@ -9,7 +9,7 @@
 AC_PREREQ([2.59])
 AC_INIT([universal-ctags],[0.0.0])
 AM_INIT_AUTOMAKE([foreign subdir-objects])
-AM_SILENT_RULES([yes])
+m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES])
 AC_CONFIG_HEADERS([config.h])
 if ! test -e "${srcdir}/config.h.in"; then
    echo "---"
```

**Comment by masatake** [comment]
```
-AM_SILENT_RULES([yes])
+m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES])
```
If `AM_SILENT_RULES` is never used in our source tree, I wonder why
AM_SILENT_RULES should be defined with `m4_ifdef`.

The effect of your patch looks the same as following patch
```
-AM_SILENT_RULES([yes])
```

Am I wrong ?

**Comment by masatake** [comment]
Anyway 1.10 is too old.

**Comment by b4n** [comment]
@masatake `m4_ifdef` expands to the second argument if a macro of the first name is defined.  The goal here is to only use that macro when available.

> ```diff
>-AM_SILENT_RULES([yes])
>+m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES])
>```

Is passing no argument the same as `yes`?  I'm not sure, the [Automake doc](https://www.gnu.org/software/automake/manual/automake.html#index-AM_005fSILENT_005fRULES) isn't clear.

Otherwise, the change looks good to me if it's all it needs.

**Comment by masatake** [comment]
@b4n, thank you. Did you try the patch?

After applying the patch, make prints `gcc ...` on my environment:

```
[jet@localhost ctags]$ automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
[jet@localhost ctags]$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

[jet@localhost ctags]$ git diff |cat
diff --git a/configure.ac b/configure.ac
index 1fc7dbd..0f63fd4 100644
--- a/configure.ac
+++ b/configure.ac
@@ -9,7 +9,7 @@
 AC_PREREQ([2.59])
 AC_INIT([universal-ctags],[0.0.0])
 AM_INIT_AUTOMAKE([foreign subdir-objects])
-AM_SILENT_RULES([yes])
+m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES])
 AC_CONFIG_HEADERS([config.h])
 if ! test -e "${srcdir}/config.h.in"; then
    echo "---"
[jet@localhost ctags]$ bash autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
/usr/share/automake-1.15/am/tags.am: warning: redefinition of 'ctags' ...
/usr/share/automake-1.15/am/program.am: ... 'ctags$(EXEEXT)' previously defined here
Makefile.am:6:   while processing program 'ctags'
autoreconf: Leaving directory `.'
optlib2c: translating optlib/CoffeeScript.ctags to optlib/CoffeeScript.c
optlib2c: translating optlib/ctags-optlib.ctags to optlib/ctags-optlib.c
optlib2c: translating optlib/elm.ctags to optlib/elm.c
optlib2c: translating optlib/gdbinit.ctags to optlib/gdbinit.c
optlib2c: translating optlib/man.ctags to optlib/man.c
optlib2c: translating optlib/pod.ctags to optlib/pod.c
[jet@localhost ctags]$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
...
config.status: executing depfiles commands
[jet@localhost ctags]$ make
./misc/gen-repoinfo > main/repoinfo.h
make  all-am
make[1]: Entering directory '/home/jet/var/ctags'
gcc -DHAVE_CONFIG_H -I.  -I. -I. -I./main    -DHAVE_REPOINFO_H  -std=gnu99 -Wall   -I/usr/include/libxml2   -g -O2 -MT main/ctags-repoinfo.o -MD -MP -MF main/.deps/ctags-repoinfo.Tpo -c -o main/ctags-repoinfo.o `test -f 'main/repoinfo.c' || echo './'`main/repoinfo.c
mv -f main/.deps/ctags-repoinfo.Tpo main/.deps/ctags-repoinfo.Po
./misc/optlib2c --transform-xcmd="s,x,x," optlib/CoffeeScript.ctags > optlib/CoffeeScript.c
```

> @masatake m4_ifdef expands to the second argument if a macro of the first name is defined. The goal here is to only use that macro when available.

I guess the patch should be:

```
[jet@localhost ctags]$ [jet@localhost ctags]$ git diff  | cat
diff --git a/configure.ac b/configure.ac
index 1fc7dbd..f513a39 100644
--- a/configure.ac
+++ b/configure.ac
@@ -9,7 +9,7 @@
 AC_PREREQ([2.59])
 AC_INIT([universal-ctags],[0.0.0])
 AM_INIT_AUTOMAKE([foreign subdir-objects])
-AM_SILENT_RULES([yes])
+m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES([yes])])
 AC_CONFIG_HEADERS([config.h])
 if ! test -e "${srcdir}/config.h.in"; then
    echo "---"
```

**Comment by b4n** [comment]
> I guess the patch should be: […]

Yeah, as mentioned I didn't know what the default is when explicitly calling `AM_SILENT_RULES`; but your test shows it's not to enable silent rules.  So if we want them on by default, your change is good.

Whether we want them or not on by default I'm not sure.  The [Automake manual says](https://www.gnu.org/software/automake/manual/automake.html#Automake-Silent-Rules):

> Note that silent rules are *disabled* by default; the user must enable them explicitly at either `configure` run time or at `make` run time. We think that this is a good policy, since it provides the casual user with enough information to prepare a good bug report in case anything breaks. 
>
> Still, notwithstanding the rationales above, a developer who really wants to make silent rules enabled by default in his own package can do so by calling `AM_SILENT_RULES([yes])` in `configure.ac`.
>
> Users who prefer to have silent rules enabled by default can edit their `config.site` file to make the variable `enable_silent_rules` default to ‘`yes`’. This should still allow disabling silent rules at `configure` time and at `make` time. 

I generally enable them on my own projects, but that's mostly because I didn't know until just now reading the above that the default can be altered on the user side in some config file (I'd have to check further to see how that works exactly though).

**Comment by masatake** [comment]
I don't have an access to environment where automake-1.10 is installed.
So I don't know whether my change works well with the old automake or not.
I'm waiting for your pull request that is tested with automake-1.10.

**Comment by b4n** [comment]
@masatake I don't either anymore, but I know that change works, I used it several times in the past.  See e.g. [Geany's `configure.ac`](https://github.com/geany/geany/blob/master/configure.ac#L12).
