### ISSUE TITLE
C function pointer isn't detected

### ISSUE THREAD

**Issue by LemonBoy** [universal-ctags/ctags#1309]
Here's a minimal test case:
```c
int foo(char *((*f)())) { }
```

**Comment by masatake** [comment]
Smaller one:

```
int ((*f)());
int (*g)();
```

Only `g` is captured.

**Comment by masatake** [comment]
Though I have never see C source codes using the parenthesis that way, I would like to fix it because 
this issue is nothing to do with C preprocessor. 
But, for fixing this issue, much deeper knowledge about the Cxx parser code than I have.

**Comment by LemonBoy** [comment]
My test-case has been obtained by reducing [this](https://github.com/vim/vim/blob/ba748c8a847561c043a63827bcb1d98bdebe16e6/src/ex_getln.c#L4937,L4944) prototype found in vim heh

**Comment by masatake** [comment]
> My test-case has been obtained by reducing this prototype found in vim heh

Oh, I see. The information is important to make us work hard:-P

**Comment by pragmaware** [comment]
See #1315.
