### ISSUE TITLE
Meta: Use Github labels for parsers

### ISSUE THREAD

**Issue by codebrainz** [universal-ctags/ctags#1310]
It would be handy to have some labels for the Github issues for each parser, so we can tag issues/PRs related to particular parsers in order to more easily see all issues related to one in particular (which I tried to do today).

I don't have ability to add new labels, but I would gladly assist in tagging any issues I come across with the correct label(s) for their parser when looking at them on Github, if someone could add the labels.

**Comment by masatake** [comment]
> I don't have ability to add new labels, but I would gladly assist in tagging any issues I come across with the correct label(s) for their parser when looking at them on Github, if someone could add the labels.

I'm very sorry that I forget to attach ctags repository to you.
Do you get the ability to add new labels now?

**Comment by codebrainz** [comment]
@masatake yes, I can assign and create labels. I will create/assign as appropriate. Thanks.

**Comment by masatake** [comment]
@codebrainz, thank you.
