### ISSUE TITLE
In C, ctags misses local variable defined as an anonymous structure

### ISSUE THREAD

**Issue by BodoStroesser** [universal-ctags/ctags#1311]
Hello,

I'm using ctags the first time. Great tool!

At the moment I'm observing that ctags does not list a local variable if it is defined as an anonymous struct. Example source:

```
int
myfunction(int a, int b, int c)
{
        int local_x;
        struct {
                int h;
                char *j;
        } mystruct = { 3, "XXX" };
        int i;

        for (i=0; i<10; i++) {
                local_x = i;
        }
        return local_x;
}
```

When I now run "ctags -u -x --c-kinds=fl testfile.c", I get:

```
myfunction       function      2 testfile.c       myfunction(int a, int b, int c)
local_x          local         4 testfile.c       int local_x;
i                local         9 testfile.c       int i;
```

And with "ctags -u -x --c-kinds=fls testfile.c" the anonymous structure is also listed. But still the variable "mystruct" is missing in the list:

```
myfunction       function      2 testfile.c       myfunction(int a, int b, int c)
local_x          local         4 testfile.c       int local_x;
__anonf81d8a160108 struct        5 testfile.c       struct {
i                local         9 testfile.c       int i;
```

Am I doing something wrong?

Thank you in advance for your help.

Best regards,
Bodo

**Comment by BodoStroesser** [comment]
Additional info:
If the initializer is removed from mystruct, ctags lists mystruct just as expected.

Modified source:

```
int
myfunction(int a, int b, int c)
{
        int local_x;
        struct ggg {
                int h;
                char *j;
        } mystruct;
        int i;

        for (i=0; i<10; i++) {
                local_x = i;
        }
        return local_x;
}
```

And now the output from ctags:

```
myfunction       function      2 testfile2.c      myfunction(int a, int b, int c)
local_x          local         4 testfile2.c      int local_x;
mystruct         local         8 testfile2.c      } mystruct;
i                local         9 testfile2.c      int i;
```

Best regards,
Bodo

**Comment by masatake** [comment]
Thank you for reporting this.

It is reproduced.
Shorter input:
```
void f (void)
{
  struct {
    int i;
  } x = { .i = 1 };
}
```

```
$ ./ctags -uxo - --kinds-'*'='*' /tmp/s.c
f                function      1 /tmp/s.c         void f (void)
__anonc375a1180108 struct        3 /tmp/s.c         struct {
i                member        4 /tmp/s.c         int i;
```

**Comment by masatake** [comment]
With the following patch, mystruct is tagged well.
```
diff --git a/parsers/cxx/cxx_parser.c b/parsers/cxx/cxx_parser.c
index 544ef00..c2bcfcb 100644
--- a/parsers/cxx/cxx_parser.c
+++ b/parsers/cxx/cxx_parser.c
@@ -448,7 +448,10 @@ static bool cxxParserParseEnumStructClassOrUnionFullDeclarationTrailer(
                        );
        }
 
-       if(cxxTokenTypeIs(g_cxx.pToken,CXXTokenTypeOpeningBracket))
+       if(((!g_cxx.pToken->pPrev) ||
+               (g_cxx.pToken->pPrev &&
+                (! cxxTokenTypeIs(g_cxx.pToken->pPrev,CXXTokenTypeAssignment)))) &&
+          cxxTokenTypeIs(g_cxx.pToken,CXXTokenTypeOpeningBracket))
        {
                CXX_DEBUG_PRINT("Found opening bracket: possibly a function declaration?");
                if(!cxxParserParseBlockHandleOpeningBracket())
```

I'm not sure this fix is right or not. Currently our C/C++ parser may be busy. So It will take a bit longer time to fix this. I will take more time for this.

**Comment by masatake** [comment]
It seems that this bug is nothing to do with scope.

```
struct {
  int h;
} s = { 1 };
```

Even in this input `s` cannot be captured.

**Comment by BodoStroesser** [comment]
Thank you for simplifying the testcase so much!

I also tested the patch you suggested. Unfortunately it does not work correctly. The last normal output now is the local variable that previously was missing:

`m                local      2032 /usr/src/apc_add_on/fct4/fct4_init.c } m = {"<Unknown>", "", ""};`

No other 'normal' tags are printed after this.

But: later in the same function different values are assigned to the local variable 'm'. All of these assignments are tagged with a line like the following:

`typeof           function   2127 /usr/src/apc_add_on/fct4/fct4_init.c m = (typeof(m)){"...", "...", "..."};`

While this really is a reference to m, it is tagged as function.

Best regards,
Bodo

**Comment by masatake** [comment]
```
struct {
  int h;
} s = { 1 };
int x;
```

x in not tagged with my patch.

**Comment by BodoStroesser** [comment]
I changed the test to:

```
int f(int p) {
  struct {
    int h;
  } s = { 1 };
  int x;
  s = (typeof(s)){ 2 };
}
```

Without the patch s is missing:
```
f                function      1 testit.c         int f(int p) {
p                parameter     1 testit.c         int f(int p) {
__anonfcf19a730108 struct        2 testit.c         struct {
h                member        3 testit.c         int h;
x                local         5 testit.c         int x;
```

With the patch s is tagged, x no longer is 'local' but 'variable', the tag for typeof IMHO is wrong:
```
f                function      1 testit.c         int f(int p) {
p                parameter     1 testit.c         int f(int p) {
__anonfcf19a730208 struct        2 testit.c         struct {
h                member        3 testit.c         int h;
s                local         4 testit.c         } s = { 1 };
x                variable      5 testit.c         int x;
typeof           function      6 testit.c         s = (typeof(s)){ 2 };
```

**Comment by masatake** [comment]
Thank you.
Good test cases driver developers. 

See #1313.

(But #1309 is really hard to fix for me.)
