### ISSUE TITLE
JSON output is not available on ctags for windows

### ISSUE THREAD

**Issue by vnStrawHat** [universal-ctags/ctags#1312]
I have download latest version of Ctags in here https://ci.appveyor.com/project/masatake/ctags but when I run ctags.exe with arg --output-format=json I got this message "ctags.exe: unknown output format name supplied for "output-format=json".

So, someone can help me build ctags for windows with json output support ?

Thanks.
Sorry for my English.

**Comment by masatake** [comment]
The json output requires libjansson. I don't know how to install it to windows and link it to ctags.
So I have to say "patches are welcome.".

**Comment by k-takata** [comment]
Now the Windows binaries support JSON, XML and YAML.
