### ISSUE TITLE
[RFH] Writing regex language extensions for utags

### ISSUE THREAD

**Issue by t-b** [universal-ctags/ctags#1317]
[Sorry for misusing the issue tracker, I could not find a mailinglist or similiar]

The C++ parser outputs for the following code

```
class MyClass
{
  static MyFunc()
  {
  }
};
```

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/a789d196/
MyClass	test.cpp	/^class MyClass$/;"	c	file:
MyFunc	test.cpp	/^  static MyFunc()$/;"	f	class:MyClass	file:
```

I would like to use the feature to include more information in the tag line, `f` vs `f	class:MyClass	file:` in a parser written using the `--langdef`, `--regex-$lang` interface.
For the following code

```
static Function MyFunc()
End
```

I would like to generate an entry like

```
MyFunc	test.ipf	/^static Function MyFunc()$/;"	f specifier:static
```

but I'm currently stuck using

```
$ctags --langdef=igorpro --langmap=igorpro:.ipf --regex-igorpro='/^[[:space:]]*static[[:space:]]+Function[\/A-Z]*[[:space:]]+([A-Z0-9_]+)\([^:]+$/\1/f,function definition/i' test.ipf
```

with

```
MyFunc	test.ipf	/^static Function MyFunc()$/;"	f
```

Any hints appreciated.

**Comment by masatake** [comment]
> [Sorry for misusing the issue tracker, I could not find a mailinglist or similiar]
This is the place for you; there is no mailing list.

Before starting discussion I would like to know  2 things about you.

Q1. whether you understand 3 important concepts of ctags: kind, field and extra.
Q2. scope of your interest: implementing a parser for igorpro or extending ctags 

If your interest is a parser for igorpro, I recommend you to write it in C with regex.
See parsers/rpmspec.c and parsers/robot.c. In addition I recommend you to learn
kind, field, and extra. If you are tolerant about my broken English. I can provide more
hints to you but I need know your stance first.


If your interest is extending ctags especially  `--regex-<LANG>` feature,  I recoomend
you to learn the output of `./ctags --list-regex-flags` and read docs.ctags.io.

For example you can capture scope information with `scope=` flag.

```
[yamato@master ctags-github]$ cat input.x
cat input.x
CLASS MYCLASS
BEGIN
  static MyMethod()
  BEGIN
  END
END

static MyFunc()
BEGIN
END
[yamato@master ctags-github]$ cat idealX.ctags
cat idealX.ctags
--langdef=idealX
--map-idealX=+.x

--regex-idealX=/^CLASS[ \t]+(.*)/\1/c,class,classes/{scope=push}
--regex-idealX=/^END$///{scope=pop}{placeholder}
--regex-idealX=/([^ \t]+)\(/\1/f,function,functions/{scope=ref}

[yamato@master ctags-github]$ ./ctags -o - --options=./idealX.ctags input.x
<ub]$ ./ctags -o - --options=./idealX.ctags input.x
MYCLASS	input.x	/^CLASS MYCLASS$/;"	c
MyFunc	input.x	/^static MyFunc()$/;"	f
MyMethod	input.x	/^  static MyMethod()$/;"	f	class:MYCLASS     <<< look here
```

**Comment by masatake** [comment]
(I will accept a parser implementation for proprietary language though I stand-by Free software side.
However, there are limitations: (1) a document explaining its syntax is available, (2) and enough test cases are provided.)

**Comment by t-b** [comment]
Thanks for your answer.

> Q1. whether you understand 3 important concepts of ctags: kind, field and extra.

At a basic level, yes.

> Q2. scope of your interest: implementing a parser for igorpro or extending ctags

I've not yet decided. I've dived into the implementation of the `scope` flag in ctags/main/lregex.c and parsers/rpmspec.c.

> (I will accept a parser implementation for proprietary language though I stand-by Free software side.
However, there are limitations: (1) a document explaining its syntax is available, (2) and enough test cases are provided.)

If I'll implement an igor pro parser in c I will definilty describe it properly and also add tests.

**Comment by masatake** [comment]
>>  Q1. whether you understand 3 important concepts of ctags: kind, field and extra.

> At a basic level, yes.

Good. 

> I would like to generate an entry like
```
MyFunc	test.ipf	/^static Function MyFunc()$/;"	f specifier:static
```

So I would like to ask what is "specifier" in the entry: field name or kind name of upper scope?
I would like to know the intent. I guess you meant a field, not a kind of upper scope.

u-ctags extends the concept fields in exuberant-ctags(e-ctags). The fields in e-ctags is parser independent global concept. However, in u-ctags, a parser can define its own fields suitable for the language the parser deals with.

`specifier` field of IgorPro parser looks similar to `properties` field of C parser.

```
[jet@localhost ctags]$ ./ctags  --list-fields=C
#LETTER NAME            ENABLED LANGUAGE         XFMT   JSTYPE DESCRIPTION                   
-       properties      off     C                TRUE   s--    properties (static, inline, mutable,...)
[jet@localhost ctags]$ cat foo.c
static int foo (void) { return 0; }


[jet@localhost ctags]$ ./ctags -o - --fields-C=+'{properties}' foo.c
foo	foo.c	/^static int foo (void) { return 0; }$/;"	f	typeref:typename:int	file:	properties:static
```

**Comment by t-b** [comment]
> specifier field of IgorPro parser looks similar to properties field of C parser.

Yes exactly. static for functions in Igor Pro has a very similiar meaning as in C.

So to rephrase my original question: Is it possible to add additional fields like `properties` via the `--regex-<LANG>` interface? From my understand this is currently not possible and would thus require to exend u-ctags. Correct?

> However, in u-ctags, a parser can define its own fields suitable for the language the parser deals with.

That's good to know, thanks.

**Comment by masatake** [comment]
> So to rephrase my original question: Is it possible to add additional fields like properties via the --regex-<LANG> interface? From my understand this is currently not possible and would thus require to exend u-ctags. Correct?

Sorry, I had to answer this question first. 
With --regex-<LANG> you cannot add an additional field. Extending u-ctags is needed.

Just adding the feature is not difficult. However, I find inconsistency between a parser(crafted parser) written in C and `--regex-<LANG>` based parser(optlib parser). They are not integrated well internally.
As the result though I added many new concept and infrastructure to main part of u-ctags, only crafted parsers get the benefit.

Currently I'm working hard to formalize "base barser/sub parser" concept. After that I will work on integrating crated parser and optlib parser. The integration may be done till next summer, I hope.

So I recommended you to write IgorPro parser in C with regex.
After learning u-ctags code, I find a crated parser can be written 4 ways:

1.  using regex function and callback. This is a simplest one. See yacc and rpmspec parsers.
2. line oriented. See sh.c.
3. simple token based. See python.c.  The way to handle token was implemented in each parsers.
    I read python.c and learn the way. After that I reimplement the routines for reusing in the other parsers. See main/tokeninfo.[ch] and dtd.c.

4. complicated token-chain pased parser. I'm studying this now. See parsers/cxx/. I would like to reimplement this, too.

I forgot writing about the most important things. A test case is very important. It tells what you want.
About writing a parser, I can help only if I know what you want.  See http://docs.ctags.io/en/latest/units.html
Especially `*.b`  suffix. Without writing a test case, you can add a test case for Igor Pro to u-ctags source tree.

**Comment by t-b** [comment]
Thanks @masatake for the comprehensive writeup. You persuaded me that I should write a crafted parser. I'll look into the optios when startings.

**Comment by masatake** [comment]
> >So to rephrase my original question: Is it possible to add additional fields like properties via the --regex- interface? From my understand this is currently not possible and would thus require to exend u-ctags. Correct?

> Sorry, I had to answer this question first.
With --regex- you cannot add an additional field. Extending u-ctags is needed.

Now u-ctags is extended. Newly introduced `--fielddef-<LANG>` option allows you to define
your parser own field, nad `_field` flag allow to attach a data to the defined field by regex pattern.
See #1416.

If you are interested in using the new feature, feel free to open this. I think I can help you to write igorpro parser and I would like to integrate to u-ctags. (After merging #1416).
