### ISSUE TITLE
typedef & issues

### ISSUE THREAD

**Issue by hubertgut** [universal-ctags/ctags#1321]
Tagging the Scintilla editor source PlatWin.cxx: With ctags-16eccf02-x86.zip 3/10/2017
Used custom delimiters in use: ?? |
WINAPI *typedef* 64 |D:\\PlatWin.cxx|  ???? /^typedef BOOL (WINAPI *AlphaBlendSig)(HDC, int, int, int, int, HDC, int, int, int, int, BLENDFUNC/ 
WINAPI *typedef* 65 |D:\\PlatWin.cxx|  ???? /^typedef HMONITOR (WINAPI *MonitorFromPointSig)(POINT, DWORD);$/ 
WINAPI *typedef* 66 |D:\\PlatWin.cxx|  ???? /^typedef HMONITOR (WINAPI *MonitorFromRectSig)(LPCRECT, DWORD);$/ 
WINAPI *typedef* 67 |D:\\PlatWin.cxx|  ???? /^typedef BOOL (WINAPI *GetMonitorInfoSig)(HMONITOR, LPMONITORINFO);$/ 

A lovely piece of code which also is tagging fast! 
There are two alterations I would welcome very much:
1. Regarding querying of ctags. Queries cannot be combined thus multiple invoking is requested.
2. Regarding line length limitation. You focus on Vi (512 chars). 
Referencing filenames can free considerable space, enhance overview and allow later truncation of entries. 
Strictly speaking this is not a format change but an extension or option. 
D:\\_User_Xyz\\_Source\\___Controls Selected\\_Scintilla CsWrapper\\ctags docu\\FileName.cxx
Ref:\\#3	 (having filenames in an output file)

**Comment by masatake** [comment]
How about adding `-D WINAPI` as option:
```
[jet@localhost ctags]$ cat bar.cxx 
typedef BOOL (WINAPI *AlphaBlendSig)(HDC, int, int, int, int, HDC, int, int, int, int, BLENDFUNCTION);
typedef HMONITOR (WINAPI *MonitorFromPointSig)(POINT, DWORD);

[jet@localhost ctags]$ ./ctags -D WINAPI -o - bar.cxx
AlphaBlendSig	bar.cxx	/^typedef BOOL (WINAPI *AlphaBlendSig)(HDC, int, int, int, int, HDC, int, int, int, int, BLENDFUNC/;"	t	typeref:typename:BOOL (*)(HDC,int,int,int,int,HDC,int,int,int,int,BLENDFUNCTION)	file:
MonitorFromPointSig	bar.cxx	/^typedef HMONITOR (WINAPI *MonitorFromPointSig)(POINT, DWORD);$/;"	t	typeref:typename:HMONITOR (*)(POINT,DWORD)	file:
[jet@localhost ctags]$ 
```

However, I guess we can improve the routine  parsing function pointer declaration by tagging only the last token inside parenthesis. I have to think this more.


> Regarding querying of ctags. Queries cannot be combined thus multiple invoking is requested.

I don't understand this, What is query here? An example is needed. Are you talking about readtags?

> Regarding line length limitation. You focus on Vi (512 chars).
Do you mean the default value, 96 is too short?
As far as I can remember this limitation is applied only to patterns, not applied to file names.
Am I wrong?

**Comment by hubertgut** [comment]
Thanks for the prompt reply masatake

Quoting: Retrieving internal settings e.g. "--list-languages", "--list-kinds=all" ...
-D option might not be the ideal solution considering uncountable projects tagging

Please take others just as a note

**Comment by masatake** [comment]
> Quoting: Retrieving internal settings e.g. "--list-languages", "--list-kinds=all" ...

I guess you mean "query", not "Quoting".
I think mixed outputs of `--list-*` options may make users panic. The outputs may be too complicated.
However, I'm thinking about introducing "--describe-language=<LANG>" or "--desscribe-parsr=<LANG>".

> -D option might not be the ideal solution considering uncountable projects tagging

I see.

**Comment by masatake** [comment]
Simplified the test case:
```
typedef void (WINAPI *a) (void);
typedef void (WINAPI  b) (void);
```

**Comment by masatake** [comment]
I merged my changes that fix the bug reported here. Feel free reopning this if the bug is not fixed with my change.
