### ISSUE TITLE
Can't get yaml parsing working

### ISSUE THREAD

**Issue by haizaar** [universal-ctags/ctags#1322]
I've built ctags from master (rev cbbf4fe). And I can't get the yaml pasring  working:

```
$ ./ctags --list-languages |grep -i yaml
Yaml
$ cat /tmp/my.yml
a:
  b:
    c: 1
$ ./ctags /tmp/my.yml
$ cat tags 
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/cbbf4fe/
```

Am I missing something?

**Comment by masatake** [comment]
Currently yaml parser tags only anchors and alias(only when `r`(reference extra tag) is enabled).

For 
```
a:
  b:
    c: 1
    d: something
```

What kind of output do you expect?
`a`, `b`, `c`, and `d`? How about `something`?

**Comment by haizaar** [comment]
Thank you for clarifying. Since I'm new to ctags, I'll try to annotate my
files with anchors and see how it goes.

I need it for vim to help me working with large swagger schema​ definition
yaml files. For this use case, generating tags for first two levels of keys
is perfect. However since it may be worth creating a dedicated parser
(plugin) for swagger.

P.S. running `ctags --list-kinds` reveals that anchors misspelled as
"anchros".

**Comment by haizaar** [comment]
Tried with anchors - works fine. Thanks!

**Comment by masatake** [comment]
> However since swagger format is quite specific, it may be worth creating a dedicated parser (plugin) for swagger.

That is the point.
I'm working on implementing an infrastructure (API) for writing subparsers on a base parser.
In your case yaml is a base parser and swagger is a subparser.

> P.S. running `ctags --list-kinds` reveals that anchors misspelled as "anchros".

Thanks. Fixed in HEAD.

**Comment by haizaar** [comment]
Great. I'll appreciate if you update this post when the API is ready, so I can try it out.

**Comment by masatake** [comment]
I submit a patch set for implementing a subparser. https://github.com/universal-ctags/ctags/commit/9ac9b7a0f666234dcb1eff6486f6b0fd93d6d299

Swagger parser can be implemented on yaml parser with this new infrastructure. However, it is not enough.
Token API is not powerful enough. After implementing the token API, I can work on swagger parser. It takes more time.

**Comment by t-b** [comment]
I found this issue as ctags could not find anything in my gitlab-ci.yml files.
As I'm only interested in the array names starting at the start of line I added 

```
--kinddef-Yaml=a,array,array at start of line
--regex-Yaml=/^([[:graph:]]+):[[:space:]]*^/\1/a/i
```

to my ctags config file. Works so far :)

**Comment by masatake** [comment]
See #3245 and #3254. Now OpenAPI/Swagger parser is available.
