### ISSUE TITLE
make check failing test cases. (Linux 64-Bit Ubuntu 16.04)

### ISSUE THREAD

**Issue by AmeyaVS** [universal-ctags/ctags#1348]
I am building from the master branch of universal-ctags.
Below are the configuration, build and check commands, I currently use(since I don't have root access on the system.):

```sh
# From universal-ctags source directory
$ mkdir objdir
$ cd objdir
$ ../configure --prefix=$HOME/apps/ctags --program-prefix=u_
$ make -j4
$ make check
``` 

Below is the truncated log of the make check output:

```text
Summary (see CMDLINE.tmp to reproduce without test harness)
------------------------------------------------------------
  #passed:                                720
  #FIXED:                                 0
  #FAILED (unexpected-exit-status):       0
  #FAILED (unexpected-output):            21
	parser-c.r/bit_field.c
	parser-c.r/bug1466117.c
	parser-c.r/bug1491666.c
	parser-c.r/bug556646.c
	parser-c.r/c-struct-var-with-initializer
	parser-c.r/enum.c
	parser-cxx.r/bug639639.cpp
	parser-cxx.r/bug639644.cpp
	parser-cxx.r/cxx11-lambdas
	parser-cxx.r/cxx11enum.cpp
	parser-cxx.r/namespace.cpp
	parser-cxx.r/templates-in-labmdas-1.cpp
	parser-cxx.r/templates-in-labmdas-2.cpp
	parser-cxx.r/typedefs.cpp
	parser-javascript.r/js-complex-return
	parser-javascript.r/js-es6-class
	parser-javascript.r/js-es6-mixin
	parser-javascript.r/js-many-functions
	parser-yacc.r/c-anon-ids
	parser-yacc.r/nested
	xformat-option.r/format-NlKkFnP
  #TIMED-OUT (10s)                        0
  #skipped (features):                    1
	parser-ant.r/regex-based
  #skipped (languages):                   4
	main-xcmd.r/xcmd-coffeetags-pseudo
	main-xcmd.r/xcmd-coffeetags
	main-xcmd.r/xcmd-etags
	main-xcmd.r/xcmd-xref
  #known-bugs:                            12
	parser-autoconf.r/nested-block.ac
	parser-c.r/attr-attached-to-array-failed
	parser-c.r/extern_variable.h
	parser-cxx.r/cxx-keywords-as-c-identifiers
	parser-cxx.r/cxx-keywords-as-c-identifiers
	parser-cxx.r/namespace-and-scope
	parser-cxx.r/variables-prototypes.cpp
	parser-java.r/bug1777344.java
	parser-m4.r/m4-quotestring
	parser-python.r/newlines-cr
	parser-scheme.r/scheme-srfi-30-comment
	parser-scheme.r/scheme-string
Makefile:6271: recipe for target 'units' failed
make: *** [units] Error 1
```

Sorry for populating the issue page, since I could not find the discussion portal (gitter/irc etc.).

**Note:** I have installed the following dependencies:
```
$ sudo apt install libyaml-dev libxml2-dev libjansson-dev
```

Let me know if I have missed any other dependencies.

-Ameya

**Note:** Updated the build steps for object directory for out of source tree build.

**Comment by masatake** [comment]
Thank you for reporting.

> $ ../configure --prefix=$HOME/apps/ctags --program-prefix=u_

I wonder why you invoke configure at the parent directory.

**Comment by masatake** [comment]
Could you run ` make check TRAVIS=1 ` ?

With `TRAVIS=1`, the test harness reports the diffs between expected output and unexpected-output.
The diffs help me understand what happens on your pc.

If the diffs are too large, putting some parts of lines is o.k.

**Comment by AmeyaVS** [comment]
I have updated the original post and added the diff log for your reference.
Thank you for the quick response.
-Ameya
[ctags_check_diff.txt](https://github.com/universal-ctags/ctags/files/944967/ctags_check_diff.txt)

**Comment by masatake** [comment]
Thank you for preparing the diff. 

There are reproduced.

I found two issues.
One is about anonymous name generator. It uses a hash value calculated from an input file name.
You run "make check" in a build directory which differs from the source directory.
As the result the generated names in you got by running "make units" are different from the generated names expected. I have to fix this but I wonder how can I do it...

Another one is about the bug of test harness. This is not difficult to fix.

Anyway these are not bugs of ctags command. These are bugs about the test harness of ctags.

**Comment by masatake** [comment]
@AmeyaVS, could you try #1351?

**Comment by masatake** [comment]
See also #1353.

**Comment by masatake** [comment]
`xcmd-tag-relative-option.d` still fails. This test case als reports memory leaks.
Looks very strange.

**Comment by AmeyaVS** [comment]
Hi,

With the #1351 :
These are the results of make check 
[ctags_check_diff1531.txt](https://github.com/universal-ctags/ctags/files/948688/ctags_check_diff1531.txt)
It seems the changes are good.
As for the #1353 I am not seeing much change, I will try to look into it further.

-Ameya

**Comment by masatake** [comment]
Thank you.

**Comment by masatake** [comment]
After merging the both PRs, none failure is reported.
The failure of xcmd-tag-relative-option.d is gone.  I wonder why...

```
make units UNITS=xcmd-tag-relative-option VG=1
```
Above command line reports a memory leak but it is nothing to do with this issue.

**Comment by masatake** [comment]
I found that `xcmd-tag-relative-option` is a test case available only my note PC:-P.

Now all test cases are passed. Please, close this if everything is o.k.

**Comment by AmeyaVS** [comment]
Thank you for your kind support.
Verified from the latest commits in master.
Closing the issue.
