### ISSUE TITLE
avoid mktemp for -f- mode

### ISSUE THREAD

**Issue by hanwen** [universal-ctags/ctags#1350]
I am currently running ctags inside a user namespace sandbox on Linux for security reasons. This is a little fidgety; one source of problems is that the -f -  (stdout output)  creates a temporary file, which requires correct setup of /tmp/ in the sandbox.

It would be great if that could be avoided. I tried using mio_new_memory() to replace the tempFile call, but somehow it eats all newlines. Alternatively, (preferred) the writes could go directly to the stdout filedescriptor. I can sort the output data myself.

**Comment by masatake** [comment]
When you specify both `-o -` and `--sort=no`,  ctags should not open a temporary file.
I'm working on this issue in #1352.

**Comment by masatake** [comment]
Could you try the latest code?
With `-o - --sort=no` option, ctags doesn't make a temporary file.
