### ISSUE TITLE
In -I, + cannot be combined with =

### ISSUE THREAD

**Issue by pskocik** [universal-ctags/ctags#1357]
I'd expect that either -I FOO+=BAR or -I FOO+=BAR would cause things like FOO(A,B,C) to be replaced with BAR, but it doesn't work this way.
(A probably even better solution would to use a full blown c-preprocessor to do the replacements).

**Comment by masatake** [comment]
Could you show me an example input file?
I don't understand what you want.

**Comment by pskocik** [comment]
It's just that ctags isn't handling my macro-heavy C project very well. (Like I'm wrapping curly braces in macros to emulate RAII, and stuff like that and ctags won't parse it). But it's no big deal. I guess I don't really need ctags anyway.

**Comment by masatake** [comment]
What I was thinking about was `-D`. But there is no way to know how useful it is.

**Comment by pskocik** [comment]
`-D` (i.e., expanding selected macros with a proper c-preprocessor for the purposes of ctag parsing) would be great. It'd effectively solve all the macro-related problems.

**Comment by masatake** [comment]
`-D` is already implemented. 

>  I guess I don't really need ctags anyway.

I'm bad in English so I always ask people to show an exmaple input and tags file expected.
If you are interested in C preprocessing in ctags, please, show them. I don't understand what you want.

**Comment by pskocik** [comment]
Thanks for letting me know. I didn't know about it. I had only read the manpage.

Unfortunately, it's not working for me. I guess I could get ctags to work for me if I could get it to process something like:

```C
M(int, foo, bar, int x)
FN_b({)
FN_e(}, {
       /*dtors*/
})
```
and parse it as

```
int foo__bar(foo *this, int x)
{
}
```
These macros do that:
```c
#define M(Ret,Class,Method,...) Ret Class##__##Method(Class *this, ##__VA_ARGS__)
#define FN_b(...) { /*not really this, but this is what ctags should see*/
#define FN_e(...) } /*not really this, but this is what ctags should see*/
````
But if I pass them to `ctags` like so:
```shell
rm tags; ctags -D 'M(Ret,Class,Method,...)=Ret Class##__##Method(Class *this, ##__VA_ARGS__)' -D 'FN_b(...)={' -D 'FN_e(...)=}' test.c   && cat tags
```
it doesn't work

**Comment by pragmaware** [comment]
I guess it's the unbalanced "{" passed as a macro argument...

**Comment by masatake** [comment]
@pragmaware,
The result of expansion looks strange.

```
[jet@localhost]~/var/ctags% cat args.ctags
-D M(Ret,Class,Method,...)=Ret Class##__##Method(Class *this, ##__VA_ARGS__)
[jet@localhost]~/var/ctags% cat input.c
M(int, foo, bar, int x)
[jet@localhost]~/var/ctags% ./ctags --options=./args.ctags -o - input.c
./ctags --options=./args.ctags -o - input.c
...
            [cxxParserParseNextToken][at 1] The token has replacements: applying
            [>> cxxParserParseNextTokenApplyReplacement][at 1] 
                [cxxParserParseNextTokenApplyReplacement][at 1] Applying complex replacement 'int fooint xbar(foo *this,int x)'
```

**Comment by masatake** [comment]
```
    [saveMacro][at 0] Found token paste operator
    [saveMacro][at 0] Check token '__'
    [saveMacro][at 0] Parameter replacement part: 3 (vararg 1)
```

It seems that `__` is not recognized as a constant replacement part.

**Comment by pragmaware** [comment]
Yep. Bug is probably here.

				bool bIsVarArg = strncmp(tokenBegin,"__VA_ARGS__",tokenLen) == 0;

should add a (tokenLen == 11) just before strncmp.

**Comment by masatake** [comment]
I found the same just NOW.

**Comment by pragmaware** [comment]
:)

I haven't tried but I guess that also the unbalanced { as macro parameter may give problems.

**Comment by pragmaware** [comment]
In cxxParserParseNextTokenSkipMacroParenthesis() we might avoid creating subchains on { and [, so they don't need to match. I guess the preprocessor ignores these.

**Comment by masatake** [comment]
```
diff --git a/parsers/cpreprocessor.c b/parsers/cpreprocessor.c
index 95c0c50..e66d981 100644
--- a/parsers/cpreprocessor.c
+++ b/parsers/cpreprocessor.c
@@ -1552,10 +1552,10 @@ static void saveMacro(const char * macro)
 
 				// check if it is a parameter
 				int tokenLen = c - tokenBegin;
+				bool bIsVarArg = ((tokenLen == 11) && (strncmp(tokenBegin,"__VA_ARGS__", 11) == 0));
 
-				CXX_DEBUG_PRINT("Check token '%.*s'",tokenLen,tokenBegin);
-
-				bool bIsVarArg = strncmp(tokenBegin,"__VA_ARGS__",tokenLen) == 0;
+				CXX_DEBUG_PRINT("Check token '%.*s'%s",tokenLen,tokenBegin,
+								bIsVarArg? " (va args)": "");
 
 				int i = 0;
 				for(;i<iParamCount;i++)
```

**Comment by masatake** [comment]
@pragmaware, I would like you to see #1345, too.

**Comment by pskocik** [comment]
Thanks for looking at it!
