### ISSUE TITLE
alignas not handled correctly on structs

### ISSUE THREAD

**Issue by olson-dan** [universal-ctags/ctags#1374]
Using this version:

Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May  8 2017, 05:30:49
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +multibyte, +case-insensitive-filenames

If I create these two objects:

```
struct alignas( 64 ) AlignasTestStruct
{
};

class alignas( 64 ) AlignasTestStruct2
{
};
```

ctags will generate a tag for AlignasTestStruct2 but AlignasTestStruct will be ignored.

**Comment by masatake** [comment]
Thank you for reporting. 
Please, try #1375.
