### ISSUE TITLE
Large C array definition blows up ctags memory use

### ISSUE THREAD

**Issue by dtikhonov** [universal-ctags/ctags#1378]
As of c603db3dcd, the following occurs:

```
[dmitri@ubuntu-dmitri ctags]$ wc -l t.c
10005 t.c
[dmitri@ubuntu-dmitri ctags]$ ctags -fx t.c
ctags: cannot sort tag file : Cannot allocate memory
[dmitri@ubuntu-dmitri ctags]$
```

Stock `ctags` works fine:

```
[dmitri@ubuntu-dmitri ctags]$ /usr/bin/ctags -fx t.c
ctags: Warning: Ignoring non-option in ./.ctags

[dmitri@ubuntu-dmitri ctags]$ cat x
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME      Exuberant Ctags //
!_TAG_PROGRAM_URL       http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.9~svn20110310 //
IOV     t.c     1;"     d       file:
myarray t.c     /^static struct mystruct myarray[] =$/;"        v       typeref:struct:mystruct file:
[dmitri@ubuntu-dmitri ctags]$
```

I am attaching t.c: 
[t.c.txt](https://github.com/universal-ctags/ctags/files/991679/t.c.txt)

**Comment by masatake** [comment]
Interesting. I would like to try to fix this one to understanding the new C parser well.

**Comment by masatake** [comment]
To understand the issue, I introduce a smaller example input:
```
int foo [] = {
	1
};
```
To solve this issue, C parser has to have an ability to ignore the "1" which is inside array 
initializer. 

@pragmaware, how do you think about following approach?
`do_reduce_elements` is a stub.

When the parser parse a block the parser may know whether the block is values for array/structure initialization. Actually when I turned on tracer I found:

```
 [<< cxxParserParseBlockHandleOpeningBracket][at 7] Handled array or list-like initialisation or return
```

If the block is for the initialization, `cxxParserParseAndCondenseSubchainsUpToOneOf` can change
its behaviour.

```
 bool cxxParserParseAndCondenseSubchainsUpToOneOf(
 		unsigned int uTokenTypes,
-		unsigned int uInitialSubchainMarkerTypes
+		unsigned int uInitialSubchainMarkerTypes,
+		bool bCanReduceInnerElements
 	)
 {
 	CXX_DEBUG_ENTER_TEXT("Token types = 0x%x(%s)", uTokenTypes, cxxDebugTypeDecode(uTokenTypes));
@@ -171,7 +175,8 @@ bool cxxParserParseAndCondenseSubchainsUpToOneOf(
 			} else {
 				if(!cxxParserParseAndCondenseCurrentSubchain(
 						uInitialSubchainMarkerTypes,
-						(uTokenTypes & CXXTokenTypeEOF)
+						(uTokenTypes & CXXTokenTypeEOF),
+						bCanReduceInnerElements
 					)
 				)
 				{
@@ -190,6 +195,8 @@ bool cxxParserParseAndCondenseSubchainsUpToOneOf(
 						"Got terminator subchain token 0x%x",
 						g_cxx.pToken->eType
 					);
+				if (bCanReduceInnerElements)
+					do_reduce_elements(...);
 				return true;
 			}
--- a/parsers/cxx/cxx_parser_block.c
+++ b/parsers/cxx/cxx_parser_block.c
@@ -93,7 +93,8 @@ bool cxxParserParseBlockHandleOpeningBracket(void)
 		bool bRet = cxxParserParseAndCondenseCurrentSubchain(
 				CXXTokenTypeOpeningBracket | CXXTokenTypeOpeningParenthesis |
 					CXXTokenTypeOpeningSquareParenthesis,
-				false
+				false,
+				true
 			);
 
 		CXX_DEBUG_LEAVE_TEXT("Handled array or list-like initialisation or return");
```

**Comment by masatake** [comment]
In the last comment, I inserted `do_reduce_elements` to the wrong place.

I implmented my idea and submit it as #1380.

@dtikhonov, could you try #1380?

Instead of reducing, skipping is another approach. However, for implementing "reference tags" in C parser, I would like to keep the current code.

**Comment by dtikhonov** [comment]
@masatake, I would try it, but I can't figure out how to get a usable diff from this link: https://github.com/universal-ctags/ctags/pull/1380/files

There has to be an easy way to do it, but I do not know it.

**Comment by masatake** [comment]
With following steps, you will get a source tree in which my commis are merged.

```
git checkout -b masatake-cxx-reducer master
git pull https://github.com/masatake/ctags.git cxx-reducer
```

**Comment by dtikhonov** [comment]
@masatake, this makes the problem go away -- thanks!

**Comment by dtikhonov** [comment]
> I can't figure out how to get a usable diff from this link: https://github.com/universal-ctags/ctags/pull/1380/files

To answer my own question: the trick is to add `.diff` to the end of the pull request URI: I can't figure out how to get a usable diff from this link: https://github.com/universal-ctags/ctags/pull/1380.diff

**Comment by pragmaware** [comment]
LGTM
