### ISSUE TITLE
Extended regression environment

### ISSUE THREAD

**Issue by vhda** [universal-ctags/ctags#140]
Build a script that is able to download a set of files from the internet, place them under "Units" and generate an expected.tags file using an older version of ctags binary. There should be a configuration file that lists the tar balls that need to be downloaded, using a format like:

```
language;http://link/to/file.tar.gz
```

This is intended only to find regressions that may not be covered by a specific test unit.
Note: a new test unit must be manually created if such a regression is found.

**Comment by masatake** [comment]
I'm working on this issue very hard these days.

https://github.com/masatake/srpmix7

It is not ready for public use. When it is ready, I will report it here.

**Comment by masatake** [comment]
Now srpmix7 can expand dsc/deb source.
After some code clean-up, I will study how to utilize it with ctags development.

**Comment by masatake** [comment]
To think about performance of parsing, we need large code base.
I will revise `--totals` option. I guess I have broken the option in past development.

**Comment by masatake** [comment]
See https://github.com/universal-ctags/codebase
I designed "codebase" for performance measurement.
However, we can extend it to an environement and target for regression test.
