### ISSUE TITLE
Allows dashes in Robot identifiers

### ISSUE THREAD

**Issue by mMontu** [universal-ctags/ctags#1406]
As far as I understand it is valid to use dashes in Robot keyword. But when the tags are generated the identifier stops before the dash:

```
My Keyword	../path/to/my/file.robot	/^My Keyword - Closed$/;"	k
My Keyword	../path/to/my/file.robot	/^My Keyword - Open$/;"	k
```

Thus it isn't possible to jump to tags using `My Keyword - Closed` and `My Keyword - Open`, despite they are clearly present in tags file

**Comment by masatake** [comment]
Could you show  me small example input file?

It is needed to write a test case. However, I don't know Robot.

**Comment by masatake** [comment]
Oh, sorry. 

```
My Keyword - Open
```

is an example.
O.k. I will make a fix.

**Comment by mMontu** [comment]
Sorry, this could be used as an input file:
```

*** Keywords ***

My Keyword - Closed
    Sleep  5s

My Keyword - Open
    Sleep  5s

```

**Comment by masatake** [comment]
Thank you!

**Comment by masatake** [comment]
Robot parser treats " " and "_" in special way; it an convert "Foo Bar" to "Foo_Bar" vice versa.
How about "-" ? Do you think Robot parser should do something char conversion?
What I got for the input is

```
My Keyword - Closed	input.robot	/^My Keyword - Closed$/;"	k
My Keyword - Open		input.robot	/^My Keyword - Open$/;"		k
My_Keyword_-_Closed	input.robot	/^My Keyword - Closed$/;"	k
My_Keyword_-_Open	input.robot	/^My Keyword - Open$/;"		k

```

These are good enough?

**Comment by mMontu** [comment]
I'm pretty confident that only "_" is interchangeable with spaces, but I'll get a documentation reference.

I thinks the output you got is perfect :)

**Comment by masatake** [comment]
Fixed in #1408. Thank you for reporting this.

**Comment by mMontu** [comment]
I couldn't find very explicit in the documentation; I got this:

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-types
> Robot Framework variables, similarly as keywords, are case-insensitive, and also spaces and underscores are ignored. 

Man, both your response and the fix were incredibly fast
Thank you very much!!

**Comment by masatake** [comment]
Thank you. I understand that the conversion is related to  paces and underscores, nothing to do with dashes.

**Comment by mMontu** [comment]
I've built the new version, and it works like a charm!
