### ISSUE TITLE
Some C functions are not present in tags

### ISSUE THREAD

**Issue by bmansurov** [universal-ctags/ctags#1414]
Hi,

Only two functions from the file [ghash.h](https://github.com/GNOME/glib/blob/master/glib/ghash.h) are present in the output: [g_hash_table_freeze](https://github.com/GNOME/glib/blob/master/glib/ghash.h#L147) and [g_hash_table_thaw](https://github.com/GNOME/glib/blob/master/glib/ghash.h#L148).

[g_hash_table_new](https://github.com/GNOME/glib/blob/master/glib/ghash.h#L57), for example, is not present.

**Comment by masatake** [comment]
Use `--kinds-C=+p` option.
BTW, `g_hash_table_freeze` and `g_hash_table_thaw` are macros, not function.

**Comment by bmansurov** [comment]
@masatake Thanks for the reply. No luck, I've also tried `--C-kinds=+p`, but without luck again. What else can I try?

If those two functions are macros, that's why they got picked up, I guess. From the user point of view, they are described as [functions](https://developer.gnome.org/glib/2.28/glib-Hash-Tables.html#g-hash-table-thaw) though.

**Comment by bmansurov** [comment]
OK, it's working now. I had to pass `--c-kinds=+p ` right after `ctags`. Earlier I was writing this flag at the end of the command, which didn't work. Thanks again!

**Comment by masatake** [comment]
ctags captured the two because they are macros.
