### ISSUE TITLE
Incorrect handling of types causes a segfault on armv7l (e.g., Raspberry Pi)

### ISSUE THREAD

**Issue by wbkang** [universal-ctags/ctags#1423]
Hello,

I was excited to try out your project on my Raspberry Pi but ctags died with a segfault. After running it through gdb, I found the root cause:
```
// main/kind.h
#define KIND_GHOST_INDEX -1
#define KIND_FILE_INDEX -2
// main/parse.c
extern kindDefinition* getLanguageKind (const langType language, char kindIndex)
{
	kindDefinition* kdef;

	Assert (0 <= language  &&  language < (int) LanguageCount);

	switch (kindIndex)
	{
	case KIND_FILE_INDEX:
		kdef = LanguageTable [language].fileKind;
		break;
	case KIND_GHOST_INDEX:
		kdef = &kindGhost;
		break;
	default:
		kdef = getKind (LanguageTable [language].kindControlBlock, kindIndex);
	}
	return kdef;
}
```

On armv7l, char type is actually unsigned. So doing a switch on an unsigned value `kindIndex` with a negative case value actually does not work. My suggestion is to fix the type of `kindIndex` specifically to `signed char`. All unit tests pass if I make that change as well.

**Comment by masatake** [comment]
Thank you for reporting and fixing this.
I will add #1428 , too.
