### ISSUE TITLE
End line for java

### ISSUE THREAD

**Issue by adrianmay** [universal-ctags/ctags#1425]
For some reason I don't get the end:123 field for java files like I do for C/C++ files when I specify --fields=e. 

Is this an oversight or is it hard for some reason?

**Comment by masatake** [comment]
Only some parsers implements `end:` field. Java parser does not.

**Comment by adrianmay** [comment]
I'd be very grateful if it did or if you could help me implement it. It's actually the only reason I'm using the software. My motivation is that I'm trying to find out which functions a source control commit affects, so that I can run statistics about which functions have a historical tendency to change together. I know that git and hg both attempt this, but they both get it wrong.

**Comment by masatake** [comment]
"Of course, a patch is welcome", is the motto of this project.

Java parser is implemented in parsers/c.c.  

As you wrote C/C++ parsers can record end: field. C/C++ parser is newly written by @pragmaware who started rewriting it not to maintain the old C/C++ parser. He though it is hard to maintain the old C/C++ parsers.

Java parser is implemented as a variant of the old C/C++ parser.
To add end: to Java parser, there are two ways. 

1. understanding c.c and changing it
2. as @pragmaware did, writing new Java parser

 Anyway, to add `end:` field, you want to use CorkAPI.

Step for adding `end:` 

0. study javascript language quickly if you don't know.
1. read a javascript parser (jscript.c) and understand how `initTagEntry` and `makeTagEntry` functions are used.
    makeSimpleTag doesn't help you.
2. read http://docs.ctags.io/en/latest/internal.html#cork-api
3. See following patch. I have tried to add end: to JavaScript  parser. The change is not perfect but it will help you to understand how to add end:. 
https://gist.github.com/masatake/b09f530f5b1376b909a62bb54e74e533

4. Do the same existing Java parser or your new Java parser.
5. Run existing test: make units and make units VG=1
6.  Write your own test cases to verify end: field is recorded well. See http://docs.ctags.io/en/latest/units.html#units-test-facility
7. make a pull request

Good luck!

**Comment by adrianmay** [comment]
Well I've been struggling with this but it isn't making much sense to me. The structure of c.c and jscript.c look completely different. In the latter, the function findCmdTerm appears to be the crucial one that skips to the closing brace of the function, but I'm not finding an equivalent in c.c. Also, if there's currently no usage of cork in c.c, why would I need to convert it now? 

To me it seems that if the endLine feature is desirable for C and C++, then there seems no reason to omit it for java or other popular languages. This would probably be a lot easier for someone who's already familiar with the code. Although this looks like a great project that I'd love to contribute to, you have to understand that for me it's just a small part of a bigger picture and if I let myself get bogged down in details like this I'll never get anything finished. Does it really make sense for me to familiarise myself with all this code just to implement one little feature and then forget it all again? My alternative is to count {}s from the start-line tags to the end of each function, and I think I can do that using my existing knowledge. It's a messy solution, and I'd rather the tags generator did it all, but that's not really a good enough reason for me to get side-tracked into this project. 

I'd be really grateful if somebody who already knows the code would fill this hole, but I honestly don't think I can justify to my boss why I'm spending time on this.

**Comment by masatake** [comment]
> I'd be really grateful if somebody who already knows the code would fill this hole

I agree with you, but I honestly don't think I can find a person who already knows the code well.
Such person was in Exuberant-ctags project.
