### ISSUE TITLE
Problem with complex C definitions

### ISSUE THREAD

**Issue by LemonBoy** [universal-ctags/ctags#1431]
I apologize in advance for the huge test case, when ctags is run on [this](https://github.com/vim/vim/blob/master/src/globals.h) file all the `EXTERN` variables are lumped together under the `INIT` name.

**Comment by masatake** [comment]
ctags doesn't know INIT so you have to tell it to ctags like

```
 ./ctags -IINIT -IEXTERN=extern --kinds-C=+x globals.h
```

See ctags.1 man page about the options.

**Comment by LemonBoy** [comment]
I see, I expected ctags to pull some magic heuristic trick :)
Sorry for the noise.
