### ISSUE TITLE
No rule for creating html version of manpage

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#1435]
See #1433.

A makefile rule for creating `man/ctags.1.html` from `man/ctags.1.rst` is needed.
We can use rst2html for it, however some part is wrongly marked up. https://github.com/universal-ctags/ctags/pull/1433#issuecomment-305650424

**Comment by masatake** [comment]
(python-docutils git mirror: http://repo.or.cz/docutils.git)
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#option-lists

It seems that square brackets notation is not supported in docutils.
Extending docutils may be one of approach but I'm not sure whether it is acceptable or not.

I'll look into this topic more.

**Comment by masatake** [comment]
``--foo-<LANG>`` also cases a trouble of rendering. Different from the bracket issue, this notation is not so popolar. So I think we cannot fix docsutils side. So I will convert the items using "option list" notation to using "definition list" notation with inline markup. I will do this incrementally. As far as  my understanding, you don't have to do nothing your side.
