### ISSUE TITLE
RFC: removing XCMD feature

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1442]
I will remove XCMD from the planed first stable release(6.0).

I like the idea but it makes difficult to keep the consistency of ctags internal.
I guess only a few people using the feature. 

Universal-ctags manages kinds more strictly than Exuberant-ctags.
Many of tags generators(xcmds) for specific languages models Exuberant-ctags.
The current Universal-ctags cannot fill the gap in kinds managment.

One of the way to go is that Universal-ctags defines better protocol between
Universal-ctags and xcmds that fill the gaps. However, to define such
protocol, I need much more experiences.

#705 (Process Multiple files with xcmd ) porints the critical weakness of
XCMD feature.

If you are using the feature and you like it, plesae add comments here. Based on the comments, I will revise the feature in 7.0 or later.  

The thumb  down reaction implies "I want it".

TODO: I have to notify this to CoffeeTags people.

**Comment by masatake** [comment]
@kopischke, thank you for the feed-back. Could you tell me how you use xcmd?

**Comment by kopischke** [comment]
@masatake for ripper-tags integration (supported as of [this PR](https://github.com/tmm1/ripper-tags/pull/42)). ctags’ stock Ruby tagging is laughably bad (Ruby’s fault for being a metaprogramming maze, not ctags).

**Comment by masatake** [comment]
@kopischke, I see. Thank you.
