### ISSUE TITLE
Make man pages avaiable on http://docs.ctags.io/en/latest/

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1444]
Derived from #1435.

**Comment by masatake** [comment]
@cweagans, do you know whose account on ReadTheDocs is used to generate http://docs.ctags.io?

I would like to put man/*.html to the web site, too. However, the seeting on ReadTheDocs service is needed.

**Comment by cweagans** [comment]
I believe it's on my account. What do you need me to do?

**Comment by masatake** [comment]
@cweagans, thank you for the response.

We (@k-takata and I) are working for releasing 6.0(or 5.9).
In the work, we are updating ctags.1 and the other man pages. Some of contents are converted from the hacking guide.

I would like to ask you to setup "automatic uploading"  man/*.html to http://docs.ctags.io/ as you did in docs/ directory.
The html files can be generated with doing "cd man; make" if rst2html command, which is part of python-docutils is available.

**Comment by cweagans** [comment]
That's not going to be possible. Read The Docs is the service that's used for the documentation site, and they only deal with .rst or .md files in a single directory. To solve this, I recommend updating your Makefile to build a complete .rst that gets put into the docs/ directory. This way, it will go through the existing process and won't have any problems with RTD.

**Comment by masatake** [comment]
Oh, I see... The html files are generated from .rst.in files. ./configure must be run before generating .rst files.
I have to find a method satisfying RTD. Thank you.

**Comment by alphaCTzo7G** [comment]
I installed universal tags by compling from the source.

I noticed that `ctags` help can be accessed by `ctags --help`. Is this the way to get the documentation on the command line. 

Is there a more detailed `man` page available at the command line? I am guessing most people using ctags, use the command line, so having man pages available would be helpful.

**Comment by masatake** [comment]
@alphaCTzo7G, you can find it in man/.
See https://github.com/universal-ctags/ctags/tree/master/man

The man pages are not updated enough yet.
