### ISSUE TITLE
Could you start maintaining "github releases"?

### ISSUE THREAD

**Issue by Myz** [universal-ctags/ctags#1452]
It would be very nice for our internal build tool to have the releases as a "github release" so out bot can parse the /releases page to determine the latest package.

https://github.com/universal-ctags/ctags/releases

Might this be possible or is it too much effort?
Thanks in advance.

**Comment by NoctuaNivalis** [comment]
See #1038, #661 and #1272.

**Comment by Myz** [comment]
Thanks, at some day I will learn how to use the search bar, sorry....

**Comment by Myz** [comment]
Since you are using the `packcc` as a direct dependency to the ctags build, it might be necessary to have source releases that bundle a fully buildable archive.

If you download the bundled zip archive from the github page now, extract it and then try to configure and build it, it will not work because the `autogen.sh` contains this git commands now.

How are your plans on this?

**Comment by Myz** [comment]
Yes that would help me out a lot at the moment.

Am Mi., 6. März 2019 um 15:51 Uhr schrieb Masatake YAMATO <
notifications@github.com>:

**Comment by masatake** [comment]
I would like to know a bit more details of the build process you run.
After getting a zip file of ctags, do you run autogen.sh before running configure?
In that case, you will get packcc because autogen.sh runs git-submodule commands.
I guess you run something custom scripts instead of autogen.sh.

I would like to think more about what area in ctags I should fix.

**Comment by k-takata** [comment]
git-submodule commands won't work when getting a zip file, because .git doesn't exist.
How about using git-subtree command instead of git-submodule?

**Comment by masatake** [comment]
@k-takata, thank you.
At a glance, it looks good. Maybe it is better than adding --without-packcc option to ctags.
I will study more about git-subtree in this weekend.

...The weekend queue becomes longer and longer.

**Comment by k-takata** [comment]
Example:
1st time:

```sh
$ git submodule deinit -f misc/packcc
$ git rm -f misc/packcc
$ git commit -m 'Delete packcc'
$ git subtree add --prefix misc/packcc https://github.com/universal-ctags/packcc.git master --squash
```

When you want to import the updated packcc:

```sh
$ git subtree pull --prefix misc/packcc https://github.com/universal-ctags/packcc.git master --squash
```

**Comment by masatake** [comment]
@k-takata, can I ask you to make a pull request for it?

I will add your suggestion:
```
$ git subtree pull --prefix misc/packcc https://github.com/universal-ctags/packcc.git master --squash
```
as what developers should do to ... README.md of packcc side. I will do it after merging your change.

**Comment by k-takata** [comment]
I will create a PR later.
How about adding a script for git-subtree-pull? E.g. `misc/pull-packcc.sh`:

```sh
#!/bin/sh
# Execute this if you want to import the latest packcc.
git subtree pull --prefix misc/packcc https://github.com/universal-ctags/packcc.git master --squash
```

**Comment by Myz** [comment]
@masatake Our build process is rather simple. We have set up a script that downloads the zip bundled archive of the master branch, extracts and configures it after using the `./autogen.sh` script.
1. The downloaded zip archive of the master branch is not a git repository anymore
2. The environment that does this, does not have a git client at hand or even an open routet to the internet

**Comment by k-takata** [comment]
I created a PR #2035.

**Comment by Myz** [comment]
I would appreciate the changes from PR #2035. Like this I would be able to build it again.

**Comment by k-takata** [comment]
I think now we can close this again.
