### ISSUE TITLE
Can't find references to functions/deinitions

### ISSUE THREAD

**Issue by hisnawi** [universal-ctags/ctags#1453]
I am not able to show references to a function/definition.

I use ggtags in emacs and have this .ctag setup:

--extras=+r
--fields=+r
--regex-asm=/^[[:blank:]]*ENTRY[[:blank:]]*\((.*)\)/\1/f,function/x

I use gtags with universal-ctags to generate the tags files.

gtags --gtagslabel=new-ctags
ctags: Warning: --extra option is obsolete; use --extras instead

But I can't find references.

This is what ggtags show in emacs:
Global found 0 references

What Am I doing wrong?

**Comment by masatake** [comment]
I'm sorry but reference tags are implemented in very limited area. It may be far from what you want.
What Universal-crags has currently is only infrastructure to record reference tags.

**Comment by masatake** [comment]
If you are interested in implementing reference tags feature in your favourite language, see parsers/python.c.
The parser captures XXX of import XXXX as a reference tag.

**Comment by hisnawi** [comment]
I think you misunderstood. 
I included the line:
`--regex-asm=/^[[:blank:]]ENTRY[[:blank:]]((.*))/\1/f,function/x
`
Just to figure if it is the reason why it doesn't parse references in C.
I failed to mention that I am looking for references (which functions used this define/call) in C not assembly or a new language, I am sure universal-etags should know how to parse these.

Specially that gtags on it's own without the option "-gtagslabel=new-ctags" does parse the references and I am able to navigate through them.
Is it something in my config file?

**Comment by masatake** [comment]
I'm sorry but I don't understand what you are talking about.
Though I should know, I don't know gtags.

> I am not able to show references to a function/definition.
ctags is not a tool to show references.
ctags just captures language objects in source files.

Showing something is job of client tools. 

I wrote "language objects" here. References and definitions are included in the language objects.
However, currently only a few roles of references are captured.
So the most of all questions and bugs are about capturing definition tags.
A question may become "
though following input is given: ..., ctags cannot capture FOO.
"

Or do you ask me to debug the following option?
```
--regex-asm=/^[[:blank:]]ENTRY[[:blank:]]((.*))/\1/f,function/x
```

I will do follwoing:
```
[yamato@master]~/var/ctags-github% cat /tmp/foo.s 
ENTRY(foo)
[yamato@master]~/var/ctags-github% ./ctags -o - --kinddef-asm='f,function,functions' --regex-asm='/^[[:blank:]]?ENTRY[[:blank:]]?\((.*)\)/\1/f/x' /tmp/foo.s
./ctags -o - --kinddef-asm='f,function,functions' --regex-asm='/^[[:blank:]]?ENTRY[[:blank:]]?\((.*)\)/\1/f/x' /tmp/foo.s
foo	/tmp/foo.s	/^ENTRY(foo)$/;"	f
```
