### ISSUE TITLE
Put https://github.com/universal-ctags/ctags/blob/master/main/parsers.h to the web site as iist of supported language

### ISSUE THREAD

**Issue by mtangoo** [universal-ctags/ctags#1454]
Hi,
I have tried to find list of supported languages and what is actually supported but could not find. 
Is such list in existence and I missed or it is purposely missing?

There is old list [here](http://ctags.sourceforge.net/languages.html) but am sure many things have changed since then (Dropped/Added support?)

Sorry if it is already in the docs, I just could not find it

**Comment by f-koehler** [comment]
[Here](http://docs.ctags.io/en/latest/news.html#importing-changes-from-exuberant-ctags) you can find a list of all the parsers that have been added/improved. If you combine it with the [list](http://ctags.sourceforge.net/languages.html) you should obtain the full set of supported languages. I could not find any information indicating that the support for a language was removed.

**Comment by mtangoo** [comment]
Thank you @f-koehler

**Comment by masatake** [comment]
Reliable list  is here:-)

 https://github.com/universal-ctags/ctags/blob/master/main/parsers.h .

**Comment by mtangoo** [comment]
Thanks @masatake. I think adding that to docs will help a lot!

**Comment by masatake** [comment]
> Thanks @masatake. I think adding that link to docs will help a lot!

The pull request is welcome. See docs/news.rst or somewhere.
