### ISSUE TITLE
Create another project for daily builds?

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#1455]
As I wrote in #1446, I have set up "universalctags" AppVeyor account and set up win32 daily builds.
However I wonder if we should create another github project for win32 daily builds.
Because if we keep using the same project for normal developing and the daily builds, the history of AppVeyor becomes complex and hard to find daily builds.

So, how about creating a new project (e.g. `universal-ctags/win32-dailybuilds` or something)?
It would be nice to utilize GitHub releases so that users can easily download the latest win32 package.
[vim/vim-win32-installer](https://github.com/vim/vim-win32-installer) is a good example.

When we release tagged versions, we should use GitHub releases on this project (`universal-ctags/ctags`).
Then users can easily select the packages; daily builds or official release builds.

**Comment by masatake** [comment]
It may be good idea.

**Comment by cweagans** [comment]
I don't have any objection to creating another project for daily builds, though I do question the rationale behind providing them at all. IMO, it'd be much better to just get to the point where we're doing frequent tagged releases and just host the release here.

**Comment by k-takata** [comment]
I don't think there are so many people who really need daily builds if we provide frequent tagged releases. But we haven't provided yet even two years past from creation of this github organization. I think the first tagged release becomes closer now, but still think it takes about a few months.
I also hope some people try the daily builds and report bugs before tagged releases. So I don't think providing daily builds is meaningless.
Of course, we should host tagged releases here as I wrote avobe.

**Comment by k-takata** [comment]
Now I'm setting up daily builds at here: https://github.com/k-takata/ctags-win32/releases
It looks almost fine. I'm going to transfer the project to this organization.

**Comment by k-takata** [comment]
@masatake
I transferred the project to https://github.com/universal-ctags/ctags-win32, but it seems that I don't have rights to setup CI on the project. Could you setup the rights?

**Comment by masatake** [comment]
I have just made you "Admin". Could you veirfy your rigth again?

**Comment by k-takata** [comment]
Oh, thank you. Now I can setup the CI on the new project.

**Comment by masatake** [comment]
Thank you.

**Comment by k-takata** [comment]
Daily builds start working fine.
https://github.com/universal-ctags/ctags-win32/releases
I will close this after updating README.md.
