### ISSUE TITLE
Universal Ctags unexpectedly stops parsing

### ISSUE THREAD

**Issue by FlKo** [universal-ctags/ctags#1470]
The issue is described at stackoverflow.com:

[Universal Ctags unexpectedly stops parsing](https://stackoverflow.com/questions/44648251/universal-ctags-unexpectedly-stops-parsing)

**Comment by masatake** [comment]
How about adding `-D__interface=class`  to command line?

(TODO: I have to add a help message for -D option.)

**Comment by FlKo** [comment]
> How about adding -D__interface=class to command line?
That's it! Problem solved! Many thanks!!
