### ISSUE TITLE
Feature: Support for Windows style slashes?

### ISSUE THREAD

**Issue by DoumanAsh** [universal-ctags/ctags#1489]
Currently something like that wouldn't work:
```
ctags -R .\app\
ctags.exe: Warning: cannot open input file ".\app\" : No such file or directory
```
Instead you need to correct when using ctags in powershell to `ctags -R ./app`

I'm not sure what API is used to access FS, but it would be nice to handle FS operations cross-platformly.
Though I understand that no one cares for Windows usually so feel free to close it, if it is of no interest.

**Comment by masatake** [comment]
ctags does nothing speciall. It calls `fopen`.  I guess many softwares use fopen internally. So I think the  backslash to slash conversion should be done in fopen, not in ctags.

**Comment by DoumanAsh** [comment]
In this case it is a directory but I'm pretty sure that libstd on Windows should handle Windows paths as it should use WinAPI under hood.

Simple example like that works with fopen.
```c++
#include <stdio.h>

int main(int argc, char *argv[]) {
    auto test = fopen(".\\test.cpp", "r");

    if (test != NULL) {
        printf("Open file through win path\n");
    }
}
```

Well, I will take a look at how ctags handle directories. I didn't have time since i was having this issue during work.

**Comment by DoumanAsh** [comment]
Ok, I'm sorry it turns out that -R just enables recursive search through directories of supplied files.
So it was all along my misunderstanding I suppose but for some reason i definitely remember that -R accepted directories.

**Comment by masatake** [comment]
I wonder why we have to specify -R explicitly.

**Comment by DoumanAsh** [comment]
I suppose because always performing recursive walk through file system would end up unpleasant default for some users (would take too long without depth control)

**Comment by masatake** [comment]
Oh, I see. Thank you for the comment.
