### ISSUE TITLE
pattern is both string and boolean

### ISSUE THREAD

**Issue by hanwen** [universal-ctags/ctags#1492]
if the pattern is not defined, omit it from the json, or put the empty string.

2017/06/29 01:05:10 ignoring /home/hanwen/bin/universal-ctags error: unmarshal("{\"_type\": \"tag\", \"name\": \"common1\", \"path\": \"Units/parser-fortran.r/common.f.d/input.f\", \"pattern\": false, \"language\": \"Fortran\", \"line\": 2, \"kind\": \"common\", \"scope\": \"main\", \"scopeKind\": \"program\"}"): json: cannot unmarshal bool into Go struct field reply.pattern of type string

**Comment by masatake** [comment]
pattern line in `--list-fields` output doesn't tell that the field takes bool as a value.
```
#LETTER NAME           ENABLED LANGUAGE         JSTYPE FIXED DESCRIPTION
...
P       pattern        yes     NONE             s--    yes   pattern
...
```

This should be
```
P       pattern        yes     NONE             s-b   yes   pattern
```

I will fix this.

**Comment by masatake** [comment]
??? something wrong. I wonder why pattern is not given as a string.

**Comment by masatake** [comment]
It seems that the knowledge of Fortran language that I don't have.

Following lines of parsers/fortran.c cause this exceptional output:
```
		if (token->tag == TAG_COMMON_BLOCK)
			e.lineNumberEntry = (bool) (Option.locate != EX_PATTERN);
```

I don't understand what this means. I will find time to learn the basic concept of fortran.
