### ISSUE TITLE
fuzz test generates "(null)" json output

### ISSUE THREAD

**Issue by hanwen** [universal-ctags/ctags#1493]
2017/06/29 01:10:09 post "{\"command\":\"generate-tags\",\"filename\":\"Units/afl-fuzz.r/github-issue-539-js.d/input.js\",\"size\":6}\n"
2017/06/29 01:10:09 let`	

2017/06/29 01:10:09 read (null)
2017/06/29 01:10:09 ignoring /home/hanwen/bin/universal-ctags error: unmarshal((null)): invalid character '(' looking for beginning of value

**Comment by masatake** [comment]
Sorry to be late. I will inspect this.
