### ISSUE TITLE
ocaml parser gets confused over line numbers

### ISSUE THREAD

**Issue by hanwen** [universal-ctags/ctags#1498]
using ctags on the ctags source code:

$ cat q.sh
for f in $(git ls-tree --name-only -r HEAD );
do
    sz=$(stat -c %s $f)
    ( echo '{"command":"generate-tags", "filename":"'$f'", "size": '$sz'}' ;
      cat $f ;
      echo )
done | ./ctags --_interactive --fields=*

$ sh q.sh  > out
$ grep  Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml out
{"_type": "tag", "name": "Input", "path": "Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml", "pattern": "/^let _ = p \"foo\"$/", "language": "OCaml", "line": 34, "kind": "module"}
{"_type": "tag", "name": "p", "path": "Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml", "pattern": "/^let p = print_endline$/", "language": "OCaml", "line": 2, "kind": "var"}
{"_type": "tag", "name": "_", "path": "Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml", "pattern": "/^let _ = p \"foo\"$/", "language": "OCaml", "line": 3, "kind": "function"}

note that Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml  has just 4 lines, so "line": 34 is broken. If using on its own, the file gets parsed correctly:

$ sh z.sh Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml
{"_type": "program", "name": "Universal Ctags", "version": "0.0.0"}
{"_type": "tag", "name": "Input", "path": "Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml", "pattern": "/^(* the string \"(*\" does NOT start a comment *)$/", "language": "OCaml", "line": 0, "kind": "module"}
{"_type": "tag", "name": "p", "path": "Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml", "pattern": "/^let p = print_endline$/", "language": "OCaml", "line": 2, "kind": "var"}
{"_type": "tag", "name": "_", "path": "Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/input.ml", "pattern": "/^let _ = p \"foo\"$/", "language": "OCaml", "line": 3, "kind": "function"}
{"_type": "completed", "command": "generate-tags"}

**Comment by masatake** [comment]
Reproduced here.
Can I see z.sh?

**Comment by hanwen** [comment]
z.sh just pushes a single file through the interactive mode.
