### ISSUE TITLE
byte offsets of symbols

### ISSUE THREAD

**Issue by hanwen** [universal-ctags/ctags#1502]
I need exact offsets of where the tags are in the content. Currently, I look for the tag on the line, which kind of works, except that that can easily go wrong if the tag name is very short or common, or the lines have multiple declarations.

Would it be possible to have the column within the line where the tag occurs, or even better the byte offset relative to start of file of the tag?

If not, is it guaranteed that the tags will be found in order of occurrence?

**Comment by masatake** [comment]
> Would it be possible to have the column within the line where the tag occurs, or even better the byte offset relative to start of file of the tag?

Difficult. The main part of ctags can provide the byte offset information to parsers. However, each parser must utilize the information. So we have to work on each parser. The implementations are very different in parser by parser. 

So I cannot solve this issue quickly. However, I would like to hear if you have a primary target language.

> If not, is it guaranteed that the tags will be found in order of occurrence?

The order is not guaranteed. Typical case that breaks the order can be found in #1495.

**Comment by hanwen** [comment]
That is unfortunate, but understandable. I have no primary target language.
