### ISSUE TITLE
_multiline extension does not respect \n?

### ISSUE THREAD

**Issue by wwoods** [universal-ctags/ctags#1508]
I've been trying to get this working for revealmd:

Example file:

    # Slide 1
    
    text

    ---

    ## Slide 2

    ---

    # Slide 3

~/.ctags:

    --langdef=revealmd
    --langmap=revealmd:(*slides.md)
    --regex-revealmd=/(^|\n\s+\n---\n\s*\n)\s*#+[ \t]*([^\n]+)/\2/s,slide/{_multiline=2}

The desired tags are `Slide 1`, `Slide 2`, and `Slide 3`.  What I want matched is the text following any number of hashtags, after either the beginning of the document and some lines, or a blank line, a line with ---, and another blank line.  However, `\n` does not appear to work correctly with universal-ctags.

Thanks in advance.

PS - Replacing the `\n` with `[\n\r]` does not help.

**Comment by masatake** [comment]
Your parser works fine.
Which platform do you use?


```
[jet@localhost]/tmp% uname 
Linux
[jet@localhost]/tmp% cat revealmd.ctags 
--langdef=revealmd
--langmap=revealmd:(*slides.md)
--regex-revealmd=/(^|\n\s+\n---[:space:]\s*\n)\s*#+[ \t]*([^\n]+)/\2/s,slide/{_multiline=2}

# The desired tags are Slide 1, Slide 2, and Slide 3. What I want
# matched is
# - the text following any number of hashtags,
# - after either the beginning of the document and some lines, or
# - a blank line, a line with ---, and another blank line.
# However, \n does not appear to work correctly with universal-ctags.
[jet@localhost]/tmp% ~/var/ctags/ctags -o - --options=/tmp/revealmd.ctags /tmp/input-slides.md 
Slide 1	/tmp/input-slides.md	/^# Slide 1$/;"	s
Slide 2	/tmp/input-slides.md	/^## Slide 2$/;"	s
Slide 3	/tmp/input-slides.md	/^# Slide 3$/;"	s
```

**Comment by masatake** [comment]
BTW, about the syntax level, are their difference betwen markdown and revealmd?

**Comment by wwoods** [comment]
On Linux.

Weird!  I rewrote my ~/.ctags file and it started working.  This is on a networked filesystem at a university... perhaps there was a bug there, and the file pointer needed to be rewritten or something.  Sorry for the extraneous issue!

As for merging revealmd into Universal-ctags, if you want a parser in there, sure, though I'll need a pointer in the right direction.  The syntax is basically the same as markdown, except the tags would be slides (as in my example) and probably some multimedia stuff (included images, etc).  I find that many parsers include too many tags, and it's a pain to wade through them all.  I would not mind making a quick section-based markdown parser either though, for e.g. README.md files.  Supporting all of markdown is way, way outside of my scope.  So depends on the level of completeness you want for modules of universal-ctags.  Let me know

**Comment by wwoods** [comment]
Actually, no, it's not entirely fixed.  Now using:

    --regex-revealmd=/(^|\n\s+\n---\n)\s*#+[ \t]*([^\n]+)/\2/s,slide/{_multiline=2}

And it's not working for:

    # Ok, another test
    
    ---

    ## Error in All VMMs

    ---

    ## Another test with a long name

Because what I'm getting is `A`, `Error i`, and `Ok, a` as the tags (the `[^\n]` appears to not be working as expected).

**Comment by masatake** [comment]
```
--regex-revealmd=/(^|\n\s+\n---\n)\s*#+[ \t]*([^\n]+)/\2/s,slide/{_multiline=2}
```

This should be 
```
--regex-revealmd=/(^|\n\s+\n---\n)\s*#+[ \t]*(.+$)/\2/s,slide/{_multiline=2}
```

**Comment by wwoods** [comment]
Shouldn't [\n] work as well?  What if I wanted to go until a colon or a
newline, eg [:\n]?

**Comment by wwoods** [comment]
Or are you saying [:$] would work?  What's the true end-of-document
character, if $ is endline?

**Comment by masatake** [comment]
```
[yamato@master]/tmp% cat revealmd.ctags
cat revealmd.ctags
--langdef=revealmd
--langmap=revealmd:(*slides.md)
--regex-revealmd=/(^|\n\s+\n---[:space:]\s*\n)\s*#+[ \t]*([^:]+)/\2/s,slide/{_multiline=2}
[yamato@master]/tmp% cat /tmp/input-slides.md 
cat /tmp/input-slides.md 
# Slide 1

text

---

## Slide 2

---

# Slide 3

---

# Slide 4 This the title: The rest should be dropped

[yamato@master]/tmp% u-ctags -o - --options=revealmd.ctags /tmp/input-slides.md
u-ctags -o - --options=revealmd.ctags /tmp/input-slides.md
Slide 1	/tmp/input-slides.md	/^# Slide 1$/;"	s
Slide 2	/tmp/input-slides.md	/^## Slide 2$/;"	s
Slide 3	/tmp/input-slides.md	/^# Slide 3$/;"	s
Slide 4 This the title	/tmp/input-slides.md	/^# Slide 4 This the title: The rest should be dropped$/;"	s
```

**Comment by masatake** [comment]
https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions

**Comment by masatake** [comment]
I'm not sure this is a bug or not.

**Comment by wwoods** [comment]
Given that the wiki page you linked specifies that [:space:] should behave the same as `[ \t\n\r\f\v]`: 

![image](https://user-images.githubusercontent.com/222184/28234226-2f72c38c-68b2-11e7-837e-41e4fbd97595.png)

I would say it's a bug, as a subset of that `[\n]` is not working correctly.

**Comment by masatake** [comment]
> On Linux.

Could you tell me the distribution? I'm using Fedora25.

**Comment by wwoods** [comment]
Ubuntu 16.04

On Jul 14, 2017 7:22 PM, "Masatake YAMATO" <notifications@github.com> wrote:

On Linux.

Could you tell me the distribution? I'm using Fedora25.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/universal-ctags/ctags/issues/1508#issuecomment-315503203>,
or mute the thread

**Comment by masatake** [comment]
> I would say it's a bug, as a subset of that [\n] is not working correctly.

I agree with you. I found I took critical mistakes in code handling multiline regex parser.
I will fix them.

**Comment by masatake** [comment]
See #1509.
I introduce `--ml-regex-<LANG>` option.

```
[yamato@master]/tmp% cat revealmd.ctags                                     
--langdef=revealmd
--langmap=revealmd:(*slides.md)
--regex-revealmd=/(^|\n\s+\n---\n\s*\n)\s*#+[ \t]*([^:\n]+)/\2/s,slide/{_multiline=2}
[yamato@master]/tmp% cat input-slides.md                                    
# Slide 1

text

---

## Slide 2

---

# Slide 3

---

# Slide 4 This the title: The rest should be dropped

[yamato@master]/tmp% u-ctags --options=./revealmd.ctags -o - input-slides.md
Slide 1	input-slides.md	/^# Slide 1$/;"	s
Slide 2	input-slides.md	/^## Slide 2$/;"	s
Slide 3	input-slides.md	/^# Slide 3$/;"	s
Slide 4 This the title	input-slides.md	/^# Slide 4 This the title: The rest should be dropped$/;"	s
```

**Comment by wwoods** [comment]
`\n` now works 100% as expected.  Thanks!  Also, --mline-regex feels much less awkward than the previous {_multiline=#} format.  It's a breaking change though...  What are your backwards compatibility ideas for this project?

Nitpicks:

1. `\r` is broken the same as `\n` was.  That is, putting `[^\r\n]` in a regex will stop the match at an `r`.

2. Your added documentation states that `--mline-regex` will be applied to the whole file contents rather than line-by-line.  The POSIX docs state that `^` and `$` refer to the beginning and end of a string rather than a line (Section 9.3.8): http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_03_08.  I read that as `^` shall only match the beginning of the file, not the beginning of each line as its current behavior.  Same with `$` for end of document instead of lines.

Let me know what you think.

**Comment by masatake** [comment]
> \n now works 100% as expected. Thanks! Also, --mline-regex feels much less awkward than the previous {_multiline=#} format. It's a breaking change though... What are your backwards compatibility ideas for this project?

Ideally, I should not introduce such change. However, it 's hard to do so. So I allow myself breaking self-compatibility about features and interfaces introduced in the current development phase. When we release a version, we should not break the features and interfaces written in our man pages in the published version. https://docs.ctags.io is not man page. The web pages tell what we have done in the current development phase. For releasing, I am refining features and interfaces, and writing the man pages now. You gave me a chance to refine the "multiline regex" feature. Thank you.

About compatibility with Exuberant-ctags, I allow myself breaking it only in the first Universal-ctags releasing. People may say we should not do so. However, this is the last chance to clean up the historical(?) inconsistent interface. 

> \r is broken the same as \n was. That is, putting [^\r\n] in a regex will stop the match at an r.

I will fix this. Thank you.

> Your added documentation states that --mline-regex will be applied to the whole file contents rather than line-by-line. The POSIX docs state that ^ and $ refer to the beginning and end of a string rather than a line (Section 9.3.8): http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_03_08. I read that as ^ shall only match the beginning of the file, not the beginning of each line as its current behavior. Same with $ for end of document instead of lines.

I didn't test yet, but ``^`` will not work.  ``^`` will match with the position where the end of the last matching.
``$``  may match with the end of the input file. See 
matchMultilineRegexPattern in main/lregex.c. I have to revise this area and write the behavior to the man page.

**Comment by masatake** [comment]
> \r is broken the same as \n was. That is, putting [^\r\n] in a regex will stop the match at an r.

I found much more bugs behind this. I'm working on fixing them.

**Comment by wwoods** [comment]
All of the above sounds good, thanks for your hard work @masatake  :)  If {_multiline} was recent (last few months) it makes sense to change it.  And yes, if `^` and `$`'s behavior are properly documented, it's fine... Ideally though, they would meet the true POSIX specs of beginning and end of document.  Of course, that might not be possible.

**Comment by masatake** [comment]
After thinking I wonder I should add support for \r, \f, and \v.
I would like to work on them later.

@wwoods, as you reported, supporting \n in mline parser had critical bugs.
I focused on the bugs and I think I fixed it in #1509. I will write the restriction in our document.

**Comment by wwoods** [comment]
Just FYI, I will get to looking at this again next week.  Thanks for fixing it!

**Comment by masatake** [comment]
I have to understand
REG_NEWLINE, REG_NOTBOL, and REG_NOTEOL; and consider whether ctags can utilize the flags.
