### ISSUE TITLE
Question: -R option on Windows

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1511]
Does -R option work well on windows?
In other words readir/opendir/closedir are available on Windows?

**Comment by masatake** [comment]
They may be available on mingw and cygwin. My question is about VC.

**Comment by k-takata** [comment]
Windows doesn't have readdir/opendir/closedir, but -R works on Windows.
_findfirst/_findnext/_findclose are used instead.

**Comment by masatake** [comment]
Thank you. I should read the source code first.
