### ISSUE TITLE
Automake parser generates unspecified `m` kind

### ISSUE THREAD

**Issue by majutsushi** [universal-ctags/ctags#1531]
I'm currently updating the Tagbar type definitions for Universal-Ctags and noticed that the automake parser currently can produce tags that have the `m`/`macro` kind. However, this kind is not listed in the `--list-kinds=automake` output. I can't even find it with a quick look at the parser source, I assume it gets inherited from the `make` parser somehow. Not a huge deal, but I wanted to mention it.

The same is true of the `t`/`target` kind.

**Comment by masatake** [comment]
Yes, m and t come from make parser.

This is expected behavior. Now ctags runs multiple parser for an input file.
See  http://docs.ctags.io/en/latest/running-multi-parsers.html#examples-of-sub-base-combinations

**Comment by majutsushi** [comment]
Yeah, that makes sense. It would be useful though if `--list-kinds=automake` would also list the inherited kinds, so that you could for example automatically parse its output to know what "kinds" you would have to expect in a tag of that filetype.

**Comment by masatake** [comment]
Thank you for the comment.
I think I have done too many things this area( as I did in .ctags). So I wonder what I should do.
However, if ctags provideds enough good introspection interface for a tool, not for user, good client tools like Tagbar may help users.

Did you see the output of ./ctags --list-subparsers ?
```
[yamato@master]~/var/ctags-github% ./ctags --list-subparsers
#NAME                BASEPARSER        DIRECTIONS
AnsiblePlaybook      Yaml              base <> sub {bidirectional}
Autoconf             M4                base <> sub {bidirectional}
Automake             Make              base <= sub {dedicated}
ITcl                 Tcl               base <> sub {bidirectional}
JAXRS                Java              base => sub {shared}
LinuxKernel          C                 base => sub {shared}
LinuxOVS             C                 base => sub {shared}
OpenVSwitch          C                 base => sub {shared}
PythonLoggingConfig  Iniconf           base <> sub {bidirectional}
PythonMain           Python            base => sub {shared}
PythonTuned          Python            base => sub {shared}
RSpec                Ruby              base => sub {shared}
SystemdUnit          Iniconf           base <= sub {dedicated}
TclOO                Tcl               base <> sub {bidirectional}
YumRepo              Iniconf           base <= sub {dedicated}
selinuxPolicy        selinuxPolicyBase base => sub {shared}
```

I'm afraid providing too friendly user interface breaks the consistency.
u-ctags allows using the same kind letter between a base parser and its subparsers.
If printing both kinds of the base and sub parsers in --list-kinds makes people confused.

**Comment by masatake** [comment]
If you speicy `--fields=+l` option, understanding the output becomes easier.

```
[jet@localhost]/tmp% cat Makefile.am 
all:
[jet@localhost]/tmp% u-ctags -o - --fields=+l Makefile.am 
all	Makefile.am	/^all:$/;"	t	language:Make
```

**Comment by majutsushi** [comment]
Thanks about pointing out the `--list-subparsers` option, I wasn't aware of that one. That's quite useful.

As for what would be confusing for users, personally I think it would be more confusing if a parser outputs kinds that are not listed in its `--list-kinds` output. A user shouldn't really have to worry about the inheritance hierarchy when they're just trying to parse a specific file type. Maybe it could be added to the `--list-kinds` output, and the `--list-kinds-full` output could have an additional column that said whether a specific kind was inherited? Something like this:

```
$ uctags --list-kinds-full=automake
#LETTER NAME      ENABLED REFONLY NROLES MASTER DESCRIPTION INHERITED
D       data      yes     no      0      NONE   datum       no
L       library   yes     no      0      NONE   libraries   no
M       man       yes     no      0      NONE   manuals     no
P       program   yes     no      0      NONE   programs    no
S       script    yes     no      0      NONE   scripts     no
T       ltlibrary yes     no      0      NONE   ltlibraries no
c       condition yes     yes     1      NONE   conditions  no
d       directory yes     no      6      NONE   directories no
I       makefile  yes     yes     2      NONE   makefiles   yes
m       macro     yes     no      0      NONE   macros      yes
t       target    yes     no      0      NONE   targets     yes
```

**Comment by majutsushi** [comment]
So looking at the subparser stuff in more detail this is actually a bit more complicated than simply having inherited kinds. I also noticed that subparsers can reuse the same short form for a kind, for example the Ruby parser has the `c` kind to mean "classes", whereas its RSpec subparser uses `c` to denote "contexts". So simply including the Rspec kinds in the Ruby `--list-kinds` output is not going to work. So far the only way I can see this would work is to use the `--fields=+l` option that you mentioned and then interpreting the kind based on the language in that field.

**Comment by masatake** [comment]
So can I close this?

I will write what you pointed in man pages.

I guess `./ctags  --machinable --list-subparsers` may help you adapt your tool to u-ctags.

**Comment by majutsushi** [comment]
Yes, this can be closed for now. If I can think of something concrete that could improve this for other tools I'll open a new issue.
