### ISSUE TITLE
ObjectiveC parser produces self-referential `protocol` scope

### ISSUE THREAD

**Issue by majutsushi** [universal-ctags/ctags#1532]
When the ObjectiveC parser a protocol definition, it will emit a `protocol:` scope field even for the tag defining the scope, essentially saying that the tag is part of its own scope. Obviously this doesn't make any sense, so the field should be omitted in that case.

There's an example right here in the tests, look at the `Locking` tag:
https://github.com/universal-ctags/ctags/blob/master/Units/parser-objectivec.r/objectivec_protocol.h.d/expected.tags#L1

**Comment by masatake** [comment]
Thank you. for reporting.
