### ISSUE TITLE
javascript - async functions

### ISSUE THREAD

**Issue by marcelo140** [universal-ctags/ctags#1537]
First of all I would like to thank you for all the hard word. This project is awesome. 

I started using ctags some days ago and noticed that the javascript parser has no support for async functions as described in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Syntax). For example, the following snippet from the linked article would not generate a tag for the `add1` function.

**Input**
```javascript
function resolveAfter2Seconds(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}

async function add1(x) {
  var a = resolveAfter2Seconds(20);
  var b = resolveAfter2Seconds(30);
  return x + await a + await b;
}
```

**Output**
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/058eb2ca/
resolveAfter2Seconds	test.js	/^function resolveAfter2Seconds(x) {$/;"	f
```

I managed to make it work by reproducing the changes in https://github.com/nedp/ctags/commit/1917d23d3a940e47c5b382a8c991c5aa45f04239 which solves exactly the same problem for the `export` keyword.

**Comment by masatake** [comment]
A pull request is welcome.
