### ISSUE TITLE
universal ctags not parsing c++ headers

### ISSUE THREAD

**Issue by articuluxe** [universal-ctags/ctags#1539]
I have been in the habit of running exuberant ctags with the following command:

`ctags -Re --language-force=c++ -h=".h.H.hh.hpp.hxx.h++.inc.def." --c++-kinds=+l --file-scope=no --tag-relative=no -f TAGS /usr/include/c++/7.1.0`

This creates a 2.1 MB TAGS file that I can load up in emacs and look up tags for classes in the standard libraries (e.g. vector).

But running the same command with universal ctags creates a file of size 469k, and that lacks vector, for example.

I'm not sure if this is due to differences in the parsers used, or perhaps my command line options are outdated now?

**Comment by pragmaware** [comment]
Try adding -D "_GLIBCXX_VISIBILITY(x)=" as parameter.
Maybe we could handle this better...

**Comment by articuluxe** [comment]
That parameter did help, thank you.  Now vector is present in the tags file. 

I haven't had a chance to try the updated code yet. Do you still recommend adding this parameter going forward?

**Comment by pragmaware** [comment]
With #1541 the parameter should no longer be necessary.
