### ISSUE TITLE
Question about --regex usage and special character escapes

### ISSUE THREAD

**Issue by shaehn** [universal-ctags/ctags#1545]
I am trying to write a regular expression for Windows PowerShell syntax. The unfortunate problem  I encounter is that variables names all begin with '$' which is also a special character to regular expression. So for the definition of a variable, I have the following:      --regex-Posh=/(\$\{[^}]+\})/\1/v,variable/

After running ctags over a powershell script, I will get tag elements like:
    $variable   ..\\..\\workspaces\\NGPS_2\\cw.ps1      /^function getenv ( $variable, $default ) {$/;" v

If the field after the file name is a true regular expression, I think that the '$' in front of the names variable and default need to be escaped. Is there a way to do that?  I have been reading various documents, but have not found anything to answer my question.

**Comment by masatake** [comment]
@blueyed, how do you think about this?

**Comment by masatake** [comment]
@shaehn, there is no way.
I think you can say this is a bug. This bug has existed even in  Exuberant-ctags. 
This bug has not been known more than 10 years.
I think none have written a regex parser which includes '$' to the tag name.

Other meta characters of regular expression are not escaped, too.
The pattern field is created just adding `/^` to the start, and `$/` to the end of a line picked up.

https://github.com/universal-ctags/ctags/blob/master/main/entry.c#L657
https://github.com/universal-ctags/ctags/blob/master/main/entry.c#L680

**Comment by masatake** [comment]
Anyway including `$` to the tag name is not good idea. I think it is not the part of a name.

**Comment by masatake** [comment]
vi/vim users, comments are welcome.

**Comment by shaehn** [comment]
If this has been working for most folks for all this time, then it might not be a problem. I was having issues with OpenGrok at the time and thought it might be the regular expression character '$' not being escaped. It turns out that the problem was with the difference between how regular expressions are interpreted on Windows vs Unix.  Windows usage had no problem in determining what to do with '\w+' (match word), but that did not work at all on Unix. I finally figured out I had to use the Posix '[[:alnum:]_]+' to get the match to work. I am guessing that the programs based on these tags must be handling any internal special characters appropriately.

**Comment by masatake** [comment]
BTW, I guess
```
 --regex-Posh=/(${[^}]+})/\1/v,variable/
```
should be
```
--regex-Posh=/(\$\{[^}]+})/\1/v,variable/
```
.

Am I wrong? Both `$` and `{` are metacharacters of regex pattern.

**Comment by shaehn** [comment]
Yes, you are correct and that is what I actually have in the regular expression I am using.  I must have either mistyped the original, or maybe the web commenting stuff here stripped them out.

**Comment by masatake** [comment]
@shaehn, I'm very bad in English. So I would like to make sure about your question/report.
Which you are talking about `$` usage of ctags command line or `$` printed as part of pattern field of tags output?

At the first time I saw this issue, I thought you are talking about output. However, after discussing here, I am not sure.

**Comment by shaehn** [comment]
Most definitely, printed as part of tags output.

**Comment by masatake** [comment]
It seems that adding backslash chars to the pattern is not so difficult.
However, as I wrote, I guess the change will make big impact on vi/vim users.
So I would like to get vi/vim users' feedback. 
Is this o.k.?

Your interest is OpenGrok. I know how important the software is. However, I don't have much chance to us e it. Does this issue cause a trouble for using OpenGrok? 
If yes, I have to work hard for this issue more.

I, myself use emacs. So I don't care whether the pattern should be escaped with backslash more or not.
However, lesser backslash chars make user read tags file:-).

**Comment by shaehn** [comment]
Initially I thought I was having a problem with this situation, but that had not turned out to be the case. So I think you can close this item if you wish.

**Comment by masatake** [comment]
O.k. I will close this. Thank you for reporting.

BTW, how about merging your PowerShell parser to ctags?
See .ctags file in optlib directory of u-ctags source tree.

u-ctags build system can convert a .ctags to .c file.
You may have interest in newly introduced multi state byte orientated regex parser.
http://docs.ctags.io/en/latest/optlib.html#byte-oriented-pattern-matching-with-multiple-regex-tables
