### ISSUE TITLE
-f doesnt work with json output?

### ISSUE THREAD

**Issue by vpereira** [universal-ctags/ctags#1546]
From the --help:

```
-f <name>
       Write tags to specified file. Value of "-" writes tags to stdout
       ["tags"; or "TAGS" when -e supplied].
```
so running the command 
```
./ctags --recurse=yes --fields=* --output-format=json -f ctags.json  . 
```

should generate the ctags.json on my local directory. However the ```-f``` flag is ignored and the output is being sent to stdout..

**Comment by masatake** [comment]
I'm working hard for fixing this...

**Comment by vpereira** [comment]
thank you @masatake, universal-ctags is awesome!

**Comment by masatake** [comment]
Thank you for reporting. During fixing this bug, I found some related bugs. And, during fixing these bugs, I found much more related bugs....

**Comment by masatake** [comment]
Many bugs have been hunted. Could you try the branch, 

```
git checkout -b masatake-output-option-in-json-output-mode master
git pull https://github.com/masatake/ctags.git output-option-in-json-output-mode
```

**Comment by vpereira** [comment]
in my test case it worked well. Thank you.

I have it packaged as RPM
https://build.opensuse.org/package/show/home:vpereirabr/universal-ctags
however I have a question about versioning:

I see the PACKAGE_VERSION is to 0.0 and running ```ctags --help``` I get
the following:

```
Universal Ctags 0.0.0(c310a7cd), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
```

I would like to set a right version to my package. Which one should I set?
5.9?

**Comment by masatake** [comment]
The next version will be 6.0 because I introduced so many incompatibilities.
They must be documented.

I wonder which version I should put for the current source tree.
What I can say is  that Universal-ctags project have not released any version yet.

**Comment by vpereira** [comment]
I think if its not the "exuberant tags" anymore, you should start a new versioning, no?

**Comment by masatake** [comment]
> I think if its not the "exuberant tags" anymore, you should start a new versioning, no?

I'm dishonest person. I would like to mislead people into recognizing u-ctags as a descendant of u-ctags so that u-ctags gets contribution. This is the reason I will name the our first version "6.0".

**Comment by vpereira** [comment]
Lol,

I agree with you, however if somebody tries to keep from version 5.8 -
imagine the Maintainer wants to develop it futher -  then we would end up
with two versions 5.9, 6.0, etc..

**Comment by masatake** [comment]
> imagine the Maintainer wants to develop it futher - then we would end up with two versions 5.9, 6.0, etc..

I will release the source code we are developing here as Universal-ctags 6.0.
That's all.

Current string "Exuberant-ctags" is printed in --version output because I know many tools scan the string to detect wheter /usr/bin/ctags is  Exuberant-ctags binary or a ctags shipped as part of emacs.

Like Windows 95, the first version of Universal-ctags will be Universal-ctags 6.0. Is is as I wrote marketing strategy:-P

I wonder which package name will you use, ctags or universal-ctags?   I'm not sure which is better.

There are people who are wokring for the other distribution.  How do you do in your distribution?

**Comment by vpereira** [comment]
I'm using universal-ctags. At SUSE we have extuberant-tags as ctags and therefore I created it as universal-ctags with a Conflict: ctags. 

You can see the rpm spec here: https://build.opensuse.org/package/view_file/home:vpereirabr/universal-ctags/universal-ctags.spec?expand=1

**Comment by vpereira** [comment]
What I would ask you, could you please generate a "github release", which means, to have the tarball to download with the release number? Than when we downstream it - openSUSE/Fedora/etc - we could fix exactly which version we are using.

**Comment by masatake** [comment]
See  #1038.

**Comment by masatake** [comment]
I think the original issue is fixed. Thank you for reporting.
