### ISSUE TITLE
Provide --include option to override --exclude

### ISSUE THREAD

**Issue by blueyed** [universal-ctags/ctags#1551]
I have `--exclude=.tox` in `~/.ctags` to exclude those directories by default, but would like to inlcude it temporarily; allowing to specify `--include=.tox` with `ctags -R` would help in that case.

I've tried `ctags -Ra .tox` as an alternative, but even when `.tox` is given explicitly it seems to get ignored (a separate issue?!).

The workaround I've found was to change to the directory and specify the tags file I want to append to:

```sh
cd .tox && ctags --tag-relative=yes -Ra -f ../tags
```

**Comment by masatake** [comment]
> I've tried ctags -Ra .tox as an alternative, but even when .tox is given explicitly it seems to get ignored (a separate issue?!).

I wonder why -a option is related to including/excluding.

**Comment by masatake** [comment]
The option will be named --exclude-exception.

**Comment by blueyed** [comment]
> I wonder why -a option is related to including/excluding.

Because I want to append to the existing file.

**Comment by masatake** [comment]
> I've tried ctags -Ra .tox as an alternative, but even when .tox is given explicitly it seems to get ignored (a separate issue?!).

This behavior is the same as exuberant-ctags. So I would like to say this is not an issue.

> I have --exclude=.tox in ~/.ctags to exclude those directories by default, but would like to inlcude it temporarily; allowing to specify --include=.tox with ctags -R would help in that case.

This is understandable. May be useful.
These days I found the code solving the same code:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/DM_Multipath/blacklist_exceptions.html

How about --exclude-exception as the name of the option you want?

**Comment by blueyed** [comment]
> How about --exclude-exception as the name of the option you want?

Don't know.
What about `--include`?

**Comment by masatake** [comment]
`--include` implies `#include` of C preprocessor.
In addition, people may remember the order of operations.

**Comment by masatake** [comment]
We can add --exclude-exception-exception, and --exclude-exception-exception-exception. Very flexible.

**Comment by masatake** [comment]
```
diff --git a/main/options.c b/main/options.c
index f243fc8b..206db35e 100644
--- a/main/options.c
+++ b/main/options.c
@@ -128,7 +128,7 @@ typedef stringList searchPathList;
 static searchPathList *OptlibPathList;
 static searchPathList *PreloadPathList;
 
-static stringList* Excluded;
+static stringList *Excluded, * ExcludedException;
 static bool FilesRequired = true;
 static bool SkipConfiguration;
 
@@ -250,6 +250,8 @@ static optionDescription LongOptionDescription [] = {
  {1,"      Include reference to 'file' in Emacs-style tag file (requires -e)."},
  {1,"  --exclude=pattern"},
  {1,"      Exclude files and directories matching 'pattern'."},
+ {1,"  --exclude-exception=pattern"},
+ {1,"      Don't exclude files and directories matching 'pattern'."},
  {0,"  --excmd=number|pattern|mix"},
 #ifdef MACROS_USE_PATTERNS
  {0,"       Uses the specified type of EX command to locate tags [pattern]."},
@@ -1125,33 +1127,45 @@ static void processEtagsInclude (
 	}
 }
 
-static void processExcludeOption (
-		const char *const option CTAGS_ATTR_UNUSED, const char *const parameter)
+static void processExcludeOptionCommon (
+	stringList** list, const char *const optname, const char *const parameter)
 {
 	const char *const fileName = parameter + 1;
 	if (parameter [0] == '\0')
-		freeList (&Excluded);
+		freeList (list);
 	else if (parameter [0] == '@')
 	{
 		stringList* const sl = stringListNewFromFile (fileName);
 		if (sl == NULL)
 			error (FATAL | PERROR, "cannot open \"%s\"", fileName);
-		if (Excluded == NULL)
-			Excluded = sl;
+		if (*list == NULL)
+			*list = sl;
 		else
-			stringListCombine (Excluded, sl);
-		verbose ("    adding exclude patterns from %s\n", fileName);
+			stringListCombine (*list, sl);
+		verbose ("    adding %s patterns from %s\n", optname, fileName);
 	}
 	else
 	{
 		vString *const item = vStringNewInit (parameter);
-		if (Excluded == NULL)
-			Excluded = stringListNew ();
-		stringListAdd (Excluded, item);
-		verbose ("    adding exclude pattern: %s\n", parameter);
+		if (*list == NULL)
+			*list = stringListNew ();
+		stringListAdd (*list, item);
+		verbose ("    adding %s pattern: %s\n", optname, parameter);
 	}
 }
 
+static void processExcludeOption (
+		const char *const option, const char *const parameter)
+{
+	processExcludeOptionCommon (&Excluded, option, parameter);
+}
+
+static void processExcludeExceptionOption (
+		const char *const option, const char *const parameter)
+{
+	processExcludeOptionCommon (&ExcludedException, option, parameter);
+}
+
 extern bool isExcludedFile (const char* const name)
 {
 	const char* base = baseFilename (name);
@@ -1162,6 +1176,18 @@ extern bool isExcludedFile (const char* const name)
 		if (! result  &&  name != base)
 			result = stringListFileMatched (Excluded, name);
 	}
+
+	if (result && ExcludedException != NULL)
+	{
+		bool result_exception;
+
+		result_exception = stringListFileMatched (ExcludedException, base);
+		if (! result_exception && name != base)
+			result_exception = stringListFileMatched (ExcludedException, name);
+
+		if (result_exception)
+			result = false;
+	}
 	return result;
 }
 
@@ -2663,6 +2689,7 @@ static parametricOption ParametricOptions [] = {
 	{ "data-dir",               processDataDir,                 false,  STAGE_ANY },
 	{ "etags-include",          processEtagsInclude,            false,  STAGE_ANY },
 	{ "exclude",                processExcludeOption,           false,  STAGE_ANY },
+	{ "exclude-exception",      processExcludeExceptionOption,  false,  STAGE_ANY },
 	{ "excmd",                  processExcmdOption,             false,  STAGE_ANY },
 	{ "extra",                  processExtraTagsOption,         false,  STAGE_ANY },
 	{ "extras",                 processExtraTagsOption,         false,  STAGE_ANY },
@@ -3717,6 +3744,7 @@ extern void freeOptionResources (void)
 	freeString (&Option.filterTerminator);
 
 	freeList (&Excluded);
+	freeList (&ExcludedException);
 	freeList (&Option.headerExt);
 	freeList (&Option.etagsInclude);
 
```

**Comment by masatake** [comment]
```
[jet@localhost]/tmp% find .tox
.tox
.tox/foo.c

[jet@localhost]/tmp% cat .tox/foo.c
int main(void){}

[jet@localhost]/tmp% u-ctags -o - --exclude=.tox  -R .tox

[jet@localhost]/tmp% u-ctags -o - --exclude=.tox --exclude-exception=.tox -R .tox
main	.tox/foo.c	/^int main(void){}$/;"	f	typeref:typename:int

```

**Comment by masatake** [comment]
Deciding the name of the option and writing the help message are the most difficult part of this change.

**Comment by masatake** [comment]
```
[jet@localhost]/tmp% u-ctags -o - --exclude=.tox --exclude-exception=.tox -R .tox
main	.tox/foo.c	/^int main(void){}$/;"	f	typeref:typename:int
```

This works fine. However, following doesn't work.

```
[yamato@master]/tmp% u-ctags -o - --exclude=.tox --exclude-exception='*.c' -R .tox
```

`--exclude` excludes directories in directory walking stage.

Following patch makes `--exclude` no effect in dorectory awlking stage.
```
diff --git a/main/main.c b/main/main.c
index a2d5d8f8..e8cbb7ba 100644
--- a/main/main.c
+++ b/main/main.c
@@ -241,9 +241,7 @@ static bool createTagsForEntry (const char *const entryName)
 	fileStatus *status = eStat (entryName);
 
 	Assert (entryName != NULL);
-	if (isExcludedFile (entryName))
-		verbose ("excluding \"%s\"\n", entryName);
-	else if (status->isSymbolicLink  &&  ! Option.followLinks)
+	if (status->isSymbolicLink  &&  ! Option.followLinks)
 		verbose ("ignoring \"%s\" (symbolic link)\n", entryName);
 	else if (! status->exists)
 		error (WARNING | PERROR, "cannot open input file \"%s\"", entryName);
@@ -251,6 +249,8 @@ static bool createTagsForEntry (const char *const entryName)
 		resize = recurseIntoDirectory (entryName);
 	else if (! status->isNormalFile)
 		verbose ("ignoring \"%s\" (special file)\n", entryName);
+	else if (isExcludedFile (entryName))
+		verbose ("excluding \"%s\"\n", entryName);
 	else
 		resize = parseFile (entryName);
 
```

With the patch I can get the tag for `main`:
```
[yamato@master]/tmp% u-ctags -o - --exclude=.tox --exclude-exception='*.c' -R .tox
x	.tox/foo.c	/^int x;$/;"	v	typeref:typename:int
```

However, this patch introduces not small performance penalty.

So, I think, instead of introducing `--exclude-exception` option, it may be better to ask user to use -L option for the filtering purpose.

**Comment by masatake** [comment]
How aboutt adding `--traverse-directory-eager` that allows the performance penalty ?

**Comment by sempuki** [comment]
I don't care about the name (--include is my preference) I just want the feature. My use case is bazel, which creates a lot of symbolic links, and a tiny amount of time there's generated or copied files that are interesting (ie. the copy of protobuf that I'm actually linking against).

I would prefer to have my ctags configuration in ~/.ctags than inside ~/.vimrc as `find ... |ctags -L-`

**Comment by sempuki** [comment]
I don't care about the name (--include is my preference) I just want the feature. My use case is bazel, which creates a lot of symbolic links, and a tiny amount of time there's generated or copied files that are interesting (ie. the copy of protobuf that I'm actually linking against).

I would prefer to have my ctags configuration in ~/.ctags than inside ~/.vimrc as `find ... |ctags -L-` for every language I wish to tag.

**Comment by masatake** [comment]
@sempuki, how abot using `--links=no` option?

**Comment by yoution** [comment]
I want to exclude  `node_modules` directory, but still want to keep some sub directories in  `node_modules`

**Comment by masatake** [comment]
At least 3 users wan this.
After revising my old comment, and I still think the name --include makes user being confused.
So I choose --exclude-exception. See #2445.

**Comment by yoution** [comment]
thanks, because it doesn't support regex  `/node_modules\/(?!(MY-MODUL)\/).*/,`
when will the new version release?

**Comment by masatake** [comment]
> when will the new version release?

See https://github.com/universal-ctags/ctags/issues/1038 .
