### ISSUE TITLE
At least tag releases in git

### ISSUE THREAD

**Issue by dcantrell** [universal-ctags/ctags#1562]
There are no tags or branches for releases.  Everything is on master.  This makes it difficult for users seeking specific releases or distributions wanting to track the upstream developers consider stable.  Could you at least tag releases on the main branch so it's easier for integrators downstream?

**Comment by NoctuaNivalis** [comment]
I'm sure there will be tag releases, as soon as there are releases #1038 #909

**Comment by blueyed** [comment]
Closing in favor of #1038.
