### ISSUE TITLE
Question: `HAVE_PYTHON` (or `HAVE_PYTHON3`) better than `HAVE_RST2MAN`?

### ISSUE THREAD

**Issue by KazuakiM** [universal-ctags/ctags#1575]
Hi,
I create PR "Defaultly install man pages." at https://github.com/universal-ctags/homebrew-universal-ctags/pull/26 .
Python2 have been installed at Mac by default.

But I think universal-ctags should check during installation.
And when `HAVE_PYTHON` (or `HAVE_PYTHON3`) is true and rst2man isn't installed, universal-ctags will install rst2man.
What do you think about?

**Comment by masatake** [comment]
> But I think universal-ctags should check during installation.
> And when HAVE_PYTHON (or HAVE_PYTHON3) is true and rst2man isn't installed, universal-ctags will > install rst2man.
> What do you think about?

I'm not sure I understand your question well. 
However, universal-ctags (and its build-system) should not install rst2man.
universal-ctags is a source code tagging tool. It is not an installer, a downloader, nor a package manager.

Providing rst2man is the job of build-environment. The build-system of universal-ctags just uses rst2man (rst2man.py, rst2man3, or rst2man3.py) only if it is available in the build-environment.

The build system of universal-ctags expects the existence of the command (=rst2man) only. 
The build system of universal-ctags doesn't care whether python2 or python3 is used in rst2man.

Do I make sense?

**Comment by KazuakiM** [comment]
Hi @masatake ,

I see.
When there was a change after merging https://github.com/universal-ctags/homebrew-universal-ctags/pull/26 ,
It becomes a duplication check. So I asked a question.

> universal-ctags is a source code tagging tool. It is not an installer, a downloader, nor a package manager.

You are right. Thanks!

**Comment by masatake** [comment]
> Hi @masatake ,
> 
> I see.
> When there was a change after merging universal-ctags/homebrew-universal-ctags#26 ,
> It becomes a duplication check. So I asked a question.

Oh, I see. Your question was about configure, a build-tool we are using.
Basically, configure just checks the existence of libraries and tools, and generates a Makefile adapting to the build-environment. Logically it is possible to make configure install or download something but I have never seen such usage. See configure.ac. autoconf generates configure from configure.ac.

Feel free to make a question in configure.ac.
