### ISSUE TITLE
Sh:  Tag incorrectly added for .sh script containing PHP code

### ISSUE THREAD

**Issue by benjifisher** [universal-ctags/ctags#1583]
The following code

```php
foreach (\Drupal::moduleHandler()->getModuleList() as $module => $filename) {
  $output .= " *  - $module\n";
}
```

leads to this tag:

```tags
Drupal::moduleHandler	core/scripts/dump-database-d7.sh	/^foreach (\\Drupal::moduleHandler()->getModuleList() as $module => $filename) {$/;"	f
```

I think this is a regression from Exuberant ctags.

I see the label `Parsers/sh`, but I do not seem to have permission to add it.

**Comment by benjifisher** [comment]
Another oddity.  I am not sure whether this comes from the PHP parser or from the Sh parser, since the extension is `.sh` but the file starts with `<?php` and it is clearly a PHP file.

The code

```php
  // DrupalTestCase::run() catches exceptions already, so this is only reached
```

leads to the tag

```tag
  // DrupalTestCase::run() catches exceptions already, so this is only reached
```

Again, this seems to be a regression.

**Comment by b4n** [comment]
I can't reproduce either of those issues using the PHP parser, but the Shell parser does show this behavior.  I doubt Exuberant-CTags was mapping `.sh` extension to PHP by default, but maybe Universal-CTags is not reading one of Exuberant-CTags configuration files.

So, to summarize I can reproduce your "issues" with `./ctags --language-force=sh`, but not with `./ctags --language-force=php`.  So IMO it's a non-issue, and you should just manually map `.sh` to `php` somehow (@masatake?).

**Comment by benjifisher** [comment]
Oops, I noticed on the second that the file extension was `.sh`, but I did not notice the same thing on the first file.  (Also, I pasted in the wrong line for the second example.  Edited.)

Sorry, I was in midst of comparing a few 10,000's of lines of output from Universal ctags to Exuberant ctags.

I will edit the title of this issue.

I do not know whether it is a bug or a feature, but this is certainly a difference between Exuberant ctags and Universal ctags.  Exuberant ctags does not generate any tags for this file, which starts with a shebang line and an opening PHP tag.

```
ctags -f dump-database-d7.tags core/scripts/dump-database-d7.sh 
/usr/local/Cellar/ctags/5.8_1/bin/ctags -f dump-database-d7.etags core/scripts/dump-database-d7.sh 
```

Source and results attached in a little tarball.  With Universal ctags, I get the same result with and without the `-G` flag.  (This source file has a shebang line.)

[ctags.tar.gz](https://github.com/universal-ctags/ctags/files/1405353/ctags.tar.gz)

**Comment by masatake** [comment]
I inspect the script in ctags.tar.gz;

dump-database-d7.sh:
```
#!/usr/bin/env php
<?php
....
```

u-ctags detects this script as a shell script from its file exntesion, and runs sh parser. 
This is expected behavior. I would like to say using .sh for this file is unusual.
Using .php as file extension instead, or giving `--languages=-Sh -G` to u-ctags as options.

This is not regression of language detection code. Even Exuberant ctags detects dump-database-d7.sh
as a shell script. You can observe how ctags detecting the input language with --verbose option.

```
$ /usr/bin/ctags --verbose -o - dump-database-d7.sh
...
OPENING dump-database-d7.sh as Sh language file
```

How u-ctags detects the language for input file is written in man/ctags.1.rst.

I have an interest to run php parser for following input file named foo.sh:
```
#!/bin/sh
/usr/bin/env php<<EOF
<?php
...
>
EOF
```

This is a really shell script, which runs php inside. Currently ctags cannot run php parser in the php area.
Very interesting for me, but none may want this.

**Comment by b4n** [comment]
@masatake we could probably add PHP shebang detection, too.  I never seen this, but it should work good according to http://php.net/manual/en/features.commandline.usage.php

**Comment by b4n** [comment]
Hum, OK, CTags prefers extension over shebang, so as `sh` will already have matched it won't search further.  Not sure if there's something good we can do here.

**Comment by masatake** [comment]
Inspecting the content of input file before checking file name is one of the ways.
However, I cannot convince it is the way to go. 

About this issue,  I cannot find any reason using .sh as extension here. 
Even .sh must be used for some reason, adding  `--map-sh=.sh` to the command line  is enough 
for handling this special case.

BTW I'm thinking about adding an option for defining a pattern for detecting a language for specified file extension after releasing 6.0.

```
--arbitrator-default-score-ObjectiveC=.h:0
--arbitrator-default-score-C++=.h:1
--arbitrator-pattern-ObjectiveC=.h/@interface|@implemntation/+2
```

Above example is for detecting whether a .h file is written in ObjectiveC or C++.
The default is C++ which has 1 as the score for .h extension.
ObjectiveC has 0 as the score for .h extension. C++ has higher score.
However, when scanning file content and ctags find a line matching the pattern for ObjectiveC,
ObjectiveC gains the score 2. As the result ctags can choose ObjectiveC.

Currently these scoring is done in main/selectors.c. However, patterns are hardcoded.
If will be nice if a user can add the patterns from command line.

**Comment by codebrainz** [comment]
> BTW I'm thinking about adding an option for defining a pattern for detecting a language for specified file extension after releasing 6.0.

This could probably be extended to support the use case of this Issue as well. As long as the detected contents can somehow take priority over the file extension (file extensions are somewhat meaningless/ambiguous anyway). The pattern could detect the shebang line (ex. `^#!.+?php.*?$`) or even standard C++ headers without any extension at all using those special comments (ex. `\-\*\-\s*C\+\+\s*\-\*\-` like GNU stdlib uses). I think Geany does similar to detect filetype.

**Comment by masatake** [comment]
Universal-ctags has built-in patterns used when ctags cannot decide language from input file name. 

Quoted from ctags.1.rst.1:

If @CTAGS_NAME_EXECUTABLE@ cannot select a parser from the mapping of file names,
various tests are conducted for the guessing:

template file name testing
	If the file name has ".in" extension, apply the mapping to the file
	name without the extension. For example, "config.h" is tested for a file
	named "config.h.in".

"interpreter" testing
	The first line of the file is checked to see if the file is a "#!"
	script for a recognized language.  @CTAGS_NAME_EXECUTABLE@ looks for
	a parser having the same name.

	If @CTAGS_NAME_EXECUTABLE@ finds no such parser,
	@CTAGS_NAME_EXECUTABLE@ looks for the name in alias lists. For
	example, consider if the first line is "#!/bin/sh".  Though
	@CTAGS_NAME_EXECUTABLE@ has "shell" parser, it doesn't have "sh"
	parser. However, "sh" is listed as an alias for "shell",
	@CTAGS_NAME_EXECUTABLE@ selects the "shell" parser for the file.

	An exception is "env". If "env" is specified, @CTAGS_NAME_EXECUTABLE@
	reads more lines to find real interpreter specification.

	To display the list of aliases, use ``--list-aliases`` option.
	To add/remove an item to/from the list, use ``--alias-<LANG>=[+|-]aliasPattern``
	option.

"zsh autoload tag" testing
	If the first line is started with "#compdef" or "#autoload",
	@CTAGS_NAME_EXECUTABLE@ regards the line as "zsh".

"emacs mode at the first line" testing
	Emacs editor has multiple editing modes specialized to programming
	languages. Emacs can recognize a marker called modeline in a file
	and utilize the marker for the mode selection. This testing does
	the same as what Emacs does.

	@CTAGS_NAME_EXECUTABLE@ treats *MODE* as a name of interpreter and applies the same
	rule of "interpreter" testing if the first line has one of
	the following patterns::

		-*- mode: MODE -*-

	or

	::

		-*- MODE -*-

"emacs mode at the EOF" testing
	Emacs editor recognizes another marker at the end of file as a
	mode specifier. This testing does the same as what Emacs does.

	@CTAGS_NAME_EXECUTABLE@ treats *MODE* as a name of interpreter and applies the same
	rule of "interpreter" testing if the lines at the tail of the file
	have the following pattern::

		Local Variables:
		...
		mode: MODE
		...
		End:

	3000 characters are sought from the end of file to find the pattern.

"vim modeline" testing
	Like the modeline of Emacs editor, Vim editor has the same concept.
	@CTAGS_NAME_EXECUTABLE@ treats *TYPE* as a name of interpreter and applies the same
	rule of "interpreter" testing if the last 5 lines of the file
	have one of the following patterns::

		filetype=TYPE

	or

	::

		ft=TYPE

"PHP marker" testing
	If the first line is started with "<?php",
	@CTAGS_NAME_EXECUTABLE@ regards the line as "php".

Looking into the file contents is more expensive operation than file
name matching. So @CTAGS_NAME_EXECUTABLE@ runs the testings in limited
conditions.  "interpreter" testing is enabled only when a file is
executable or ``--guess-language-eagerly`` (``-G`` in short) option is
given. The other testings are enabled only when ``-G`` option is
given.

``--print-language`` can be used just for printing the results of
parser selections for given files instead of making tags file.

```
If @CTAGS_NAME_EXECUTABLE@ cannot select a parser from the mapping of file names,
various tests are conducted for the guessing:

template file name testing
	If the file name has ".in" extension, apply the mapping to the file
	name without the extension. For example, "config.h" is tested for a file
	named "config.h.in".

"interpreter" testing
	The first line of the file is checked to see if the file is a "#!"
	script for a recognized language.  @CTAGS_NAME_EXECUTABLE@ looks for
	a parser having the same name.

	If @CTAGS_NAME_EXECUTABLE@ finds no such parser,
	@CTAGS_NAME_EXECUTABLE@ looks for the name in alias lists. For
	example, consider if the first line is "#!/bin/sh".  Though
	@CTAGS_NAME_EXECUTABLE@ has "shell" parser, it doesn't have "sh"
	parser. However, "sh" is listed as an alias for "shell",
	@CTAGS_NAME_EXECUTABLE@ selects the "shell" parser for the file.

	An exception is "env". If "env" is specified, @CTAGS_NAME_EXECUTABLE@
	reads more lines to find real interpreter specification.

	To display the list of aliases, use ``--list-aliases`` option.
	To add/remove an item to/from the list, use ``--alias-<LANG>=[+|-]aliasPattern``
	option.

"zsh autoload tag" testing
	If the first line is started with "#compdef" or "#autoload",
	@CTAGS_NAME_EXECUTABLE@ regards the line as "zsh".

"emacs mode at the first line" testing
	Emacs editor has multiple editing modes specialized to programming
	languages. Emacs can recognize a marker called modeline in a file
	and utilize the marker for the mode selection. This testing does
	the same as what Emacs does.

	@CTAGS_NAME_EXECUTABLE@ treats *MODE* as a name of interpreter and applies the same
	rule of "interpreter" testing if the first line has one of
	the following patterns::

		-*- mode: MODE -*-

	or

	::

		-*- MODE -*-

"emacs mode at the EOF" testing
	Emacs editor recognizes another marker at the end of file as a
	mode specifier. This testing does the same as what Emacs does.

	@CTAGS_NAME_EXECUTABLE@ treats *MODE* as a name of interpreter and applies the same
	rule of "interpreter" testing if the lines at the tail of the file
	have the following pattern::

		Local Variables:
		...
		mode: MODE
		...
		End:

	3000 characters are sought from the end of file to find the pattern.

"vim modeline" testing
	Like the modeline of Emacs editor, Vim editor has the same concept.
	@CTAGS_NAME_EXECUTABLE@ treats *TYPE* as a name of interpreter and applies the same
	rule of "interpreter" testing if the last 5 lines of the file
	have one of the following patterns::

		filetype=TYPE

	or

	::

		ft=TYPE

"PHP marker" testing
	If the first line is started with "<?php",
	@CTAGS_NAME_EXECUTABLE@ regards the line as "php".

Looking into the file contents is more expensive operation than file
name matching. So @CTAGS_NAME_EXECUTABLE@ runs the testings in limited
conditions.  "interpreter" testing is enabled only when a file is
executable or ``--guess-language-eagerly`` (``-G`` in short) option is
given. The other testings are enabled only when ``-G`` option is
given.

``--print-language`` can be used just for printing the results of
parser selections for given files instead of making tags file.
```

There is another case; more than one parsers are chosen from an input file name. Typical one is foo.h.
selectors (or arbitrators) are needed in this case.

In this issue, an input file has extension .sh. By default, ctags can choose a parser for the input file name.
If we have another parser for "shader language" and using .sh as file extension for the language is popular, we have to do something because ctags needs to choose shell parser or shader parser.
Even in this case, I think ctags should not consider language other than shell and shader.

**Comment by codebrainz** [comment]
The approach sounds reasonable, just backwards. It should go from most explicit (user-specified) to least explicit (guessing), IMO. Checking file content is not very expensive as it can be determined from the first or last little chunk of a file, no need to read the whole file.

**Comment by masatake** [comment]
I make a pull request (#1586) to capture a code embedded in heredoc area of sh input.

```
#!/bin/sh
/usr/bin/env php<<EOF
<?php
...
>
EOF
```

In this example, sh parser runs php parser for the area started from `<?php`.
