### ISSUE TITLE
ctags missed generating some symbols

### ISSUE THREAD

**Issue by ling-zhou** [universal-ctags/ctags#1588]
source file: https://github.com/scylladb/seastar/edit/master/core/reactor.hh

some missed symbols are as follows:
line 397:   class thread_pool {
line 442:   class reactor_backend {  
line 525:   inline open_flags operator|(open_flags a, open_flags b) {  
line 1081:  inline reactor& engine() {

cmd: ctags -I __THROW -I __nonnull --c-kinds=+pxd --extras=+fgqr --fields=+CEKRSZaeilmnprx ./reactor.hh

$ ctags --version
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 31 2017, 20:25:39
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +multibyte, +option-directory

**Comment by masatake** [comment]
Thank you for reporting.

I minimized the input (with my limited C++ knowledge):
```
#include <netinet/ip.h>
#include <map>

namespace std {
  template <>
  struct hash<::sockaddr_in> {
    int a;
  };
};

int foo (void)
{
  return 0;
}
```

Gcc says this is accepable c++ input. However, ctags cannot capture foo.
```
[yamato@master]/tmp% gcc -c baz.cc
gcc -c baz.cc
[yamato@master]/tmp% u-ctags -o - baz.cc
u-ctags -o - baz.cc
std	baz.cc	/^namespace std {$/;"	n	file:
[yamato@master]/tmp% 
```

It seems that there is a crack in the code handling `::`  :
```
#include <netinet/ip.h>
#include <map>

namespace std {
  template <>
  struct hash<x::sockaddr_in> {
    int a;
  };
};

int foo (void)
{
  return 0;
}
```

I just added `x` before `::`.  ctags works fine with the input:
```
[yamato@master]/tmp% u-ctags -o - baz.cc
u-ctags -o - baz.cc
a	baz.cc	/^    int a;$/;"	m	struct:std::hash	typeref:typename:int	file:
foo	baz.cc	/^int foo (void)$/;"	f	typeref:typename:int
hash	baz.cc	/^  struct hash<x::sockaddr_in> {$/;"	s	namespace:std	file:
std	baz.cc	/^namespace std {$/;"	n	file:
```

THIS IS NOT CPP MACRO ISSUE. So we must fix it.

**Comment by masatake** [comment]
cpreprocess layer of ctags converts `<:` in the line `struct hash<x::sockaddr_in> `.
It is known as digraph.

See

https://books.google.co.jp/books?id=i7M1DwAAQBAJ&pg=PT1234&lpg=PT1234&dq=digraph+scope+C%2B%2B&source=bl&ots=4hTN2Y7Dy3&sig=DRyzb05Yf50dSoOJ90uvefcf78w&hl=ja&sa=X&ved=0ahUKEwiS8faespvXAhUGJpQKHaOTDWMQ6AEISjAE#v=onepage&q=digraph%20scope%20C%2B%2B&f=false

.

I wonder what is "special hack" in C++-11.

**Comment by masatake** [comment]
I have found just one more char is enough for detecting wheter the conversion should be avoided or not.

**Comment by masatake** [comment]
bingo!

```
[jet@localhost]~/var/ctags% git diff 
diff --git a/parsers/cpreprocessor.c b/parsers/cpreprocessor.c
index 46ba5035..9fbc8a2e 100644
--- a/parsers/cpreprocessor.c
+++ b/parsers/cpreprocessor.c
@@ -1223,9 +1223,23 @@ process:
                        case '<':
                        {
                                int next = cppGetcFromUngetBufferOrFile ();
+                               int onemore;
                                switch (next)
                                {
-                                       case ':':       c = '['; break;
+                                       case ':':
+                                               onemore = cppGetcFromUngetBufferOrFile ();
+                                               cppUngetc (onemore);
+                                               if (onemore == ':')
+                                               {
+                                                       /* If one more ':' follows, the first ':' is part of <::namespace>
+                                                          in C++. In this case, just return '<' and push back the first ':'
+                                                          to the input stream. */
+                                                       cppUngetc (next);
+                                                       c = '<';
+                                               }
+                                               else
+                                                       c = '[';
+                                               break;
                                        case '%':       c = '{'; break;
                                        default: cppUngetc (next);
                                }
[jet@localhost]~/var/ctags% ./ctags -o - --fields=+n reactor.hh | grep '^\(thread_pool\|reactor_backend\|operator |\|engine\)[[:space:]]'
engine	reactor.hh	/^inline reactor& engine() {$/;"	f	line:1081	namespace:seastar	typeref:typename:reactor &
operator |	reactor.hh	/^inline open_flags operator|(open_flags a, open_flags b) {$/;"	f	line:525	namespace:seastar	typeref:typename:open_flags
reactor_backend	reactor.hh	/^class reactor_backend {$/;"	c	line:442	namespace:seastar
thread_pool	reactor.hh	/^class thread_pool {$/;"	c	line:397	namespace:seastar

```

**Comment by ling-zhou** [comment]
@masatake Thanks for your great work.

**Comment by ling-zhou** [comment]
Default branch
    master Updated a year ago by masatake

So, shoud I use certain one of "Active branches"? 
which one do you suggest? 
Thanks in advance.

**Comment by k-takata** [comment]
The [master branch](https://github.com/universal-ctags/ctags/tree/master) was updated yesterday.
The fix for this (#1590) has not been merged yet, though.

**Comment by masatake** [comment]
```
% cd /tmp
[yamato@master]/tmp% git clone https://github.com/universal-ctags/ctags.git
Cloning into 'ctags'...
remote: Counting objects: 34012, done.
remote: Compressing objects: 100% (160/160), done.
remote: Total 34012 (delta 135), reused 203 (delta 120), pack-reused 33730
Receiving objects: 100% (34012/34012), 10.81 MiB | 6.41 MiB/s, done.
Resolving deltas: 100% (21224/21224), done.
[yamato@master]/tmp% cd ctags
[yamato@master]/tmp/ctags% git checkout -b masatake-cxx-digraph-or-template-angle-detection master
Switched to a new branch 'masatake-cxx-digraph-or-template-angle-detection'
[yamato@master]/tmp/ctags% git pull https://github.com/masatake/ctags.git cxx-digraph-or-template-angle-detection
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 19 (delta 13), reused 19 (delta 13), pack-reused 0
Unpacking objects: 100% (19/19), done.
From https://github.com/masatake/ctags
 * branch              cxx-digraph-or-template-angle-detection -> FETCH_HEAD
Updating 66fcc1d6..73d334ac
Fast-forward
 .../expected.tags                                     |  4 +++
 .../digraph-and-template-angle-confliction.d/input.hh | 14 ++++++++
 main/parse.c                                          |  5 +++
 main/parse.h                                          |  1 +
 parsers/cpreprocessor.c                               | 40 ++++++++++++++++++++---
 parsers/cxx/cxx_tag.c                                 |  4 +--
 6 files changed, 62 insertions(+), 6 deletions(-)
 create mode 100644 Units/parser-cxx.r/digraph-and-template-angle-confliction.d/expected.tags
 create mode 100644 Units/parser-cxx.r/digraph-and-template-angle-confliction.d/input.hh
```

**Comment by masatake** [comment]
I merged my change. I think the issue you reported here is fixed. If you still have the trouble, reopen this.
Thank you for reporting.

**Comment by ling-zhou** [comment]
It works now,  thank you. I will report if I find any new problems.

**Comment by ling-zhou** [comment]
# pri kind tag               file
  1 F C member_engine_thread   ./atlas/seastar/core/reactor.hh
               line:667 language:C++ scope:class:reactor typeref:typename:sched::thread * access:private
               sched::thread *_engine_thread;

There is a little flaw in the output of 'g]', maybe some whitespaces are needed between "member" and  "_engine_thread".

**Comment by masatake** [comment]
@ling-zhou, I don't understand what are you talking about.
I guess you are talking about vim frontend?

ctags captures `_engine_thread` as in tags file:
```
_engine_thread	foo.hh	/^    sched::thread *_engine_thread;$/;"	kind:member	line:676	language:C++	scope:class:seastar::reactor	typeref:typename:sched::thread *	access:private
```

It seems o.k. for me. Am I missing something?

**Comment by ling-zhou** [comment]
yes, in vim frontend, press g], see the output here: [https://github.com/ling-zhou/pictures/blob/master/QQ20171110215106.png](url)

**Comment by ling-zhou** [comment]
$ grep _engine_thread tags
_engine_thread  ./atlas/seastar/core/reactor.hh /^    sched::thread *_engine_thread;$/;"        member  line:667        language:C++    scope:class:reactor    typeref:typename:sched::thread *        access:private
reactor::_engine_thread ./atlas/seastar/core/reactor.hh /^    sched::thread *_engine_thread;$/;"        member  line:667        language:C++  scope:class:reactor      typeref:typename:sched::thread *        access:private  extras:qualified

The tags content itself is ok, the problem is at **vim screen output**(focus the cursor on the symbol, and press g])

**Comment by masatake** [comment]
I myself is a user of emacs. I don't have enough knowledge about vim.
The default file format of u-ctags is different from that of exuberant-ctags.
`--output-format=e-ctags` option is for letting u-ctags generate exuberant-ctags compatible output.
(I must write this in u-ctags manual.)
