### ISSUE TITLE
Path separator makes --exclude non-portable

### ISSUE THREAD

**Issue by oscarfv** [universal-ctags/ctags#1609]
On Windows universal-ctags expect `\\` as path separator. This means that a --exclude value that works on POSIX won't work on Windows. This means that scripts and .ctags files that are functional on POSIX will break on Windows.

I suggest translating `/` to `\\` on Windows, for values of --exclude and others that might contain paths.

**Comment by masatake** [comment]
Thank you. Try #1611.

I have to enumerate the  "others" you wrote.

**Comment by masatake** [comment]
Does the change work well?

**Comment by oscarfv** [comment]
I tested your `convert-slash-to-backslash-in-exclude-option` branch on Windows 8.1 and it works fine.

Thank you.

**Comment by masatake** [comment]
Thank you for testing.

**Comment by masatake** [comment]
Merged. Though I should inspect other options which take file paths, I would like to close this.
