### ISSUE TITLE
Fortran submodule support

### ISSUE THREAD

**Issue by cbcoutinho** [universal-ctags/ctags#1616]
Thanks for maintaining this great tool everyone, I really appreciate it.

The last few releases of Fortran have included support for submodules, which are essentially a way of deferring the implementation of a subprogram to a separate file. This has various benefits because you can put separate implementations of a generic interface in various files, without each implementation knowing anything about sibling variables, etc. I think of submodules of ways to extend modules, commonly because you want to make some procedures in your code generic, and keeping them all in one file can become unwieldy for large projects. Further, submodules are also hidden from each other, so you don't have to worry about naming conflicts on functions internal to a submodule

An overview of submodules from the Fortran wiki: http://fortranwiki.org/fortran/show/Submodules, with a small single file example.

Right now ctags properly creates tags for variables and functions between `program`s and `module`s, so by using vim I can move between the two, but when I want to jump to the implementation of a procedure (function/subroutine) that is contained within a submodule, ctags sends an error `E426: tag not found`. I think that ctags is unaware that a module interface could be implemented in a submodule file. 

---

I created a simple MWE that contains three Fortran source files and a makefile at https://github.com/cbcoutinho/submodules_mwe . The Fortran source files contain a main program file, a module file, and submodule file.

Main program file, main.f90
```fortran
program main
    use :: example_mod, only : f, f_interface, g

    ! The main program calls each function/interface with identical
    ! input

    print*, f(2)
    print*, f_interface(2)
    print*, g(2)

end program main
```

Module file, example_mod.f90
```fortran
module example_mod

    ! This module contains two interfaces:
    !   1. f_interface, which is an interface to the local f function
    !   2. g, which is implemented in the example_smod submodule

    interface f_interface
        ! The function `f` is defined below, within the `contains` statement
        module function f(x) result(y)
            integer :: x, y
        end function f
    end interface f_interface

    interface
        ! The function `g` is implemented in example_smod.f90
        module function g(x) result(y)
            integer :: x,y
        end function g
    end interface

contains
    function f(x) result(y)
        integer :: x, y

        y = x * 2
    end function f

end module example_mod
```

Submodule file, example_smod.f90
```fortran
submodule (example_mod) example_smod

    ! This submodule implements the interface `g` definted in the
    ! example_mod module

contains
    module function g(x) result(y)
        integer :: x,y
        y = x * 2
    end function g
end submodule example_smod
```

If I can help implement this, please let me know how and where.

**Comment by masatake** [comment]
I don't know vim. I would like to talk with you in the scope of tags output. I know tags output well:-)

The biggest question is how submodule should be represented on tags output.
Following is tags output for example_mod.f90.
```
$ u-ctags --fields=+K --kinds-all='*' -o - /tmp/example_mod.f90
example_mod	/tmp/example_mod.f90	/^module example_mod$/;"	module
f	/tmp/example_mod.f90	/^    fu/;"	function
f_interface	/tmp/example_mod.f90	/^    interface f_interface$/;"	interface	module:example_mod
x	/tmp/example_mod.f90	/^        integer :: x,/;"	local	function:f	file:
y	/tmp/example_mod.f90	/^        integer :: x, y$/;"	local	function:f	file:
```

Could you show me your ideal tags output for example_smod.f90?
My idea is:
```
example_smod example_smod.f90 /^submodule (example_mod) example_smod/;" submodule module:example_mod
g example_smod.f90 /^    module function g(x) result(y)/;" function submodule:example_smod
x	/tmp/example_mod.f90	/^        integer :: x,/;"	local	function:g	file:
y	/tmp/example_mod.f90	/^        integer :: x, y$/;"	local	function:g	file:
```

How do you think whether I should introduce new `submodule` kind, or reuse `module` kind for submodule?
I would like to know how I should call the relation between `(example_mod)` and `example_smod` appearted in the line `submodule (example_mod) example_smod`. In my idea, I use scope relation; `example_smod` is defined in the scope `example_mod`. I wonder this is a good or not.

**Comment by masatake** [comment]
Anyway I don't have much time in this year.

**Comment by masatake** [comment]
BTW, pattern field of `f` for example_mod.f90 is wrong. This is a bug. Sigh...

**Comment by cbcoutinho** [comment]
I have to plead ignorance w.r.t ctags, so I hope we can learn from each other here.

I'm not sure what the difference would be from the perspective of ctags if you create a new `submodule` kind or just jam it into `module`. What would the ramifications be? Just for reference, Fortran `functions` and `subroutines` are very similar, but different enough to impose different program sub-units. Maybe it makes sense to follow that and create a separate kind for `submodules`.

I'm not sure about the scope relations you mentioned. Submodules are able to extend a module, similar to how classes can inherit and extend other classes in some OOP languages. In that way, you can have multiple submodules that extend a single module, but modules don't _need_ to be extended. I could think of a few instances where some basic functionality is defined in a module, and only for a few edge cases further functionality is defined in a submodule.

I didn't notice the bug you mentioned, at least I didn't notice anything unusual when I was messing around with the MWE I made.

**Comment by masatake** [comment]
Thank you. I will introduce submodule kind. 
Using it seems that using scope looks bad. Instead, I will use `inherits:` field to represent the relationship between a module and its submodule.

**Comment by masatake** [comment]
Please, try #1617.

**Comment by cbcoutinho** [comment]
Thanks for the quick work on this @masatake! This works great on the submodule MWE worked flawlessly.

I just tried it out on some projects I'm involved with, that are quite a bit larger, and noticed a small issue:

See for instance this module file I have in a project I'm working on: https://github.com/cbcoutinho/learn_dg/blob/master/src/integration/mod_integration.f90

I define an interface with the name `integrate`, and the two `module procedure`s are implemented later on down in the file. Since they are implemented later in the same file, I don't need to specify input variables/types, because they are handled implictly:

```fortran
public :: integrate
interface integrate
      module procedure integrate1D
      module procedure integrate2D
end interface integrate
```

later on down in the same file:

```fortran
    module function integrate1D(fun, xbnds) result(result)
        ! This routine uses gauss-legendre quadrature to integrate a 1D
        ! line function

        ! Input/Output dummy variables
        real(wp), intent(in)    :: xbnds(2)
        real(wp)                :: result
        procedure(fun1d_interf) :: fun
.
.
.
```
This means that in a single file, a `module procedure` could be either a `module function` or `module subroutine`.

Further, if a `module procedure` is later implemented in a separate submodule, the interface in the module itself needs the complete function or subroutine header (i.e. function/subroutine statement with input and output variables). It's possible to implement the function or subroutine just as a `module procedure` in a submodule (i.e. without stating the input/output variables again, because these would be implicit). Then a `module function` or `module subroutine` could point to a `module procedure` in a submodule.

There is a simple example of this shown on the Fortran wiki: http://fortranwiki.org/fortran/show/Submodules.

Besides that, this is really great.

**Comment by masatake** [comment]
@cbcoutinho, thank you for testing. I don't understand well the small issue well.

I think my patch implements what you wanted the original. Am I correct? I asked this because
I would like to merge #1617 if it improves ctags.

For me, the small issue looks new one, and it is not about submodule.
If it is new one, please make a new issue. In that case, I would like to you to read http://docs.ctags.io/en/latest/reporting.html. I need not only input file but also expect output. So I can understand what you want quickly.

**Comment by cbcoutinho** [comment]
@masatake, you're probably right, it's a separate issue - you can merge this PR. Your solution works great, and I'll create a new issue with expected output when I get some time later today or this week.

**Comment by masatake** [comment]
The new issue is welcome. My side is ready:-P
```
[yamato@master]~/var/ctags-github% u-ctags  --kinds-Fortran='*' --sort=no -o -  /tmp/input.f90 
<nds-Fortran='*' --sort=no -o -  /tmp/input.f90 
mod_integration	/tmp/input.f90	/^module mod_integration$/;"	m
integrate	/tmp/input.f90	/^  interface integrate$/;"	i	module:mod_integration
integrate1D	/tmp/input.f90	/^    module procedure integrate1D$/;"	P	module:mod_integration
integrate2D	/tmp/input.f90	/^    module procedure integrate2D$/;"	P	module:mod_integration
fun2d_interf	/tmp/input.f90	/^    module function fun2d_interf(/;"	P	module:mod_integration
x	/tmp/input.f90	/^      real(wp), intent(in)  :: x(/;"	L	prototype:fun2d_interf	file:
y	/tmp/input.f90	/^      real(wp), intent(in)  :: x(:,:), y(/;"	L	prototype:fun2d_interf	file:
z	/tmp/input.f90	/^      real(wp), allocatable :: z(/;"	L	prototype:fun2d_interf	file:
fun1d_interf	/tmp/input.f90	/^    module function fun1d_interf(/;"	P	module:mod_integration
xx	/tmp/input.f90	/^      real(wp), intent(in)  :: xx(/;"	L	prototype:fun1d_interf	file:
yy	/tmp/input.f90	/^      real(wp), allocatable :: yy(/;"	L	prototype:fun1d_interf	file:
gaussquad	/tmp/input.f90	/^    module subroutine gaussquad(/;"	P	module:mod_integration
N	/tmp/input.f90	/^      integer,  intent(in)  :: N$/;"	L	prototype:gaussquad	file:
x	/tmp/input.f90	/^      real(wp), intent(out) :: x(/;"	L	prototype:gaussquad	file:
w	/tmp/input.f90	/^      real(wp/;"	L	prototype:gaussquad	file:
integrate1D	/tmp/input.f90	/^  module function integrate1D(/;"	f	module:mod_integration
xbnds	/tmp/input.f90	/^    real(wp), intent(in)    :: xbnds(/;"	L	function:integrate1D	file:
result	/tmp/input.f90	/^    real(wp)                :: result$/;"	L	function:integrate1D	file:
fun	/tmp/input.f90	/^    procedure(fun1/;"	L	function:integrate1D	file:
N_start	/tmp/input.f90	/^    integer, parameter    :: N_start /;"	L	function:integrate1D	file:
N	/tmp/input.f90	/^    integer               :: N$/;"	L	function:integrate1D	file:
result_old	/tmp/input.f90	/^    real(wp)              :: result_old,/;"	L	function:integrate1D	file:
error	/tmp/input.f90	/^    real(wp)              :: result_old, error$/;"	L	function:integrate1D	file:
eps	/tmp/input.f90	/^    real(wp), parameter   :: eps /;"	L	function:integrate1D	file:
x	/tmp/input.f90	/^    real(wp), allocatable :: x(/;"	L	function:integrate1D	file:
w	/tmp/input.f90	/^    real(wp/;"	L	function:integrate1D	file:
y	/tmp/input.f90	/^    real(wp), allocatable :: x(:), w(:), y(/;"	L	function:integrate1D	file:
integrate2D	/tmp/input.f90	/^  module function integrate2D(/;"	f	module:mod_integration
fun	/tmp/input.f90	/^    procedure(fun2/;"	L	function:integrate2D	file:
xbnds	/tmp/input.f90	/^    real(wp), intent(in)    :: xbnds(/;"	L	function:integrate2D	file:
ybnds	/tmp/input.f90	/^    real(wp), intent(in)    :: xbnds(2), ybnds(/;"	L	function:integrate2D	file:
out	/tmp/input.f90	/^    real(wp)                :: out$/;"	L	function:integrate2D	file:
N_start	/tmp/input.f90	/^    integer, parameter                    :: N_start /;"	L	function:integrate2D	file:
ii	/tmp/input.f90	/^    integer                               :: ii,/;"	L	function:integrate2D	file:
N	/tmp/input.f90	/^    integer                               :: ii, N$/;"	L	function:integrate2D	file:
out_old	/tmp/input.f90	/^    real(wp)                              :: out_old,/;"	L	function:integrate2D	file:
error	/tmp/input.f90	/^    real(wp)                              :: out_old, error$/;"	L	function:integrate2D	file:
eps	/tmp/input.f90	/^    real(wp), parameter                   :: eps /;"	L	function:integrate2D	file:
x	/tmp/input.f90	/^    real(wp), dimension(:),   allocatable :: x,/;"	L	function:integrate2D	file:
w	/tmp/input.f90	/^    real(wp/;"	L	function:integrate2D	file:
xx	/tmp/input.f90	/^    real(wp), dimension(:,:), allocatable :: xx,/;"	L	function:integrate2D	file:
yy	/tmp/input.f90	/^    real(wp), dimension(:,:), allocatable :: xx, yy$/;"	L	function:integrate2D	file:
wx	/tmp/input.f90	/^    real(wp), dimension(:,:), allocatable :: wx,/;"	L	function:integrate2D	file:
wy	/tmp/input.f90	/^    real(wp), dimension(:,:), allocatable :: wx, wy$/;"	L	function:integrate2D	file:
out_spread	/tmp/input.f90	/^    real(wp), dimension(:,:), allocatable :: out_spread$/;"	L	function:integrate2D	file:
[yamato@master]~/var/ctags-github% git diff |cat
git diff |cat
diff --git a/parsers/fortran.c b/parsers/fortran.c
index 12ad0404..4d580846 100644
--- a/parsers/fortran.c
+++ b/parsers/fortran.c
@@ -1968,6 +1968,26 @@ static void parseDerivedTypeDef (tokenInfo *const token)
  *  module-procedure-stmt is
  *      MODULE PROCEDURE procedure-name-list
  */
+static bool parseModuleProcedureStatement(tokenInfo *const token)
+{
+	bool r = false;
+
+	do {
+		readToken (token);
+		if (isType (token, TOKEN_IDENTIFIER))
+		{
+			makeFortranTag (token, TAG_PROTOTYPE);
+			readToken (token);
+			r = true;
+			if (!isType (token, TOKEN_COMMA))
+				break;
+		}
+		else
+			break;
+	} while (1);
+	return r;
+}
+
 static void parseInterfaceBlock (tokenInfo *const token)
 {
 	tokenInfo *name = NULL;
@@ -2000,10 +2020,14 @@ static void parseInterfaceBlock (tokenInfo *const token)
 	while (! isKeyword (token, KEYWORD_end) &&
 		   ! isType (token, TOKEN_EOF))
 	{
+		if (isKeyword (token, KEYWORD_module))
+			readToken (token);
+
 		switch (token->keyword)
 		{
 			case KEYWORD_function:
 			case KEYWORD_subroutine: parseSubprogram (token); break;
+			case KEYWORD_procedure: parseModuleProcedureStatement (token); break;
 
 			default:
 				if (isSubprogramPrefix (token))
[yamato@master]~/var/ctags-github% 
```

**Comment by masatake** [comment]
About `/^    fu/;` issue, following change fixes it.

```
[yamato@master]~/var/ctags-github% git diff
diff --git a/parsers/fortran.c b/parsers/fortran.c
index 12ad0404..d40ca15a 100644
--- a/parsers/fortran.c
+++ b/parsers/fortran.c
@@ -533,7 +533,7 @@ static void makeFortranTag (tokenInfo *const token, tagType tag)
                e.isFileScope   = isFileScope (token->tag);
                if (e.isFileScope)
                        markTagExtraBit (&e, XTAG_FILE_SCOPE);
-               e.truncateLineAfterTag = (bool) (token->tag != TAG_LABEL);
+               // e.truncateLineAfterTag = (bool) (token->tag != TAG_LABEL);
 
                if (ancestorCount () > 0)
                {
```

However, I'm not sure this change is needed or not.
