### ISSUE TITLE
Match a line not containing a keyword?

### ISSUE THREAD

**Issue by gqqnbig** [universal-ctags/ctags#1620]
My file is
```
trigger = {
	has_full_control_of_state = 282
	NOT = { 
		tag = JAP 
	}
	AND = { 
		tag = JAP 
	}

	mean_time_to_happen = {
		days = 1
	}
}

```

My config file has

`--regex-hoi=/^\s*(\w+)\s*\=\s*\{\s*$/\1/s,section/`

it outputs tags `trigger`, `NOT`, `AND`, `mean_time_to_happen`. How do I exclude `NOT `and `AND`?

I read the documentation, and understand the {exclusive} flag may be the cure. 

For curiosity, I searched online, it seems possible to exclude keywords within the regular expression, by using (?<!AND).* construct. I tried but failed.

Is it possible to exclude keywords in universal-ctags? Or is {exclusive} the workaround to this limitation?

**Comment by masatake** [comment]
How about this?

```
[jet@localhost]~/var/ctags% cat hoi.ctags
cat hoi.ctags
--langdef=hoi
--map-hoi=+.hoi
--kinddef-hoi=s,section,sections
--regex-hoi=/^\s*(AND|NOT)\s*\=\s*\{\s*$//{exclusive}
--regex-hoi=/^\s*(\w+)\s*\=\s*\{\s*$/\1/s/
[jet@localhost]~/var/ctags% cat input.hoi 
cat input.hoi 
trigger = {
	has_full_control_of_state = 282
	NOT = { 
		tag = JAP 
	}
	AND = { 
		tag = JAP 
	}

	mean_time_to_happen = {
		days = 1
	}
}
[jet@localhost]~/var/ctags% ./ctags --options=hoi.ctags -o - input.hoi 
./ctags --options=hoi.ctags -o - input.hoi 
mean_time_to_happen	input.hoi	/^	mean_time_to_happen = {$/;"	s
trigger	input.hoi	/^trigger = {$/;"	s
```

**Comment by gqqnbig** [comment]
Yeah, so {exclusive} seems the only to do this. Thanks for confirming, I'm fine with that.

**Comment by gqqnbig** [comment]
Can you confirm if it's possible to do balanced group in --mtable option?

**Comment by masatake** [comment]
Yes. However, there is no documentation how to use --mtable.

**Comment by masatake** [comment]
Surprisingly I find I  wrote about it.
http://docs.ctags.io/en/latest/optlib.html?highlight=mtable#byte-oriented-pattern-matching-with-multiple-regex-tables

**Comment by gqqnbig** [comment]
I scanned the documentation, but didn't find information on balanced group. 

Basically I want to output proper scope of my selected symbols. For now they are `trigger `and `mean_time_to_happen`. 

My previous example file is an abstract of the original file which contains a massive number of left hand symbols (the keyword left to `=`). Rather than match all and exclude others, I think selectively output some interesting tags is the better approach.

If I match `}` to pop stack, ctags will match `}` that belongs to, say, `NOT = {`, and thus destroys the scope. I don't know how to do it properly.

**Comment by masatake** [comment]
See  https://github.com/universal-ctags/ctags/blob/master/optlib/puppetManifest.ctags.

Could you show me your expected tags output for the input?

**Comment by gqqnbig** [comment]
You are so helpful! Sorry to give you a longer example.
```

country_event = {
	id = cor_sta.1
	fire_only_once = no
	mean_time_to_happen = {
		days = 1 
	}
	hidden = no
	
	title = cor_sta.1.t
	desc = cor_sta.1.d
	
	trigger = {
		any_state = {
			AND = {
				is_controlled_by = FROM
				NOT = { is_core_of = FROM }
				if = {
					LIMIT = { 
						NOT = { is_owned_by = FROM }
					}
					all_neighbor_state = {
						is_controlled_by = FROM
					}
				}
				OR = {
					any_neighbor_state = {
						OR = {
							is_core_of = FROM
							has_state_flag = integrated_by_@FROM
						}
					}
					AND = {
						is_coastal = yes
						FROM = {
							any_owned_state = {
								AND = {
									is_core_of = FROM
									is_coastal = yes
								}
							}
						}
					}
				}
				AND = {
					NOT = { has_state_flag = integrated_by_@FROM }
					NOT = { has_state_flag = fast_integration_@FROM }
					NOT = { has_state_flag = normal_integration_@FROM }
					NOT = { has_state_flag = slow_integration_@FROM }
				}
			}
		}
	}
	
	option = {
		name = cor_sta.1.a
		add_political_power = -15
		random_state = {
			limit = {
				AND = {
					is_controlled_by = FROM
					NOT = { is_core_of = FROM }
					if = {
						LIMIT = { 
							NOT = { is_owned_by = FROM }
						}
						all_neighbor_state = {
							is_controlled_by = FROM
						}
					}
					OR = {
						any_neighbor_state = {
							OR = {
								is_core_of = FROM
								has_state_flag = integrated_by_@FROM
							}
						}
						AND = {
							is_coastal = yes
							FROM = {
								any_owned_state = {
									AND = {
										is_core_of = FROM
										is_coastal = yes
									}
								}
							}
						}
					}
					AND = {
						NOT = { has_state_flag = integrated_by_@FROM }
						NOT = { has_state_flag = fast_integration_@FROM }
						NOT = { has_state_flag = normal_integration_@FROM }
						NOT = { has_state_flag = slow_integration_@FROM }
					}
				}
			}
			set_state_flag = fast_integration_@FROM
			custom_effect_tooltip = cor_sta.1.a.t
		}
	}
	
	option = {
		name = cor_sta.1.b
		add_political_power = -5
		random_state = {
			limit = {
				AND = {
					is_controlled_by = FROM
					NOT = { is_core_of = FROM }
					AND = {
						NOT = { has_state_flag = integrated_by_@FROM }
						NOT = { has_state_flag = fast_integration_@FROM }
						NOT = { has_state_flag = normal_integration_@FROM }
						NOT = { has_state_flag = slow_integration_@FROM }
					}
					if = {
						LIMIT = { 
							NOT = { is_owned_by = FROM }
						}
						all_neighbor_state = {
							is_controlled_by = FROM
						}
					}
					OR = {
						any_neighbor_state = {
							OR = {
								is_core_of = FROM
								has_state_flag = integrated_by_@FROM
							}
						}
						AND = {
							is_coastal = yes
							FROM = {
								any_owned_state = {
									AND = {
										is_core_of = FROM
										is_coastal = yes
									}
								}
							}
						}
					}
				}
			}
			set_state_flag = normal_integration_@FROM
			custom_effect_tooltip = cor_sta.1.b.t
		}
	}
	
	option = {
		name = cor_sta.1.c
		random_state = {
			limit = {
				AND = {
					is_controlled_by = FROM
					NOT = { is_core_of = FROM }
					AND = {
						NOT = { has_state_flag = integrated_by_@FROM }
						NOT = { has_state_flag = fast_integration_@FROM }
						NOT = { has_state_flag = normal_integration_@FROM }
						NOT = { has_state_flag = slow_integration_@FROM }
					}
					if = {
						LIMIT = { 
							NOT = { is_owned_by = FROM }
						}
						all_neighbor_state = {
							is_controlled_by = FROM
						}
					}
					OR = {
						any_neighbor_state = {
							OR = {
								is_core_of = FROM
								has_state_flag = integrated_by_@FROM
							}
						}
						AND = {
							is_coastal = yes
							FROM = {
								any_owned_state = {
									AND = {
										is_core_of = FROM
										is_coastal = yes
									}
								}
							}
						}
					}
				}
			}
			set_state_flag = slow_integration_@FROM
			custom_effect_tooltip = cor_sta.1.c.t
		}
	}
}

```
I want the scope like
```
country_event
- mean_time_to_happen
- trigger
- option
- option
- option

```

**Comment by masatake** [comment]
How about expected output(tags output)?

**Comment by gqqnbig** [comment]
I'm not famililar with the ctags output format... I guess I expect it like this 

```
country_event  a.hoi   /^country_event = {$/;" s       line:1
mean_time_to_happen    a.hoi   /^      mean_time_to_happen = {$/;"     s       line:4  section:country_event
trigger        a.hoi   /^      trigger = {$/;" s       line:12 section:country_event
option         a.hoi   /^      option = {$/;"  s       line:54 section:country_event
option         a.hoi   /^      option = {$/;"  s       line:102        section:country_event 
option         a.hoi   /^      option = {$/;"  s       line:150        section:country_event

```

**Comment by masatake** [comment]
```
[yamato@master]~/var/strace% cat /tmp/hoi.ctags 
cat /tmp/hoi.ctags 
--langdef=Hoi
--map-Hoi=+.hoi

--kinddef-Hoi=s,section,sections
# --kinddef-Hoi=a,attr,attributes

--_tabledef-Hoi=main
--_tabledef-Hoi=anonblk
--_tabledef-Hoi=namedblk
--_tabledef-Hoi=common


--_mtable-regex-Hoi=common/(AND|NOT)[ \t\n]*=[ \t\n]* \{//{tenter=anonblk}
--_mtable-regex-Hoi=common/([a-zA-Z_][a-zA-Z_0-9]*)[ \t\n]*=[ \t\n]*\{/\1/s/{tenter=namedblk}{scope=push}

--_mtable-regex-Hoi=main/[ \t\n]+//
--_mtable-extend-Hoi=main+common
--_mtable-regex-Hoi=main/.//

--_mtable-regex-Hoi=anonblk/[ \t\n]+//
--_mtable-regex-Hoi=anonblk/([a-zA-Z_][a-zA-Z_0-9]*)[ \t\n]*=[ \t\n]*\{//{tenter=anonblk}
--_mtable-regex-Hoi=anonblk/\}//{tleave}
--_mtable-regex-Hoi=anonblk/.//

--_mtable-regex-Hoi=namedblk/[ \t\n]+//
--_mtable-extend-Hoi=namedblk+common
--_mtable-regex-Hoi=namedblk/\}//{tleave}{scope=pop}
--_mtable-regex-Hoi=namedblk/.//
[yamato@master]~/var/strace% u-ctags --sort=no --extras=+q --options=/tmp/hoi.ctags -o - /tmp/input2.hoi 
u-ctags --sort=no --extras=+q --options=/tmp/hoi.ctags -o - /tmp/input2.hoi 
country_event	/tmp/input2.hoi	/^country_event = {$/;"	s
mean_time_to_happen	/tmp/input2.hoi	/^	mean_time_to_happen = {$/;"	s	section:country_event
trigger	/tmp/input2.hoi	/^	trigger = {$/;"	s	section:country_event
any_state	/tmp/input2.hoi	/^		any_state = {$/;"	s	section:country_event.trigger
option	/tmp/input2.hoi	/^	option = {$/;"	s	section:country_event
random_state	/tmp/input2.hoi	/^		random_state = {$/;"	s	section:country_event.option
limit	/tmp/input2.hoi	/^			limit = {$/;"	s	section:country_event.option.random_state
option	/tmp/input2.hoi	/^	option = {$/;"	s	section:country_event
random_state	/tmp/input2.hoi	/^		random_state = {$/;"	s	section:country_event.option
limit	/tmp/input2.hoi	/^			limit = {$/;"	s	section:country_event.option.random_state
option	/tmp/input2.hoi	/^	option = {$/;"	s	section:country_event
random_state	/tmp/input2.hoi	/^		random_state = {$/;"	s	section:country_event.option
limit	/tmp/input2.hoi	/^			limit = {$/;"	s	section:country_event.option.random_state
```

Full qualified tag is used for the scope field. I wonder whether this is good or not.

**Comment by gqqnbig** [comment]
Thanks so much. I have to revise

--_mtable-regex-Hoi=common/(AND|NOT|any_state|limit|random_state)[ \t\n]*=[ \t\n]* \{//{tenter=anonblk}

to include more unwanted keywords.

As I said, this language has 100 keywords, and users can define their own keywords. I'm only interested in a couple keywords, it's not feasible to list the unwanted ones in anonblk.

**Comment by gqqnbig** [comment]
It's my bad that I didn't ask an explicit question.

I'm saying I have too many keywords and user defined keywords to exclude in the config file. 

Is there a way to only include interested keywords in the config file without knowing other unknown keywords?

**Comment by masatake** [comment]
I don't understand what you want.
Do you mean you just want capture only country_event, trigger, mean_time_to_happen and option?

**Comment by gqqnbig** [comment]
Correct. And I do not want to list out unwanted keywords in regex. Reason is the language has 100 keywords, and users can defined their own keywords, while I'm able to write 
`
--_mtable-regex-Hoi=common/(AND|NOT|any_state|limit|random_state|tags||random_owned_controlled_state|OVERLORD|state_id|any_neighbor_country|TAG|any_country|any_enemy_country|all_neighbor_country|all_country|all_enemy_country|any_state|any_owned_state|any_neighbor_state|any_allied_country|all_state|every_owned_state|all_neighbor_state|all_allied_country|every_country|random_country|every_neighbor_country|random_neighbor_country|every_enemy_country|random_enemy_country|random_state|random_owned_state|random_neighbor_state|every_state|every_owned_state|every_neighbor_state|capital_scope|num_divisions|has_focus_tree|is_staging_coup|has_full_control_of_state|has_army_experience|has_air_experience|has_navy_experience|has_country_leader|has_tech_bonus|has_resources_amount|num_of_subjects|num_tech_sharing_groups|compare_autonomy_progress_ratio|ai_irrationality|ai_liberate_desire|always|any_claim|any_war_score|armor|can_research|controls_state|country_exists|date >, date <|dig_in|distance_to|divisions_in_state|exists|fastest_unit|focus_progress|free_building_slots|frontage_full|gives_military_access_to|hardness|has_added_tension_amount|has_annex_war_goal|has_army_manpower|has_army_size|has_autonomy_state|has_available_idea_with_traits|has_built|has_capitulated|has_carrier_airwings_on_mission|has_civil_war|has_combat_modifier|has_completed_focus|has_country_flag|has_defensive_war|has_defensive_war_with|has_deployed_air_force_size|has_equipment|has_flanked_opponent|has_global_flag|has_government|has_guaranteed|has_idea|has_idea_with_trait|has_manpower|has_manpower_for_recruit_change_to|has_max_planning|has_military_access_to|has_national_unity|has_navy_size|has_offensive_war|has_offensive_war_with|has_opinion|has_opinion_modifier|has_political_power|has_reserves|has_start_date|has_state_flag|has_tech|has_template_containing_unit|has_trait|has_volunteers_from|has_war|has_war_together_with|has_war_with|has_war_with_amount|ic_ratio|is_ai|is_amphibious_invasion|is_attacker|is_border_conflict|is_claimed_by|is_coastal|is_controlled_by|is_core_of|is_defender|is_demilitarized_zone|is_faction_leader|is_fighting_air_units|is_fighting_in_terrain|is_guaranteed_by|is_historical_focus_on|is_in_faction|is_in_faction_with|is_in_home_area|is_ironman|is_lend_leasing|is_major|is_neighbor_of|is_on_continent|is_owned_by|is_puppet|is_puppet_of|is_subject|is_subject_of|is_winning|land_doctrine_level|less_combat_width_than_opponent|night|num_of_available_civilian_factories|num_of_available_military_factories|num_of_available_naval_factories|num_of_civilian_factories|num_of_controlled_states|num_of_factories|num_of_military_factories|num_of_naval_factories|'buildingtype'|num_of_nukes|original_tag|owns_state|phase|recon_advantage|region/area|reserves|ships_in_area|ships_in_state_ports|skill|skill_advantage|state_population|strength_ratio|surrender_progress|tag|temperature|threat)[ \t\n]*=[ \t\n]* \{//{tenter=anonblk}
`

that excludes predefined unwanted keywords, I'm unable to exclude user-defined custom keywords.

Is it clear enough?

**Comment by masatake** [comment]
I don't understand why you don't use just grep if you know what you want.

Anyway, here is the way in u-ctags:

```
[yamato@master]~/var/ctags-github% cat /tmp/hoi.ctags
--langdef=Hoi
--map-Hoi=+.hoi

--kinddef-Hoi=s,section,sections
# --kinddef-Hoi=a,attr,attributes

--_tabledef-Hoi=main
--_tabledef-Hoi=anonblk
--_tabledef-Hoi=namedblk
--_tabledef-Hoi=common

--_mtable-regex-Hoi=common/(country_event|trigger|mean_time_to_happen|option)[ \t\n]*=[ \t\n]* \{/\1/s/{tenter=namedblk}{scope=push}
--_mtable-regex-Hoi=common/([a-zA-Z_][a-zA-Z_0-9]*)[ \t\n]*=[ \t\n]*\{//{tenter=anonblk}

--_mtable-regex-Hoi=main/[ \t\n]+//
--_mtable-extend-Hoi=main+common
--_mtable-regex-Hoi=main/.//

--_mtable-regex-Hoi=anonblk/[ \t\n]+//
--_mtable-regex-Hoi=anonblk/([a-zA-Z_][a-zA-Z_0-9]*)[ \t\n]*=[ \t\n]*\{//{tenter=anonblk}
--_mtable-regex-Hoi=anonblk/\}//{tleave}
--_mtable-regex-Hoi=anonblk/.//

--_mtable-regex-Hoi=namedblk/[ \t\n]+//
--_mtable-extend-Hoi=namedblk+common
--_mtable-regex-Hoi=namedblk/\}//{tleave}{scope=pop}
[yamato@master]~/var/ctags-github% ./ctags --fields=+n --sort=no --options=/tmp/hoi.ctags -o - /tmp/input.hoi
country_event	/tmp/input.hoi	/^country_event = {$/;"	s	line:1
trigger	/tmp/input.hoi	/^	trigger = {$/;"	s	line:9	section:country_event
mean_time_to_happen	/tmp/input.hoi	/^		mean_time_to_happen = {$/;"	s	line:10	section:country_event.trigger
option	/tmp/input.hoi	/^	option = {$/;"	s	line:54	section:country_event
option	/tmp/input.hoi	/^	option = {$/;"	s	line:102	section:country_event
option	/tmp/input.hoi	/^	option = {$/;"	s	line:150	section:country_event
```
