### ISSUE TITLE
[main/entry.c] uninitialized variable 'lang'

### ISSUE THREAD

**Issue by jannick0** [universal-ctags/ctags#1622]
https://github.com/universal-ctags/ctags/blob/d1616530d659ba603454bde3506f22e7eb9eae7a/main/entry.c#L755-L773

**Comment by masatake** [comment]
Does your compiler warn this?

I understand the code as follows:
lang is referred only when kindIndex != KIND_GHOST_INDEX.
A value is assigned to lang when kindIndex == KIND_GHOST_INDEX.
So I can expect lang has a valid value when it is referred.

If we initialize lang at the first, I think it makes harder to understand the intent of the code.

**Comment by jannick0** [comment]
Ah, I see. But couldn't the compiler be pacified by an initialization like `lang = LANGUAGE_GHOST_INDEX`.

Please see #1624 regarding my compiler configuration.

**Comment by masatake** [comment]
I reread the discussion.

I still think the initialization for suppressing the warning from the compiler makes harder to understand the intent of the code.
