### ISSUE TITLE
[main/fmt.c] uninitialized variable 'f'

### ISSUE THREAD

**Issue by jannick0** [universal-ctags/ctags#1623]
https://github.com/universal-ctags/ctags/blob/d1616530d659ba603454bde3506f22e7eb9eae7a/main/fmt.c#L78

**Comment by masatake** [comment]
Does your compiler warn this?
If yes, I would like to know which compiler you are using.


Look at the for-loop ahead of the line.
f is initialized in the body of loop when tag->usedParserFields != 0.

If tag->usedParserFields == 0, there is no chance for initialzing f. However, in that case
we can expect findex == tag->usedParserFields. In this case f is not referred.

**Comment by jannick0** [comment]
The compiler does not grasp the semantic logic unfortunately. 

Here a suggestion which essentially implements what you are saying above and would pacify the compiler. Moreover, the case that `getParserField` returns `NULL` (which is not excluded) would be covered then, too.
```diff
@@ -64,7 +64,7 @@ static int printTagField (fmtSpec* fspec, MIO* fp, const tagEntryInfo * tag)
 	else
 	{
 		unsigned int findex;
-		const tagField *f;
+		const tagField *f = NULL;
 
 		for (findex = 0; findex < tag->usedParserFields; findex++)
 		{
@@ -73,7 +73,7 @@ static int printTagField (fmtSpec* fspec, MIO* fp, const tagEntryInfo * tag)
 				break;
 		}
 
-		if (findex == tag->usedParserFields)
+		if ( !f)
 			str = "";
 		else if (isFieldEnabled (f->ftype))
 			/* TODO: Don't use WRITER_XREF directly */
```

**Comment by jannick0** [comment]
@masatake Cf. [travis'](https://travis-ci.org/universal-ctags/ctags/jobs/323065084) output with the complaints of mingw's gcc.

**Comment by b4n** [comment]
I quite like the code in https://github.com/universal-ctags/ctags/issues/1623#issuecomment-354044391

**Comment by masatake** [comment]
@b4n, thank you.

@jannick0, could you make a pull request based on your comment?
