### ISSUE TITLE
[parsers/tcl.c] uninitialized variable 'r'

### ISSUE THREAD

**Issue by jannick0** [universal-ctags/ctags#1624]
https://github.com/universal-ctags/ctags/blob/d1616530d659ba603454bde3506f22e7eb9eae7a/parsers/tcl.c#L394

... potentially?
```c
int r = CORK_NIL;
```

**Comment by masatake** [comment]
Thank you.

Can I ask you to make a pull request for this?

I wonder why my gcc doesn't report this. Maybe I should add more options for making warnings.

**Comment by jannick0** [comment]
Done. I am compiling essentially with `mingw32-gcc.exe -Wall -Og -g` (version 6.3.0).
