### ISSUE TITLE
[DEBUG / MinGW] compilation error since getppid() not existing

### ISSUE THREAD

**Issue by jannick0** [universal-ctags/ctags#1625]
A CPP guard excluding this case branch for MinGW https://github.com/universal-ctags/ctags/blob/d1616530d659ba603454bde3506f22e7eb9eae7a/main/parse.c#L3962-L3966 like so
```c
#if DEBUG && ! __MINGW32__
```
would avoid a compilation error, since `getppid()` is not existing for `MinGW` IIRC. Some other OSes supposedly to be dealt with as well.

**Comment by masatake** [comment]
Thank you for making a pull request.

**Comment by jannick0** [comment]
@masatake Happy to do so, but I thought that this needed a broader approach as you indicated in #1619 (I am currently working on for the yacc syntax. PR will be updated soon I hope). ... or am I misunderstanding something in your posting above?

**Comment by masatake** [comment]
Wow, sorry. What I would like to say that "Thank you for opening this issue."
*I* will fix this issue. You don't have to do more.

**Comment by jannick0** [comment]
No worries at all! 

I guess that `getppid` is not available on Windows, so the exclusion could be achieved by either

- checking the existence in the `configure` step and defining `HAVE_GETPPID` or rather `HAVE_(what ever header file getppid is declared in)` which could then guard this `case` branch away; this could cope with other OSes automatically
- or - less subtly - saying `! WIN32` or so in place

**Comment by masatake** [comment]
Could you look at #1627?

**Comment by masatake** [comment]
Though I call getppid, it is not important. Calling any system call which is restricted using in the sandbox mode. getpid was one of the candidates but calling it multiple times are suppressed by glibc for optimizing purpose. So my choice was getppid:-P
