### ISSUE TITLE
Limit the output pattern entry length

### ISSUE THREAD

**Issue by b4n** [universal-ctags/ctags#163]
When outputting patterns as excmds, there is no maximum pattern length.  This is OK for normal source files when all lines have a reasonable length (like 120 columns tops and often less), but inappropriate when the lines are overly long, like with minified JavaScript or CSS.

Such files generally contain one single line, line that can be *very* long (like 30k characters).  This results in overly large tag files, yet pretty much useless patterns as all tags have the same one.

I think that the pattern length should be limited to some sane lengths, like 80 characters.  If needed, an option could probably be introduced, but I would believe that 80 characters is unique enough to be useful.

Ideally, and if users of the pattern excmd can use it, the pattern could be truncated around the actual location of the tag on the line rather than only keeping the start, but that's probably only fancier.

**Comment by blueyed** [comment]
Cutting the line at the end should still work (given that only the end-of-line marker is being removed).

However, if it would cut the pattern in the middle of some (escaped) special sequence, it might fail to get matched then.

Apart from that I think that a default limit of 80 characters would be nice to have. Maybe there could be different default limits, like 80 for json/js and 120 for all others?

**Comment by blueyed** [comment]
I consider it a grave bug, when a program accidentally fills up the whole disk with dozens of gigabytes (https://github.com/fishman/ctags/issues/201#issuecomment-68784338).

**Comment by masatake** [comment]
This issue hits me now.
Any patch I can try?

**Comment by masatake** [comment]
I'm working this now.

**Comment by masatake** [comment]
None may want to do tag-jump to such long input file. (Editor may hung:-P)
However, people may want the tag names for completion purpose.

My ideas is using `.{N}` regex pattern for omitting the pattern when a line is too long.

**Comment by masatake** [comment]
Long patterns derived from long input lines make tags file too large. As I wrote it causes "disk-full" error or "OOM-killer".  Shorten pattern I wrote above comment mitigates it. However, there is one more issue.

Making such pattern hogs CPU clock.  For testing I use 1M bytes single line json input:
```
    Evaluatoin:
    
    1. Making an input file for evaluation
    
        $ git clone https://github.com/google/trace-viewer.git
        $ git checkout 2ca1bc034d0055963541aad41ff3ff7fdf483b48
        $ LC_ALL=C ls -lh trace-viewer/tracing/test_data/repaints_on_scroll_region.json
        -rw-r--r--. 1 yamato yamato 9.2M Oct 15 03:08 trace-viewer/tracing/test_data/repaints_on_scroll_region.json
    
    This one is too large for current ctags. Make smaller one.
    
        $ dd if=trace-viewer/tracing/test_data/repaints_on_scroll_region.json of=tmp-1M.json bs=1024 count=1024
        $ zsh
```

To make tags file for the input, it takes about 40 seconds:
```
$ time ./ctags-incremental -o tags.incremental  tmp-1M.json > /dev/null; done;
        43.35s user 4.33s system 100% cpu 47.623 total
```

Unacceptably slow.

I'm working on optimizing:
 ```
[yamato@x201]~/var/ctags-github% time  ./ctags -o - tmp-1M.json    > /dev/null
./ctags -o - tmp-1M.json > /dev/null  0.11s user 0.02s system 99% cpu 0.128 total
```

It becomes fater. Now ctags makes tags file for the original input, repaints_on_scroll_region.json.
```
% LC_ALL=C ls -lh repaints_on_scroll_region.json
-rw-r--r--. 1 yamato yamato 9.2M Oct 15 03:10 repaints_on_scroll_region.json
% time ./ctags -o - repaints_on_scroll_region.json >/dev/null
1.35s user 0.13s system 126% cpu 1.171 total
```

After optmizing, the case parser-c/c-heapoverflow-sh-bug-363 is failed. More work is needed.

The optimization focuses on single long line inputs. For normal input, there is bad side effects.
```
before
./ctags-no-cache -o - -R ~/var/linux > /dev/null  19.47s user 1.62s system 112% cpu 18.719 total
./ctags-no-cache -o - -R ~/var/linux > /dev/null  19.53s user 1.63s system 113% cpu 18.706 total
./ctags-no-cache -o - -R ~/var/linux > /dev/null  19.74s user 1.63s system 112% cpu 18.930 total
after
./ctags-with-cache -o - -R ~/var/linux > /dev/null  25.83s user 1.72s system 109% cpu 25.101 total
./ctags-with-cache -o - -R ~/var/linux > /dev/null  26.06s user 1.61s system 109% cpu 25.272 total
./ctags-with-cache -o - -R ~/var/linux > /dev/null  25.75s user 1.76s system 109% cpu 25.100 total
```
Much slower. I will work more.

**Comment by masatake** [comment]
Disabling pattern cache when an input line is not long improves the result.
```
[yamato@x201]~/var/ctags-github% time  ./ctags -o - repaints_on_scroll_region.json > /dev/null
./ctags -o - repaints_on_scroll_region.json > /dev/null  1.10s user 0.15s system 131% cpu 0.953 total
[yamato@x201]~/var/ctags-github% export COUNT=2 echo before; repeat $COUNT; do time ./ctags-no-cache -o - -R ~/var/linux > /dev/null; done; echo after; repeat $COUNT; do time ./ctags -o - -R ~/var/linux > /dev/null; done
19.54s user 1.69s system 112% cpu 18.799 total
19.60s user 1.62s system 112% cpu 18.873 total
after
19.54s user 1.66s system 111% cpu 18.967 total
19.47s user 1.71s system 113% cpu 18.713 total
```

This is acceptable.

**Comment by masatake** [comment]
I found I took a fundamental mistaking.

It seems that `.{N}`, `.\{N\}`, or `.\{N}`. doesn't work well with vim.
Further more `.*` doesn't work, too.

input:
```
[yamato@x201]/tmp% cat foo.c
int main(void)
{
  return 0;
}
main();
```

make a tag file:
```
[yamato@x201]/tmp% ctags -o - foo.c | tee normal.tags
main	foo.c	/^int main(void)$/;"	f
```

Make a derived tag file which uses `.` in a pattern:
```
[yamato@x201]/tmp% cp normal.tags hacked.tags
[yamato@x201]/tmp% sed -i 's/ main/ .ain/' hacked.tags 
[yamato@x201]/tmp% cat hacked.tags 
main	foo.c	/^int .ain(void)$/;"	f
```

Failed in tag jumping(interactive operation)
```
[yamato@x201]/tmp% cp hacked.tags tags
cp hacked.tags tags
[yamato@x201]/tmp% gvim foo.c
```

Successful in tag jumping(interactive operation) 
```
[yamato@x201]/tmp% cp normal.tags tags
[yamato@x201]/tmp% gvim foo.c
```

Am I missing something?

**Comment by vhda** [comment]
From that list of commands, you did not copy `hacked.tags` into `tags` in the first jump attempt.

**Comment by masatake** [comment]
???  I think I copied it. (I put a maker '>' to the original post).

```
[yamato@x201]/tmp% cp hacked.tags tags
```

**Comment by vhda** [comment]
First you say that tag jumping failed, then you copy the file:

    [yamato@x201]/tmp% cat hacked.tags
    main    foo.c   /^int .ain(void)$/;"    f

Failed in tag jumping(interactive operation)

    [yamato@x201]/tmp% cp hacked.tags tags
    cp hacked.tags tags

**Comment by masatake** [comment]
Oh, sorry.

I made misleading.
I showed hacked.tags as an example of tags file, with that tag jumping is failed.

```
[yamato@x201]/tmp% cat hacked.tags 
main    foo.c   /^int .ain(void)$/;"    f
```
I expected the above pattern using `.` matches "main()", but the pattern doesn't work as I expected.

**Comment by vhda** [comment]
Currently boarding an airplane, so I can't provide further help. Sorry.

**Comment by masatake** [comment]
@vhda, oh, thank you.

I found a pattern that works:
```
main    foo.c   /^int \.ain(void)$/;"    f
```
It seems that a backslash is needed before meta character.

Further more

```
main	foo.c	/^int \.ain(\.\{5\}$/;"	f
```

also works. I will rewrite my patch.

**Comment by vhda** [comment]
As far as I can see `'magic'` is disabled in tag patterns. You could force enable it including `\m` in the beginning of the pattern, but given that the pattern is generated automatically simply escaping the special characters should be enough :)
