### ISSUE TITLE
[main/read.c] introduce variable lang to avoid multiple calls

### ISSUE THREAD

**Issue by jannick0** [universal-ctags/ctags#1632]
... to avoid multiple calls of `getInputLanguage ()` in central function `iFileGetLine`  I would like to suggest. I am happy to file a pull request.

https://github.com/universal-ctags/ctags/blob/4f9f6f83de929385c448e59d40e5b62588b6bbcb/main/read.c#L855-L896

**Comment by masatake** [comment]
What kind of suggestion? I would like to see it in a pull request because My C language skill is better than my English skill. Thank you.
