### ISSUE TITLE
'ctags -x' gets trunked

### ISSUE THREAD

**Issue by teto** [universal-ctags/ctags#1646]
Hi,

I am using ctags -x to retrieve C prototypes in a script but sometimes the signatures get trunked.
For instance if I run 
`ctags -x --c-kinds=fp` on https://github.com/lkl/linux/blob/master/tools/lkl/include/lkl.h
I get lkl_umount_dev prototype trunked
```
lkl_add_gateway  prototype   513 /home/teto/lkl/tools/lkl/include/lkl.h int lkl_add_gateway(int af, void *gwaddr);
lkl_add_neighbor prototype   481 /home/teto/lkl/tools/lkl/include/lkl.h int lkl_add_neighbor(int ifindex, int af, void* addr, void* mac);
lkl_closedir     prototype   238 /home/teto/lkl/tools/lkl/include/lkl.h int lkl_closedir(struct lkl_dir *dir);
lkl_dirfd        prototype   265 /home/teto/lkl/tools/lkl/include/lkl.h int lkl_dirfd(struct lkl_dir *dir);
....
lkl_umount_dev   prototype   194 /home/teto/lkl/tools/lkl/include/lkl.h long lkl_umount_dev(unsigned int disk_id, unsigned int part, int flags,
lkl_umount_timeout prototype   206 /home/teto/lkl/tools/lkl/include/lkl.h long lkl_umount_timeout(char *path, int flags, long timeout_ms);

```
How can I get the full prototype please ?

**Comment by teto** [comment]
sorry i am actually using exuberant-ctags wron repo :s

**Comment by masatake** [comment]
The last component of -x output is "pattern".

`--_xformat` is for you. See http://docs.ctags.io/en/latest/news.html#customizing-xref-output .

```
[jet@localhost]~/var/ctags% ./ctags --kinds-c=fp -x --_xformat='%-16N %-10K %4n %-16F %C SIGNATURE:%{signature}'  lkl.h | grep lkl_umount_dev
lkl_umount_dev   prototype   207 lkl.h            long lkl_umount_dev(unsigned int disk_id, unsigned int part, int flags, SIGNATURE:(unsigned int disk_id,unsigned int part,int flags,long timeout_ms) 
```

**Comment by teto** [comment]
Perfect I did spend some time in the man but missed that thx

**Comment by masatake** [comment]
We didn't have updated the man pages yet.

**Comment by teto** [comment]
Looking at the doc, I couldn't find a field for --_xformat that prints the return value ? Did I miss anything ?

NB: In the documentation you linked there is a missing dash before `-list-fields`; `Here field means an item listed with -list-fields option`.

**Comment by masatake** [comment]
```
/ctags --kinds-c=fp -x --_xformat='%-16N %-10K %4n %-16F %C RTYPE %{typeref} SIGNATURE:%{signature}'  lkl.h | grep lkl_umount_dev
lkl_umount_dev   prototype   207 lkl.h            long lkl_umount_dev(unsigned int disk_id, unsigned int part, int flags, RTYPE long SIGNATURE:(unsigned int disk_id,unsigned int part,int flags,long timeout_ms)
```

The field name , `typeref`, is under disucssion. https://github.com/universal-ctags/ctags/issues/862

**Comment by teto** [comment]
That worked great thanks.
