### ISSUE TITLE
Possible NULL dereference in storeAdaTags

### ISSUE THREAD

**Issue by SiIky** [universal-ctags/ctags#1653]
https://github.com/universal-ctags/ctags/blob/4dbeb0be3a2e2f710ca8468badeba7611b79f906/parsers/ada.c#L2051-L2171
First possible NULL derefence at line 2088.
https://github.com/universal-ctags/ctags/blob/4dbeb0be3a2e2f710ca8468badeba7611b79f906/parsers/ada.c#L2088
`storeAdaTags()` is called only twice and `token` is not NULL in neither of those, so I think the if should either be removed or have the rest of the function inside it.

**Comment by SiIky** [comment]
I didn't make a pull request because I didn't know which you preferred (to remove the if or not)
No, I used `cppcheck` :p I found another bug today so I'll create a new issue for it later and elaborate on `cppcheck`

**Comment by masatake** [comment]
I see.

**Comment by SiIky** [comment]
Fixed in 047870360a5e6995cd52b79343fdcc7327d19c4e
