### ISSUE TITLE
Wrong NULL check

### ISSUE THREAD

**Issue by SiIky** [universal-ctags/ctags#1655]
https://github.com/universal-ctags/ctags/blob/796684b6bb67dc9cc738f619baec89f9ece863fa/parsers/cxx/cxx_token_chain.c#L291-L300
Returns early if `t` is non NULL, otherwise, since `vStringCatS()` doesn't touch `t` and `cxxTokenAppendToString()` doesn't check for NULL `t` is dereferenced.

As mentioned in my other issue, I used `cppcheck` to find these.
```sh
find . -name '*.[ch]' |\
 cppcheck --std=c99 -v --language=c -f --enable=warning --file-list=- 2&>cppcheck.log
```
Don't know where all the code and tests are, but thought the parsers directory was a good place to start :) The message cppcheck gave for this one was:
```
[parsers/cxx/cxx_token_chain.c:294] -> [parsers/cxx/cxx_token_chain.c:304]: (warning) Either the condition 't' is redundant or there is possible null pointer dereference: t.
```

**Comment by masatake** [comment]
Thank you.
We have to think about running cppcheck on Travis.
cppcheck target is already defined in makefiles/testing.mak.

**Comment by codebrainz** [comment]
Even better, use the clang analyzers since they have full insight into the code/compilation and are linked into the binary under test, they are much more accurate and thorough.

**Comment by masatake** [comment]
I found the line is not covered by our test cases.
At least cxxScopeGetFullNameExceptLastComponentAsString in cxxTagCommit in cxx_tag.c must be called.
