### ISSUE TITLE
Clojure parser should handle metadata tags

### ISSUE THREAD

**Issue by arichiardi** [universal-ctags/ctags#1657]
In Clojure we have custom readers and one of them adds metadata to the symbol it preceeds.

I have a file like this one:

```clojure
(ns ^{:doc "Utility functions."} ep-cloud.util)

(defn debug? ^boolean
  []
  goog.DEBUG)
```

produces:

```
!_TAG_FILE_FORMAT	3	/extended format with meta character escaping/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/70dd618/
^{:doc	src/ep_cloud/util.cljc	/^(ns ^{:doc "Utility functions."} ep-cloud.util)$/;"	n
debug?	src/ep_cloud/util.cljc	/^(defn debug? ^boolean$/;"	f	namespace:^{:doc
```

it should produce:

```
!_TAG_FILE_FORMAT	3	/extended format with meta character escaping/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/70dd618/
ep-cloud.util	src/ep_cloud/util.cljc	/^(ns ^{:doc "Utility functions."} ep-cloud.util)$/;"	n
debug?	src/ep_cloud/util.cljc	/^(defn debug? ^boolean$/;"	f	namespace:ep-cloud.util
```

The command is `ctags filename.cljs`

The metadata `^` is on the namespace AND before `debug?` and it can be before any symbol for that matter, so it should always be skipped. 

According to the Clojure specification, the opening char is always `^` and the metadata section finishes at a the first space.

I also wanted to point to a very nice [test project](https://github.com/kawas44/test-tags-for-clojure/blob/master/gen_tags.sh) for trying things out.

Thanks for your work!

**Comment by masatake** [comment]
I don't understand what you want.
`debug?` is captured well.  What kind of output from ctags do you want?

**Comment by arichiardi** [comment]
Sorry I have not explained it very well...also, this is an improvement that is scheduled in my queue.
Check another symbol in the same namespace for instance:

```
debug	src/ep_cloud/utils.cljs	/^(defn debug [label]$/;"	f	namespace:cqrs-cljs.utils
```

**Comment by masatake** [comment]
Still I don't understand. In the example `debug` after `defn` is captured well.
From input `(defn debug?...`, ctags emits `debug?`.
From input `(defn debug...`, ctags emits `debug`. 
What's wrong?

What I need to know is small input and expected tags output for it.

**Comment by arichiardi** [comment]
The correct out put for the function with the `^:boolean` should be the same as the one without the boolean basically.

The exact output is shown in my previous message.

**Comment by masatake** [comment]
Still I don't understand. Do you mean the question mark should be trimmed?

```
(defn debug? ^boolean
  []
  goog.DEBUG)
```

For the above input, do you want following output?

```
debug	src/ep_cloud/utils.cljs	/^(defn debug [label]$/;"	f	namespace:cqrs-cljs.utils
```

**Comment by arichiardi** [comment]
No so basically the current output is:

```
debug?	src/ep_cloud/util.cljc	/^(defn debug ^boolean$/;"	f	namespace:^{:doc
``` 

That namespace is wrong.

It should instead be:

```
debug?	src/ep_cloud/utils.cljs	/^(defn debug [label]$/;"	f	namespace:cqrs-cljs.utils
```

It looks like the regex does not skip `^:boolean`. Everything with that precedes a symbol but starts with `^` in Clojure is [metadata](https://clojure.org/reference/metadata) and should be skipped for this kind of tagging.

**Comment by masatake** [comment]
> That namespace is wrong.

Oh, I see. However, what I don't understand next is "^{:doc". Where it comes from?

```
(defn debug? ^boolean
  []
  goog.DEBUG)
```

There is no string like "^{:doc" in the sample input.
Actually when I run ctags for the input, what I got is

```
debug?	/tmp/foo.clj	/^(defn debug? ^boolean$/;"	f
```

There is no namespcae: field in the output.

**Comment by masatake** [comment]
So the code of ctags scanning  and capturing namespace information may be wrong.
How the namespace is given in the original input you are talking about?

**Comment by arichiardi** [comment]
Sorry for the delay, I think what the code needs to do is to skip everything from `^{` to `}` and then then symbol after is the beginning of the namespace name.

Will write a better recap.

**Comment by arichiardi** [comment]
The namespace is not involved in the definition and it is computed from the name of the file where the definition resides.

**Comment by masatake** [comment]
Please, read http://docs.ctags.io/en/latest/reporting.html carefully.
You have to answer where "^{:doc" comes from.

**Comment by arichiardi** [comment]
@masatake why has this been closed? I mean to explain, but you are not doing a good job in closing a bug report like this in my opinion.

**Comment by arichiardi** [comment]
The reporting section is good, I will for sure write a better report. Closing and reopening does not seem a good approach as you lose history. Anyways up to you.

**Comment by arichiardi** [comment]
Additionally, I think my comment https://github.com/universal-ctags/ctags/issues/1657#issuecomment-374835234 answers the question, after that comment you started asking question about the implementation of `ctags` which I am not familiar with.

Please read again the comment above to see what is that I see and what is the expected output.
You are focusing on ` "^{:doc"`, which is part of the bug, I don't know where it comes from.

If you want I can try to run the tool again and report the output again.

**Comment by masatake** [comment]
Please, prepare following things:

* the original input
* actual output from u-ctags
* expected output (output you want)
* the command line you used to generated the actual output

Above combination is very important.
Please, read http://docs.ctags.io/en/latest/reporting.html carefully.

**Comment by masatake** [comment]
The combination must be prepared in a comment.
Reporting them in comments makes me confused.
https://github.com/universal-ctags/ctags/issues/1340 this one is beautiful.

**Comment by arichiardi** [comment]
Will do my best

**Comment by masatake** [comment]
You report the input in the initial comment:
```
(defn debug? ^boolean
  []
  goog.DEBUG)
```

You wrote following as actual output for the input:
```
debug?	src/ep_cloud/util.cljc	/^(defn debug? ^boolean$/;"	f	namespace:^{:doc
```

You didn't wrote the expected output in the comment. 

> At the moment uctags fails to recognize symbols with metadata attached.

You wrote just "fails".

As far as reading the source code of clojure parser, `^{:doc` must come from `(ns ...` somewhere in the original input. However, `ns` is not found in the original input.

There can be two cases, one is something to do with uninitialized memory. The another is you omitted the original input when reporting here.

**Comment by masatake** [comment]
Show src/ep_cloud/utils.cljs if you can.

**Comment by arichiardi** [comment]
I updated the initial report: https://github.com/universal-ctags/ctags/issues/1657#issue-287925993

**Comment by masatake** [comment]
Fine!

**Comment by arichiardi** [comment]
Updated with the desired output, thanks a lot and sorry for the hassle.

**Comment by masatake** [comment]
Maybe solved. I will make a pull request tomorrow.

```
[yamato@master]~/var/ctags-github% cat Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
;; Taken from #1657 opened by @arichiardi
(ns ^{:doc "Utility functions."} ep-cloud.util)

(defn debug? ^boolean
  []
  goog.DEBUG)

[yamato@master]~/var/ctags-github% ./ctags -o - Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
debug?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug? ^boolean$/;"	f	namespace:ep-cloud.util
ep-cloud.util	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^{:doc "Utility functions."} ep-cloud.util)$/;"	n

[yamato@master]~/var/ctags-github% ./ctags --sort=no -o - Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
./ctags --sort=no -o - Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
ep-cloud.util	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^{:doc "Utility functions."} ep-cloud.util)$/;"	n
debug?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug? ^boolean$/;"	f	namespace:ep-cloud.util
[yamato@master]~/var/ctags-github% git diff |cat
git diff |cat
diff --git a/parsers/clojure.c b/parsers/clojure.c
index 5e62152d..8ed1d576 100644
--- a/parsers/clojure.c
+++ b/parsers/clojure.c
@@ -62,6 +62,19 @@ static void functionName (vString * const name, const char *dbp)
 
 static int makeNamespaceTag (vString * const name, const char *dbp)
 {
+	/* skipping metadata */
+	if (*dbp == '^' && *(dbp + 1) == '{')
+	{
+		/* skipping metadata */
+		for (; *dbp != '\0' && *dbp != '}'; dbp++)
+			;
+		if (*dbp == '\0')
+			return CORK_NIL;
+		dbp++;
+		while (isspace ((int)*dbp)) /* TODO */
+			dbp++;
+	}
+
 	functionName (name, dbp);
 	if (vStringLength (name) > 0 && ClojureKinds[K_NAMESPACE].enabled)
 	{
```

**Comment by arichiardi** [comment]
@masatake first of all thanks, second if I read correctly you are skipping only after `^{`. 
The language dictates to skip after `^`.

As you can see in the example `^boolean` is vaild metadata, as well as `^:private`.

When you have a PR ready I can try it out, I checked out the repo.

**Comment by masatake** [comment]
Any Sexp is ok after `^`?

**Comment by arichiardi** [comment]
Pretty much, actually I have just noticed you can have multiple, like

`^:dynamic ^ints whatever`

https://clojure.org/reference/metadata

**Comment by masatake** [comment]
```
[yamato@master]~/var/ctags-github% cat Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
cat Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
;; Taken from #1657 opened by @arichiardi
(ns ^{:doc "Utility functions."} ns0)
(defn debug0? ^boolean
  []
  goog.DEBUG)


(ns ^:dynamic ns1)
(defn debug1? ^boolean
  []
  goog.DEBUG)

(ns ^String ns2)
(defn debug2? ^boolean
  []
  goog.DEBUG)

(ns ^{:doc "Utility functions."} ^{:doc1 "something"} ns00)
(defn debug00? ^boolean
  []
  goog.DEBUG)

(ns ^{:doc "Utility functions."} ^:dynamic ns01)
(defn debug01? ^boolean
  []
  goog.DEBUG)

(ns ^{:doc "Utility functions."} ^String ns02)
(defn debug02? ^boolean
  []
  goog.DEBUG)


(ns ^:dynamic ^{:doc "Utility functions."} ns10)
(defn debug10? ^boolean
  []
  goog.DEBUG)
  
(ns ^:dynamic ^:dynamic-something ns11)
(defn debug11? ^boolean
  []
  goog.DEBUG)

(ns ^:dynamic ^String ns12)
(defn debug12? ^boolean
  []
  goog.DEBUG)

(ns ^String ^{:doc "Utility functions."} ns20)
(defn debug20? ^boolean
  []
  goog.DEBUG)

(ns ^String ^:dynamic ns21)
(defn debug21? ^boolean
  []
  goog.DEBUG)

(ns ^String ^String-something ns22)
(defn debug22? ^boolean
  []
  goog.DEBUG)


[yamato@master]~/var/ctags-github% ./ctags --sort=no -o - Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
./ctags --sort=no -o - Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj
ns0	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^{:doc "Utility functions."} ns0)$/;"	n
debug0?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug0? ^boolean$/;"	f	namespace:ns0
ns1	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^:dynamic ns1)$/;"	n
debug1?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug1? ^boolean$/;"	f	namespace:ns1
ns2	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^String ns2)$/;"	n
debug2?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug2? ^boolean$/;"	f	namespace:ns2
ns00	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^{:doc "Utility functions."} ^{:doc1 "something"} ns00)$/;"	n
debug00?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug00? ^boolean$/;"	f	namespace:ns00
ns01	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^{:doc "Utility functions."} ^:dynamic ns01)$/;"	n
debug01?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug01? ^boolean$/;"	f	namespace:ns01
ns02	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^{:doc "Utility functions."} ^String ns02)$/;"	n
debug02?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug02? ^boolean$/;"	f	namespace:ns02
ns10	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^:dynamic ^{:doc "Utility functions."} ns10)$/;"	n
debug10?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug10? ^boolean$/;"	f	namespace:ns10
ns11	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^:dynamic ^:dynamic-something ns11)$/;"	n
debug11?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug11? ^boolean$/;"	f	namespace:ns11
ns12	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^:dynamic ^String ns12)$/;"	n
debug12?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug12? ^boolean$/;"	f	namespace:ns12
ns20	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^String ^{:doc "Utility functions."} ns20)$/;"	n
debug20?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug20? ^boolean$/;"	f	namespace:ns20
ns21	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^String ^:dynamic ns21)$/;"	n
debug21?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug21? ^boolean$/;"	f	namespace:ns21
ns22	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(ns ^String ^String-something ns22)$/;"	n
debug22?	Units/parser-clojure.d/clojure-metadata-in-ns.d/input.clj	/^(defn debug22? ^boolean$/;"	f	namespace:ns22
[yamato@master]~/var/ctags-github% git diff |cat
git diff |cat
diff --git a/parsers/clojure.c b/parsers/clojure.c
index 5e62152d..dbffb1f3 100644
--- a/parsers/clojure.c
+++ b/parsers/clojure.c
@@ -62,6 +62,35 @@ static void functionName (vString * const name, const char *dbp)
 
 static int makeNamespaceTag (vString * const name, const char *dbp)
 {
+	/* skipping metadata */
+	while (1)
+	{
+		if (*dbp == '^')
+		{
+			/* skipping metadata */
+			dbp++;
+			if (*dbp == '{')
+			{
+				for (; *dbp != '\0' && *dbp != '}'; dbp++)
+					;
+				if (*dbp == '\0')
+					return CORK_NIL;
+				dbp++;
+			}
+			else
+			{
+				for (; *dbp != '\0' && !isspace((int)*dbp); dbp++)
+					;
+				if (*dbp == '\0')
+					return CORK_NIL;
+			}
+			while (isspace ((int)*dbp)) /* TODO */
+				dbp++;
+		}
+		else
+			break;
+	}
+
 	functionName (name, dbp);
 	if (vStringLength (name) > 0 && ClojureKinds[K_NAMESPACE].enabled)
 	{
[yamato@master]~/var/ctags-github% 
```

**Comment by masatake** [comment]
To get perfect results, SkipSexp is needed. Implementing it means rewriting the clojure parser.

**Comment by arichiardi** [comment]
Got it, yes I feel that sooner or later a proper parser is needed. This looks better already :smile:

**Comment by masatake** [comment]
The patch is imperfect. However, I hope it handles the more of all codes in the real world.
I wonder I can expect such a thing. Lisp hackers always do more than I can image.

**Comment by masatake** [comment]
I will take asleep. Good night.

**Comment by arichiardi** [comment]
Good night man, thank you!

**Comment by arichiardi** [comment]
You got that right as well :smile:

**Comment by masatake** [comment]
I made a pull request for this issue: #1743 .

**Comment by arichiardi** [comment]
Sorry to write here and I very newbie question, but how to use the compiled version of this patch in a `gtags_parser` entry?

I see I need `.la` files there, but `make` does not produce them?

How does it work?

**Comment by masatake** [comment]
this patch? which patch?
