### ISSUE TITLE
Support for "CREATE TABLE AS" SQL syntax 

### ISSUE THREAD

**Issue by karlb** [universal-ctags/ctags#1658]
Running ctags on the following file will lead to correct tags for the table `foo`, but table `bar` is missed completely. I assume this is caused by the `CREATE TABLE AS` syntax.

```sql
CREATE TABLE foo(
    col1 text
);

CREATE TABLE bar AS
SELECT 1 AS col1;
```

Ideally, both the table and the column would be picked up by ctags, but at least the table name should be included in the tags file.

**Comment by masatake** [comment]
> Ideally, both the table and the column would be picked up by ctags, but at least the table name should be included in the tags file.

Do you mean ctags should capture `col1` in `bar` ?

**Comment by karlb** [comment]
Sorry for the late reply. I was pretty sure that I responded already, but apparently I didn't or my response got lost somehow.

> Do you mean ctags should capture col1 in bar ?

Yes, that would be ideal. The important thing for me is that the table name gets picked up, but including that columns would be best.

The code handling this should probably be the same one as for views.

```sql
CREATE VIEW bar AS
SELECT 1 AS col1;
```

would create the same structure (table/view name "bar" with one column named "col1") with the only difference that it is a view instead of a table.
