### ISSUE TITLE
Cxx: broken input crashes ctags crash

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1659]
input.cc
```
__attribute__((visibility("protected")))
        f1(int f1p1,int f1p2 __attribute__([(unused)),int f1p3)
                __attribute__ ((warn_unused_result,always_inline,deprecated))
{
```

For the input I got:

```
[yamato@master]~/var/ctags-github% ./ctags -o - input.cc
./ctags -o - input.cc
zsh: segmentation fault (core dumped)  ./ctags -o - input.cc
```

`make noise` reports this.

**Comment by b4n** [comment]
There are a few places where a `CXX_DEBUG_ASSERT(x, …)` is *not* followed by a non-debug test for the same thing, yet several other places do (e.g. parsers/cxx/cxx_parser_function.c#L115).  As `cxxTokenTypeIs()` is not NULL-safe, any non-buggy situation should be guarded against dereferencing a NULL token.

I'm not sure if the best way is to double check every time, or if for some a NULL-safe `cxxTokenTypeIs()` would be easier/better.

**Comment by pragmaware** [comment]
@b4n : you're right, the usage is inconsistent in some places. The presence of the non-debug check usually indicates that at the time of writing I wasn't 100% sure that the condition enforced by the assert was an invariant.

cxxTokenTypeIs() is a macro used very frequently and in most cases the "caller" knows for sure that the token is not NULL. So adding a NULL check there adds a performance penalty that is avoidable.
