### ISSUE TITLE
Problems with Windows CLI directory exclude

### ISSUE THREAD

**Issue by ianchanning** [universal-ctags/ctags#1672]
I am using the ctags win32 release [2018-01-30/17d07a30][1]. I am on Windows 10 64-bit.

I have a work around for the following issue, so I'm mostly just documenting the issues, which is that I could not get the `--exclude` option to work on the command line in Windows.

Firstly thank you for this project, now that I have it working it's a great improvement over exuberant-ctags, handling javascript functions and php methods much better! 

I have a `node_modules` directory in my project that I wanted to exclude.

My attempt to put my `.ctags` file into `%userprofile%\.ctags.d\.ctags` didn't work as running `ctags -R .` ignored that file. The eventual workaround, after following [this comment][2] was to put my `.ctags` file into the project directory as `C:\path\to\project\.ctags.d\exclude.ctags` this worked and used the ignore setting that I had.

The main issue that I hit after that was in my attempts to test which excludes would work at the command line. I tried all of the following and none worked. In my project I have a directory `app\webroot\bootstrap-3.3.7\node_modules` that I want to exclude, this is what I tried, ctags would look inside the directory for every one of these attempts:

```
ctags -R . --exclude=node_modules\*
ctags -R . --exclude=*\node_modules\*
ctags -R . --exclude=*/node_modules/*
ctags -R . --exclude=app\webroot\bootstrap-3.3.7
ctags -R . --exclude=app/webroot/bootstrap-3.3.7
ctags -R . --exclude=*bootstrap-3.3.7/*
ctags -R . --exclude=*bootstrap-3.3.7\*
ctags -R . --exclude=*bootstrap-3.3.7\\*
ctags -R . --exclude=app\\webroot\\bootstrap-3.3.7\\*
ctags -R . --exclude=node_modules
```

I tried to follow both #759 and #1609, but neither seemed to help.

This is the contents of what was my `.ctags` file and is now `exclude.ctags`:

```
--exclude=.svn
--exclude=.git
--exclude=node_modules
--exclude=plotlyjs
--exclude=highcharts4
--exclude=bootstrap-3.3.7
--exclude=html2canvas
--exclude=jspdf
--exclude=tests
--exclude=vendors
--langmap=php:+.ctp
```

Now that ctags is picking up my `exclude.ctags` file then it no longer attempts to look inside the `node_modules` directory.

[1]: https://github.com/universal-ctags/ctags-win32/releases/download/2018-01-30%2F17d07a30/ctags-2018-01-30_17d07a30-x64.zip
[2]: https://github.com/universal-ctags/ctags/issues/1608#issuecomment-350493824

**Comment by masatake** [comment]
What happens if you use slash instead of backslash as discussed in #759.

**Comment by ianchanning** [comment]
@masatake yes amongst the list above I tried `ctags -R . --exclude=app/webroot/bootstrap-3.3.7` which didn't work. Here's what I get, you can see that it's throwing warnings from searching files in the `bootstrap-3.3.7` directory.

```
C:\inetpub\wwwroot\my_project>ctags -R . --exclude=app/webroot/bootstrap-3.3.7
ctags: Warning: ignoring null tag in app\webroot\bootstrap-3.3.7\docs\assets\js\customize.min.js(line: 47)
ctags: Warning: ignoring null tag in app\webroot\bootstrap-3.3.7\docs\assets\js\vendor\less.min.js(line: 14)
ctags: Warning: ignoring null tag in app\webroot\bootstrap-3.3.7\node_modules\acorn\src\expression.js(line: 39)
ctags: Warning: ignoring null tag in app\webroot\bootstrap-3.3.7\node_modules\bl\node_modules\readable-stream\lib\_stream_readable.js(line: 768)
ctags: Warning: ignoring null tag in app\webroot\bootstrap-3.3.7\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_readable.js(line: 768)
```

**Comment by masatake** [comment]
This is nothing to do with Windows.

**Comment by masatake** [comment]
Could you try the following command line?

```
ctags -R --exclude=node_modules .
```

**Comment by ianchanning** [comment]
Yes, that works correctly. So it's purely the placement of the `.`. d'Oh!

**Comment by ianchanning** [comment]
Sorry for the time waste. Thanks for looking into it.

**Comment by masatake** [comment]
I wonder how to handle optoins after input arguments.
The simplest one is rejecting such options. 
(invocation parseCmdlineOptions in createTagsForArgs )

**Comment by ianchanning** [comment]
I'm pretty sure that exuberant-ctags ignored them, looking through my command history I'd made similar mistakes before but also put it around the correct way too.

Although `ls` will handle `ls -l * -rt`.
