### ISSUE TITLE
Supporting Forth language

### ISSUE THREAD

**Issue by hisnawi** [universal-ctags/ctags#1674]
Is there a plan to support forth language?
I am using gtags and universal-ctags as the ctags engine but forth files (.fth .ftb) are not being parsed.

**Comment by masatake** [comment]
We may support all languages other than natural languages and languages for machine(machine code).
If a language is not supported in u-ctags, it is because none writes a parser and test cases for the language.

So the question goes back to you. Are you interested in writing them?

**Comment by hisnawi** [comment]
I found online that the parser is very simple:

```
--langdef=forth
--langmap=forth:.fth.ftb
--regex-forth=/^\s*:\s+([^ ]+)/\1/d,definition/


```

But I don't have the needed knowledge to incorporate that in ctags.

I also tried to include the above code in a .ctags file but it seems gtags.conf doesn't recognize the file.

**Comment by masatake** [comment]
> But I don't have the needed knowledge to incorporate that in ctags.

No problem. I can do it well.

The first of all, we need a license notice.

See 
https://github.com/universal-ctags/ctags/blob/master/optlib/pod.ctags.

This is an example.

You can use '#' as starter of comment.
For integrating with ctags, the source code must be distributable with "GPL v2 or later".
If you are o.k. about the license, could you put paster your .ctags which includes forth parser here again with the copyright notice?
Then  I will put your code to optlib directory of u-ctags source tree. u-ctags build system may translate your .ctags to C language.

The next step is writing test cases. The test cases are really important to extend the life of ctags development. Could you read http://docs.ctags.io/en/latest/units.html first?
I don't know forth language though I was a postscript hacker:-P 
http://web.mit.edu/~firebird/arch/sun4x_59/share/ghostscript/7.07/lib/CIDFnmap

People who knows force must write pairs of example force inputs and expected ctags outputs.
 
> I also tried to include the above code in a .ctags file but it seems gtags.conf doesn't recognize the file.
I'm sorry that I don't know well about gtags, so I cannot help you.

**Comment by masatake** [comment]
Just a question. Which OS do you use for running ctags?

**Comment by hisnawi** [comment]
I use OSX

**Comment by masatake** [comment]
> I use OSX
I see. Thank you.

Of course, you can make a pull request based on your .ctags.
See `git show 3409f3d` as an example. To run a program translating foo.ctags to foo.c, you may have to do "bash ./autogen.sh". The steps are not so simple but if you are interested in supporting more languages than force, it may be worth to know.

**Comment by masatake** [comment]
ping.

**Comment by hisnawi** [comment]
Thanks for the idea. I found another way getting the tags for a forth language based file.

**Comment by d99943001** [comment]
Hi @hisnawi, I'm interested in forth ctags as well.  
Could you please let me know how you get the tags from your forth code?
I'm desperately trying to get it,  but have no any progress...

**Comment by masatake** [comment]
```
[yamato@slave]/tmp% cat forth.ctags                                                     
--langdef=forth
--map-forth=+.fth
--map-forth=+.ftb
--kinddef-forth=d,definition,definitions
--regex-forth=/^\s*:\s+([^ ]+)/\1/d/
[yamato@slave]/tmp% cat input.fth 
: a-forth-word ( a b c -- a*b+c )  + * ;
[yamato@slave]/tmp% u-ctags -o - --options=./forth.ctags input.fth
a-forth-word	input.fth	/^: a-forth-word ( a b c -- a*b+c )  + * ;$/;"	d	language:forth
```

Capturing only defintions may not be enough.
See https://searchcode.com/codesearch/view/115911295/
