### ISSUE TITLE
c/c++ struct declarations containing macro functions not handled correctly

### ISSUE THREAD

**Issue by bfrg** [universal-ctags/ctags#1675]
Structure declarations that contain macro functions are not parsed correctly.
Example:
```cpp
// test.h
#define __device_builtin__
#define __builtin_align__(x)

// structure longlong4 is completely ignored
struct __device_builtin__ __builtin_align__(16) longlong4
{
    // x,y,z,w will be parsed as (global) variables and not members
    long long int x, y, z, w;
};

// this one is parsed correctly
struct __device_builtin__ longlong3
{
    long long int x, y, z;
};
```
Generated tags file (run `ctags test.h`):
```
__builtin_align__	test.h	/^#define __builtin_align__(/;"	d
__device_builtin__	test.h	/^#define __device_builtin__$/;"	d
longlong3	test.h	/^struct __device_builtin__ longlong3$/;"	s
w	test.h	/^    long long int x, y, z, w;$/;"	v	typeref:typename:long long int
x	test.h	/^    long long int x, y, z, w;$/;"	v	typeref:typename:long long int
x	test.h	/^    long long int x, y, z;$/;"	m	struct:longlong3	typeref:typename:long long int
y	test.h	/^    long long int x, y, z, w;$/;"	v	typeref:typename:long long int
y	test.h	/^    long long int x, y, z;$/;"	m	struct:longlong3	typeref:typename:long long int
z	test.h	/^    long long int x, y, z, w;$/;"	v	typeref:typename:long long int
z	test.h	/^    long long int x, y, z;$/;"	m	struct:longlong3	typeref:typename:long long int
```
 Sort of related: #1374 

Tested with the latest github version.

**Comment by masatake** [comment]
(-D option doesn't work expectedly. I wodner why.)

**Comment by bfrg** [comment]
Maybe I should have mentioned that the code snippet is from a header file which is supplied by **CUDA**. You can find it in `/usr/local/cuda/include/vector_types.h` (or where ever you have it installed). 
Here's a link to an older version of the header [vector_types.h](https://github.com/pathscale/nvidia_sdk_samples/blob/master/matrixMul/build/cuda/5.0.35-13978363_x64/include/vector_types.h#L302) (that's the only version I could find on the internet).

**Comment by b4n** [comment]
@masatake what do you mean?  `ctags -D '__builtin_align__(x)='` works perfectly fine for me, and does fix the issue.

Here, I wonder whether the parser should augment the `-D` mapping with macros found in the source, or if this should be a WONTFIX/workaround available.

**Comment by masatake** [comment]
@b4n, I called ctags with "ctags -D '__builtin_align__='", mistakenly. Sorry for making the noise.
BTW, as the shorthand notation, adding -U seems a good  idea: -U __builtin_align__.

Utilizing the macro definition is really attractive idea especially if ctags ca scan whole the input source tree more than once as I wrote in #1495. However, for awhile, we should put it "WONTFIX/workaround".
This is my position. What I have to do is reviewing your patch for readtags, updating the documents and releasing 5.9 or 6.0.

BTW, assuming the last token before `{` is the tag of struct is another heuristic. However, I wonder this heuristic may conflict with the other heuristics already implemented in cxx parser.

**Comment by masatake** [comment]
@bfrg, as @b4n wrote, could you try `-D` option like following:

```
[yamato@master]/tmp% cat /tmp/foo.h
cat /tmp/foo.h
// test.h
#define __device_builtin__
#define __builtin_align__(x)

// structure longlong4 is completely ignored
struct __device_builtin__ __builtin_align__(16) longlong4
{
    // x,y,z,w will be parsed as (global) variables and not members
    long long int x, y, z, w;
};

// this one is parsed correctly
struct __device_builtin__ longlong3
{
    long long int x, y, z;
};
[yamato@master]/tmp% u-ctags -D__device_builtin__= '-D__builtin_align__(x)=' -o - foo.h  2>/dev/null
u-ctags -D__device_builtin__= '-D__builtin_align__(x)=' -o - foo.h  2>/dev/null
__builtin_align__	foo.h	/^#define __builtin_align__(/;"	d
__device_builtin__	foo.h	/^#define __device_builtin__$/;"	d
longlong3	foo.h	/^struct __device_builtin__ longlong3$/;"	s
longlong4	foo.h	/^struct __device_builtin__ __builtin_align__(16) longlong4$/;"	s
w	foo.h	/^    long long int x, y, z, w;$/;"	m	struct:longlong4	typeref:typename:long long int
x	foo.h	/^    long long int x, y, z, w;$/;"	m	struct:longlong4	typeref:typename:long long int
x	foo.h	/^    long long int x, y, z;$/;"	m	struct:longlong3	typeref:typename:long long int
y	foo.h	/^    long long int x, y, z, w;$/;"	m	struct:longlong4	typeref:typename:long long int
y	foo.h	/^    long long int x, y, z;$/;"	m	struct:longlong3	typeref:typename:long long int
z	foo.h	/^    long long int x, y, z, w;$/;"	m	struct:longlong4	typeref:typename:long long int
z	foo.h	/^    long long int x, y, z;$/;"	m	struct:longlong3	typeref:typename:long long int
```

It is nice if we don't have to specify `-D` option. However, I would like to say adding too much heretics is not good idea. To do it perfectly, we have to parse scripts for build system because a macro can be defined from a command line passed to a compiler.
I don't know well but as far as I know clang based tags generator may parser input for cmake. So the tool may work perfectly. However, for u-ctags, it is not the way to go.

**Comment by masatake** [comment]
@pragmaware, feel free to close this. If you can find the way to improve, it is up to you:-P.
