### ISSUE TITLE
~/.ctags ignored

### ISSUE THREAD

**Issue by Alok** [universal-ctags/ctags#1676]
Is this intentional? I noticed that exuberant and universal ctags have different files they read by default.

**Comment by bfrg** [comment]
I think, this is intentional. This is from the **Differences** section of [README.md](https://github.com/universal-ctags/ctags#difference):
```
The most significant one is that Universal-ctags doesn't load ~/.ctags and ./.ctags at 
starting up time. Instead, it loads ~/.ctags.d/*.ctags and ./.ctags.d/*.ctags. See the above
web site and man pages (man/ctags.1.rst.in and man/ctags-incompatibilities.7.in in the
source tree).
```
