### ISSUE TITLE
How to properly debug ctags?

### ISSUE THREAD

**Issue by azhidkov** [universal-ctags/ctags#1681]
How to properly build ctags for debugging? I use such steps
```
./configure --enable-debuggin
make 
```
but when I load ctags in lldb I got the warning "tags was compiled with optimization - stepping may behave oddly; variables may not be available". And when I try step-in in code variables are not available for me. 

I have two questions. How I can build ctags with debug symbols? And how do you debug ctags?

**Comment by codebrainz** [comment]
> How I can build ctags with debug symbols?

`CFLAGS="-g -O0" ./configure`

**Comment by masatake** [comment]
Making a good bug report is another approach.
See http://docs.ctags.io/en/latest/reporting.html.
