### ISSUE TITLE
list c++ template specialization

### ISSUE THREAD

**Issue by mtozjh** [universal-ctags/ctags#1684]
Based on the document, it is said that the template specialization can be print by 

-fields-c++=+{specialization}

but there is no specialization field in the output file.

**Comment by masatake** [comment]
The document says:
> At the time of writing the following properties are reported:
> ...
> specialization: a function is a template specialization

```
[jet@localhost]~/var/ctags% cat /tmp/foo.cc                                      
template<> void m<int>(int)
{
}
[jet@localhost]~/var/ctags% ./ctags -o - --fields-C++=+'{properties}' /tmp/foo.cc
m	/tmp/foo.cc	/^template<> void m<int>(int)$/;"	f	typeref:typename:void	properties:specialization
```

`specialization` is printed well.

**Comment by pragmaware** [comment]
@mtozjh : See masatake's comment above. If that doesn't solve the issue please reopen the ticket and provide a test case.

**Comment by mtozjh** [comment]
Thanks for the reply, masatake and pragmaware.
it works for me
