### ISSUE TITLE
(null) JSON output for .cs file

### ISSUE THREAD

**Issue by mmm444** [universal-ctags/ctags#1686]
When the following file (named `test.cs`) which is not valid C# and contains non-ASCII characters
```
aá:{0}
```
is stored in UTF-8, parsed and output requested in JSON format one gets `(null)`.

```
# ctags --output-format=json -f- test.cs 
(null)
```
```
# ctags --version
Universal Ctags 0.0.0(f681fe60), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb 13 2018, 13:58:44
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +multibyte, +option-directory, +xpath, +json, +interactive, +sandbox
```

Also with default output format the result has invalid UTF-8 characters in it:
```
# ctags -f- test.cs 
a�      test.cs /^aá:{0}$/;"    p
# ctags -f- test.cs | hexdump -C
00000000  61 c3 09 74 65 73 74 2e  63 73 09 2f 5e 61 c3 a1  |a..test.cs./^a..|
00000010  3a 7b 30 7d 24 2f 3b 22  09 70 0a                 |:{0}$/;".p.|
0000001b
```

Github doesn't allow attaching .cs files so please find the file in [test.zip](https://github.com/universal-ctags/ctags/files/1720263/test.zip).

**Comment by masatake** [comment]
Thank you for reporting. Could you try #1691?


I wonder how to handle the input in tags output format.

**Comment by mmm444** [comment]
Thank you for the quick response! I have tried #1691 and it fixes the problem for me.
