### ISSUE TITLE
Question: I can't get my ctags dotfile to work

### ISSUE THREAD

**Issue by trevordmiller** [universal-ctags/ctags#1696]
Here is my `.ctags.d` placed in my home directory:

```
--exclude=.git
--exclude=.DS_Store

--exclude=node_modules
--exclude=package-lock.json
--exclude=yarn.lock
--exclude=flow-typed
--exclude=.next

--exclude=Gemfile.lock
--exclude=vendor
```

But running `ctags -R` still includes these item from these files and directories. I've also tried renaming my ctags dotfile to the traditional `.ctags` but that doesn't make a difference. What am I doing wrong?

Also, unrelated but is there a way to add comments to `.ctags` files?

**Comment by masatake** [comment]
I guess your ~/.ctags.d is a file.
You should put your configuration to ~/.ctags.d/something.ctags.
In other word, ~/.ctags.d must be a directory.

You can use '#' as line oriented comment starter.

**Comment by masatake** [comment]
If our document misleads you, please tell me how shoud we rewrite the document.

**Comment by trevordmiller** [comment]
@masatake Thank you for your help! I was able to get it working by creating a `~/.ctags.d` directory and placing this `config.ctags` in it:

```
# GENERAL
--exclude=.git
--exclude=.DS_Store

# RUBY
--exclude=vendor
--exclude=Gemfile.lock

# JAVASCRIPT
--exclude=node_modules
--exclude=flow-typed
--exclude=.next
--exclude=package-lock.json
--exclude=yarn.lock
```

I think what would help make the docs more clear would be:
1) An explanation of why the `~/.ctags.d/*` directory is used instead of the conventional single `~/.ctags` dotfile
2) A practical example like what I have here ^

Thank you for your help and the great project!

**Comment by artemave** [comment]
Really tripped me over.

> An explanation of why the ~/.ctags.d/* directory is used instead of the conventional single ~/.ctags dotfile

Yes please.

**Comment by masatake** [comment]
https://github.com/universal-ctags/ctags/blob/master/docs/optlib.rst#preload-option-file

**Comment by artemave** [comment]
Thanks. I can't read. I read that section already. Few times. But it didn't click.

This (from the above) did:

> get it working by creating a `~/.ctags.d` directory and placing this `config.ctags` in it

**Comment by masatake** [comment]
> Thanks. I can't read. I read that section already.

Whta do you mean?  Did you read or not?
If you are talking about the quality of the document, what I can do for you is very limitted.

**Comment by artemave** [comment]
I read it and didn't understand what to do.

**Comment by masatake** [comment]
Oh, I see. I hope FILES section of ctags.1 man page may help you.
