### ISSUE TITLE
Generated Manpage is hard to read due to unlimited textwidth

### ISSUE THREAD

**Issue by kiryph** [universal-ctags/ctags#1705]
Most manpages have a fixed textwidth  which I think is a good thing. Check for yourself bash, git, awk, grep, ...

However, the lines of the generated manpage of uctags by rst2man.py run as long as your screen provides space.

Are you in favor of changing this to a fixed textwidth?

I have not figured out the option of `rst2man.py` to change this myself.

If someone knows that rst2man.py can do this, please let me know. It could be the case that `rst2man.py` has to be extended.

**Comment by kiryph** [comment]
Sorry for the noice. I was totally wrong. Please ignore this issue!

**Comment by masatake** [comment]
Thank you for taking time to our man pages.
Feed backs are really welcome. For me, writing English text without feedbacks makes me sick.
