### ISSUE TITLE
Excluding folders/files defined in --exclude=@.gitignore doesn't seem to work

### ISSUE THREAD

**Issue by samaursa** [universal-ctags/ctags#1721]
I found a related issue https://github.com/universal-ctags/ctags/issues/218, however in the issue I get the impression that `--exclude=@.gitignore`[1] is supposed to work. But I can't get it to work.

I have tried `--exlude={build,install}` and that does exclude the `build` and `install` folders. Any help would be appreicated!

> [1] I also tried `--exclude="@.gitignore` and also `--exclude=@ctagsignore` where `ctagsignore` is a simple file with a couple of folders just to test this feature

**Comment by samaursa** [comment]
I have managed to make it _partially_ work. I say _partially_ because the file specified in `--exclude=@.ignorefile` cannot have folders that end with `/`. So, the following is _not_ okay:

```
build/
install/
```

but this will work

```
build
install
```

Would be nice for the exclude pattern to recognize `mydir/` as directories.

**Comment by masatake** [comment]
See #218.
