### ISSUE TITLE
Python import … as statement within method confuses ctags.

### ISSUE THREAD

**Issue by Viech** [universal-ctags/ctags#1731]
I'm using the latest version 8e09804 of ctags under the `atom` editor with the `symbols-navigator` package. I noticed some weird behaviour when class methods contain an `import modulename as newname` statement. The code
```
class TestClass:
    def method(self):
        pass

    def methodWithImport(self):
        import numpy as np

    def secondMethod(self):
        pass

    def secondMethodWithImport(self):
        import numpy as np
```
gives me the following broken listing:

![A broken listing](http://dl.viech.name/ctagsissue.jpg)

I am not familiar with the ctags format so I can't tell for sure that this is an issue on your end as opposed to a potential problem with the package that creates the listing. Here's the ctags output:
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/8e098045/
TestClass	test.py	/^class TestClass:$/;"	c
method	test.py	/^    def method(self):$/;"	m	class:TestClass
methodWithImport	test.py	/^    def methodWithImport(self):$/;"	m	class:TestClass
np	test.py	/^        import numpy as np$/;"	I	member:TestClass.methodWithImport	file:
np	test.py	/^        import numpy as np$/;"	I	member:TestClass.secondMethodWithImport	file:
secondMethod	test.py	/^    def secondMethod(self):$/;"	m	class:TestClass
secondMethodWithImport	test.py	/^    def secondMethodWithImport(self):$/;"	m	class:TestClass
```

**Comment by Viech** [comment]
Pinging @lejsue, the lead developer of `symbols-navigator`.

**Comment by b4n** [comment]
The UCTags output seems good to me -- look at the 4th field, looking like `class:TestClass` or `member:TestClass.methodWithImport` which represents the scope/"parent tag".
Building a tree from the output following the reported parent for hierarchy should give something like:

* TestClass
  * method
  * methodWithImport
    * np
  * secondMethod
  * secondMethodWithImport
    * np

Which looks good to me.  I guess it's a weird issue with the symbol tree generator you're using, but I really can't see where it gets the duplicate *\*withImport* that it shows as "variables" -- my only guess would be it generates dummies from the scope field when it somehow thinks there's no actual tag there.
