### ISSUE TITLE
Swift not working

### ISSUE THREAD

**Issue by gonsolo** [universal-ctags/ctags#1741]
When I try to use ctags with Swift I am using the advice from https://akrabat.com/ctags-with-swift and add the following to my ~/.ctags file:

--langdef=Swift 
--langmap=Swift:+.swift 
--regex-swift=/(var|let)[ \t]+([^:=]+).*$/\2/,variable/ 
--regex-swift=/func[ \t]+([^\(\)]+)\([^\(\)]*\)/\1/,function/ 
--regex-swift=/class[ \t]+([^:\{]+).*$/\1/,class/ 
--regex-swift=/protocol[ \t]+([^:\{]+).*$/\1/,protocol/

This works flawlessly with exuberant-ctags but not at all with universal ctags.

**Comment by masatake** [comment]
You have to do rename your ~/.ctags to ~/.ctags.d/swift.ctags first of all.  Here after I call your .ctags swift.ctags.

From the view point of u-ctags developer, your swift.ctags is broken.
* Kind letters are not given.
* the parser name should be started from lower case character: swift, not Swift.

Here is the version considering above my comment:
```
--langdef=swift
--langmap=swift:+.swift
--kinddef-swift=v,variable,varaibles
--kinddef-swift=f,function,functions
--kinddef-swift=c,class,classes
--kinddef-swift=p,protocol,protocols
--regex-swift=/(var|let)[ \t]+([^:=]+).$/\2/v/
--regex-swift=/func[ \t]+([^()]+)([^()])/\1/f/
--regex-swift=/class[ \t]+([^:{]+).$/\1/c/
--regex-swift=/protocol[ \t]+([^:{]+).$/\1/p/
```
(Not tested at all.)

**Comment by masatake** [comment]
I wrote how to write a parser for u-ctags in man pages: man/ctags-optlib.7 and man/ctags-incompatibilities.7.
I would like to get comments (and fix) for the pages.

**Comment by gonsolo** [comment]
Hi!

Thanks for the help.


I wrote how to write a parser for u-ctags in man pages: man/ctags-optlib.7
> and man/ctags-incompatibilities.7.
> I would like to get comments (and fix) for the pages.
>
In optlib:
/kindedef/kinddef/
/user/the user/ (sometimes)

I also tried the following version

--langdef=swift
--langmap=swift:+.swift
--kinddef-swift=v,variable,variables
--kinddef-swift=f,function,functions
--kinddef-swift=s,struct,structs
--kinddef-swift=c,class,classes
--kinddef-swift=p,protocol,protocols
--kinddef-swift=e,enum,enums
--regex-swift=/(var|let)[ \t]+([^:=]+).$/\2/v/
--regex-swift=/func[ \t]+([^()]+)([^()])/\1/f/
--regex-swift=/struct[ \t]+([^:{]+).$/\1/c/
--regex-swift=/class[ \t]+([^:{]+).$/\1/c/
--regex-swift=/enum[ \t]+([^:{]+).$/\1/c/
--regex-swift=/protocol[ \t]+([^:{]+).$/\1/p/

which doesn't quite work.
1. I don't know why there is a v, variable and variables but I don't think
that is what makes it fail
2. It recognizes protocols but no classes, structs or enums, and I have no
idea what the regular expressions mean.

The syntax would be:

let myVariable = 1
or
let myVariable: Int

enum MyEnum
or
enum MyEnum: Base

[open, public, private, fileprivate] class MyClass { ... }
[open, public, private, fileprivate] struct MyStruct { ... }
[open, public, private, fileprivate] protocol MyProtocol { ... }

Could you give me a hint how it would look like (without regexes) if ctags
would only look for <class somename> and not try anything else?

Thanks,


-- 
g

**Comment by gonsolo** [comment]
Hi again.

Here is a working version, maybe you want to include it.

Thanks,
Andreas


On Thu, Apr 19, 2018 at 2:07 PM, Gonsolo <gonsolo@gmail.com> wrote:
> Hi!
>
> Thanks for the help.
>
>
>> I wrote how to write a parser for u-ctags in man pages: man/ctags-optlib.7
>> and man/ctags-incompatibilities.7.
>> I would like to get comments (and fix) for the pages.
>
> In optlib:
> /kindedef/kinddef/
> /user/the user/ (sometimes)
>
> I also tried the following version
>
> --langdef=swift
> --langmap=swift:+.swift
> --kinddef-swift=v,variable,variables
> --kinddef-swift=f,function,functions
> --kinddef-swift=s,struct,structs
> --kinddef-swift=c,class,classes
> --kinddef-swift=p,protocol,protocols
> --kinddef-swift=e,enum,enums
> --regex-swift=/(var|let)[ \t]+([^:=]+).$/\2/v/
> --regex-swift=/func[ \t]+([^()]+)([^()])/\1/f/
> --regex-swift=/struct[ \t]+([^:{]+).$/\1/c/
> --regex-swift=/class[ \t]+([^:{]+).$/\1/c/
> --regex-swift=/enum[ \t]+([^:{]+).$/\1/c/
> --regex-swift=/protocol[ \t]+([^:{]+).$/\1/p/
>
> which doesn't quite work.
> 1. I don't know why there is a v, variable and variables but I don't think
> that is what makes it fail
> 2. It recognizes protocols but no classes, structs or enums, and I have no
> idea what the regular expressions mean.
>
> The syntax would be:
>
> let myVariable = 1
> or
> let myVariable: Int
>
> enum MyEnum
> or
> enum MyEnum: Base
>
> [open, public, private, fileprivate] class MyClass { ... }
> [open, public, private, fileprivate] struct MyStruct { ... }
> [open, public, private, fileprivate] protocol MyProtocol { ... }
>
> Could you give me a hint how it would look like (without regexes) if ctags
> would only look for <class somename> and not try anything else?
>
> Thanks,
>
>
> --
> g



-- 
g

**Comment by masatake** [comment]
Please, use github web interface. The layout of your text sent via e-mail is broken. I cannot read it.

> /kindedef/kinddef/

Thank you.

> /user/the user/ (sometimes)
I would like to get the diff (or a pull request for the diff).

I'm really looking for a person who improves the documents. 
You gave me the comment about `kindedef`. So I will take more time for solving your issue.


```
[yamato@master]~/var/ctags-github% cat /tmp/input.swift 
cat /tmp/input.swift 
let myVariable0 = 1
let myVariable1: Int

enum MyEnum0 {
}

enum MyEnum1: Base {
}

open class MyClass0 {
}

public class MyClass1 {
}

private class MyClass2 {
}

fileprivate class MyClass3 {
}

open struct MyStruct0 {
}

public struct MyStruct1 {
}

private struct MyStruct2 {
}

fileprivate struct MyStruct3 {
}

open protocol MyProtocol0 {
}

public protocol MyProtocol1 {
}

private protocol MyProtocol2 {
}

fileprivate protocol MyProtocol3 {
}


[yamato@master]~/var/ctags-github% cat /tmp/swift.ctags 
cat /tmp/swift.ctags 
--langdef=swift
--langmap=swift:+.swift
--kinddef-swift=v,variable,variables
--kinddef-swift=f,function,functions
--kinddef-swift=s,struct,structs
--kinddef-swift=c,class,classes
--kinddef-swift=p,protocol,protocols
--kinddef-swift=e,enum,enums
--regex-swift=/(var|let)[ \t]+([^:=]+).*$/\2/v/
--regex-swift=/func[ \t]+([^()]+)([^()])/\1/f/
--regex-swift=/struct[ \t]+([^:{]+).*$/\1/c/
--regex-swift=/class[ \t]+([^:{]+).*$/\1/c/
--regex-swift=/enum[ \t]+([^:{]+).*$/\1/c/
[yamato@master]~/var/ctags-github% u-ctags --sort=no -o - --options=/tmp/swift.ctags /tmp/input.swift 
u-ctags --sort=no -o - --options=/tmp/swift.ctags /tmp/input.swift 
myVariable0	/tmp/input.swift	/^let myVariable0 = 1$/;"	v
myVariable1	/tmp/input.swift	/^let myVariable1: Int$/;"	v
MyEnum0	/tmp/input.swift	/^enum MyEnum0 {$/;"	c
MyEnum1	/tmp/input.swift	/^enum MyEnum1: Base {$/;"	c
MyClass0	/tmp/input.swift	/^open class MyClass0 {$/;"	c
MyClass1	/tmp/input.swift	/^public class MyClass1 {$/;"	c
MyClass2	/tmp/input.swift	/^private class MyClass2 {$/;"	c
MyClass3	/tmp/input.swift	/^fileprivate class MyClass3 {$/;"	c
MyStruct0	/tmp/input.swift	/^open struct MyStruct0 {$/;"	c
MyStruct1	/tmp/input.swift	/^public struct MyStruct1 {$/;"	c
MyStruct2	/tmp/input.swift	/^private struct MyStruct2 {$/;"	c
MyStruct3	/tmp/input.swift	/^fileprivate struct MyStruct3 {$/;"	c
MyProtocol0	/tmp/input.swift	/^open protocol MyProtocol0 {$/;"	p
MyProtocol1	/tmp/input.swift	/^public protocol MyProtocol1 {$/;"	p
MyProtocol2	/tmp/input.swift	/^private protocol MyProtocol2 {$/;"	p
MyProtocol3	/tmp/input.swift	/^fileprivate protocol MyProtocol3 {$/;"	p
```

I improve the original swift.ctags a bit. It works well for me.
Please, try /tmp/swift.ctags in the above quoted text.
If you cannot get what you want, could you show me the output in your environment.

**Comment by masatake** [comment]
It seems that the last line of swift.ctags is not pasted well.
Here is the updated version:
```
--langdef=swift
--langmap=swift:+.swift
--kinddef-swift=v,variable,variables
--kinddef-swift=f,function,functions
--kinddef-swift=s,struct,structs
--kinddef-swift=c,class,classes
--kinddef-swift=p,protocol,protocols
--kinddef-swift=e,enum,enums
--regex-swift=/(var|let)[ \t]+([^:=]+).*$/\2/v/
--regex-swift=/func[ \t]+([^()]+)([^()])/\1/f/
--regex-swift=/struct[ \t]+([^:{]+).*$/\1/s/
--regex-swift=/class[ \t]+([^:{]+).*$/\1/c/
--regex-swift=/enum[ \t]+([^:{]+).*$/\1/e/
--regex-swift=/protocol[ \t]+([^:{]+).*$/\1/p/
```

**Comment by masatake** [comment]
Feel free to reopen this if you need.

**Comment by qingkong1998** [comment]
hello，how you solve ctags support swift language？

**Comment by gonsolo** [comment]
Hi!

> hello，how you solve ctags support swift language?
>

You have to add a directory named .ctags.d to your home directory (I'm on
Ubuntu) and add a file called swift.ctags.
The content of that file is:
--------------------------------------------------------------------
# Swift definitions for universal ctags

--langdef=swift
--langmap=swift:+.swift

--kinddef-swift=v,variable,variables
--kinddef-swift=f,function,functions
--kinddef-swift=s,struct,structs
--kinddef-swift=c,class,classes
--kinddef-swift=p,protocol,protocols
--kinddef-swift=e,enum,enums
--kinddef-swift=t,typealias,typealiases

--regex-swift=/(var|let)[ \t]+([^:=]+).*$/\2/v/
--regex-swift=/func[ \t]+([^\(\)]+)\([^\(\)]*\)/\1/f/
--regex-swift=/struct[ \t]+([^:\{]+).*$/\1/s/
--regex-swift=/class[ \t]+([^:\{]+).*$/\1/c/
--regex-swift=/protocol[ \t]+([^:\{]+).*$/\1/p/
--regex-swift=/enum[ \t]+([^:\{]+).*$/\1/e/
--regex-swift=/(typealias)[ \t]+([^:=]+).*$/\2/v/
 ------------------------------------------------------------------------------------------------------------------

Then ctags will find those definitions and work with Swift. I have a ctags
-R in my Makefile.

Regards,
Andreas

**Comment by qingkong1998** [comment]
but on Windows7，what should i do ？ at the same time i want  Ctags working with tagbar plugin also
