### ISSUE TITLE
C/C++: Wrongly picks up variables after macro

### ISSUE THREAD

**Issue by ChoppinBlockParty** [universal-ctags/ctags#1748]
Wrongly picks up variables after macro:

    TEST_CASE("", "") {
    	int i;
    }

This will result in tag `i variable`.

**Comment by b4n** [comment]
I don't know if there could be a *reasonable* workaround for this one *that doesn't conflict with any other workarounds*, but basically a macro is always gonna be a problem when its actual expansion isn't known.  Nothing stops the programmer from writing something like
```C
#define X {
int main(void) X return 0; }
```
which is basically impossible to parse if you don't actually know `X` stands for `{`.

I would recommend you to instruct the C parser what `TEST_CASE` actually expands to (or any value that results in valid code) through the `-D` switch.  For example, `-D 'TEST_CASE()=static void test_case(void)'` would get CTags to properly parse your example.

**Comment by masatake** [comment]
In d8261476a, the description for -D option was added to ctags.1.
