### ISSUE TITLE
ignoring "." (directory)

### ISSUE THREAD

**Issue by DanielSiepmann** [universal-ctags/ctags#1754]
Calling ctags on Ubuntu18.04  for a directory will return
```
ignoring "." (directory)
```
instead of generating tags for files inside of the directory.

```
$ ctags --options=NONE -V .
```

On macOS with an older version there was no issue. I would expect ctags to generate a tags file inside the cwd for all files in this folder or subfolders, accordingly to `--recurse=yes` and `--maxdepth=10`

Using `$ ctags --options=NONE -V Documentation/**/*.rst` within zsh works as expected.

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(6418097e), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 16 2018, 21:05:26
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory
```

**Comment by DanielSiepmann** [comment]
Turns out that `--recurse` on cli works as expected, adding the option to `~/.ctags` does not work.

**Comment by masatake** [comment]
Put the option to ~/.ctags.d/DanielSiepmann.ctags instead of putting it to ~/.ctags.

**Comment by DanielSiepmann** [comment]
Thanks just found it out. Looks like that has changed since I've last installed it on macOS.
