### ISSUE TITLE
[Request] Add elixir support 

### ISSUE THREAD

**Issue by dylan-chong** [universal-ctags/ctags#1758]
For example this https://github.com/mmorearty/elixir-ctags

**Comment by masatake** [comment]
See https://github.com/mmorearty/elixir-ctags/issues/5 .

**Comment by dylan-chong** [comment]
I've made a comment on that issue, let's see what he says in response

**Comment by dylan-chong** [comment]
The licence was changed on that repository! So we can incorporate elixir now!

**Comment by masatake** [comment]
See #1806. More test cases are needed for merging the pull request.

**Comment by masatake** [comment]
@dylan-chong, can I close this?

**Comment by dylan-chong** [comment]
yup

**Comment by masatake** [comment]
None has worked on the test case for Elixir parser, so I close this.
