### ISSUE TITLE
reStructuredText: handle targets

### ISSUE THREAD

**Issue by blueyed** [universal-ctags/ctags#1777]
It would be nice to parse targets in rst files, e.g.:

```
.. target-name:
```

Spec: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-targets

I guess this would not be hard to implement, but also not trivial given the current logic therein: https://github.com/universal-ctags/ctags/blob/35c89c8fbb4c7dd6a008acc31207a0a2a61868e8/parsers/rst.c#L223.

I think there should be a new kind ("T", since "t" is taken already), enabled by default?

**Comment by masatake** [comment]
See #1779.
Very important suggestion for languages for documentation.
A good size of request for a change:-)

Thank you.

**Comment by masatake** [comment]
Implemented in #1779.
