### ISSUE TITLE
optlib2c generates invalid C-string when regex has double-quotes in certain cases

### ISSUE THREAD

**Issue by hadrielk** [universal-ctags/ctags#1821]
When a regex has an escaped-backslash followed by double-quotes, the double-quotes are not escaped in the generated C-code from optlib2c.

For example:
```
--regex-Test=/val=\\"(.*)/\1/v,variable
```
should be perfectly legal, and works when used in a `.ctags` options file. The first `\\` escapes it in regex so that a literal `\` has to be found, followed by a `"`. So it would match an input string of:
```
val=\"foo
```
With `optlib2c`, it correctly escapes each of the `\`, to get `\\\\`, but then does not escape the next `"`, making it invalid. In other words, `optlib2c` generates this C-code for the regex string:
```
"val=\\\\"(.*)"
```
which won't compile obviously.

I have created a bogus git branch to show this: https://github.com/hadrielk/ctags/tree/hadriel/bug-optlib2c-quotes-escape
(it's the top commit, obviously)

Unfortunately I'm not sure I understand perl well enough to fix this in `optlib2c`.

A work-around is for the user to escape the `"` in the `.ctags` file, like this:
```
--regex-Test=/val=\\\"(.*)/\1/v,variable
```
but that work-around is confusing, because a `"` is not special in regex, and if they put a `\` before every `"` that will break the C-string too, because this also gets screwed up by `optlib2c`:
```
--regex-Test=/val=\"(.*)/\1/v,variable
```

--------------
```
ctags --version
Universal Ctags 0.0.0(0d560136), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug  9 2018, 16:28:35
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +case-insensitive-filenames
```

**Comment by masatake** [comment]
Fixed in #1822.
