### ISSUE TITLE
Umlaute in tags

### ISSUE THREAD

**Issue by mightymicha** [universal-ctags/ctags#1846]
The name of the parser: Latex

The command line you used to run ctags:

```
$ ctags --options=NONE mwe.tex
```

The content of input file:

```C
\documentclass[11pt]{article}

\begin{document}
\section{ABC}
\section{ZÖZÜZÄZßZ}
\end{document}
```

The tags output you are not satisfied with:

```
ABC	mwe.tex	/^\\section{ABC}$/;"	s
Z   Z   Z   Z   Z	mwe.tex	/^\\section{ZÖZÜZÄZßZ}$/;"	s
...
```

The tags output you expect:

```
ABC	mwe.tex	/^\\section{ABC}$/;"	s
ZÖZÜZÄZßZ	mwe.tex	/^\\section{ZÖZÜZÄZßZ}$/;"	s
...
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(2258b24b), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 19 2018, 13:11:28
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json,
```

How do you get ctags binary:

(
AUR: universal-ctags-git
)

Hello! I wanted to ask whether I miss some option which disables utf8-encoding in the tag names? I already tried the --input-encoding=utf-8 option. Im using vim and tagbar to write latex, this was the first time I had an umlaut in a tag. Thanks for your help!

**Comment by b4n** [comment]
@mightymicha could you test #1848 and see if it works for you as you'd expect?

**Comment by mightymicha** [comment]
It works for me thanks!

**Comment by masatake** [comment]
@b4n, thank you.
