### ISSUE TITLE
--file-tags[=yes] is undocumented?

### ISSUE THREAD

**Issue by fwmechanic** [universal-ctags/ctags#1871]
Perhaps a contributing factor for why #1869 went unnoticed for 6 months is that the --file-tags[=yes] option _seems_ to be undocumented (though I've been using this functionality for many years).  

```
c:\Users\Kevin\klg\BIN\univ-ctags-180907>ctags --version
Universal Ctags 0.0.0(6712037d), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep  7 2018, 00:06:32
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames

c:\Users\Kevin\klg\BIN\univ-ctags-180907>ctags --help | fgrep file-
  --file-scope=[yes|no]

c:\Users\Kevin\klg\BIN\univ-ctags-180907>fgrep -n -- --file- man\ctags.1.html
761:current list. See, also, the <tt class="docutils literal"><span class="pre">--file-scope</span></tt> option. The default list is
858:file (e.g. &quot;ctags -x --c-kinds=v --file-scope=no file&quot;).
981:<dd>Equivalent to <tt class="docutils literal"><span class="pre">--file-scope</span></tt>.</dd>
1109:<dt><tt class="docutils literal"><span class="pre">--file-scope[=yes|no]</span></tt></dt>

c:\Users\Kevin\klg\BIN\univ-ctags-180907>fgrep -n -- --file-tags man\ctags.1.html

c:\Users\Kevin\klg\BIN\univ-ctags-180907>

```

Filing a separate issue in hopes this apparent oversight can be corrected.

**Comment by masatake** [comment]
I have looked into the man page and `--help` output of Exuberant-ctags, the origin of Universal-ctags.
`--file-tags` is not found in them, though the option works well. I just knew.

You can use ``--extras=+f`` instead.
Rather, I would like to remove ``--file-tags`` option from ctags itself and its documents.

**Comment by masatake** [comment]
Providing the multiple ways to set an option can be a trouble. See #1085 to know how I struggled about this topic.

**Comment by fwmechanic** [comment]
Since `--extras=+f` is the documented/supported option equivalent in effect to `--tag-files` (I was unaware of but just verified this), perhaps the man page passage

> Include an entry for the base file name of every source file (e.g. "example.c"), which addresses the first line of the file.

could be changed to

> Include an entry for the base file name of every source file (e.g. "example.c"), which addresses the first line of the file.  This is equivalent in effect to the deprecated `--file-tags=yes` option.

?

This would allow sufficiently curious users who are ignorantly using the deprecated option to self-discover the supported alternative, while hopefully not encouraging users to adopt use of the latter option (as its presence in `--help` output would tend to do).
