### ISSUE TITLE
scheme: add support for Racket

### ISSUE THREAD

**Issue by cwfoo** [universal-ctags/ctags#1877]
Add support for the [Racket](https://en.wikipedia.org/wiki/Racket_%28programming_language%29) language.

The Scheme parser could be reused for Racket. Racket file extensions (e.g. `*.rkt`) could be added to these lines:
https://github.com/universal-ctags/ctags/blob/e522743d873abcfa4997fe6bad5f5cf634f57c6d/parsers/scheme.c#L113-L118

**Comment by masatake** [comment]
Could you open a pull request?

**Comment by masatake** [comment]
I don't know Racket well.

As far as reading its web site quikcly, racket can switch grammer (syntax?) for the input file with `#lang` notation. So choosing the scheme parser for ".rkt" file doesn't make good result.

What we need is a Rapcker parser which recognizes `#lang` notation and run a proper subparser.
http://docs.racket-lang.org/search/index.html?q=H%3A

Which non-S-exp language is popoular as Racker language extentsion?
datalog?

**Comment by masatake** [comment]
I see. Thank you.

**Comment by masatake** [comment]
Solved by #2315. Sorry to be late for solving this issue.
 Scribble language is interesting but it is not the time for working for the language.
