### ISSUE TITLE
run from docker

### ISSUE THREAD

**Issue by ditsara** [universal-ctags/ctags#1891]
I built the binary and packaged it in docker for my own use ([ditsara/universal-ctags-docker](https://github.com/ditsara/universal-ctags-docker)). Is this something the project maintainers would be interested in incorporating into daily builds, similar to the win32 binary?

**Comment by masatake** [comment]
I may be the worst person to answer the question.
I know how to build universal-ctags well. I'm using multiple customized Universal-ctags binaries:-P
Universal-ctags uses Docker only for testing purpose at circle-ci now.
I myself don't need it. So I wonder how potential users say.

How do you think to be a member of universal-ctags organization to run the project here?

**Comment by ditsara** [comment]
Sure, I'd be happy to be a member of universal-ctags and incorporate the project.

**Comment by masatake** [comment]
I sent an invitation to you.
You can make a repository for your work.
I have one very important request. Could you put a license notice to your Dockerfile?
So people can work on your work. Adding LICENSE or COPYING file is also good.

Following items are rather weak requests.
1. Improve README. I would like you to write more use case and command line examples.
2. Link libxml, libyaml, and libjansson. I'm not sure wheter we can use libseccomp inside container.

See https://github.com/universal-ctags/ctags/blob/master/circle.yml . Currently u-ctags tested only on fedora and centos images. I wonder you may want to add alpine.

Happy hacking!

**Comment by ditsara** [comment]
@masatake thanks, I got the invitation. I'll take a look at the CI docs and try to get something started this coming weekend.

**Comment by masatake** [comment]
I invited @ditsara to our organization.
