### ISSUE TITLE
What is `repr' in python.c

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1895]
@b4n, I have a question about python.c that you rewrote as a token-based parser.

I'm very interested in "reprCat". When I worked on extending Go parser, I had to write similar code.
(See 2235f9b5f57ee4335c92c8e41b5624615692c8b8).

I'm thinking about moving "repr" related code to the main part.

The question is what is "repr"?  Do you mean representation?
In my code, I use a word, "collector" for the same purpose.
Do you have a suggestion about naming?

**Comment by b4n** [comment]
> The question is what is "repr"? Do you mean representation?

Yes.  The name follows Python's own `repr()` builtin function.

> I'm very interested in "reprCat". When I worked on extending Go parser, I had to write similar code.

From what I see, what you used in the Go parser is fairly

**Comment by masatake** [comment]
Thank you for answering the question. I will revisit this topic after reworking Go related pull requests.
