### ISSUE TITLE
ctags -R hangs when encountering a TeX file which is missing a line break at EOF

### ISSUE THREAD

**Issue by siegel** [universal-ctags/ctags#1896]
Summary: when using `ctags -R` to recursively process a directory, `ctags` will hang when it encounters a TeX source file in which the last line of a file does not end with a line break.

I have attached the example file.

Steps:

- place the attached TeX file in a directory by itself. (There may be other files there, they will not matter.) [junk.txt](https://github.com/universal-ctags/ctags/files/2439438/junk.txt)

- change its filename extension from `txt` to `tex` so that it is recognized as a TeX file.

- check and make certain that the last line in the file does not end with a line break.

- `cd` to the directory containing the TeX file.

- `ctags -R .`

Expected:

=> ctags runs and generates an output file.

Actual:

=> ctags hangs, I have attached the output of a macOS `sample` command: 
[ctags_2018-10-02_153200_k1Fb.sample.txt](https://github.com/universal-ctags/ctags/files/2439451/ctags_2018-10-02_153200_k1Fb.sample.txt)

Regression:

If `-R` is *not* specified on the command line, ctags does not hang on this file.

`ctags --version` reports:

```
Universal Ctags 0.0.0(d0807887), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct  2 2018, 15:26:35
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames
```

**Comment by b4n** [comment]
I confirm there is an infinite loop with your sample file (well, with any file that has an identifier ending at EOF), although I reproduce it without `-R` just the same -- `ctags -o- junk.tex` hangs.

I'm to blame for this bug I introduced in #1848.  I submitted a fix in #1899.
