### ISSUE TITLE
Possible memory leak with opengrok

### ISSUE THREAD

**Issue by gtoph** [universal-ctags/ctags#1900]
Posted on the opengrok issue page as well as I'm not sure if there is a possible leak on their end or from ctags itself, but the memory usage seems to keep growing when doing the indexing.

I'm using the latest daily build (9/29 I think it is) but don't really have any more info that what you see below, but maybe the command line itself will point to something obvious?

![ctags_mem](https://user-images.githubusercontent.com/22400253/46426913-c426d800-c6f4-11e8-84cb-5bb74595b7e4.jpg)

**Comment by masatake** [comment]
It is up to what kind of input files are given.
At least I would like to know the programming languages used in the input files.

**Comment by masatake** [comment]
Can I get the input files?

**Comment by masatake** [comment]
I have to run ctags under valgrind to find the leaking.

**Comment by gtoph** [comment]
Well there are probably over 10k files, plus I'm sure you understand, but there is no way I can give you source code :)

Not sure valgrind can be used on windows either, otherwise I could try to run it locally.

**Comment by masatake** [comment]
I cloned the source tree of Linux kernel (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/).
And I checked out 67b8d5c7081221efa252e111cd52532ec6d4266f.

Then I run:
```
$ { find ~/var/linux -type f; echo __END_CTAGS__; } | valgrind --leak-check=full  --show-reachable=yes ./ctags   --c-kinds=+l --file-scope=yes -u --filter --fi\
lter-terminator=__END_CTAGS__ --fields=-anf+iKnS > /dev/null
```

What I got is
```
=16040==    definitely lost: 0 bytes in 0 blocks
==16040==    indirectly lost: 0 bytes in 0 blocks
==16040==      possibly lost: 0 bytes in 0 blocks
==16040==    still reachable: 41,895 bytes in 214 blocks
==16040==         suppressed: 0 bytes in 0 blocks
==16040==
==16040== For counts of detected and suppressed errors, rerun with: -v
==16040== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
There is no "definitely lost". The many part of "still reachable" come from XML parser.
I would like you to try to give only XML files to ctags, and tell me what happens.

**Comment by gtoph** [comment]
I can maybe see if cygwin can run valgrind, but I'm not going to hold my breath.
Also, just FYI, I got the full command line from the opengrok log and it's a doozy:

`16:12:07.610    FINE [org.opengrok.indexer.analysis] - Executing ctags command [d:\uctags-x64\ctags.exe --c-kinds=+l --langmap=clojure:+.cljs --langmap=clojure:+.cljx --java-kinds=+l --sql-kinds=+l --Fortran-kinds=+L --C++-kinds=+l --file-scope=yes -u --filter=yes --filter-terminator=__ctags_done_with_file__
 --fields=-anf+iKnS --excmd=pattern --langmap=sh:+.kshlib --langmap=sql:+.plb --langmap=sql:+.pls --langmap=sql:+.pld --langmap=sql:+.pks --langmap=sql:+.pkb --langmap=sql:+.pck --langmap=javascript:+.ts --langdef=scala --langmap=scala:+.scala --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*class[[:space:]]+([a-zA-Z0-9_]+)/\4/c,classes/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*object[[:space:]]+([a-zA-Z0-9_]+)/\4/o,objects/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*case class[[:space:]]+([a-zA-Z0-9_]+)/\4/C,case classes/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*case object[[:space:]]+([a-zA-Z0-9_]+)/\4/O,case objects/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*trait[[:space:]]+([a-zA-Z0-9_]+)/\4/t,traits/ --regex-scala=/^[[:space:]]*type[[:space:]]+([a-zA-Z0-9_]+)/\1/T,types/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*def[[:space:]]+([a-zA-Z0-9_]+)/\3/m,methods/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*val[[:space:]]+([a-zA-Z0-9_]+)/\3/l,constants/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*var[[:space:]]+([a-zA-Z0-9_]+)/\3/v,variables/ --regex-scala=/^[[:space:]]*package[[:space:]]+([a-zA-Z0-9_.]+)/\1/p,packages/ --langdef=haskell --langmap=haskell:+.hs --langmap=haskell:+.hsc --regex-haskell=/^[[:space:]]*class[[:space:]]+([a-zA-Z0-9_]+)/\1/c,classes/ --regex-haskell=/^[[:space:]]*data[[:space:]]+([a-zA-Z0-9_]+)/\1/t,types/ --regex-haskell=/^[[:space:]]*newtype[[:space:]]+([a-zA-Z0-9_]+)/\1/t,types/ --regex-haskell=/^[[:space:]]*type[[:space:]]+([a-zA-Z0-9_]+)/\1/t,types/ --regex-haskell=/^([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\1/f,functions/ --regex-haskell=/[[:space:]]+([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\1/f,functions/ --regex-haskell=/^(let|where)[[:space:]]+([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\2/f,functions/ --regex-haskell=/[[:space:]]+(let|where)[[:space:]]+([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\2/f,functions/ --langdef=clojure --langmap=clojure:+.clj --regex-clojure=/\([[:space:]]*create-ns[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/n,namespace/ --regex-clojure=/\([[:space:]]*def[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/d,definition/ --regex-clojure=/\([[:space:]]*defn-[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/p,private function/ --regex-clojure=/\([[:space:]]*defmacro[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/m,macro/ --regex-clojure=/\([[:space:]]*definline[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/i,inline/ --regex-clojure=/\([[:space:]]*defmulti[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/a,multimethod definition/ --regex-clojure=/\([[:space:]]*defmethod[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/b,multimethod instance/ --regex-clojure=/\([[:space:]]*defonce[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/c,definition (once)/ --regex-clojure=/\([[:space:]]*defstruct[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/s,struct/ --regex-clojure=/\([[:space:]]*intern[[:space:]]+([-[:alnum:]*+!_:\/.?]+)/\1/v,intern/ --langdef=kotlin --langmap=kotlin:+.kt --langmap=kotlin:+.kts --regex-kotlin=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private[^ ]*|protected)?[[:space:]]*class[[:space:]]+([[:alnum:]_:]+)/\4/c,classes/ --regex-kotlin=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private[^ ]*|protected)?[[:space:]]*object[[:space:]]+([[:alnum:]_:]+)/\4/o,objects/ --regex-kotlin=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private[^ ]*|protected)?[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*data class[[:space:]]+([[:alnum:]_:]+)/\6/d,data classes/ --regex-kotlin=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private[^ ]*|protected)?[[:space:]]*interface[[:space:]]+([[:alnum:]_:]+)/\4/i,interfaces/ --regex-kotlin=/^[[:space:]]*type[[:space:]]+([[:alnum:]_:]+)/\1/T,types/ --regex-kotlin=/^[[:space:]]*((abstract|final|sealed|implicit|lazy|private[^ ]*(\[[a-z]*\])*|protected)[[:space:]]*)*fun[[:space:]]+([[:alnum:]_:]+)/\4/m,methods/ --regex-kotlin=/^[[:space:]]*((abstract|final|sealed|implicit|lazy|private[^ ]*|protected)[[:space:]]*)*val[[:space:]]+([[:alnum:]_:]+)/\3/C,constants/ --regex-kotlin=/^[[:space:]]*((abstract|final|sealed|implicit|lazy|private[^ ]*|protected)[[:space:]]*)*var[[:space:]]+([[:alnum:]_:]+)/\3/v,variables/ --regex-kotlin=/^[[:space:]]*package[[:space:]]+([[:alnum:]_.:]+)/\1/p,packages/ --regex-kotlin=/^[[:space:]]*import[[:space:]]+([[:alnum:]_.:]+)/\1/I,imports/ --langdef=swift --langmap=swift:+.swift --regex-swift=/enum[[:space:]]+([^\{\}]+).*$/\1/n,enum,enums/ --regex-swift=/typealias[[:space:]]+([^:=]+).*$/\1/t,typealias,typealiases/ --regex-swift=/protocol[[:space:]]+([^:\{]+).*$/\1/p,protocol,protocols/ --regex-swift=/struct[[:space:]]+([^:\{]+).*$/\1/s,struct,structs/ --regex-swift=/class[[:space:]]+([^:\{]+).*$/\1/c,class,classes/ --regex-swift=/func[[:space:]]+([^\(\)]+)\([^\(\)]*\)/\1/f,function,functions/ --regex-swift=/(var|let)[[:space:]]+([^:=]+).*$/\2/v,variable,variables/ --regex-swift=/^[[:space:]]*extension[[:space:]]+([^:\{]+).*$/\1/e,extension,extensions/ --langdef=rust --langmap=rust:+.rs --regex-rust=/^[[:space:]]*(pub[[:space:]]+)?(static|const)[[:space:]]+(mut[[:space:]]+)?([[:alnum:]_]+)/\4/C,consts,static constants/ --regex-rust=/^[[:space:]]*(pub[[:space:]]+)?(unsafe[[:space:]]+)?impl([[:space:]
]*<[^>]*>)?[[:space:]]+(([[:alnum:]_:]+)[[:space:]]*(<[^>]*>)?[[:space:]]+(for)[[:space:]]+)?([[:alnum:]_]+)/\5 \7 \8/I,impls,trait implementations/ --regex-rust=/^[[:space:]]*(pub[[:space:]]+)?(unsafe[[:space:]]+)?trait[[:space:]]+([[:alnum:]_]+)/\3/r,traits,traits/ --regex-rust=/^[[:space:]]*let[[:space:]]+(mut)?[[:space:]]+([[:alnum:]_]+)/\2/V,variables/ --langdef=pascal --langmap=pascal:+.pas --regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*\([[:space:]]*[[:alnum:]_][[:space:]]*\)/\1/t,Type/ --regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*class[[:space:]]*[^;]*$/\1/c,Class/ --regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*interface[[:space:]]*[^;]*$/\1/i,interface/ --regex-pascal=/^constructor[[:space:]]+(T[a-zA-Z0-9_]+(<[a-zA-Z0-9_, ]+>)?\.)([a-zA-Z0-9_<>, ]+)(.*)+/\1\3/n,Constructor/ --regex-pascal=/^destructor[[:space:]]+(T[a-zA-Z0-9_]+(<[a-zA-Z0-9_, ]+>)?\.)([a-zA-Z0-9_<>, ]+)(.*)+/\1\3/d,Destructor/ --regex-pascal=/^(procedure)[[:space:]]+T[a-zA-Z0-9_<>, ]+\.([a-zA-Z0-9_<>, ]+)(.*)/\2/p,procedure/ --regex-pascal=/^(function)[[:space:]]+T[a-zA-Z0-9_<>, ]+\.([a-zA-Z0-9_<>, ]+)(.*)/\2/f,function/ --regex-pascal=/^[[:space:]]*property[[:space:]]+([a-zA-Z0-9_<>, ]+)[[:space:]]*\:(.*)/\1/o,property/ --regex-pascal=/^(uses|interface|implementation)$/\1/s,Section/ --regex-pascal=/^unit[[:space:]]+([a-zA-Z0-9_<>, ]+)[;(]/\1/u,unit/ --langdef=Posh --langmap=Posh:+.ps1,Posh:+.psm1 --regex-Posh=/\$(\{[^}]+\})/\1/v,variable/ --regex-Posh=/\$([[:alnum:]_]+([:.][[:alnum:]_]+)*)/\1/v,variable/ --regex-Posh=/^[[:space:]]*(:[^[:space:]]+)/\1/l,label/ --_fielddef-Posh=signature,signatures --fields-Posh=+{signature} --regex-Posh=/`\$([[:alnum:]_]+([:.][[:alnum:]_]+)*)/\1//{exclusive} --regex-Posh=/`\$(\{[^}]+\})/\1//{exclusive} --regex-Posh=/#.*\$([[:alnum:]_]+([:.][[:alnum:]_]+)*)/\1//{exclusive} --regex-Posh=/#.*\$(\{[^}]+\})/\1//{exclusive} --regex-Posh=/^[[:space:]]*(function|filter)[[:space:]]+([^({[:space:]]+)[[:space:]]*(\(([^)]+)\))?/\2/f,function,functions/{icase}{exclusive}{_field=signature:(\4)} ]`

**Comment by gtoph** [comment]
Working on getting to actually work correctly when opengrok is running a real indexing, but I did get this on just a --version check:

[version_check.txt](https://github.com/universal-ctags/ctags/files/2451413/version_check.txt)

**Comment by masatake** [comment]
I looked the attached file. It seems that they are all "still-reachable" leaks.
Ideally, "still-reachable" leaks should be zero. However, I think "still-reachable" leaks are acceptable.
In the much of cases, the "still-reachable" leaks don't grow during parsing.

I run `valgrind --leak-check=full --show-leak-kinds=all ./ctags --version` on my pc.
What I got is:

```
==7132== LEAK SUMMARY:
==7132==    definitely lost: 0 bytes in 0 blocks
==7132==    indirectly lost: 0 bytes in 0 blocks
==7132==      possibly lost: 0 bytes in 0 blocks
==7132==    still reachable: 460,202 bytes in 9,854 blocks
==7132==         suppressed: 0 bytes in 0 blocks
```
What I mind are "lost".

**Comment by masatake** [comment]
Reopen this if you find an input file causing "definitely lost", "indirectly lost", or "possibly lost".
