### ISSUE TITLE
C : Can't parse function after macro line

### ISSUE THREAD

**Issue by blackb1rd** [universal-ctags/ctags#191]
Hello,
I found a bug in parsing C using ctags (it's in exuberant-ctags also).

The problem is the following:
```c
#include <stdio.h>

#define PRAGMA(x) _Pragma(#x)
PRAGMA(bar)
int foo() {
	int a = 1;
	printf("a = %d\n", a);
}

void main(void) {
	foo();
}
```

Output of ctags file did not have a function `foo()` as below.
```tags
PRAGMA	f.c	/^#define PRAGMA(/;"	d	file:
PRAGMA	f.c	/^PRAGMA(bar)$/;"	f
main	f.c	/^void main(void) {$/;"	f
```

Thanks!!

**Comment by blueyed** [comment]
@masatake 
Have you made progress on this?
Is your branch available somewhere?

**Comment by masatake** [comment]
No. I do nothing about this topic.

**Comment by ntrel** [comment]
Perhaps you could use `ctags -I 'PRAGMA+'` to skip the macro expansion part.

**Comment by b4n** [comment]
> Private note: We have to record the macro definition in directiveDefine of get.c cork layer

This will not be enough to solve all macro usage, because many can come from included headers, and expand to weird things, so without a full-blown C preprocessor it won't ever be perfect.  So I wonder if it makes sense to add all the complexity required to track macro expansion if it won't ever be enough.

**Comment by masatake** [comment]
@b4n, I agree.

**Comment by masatake** [comment]
I don't know the trick but the new parse solves this.
I got:
```
PRAGMA	/tmp/enum.c	/^#define PRAGMA(/;"	d	file:
foo	/tmp/enum.c	/^int foo() {$/;"	f
main	/tmp/enum.c	/^void main(void) {$/;"	f
```
