### ISSUE TITLE
PuppetManifest: Need to consider top namespace

### ISSUE THREAD

**Issue by ahakanbaba** [universal-ctags/ctags#1916]
In this issue I would like to raise attention about the `top namespace` in puppet. It is the global, top level namespace and its name is the empty string `""`.
 
From the documentation I was able to find one short mention about it [here](https://puppet.com/docs/puppet/5.0/lang_reserved.html#classes-and-defined-resource-types)

> The one exception is the top namespace, whose name is the empty string.

This means the following both includes are equivalent. (The extract is valid puppet code)

 ```
class base {
    file { "/tmp/classheir1": ensure => file, mode => '0755' }
}
include ::base
include base
```
A small digression here: 

> PS: There is disgusting amount of details around the leading `::` usage for includes, stemming from but not limited to the following: 
> - Puppet resolver behavior, that can change with respect to your puppet version ( 3 vs 4 for example).
> - Coding conventions and best practices in puppet. 
> - Opinionated community.
>
> I have seen that the `include ::base` style to be called an anti-pattern and frowned upon. Regardless, I think that is besides the point of ctags related discussion. As long as it is valid puppet code, ctags should do its best to generate tags. 

Right now ctags is only generating this tag for the `class base`.
```
base	dummy.pp	/^class base {$/;"	c	line:2
```
I want to suggest that with  the parameter `--extras=+q` ctags should generate the following too.
```
::base	dummy.pp	/^class base {$/;"	c	line:2
```

That way, the user can jump to the definition of `class base` whether it has been included with `include base` or with `include ::base`.

PS: I am by no means a puppet expert. Feel free to correct me if you find problems with the explanation. 

I understand that the `--extras=+q` does not work with mtable parser right now. I think #1724 and #1260 may have relevant information. I wanted to create this issue in any case to raise attention about the top namespace and valid usages of the leading `::` characters. 

------------------------------------

The name of the parser: puppetManifest

The command line you used to run ctags: 

```
ctags --options=NONE  --fields=+n  -o - dummy.pp
```

The content of input file:

```
class base {
    file { "/tmp/classheir1": ensure => file, mode => '0755' }
}

include ::base
include base
```

The file is valid puppet code:

```
$ /opt/puppetlabs/bin/puppet  apply --noop dummy.pp
Notice: Compiled catalog for mbp-005063.ad.whirl.net in environment production in 0.03 seconds
Notice: /Stage[main]/Base/File[/tmp/classheir1]/ensure: current_value 'absent', should be 'file' (noop)
Notice: Class[Base]: Would have triggered 'refresh' from 1 event
Notice: Stage[main]: Would have triggered 'refresh' from 1 event
Notice: Applied catalog in 0.05 seconds
hbaba@mbp-005063:~/misc$
```

The tags output you are not satisfied with:

```
/tmp/classheir1	dummy.pp	/^    file { "\/tmp\/classheir1": ensure => file, mode => '0755' }$/;"	r	line:3	class:base
base	dummy.pp	/^class base {$/;"	c	line:2
```

The tags output you expect:

```
See above discussion
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(15560853), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 10 2018, 22:29:37
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +yaml, +case-insensitive-filenames

```

How do you get ctags binary:

Build it locally from source manualy.

**Comment by masatake** [comment]
I read the comments of  #1724. I found the reason why I didn't merge the change because the documentation is not completed.

@ahakanbaba, to solve this issue, we have to merge #1724.
So the question is, are you good at English? 
I am always looking for patient volunteer.

**Comment by ahakanbaba** [comment]
Sure, I am more than happy to help. Let's move the discussion to #1724

**Comment by ahakanbaba** [comment]
Thank you @masatake for putting this issue on your short term roadmap. I think I am blocked on this issue before strongly evangelizing universal-ctags/ctags usage with the teams I interact with. Let me know if there is anything I can help with.

**Comment by ahakanbaba** [comment]
@masatake Sorry to bother you about this, but any luck on improving the puppet parser ?

**Comment by masatake** [comment]
This issue is not easy to fix. Various areas must be refined before fixing this. #1934 is one of the such effort.
This is still at the top of my todo list. However, many sub items are in the todo item.

**Comment by masatake** [comment]
I have partially implemented `--_scopesep` option.

Here is an example of the option.
I specify `::' as root separator for class kind.

```
[yamato@slave]~/var/ctags-github% cat /tmp/foo.pp
class one {
    file { "/A": content => "one" }
}

class two {
    file { "/B": content => "two" }
}

include one
[yamato@slave]~/var/ctags-github% u-ctags --extras=+q --_scopesep-PuppetManifest='c.,::' -o - /tmp/foo.pp
/A	/tmp/foo.pp	/^    file { "\/A": content => "one" }$/;"	r	class:one
/B	/tmp/foo.pp	/^    file { "\/B": content => "two" }$/;"	r	class:two
::one	/tmp/foo.pp	/^class one {$/;"	c
::one./A	/tmp/foo.pp	/^    file { "\/A": content => "one" }$/;"	r	class:one
::two	/tmp/foo.pp	/^class two {$/;"	c
::two./B	/tmp/foo.pp	/^    file { "\/B": content => "two" }$/;"	r	class:two
one	/tmp/foo.pp	/^class one {$/;"	c
two	/tmp/foo.pp	/^class two {$/;"	c
```

This is not perfect.
See the scope field for entry `::one./A`. It is `class:one`. It should be `class:::one`.

The other tasks are:
(1) extend optlib2c translator to support `_scopesep`,
(2) update puppetManifest parser,
(3) write this to the web doc.
(4) remember issues about Elm parser (https://github.com/universal-ctags/ctags/pull/1260)
If I can remember correctly, Elm parser also wants `--_scopesep` option.

**Comment by masatake** [comment]
( `.` in the example out is defined as a default seperator in ctags. )

**Comment by ahakanbaba** [comment]
Vauvv ! Thank you very much @masatake. Did this merge to master? If not, in which branch can I try this ? 

Couple of questions: 

1) 
> See the scope field for entry `::one./A`. It is `class:one`. It should be `class:::one`.

Why `class:::one` with three colons, should it not be `class::one` with two colons ? 

2) 
`--_scopesep-PuppetManifest='c.,::'`
Why is the purpose of the leading 'c.' in the value ?

**Comment by masatake** [comment]
Please, see https://github.com/universal-ctags/ctags/pull/1975 .
```
git checkout -b masatake-separator-for-optlib master
git pull https://github.com/masatake/ctags.git separator-for-optlib
```

> Why class:::one with three colons, should it not be class::one with two colons ?
The first `:` comes from the format of tags file.
ctags represents a scope information with format `<kind>`:`<scopename>`.
Here `class` is the kind.
`::one` is the scopename.

> --_scopesep-PuppetManifest='c.,::'

Here `c` means class.

The format for the argument of `--_scopesep-<LANG>` option is `<kind-letter-for-inner-element>.<kind-letter-for-upper-element>:<separator>`. For specifying a root separator (or prefix), set `<kind-letter-for-upper-element>` empty.
