### ISSUE TITLE
why not support swift and oc language？

### ISSUE THREAD

**Issue by qingkong1998** [universal-ctags/ctags#1919]
(
Thank you for contacting us.

If you are reporting an issue with the parsing output, please fill
the following template.  As your custom CTags configuration can
affect results, please always use `--options=NONE` as the first
option when running `ctags`.

Otherwise, delete the template and write your issue from scratch.
Examples may help developers understanding your issue better.

Use GitHub web interface and markdown notation.
Using mail results broken text rendering that makes
the developers go crazy.
)

*****

The name of the parser:

The command line you used to run ctags:

```
$ ctags --options=NONE ...
```

The content of input file:

```C
/* THIS IS AN EXAMPLE */
int
main(void)
{
	...
```

The tags output you are not satisfied with:

```
!_THIS_IS_AN_EXAMPLE
mainVoid	foo.c	/^main(void)$/;"	kind:function	line:2	language:C	typeref:typename:int	signature:(void)	roles:def
...
```

The tags output you expect:

```
!_THIS_IS_AN_EXAMPLE
main	foo.c	/^main(void)$/;"	kind:function	line:2	language:C	typeref:typename:int	signature:(void)	roles:def
...
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(EXAMPLE), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 11 1018, 23:16:36
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +aspell
```

How do you get ctags binary:

(
Building it locally, via GNU/Linux distribution, as BSD's package,
win32 binary taken from Universal-ctags/ctags-win32 project, macosx
binary taken from Universal-ctags/homebrew-universal-ctags project,
etc.
)

**Comment by qingkong1998** [comment]
ctags ,tagbar and etc. ,vim plugins , but  why why not support swift and oc language？
![snipaste_2018-10-14_20-07-50](https://user-images.githubusercontent.com/13163880/46916420-3fd62e00-cfed-11e8-82bc-999d4912d6ee.png)

**Comment by masatake** [comment]
What is oc? Objective-C?

**Comment by qingkong1998** [comment]
yes

**Comment by qingkong1998** [comment]
but swift also not support well

**Comment by masatake** [comment]
ctags doesn't support swift because none wrote a parser for it.
ctags supports ObjectiveC.

**Comment by masatake** [comment]
How not well?

**Comment by qingkong1998** [comment]
the shotscreen above tagbar for vim support objective-C，but not support swift，although，support objective-C also not perfect！

**Comment by masatake** [comment]
How does not the objective-C parser of Universal-ctags perfect?
I don't understand it from the screenshot.
What kind of input the objective-C parser cannot parse well?

**Comment by masatake** [comment]
viewController implementation is parsed well.
Are you talking about viewController interface?
If yes, I would like to know your expectation about the result of parsing for  viewController interface.

**Comment by masatake** [comment]
About swift, someone must write a parser. So we cannot solve it quickly. 
However, about ObjectiveC, we have a parser. It may be possible to fix ObjectiveC parser quickly.
To fix the ObjectiveC parser, I have to know how it is imperfect.
Could you let me know how ObjectiveC parser is not perfect?

**Comment by qingkong1998** [comment]
I hope everything goes well！

**Comment by masatake** [comment]
I see.

**Comment by b4n** [comment]
About Swift, I did start a parser a while back for a Geany feature request, but never got to finish it (to be fair, I never used Swift, so my main motivation was the fun of it).  I can try to dig it out one of these days and see if I could get it to a usable state.

**Comment by qingkong1998** [comment]
thanks for all your effort，good luck
