### ISSUE TITLE
How to use --exclude glob patterns?

### ISSUE THREAD

**Issue by trevordmiller** [universal-ctags/ctags#1928]
# Background

I've been reading through issues like https://github.com/universal-ctags/ctags/issues/759 and it seems that Universal Ctags does support some globbing patterns for `--exclude`.

For example, I've been able to get the following patterns to work:

```shell
--exclude=packages/*/lib/*
```

This ignores files like `packages/some-dir/lib/some-dir/thing.js` as expected 👍

But I can't figure out how to do the equivalent of a `packages/*/*.js` from a `.gitignore`. I've tried:

```shell
--exclude=packages/*/*.js
```

I want it to ignore files like `packages/some-dir/thing.js`, which it does. But it also ignores all recursive matches like `packages/some-dir/src/some-dir/thing.js`, which I don't want.

# Question

**How can I exclude files directly inside a specific directory without excluding sibling sub-directories?**

---

### Notes

It would be awesome if `--exclude` patterns could be documented on http://docs.ctags.io - I couldn't find it, unless I am searching for the wrong things :)

Also, I don't think this is relevant, but I am using the CLI arguments with a `.ctags.d/config.ctags` file like this:

```shell
# GENERAL
--exclude=.git
--exclude=.DS_Store
--exclude=*.jpg
--exclude=*.png
--exclude=*.gif
--exclude=*.svg
--exclude=*.ico
--exclude=*.mp3
--exclude=*.mp4

# JAVASCRIPT
--exclude=node_modules
--exclude=package-lock.json
--exclude=dist
--exclude=docs
--exclude=__snapshots__
--exclude=.next
--exclude=storybook-static
--exclude=packages/*/lib/*
--exclude=packages/*/parts/*
--exclude=packages/*/*.js                                 # the one that's not working
...
```

**Comment by trevordmiller** [comment]
Thanks for looking into this!

**Comment by trevordmiller** [comment]
I've found a possibly related situation. I can't figure out how to do the equivalent of a `packages/*/parts/*` from a `.gitignore`. I've tried:

```shell
--exclude=packages/*/parts/*
```

I want it to ignore files like `packages/some-dir/parts/thing.js`, which it does. But it also ignores all recursive matches like `packages/some-dir/src/some-dir/parts/thing.js`, which I don't want.

It seems to me with this situation and the one in [the original description](https://github.com/universal-ctags/ctags/issues/1928#issue-375609388) that perhaps ctags is treating `*` as "everything under this", when I feel treating it like git does (glob for one level) would be better. Then ctags could add a `**` like git does for "everything under this" instead? What do you think?

**Comment by masatake** [comment]
I should make a pull request for the change and write about the incompatibility in our man page.
I will do them when I can find time.

**Comment by trevordmiller** [comment]
I'm looking forward to it, thanks so much!

**Comment by trevordmiller** [comment]
@masatake Yep!

**Comment by masatake** [comment]
Sorry to be late.

I read the man page, ctags.1.

```
``--exclude=[pattern]``
	Add pattern to a list of excluded files and directories. This option may
	be specified as many times as desired. For each file name considered
	by @CTAGS_NAME_EXECUTABLE@, each pattern specified using this option
	will be compared against both the complete path (e.g.
	some/path/base.ext) and the base name (e.g. base.ext) of the file, thus
	allowing patterns which match a given file name irrespective of its
	path, or match only a specific path.
```
So, matching the pattern
```
--exclude=packages/*/*.js
```
to `packages/some-dir/src/some-dir/thing.js` is not a bug. Some users may expect this behavior.

So the change I proposed in the comment of this issue breaks compatibilities.
I wonder what I should do.

How about introducing a more flexible way to specify exclusion?
```
--exclude-full=method:pattern
```

```
--exclude-full=classic:pattern
```
does the same as `--exclude=`.

```
--exclude-full=path:pattern
```
does what I proposed. This uses FNM_PATHNAME.

```
--exclude-full=regex:REGEX_PATTERN
```
uses regex pattern, not glob pattern.

```
--exclude-full=@:filename
```
does the same as `--exclude=@:filename`.

I myself like this idea. However, people may think this is too complicated.

**Comment by trevordmiller** [comment]
I’m not sure what would be best to do here :/

**Comment by masatake** [comment]
I see.
