### ISSUE TITLE
how to ignore certain lines

### ISSUE THREAD

**Issue by vladak** [universal-ctags/ctags#1935]
In our code base we use a set of macros for C code that suppress some warnings, e.g.
```C
static void
foo(int a)
{
    return a;
}

NOTE(ARGSUSED(1))
static void
bar(int b)
{
    return b;
}
```
however these macros cause the function definition not to be recognized:
```
$ cat tags
!_TAG_FILE_FORMAT    2    /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED    1    /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE    u-ctags    /u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME    Universal Ctags    /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL    https://ctags.io/    /official site/
!_TAG_PROGRAM_VERSION    0.0.0    /befcb888/
foo    ../foo.c    /^foo(int a)$/;"    f    typeref:typename:void    file:
```

In particular, the parentheses prevent the definition from being detected.

Using the latest ctags (as of now) built from source.

This is more of a question rather than bug report - is there perhaps a way how to ignore certain lines from being processed ?

**Comment by vladak** [comment]
This leaves the part of the macro in the `typename` however at least the definition is present. Thanks !

**Comment by pragmaware** [comment]
Define a macro with a parameter.

--

STS

Il mer 21 nov 2018, 11:35 Vladimir Kotal <notifications@github.com> ha
scritto:

**Comment by vladak** [comment]
Cool, `-D'NOTE(arg)'=` works.

st 21. 11. 2018 12:45 odesílatel Szymon Tomasz Stefanek <
notifications@github.com> napsal:

**Comment by masatake** [comment]
Can I close this?

**Comment by vladak** [comment]
Yes.

po 26. 11. 2018 4:45 odesílatel Masatake YAMATO <notifications@github.com>
napsal:
