### ISSUE TITLE
Please support nasm filetype.

### ISSUE THREAD

**Issue by pqnhan** [universal-ctags/ctags#1946]
I use Vim as my main editor. Ctags can't work if I set filetype as nasm.
How can I fix it? I think it's exactly the same, but ctags don't detect nasm extension.

**Comment by pqnhan** [comment]
I'm using .asm as the extension, then set filetype in vim is Nasm.
When I do that, ctags can detect any label and function.
p/s: I use tagbar plugin in vim.

Can I config ctags identify Asm filetype as Nasm?

**Comment by masatake** [comment]
... A bit storange. .asm is already registered as an extension for Asm parser.
ctags doesn't use any knowledge about vim.

```
% u-ctags --list-maps=Asm   
Asm      *.A51 *.29[kK] *.[68][68][kKsSxX] *.[xX][68][68] *.asm *.ASM *.s *.S
```

How about using ctags from command line like:
```
% u-ctags -o - foo.asm
```

ctags may prints tags output for foo.asm to your terminal screen.
If it works fine, your trouble may be about vim. I don't know vim. So I cannot help you in that case.

If the command line doesn't work expectedly, try --options=NONE optoin as the first argument of the command line. If the extra option helps you, you should check your ~/.ctags.d/*.ctags files.

**Comment by pqnhan** [comment]
It work correctly if I don't switch filetype in Vim.
I always set my assembly source file extension is .asm, I think the problem is the vim plugin.
Anyway, thank you for suggestion ;)
