### ISSUE TITLE
JavaScript: Missing methods inside modernish JavaScript class

### ISSUE THREAD

**Issue by maxnordlund** [universal-ctags/ctags#1949]
The name of the parser:
JavaScript (jscript.c)

The command line you used to run ctags:

```
$ ctags --options=NONE --langmap=javascript:+.mjs -f - models/user.mjs
```

<details>
<summary>The content of input file:</summary>

```javascript
import uuid from "uuid"

import * as emails from "../app/emails"
import Controller from "../controllers/controller"
import Group from "./group"
import Model from "./model"
import Order from "./order"

export default class User extends Model {
  static get tableName() {
    return "users"
  }

  static get ["json-schema"]() {
    return {
      type: "object",
      optional: [
        "passwordHash",
        "passwordResetRequestedAt",
        "passwordResetToken",
        "verificationToken",
        "verifiedAt",
      ],
      properties: {
        name: { type: "string" },
        email: { type: "string", format: "email" },
        passwordHash: { type: "string" },
        verificationToken: { type: "string", format: "uuid" },
        verifiedAt: { type: "string", format: "date-time" },
        passwordResetToken: { type: "string", format: "uuid" },
        passwordResetRequestedAt: { type: "string", format: "date-time" },
        address: {
          type: "object",
          properties: {
            streetAddress: { type: "string", description: "The street address. For example, 1600 Amphitheatre Pkwy." },
            postalCode: { type: "string", description: "The postal code. For example, 94043." },
            locality: { type: "string", description: "The locality. For example, Mountain View." },
            region: { type: "string", description: "The region. For example, CA." },
            country: { type: "string", default: "USA", description: "The country. For example, USA. You can also provide the two-letter ISO 3166-1 alpha-2 country code." }
          }
        }
      }
    }
  }

  static get relationMappings() {
    return {
      orders: {
        relation: Model.HasManyRelation,
        modelClass: Order,
        join: {
          from: "users.id",
          to: "orders.user_id"
        }
      },
      groups: {
        relation: Model.ManyToManyRelation,
        modelClass: Group,
        join: {
          from: "users.id",
          through: {
            from: "users_groups.user_id",
            to: "users_groups.group_id"
          },
          to: "groups.id"
        }
      }
    }
  }

  get isAnonymous() { return false }
  get isAuthenticated () { return true }

  async $beforeInsert(queryContext) {
    await super.$beforeInsert(queryContext)
    this.verificationToken = uuid.v4()
  }

  inspect(_depth, _options) {
    return `${this.name} (${this.id}) <${this.email}>`
  }

  async sendVerificationMail() {
    let verificationLink = [
      process.env.HOST,
      Controller.urlFor("account.confirm_page", { token: this.verificationToken })
    ].join("")

    return emails.verification(this.email, { name: this.name, verificationLink })
  }

  async sendResetPasswordMail() {
    let passwordResetLink = [
      process.env.HOST,
      Controller.urlFor("account.password_reset_page", { token: this.passwordResetToken })
    ].join("")

    return emails.passwordReset(this.email, { name: this.name, passwordResetLink })
  }
}

export class AnonymousUser extends User {

  get isAnonymous() { return true }
  get isAuthenticated () { return false }

  sendVerificationMail() {
    throw new TypeError("Can't send a verification email to the anonymous user.")
  }

  sendResetPasswordMail() {
    throw new TypeError("Can't send a password reset email to the anonymous user.")
  }
}

export const ANONYMOUS_USER = new AnonymousUser({ name: "<anonymous>" })
```

</details>

The tags output you are not satisfied with:

```
AnonymousUser	models/user.mjs	/^export class AnonymousUser extends User {$/;"	c
User	models/user.mjs	/^export default class User extends Model {$/;"	c
passwordResetLink	models/user.mjs	/^    let passwordResetLink = [$/;"	v
sendResetPasswordMail	models/user.mjs	/^  sendResetPasswordMail() {$/;"	m	class:AnonymousUser
sendVerificationMail	models/user.mjs	/^  sendVerificationMail() {$/;"	m	class:AnonymousUser
verificationLink	models/user.mjs	/^    let verificationLink = [$/;"	v
```

The tags output you expect:

The above, but also tags for the methods/computed properties.

The version of ctags:

```
$ ctags --version                                                                                                                                                                          11:14:25
Universal Ctags 0.0.0(64f7d61), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 14 2018, 10:37:50
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames
```

How do you get ctags binary:

homebrew:

```
$ brew info universal-ctags/universal-ctags/universal-ctags                                                                                                                                11:58:48
universal-ctags/universal-ctags/universal-ctags: HEAD
Maintained ctags implementation
https://github.com/universal-ctags/ctags
Conflicts with:
  ctags (because this formula installs the same executable as the ctags formula)
/usr/local/Cellar/universal-ctags/HEAD-64f7d61 (325 files, 4.3MB) *
  Built from source on 2018-12-14 at 10:38:07
From: https://github.com/universal-ctags/homebrew-universal-ctags/blob/master/universal-ctags.rb
```

---

This is taken from an actual project am working on, but I figured the user class should be common enough to demonstrate my point. For some other module/classes there're even less tags outputted.

I think it's the use of computed properties (`get`/`set`), `async` and `["funky-method"]`. The latter is more common then one might think, language level protocols are mostly implemented using [well-known symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols).

```js
class InfiniteCounter {
  *[Symbol.iterator]() {
    for (let i = 0;; ++i) yield i
   }
}
```

**Comment by bigfish** [comment]
Just ran into this as well. Not indexing class methods is quite disappointing...

**Comment by bigfish** [comment]
there is code in the parser to parse ES6 methods.. perhaps my version from homebrew is out of date.

ctags --version output..

Universal Ctags 0.0.0(6aa62c9), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun 22 2018, 14:43:13
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames
~

will try building latest

**Comment by bigfish** [comment]
Still not working on latest version(578ea8bc)

**Comment by AkitakiKou** [comment]
This is happening on one of my projects as well. In my class with `get` and `set` functions on top of a class,  the rest methods of the class aren't present in the output at all.

**Comment by masatake** [comment]
Which standard should I read to understand the requirement?
The input file reported in the initial comment is too large to work on this issue incrementally.

The JavaScript parser doesn't capture `latest` in the following input:
```
var obj = {
  log: ['example','test'],
  get latest() {
    if (this.log.length == 0) return undefined;
    return this.log[this.log.length - 1];
  }
}
console.log(obj.latest); // "test".
```

I think we should introduce `getter` kind, and make the JavaScript parser capture `latest` as a `getter`.
I think we can do the same for `setter`.

**Comment by AkitakiKou** [comment]
I'm no expert in this so not sure what standard you're referring to, but did you mean [this EMCAScript 2015 standard](https://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions)? It's where computed property names, along with `set` and `get` were first introduced.

**Comment by masatake** [comment]
@AkitakiKou, thank you! 
The url you showed helps me.

**Comment by masatake** [comment]
@AkitakiKou, thank you! That is what I would like to know.

**Comment by masatake** [comment]
I added support for getter and setter in #1989.
Could you try the change?

I guess I have not solved whole the issue yet. Could you lead me the next smaller sub issue like @AkitakiKou did. I have no time to learn JavaScript from scratch.

```
export default class User extends Model {
  static get tableName() {
    return "users"
  }

  static get ["json-schema"]() {
    return {
      type: "object",
      optional: [
        "passwordHash",
        "passwordResetRequestedAt",
        "passwordResetToken",
        "verificationToken",
        "verifiedAt",
      ]
    }
  }
}
```

I guess `json-schema` should be tagged as a getter. Am I correct?

**Comment by AkitakiKou** [comment]
Yes, `json-schema` should be tagged as a getter as well, to my understanding. I'm on mobile so can't test out #1989 , will do when I got time.

**Comment by bigfish** [comment]
Hey, great to see some activity on this! getters and setters are great to have --  I will test it out tonight. 
[Dynamic properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names)  seems like they may be troublesome, as they can be the result of any JS code inside the [] .. if there's a literal string it should be OK, but they why are dynamic properties even used? I wouldn't expend any more effort on this.. I was simply hoping to have regular class methods work.. see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) for some docs on ES6 /ES2015 Class syntax, specifically the method syntax.

**Comment by masatake** [comment]
@bigfish, thank you.

I pushed the code for capturing computed properties only if thay are represented in a string literal.
I don't touch 'Symbol.*'.

I would like to get your feedback.

**Comment by masatake** [comment]
I have worked the get/set keywords and the computed property notations. I will merge the result soon after getting an ack from @b4n.

Do my changes solve this issue?

**Comment by bigfish** [comment]
yah, it's working great. Thanks, @masatake!

**Comment by masatake** [comment]
O.k. I would like to close this.  If the changes newly introduced for this issue are not enough, please, open new issues. I expect rather smaller input, URL to standards describing the syntax in the new issues.
