### ISSUE TITLE
ctags does not search %HOMEDRIVE%%HOMEPATH%/.ctags.d for configuration

### ISSUE THREAD

**Issue by WillDHB** [universal-ctags/ctags#1957]
ctags version:
Universal Ctags 0.0.0(64f7d619), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 14 2018, 00:12:26
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames

According to the docs, ctags searches for configuration at:

    :file:`$HOME/.ctags.d`
    :file:`$HOMEDRIVE$HOMEPATH/.ctags.d` (in Windows)
    :file:`.ctags.d`
    :file:`ctags.d`

I'm running ctags on Windows, and it is failing to find my configuration files at $HOMEDRIVE$HOMEPATH/.ctags.d.  If I manually set HOME=%HOMEDRIVE%%HOMEPATH%, then ctags can find them and process them as I expect.

**Comment by WillDHB** [comment]
Yes, ctags.d works fine.  I hadn't checked that one.  Is .ctags.d supposed to work as well?

**Comment by masatake** [comment]
How do you know that ctags reads configuration files from `$HOMEDRIVE$HOMEPATH/.ctags.d`?
I guess you may read a document. I would like to know it. It is documentation bug.
By default, ctags doesn't read configuration files from `$HOMEDRIVE$HOMEPATH/.ctags.d`.
See ctags.1 man page.

**Comment by masatake** [comment]
```
According to the docs, ctags searches for configuration at:
```
Which docs?

**Comment by WillDHB** [comment]
Sorry, I meant to add the link, but must've forgotten. https://github.com/universal-ctags/ctags/blob/master/docs/optlib.rst

**Comment by masatake** [comment]
Thank you. I made a pull request. I will close this issue via the fix.
