### ISSUE TITLE
Using ‘ctags.exe -L C:\test\filesTxt --output-format=json --fields=+ne’

### ISSUE THREAD

**Issue by Lennon925** [universal-ctags/ctags#1963]
When I use command 'ctags.exe -L C:\test\filesTxt --output-format=json --fields=+ne' to get results, if filesTxt is a utf-8 file and there are some chinese path in it, the error will show: cannot open input file xxxx: no such file or directory.

**Comment by masatake** [comment]
How about removing `--output-format=json` and `--fields=+ne` options?

**Comment by Lennon925** [comment]
> How about removing `--output-format=json` and `--fields=+ne` options?

after I removed both of them, the result is the same with above

**Comment by masatake** [comment]
Thank you.  O.k. let's foret --output-format=json and --fields=+ne options. They are nothing to do with this issue.

You wrote:
> the error will show: cannot open input file xxxx: no such file or directory.

Here xxxx is the file name you wrote in filesTxt?
If your answer is yes, this is known issue.
See https://github.com/universal-ctags/ctags/issues/1837

**Comment by masatake** [comment]
This is a duplication of #1837.
