### ISSUE TITLE
C++: Incorrectly parsed function parameter's default value

### ISSUE THREAD

**Issue by vahancho** [universal-ctags/ctags#1967]
The C++ class member function has the following signature:

` void SetValues(const Foo& lst, const QChar sep = ',');`

The _--_xformat={signature}_ option used to to extract functions signatures, i.e.:

`ctags -R -x --_xformat={signature} --sort=no --extra=*-q --c++-kinds=*-zlm --fields=*-lne --language-force=C++ `

As a result, the signature appears as:

`(const Foo & lst,const QChar sep='')`

Note the missing comma: `''` vs `','` for the default value of `sep` parameter.

Universal Ctags version:

```
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 13 2016, 23:07:25
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +multibyte
```
However the same issue occurs with the latest release too.

**Comment by masatake** [comment]
Reproduced:

```
[yamato@slave]~/var/ctags-github% cat /tmp/foo.cpp 
void f(char s = ',')
{
}
[yamato@slave]~/var/ctags-github% ./ctags --options=NONE --fields=+S -o - /tmp/foo.cpp
ctags: Notice: No options will be read from files or environment
f	/tmp/foo.cpp	/^void f(char s = ',')$/;"	f	typeref:typename:void	signature:(char s='')
```

**Comment by masatake** [comment]
@pragmaware, cppGetcFull I proposed in  https://github.com/universal-ctags/ctags/pull/1302/commits/700b929002ccc88772f69e351c94e3caf05b7e67 may be useful to fix this issue.

**Comment by masatake** [comment]
A string literal becomes empty, too.

```
void f(char c = 'a')
{
}
void g(const char *s = "abc")
{
}
```

**Comment by masatake** [comment]
#1968 may fix this issue.
I will merge it soon.
