### ISSUE TITLE
signature went wrong after PR #1968

### ISSUE THREAD

**Issue by elecalion** [universal-ctags/ctags#2014]
It seems signature went wrong after PR #1968 if --fields=+S is set.

The command line you used to run ctags:

```
--output-format=e-ctags
--kinds-c++=+p
--fields=+iaS
```

The content of input file:

```C
/* Can NOT be parsed */
int32 test(int32 a)
{
    return 0;
}
/* Can be parsed */
int32 test2(void)
{
    return 0;
}
```

The tags output you are not satisfied with:

```
test2	test.c	/^int32 test(void)$/;"	f	typeref:typename:int32	signature:(void)
```

The tags output you expect:

```
test	test.c	/^int32 test(void)$/;"	f	typeref:typename:int32	signature:(int32 ...)
test2	test.c	/^int32 test(void)$/;"	f	typeref:typename:int32	signature:(void)
```

The version of ctags:

```
Universal Ctags 0.0.0(b60a7b92), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  8 2019, 00:09:52
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames
```

How do you get ctags binary:
win32 binary taken from Universal-ctags/ctags-win32 project

**Comment by b4n** [comment]
This only happens when using `e-ctags` output format.

**Comment by b4n** [comment]
First bad commit is ba82e4f4382a9aa0acf2a05e1804101639fa6bb3

**Comment by b4n** [comment]
I'm not quite sure we disallow spaces (as opposed to tabs) when rendering E-CTags?  AFAIK it should work there, shouldn't it?

**Comment by masatake** [comment]
@elecalion, thank you for reporting.

This one may be related to https://github.com/universal-ctags/ctags/issues/1969.
```
diff --git a/main/field.c b/main/field.c
index 7e32154e..a32142bf 100644
--- a/main/field.c
+++ b/main/field.c
@@ -437,7 +437,7 @@ static const char *renderFieldNameNoEscape (const tagEntryInfo *const tag, const
 
 static bool hasWhitespaceInName (const tagEntryInfo *const tag, const char *value CTAGS_ATTR_UNUSED)
 {
-       return strpbrk (tag->name, " \t")? true: false;
+       return strpbrk (tag->name, "\t")? true: false;
 }
 
 static const char *renderFieldInput (const tagEntryInfo *const tag, const char *value CTAGS_ATTR_UNUSED, vString* b)
@@ -466,7 +466,7 @@ static bool hasWhitespaceInInput (const tagEntryInfo *const tag, const char *val
        if (Option.lineDirectives && tag->sourceFileName)
                f = tag->sourceFileName;
 
-       return strpbrk (f, " \t")? true: false;
+       return strpbrk (f, "\t")? true: false;
 }
 
 static const char *renderFieldSignature (const tagEntryInfo *const tag, const char *value CTAGS_ATTR_UNUSED, vString* b)
@@ -482,7 +482,7 @@ static const char *renderFieldSignatureNoEscape (const tagEntryInfo *const tag,
 
 static bool hasWhitespaceInSignature (const tagEntryInfo *const tag, const char *value CTAGS_ATTR_UNUSED)
 {
-       return (tag->extensionFields.signature && strpbrk(tag->extensionFields.signature, " \t"))
+       return (tag->extensionFields.signature && strpbrk(tag->extensionFields.signature, "\t"))
                ? true
                : false;
 }
```

Above change may fix this issue. After revising the above change, I will make a pull request.

**Comment by b4n** [comment]
@masatake yes I would think that would be the right fix here (well, or one way to achieve it), because normally e-ctags should be fine with inline spaces, just not tabs.
BTW, if you're only checking one character now, you could use `strchr()` instead of `strpbrk()`.

**Comment by masatake** [comment]
@b4n, how do you think about characters handled in vStringCatSWithEscaping().
e.g. `\a`.  I think we have to do nothing special for characters other than `\t`.
The reason we have to do special for `\t` is it is the separator character in tags format.
So just strchr() is enough as you suggested.

**Comment by masatake** [comment]
Surprisingly, my code for handling tab char doesn't work is --sort=no is given...
I think I cannot fix it quickly. So I will make a pull request for fixing this issue in the case --sort=no is not given first. Then I will make a second PR for --sort=yes.

**Comment by masatake** [comment]
The related bug I found is also fixed.
