### ISSUE TITLE
missing PRELOAD_OPTLIB variable in Makefile.in or outdated documentation

### ISSUE THREAD

**Issue by dreamtigers** [universal-ctags/ctags#2033]
I did a review of `docs/optlib.rst` and in the last section "Submitting an optlib file to Universal-ctags project", in the subsection "Makefile.in". The documentation talks about adding the optlib file to a PRELOAD_OPTLIB variable in the Makefile.in and even an OPTLIB variable in the same file.

I ran `grep -rn 'PRELOAD_OPTLIB' *` against the source code and the only place where said variable is mentioned is in that subsection of the documentation.

My question is: is it an outdated documentation, a missing feature, or am I mistaken?

If it's the first one, and can be removed without problems, let me know, so I can update my pull request of the documentation update (#2032) to include that removal.

**Comment by masatake** [comment]
Thank you. It is outdated.

The `Makefile.in` section shuld be:

```diff
diff --git a/docs/optlib.rst b/docs/optlib.rst
index 34469366..582a0081 100644
--- a/docs/optlib.rst
+++ b/docs/optlib.rst
@@ -1633,15 +1633,10 @@ test case own *args.ctags*.
 Assume your test name is *swine-simile.d*. Put ``--option=swine`` in
 *Units/swine-simile.d/args.ctags*.
 
-Makefile.in
+Adding your parser to build process
 ......................................................................
-Add your optlib file, *swine.ctags* to ``PRELOAD_OPTLIB`` variable of
-*Makefile.in*.
-
-
-If you don't want your optlib loaded automatically when ``ctags`` starts up,
-put your optlib file into ``OPTLIB`` of *Makefile.in* instead of
-``PRELOAD_OPTLIB``.
+Add your optlib file, *swine.ctags* to ``OPTLIB2C_INPUT`` variable of
+*makefiles/optlib2c_input.mak* in Universal-ctags source tree.
 
 Verification
 ......................................................................
@@ -1658,7 +1653,7 @@ Let's verify all your work here.
 	$ ./configure --prefix=/tmp/tmp
 	$ make
 	$ make install
-	$ /tmp/tmp/ctags -o - --option=swine something_input.swn
+	$ /tmp/tmp/ctags -o - --languages=Swine something_input.swn
 
 
 Pull-request
```
