### ISSUE TITLE
Cannot run ctags.exe in windows

### ISSUE THREAD

**Issue by luksfarris** [universal-ctags/ctags#2048]
Dear maintainers of this project,
I am unable to use universal-ctags in windows (I hate windows, but have no choice at work). Could you please share directions on how I can run it?

**What I've done:**
1. Downloaded the latest release from https://github.com/universal-ctags/ctags-win32/releases
2. Extracted the zip folder
3. On a CMD, and Powershell, I've ran `C:\path\to\universal-ctags\ctags.exe --version`

**What I saw:**
```
ctags.exe: Warning: Ignoring non-option in CTAGS variable
ctags.exe: --version option may not follow a file name
```

**What I expected to see:**
The version of ctags.

**Further info:**
I've checked `ctags-universal\docs\windows.html` but there is no information there on how to run. `ctags-universal\README.md` also does not have this information.
I've tried to add the `ctags.exe` to an environment variable, and call it from there, but the same `...may not follow a file name` result happened.

On a side note, I believe this information could be useful in the README of https://github.com/universal-ctags/ctags-win32 . I'd gladly make this contribution, if it's ok with you, when I learn how to run it.

Thanks for your time and effort

**Comment by masatake** [comment]
I don't know Windows well but is there a concept named environment variable in Windows?
I guess an environment variable named $CTAGS is set in your environment.
So reset or clear the variable. Then run again.

**Comment by luksfarris** [comment]
Thanks @masatake,
I've tried removing, and resetting, but I get the same result.
I will try to build from source and see what happens

**Comment by masatake** [comment]
@k-takata, do you have any idea about this?

**Comment by k-takata** [comment]
Hmm, I have no idea.

> ctags.exe: --version option may not follow a file name

I don't know why this is shown.

**Comment by masatake** [comment]
@luksfarris, could you try --verbose option like:

```
C:\path\to\universal-ctags\ctags.exe --verbose
```

And put the output here. It may be long output.
The output includes the value given to the environment variable like:
```
[yamato@slave]~/var/ctags/typescript% CTAGS=--options=NONE ./ctags --verbose
...

Reading options from $CTAGS
  Option: --options=NONE
ctags: cannot stat "NONE" : No such file or directory
```

**Comment by brunaostii** [comment]
I have the same issue, you can fix this adding the path in the system variable as CTAGS_PATH, and in the variables for your user you can add %CTAGS_PATH%, I hope this helps you.

**Comment by masatake** [comment]
I want to write about this issue and the way to avoid the issue in our man pages when we find the root cause of the issue.

**Comment by k-takata** [comment]
I confirmed that the same message was shown when I set something to $CTAGS, but not sure whether this is the cause.

**Comment by leleliu008** [comment]
run following code in CMD:
```
set CTAGS=xxxx & ctags.exe --version
```
encounter following logs:
```
ctags.exe: Warning: Ignoring non-option in CTAGS variable
ctags.exe: --version option may not follow a file name
```
relavent code: [main/options.c#L3759-L3784](https://github.com/universal-ctags/ctags/blob/master/main/options.c#L3759-L3784)

It seems that when `CTAGS=xxxx` not contains options , ignore the `--version` option, then `NonOptionEncountered = 1`, when no options specified, a file path is needed.

**Comment by masatake** [comment]
@leleliu008, it is expected behavior as written in ctags(1) man page.
```
CTAGS
    If  this environment variable exists, it will be expected to contain a set of default options
    which are read when ctags starts, after the configuration files listed in FILES,  below,  are
    read,  but  before  any  command line options are read. Options appearing on the command line
    will override options specified in this variable. Only options will be read from  this  vari‐
    able.  Note that all white space in this variable is considered a separator, making it impos‐
    sible to pass an option parameter containing an embedded space. If this is a problem,  use  a
    configuration file instead.
```

What I cannot understand are:

The message was shown though CTAGS was cleared. I wonder why.
https://github.com/universal-ctags/ctags/issues/2048#issuecomment-476708049

The message was hidden when CTAGS_PATH is set. I wonder why.
https://github.com/universal-ctags/ctags/issues/2048#issuecomment-783553146

**Comment by k-takata** [comment]
I grepped CTAGS_PATH in the source code, but nothing found.

> The message was shown though CTAGS was cleared. I wonder why.
> The message was hidden when CTAGS_PATH is set. I wonder why.

Me too.

**Comment by leleliu008** [comment]
@masatake @k-takata 
1. do you really understand what @brunaostii said ? I'm sorry I don't really understand what she said. 
2. do you confirmed what she said? how to reproduce?

I run the following commands in `CMD`:
```
choco install -y curl unzip

cd C:\

curl -LO https://github.com/universal-ctags/ctags-win32/releases/download/2021-02-22%2Fp5.9.20210221.0-2-gd36d8436/ctags-2021-02-22_p5.9.20210221.0-2-gd36d8436-x64.zip

unzip ctags-2021-02-22_p5.9.20210221.0-2-gd36d8436-x64.zip -d ctags
```
then set the `CTAGS_PATH` as following:

![image](https://user-images.githubusercontent.com/3040852/108931897-6c051d80-7683-11eb-8bc7-2a156dde4dcd.png)
![image](https://user-images.githubusercontent.com/3040852/108931974-8b03af80-7683-11eb-998f-75f67b536e41.png)

reopen the `CMD`, run the following command:
```
set CTAGS=xxxx & ctags.exe --version
```
encounter following logs:
```
ctags.exe: Warning: Ignoring non-option in CTAGS variable
ctags.exe: --version option may not follow a file name
```

`CTAGS_PATH` not worked.

**Comment by brunaostii** [comment]
Well, I add the %CTAGS_PATH% to the path for my user and it works, I don't really know why, but I really just changed that. I can give a better look if you need.

**Comment by masatake** [comment]
@leleliu008, I didn't understand what she wrote because my knowledge about Windows is limited.
Information is not enough to inspect this issue more.

**Comment by masatake** [comment]
It is hard for me to know what happened in the environment. I cannot find a way to start the inspection.

However, I have to think about the following output:
```
ctags.exe: Warning: Ignoring non-option in CTAGS variable
ctags.exe: --version option may not follow a file name
```

If ctags ignores CTAGS because the variable doesn't hold a "non-option" value,
the --version option should work.

In addition, --verbose option should report the value assigned to the CTAGS variable.

**Comment by masatake** [comment]
@brunaostii, I have a question. Before arranging CTAGS_PATH, did you set CTAGS environment variable or system? variable?
I guess your answer is yes. If yes, I would like to know the value you gave for it.

**Comment by masatake** [comment]
After long thinking about this issue, I find the variable name CTAGS is really bad for passing options to ctags.
Like CC, people may use, intentionally or unintentionally, CTAGS for specifying a ctags executable, especially if the user installs both Exuberant Ctags and Universal Ctags.

My proposal is that rename CTAGS to CTAGS_OPTIONS, and ETAGS to ETAGS_OPTIONS.
This breaks the compatibility. However, I think we should rename them. How do you think?

**Comment by leleliu008** [comment]
@masatake I think we shouldn't use environment variable to pass default options to ctags command. let's think about following situation:

```sh
ETAGS_OPTIONS="-e"
CTAGS_OPTIONS="-e"
ctags --version
```
In this case, how to determine `etags mode`?

1. If want to use environment variable to pass default options to ctags command. we must tell user which option can be put into the environment variable, because not all options can be put into the environment variable.
2. If the environment variable contains non-option, how to handle this situation? just ignore the non-option or ignore all option in environment variable or trigger an abort?

**Comment by masatake** [comment]
@leleliu008, thank you. I agree with you. Removing them is better. I will open an issue based on your comment.
