### ISSUE TITLE
Lookahead operator

### ISSUE THREAD

**Issue by pidgeon777** [universal-ctags/ctags#2049]
I have a problem similar to this one:

https://sourceforge.net/p/ctags/mailman/message/1877046/

Is there a way to enable lookahead operator as `(?!<regex>)` on Exuberant Ctags version 5.8, or eventually on even newer versions?

On that topic, someone suggested using the PCRE library by just changing the ctags' #includes to grab <pcreposix.h>.

It seems easy to say, but I'm not sure about the details and the possible outcome.

**Comment by masatake** [comment]
We didn't have time working on it. 

See https://github.com/universal-ctags/ctags/issues/1861

Any trials are welcome.

**Comment by masatake** [comment]
The biggest issue I concern is Windows. I wonder PCRE is available on Windows.

**Comment by k-takata** [comment]
I haven't tried to build PCRE with MSVC, but it is available on MSYS2/MinGW as a package. So, it will be easy to build on MinGW.

**Comment by masatake** [comment]
@k-takata, how about PCRE2?

In addition, I would like to hear about Onigmo from you. 
Do you recommend us to use Onigmo (than PCRE2)? 
Basically, I would like to use a popular one. But I really want to make akr special operator available in ctags.

**Comment by k-takata** [comment]
PCRE2 is also available in MSYS2.
Onigmo is unfortunately not available in MSYS2 as a package. So, PCRE2 is easier to use.

**Comment by masatake** [comment]
@k-takata, I see. but...

Using git-subtree to embed Onigmo source tree into ctags source tree is another approach, isn't it?
I guess Ruby developers use similar technique.

**Comment by k-takata** [comment]
Ah, that is an option, but I don't have strong opinion which to use.
FYI, Ruby embeds Onigmo source manually.

**Comment by masatake** [comment]
> but I don't have strong opinion which to use.

This is what I would like to know. Thank you.

**Comment by masatake** [comment]
This is duplication of #1861

**Comment by masatake** [comment]
See #3036.
