### ISSUE TITLE
SourceCookifier and latest Universal Ctags version

### ISSUE THREAD

**Issue by pidgeon777** [universal-ctags/ctags#2050]
SourceCookifier, a cool plugin for Notepad++, is based on Universal Ctags v5.8:

http://sourcecookifier.sourceforge.net/

I think it would be great to adapt this plugin so that it could make use of the latest Universal Ctags version. The original author even provided its source code back in 2012:

https://sourceforge.net/p/sourcecookifier/git/ci/master/tree/sourcecookifier/

Thousands of users around the globe are actually using this plugin which really improves Notepad++ experience a lot.

Has someone already tried this, or would be willing to give it a try?

**Comment by masatake** [comment]
Sometimes we find unmaintained free software. Some of them are really important to our daily computing.
If it is really important to you, consider being a maintainer or reactivating its development. 
For me, ctags and lsof are important software. GitHub is a really good place to reactivate a project.

I know the basic algorithm for reactivation that I applied to run u-ctags project.

(1) find the most active forked repository for the project in the GitHub. When I got an interest in ctags, I did the so. What I found is a ctags repository run by @fishman. If you find one, contribute to the repository.
(1') if you cannot find one, you must make a repository by yourself. Make one and improve it slowly and carefully.
(2) prepare for automatic testing. Write a test harness, add test cases running on the harness, and configure travis-ci. You don't know internal of sourcecookifier. So you can inject a bug when you introduce changes. The test can reduce such chances injecting a bug. I wrote Units and Tmain test harnesses for u-ctags. http://docs.ctags.io/en/latest/testing.html I think these are the most valuable work I have done for u-ctags.
(3) contact the original author and tell that you are running a forked project. Do this in public space like a public mailing list. I can say nothing how the original author says. About ctags, we cannot get an approval of being u-ctags as an officially derived project. However, I thought it is a small thing. The license of the software may allow exchanging the code between two sides. The important thing is a declaration that let users of SourceCookifier know your effort.

Tell us if you need help from ctags side. Good luck.

**Comment by pidgeon777** [comment]
Ok, thanks for the detailed reply.
