### ISSUE TITLE
ctags fails when parsing C++ template templates

### ISSUE THREAD

**Issue by dmhacker** [universal-ctags/ctags#2060]
Hello! I'm having issues when using ctags with template arguments that use or require templates themselves. It looks like ctags is stops parsing once it reaches one of these arguments. I found a similar closed issue from January 2018 (#1671), and testing ctags using the previous author's examples reveals that ctags handles default initialized templates just fine.

As for an example, consider the following input:

```C++
template <long x, typename enabled=void>
struct tabs { const static long value = x; };

template <class Key, class T>
class success {};

template <class Key=long, class T=std::string, class Hash=long_hash_function>
class success2 {};

template <class Key, class T, class Hash=std::hash<Key>, class KeyEqual=std::equal_to<Key>>
class failure {};

namespace test {
...
}
```

What one would expect is that ctags lists tags for all declarations:
* tabs
* success
* success2
* failure
* test

Instead, ctags stops at success, because it fails at parsing `class Hash=std::hash<Key>`, specifically the `<Key>` part. You would only get tags for:
* tabs
* success
* success2

I am currently on Arch Linux, and I am using the official ctags package from the extra repository. 
`ctags --version` outputs:
```
Universal Ctags 0.0.0(45968eff), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 15 2018, 21:55:11
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml
```

Let me know if you need anything else to aid in debugging or if this was previously resolved.

**Comment by masatake** [comment]
Smaller input:
```
#include <hashtable.h>
template <class T, class Hash=std::hash<T>>
class failure {};

```

**Comment by masatake** [comment]
@pragmaware, I am thinking of following heristic:

Consider we have a per input symbol table which is I am implementing now.
Consider the input file I submitted in the last comment.

1. Introduce template parameter kind.
2. Capture T as the kind.
3. When a token sequence of `>`, `>` is found in cxxParserParseTemplateAngleBracketsInternal, look up 
    g_cxx.pToken->pPrev->pPrev->pszWord in the symbol table. In the example input, `T` is stored to pszWord.
4. If you find an entry for the pszWord in the table, and the kind for it is template parameter, we can say the '>>' is not shift operator.

How do you think this heuristic?

**Comment by masatake** [comment]
@dmhacker, could you try #2066?
