### ISSUE TITLE
Ctags can't distinguish function name if code like this

### ISSUE THREAD

**Issue by Lennon925** [universal-ctags/ctags#2068]
Ctags can't distinguish function definition if code like this:

void Test
（int i, int j, int m, int n, int x, int y, int z）   //brackets and parameters on the next line
{
     int count = 0;
     count ++;
}

**Comment by masatake** [comment]
I guess this is C program.
However, it is not valid C program.
So ctags cannot recognize the input well.
In addition, ctags doesn't handle multi-bytes characters as input.
```
[yamato@slave]/tmp% cat /tmp/bar.c
cat /tmp/bar.c
void Test
（int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
{
int count = 0;
count ++;
}
```
```
[yamato@slave]/tmp% hexdump -C /tmp/bar.c
hexdump -C /tmp/bar.c
00000000  76 6f 69 64 20 54 65 73  74 0a ef bc 88 69 6e 74  |void Test....int|
00000010  20 69 2c 20 69 6e 74 20  6a 2c 20 69 6e 74 20 6d  | i, int j, int m|
00000020  2c 20 69 6e 74 20 6e 2c  20 69 6e 74 20 78 2c 20  |, int n, int x, |
00000030  69 6e 74 20 79 2c 20 69  6e 74 20 7a ef bc 89 20  |int y, int z... |
00000040  2f 2f 62 72 61 63 6b 65  74 73 20 61 6e 64 20 70  |//brackets and p|
00000050  61 72 61 6d 65 74 65 72  73 20 6f 6e 20 74 68 65  |arameters on the|
00000060  20 6e 65 78 74 20 6c 69  6e 65 0a 7b 0a 69 6e 74  | next line.{.int|
00000070  20 63 6f 75 6e 74 20 3d  20 30 3b 0a 63 6f 75 6e  | count = 0;.coun|
00000080  74 20 2b 2b 3b 0a 7d 0a                           |t ++;.}.|
00000088
```
Look at hexdump. The parentheses are not represented in ascii range.
Actually gcc doesn't accept the input.
```
[yamato@slave]/tmp% gcc -c /tmp/bar.c
gcc -c /tmp/bar.c
/tmp/bar.c:2:1: error: stray ‘\357’ in program
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
 ^
/tmp/bar.c:2:2: error: stray ‘\274’ in program
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
  ^
/tmp/bar.c:2:3: error: stray ‘\210’ in program
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
   ^
/tmp/bar.c:1:10: error: expected ‘;’ before ‘int’
 void Test
          ^
          ;
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
    ~~~    
/tmp/bar.c:2:11: error: expected identifier or ‘(’ before ‘int’
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
           ^~~
/tmp/bar.c:2:51: error: stray ‘\357’ in program
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
                                                   ^
/tmp/bar.c:2:52: error: stray ‘\274’ in program
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
                                                    ^
/tmp/bar.c:2:53: error: stray ‘\211’ in program
 （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
                                                     ^
```
Can I close this?

**Comment by Lennon925** [comment]
> I guess this is C program.
> However, it is not valid C program.
> So ctags cannot recognize the input well.
> In addition, ctags doesn't handle multi-bytes characters as input.
> 
> ```
> [yamato@slave]/tmp% cat /tmp/bar.c
> cat /tmp/bar.c
> void Test
> （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
> {
> int count = 0;
> count ++;
> }
> ```
> ```
> [yamato@slave]/tmp% hexdump -C /tmp/bar.c
> hexdump -C /tmp/bar.c
> 00000000  76 6f 69 64 20 54 65 73  74 0a ef bc 88 69 6e 74  |void Test....int|
> 00000010  20 69 2c 20 69 6e 74 20  6a 2c 20 69 6e 74 20 6d  | i, int j, int m|
> 00000020  2c 20 69 6e 74 20 6e 2c  20 69 6e 74 20 78 2c 20  |, int n, int x, |
> 00000030  69 6e 74 20 79 2c 20 69  6e 74 20 7a ef bc 89 20  |int y, int z... |
> 00000040  2f 2f 62 72 61 63 6b 65  74 73 20 61 6e 64 20 70  |//brackets and p|
> 00000050  61 72 61 6d 65 74 65 72  73 20 6f 6e 20 74 68 65  |arameters on the|
> 00000060  20 6e 65 78 74 20 6c 69  6e 65 0a 7b 0a 69 6e 74  | next line.{.int|
> 00000070  20 63 6f 75 6e 74 20 3d  20 30 3b 0a 63 6f 75 6e  | count = 0;.coun|
> 00000080  74 20 2b 2b 3b 0a 7d 0a                           |t ++;.}.|
> 00000088
> ```
> Look at hexdump. The parentheses are not represented in ascii range.
> Actually gcc doesn't accept the input.
> 
> ```
> [yamato@slave]/tmp% gcc -c /tmp/bar.c
> gcc -c /tmp/bar.c
> /tmp/bar.c:2:1: error: stray ‘\357’ in program
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>  ^
> /tmp/bar.c:2:2: error: stray ‘\274’ in program
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>   ^
> /tmp/bar.c:2:3: error: stray ‘\210’ in program
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>    ^
> /tmp/bar.c:1:10: error: expected ‘;’ before ‘int’
>  void Test
>           ^
>           ;
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>     ~~~    
> /tmp/bar.c:2:11: error: expected identifier or ‘(’ before ‘int’
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>            ^~~
> /tmp/bar.c:2:51: error: stray ‘\357’ in program
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>                                                    ^
> /tmp/bar.c:2:52: error: stray ‘\274’ in program
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>                                                     ^
> /tmp/bar.c:2:53: error: stray ‘\211’ in program
>  （int i, int j, int m, int n, int x, int y, int z） //brackets and parameters on the next line
>                                                      ^
> ```
> Can I close this?

Sorry, I made a mistake to type brackets with multi-bytes characters. In fact, I didn't mean that.
Following code is valid in Visual Studio and VSCode IDE but Ctags can't recognize function name.

void Test
(int i, int j, int m, int n, int x, int y, int z) //brackets and parameters on the next line
{
int count = 0;
count ++;
}

**Comment by masatake** [comment]
Not reproduced.
```
[jet@living]~/var/ctags% ./ctags --version
Universal Ctags 0.0.0(6875453f), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 31 2019, 03:22:16
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +debug, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +aspell, +packcc
[jet@living]~/var/ctags% ./ctags -o - /tmp/foo.c 
Test	/tmp/foo.c	/^void Test$/;"	f	typeref:typename:void
[jet@living]~/var/ctags% cat /tmp/foo.c
void Test
(int i, int j, int m, int n, int x, int y, int z) //brackets and parameters on the next line
{
int count = 0;
count ++;
}
```
Please, do the same as above.
 I would like to see the output.

**Comment by Lennon925** [comment]
> Not reproduced.
> 
> ```
> [jet@living]~/var/ctags% ./ctags --version
> Universal Ctags 0.0.0(6875453f), Copyright (C) 2015 Universal Ctags Team
> Universal Ctags is derived from Exuberant Ctags.
> Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
>   Compiled: Mar 31 2019, 03:22:16
>   URL: https://ctags.io/
>   Optional compiled features: +wildcards, +regex, +iconv, +debug, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +aspell, +packcc
> [jet@living]~/var/ctags% ./ctags -o - /tmp/foo.c 
> Test	/tmp/foo.c	/^void Test$/;"	f	typeref:typename:void
> [jet@living]~/var/ctags% cat /tmp/foo.c
> void Test
> (int i, int j, int m, int n, int x, int y, int z) //brackets and parameters on the next line
> {
> int count = 0;
> count ++;
> }
> ```
> Please, do the same as above.
> I would like to see the output.


Yes, you are right and you can close this issue. Thanks for your reply.
