### ISSUE TITLE
Use webhook to update documents at ctags.io

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2093]
I found that ctags.io had not been updated for 4 months because 'GitHub service' feature is gone.
We have to use webhook feature instead.

@cweagans, could you look at this? 
https://docs.readthedocs.io/en/latest/webhooks.html#webhook-creation

I tried updating but I could not because I am not the maintainer.
If possible, I would like you to add me as a member of the maintainer group.

**Comment by cweagans** [comment]
@masatake What is your Read The Docs username? I can add you.

**Comment by cweagans** [comment]
I don't have admin access to the Github repo so I can't set up the webhook, but I'm happy to hand out access to the RTD account so that you can do it!

**Comment by masatake** [comment]
> I  don't have admin access to the Github repo so I can't set up the  webhook, but I'm happy to hand out access to the RTD account so that you  can do it!

I login RTD via github. So I guess my account name is "masatake".

**Comment by cweagans** [comment]
I have added you.

**Comment by masatake** [comment]
Fixed! Thank you.
