### ISSUE TITLE
Markdown Support Clarification

### ISSUE THREAD

**Issue by kinowarrior** [universal-ctags/ctags#2098]
Running `ctags` never populates my tags file with markdown tags.

I see support added [with these commits](https://github.com/universal-ctags/ctags/search?q=markdown&type=Commits).

The docs also talk about [new parsers (with markdown parser support) here](http://docs.ctags.io/en/latest/news.html?highlight=markdown#new-parsers).

Finally, i see markdown listed when running:

 `ctags --list-languages  `

My `~/.ctags` file includes the following:

```
--langdef=markdown
--langmap=markdown:.md
--regex-markdown=/^#[ \t](.*$)/\1/h,heading,headings/
```

Please, can anyone explain what else is required?  Neovim fails to find any matching tags. It works for many other languages. I have tried explicitly running `ctags -R .` off the command line etc too.

**Comment by masatake** [comment]
The first of all, universal-ctags doesn't read ~/.ctags.  See https://github.com/universal-ctags/ctags 

As far as I tried the built-in markdown parser works well:
```
[jet@living]~/var/ctags% cat /tmp/foo.md
cat /tmp/foo.md
# a
## b
# c
## d
## e
#f
[jet@living]~/var/ctags% ./ctags -o - /tmp/foo.md 
./ctags -o - /tmp/foo.md 
a	/tmp/foo.md	/^# a$/;"	c
b	/tmp/foo.md	/^## b$/;"	s
c	/tmp/foo.md	/^# c$/;"	c
d	/tmp/foo.md	/^## d$/;"	s
e	/tmp/foo.md	/^## e$/;"	s
```

Nothing is needed.
