### ISSUE TITLE
Does universal-ctags support .inc file and .pc file?

### ISSUE THREAD

**Issue by Lennon925** [universal-ctags/ctags#2104]
Does universal-ctags support .inc file and .pc file?  I used command "universal-ctags.exe --output-format=json --fields=+ne -o - D:\test\smp_comm.cpp >text1.txt" to parse .inc file and found
result was empty.

**Comment by masatake** [comment]
What is inc? What I image is php. ctags has PHP parser though it doesn't recognize .inc as a file extension for php.  

What is .pc? What I image is pkg-config. ctags doesn't has a parser for pkg-config.

**Comment by masatake** [comment]
Feel free reopen this if you need.

**Comment by b4n** [comment]
> What is .inc? What I image is php. ctags has PHP parser though it doesn't recognize .inc as a file extension for php.

`.inc` is a fairly common extension for "include file", whatever the language.  It's indeed used for PHP, but sometimes for C++ or others, when it's a file that has specific semantics.

@Lennon925 However, it seems like you expect CTags to parse files `#include`ed in your `.cpp`.  But CTags does not, it might record that you included files, but it won't parse those files, for many reasons.

> What is .pc? What I image is pkg-config. ctags doesn't has a parser for pkg-config.

Here I'm as clueless as you are, for me `.pc` is pkg-config, but I'm not sure it matches anything related to the OP.
