### ISSUE TITLE
JSON DOS

### ISSUE THREAD

**Issue by hanwen** [universal-ctags/ctags#2107]
(

The name of the parser:

json

The command line you used to run ctags:

```
./ctags  /tmp/borer/core/.jvm/src/test/resources/n_structure_100000_opening_arrays.json
```

The content of input file: https://github.com/sirthias/borer/blob/master/core/.jvm/src/test/resources/n_structure_100000_opening_arrays.json

(this is a sequence of 100k '[' chars)

The tags output you are not satisfied with:

heap increases to many Gb until it crashes with segfault.

It would be nice if this could either exit with an error, or use less memory and succeed. 

```
!_THIS_IS_AN_EXAMPLE
mainVoid	foo.c	/^main(void)$/;"	kind:function	line:2	language:C	typeref:typename:int	signature:(void)	roles:def
...
```

The tags output you expect:

```
!_THIS_IS_AN_EXAMPLE
main	foo.c	/^main(void)$/;"	kind:function	line:2	language:C	typeref:typename:int	signature:(void)	roles:def
...
```

The version of ctags:

```
$ ctags --version

Universal Ctags 0.0.0(3fdf28bc), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 29 2019, 15:19:17
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +json, +interactive, +sandbox, +packcc
hanwen@hanwen:~/vc/ctags$ 
```
How do you get ctags binary:

local build, linux.

**Comment by masatake** [comment]
A related issue: https://github.com/universal-ctags/ctags/issues/1682
