### ISSUE TITLE
ctags missed generating some symbols for nginx

### ISSUE THREAD

**Issue by ling-zhou** [universal-ctags/ctags#2108]
The command line I used to run ctags:

```
$ ctags -I __THROW -I __nonnull --c-kinds=+xd --extras=+fgq --fields=+CEKRSZaeilmnprx ngx_hash.c
or 
$ ctags --options=NONE -I __THROW -I __nonnull --c-kinds=+xd --extras=+fgq --fields=+CEKRSZaeilmnprx ngx_hash.c
```

The content of input file:

```C
https://github.com/nginx/nginx/blob/master/src/core/ngx_hash.c
```

The tags output I  am not satisfied with:

```
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL       https://ctags.io/       /official site/
!_TAG_PROGRAM_VERSION   0.0.0   //
NGX_HASH_ELT_SIZE       ngx_hash.c      /^#define NGX_HASH_ELT_SIZE(/;" macro   line:248        language:C      file:   signature:(name)      roles:def        extras:fileScope        end:249
ngx_hash.c      ngx_hash.c      1;"     file    line:1  language:C      roles:def       extras:inputFile        end:1011
ngx_hash_find   ngx_hash.c      /^ngx_hash_find(ngx_hash_t *hash, ngx_uint_t key, u_char *name, size_t len)$/;" function        line:13 language:C     typeref:typename:void * signature:(ngx_hash_t * hash,ngx_uint_t key,u_char * name,size_t len)   roles:def       end:49
ngx_hash_find_combined  ngx_hash.c      /^ngx_hash_find_combined(ngx_hash_combined_t *hash, ngx_uint_t key, u_char *name,$/;"   function      line:211 language:C      typeref:typename:void * signature:(ngx_hash_combined_t * hash,ngx_uint_t key,u_char * name,size_t len)  roles:def     end:245
ngx_hash_find_wc_head   ngx_hash.c      /^ngx_hash_find_wc_head(ngx_hash_wildcard_t *hwc, u_char *name, size_t len)$/;" function        line:5language:C       typeref:typename:void * signature:(ngx_hash_wildcard_t * hwc,u_char * name,size_t len)  roles:def       end:143
ngx_hash_find_wc_tail   ngx_hash.c      /^ngx_hash_find_wc_tail(ngx_hash_wildcard_t *hwc, u_char *name, size_t len)$/;" function        line:147       language:C      typeref:typename:void * signature:(ngx_hash_wildcard_t * hwc,u_char * name,size_t len)  roles:def       end:207
ngx_hash_init   ngx_hash.c      /^ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)$/;"    function        line:252       language:C      typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def
```

The tags output I expect:

```
**many symbols are missing, such as:**

ngx_hash_wildcard_init
ngx_hash_key
ngx_hash_key_lc
ngx_hash_strlow
ngx_hash_keys_array_init
ngx_hash_add_key
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 31 2019, 20:07:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc
```

This is how I get ctags:
1. download zip from https://github.com/universal-ctags/ctags (**source date: 20190531**)
2. ./autogen.sh 
3. ./configure
4. make && make install(via GNU/Linux distribution)

**Something More(not Bug, but an expected good Feature):**
for C/C++ files, normally we have declaration symbol, e.g.: int abc(int i); in header file, and implementation symbol, eg.: int abc(int i) { return 123; } in cpp file. is it possilbe to always place the implementation symbol preferentially? so we can jump to the implementation symbol directly
by pressing ' ctrl-] ', maybe ctags could add an option '--impl-symbol-first' or something else like that for this feature?

**Comment by masatake** [comment]
> Something More(not Bug, but an expected good Feature):

ctags command is a tool for GENERATING tags file. "Jumping to the definition" is a job of client tools.
And I don't know client tools well. I'm using emacs.

readtags, a client tool included in the ctags source tree is special.  I'm working on adding an option for sorting the result.

```
[jet@living]~/var/ctags% cat /tmp/foo.c                                     
int foo (void);

int foo (void) {}

[jet@living]~/var/ctags% ./ctags --fields=+n --kinds-C=+p -o tags /tmp/foo.c
[jet@living]~/var/ctags% cat tags
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/6ca4b89f/
foo	/tmp/foo.c	/^int foo (void) {}$/;"	f	line:3	typeref:typename:int
foo	/tmp/foo.c	/^int foo (void);$/;"	p	line:1	typeref:typename:int	file:
[jet@living]~/var/ctags% ./readtags -en -S '(if (eq? $kind "p") 1 -1)' foo
foo	/tmp/foo.c	/^int foo (void);$/;"	kind:p	file:	line:1	typeref:typename:int
foo	/tmp/foo.c	/^int foo (void) {}$/;"	kind:f	line:3	typeref:typename:int
[jet@living]~/var/ctags% ./readtags -en -S '(if (eq? $kind "p") -1 1)' foo
foo	/tmp/foo.c	/^int foo (void) {}$/;"	kind:f	line:3	typeref:typename:int
foo	/tmp/foo.c	/^int foo (void);$/;"	kind:p	file:	line:1	typeref:typename:int
```
You can give a sorting rule with -S option.
However, as far as I know, there is no tool using readtags internally.

**Comment by masatake** [comment]
> maybe ctags could add an option '--impl-symbol-first' or something else like that for this feature?

Requirements for order of sorting may be changed by use context.
So I think sorting should be done after generating tags though ctags hsa --sort option.

**Comment by masatake** [comment]
I could not reproduced. All the symbols you reported are listed in the output.

```
[jet@living]/tmp% wget https://raw.githubusercontent.com/nginx/nginx/master/src/core/ngx_hash.c                                                                     
--2019-06-02 11:15:08--  https://raw.githubusercontent.com/nginx/nginx/master/src/core/ngx_hash.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22251 (22K) [text/plain]
Saving to: ‘ngx_hash.c’

ngx_hash.c                                                  100%[=========================================================================================================================================>]  21.73K  --.-KB/s    in 0.01s   

2019-06-02 11:15:08 (1.92 MB/s) - ‘ngx_hash.c’ saved [22251/22251]

[jet@living]/tmp% u-ctags --quiet --options=NONE  -o - -I __THROW -I __nonnull --c-kinds=+xd --extras=+fgq --fields=+CEKRSZaeilmnprx ./ngx_hash.c | awk '{print $1}'
NGX_HASH_ELT_SIZE
ngx_hash.c
ngx_hash_add_key
ngx_hash_find
ngx_hash_find_combined
ngx_hash_find_wc_head
ngx_hash_find_wc_tail
ngx_hash_init
ngx_hash_key
ngx_hash_key_lc
ngx_hash_keys_array_init
ngx_hash_strlow
ngx_hash_wildcard_init
[jet@living]/tmp% ./ctags --version
zsh: no such file or directory: ./ctags
[jet@living]/tmp% u-ctags --version
Universal Ctags 0.0.0(2165a716), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun  2 2019, 10:51:07
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +debug, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +aspell, +packcc
```

**Comment by ling-zhou** [comment]
> I could not reproduced. All the symbols you reported are listed in the output.
> 
> ```
> [jet@living]/tmp% wget https://raw.githubusercontent.com/nginx/nginx/master/src/core/ngx_hash.c                                                                     
> --2019-06-02 11:15:08--  https://raw.githubusercontent.com/nginx/nginx/master/src/core/ngx_hash.c
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 22251 (22K) [text/plain]
> Saving to: ‘ngx_hash.c’
> 
> ngx_hash.c                                                  100%[=========================================================================================================================================>]  21.73K  --.-KB/s    in 0.01s   
> 
> 2019-06-02 11:15:08 (1.92 MB/s) - ‘ngx_hash.c’ saved [22251/22251]
> 
> [jet@living]/tmp% u-ctags --quiet --options=NONE  -o - -I __THROW -I __nonnull --c-kinds=+xd --extras=+fgq --fields=+CEKRSZaeilmnprx ./ngx_hash.c | awk '{print $1}'
> NGX_HASH_ELT_SIZE
> ngx_hash.c
> ngx_hash_add_key
> ngx_hash_find
> ngx_hash_find_combined
> ngx_hash_find_wc_head
> ngx_hash_find_wc_tail
> ngx_hash_init
> ngx_hash_key
> ngx_hash_key_lc
> ngx_hash_keys_array_init
> ngx_hash_strlow
> ngx_hash_wildcard_init
> [jet@living]/tmp% ./ctags --version
> zsh: no such file or directory: ./ctags
> [jet@living]/tmp% u-ctags --version
> Universal Ctags 0.0.0(2165a716), Copyright (C) 2015 Universal Ctags Team
> Universal Ctags is derived from Exuberant Ctags.
> Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
>   Compiled: Jun  2 2019, 10:51:07
>   URL: https://ctags.io/
>   Optional compiled features: +wildcards, +regex, +iconv, +debug, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +aspell, +packcc
> ```

**sorry, it was my mistake!. this is the right code snippet:**
349     for (i = 0; i < size; i++) {
350         if (test[i] == sizeof(void *)) {
351             continue;
352         }
353 
354         test[i] = (u_short) (ngx_align(test[i], ngx_cacheline_size));

**I deleted one '}' in line 352 by accident, this is the wrong code snippet:**
349     for (i = 0; i < size; i++) {
350         if (test[i] == sizeof(void *)) {
351             continue;
352 
353         test[i] = (u_short) (ngx_align(test[i], ngx_cacheline_size));
354

**Comment by ling-zhou** [comment]
> > Something More(not Bug, but an expected good Feature):
> 
> ctags command is a tool for GENERATING tags file. "Jumping to the definition" is a job of client tools.
> And I don't know client tools well. I'm using emacs.
> 
> readtags, a client tool included in the ctags source tree is special. I'm working on adding an option for sorting the result.
> 
> ```
> [jet@living]~/var/ctags% cat /tmp/foo.c                                     
> int foo (void);
> 
> int foo (void) {}
> 
> [jet@living]~/var/ctags% ./ctags --fields=+n --kinds-C=+p -o tags /tmp/foo.c
> [jet@living]~/var/ctags% cat tags
> !_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
> !_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
> !_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
> !_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
> !_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
> !_TAG_PROGRAM_URL	https://ctags.io/	/official site/
> !_TAG_PROGRAM_VERSION	0.0.0	/6ca4b89f/
> foo	/tmp/foo.c	/^int foo (void) {}$/;"	f	line:3	typeref:typename:int
> foo	/tmp/foo.c	/^int foo (void);$/;"	p	line:1	typeref:typename:int	file:
> [jet@living]~/var/ctags% ./readtags -en -S '(if (eq? $kind "p") 1 -1)' foo
> foo	/tmp/foo.c	/^int foo (void);$/;"	kind:p	file:	line:1	typeref:typename:int
> foo	/tmp/foo.c	/^int foo (void) {}$/;"	kind:f	line:3	typeref:typename:int
> [jet@living]~/var/ctags% ./readtags -en -S '(if (eq? $kind "p") -1 1)' foo
> foo	/tmp/foo.c	/^int foo (void) {}$/;"	kind:f	line:3	typeref:typename:int
> foo	/tmp/foo.c	/^int foo (void);$/;"	kind:p	file:	line:1	typeref:typename:int
> ```
> 
> You can give a sorting rule with -S option.
> However, as far as I know, there is no tool using readtags internally.


I think you misunderstood my meaning, what I want is not real **"Jumping to the definition"** , but the priority symbols appear. for example:

1) the 'h'(header) file appears in front of the 'c' file
`
ngx_hash_init   ngx_hash.h      /^ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,$/;"    prototype       line:106      language:C++     typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def
ngx_hash_init   ngx_hash.c      /^ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)$/;"    function        line:252       language:C      typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def      end:462
`

so, when we jump to 'ngx_hash_init', the header file has higher priority:
`
  # pri kind tag               file
  1 F   prototypengx_hash_init ngx_hash.h
               line:106 language:C++ typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) ro
               les:def
               ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,
  2 F   functionngx_hash_init  ngx_hash.c
               line:252 language:C typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) role
               s:def end:462
               ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)
Type number and <Enter> (empty cancels): 
`


2) the 'c' file appears in front of the 'h'(header) file
`
ngx_hash_init   ngx_hash.c      /^ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)$/;"    function        line:252       language:C      typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def      end:462
ngx_hash_init   ngx_hash.h      /^ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,$/;"    prototype       line:106      language:C++     typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def
`

so, when we jump to 'ngx_hash_init', the 'c' file has higher priority:
`
  # pri kind tag               file
  1 F   functionngx_hash_init  ngx_hash.c
               line:252 language:C typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) role
               s:def end:462
               ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)
  2 F   prototypengx_hash_init ngx_hash.h
               line:106 language:C++ typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) ro
               les:def
               ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,
Type number and <Enter> (empty cancels): 
`

What I want is the ability to control the order of occurrence of the same symbols for the 'h'(header) file and the 'c' file.  As far as I know the '--sort' option can not do that:
`
$ ctags --help
  --sort=[yes|no|foldcase]
       Should tags be sorted (optionally ignoring case) [yes]?
`

**Comment by ling-zhou** [comment]
> > maybe ctags could add an option '--impl-symbol-first' or something else like that for this feature?
> 
> Requirements for the order of sorting may be changed by use context.
> So I think sorting should be done after generating tags though ctags has --sort option.

I think you misunderstood my meaning, what I want is not real **"Jumping to the definition"** , but the priority that symbols appear. for example:

**case 1.** the 'h'(header) file appears in front of the 'c' file
```
ngx_hash_init   ngx_hash.h      /^ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,$/;"    prototype       line:106      language:C++     typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def
ngx_hash_init   ngx_hash.c      /^ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)$/;"    function        line:252       language:C      typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def      end:462
```
so, when we jump to 'ngx_hash_init', the header file has higher priority:
```
  # pri kind tag               file
  1 F   prototypengx_hash_init ngx_hash.h
               line:106 language:C++ typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) ro
               les:def
               ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,
  2 F   functionngx_hash_init  ngx_hash.c
               line:252 language:C typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) role
               s:def end:462
               ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)
Type number and <Enter> (empty cancels): 
```

**case 2.** the 'c' file appears in front of the 'h'(header) file
```
ngx_hash_init   ngx_hash.c      /^ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)$/;"    function        line:252       language:C      typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def      end:462
ngx_hash_init   ngx_hash.h      /^ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,$/;"    prototype       line:106      language:C++     typeref:typename:ngx_int_t      signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts)     roles:def
```
so, when we jump to 'ngx_hash_init', the 'c' file has higher priority:
```
  # pri kind tag               file
  1 F   functionngx_hash_init  ngx_hash.c
               line:252 language:C typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) role
               s:def end:462
               ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names, ngx_uint_t nelts)
  2 F   prototypengx_hash_init ngx_hash.h
               line:106 language:C++ typeref:typename:ngx_int_t signature:(ngx_hash_init_t * hinit,ngx_hash_key_t * names,ngx_uint_t nelts) ro
               les:def
               ngx_int_t ngx_hash_init(ngx_hash_init_t *hinit, ngx_hash_key_t *names,
Type number and <Enter> (empty cancels): 
```



What I want is the ability to control the order of occurrence of the same symbols for the 'h'(header) file and the 'c' file.  I(maybe someone else too) need an option to get the result of '**case 2'** forcibly.
As far as I know the '--sort' option can not do that:
```
$ ctags --help
  --sort=[yes|no|foldcase]
       Should tags be sorted (optionally ignoring case) [yes]?
```

**Comment by masatake** [comment]
> I deleted one '}' in line 352 by accident, this is the wrong code snippet:

Do you mean ctags should tags as you expected even if you remove one '}' in the source code?

**Comment by masatake** [comment]
> case 1. the 'h'(header) file appears in front of the 'c' file

Whether prototype decl or implementation are important is up to the context of usage of tags file.
ctags should not decide the order. In addition, I cannot find efficient way to implement such feature.


It should be solved in your client tool.

```
ngx_hash_init   ngx_hash.h      /^.*$/;"    prototype       line:106      language:C++     ...
ngx_hash_init   ngx_hash.c      /^.*$/;"    function        line:252       language:C      ...
```

Though the name fields for the two tag entires have the same value, your client tool reorder the list by referring kind fields. One has `prototype` as the value for kind field. Another has `function`.
Your client tool use the values in the kind fields as keys for sorting.

About the case 2, the source file names can be used as hints.

ctags should just generate tags file. Client tools should adapt the file contents to their purpose.
Though I have added code violating this rule, this is very basic rule of u-ctags design.

**Comment by ling-zhou** [comment]
> > I deleted one '}' in line 352 by accident, this is the wrong code snippet:
> 
> Do you mean ctags should tags as you expected even if you remove one '}' in the source code?

No. But it is awesome if it could be implemented.

**Comment by ling-zhou** [comment]
> > case 1. the 'h'(header) file appears in front of the 'c' file
> 
> Whether prototype decl or implementation are important is up to the context of usage of tags file.
> ctags should not decide the order. In addition, I cannot find efficient way to implement such feature.
> 
> It should be solved in your client tool.
> 
> ```
> ngx_hash_init   ngx_hash.h      /^.*$/;"    prototype       line:106      language:C++     ...
> ngx_hash_init   ngx_hash.c      /^.*$/;"    function        line:252       language:C      ...
> ```
> 
> Though the name fields for the two tag entires have the same value, your client tool reorder the list by referring kind fields. One has `prototype` as the value for kind field. Another has `function`.
> Your client tool use the values in the kind fields as keys for sorting.
> 
> About the case 2, the source file names can be used as hints.
> 
> ctags should just generate tags file. Client tools should adapt the file contents to their purpose.
> Though I have added code violating this rule, this is very basic rule of u-ctags design.

All right, let it be, thank you.

**Comment by masatake** [comment]
> No. But it is awesome if it could be implemented.

Universal-ctags will not handle broken input.
