### ISSUE TITLE
Add 'D: macroparam' expected output to misc/mini-geany.expected

### ISSUE THREAD

**Issue by derekschrock** [universal-ctags/ctags#2143]
Introduced in commit 8e55f288 should [misc/mini-geany.expected](../tree/master//misc/mini-geany.expected) have `D: macroparam` output?

`make check` or `make tlib` fail because of this.

```diff
$ make check

...

comparing with expected output:
--- ./misc/mini-geany.expected  2019-07-15 12:32:14.000000000 +0000
+++ /wrkdirs/usr/ports/devel/universal-ctags/work/ctags-71525fe9/misc/mini-geany.actual 2019-07-16 00:57:57.450892000 +0000
@@ -16,6 +16,7 @@
 x: externvar
 z: parameter
 L: label
+D: macroparam

 Parsing buffer:
 foo    line: 1 kind: function   lang: C
*** Error code 1
```

**Comment by masatake** [comment]
@techee, I added a kind (D/macroparam) representing macro-parameters to C, C++, and CPreProcessor parsers.

As the result, we got unexpected result from mini-geany.
Is adding the kind acceptable to Geany?

**Comment by masatake** [comment]
tlib target didn't report a failure properly. So I could not know  8e55f28 breaks the test case.
Following patch is needed.

```
[yamato@slave]~/var/ctags-github% git diff
diff --git a/makefiles/testing.mak b/makefiles/testing.mak
index 08acf005..bc245411 100644
--- a/makefiles/testing.mak
+++ b/makefiles/testing.mak
@@ -175,11 +175,14 @@ tlib: $(MINI_GEANY_TEST)
    builddir=$$(pwd); \
    mkdir -p $${builddir}/misc; \
    if test -s '$(MINI_GEANY_TEST)'; then \
-       $(SHELL) $(srcdir)/misc/tlib $(MINI_GEANY_TEST) \
+       if $(SHELL) $(srcdir)/misc/tlib $(MINI_GEANY_TEST) \
            $(srcdir)/misc/mini-geany.expected \
            $${builddir}/misc/mini-geany.actual \
-           $(VG); \
-       echo 'mini-geany: OK'; \
+           $(VG); then \
+           echo 'mini-geany: OK'; \
+       else \
+           echo 'mini-geany: FALIED'; \
+       fi; \
    else \
        echo 'mini-geany: SKIP'; \
    fi
```

**Comment by masatake** [comment]
I discuss an issue derived from this issue at https://github.com/geany/geany/issues/2227 .

**Comment by techee** [comment]
Maybe we could just skip printing the kinds by mini-geany so adding/removing kinds doesn't affect its output. I did this just as an example and to utilize ctagsGetKindFromName(), ctagsGetKindName(), ctagsGetKindName() which we need in Geany (but for something else).

**Comment by masatake** [comment]
I see. Thank you. I will take more time for the area between u-ctags and Geany.
As I wrote in geany/geany#2227, I have some ideas.
