### ISSUE TITLE
The license of NSIS (and docbook) parsers

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2144]
@eht16, I imported your NSIS parser from Geany to Universal-ctags.

After merging, I noticed the version of GPL was not written explictly:
```
*   This source code is released for free distribution under the terms of the
*   GNU General Public License.
```
Can I change this to
```
*   This source code is released for free distribution under the terms of the
*   GNU General Public License version 2 or (at your option) any later version.
```

?

**Comment by eht16** [comment]
Yes, that's fine by me.
Thanks for taking care.

**Comment by masatake** [comment]
@eht16, thank you.
I have one more request.
I would like to do the same (writing the version of GPL explitly) on your docbook parser.
Is it o.k.?

**Comment by eht16** [comment]
Yes, this is OK as well. Please add the version of the GPL explicitly to the code.

**Comment by masatake** [comment]
Thank you. I will work on importing the docbook parser.

**Comment by masatake** [comment]
@eht16, hi, again. 
I have one more request.
I would like to do the same (writing the version of GPL explitly) on your powershell parser. Is it o.k.?

Sorry for contacting repeatedly.

**Comment by eht16** [comment]
Yes, it's fine by me.
No worries about asking me about this. I appreciate your efforts on this topic!

**Comment by masatake** [comment]
Thank you.
