### ISSUE TITLE
Javascript: methods with decorators are ignored

### ISSUE THREAD

**Issue by bigfish** [universal-ctags/ctags#2154]
The name of the parser: Javascript

The command line you used to run ctags:

```
$ ctags --options=NONE ...
```

The content of input file:

```Javascript

class Foo {

  @decorator
  decoratedMethod(arg) {
  }

}

```

The tags output you are not satisfied with:

```
Foo	decoratedMethod.js	/^class Foo {$/;"	c

```

The tags output you expect:

```
Foo	decoratedMethod.js	/^class Foo {$/;"	c
decoratedMethod	decoratedMethod.js	/^  decoratedMethod(arg) {$/;"	m	class:Foo
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(1b747b38), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb  3 2019, 20:32:34
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames

```

How do you get ctags binary:

binary taken from Universal-ctags/homebrew-universal-ctags project,

**Comment by bigfish** [comment]
here's an article about JS decorators, with some examples: https://www.sitepoint.com/javascript-decorators-what-they-are/. Take note that: 

- They can be applied to class definitions as well as method definitions
- They can be stacked on top of each other
- They can take arguments , eg. @log('error') . 
- They can also be on the same line as the method, preceding it, eg. @fancy method() {}
- They can have dots in them.. @namespace.decorator
-  They can be expressions in parentheses that resolve to a decorator function:  @(complex ? dec1 : dec2)  

Decorators are not officially part of the language yet, but the Babel transpiler accepts them and compiles them into function calls. See here https://babeljs.io/blog/2018/09/17/decorators for details on how Babel is supporting the latest decorators proposal. The decorator syntax has changed slightly since previous versions, and now decorators can no longer be used on Object literals (classes only).

**Comment by bigfish** [comment]
basically, I think you could ignore anything starting with @ above a method ;)

**Comment by masatake** [comment]
@bigfish, could you try #2159?

**Comment by bigfish** [comment]
Sorry, i went on vacation! I will try it out.
