### ISSUE TITLE
Moose parser crash

### ISSUE THREAD

**Issue by hanwen** [universal-ctags/ctags#2160]
this file

https://raw.githubusercontent.com/bloomberg/chromium.bb/f0d58e4aa841fda8e55d8d8b0196898a17e7c6e8/src/third_party/perl/perl/vendor/lib/Parse/Method/Signatures.pm

causes a crash:

$ universal-ctags --options=NONE src/third_party/perl/perl/vendor/lib/Parse/Method/Signatures.pm 
universal-ctags: Notice: No options will be read from files or environment
Segmentation fault

*****

```
universal-ctags --version
Universal Ctags 0.0.0(920e7910), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 31 2019, 19:54:28
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +json, +interactive, +sandbox, +packcc
```

How do you get ctags binary:

(
local build
)

**Comment by masatake** [comment]
@hanwen, thank you.
Please, try #2161.

**Comment by hanwen** [comment]
LGTM
