### ISSUE TITLE
I volunteer to maintain ctags-snap

### ISSUE THREAD

**Issue by tartley** [universal-ctags/ctags#2195]
I volunteer to maintain the snap release of universal-ctags.

I recently joined Canonical as a member of the Snap Store team. To improve my knowledge of the Snap ecosystem, I want to adopt a project to maintain a snap of.

I use ctags daily (mostly from Vim, for Python and Go), so I could use the ctags snap and have an active motivation to keep it working well.

I confess I was unaware of the universal fork until today. But it sounds great! :-)

Background:

The ctags-snap repo
https://github.com/universal-ctags/ctags-snap
currently says it is unmaintained.

The snap hasn't had a release since v0.1.1 2018-12-07.

**Comment by masatake** [comment]
Fine. Thank you. I sent an invitation.

**Comment by masatake** [comment]
I think I can close this now.
