### ISSUE TITLE
"case classes" break ctags parsing

### ISSUE THREAD

**Issue by dynofu** [universal-ctags/ctags#2207]
commit 2854ad6d7758d2dd883c5178219ef6e02c51ed53 is good
commit 27650e323c732d2c8fcc323adfb389577da29d3c is bad. 

build locally and used with opengrok

17:56:34 WARNING: File '/spark/sql/hive/src/test/resources/golden/timestamp_udf-13-51959036fd4ac4f1e24f4e06eb9b0b6' interrupted--tagLine == null
17:56:34 WARNING: Error from ctags: ctags: Non-alphanumeric char is used in kind name: 'case classes' in "--regex-scala" option
17:56:34 WARNING: ctags: Unexpected end of file!
17:56:34 WARNING: ctags exited with code: 1

**Comment by masatake** [comment]
> Non-alphanumeric char is used in kind name: 'case classes' in "--regex-scala" option

Your scala parser defines a  kind including a white space char.
It violates tags format.

When defining a kind, I recommend you to use --kinddef-<LANG> option.
See https://github.com/universal-ctags/ctags/blob/master/README.md .

**Comment by masatake** [comment]
BTW, thank you for bisecting to spot the issue.

**Comment by dynofu** [comment]
thanks for the response. then it must be opengrok passed a wrong args. will report the issue there.
