### ISSUE TITLE
SQL: capture COMMENT keyword as an identifier

### ISSUE THREAD

**Issue by akemrir** [universal-ctags/ctags#2215]
The name of the parser: SQL

The command line I used to run ctags:

```
$ ctags --options=NONE src/models/comment.sql  --verbose
```

The content of input file:

```SQL
create table api.comment (
  id serial primary key,
  body character varying(250) not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
```

The tags output you are not satisfied with:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/3fdf28bc/
```

The tags output you expect:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/3fdf28bc/
created_at	src/models/comment.sql	/^  created_at timestamptz default now(),$/;"	E	table:comment
id	src/models/comment.sql	/^  id serial primary key,$/;"	E	table:comment
body	src/models/comment.sql	/^  body character varying(250) not null default 'pl',$/;"	E	table:comment
updated_at	src/models/06_comment.sql	/^  updated_at timestamptz default now(),$/;"	E	table:comment

```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(3fdf28bc), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 22 2019, 21:51:22
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
```

How do you get ctags binary:
From package manager on archlinux.
extra/ctags 1:r20190522+g3fdf28bc-1

**Comment by masatake** [comment]
It seems that COMMENT is a reserved word.
https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_4009.htm#SQLRF01109

**Comment by akemrir** [comment]
I think it does not matter.
https://docs.oracle.com/cd/B28359_01/server.111/b28286/ap_keywd.htm#SQLRF022

I used keyword grant, compress, connect as table name and they was indexed.
Maybe there is some other restriction which prevents it from indexing.

So I need to add own regex-SQL to index this.

**Comment by akemrir** [comment]
Postgresql COMMENT is not indexed, I have almost all kinds used. Only local and records is turned off.

**Comment by masatake** [comment]
I open a pull request for fixing this issue. See #2217. Obviouly, we have to consider the other keywords and contest of parsing.
@akemrir, you know well about SQL thna I. I need your input.

**Comment by masatake** [comment]
"comment" is ignored by the parser because the parser regards it as a keyword.
"body" is ignored by the parser because the parser regards it as a keyword.
How about "select"? Can we use it as a name of a table or a fields?
How about "create"? How about ...

**Comment by masatake** [comment]
https://www.postgresql.org/docs/12/sql-keywords-appendix.html
The concepts "reserved" and "non-reserved" relate to this issue.

**Comment by masatake** [comment]
https://dev.mysql.com/doc/refman/8.0/en/keywords.html
explains well.

**Comment by akemrir** [comment]
Yeah this is complex. Different databases could have different approach to this.
`create` and `select` of course should not be available as table names or columns, they don't have any significant meaning as separate entities.

In case of `comment` or `body` this could be useful as entity or column name.
`comment` could be used in postgres in query like this one `COMMENT ON TABLE posts IS 'something'`.
Maybe that's why is non-reserved in postgres. But this query is postgres specific.

When `comment` is used as entity name properly is not harmful to query parser.
Even when I set search_path explicitly and query like this `select * from comment` postgres don't rise any errors.

**Comment by akemrir** [comment]
masatake sorry for interuption, but there is one statement from resulting tags missing
```comment	src/models/comment.sql	/^create table api.comment ($/;"	kind:t	line:7
```

**Comment by masatake** [comment]
> masatake sorry for interuption, but there is one statement from resulting tags missing
I see. I already considered about it.

I'm working on better fix than I proposed in #2217.

**Comment by masatake** [comment]
Your input uses non-reserved keywords for a table name and a field name.
For them, I think I fixed in #2217.

How about the other contexts?
e.g. using a keyword for a procedure name.
I don't know well about SQL, so I cannot write an example that shows a bug.
If you can, let me know. I think I can fix them quikly.

**Comment by akemrir** [comment]
@masatake We can't use keywords as procedure name in some cases.
```
Most non-reserved key words are actually the names of built-in tables and functions specified by SQL.
```
For example if I try to create function `create()` I receive syntax error.
They must be named differently for example create_comment.
But when I try to create function `comment()` this is possible.

create is reserved keyword, comment is non-reserved.
In case of naming function create or comment, they will not have any significant meaning ;)
This is not, a problem in case of tags indexing. Programmer must choose appropriate name.

IMHO this context should be indexed too.

**Comment by masatake** [comment]
> IMHO this context should be indexed too.

Thank you. I inspected the source of the SQL parser and I found that the parser already accept keywords as the name of procedures. So I don't have to do nothing special.

o.k. I will merge my changes.

**Comment by akemrir** [comment]
@masatake thanks for help
