### ISSUE TITLE
`--exclude` does not exclude when a file is designated on the command line

### ISSUE THREAD

**Issue by xuhdev** [universal-ctags/ctags#2227]
I tried to run something like this:

    ctags --exclude=build ./build/Makefile

While I'm expecting the whole `build` directory to be excluded, the content of `Makefile` is tagged.

This can be annoying when one uses `find` to run ctags recursively.

**Comment by masatake** [comment]
I would like to know the command line for invoking ctags. I guess inseerting `grep -v /build/` instead of using `--exclude=build` option may solve your issue.

**Comment by xuhdev** [comment]
@masatake I'm attempting to write a ctags wrapper that would invoke ctags on a per file basis, so the command line listed in the original message is pretty much it. The reason that using `grep` is not ideal is that a user can put `--exclude=...` in a `.ctags.d` directory, something that ctags knows the best.

It actually turned out to be a different issue. I will open another ticket.
