### ISSUE TITLE
ctags --exclude: patterns not recognized when the file name starts with `./`

### ISSUE THREAD

**Issue by xuhdev** [universal-ctags/ctags#2229]
Any of the following commands will generate an empty tags file:

    ctags --options=NONE -o - '--exclude=build/*' build/Makefile
    ctags --options=NONE -o - '--exclude=build' build/Makefile
    ctags --options=NONE -o - '--exclude=build' ./build/Makefile

But the following will not:

    ctags --options=NONE -o - '--exclude=build/*' ./build/Makefile

It seems like the input file path was not converted to a path relative to current working directory before the matching.

`ctags --version`:

```
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  6 2019, 23:23:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml
```

**Comment by masatake** [comment]
It is not reproduced.

```
$ ls -l build
total 4
-rw-rw-r--. 1 yamato yamato 18 Oct  6 22:55 Makefile
$ cat build/Makefile 
all:
	@echo "all"
$ u-ctags --version
Universal Ctags 0.0.0(11dcb6fe), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct  6 2019, 23:56:10
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +aspell, +packcc
$ u-ctags --options=NONE -o - --exclude=build build/Makefile
u-ctags: Notice: No options will be read from files or environment
all	build/Makefile	/^all:$/;"	t
$ u-ctags --options=NONE -o - --exclude=build ./build/Makefile
u-ctags: Notice: No options will be read from files or environment
all	./build/Makefile	/^all:$/;"	t
$ e-ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb  7 2018, 06:05:35
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
$ e-ctags --options=NONE -o - --exclude=build build/Makefile
No options will be read from files or environment
$ e-ctags --options=NONE -o - --exclude=build ./build/Makefile
No options will be read from files or environment
```

**Comment by masatake** [comment]
With u-ctags, "all" target is captured both with build/Makefile and ./build/Makefile.

**Comment by xuhdev** [comment]
@masatake Looks like I have some environment issue. I reproduced the issue using `--options=None` and edited the original comment. Thanks!

**Comment by masatake** [comment]
Please, put your "ctags --version" output.

**Comment by xuhdev** [comment]
@masatake Added

**Comment by masatake** [comment]
Reproduced. However, I wonder we should implement the future you want (or fix what you reported).

--exclude does just text operations.
To implement what you want may need file system operations.

```
ctags --options=NONE -o - '--exclude=build/*' ../foo/build/Makefile
```

In this case, how ctags can decide whether ctags should make tags for ../foo/build/Makefile or not.

```
ctags --options=NONE -o - '--exclude=../bar/build/*' ../foo/build/Makefile
```

How about this one?
If "ln bar foo" is done, the Makefile should be excluded.

**Comment by xuhdev** [comment]
@masatake I added two more situations to the original comment. For the sake of consistency and minimizing the loss of compatibility, it is desirable to fix the last situation in the original comment. To take care of your last example, maybe ctags can always simplify the input path to the simplest relative path to the current working directory?

An alternative may be to add `--exclude-dir` option, which does path simplification, while leaving `--exclude` to a naive pattern matching.

**Comment by masatake** [comment]
I recommend you to read code of ctags. See main/strlist.c.

```
[yamato@slave]/tmp% u-ctags --options=NONE -o - --exclude='build/*' build/Makefile
u-ctags --options=NONE -o - --exclude='build/*' build/Makefile
u-ctags: Notice: No options will be read from files or environment
[yamato@slave]/tmp% u-ctags --options=NONE -o - --exclude='build' build/Makefile
u-ctags --options=NONE -o - --exclude='build' build/Makefile
u-ctags: Notice: No options will be read from files or environment
all	build/Makefile	/^all:$/;"	t
[yamato@slave]/tmp% u-ctags --options=NONE -o - --exclude='build' ./build/Makefile
u-ctags --options=NONE -o - --exclude='build' ./build/Makefile
u-ctags: Notice: No options will be read from files or environment
all	./build/Makefile	/^all:$/;"	t
[yamato@slave]/tmp% u-ctags --options=NONE -o - --exclude='build/*' ./build/Makefile
u-ctags --options=NONE -o - --exclude='build/*' ./build/Makefile
u-ctags: Notice: No options will be read from files or environment
all	./build/Makefile	/^all:$/;"	t
```

The result on my system is different from what you got.
The result of mine is expected. It is just text operation.
`build` doesn't match build/Makefile, ./build/Makefile. So they are not excluded.
`build/*` matches build/Makefile. So it is not excluded.
`build/*` doesn't match ./build/Makefile. So it is not excluded.

This behaviors are expected. Not a bug.

If ctags.1 man pages doesn't help you, I would like you to make a pull request updating the man page.
If your ctags doesn't run as I wrote, please, try the latest version. Even if it doesn't run as I wrote,
it must be fixed.

**Comment by xuhdev** [comment]
Oops, I pasted the newly added lines to the wrong place. Your output is the same as mine. Thanks, this bug report is a misfire.
