### ISSUE TITLE
units: modeline-vs-2gram.m is not tested

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#2244]
`Units/modeline-vs-2gram.m` is not tested by `make units`, because the directory name is ended by `.m`.

I locally renamed it to `modeline-vs-2gram.d`, but the test still failed because the test expects the language to be Object C, but the language was detected as Matlab.
Maybe it should be renamed to `modeline-vs-2gram.b`, or needs some more modifications.

(Found while implementing #2240.)

**Comment by masatake** [comment]
Thank you very much. Could you make a pull request for removing Units/modeline-vs-2gram.m, and merge it?

Some years ago, I implemented a method choosing proper parser by 2gram.
However, it didn't work well enogh, so I deleted my code.  Now the test case becomes gabege.

**Comment by k-takata** [comment]
Done with #2245.
