### ISSUE TITLE
Releases for packaging

### ISSUE THREAD

**Issue by Eluminae** [universal-ctags/ctags#2253]
Hello there!

I'd like to package universal ctags for voidlinux repositories but the prob is there is no release of universal ctags. 
https://github.com/void-linux/void-packages/issues/15689
I checked there is milestones about some 1.0.0 release but this seems totally outdated.

What is the plan about releases ?

Thanks a lot !

**Comment by masatake** [comment]
Just, no plan.

**Comment by k-takata** [comment]
Related #1038.

**Comment by masatake** [comment]
I wrote the current status in #1038.
