### ISSUE TITLE
Tag HTML, embedded CSS, and embedded JavaScript when tagging PHP files

### ISSUE THREAD

**Issue by StephenWall** [universal-ctags/ctags#2256]
It would be useful if the PHP parser called the HTML parser to do tags generation for anything outside the `<?php ... ?>` region in `.php`, `.phtml`, etc files, similar to how the HTML parser can generate JavaScript and CSS tags for `<script>` or `<style>` elements, respectively, in an `.html` file.

**Comment by masatake** [comment]
Do you have any example input?

**Comment by StephenWall** [comment]
I'm afraid the examples of this I have are all proprietary code, and can't be shared.  We make heavy use in particular of HTML and JavaScript in `.php` files in an [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) framework, for the view component.  The layout is typically a bunch of HTML that renders a component of the UI (such as a panel or dialog) with bits of embedded PHP to fill in details (e.g., values extracted from a database), followed by a `<script>` element containing code for all the actions the user can take.

Here's a contrived example I based on one you posted at https://github.com/universal-ctags/ctags/issues/1566#issuecomment-469022265

```php
<?php
  function draw($x) {
    SomeClass::render_output($x);
  }
?>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <title>My Home Page</title>
    <link rel="stylesheet" href="css/general.css" type="text/css">
    <style type="text/css"></stylE>
  </head>
  <body>
    <h1>stuff</h1>
    <a href="/blah">nowhere</a>
    <?=draw('nowhere')?>
    <a href="/blech">somewhere</a>
    <?=draw('somewhere')?>
  </body>
</html>
<script>
    var f = function (n) {
	return n + 1;
    }
</script>
<style>
.blarg {
    position: relative;
}
</style>
```
You can also find some fairly simple examples at https://github.com/radicand/phpki

**Comment by masatake** [comment]
An experimetal version works.

```
diff --git a/main/read.c b/main/read.c
index 9b071c62..3daf38b3 100644
--- a/main/read.c
+++ b/main/read.c
@@ -145,6 +145,8 @@ extern unsigned long getInputLineNumber (void)
 
 extern int getInputLineOffset (void)
 {
+	if (!File.line)
+		return 0;
 	unsigned char *base = (unsigned char *) vStringValue (File.line);
 	int ret = File.currentLine - base - File.ungetchIdx;
 	return ret >= 0 ? ret : 0;
diff --git a/parsers/php.c b/parsers/php.c
index ce390ae7..d3975179 100644
--- a/parsers/php.c
+++ b/parsers/php.c
@@ -25,6 +25,7 @@
 #include "routines.h"
 #include "debug.h"
 #include "objpool.h"
+#include "promise.h"
 
 #define isIdentChar(c) (isalnum (c) || (c) == '_' || (c) >= 0x80)
 #define newToken() (objPoolGet (TokenPool))
@@ -860,9 +861,20 @@ getNextChar:
 
 	if (! InPhp)
 	{
+		long startSourceLineNumber = getSourceLineNumber ();
+		long startLineNumber = getInputLineNumber ();
+		long startLineOffset = getInputLineOffset ();
 		c = findPhpStart ();
 		if (c != EOF)
 			InPhp = true;
+
+		long endLineNumber = getInputLineNumber ();
+		long endLineOffset = getInputLineOffset ();
+
+		if ((startLineNumber != endLineNumber)
+			|| (startLineOffset != endLineOffset))
+			makePromise ("HTML", startLineNumber, startLineOffset,
+						 endLineNumber, endLineOffset, startSourceLineNumber);
 	}
 	else
 		c = getcFromInputFile ();
[jet@localhost]~/var/ctags% cat /tmp/foo.php 
cat /tmp/foo.php 
<?php
  function draw($x) {
    SomeClass::render_output($x);
  }
?>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <title>My Home Page</title>
    <link rel="stylesheet" href="css/general.css" type="text/css">
    <style type="text/css"></stylE>
  </head>
  <body>
    <h1>stuff</h1>
    <a href="/blah">nowhere</a>
    <?=draw('nowhere')?>
    <a href="/blech">somewhere</a>
    <?=draw('somewhere')?>
  </body>
</html>
<script>
    var f = function (n) {
	return n + 1;
    }
</script>
<style>
.blarg {
    position: relative;
}
</style>
[jet@localhost]~/var/ctags% ./ctags --fields=+l -o - --extras='*-p' /tmp/foo.php
./ctags --fields=+l -o - --extras='*-p' /tmp/foo.php
css	/tmp/foo.php	/^    <link rel="stylesheet" href="css\/general.css" type="text\/css">$/;"	C	language:HTML
css/general.css	/tmp/foo.php	/^    <link rel="stylesheet" href="css\/general.css" type="text\/css">$/;"	C	language:HTML
draw	/tmp/foo.php	/^  function draw($x) {$/;"	f	language:PHP
f	/tmp/foo.php	/^    var f = function (n) {$/;"	f	language:JavaScript
foo	/tmp/foo.php	1;"	F	language:PHP
foo.php	/tmp/foo.php	1;"	F	language:PHP
general	/tmp/foo.php	/^    <link rel="stylesheet" href="css\/general.css" type="text\/css">$/;"	C	language:HTML
php	/tmp/foo.php	1;"	F	language:PHP
stuff	/tmp/foo.php	/^    <h1>stuff<\/h1>$/;"	h	language:HTML
[jet@localhost]~/var/ctags% 
```

**Comment by masatake** [comment]
I have to study more to make a pull request.

**Comment by masatake** [comment]
> foo	/tmp/foo.php	1;"	F	language:PHP
foo.php	/tmp/foo.php	1;"	F	language:PHP
php	/tmp/foo.php	1;"	F	language:PHP

??? It looks something wrong.

**Comment by StephenWall** [comment]
> > foo	/tmp/foo.php	1;"	F	language:PHP
> > foo.php	/tmp/foo.php	1;"	F	language:PHP
> > php	/tmp/foo.php	1;"	F	language:PHP
>
> ??? It looks something wrong.

I see that in the version of uctags I am currently using (g20190223) as well.  Parsing the sample as an HTML file (same content, but in `foo.html`) with `--extras='*-p'` produces
```
foo	foo.html	1;"	F	language:HTML
foo.html	foo.html	1;"	F	language:HTML
html	foo.html	1;"	F	language:HTML
```
and parsing it as a PHP file produces the lines you noted (as well as the normal tags, of course).  Looks like it's creating tags for the file name, but also for each dot-separated component of the filename.  I'm guessing its the combination of `subword` and `inputFile` that using `--extras=*` caused.

> uctags --list-extras
> #LETTER NAME              ENABLED LANGUAGE FIXED DESCRIPTION
> \-       anonymous         yes     NONE     no    Include tags for non-named objects like lambda
> **\-       subword           no      NONE     no    Include tags for subwords generated by splitting the original tag (only for ctags development)**
> f       inputFile         no      NONE     no    Include an entry for the base file name of every input file
> ...

So, I don't think it's a problem.

I note that your patched code did not pick up the CSS code (`<script>` element) - parsing as HTML produces a tag for `.blarg` and `blarg`, which aren't in your output.


I like the patch, BTW.  Looks like you've already got the code structured to make parsing embedded languages easy.  Now I want to check if the SQL parser handles embedded python and perl functions. :)

**Comment by masatake** [comment]
Thank you! I forgot I added subword extra though I added. subword should not be enabled even when we speicfy `--extras='*'`.

> I note that your patched code did not pick up the CSS code (<script> element) - parsing as HTML produces a tag for .blarg and blarg, which aren't in your output.

It seems that EOF is not handled well when calculating the line number of input. I will inspect more.

**Comment by masatake** [comment]
I got a better result.

```
[jet@localhost]~/var/ctags% git diff|cat
git diff|cat
diff --git a/main/read.c b/main/read.c
index 9b071c62..d0c9e54b 100644
--- a/main/read.c
+++ b/main/read.c
@@ -145,8 +145,15 @@ extern unsigned long getInputLineNumber (void)
 
 extern int getInputLineOffset (void)
 {
+	if (!File.line)
+		return 0;
 	unsigned char *base = (unsigned char *) vStringValue (File.line);
-	int ret = File.currentLine - base - File.ungetchIdx;
+	int ret = 0;
+
+	if (File.currentLine)
+		ret = File.currentLine - base - File.ungetchIdx;
+	else
+		ret = mio_tell (File.mio) - getInputFileOffsetForLine(File.input.lineNumber);
 	return ret >= 0 ? ret : 0;
 }
 
diff --git a/parsers/php.c b/parsers/php.c
index ce390ae7..b420c68c 100644
--- a/parsers/php.c
+++ b/parsers/php.c
@@ -25,6 +25,7 @@
 #include "routines.h"
 #include "debug.h"
 #include "objpool.h"
+#include "promise.h"
 
 #define isIdentChar(c) (isalnum (c) || (c) == '_' || (c) >= 0x80)
 #define newToken() (objPoolGet (TokenPool))
@@ -860,9 +861,22 @@ getNextChar:
 
 	if (! InPhp)
 	{
+		unsigned long startSourceLineNumber = getSourceLineNumber ();
+		unsigned long startLineNumber = startSourceLineNumber;
+		int startLineOffset = getInputLineOffset ();
 		c = findPhpStart ();
 		if (c != EOF)
 			InPhp = true;
+
+		unsigned long endLineNumber = getInputLineNumber ();
+		int endLineOffset = getInputLineOffset ();
+
+		if ((startLineNumber != endLineNumber)
+			|| (startLineOffset != endLineOffset))
+		{
+			makePromise ("HTML", startLineNumber, startLineOffset,
+						 endLineNumber, endLineOffset, startSourceLineNumber);
+		}
 	}
 	else
 		c = getcFromInputFile ();
[jet@localhost]~/var/ctags% ./ctags --fields=+l -o - --extras='*-p{subword}' /tmp/foo.php
./ctags --fields=+l -o - --extras='*-p{subword}' /tmp/foo.php
.blarg	/tmp/foo.php	/^.blarg {$/;"	c	language:CSS
css/general.css	/tmp/foo.php	/^    <link rel="stylesheet" href="css\/general.css" type="text\/css">$/;"	C	language:HTML
draw	/tmp/foo.php	/^  function draw($x) {$/;"	f	language:PHP
f	/tmp/foo.php	/^    var f = function (n) {$/;"	f	language:JavaScript
foo.php	/tmp/foo.php	1;"	F	language:PHP
stuff	/tmp/foo.php	/^    <h1>stuff<\/h1>$/;"	h	language:HTML
```

**Comment by masatake** [comment]
I found many bugs around calculating byte offsets for boundaries where the html parser runs.
I"m fixing them.
