### ISSUE TITLE
RPM packages doc

### ISSUE THREAD

**Issue by nenadalm** [universal-ctags/ctags#226]
Hello. I noticed there are files ctags.spec and maintainer.mak which seems to support building of rpm package somehow.

I didn't figure out how to create rpm using them yet.

So I think it would be helpful to put it in the doc somewhere.

**Comment by nenadalm** [comment]
ok, I found the help, bu I think it would be better to put it add the command into docs/
https://github.com/fishman/ctags/pull/227

**Comment by masatake** [comment]
The spec file was removed.
