### ISSUE TITLE
Signatures in define macros in C/C++ have changed recently

### ISSUE THREAD

**Issue by surmish** [universal-ctags/ctags#2275]
The name of the parser: `C++`

The command line you used to run ctags:
 `prompt:> ctags  --extras=* --fields=* --languages="C++" -L ctags_filelist`

```
prompt:> cat ctags_filelist
/tmp/urmish/temp.cpp
```

The content of input file:

```C++
#define SOME_NAME(_argument_) 50
```

The tags output you are not satisfied with:
```
NAME  /tmp/urmish/temp.cpp    /^#define SOME_NAME(/;" kind:macro      line:1  language:C++    file:   signature:(_argument_,argument) roles:def      extras:fileScope,subword
SOME   /tmp/urmish/temp.cpp    /^#define SOME_/;"      kind:macro      line:1  language:C++    file:   signature:(_argument_,argument) roles:def       extras:fileScope,subword
SOME_NAME  /tmp/urmish/temp.cpp    /^#define SOME_NAME(/;" kind:macro      line:1  language:C++    file:   signature:(_argument_,argument)        roles:def       extras:fileScope        end:1
```

The tags output you expect:

```
NAME  /tmp/urmish/temp.cpp    /^#define SOME_NAME(/;" kind:macro      line:1  language:C++    file:   signature:(_argument_)  roles:def      extras:fileScope,subword
SOME  /tmp/urmish/temp.cpp    /^#define SOME_/;"      kind:macro      line:1  language:C++    file:   signature:(_argument_)  roles:def      extras:fileScope,subword
SOME_NAME  /tmp/urmish/temp.cpp    /^#define SOME_NAME(/;" kind:macro      line:1  language:C++  file:   signature:(_argument_)roles:def        extras:fileScope        end:1
```

The version of ctags (latest):

```
Universal Ctags 0.0.0(2d68619), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 28 2019, 11:13:34
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc
```

How do you get ctags binary: `local build, configure, make and make install`

The signature changed from `signature:(_argument_)` previously (compiled sometime in May, 2019) to `signature:(_argument_,argument)`  in the latest (compiled on Oct 28, 2019)

Is this expected? 

Also in both versions of ctags (older and latest), why are `NAME` and `SOME` treated as different macros when `SOME_NAME` is the only macro in the source file. These extra tags result in humongous `tags` files for a big project. Are these expected to be in there?

The `--extras=*` causes these extra lines. But the signature also changes from `signature(_argument_)` to `signature:(_argument_,argument)`

**Comment by masatake** [comment]
> Also in both versions of ctags (older and latest), why are NAME and SOME treated as different macros when SOME_NAME is the only macro in the source file. These extra tags result in humongous tags files for a big project. Are these expected to be in there?

I must fix this, too. Till I find time for fixing, please , use `--extras=*-{subword}` instad of `--extras=*`.

> signature:(_argument_,argument)
Unexpected result. This should be `signature:(_argument_)` as you expected.

**Comment by masatake** [comment]
If I gave '--extras=*-{subword}', the signature field is printed expectedly.
I have to say just removing `subword` extra may be the best way to fix this issue.

**Comment by surmish** [comment]
Thanks, that reduced the tags file for my project from 500+ MB to 80 MB. And I see the correct signature now.
