### ISSUE TITLE
parsers: gcc warnings when configured with --enable-debugging

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#2286]
The following two warnings are shown when u-ctags is configured with `--enable-debugging`:

```
../parsers/html.c:189:13: warning: ‘dumpToken’ defined but not used [-Wunused-function]
 static void dumpToken (tokenInfo *token, const char *context, const char* extra_context)
             ^
```

```
../parsers/jscript.c:2617:13: warning: ‘dumpToken’ defined but not used [-Wunused-function]
 static void dumpToken (const tokenInfo *const token)
             ^
```

We can comment out these two functions with `#if 0 ... #endif` or completely remove them to suppress the warnings.
(Not sure which is better.)

**Comment by masatake** [comment]
People may use the function for print-debuggnig. So wrapping #if 0/#endif may be better.
