### ISSUE TITLE
HEADS-UP: ignoring fedora_bmake build in circleci

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2290]
In these days, our test fails always on the platform.
Please, ignore it for a while.
It may be an issue of Fedora side. I have to report the issue to bugzilla.redhat.com.

**Comment by masatake** [comment]
See #2291, too.

**Comment by masatake** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1736126

It seems that mk-files package that bmake package requires is not maintained in Fedora31.
For testing building ctags with bmake, using Fedora30 where mk-files package is available is not bad solution for the issue. However, as a Fedora user, I would like to keep ctags buildable on the lastest Fedora. So I will add one more target, fedoraLatest_make to circleci.yml.

**Comment by masatake** [comment]
#2298 may fix this issue.

**Comment by masatake** [comment]
@k-takata, please, close this when merging #2298.

**Comment by k-takata** [comment]
Okay, closing then.
