### ISSUE TITLE
universal-ctags has any linux version binary to use?

### ISSUE THREAD

**Issue by Lennon925** [universal-ctags/ctags#2303]
universal-ctags has any linux version binary to use? I need to use it to parse code files on linux.

**Comment by masatake** [comment]
No. We don't provide any binary file for the platform. We don't have no plan to provide.

**Comment by Lennon925** [comment]
> No. We don't provide any binary file for the platform. We don't have no plan to provide.

so any way to use universal-ctags on linux?

**Comment by k-takata** [comment]
You can easily compile by yourself: https://docs.ctags.io/en/latest/autotools.html.
You can also use [snap](https://github.com/universal-ctags/ctags-snap). And on Ubuntu, some people provide PPA.

**Comment by Lennon925** [comment]
> You can easily compile by yourself: https://docs.ctags.io/en/latest/autotools.html.
> You can also use [snap](https://github.com/universal-ctags/ctags-snap). And on Ubuntu, some people provide PPA.

I will try and thanks for your reply.
