### ISSUE TITLE
Write ctags-faq.7.rst.in

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2312]
Expected questions we will get when releasing 6.0.0 should be written in the man page.

**Comment by masatake** [comment]
#2356 is a candidate to be included in faq.

**Comment by k-takata** [comment]
Another candidate: https://github.com/universal-ctags/ctags/issues/1837#issuecomment-562454661.

We also have `old-docs/FAQ`, but most of them might be outdated. We need to select which item should be copied to the new FAQ page.

**Comment by hirooih** [comment]
@masatake san and @k-takata san,

I've started creating a base of `ctags-faq.7.rst.in` from `old-docs/FAQ`.

> We also have old-docs/FAQ, but most of them might be outdated. We need to select which item should be copied to the new FAQ page.

I'd like to omit the following sections.  Could you give me your comments?

> Why do you call it "Exuberant Ctags"?

Obviously we don't need this.

> Why doesn't my editor work with these tag files?

An empty section.

> Why doesn't XEmacs' Speedbar module work with Exuberant Ctags?

> Why doesn't Xemacs correctly locate the tag in the source file?

The latest release of XEmacs is 2009.  See https://www.xemacs.org/.
I don't think we need these sections in 2021.

> Why doesn't NEdit correctly locate the tag in the source file?

It seems that NEdit is still an active project. See https://sourceforge.net/projects/nedit/.
But the description in this section is for very old NEdit.

> What is "Vim"?

This is not a question for ctags.

> How do I get regex support for Win32?

I believe `docs/windows.rst` covers everything how to build u-ctags on Win32, although I have not read it carefully yet.

**Comment by masatake** [comment]
I agreed with what you wrote.

I think we don't need to write much about client tools because client tools may have their own contact point.

**Comment by masatake** [comment]
I have put "FAQ" labels to issues. The discussions on the issues are the candidates for ctags-faq(7).
