### ISSUE TITLE
make units do not respect LANGUAGES

### ISSUE THREAD

**Issue by albfan** [universal-ctags/ctags#2321]
Seems make units is using a new script `misc/units.py` instead of `misc\units`.

- Python one miss the filter by LANGUAGE
- Bash one works correctly

I was able to launch bash one using:

    make units PYTHON= LANGUAGES=Vala

But is not obvious.

**Comment by albfan** [comment]
make units CATEGORIES=parser-vala

Allows me to filter too anyway

**Comment by albfan** [comment]
I miss skipped or failing test on purpose. If someone wants to report a problem (and not break the test suite should be able to create a failing test case)

https://github.com/universal-ctags/ctags/pull/2320/commits/488b9c890c81f540aaf5aa53775a51608a550024

Right now I use `.b` suffix. But not sure if `Bug` is the category we are looking for. `Failed` is better as the assumption it is a bug could be wrong.

Can we use the `.f` for know failed test? I can update the docs too if needed.

**Comment by k-takata** [comment]
> * Python one miss the filter by LANGUAGE

It's my mistake. I will fix it later.

**Comment by masatake** [comment]
I cannot image the use case well. If you write the use case for .f well, feel free to change the unit test harness. @k-takata is the master of misc/unit.py. 

BTW, thank you for reporting this bug.

**Comment by masatake** [comment]
.... as fa as reading the commet, I think .b is enough.
I would like to hear more detail about the use case.

**Comment by albfan** [comment]
Yes I think `.b` is enough too. Is just `know failed` is the more common. We can ignore that part.

    make units CATEGORIES=parser-vala

is enough as is quicker that `LANGUAGES` (do not traverse all the test cases)

Feel free to close this at any time, if I see a fix for units.py I will stop using `PYTHON=`

**Comment by k-takata** [comment]
Fixed with #2322.
