### ISSUE TITLE
Getting entire tag block start line (C++)

### ISSUE THREAD

**Issue by majenkotech** [universal-ctags/ctags#2339]
Is there a way of getting the *start* line of a "block" style tag? Something akin to:

```
int
foo(
    char *bar,
    int baz
) {
...
}
```

u-ctags reports the line number of `foo` above (which is technically correct if you want to navigate to that location) - but I can't see any way of either getting the *first* line of the block (the `int`) or easily identifying that it even is a multi-line block.

Basically I need to find the first actual function in a file and insert something immediately *before* that function (a `#include`), but if the first function is split across lines like that it gets included between the `int` and the `foo(`, which of course is an error.

**Comment by pragmaware** [comment]
The tag line is the one that the tagged identifier is on. So in this case the "foo(" line.

While emitting the tag we (usually) also have the tokens of the function return type so in fact the initial line number IS available. However currently there is no way to ask ctags to output it.

**Comment by pragmaware** [comment]
BUT: you can look at the tagged function return type and attempt to match and skip it back in your source.

**Comment by majenkotech** [comment]
> BUT: you can look at the tagged function return type and attempt to match and skip it back in your source.

Assuming the entirety of the return type is on one line...  What if:
```
static
int
foo(
    int something
) {
...
}
```

I haven't looked but I assume the typeref will include the `static` as well. Would that be `static\nint` or `static int`...? I must look to find out.

**Comment by majenkotech** [comment]
> I haven't looked but I assume the typeref will include the `static` as well. Would that be `static\nint` or `static int`...? I must look to find out.

Interestingly... no. It loses the `static` entirely.  Is that intentional, an overlooked scenario, or what?

**Comment by masatake** [comment]
Intentional. `static`  `properties` is for the purpose.
```
[jet@living]~% cat /tmp/foo.c
cat /tmp/foo.c
static
int
foo(
    int something
) {
...
}
[jet@living]~% u-ctags --fields-C=+'{properties}' -o - /tmp/foo.c
u-ctags --fields-C=+'{properties}' -o - /tmp/foo.c
foo	/tmp/foo.c	/^foo($/;"	f	typeref:typename:int	file:	properties:static
```

**Comment by majenkotech** [comment]
Yes, digging around I found that one.  I now use --fields-all=* to give me everything possible...

**Comment by majenkotech** [comment]
I see that I get an `end:x` field in that now, which shows me where the item to which the tag refers to ends. But no `start:` for where it begins, which is what I could do with - only `line:` for where within the block the tag itself is.

**Comment by masatake** [comment]
ctags is a name oriented tool.
ctags doesn't fit for your purpose.

```
[jet@living]~% cat /tmp/bar.c 
cat /tmp/bar.c 
int bar;
static
int
foo(
    int something
) {
...
}
[jet@living]~% u-ctags --fields-C=+'{properties}' --fields=+n -o - /tmp/bar.c 
u-ctags --fields-C=+'{properties}' --fields=+n -o - /tmp/bar.c 
bar	/tmp/bar.c	/^int bar;$/;"	v	line:1	typeref:typename:int
foo	/tmp/bar.c	/^foo($/;"	f	line:4	typeref:typename:int	file:	properties:static
```

You may have to scan backward from line 4 to line 1.

**Comment by masatake** [comment]
@pragmaware:
> However currently there is no way to ask ctags to output it.

As you know, parser specific field like `properties` allows ctags output it.
However, I think `start:` doesn't fit the design of ctags.

`end:` field that you introduced fits *VERY* well to the design of ctags.
A pair of `line:` and `end:` can represent the area of a named scope.
There may be applications.
On the other hand, `start:` doesn't contribute to the other parts of ctags.
The parser using chained-token can fill the start: field.

I'm feeling negative about introducing `start:`. However, of course, as far as using parser specific field, the parser maintainer can decide.

**Comment by masatake** [comment]
BTW, `int` can be captured in the future as a reference tag:

```
int	/tmp/bar.c	/^int$/;"	kind:typename	role:returnType	returneFrom:function:foo	extras:reference
foo	/tmp/foo.c	/^foo($/;"	kind:function	typeref:typename:int	file:
```

I guess chained-tokeninfo based C parser has enough ability to emit reference tags.
I didn't go this way because the reference tags make tags file too large.

**Comment by majenkotech** [comment]
I guess in most circumstances I can insert my include after the end: of the
previous tag, or at line 1 if there isn't one...

**Comment by majenkotech** [comment]
Yep, that seems to be the way forward. Thanks for the pointers.
