### ISSUE TITLE
buildsys: Generating sed rules in man/Makefile

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2346]
@k-takata, I have a one request about man/Makefile.

I would like to add more man pages. See #2312 and #2313 
In such case, I have to edit man/Makefile. It is o.k.
However, I have to edit to places: IN_SOURCE_FILES (or SOURCE_FILES) and sed arguments in ../docs/man/%.rst target.

Isn't it possible to make the target refer  IN_SOURCE_FILES (or SOURCE_FILES)?
So we have to edit only IN_SOURCE_FILES or SOURCE_FILES when adding a new man page.

**Comment by k-takata** [comment]
> sed arguments in ../docs/man/%.rst target.

Do you mean ```-e 's/\<ctags(1)/:ref:`& <&>`/g'``` and other arguments?
Not sure whether it is possible.

**Comment by k-takata** [comment]
This might work. The replacement pattern looks complicated, though.
I will create a PR later.

```diff
--- a/man/Makefile
+++ b/man/Makefile
@@ -64,15 +64,16 @@ man: $(man_pages)
 html: $(html_pages)
 pdf: $(pdf_pages)
 
+empty :=
+space := $(empty) $(empty)
+op_paren := (
+cl_paren := )
+reppat := \<\($(subst $(space),\|,$(subst .,$(op_paren),$(addsuffix $(cl_paren),$(man_pages))))\)
+
 update-docs: $(doc_files)
 
 ../docs/man/%.rst: %.rst
-	sed \
-		-e 's/\<ctags(1)/:ref:`& <&>`/g' \
-		-e 's/\<ctags-incompatibilities(7)/:ref:`& <&>`/g' \
-		-e 's/\<ctags-optlib(7)/:ref:`& <&>`/g' \
-		-e 's/\<tags(5)/:ref:`& <&>`/g' \
-	< $< > $@
+	sed -e 's/$(reppat)/:ref:`& <&>`/g' < $< > $@
 
 %.rst: %.rst.in
 ifeq ($(QUICK),)
```
