### ISSUE TITLE
docs(man): Move some descriptions after "OPTION ITEMS"?

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#2351]
(Copied from https://github.com/universal-ctags/ctags/pull/2349#issuecomment-558672914.)

I find this comment in ctags.1.rst:
https://github.com/universal-ctags/ctags/blob/f17ca7731a235b6950b8f02133ec1ff2656bddc7/man/ctags.1.rst.in#L64-L68

I agree with this comment.
The contents of e-ctags man pages are:

* SYNOPSIS
* DESCRIPTION
* SOURCE FILES
* OPTIONS
* ...

However, the contents of u-ctags man pages are:

* SYNOPSIS
* DESCRIPTION
* SOURCE FILES
  * Determining file language
* TAG ENTRIES
  * Fields
  * Kinds
  * Extras
  * Roles
  * Language-specific fields and extras
* COMMAND LINE INTERFACE
  * Letters and names
  * List options
* OPTION ITEMS
* ...

There are too many contents before "OPTION ITEMS".
I think "Determining file language" and "TAG ENTRIES" might be able to move after "OPTION ITEMS".

**Comment by k-takata** [comment]
@masatake's comment (https://github.com/universal-ctags/ctags/pull/2349#issuecomment-558870980):

> I agree with you about "Determining file language".
> I wonder how "TAG ENTRIES" should be. I think items explained in the section are the heart of ctags.
> I would like users to know about the concept.

**Comment by k-takata** [comment]
For comparison, the contents of other man pages are...

`man man`:

* SYNOPSIS
* DESCRIPTION
* EXAMPLES
* OVERVIEW
* DEFAULTS
* OPTIONS
* ...

`man git`:

* SYNOPSIS
* DESCRIPTION
* OPTIONS
* GIT COMMANDS
  * HIGH-LEVEL COMMANDS (PORCELAIN)
  * LOW-LEVEL COMMANDS (PLUMBING)
* ...

`man bash`:

* SYNOPSIS
* COPYRIGHT
* DESCRIPTION
* OPTIONS
* ARGUMENTS
* INVOCATION
* ...

"OPTIONS" might be better than "OPTION ITEMS"?
(Are there any general references for writing man pages?)

**Comment by masatake** [comment]
Could you wait for a while for this global change?
I would like to make more minor changes in OPTION ITEMS.
I'm afraid of confliction with your work.

**Comment by masatake** [comment]
All the planed minor changes for ctags.1.rst.in are done.
I will try to reorganize the sections of ctags.1.rst.

**Comment by masatake** [comment]
I will close this via #2389.
"COMMAND LINE INTERFACE" is stiil place before "OPTIONS". But much simplified.
