### ISSUE TITLE
ctags does not generate tags of functions if first argument is a macro with braces

### ISSUE THREAD

**Issue by Jyotiha** [universal-ctags/ctags#2368]
The command line you used to run ctags:
ctags --langmap=c:+.cnt.ppc.ph.msg.clib,COBOL:+.cbl * ;

The content of input file: a.c
int func1 (MACRO1(va1), MACRO2(var2) )
{
    return 0;
}

int func2 ( MACRO1         (va1),
            MACRO2         (var2)
          )
{
    return 0;
}

int func3 ( MACRO1(va1),
            MACRO2(var2)
          )
{
    return 0;
}

... tags generated

!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME      Exuberant Ctags //
!_TAG_PROGRAM_URL       http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.5.4   //
MACRO2  a.c     /^            MACRO2         (var2) $/;"        f
MACRO2  a.c     /^            MACRO2(var2) $/;" f
MACRO2  a.c     /^int func1 (MACRO1(va1), MACRO2(var2) )$/;"    f

The tags output you expect:

!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME      Exuberant Ctags //
!_TAG_PROGRAM_URL       http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.5.4   //
MACRO2  a.c     /^            MACRO2         (var2) $/;"        f
MACRO2  a.c     /^            MACRO2(var2) $/;" f
func1 a.c     /^int func1 (MACRO1(va1), MACRO2(var2) )$/;"    f
func2 a.c     /^int func2 (MACRO1(va1), MACRO2(var2) )$/;"    f
func3 a.c     /^int func3 (MACRO1(va1), MACRO2(var2) )$/;"    f

The version of ctags:

```
$ ctags --version
Exuberant Ctags 5.5.4, Copyright (C) 1996-2003 Darren Hiebert
  Compiled: Mar 15 2011, 10:01:39
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex

**Comment by Jyotiha** [comment]
one Example:
In .h

typedef char MACRO_C_T;
#define MACRO_C_SZ 2
#define MACRO_C_TSZ 1
#define MACRO_C_L 2
#define MACRO_C_D(varName) MACRO_C_T varName[MACRO_C_SZ]
#define MACRO_C_D_ARR(varName, arr) \

In .c

Int func ( MACRO_C_D(i_file_status)   )   ctags won’t identify it assumes MACRO_C_D is a function because of brackets 

Int func2 ( MACRO_C_T     i_file_status[MACRO_C_SZ] )   identifies 😊

**Comment by masatake** [comment]
```
$ ctags --version
Exuberant Ctags 5.5.4, Copyright (C) 1996-2003 Darren Hiebert
  Compiled: Mar 15 2011, 10:01:39
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```
You are not using Universal-ctags which we maintain. 
You are using Exuerant-ctags. It was developed at https://sourceforge.net/projects/ctags/ .
If you are interested in fixing the bug of ctags implementation you are using now, this is not the
place to report the bug.

I tried the input you showed with Universal-ctags:
```
[yamato@slave]/tmp% cat foo.c
cat foo.c
int func1 (MACRO1(va1), MACRO2(var2) )
{
return 0;
}

int func2 ( MACRO1 (va1),
MACRO2 (var2)
)
{
return 0;
}

int func3 ( MACRO1(va1),
MACRO2(var2)
)
{
return 0;
}

[yamato@slave]/tmp% u-ctags -o - /tmp/foo.c
u-ctags -o - /tmp/foo.c
func1	/tmp/foo.c	/^int func1 (MACRO1(va1), MACRO2(var2) )$/;"	f	language:C	typeref:typename:int
func2	/tmp/foo.c	/^int func2 ( MACRO1 (va1),$/;"	f	language:C	typeref:typename:int
func3	/tmp/foo.c	/^int func3 ( MACRO1(va1),$/;"	f	language:C	typeref:typename:int
```

It works. However, we cannot expect much. Handling macros is not so easy. This is FAQ. See  #2356.

**Comment by Jyotiha** [comment]
Thank you for your prompt response.
