### ISSUE TITLE
R parser does not recognize `=` based assignment

### ISSUE THREAD

**Issue by suntzuisafterU** [universal-ctags/ctags#2393]
(
Thank you for contacting us.

If you are reporting an issue with the parsing output, please fill
the following template.  As your custom CTags configuration can
affect results, please always use `--options=NONE` as the first
option when running `ctags`.

Otherwise, delete the template and write your issue from scratch.
Examples may help developers understanding your issue better.

Use GitHub web interface and markdown notation.
Using mail results broken text rendering that makes
the developers go crazy.
)

*****

The name of the parser: R

The command line you used to run ctags:

```
$ ctags --options=NONE *
```

The content of input file:
```{r}
test_function_1 = function() {
  print("This function does not appear in tag file.")
}

other_function  <- function() {
  print("This function appears in tag file.")
}

```

The tags output you are not satisfied with:

```
other_function	test_function_1.R	/^other_function  <- function() {$/;"	f
```

The tags output you expect:

```
other_function	test_function_1.R	/^other_function  <- function() {$/;"	f
test_function_1	/tmp/foo.r	/^test_function_1 = function() {$/;"	f
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(a3c87ab), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  6 2020, 14:54:04
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames, +packcc

```

How do you get ctags binary:

(
brew install on Mac OS 10.13
)

**Comment by suntzuisafterU** [comment]
Line 123 of parsers/r.c requires modification.

There may be some nuance in the difference between `=` and `<-` that I am not aware of,
but to treat them equivalently would be a very simple modification.

https://github.com/universal-ctags/ctags/blob/a3c87ab5232ffb9d047b187d6fd3852bfd12b197/parsers/r.c#L123

**Comment by masatake** [comment]
mainVoid? I cannot find it in test_function_1.R.
Please, verify the input file, unsatisfied output, and expected output.

**Comment by masatake** [comment]
```
$ git diff |cat
diff --git a/parsers/r.c b/parsers/r.c
index c91cdd70..cd038879 100644
--- a/parsers/r.c
+++ b/parsers/r.c
@@ -55,15 +55,22 @@ static void makeRTag (const vString * const name, rKind kind)
 	makeTagEntry (&e);
 }
 
+enum assignmentType {
+	ASSIGNMENT_UNKNOWN,
+	ASSIGNMENT_EQUAL = '=',
+	ASSIGNMENT_ARROW = '<',
+};
+
 static void createRTags (void)
 {
 	vString *vLine = vStringNew ();
 	vString *name = vStringNew ();
 	int ikind;
 	const unsigned char *line;
-
+	enum assignmentType assignmentType;
 	while ((line = readLineFromInputFile ()) != NULL)
 	{
+		assignmentType = ASSIGNMENT_UNKNOWN;
 		const unsigned char *cp = (const unsigned char *) line;
 
 		vStringClear (name);
@@ -120,9 +127,17 @@ static void createRTags (void)
 					cp++;
 				}
 				break;
+			case '=':
+				assignmentType = ASSIGNMENT_EQUAL;
 			case '<':
-				cp++;
-				if (*cp == '-')
+				if (assignmentType == ASSIGNMENT_UNKNOWN)
+				{
+					cp++;
+					if (*cp == '-')
+						assignmentType = ASSIGNMENT_ARROW;
+				};
+
+				if (assignmentType != ASSIGNMENT_UNKNOWN)
 				{
 					/* assignment: ident <- someval */
 					cp++;
@@ -152,7 +167,8 @@ static void createRTags (void)
 					if (strncasecmp ((const char *) cp, "function",
 							(size_t) 8) == 0)
 					{
-						/* it's a function: ident <- function(args) */
+						/* it's a function: ident <- function(args)
+						   or               ident  = function(args) */
 						cp += 8;
 						/* if the string really exists, make a tag of it */
 						if (vStringLength (name) > 0)
@@ -162,7 +178,7 @@ static void createRTags (void)
 						vStringClear (name);
 						break;
 					}
-					else
+					else if (assignmentType == ASSIGNMENT_ARROW)
 					{
 						/* it's a variable: ident <- value */
 						/* if the string really exists, make a tag of it */
$ cat /tmp/foo.r
test_function_1 = function() {
  print("This function does not appear in tag file.")
}

other_function  <- function() {
  print("This function appears in tag file.")
}
$ ./ctags --quiet --options=NONE -o - /tmp/foo.r 
other_function	/tmp/foo.r	/^other_function  <- function() {$/;"	f
test_function_1	/tmp/foo.r	/^test_function_1 = function() {$/;"	f
```

**Comment by suntzuisafterU** [comment]
@masatake Perfect! Thanks!

**Comment by suntzuisafterU** [comment]
Is this on a branch? I would like to build it today.

**Comment by masatake** [comment]
I will make a pull request.

I have a question. My change expects a keyword "function" comes after "=" like:
```
name = function...
```

Only if the "function" keyword comes, R parser captures "name".
Is this correct expectation? (I don't know R.)

If not, I would like to see more example inputs and expected tags.

**Comment by suntzuisafterU** [comment]
I am new to R, but am working on it. If there is anyone else in the community with a strong background assistance would be appreciated.  

There are definitely more cases to consider.

**Comment by suntzuisafterU** [comment]
Here is a new test file. I have added 2 significant and 1 edge case examples.
1. `x = "new variable" `
This is equivalent to `<-` (in most cases? In the global scope it is, there may be some other semantic I am not aware of)
2. `"Right arrow assignment" -> z`
This is equivalent to `<-` for variables, does not apply to functions (I tried and Rscript didn't like it).
3. `"Special scoping based 'assignment' that should be ignored" ->> i`
This is the edge case. There is also `<<-` but I think the `->>` is more likely to cause issues, since a look ahead is required when identifying right arrow `->` based assignment.

Test file:
```{r}
test_function_1 = function() {
  print("This function was defined with `=`")
}

other_function  <- function() {
  print("This function was defined with `<-`")
}

x = "a new equals based assignment variable"
y <- "a new LEFT arrow based assignment variable"
"a new RIGHT arrow bassed assignment variable" -> z

func_with_named_vars = function(var1=1, var2="default string") {
  cat("var1 = ", var1, " and var2 = ", var2, " are named parameters.\n")
}

closure_func <- function() {
  i <- 0
  function() {
    i <<- "Ignore this scoping based assignment with `<<-`, no new variable here."
    print(i)
    "Also ignore this `->>` based 'assignement', no new variable here" ->> i
    print(i)
  }
}

test_function_1()
other_function()
func_with_named_vars()
func_with_named_vars(var1=9, var2="<user specified string>")
new_func <- closure_func()
new_func()
```

Expected output:
```
# I will edit and add this shortly, have to go.
```

**Comment by suntzuisafterU** [comment]
I have added a lot. I can assist you with implementating this if you would like.

**Comment by masatake** [comment]
I am reimplementing R parser in token-oriented way.
At the first glance, I assume it is not hard.
However, it does not.

```
f <- function (x, y) {
  x
} + y

f (1, 3)
```
Rscript accepts this. 

```
f <- function (x, y) {
  x
} + y + (z <- 3)

print(z)
```
This is not accepted. So `z` is in the scope of f.

```
f <- function (x, y) {
  x + z
} + y + (z <- 3)
```
This is accepted. However,

```

```f <- function (x, y) {
  x + z
} + y + (z <- 3)

f(1,2)
```
this triggers an error.


```

**Comment by suntzuisafterU** [comment]
This is interesting.

The only thing that I can think of causing this is lazy evaluation.  The z in `(z <- 3)`
is never accessible. Instead R allows the function  to be created and when executed looks into the global scope for z.

```
f <- function(x, y) {
  x + z
} + y

z = 3

f(1,2)
```

This works. 

All R functions inherit outer scope variables by name similar to lambdas in C++.

**Comment by masatake** [comment]
I made a pull request based on the version under development.
It takes more time for merging. However, I would like to you to try the version.

**Comment by suntzuisafterU** [comment]
Sounds good!  I will try this shortly.

**Comment by suntzuisafterU** [comment]
I will have to try this at work tomorrow.  I'll let you know how it goes.

**Comment by suntzuisafterU** [comment]
I had some trouble building this at home, so will test it at work, hopefully tomorrow.

**Comment by masatake** [comment]
I refined the pull request. Though it is not perfect, it is better than the original R parser. So I will merge my pull request. Feel free to open a new issue.

Let's see how it is improved:
```
$ cat /tmp/foo.r
test_function_1 = function() {
  print("This function was defined with `=`")
}

other_function  <- function() {
  print("This function was defined with `<-`")
}

x = "a new equals based assignment variable"
y <- "a new LEFT arrow based assignment variable"
"a new RIGHT arrow bassed assignment variable" -> z

func_with_named_vars = function(var1=1, var2="default string") {
  cat("var1 = ", var1, " and var2 = ", var2, " are named parameters.\n")
}

closure_func <- function() {
  i <- 0
  function() {
    i <<- "Ignore this scoping based assignment with `<<-`, no new variable here."
    print(i)
    "Also ignore this `->>` based 'assignement', no new variable here" ->> i
    print(i)
  }
}

test_function_1()
other_function()
func_with_named_vars()
func_with_named_vars(var1=9, var2="<user specified string>")
new_func <- closure_func()

$ u-ctags -o - /tmp/foo.r
closure_func	/tmp/foo.r	/^closure_func <- function() {$/;"	f	language:R
func_with_named_vars	/tmp/foo.r	/^func_with_named_vars = function(var1=1, var2="default string") {$/;"	f	language:R
i	/tmp/foo.r	/^  i <- 0$/;"	v	language:R	function:closure_func
new_func	/tmp/foo.r	/^new_func <- closure_func()$/;"	g	language:R
other_function	/tmp/foo.r	/^other_function  <- function() {$/;"	f	language:R
test_function_1	/tmp/foo.r	/^test_function_1 = function() {$/;"	f	language:R
x	/tmp/foo.r	/^x = "a new equals based assignment variable"$/;"	g	language:R
y	/tmp/foo.r	/^y <- "a new LEFT arrow based assignment variable"$/;"	g	language:R
z	/tmp/foo.r	/^"a new RIGHT arrow bassed assignment variable" -> z$/;"	g	language:R
```

**Comment by suntzuisafterU** [comment]
Thanks!  Sorry I did not get back to you.  Things were hectic.  I will likely use this for a project within the next month, and if there are any more areas for improvement I will open a new issue.

@masatake I appreciate the efforts.  Writing library code for R is quite painful at times and this will find use.

**Comment by masatake** [comment]
Thank you for response.
I'm happy that you are in healthy.

I think the new R parser works well in many cases. If you find I missed something important, https://github.com/universal-ctags/ctags/issues/2533 is the place for reporting.

**Comment by suntzuisafterU** [comment]
Will do.  Thanks again.

**Comment by suntzuisafterU** [comment]
The new R parser works with the vim tagbar plugin, which is very nice indeed.

**Comment by masatake** [comment]
Thank you for trying. I'm happy to hear the result of your evaluation!
