### ISSUE TITLE
Is there an option to load file with defined macro like cpp.hint?

### ISSUE THREAD

**Issue by chongchai** [universal-ctags/ctags#2396]
I find ctags can use `-D` to support preprocessor macros as follows: 
```
ctags.exe --output-format=json -D IGNORE_THIS --langmap=c:+.inc --fields=+ne -o -  D:/code/test.c
```
But if the `test.c`  has multiple  preprocessor macros, it will be difficult to write all the macros in the command line with `-D`.

Is there an option to load file with defined macro like [cpp.hint](https://docs.microsoft.com/zh-cn/cpp/build/reference/hint-files?view=vs-2019)

**Comment by masatake** [comment]
ctags loads a file specified with --options option.

```
$ cat foo.ctags
-D FOO
-D BAR
-D BAZ
$ u-ctags --options foo.ctags -r .
```

I explained more interesting technique in #2356.

**Comment by chongchai** [comment]
> ctags loads a file specified with --options option.

@masatake Thank you!  that's exactly what I need.
