### ISSUE TITLE
Can't extract functions from an OpenSSL file (while exuberant-ctags extracts them correctly)

### ISSUE THREAD

**Issue by 3droj7** [universal-ctags/ctags#2398]
The command line you used to run ctags:

```
ctags -f - -x --langmap=c++:.c ./v3_utl.c
```

The content of input file:

```C
...
STACK_OF(OPENSSL_STRING) *X509_get1_email(X509 *x)
{
    GENERAL_NAMES *gens;
    STACK_OF(OPENSSL_STRING) *ret;

    gens = X509_get_ext_d2i(x, NID_subject_alt_name, NULL, NULL);
    ret = get_email(X509_get_subject_name(x), gens);
    sk_GENERAL_NAME_pop_free(gens, GENERAL_NAME_free);
    return ret;
}
...
```

The tags output you are not satisfied with:

```
STACK_OF         function    525 ./v3_utl.c       STACK_OF(OPENSSL_STRING) *X509_get1_email(X509 *x)
```

The tags output you expect:

```
X509_get1_email  function    525 ./v3_utl.c       STACK_OF(OPENSSL_STRING) *X509_get1_email(X509 *x)
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(a3c87ab), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  6 2020, 14:03:50
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +packcc
```

How do you get ctags binary:

Building it locally

When using Exuberant Ctags 5.9~svn20110310, it actually extracts all of those functions.
This is the file -
https://github.com/openssl/openssl/blob/OpenSSL_1_0_1u/crypto/x509v3/v3_utl.c

**Comment by masatake** [comment]
Try to use the following command line:
```
ctags -f - -x --langmap=c++:.c -D'STACK_OF(T)=T'  ./v3_utl.c
```

**Comment by 3droj7** [comment]
The "-D'STACK_OF(T)=T'" option made it work and I've also noticed that using the "ctags -f - -x --languages=+OldC++ --langmap=OldC++:.c  ./v3_utl.c"  works as well.. 
So, I'll probably start using the OldC++ because I don't need to manually insert the macros.

**Comment by masatake** [comment]
I see. 
We don't maintain OldC and OldC++ parsers.
