### ISSUE TITLE
[Question] Extending for a custom language: how to refer to only the previous tag in stack using only option file?

### ISSUE THREAD

**Issue by SabbathHex** [universal-ctags/ctags#2400]
Hi!

I am trying to extend ctags to support confluencewiki format ([official doc](https://confluence.atlassian.com/doc/confluence-wiki-markup-251003035.html#ConfluenceWikiMarkup-Links)). The initial support that I want to do is for ctags to properly generate the tags for headers in table of contents style.

Example file:

```
h1. Chapter 1
h2. Subchapter 1.1
h3. Subsubchapter 1.1.1
h2. Subchapter 1.2
h3. Subsubchapter 1.2.1
h3. Subsubchapter 1.2.2
h1. Chapter 2
h2. Subchapter 2.1
```
The chapter names are not necessarily those, they are just for illustration. h1, h2, h3 represent the level of headers just like in html.

The desired output of `ctags -f - --format=2 --excmd=pattern --extras= --fields=nksaSmt b.cfw2          `(trying to make it work with tagbar):

```
Chapter 1       b.cfw2  /^h1. Chapter 1$/;"     1       line:1
Chapter 2       b.cfw2  /^h1. Chapter 2$/;"     1       line:7
Subchapter 1.1  b.cfw2  /^h2. Subchapter 1.1$/;"        2       line:2  h1header:Chapter 1
Subchapter 1.2  b.cfw2  /^h2. Subchapter 1.2$/;"        2       line:4  h1header:Chapter 1
Subchapter 2.1  b.cfw2  /^h2. Subchapter 2.1$/;"        2       line:8  h1header:Chapter 2
Subsubchapter 1.1.1     b.cfw2  /^h3. Subsubchapter 1.1.1$/;"   3       line:3  h2header:Subchapter 1.1
Subsubchapter 1.2.1     b.cfw2  /^h3. Subsubchapter 1.2.1$/;"   3       line:5  h2header:Subchapter 1.2
Subsubchapter 1.2.2     b.cfw2  /^h3. Subsubchapter 1.2.2$/;"   3       line:6  h2header:Subchapter 1.2
```

So far I have only managed to get 2-level structure, putting the h2 on the same level as h3, below h1:

```
--regex-cfw2=/^h1\.(.*)/\1/1/{scope=set}
--regex-cfw2=/^h2\.(.*)/\1/2/{scope=ref}
--regex-cfw2=/^h3\.(.*)/\1/3/{scope=ref}
```

I know that the desired output is possible (python parser as an example with its nested functions, or markdown2ctags shows example of this in pythin), but the question is - **can this be done just through option file**? 

Using a combination of `push`, `pop` and `placeholder` only got me to the point where the "topmost" list of tags got populated with:

```
h1header:Chapter 1
h1header:Chapter 2
h2header:Chapter 1.Subchapter 1
...
```

Version:
```
ctags --version
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 29 2019, 18:08:44
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +sandbox, +packcc
```

**Comment by masatake** [comment]
See https://docs.ctags.io/en/latest/optlib.html#advanced-pattern-matching-with-multiple-regex-tables .

```
[jet@living]~/var/ctags% cat /tmp/cfw2.ctags 
cat /tmp/cfw2.ctags 
--langdef=Cfw2
--map-Cfw2=+.cfw2
--_scopesep-Cfw2=*/*:"

--kinddef-Cfw2=o,h1,level one header
--kinddef-Cfw2=t,h2,level two header
--kinddef-Cfw2=T,h3,level three header
--kinddef-Cfw2=f,h4,level four header
# F is reserved by ctags.
--kinddef-Cfw2=i,h5,level five header
--kinddef-Cfw2=s,h6,level six header

--_tabledef-Cfw2=main
--_tabledef-Cfw2=skip
--_tabledef-Cfw2=h1
--_tabledef-Cfw2=h2
--_tabledef-Cfw2=h3
--_tabledef-Cfw2=h4
--_tabledef-Cfw2=h5
--_tabledef-Cfw2=h6


--_mtable-regex-Cfw2=skip/^[^h\n][^\n]+[\n]//
--_mtable-regex-Cfw2=skip/[\n]+//

--_mtable-extend-Cfw2=main+skip
--_mtable-regex-Cfw2=main/^h1\.[ \t]*([^\n]+)/\1/o/{scope=push}{tenter=h1}

--_mtable-extend-Cfw2=h1+skip
--_mtable-regex-Cfw2=h1/^h2\.[ \t]*([^\n]+)/\1/t/{scope=push}{tenter=h2}
--_mtable-regex-Cfw2=h1/^h1\.[ \t]*([^\n]+)//{scope=pop}{tleave}{_advanceTo=0start}

--_mtable-extend-Cfw2=h2+skip
--_mtable-regex-Cfw2=h2/^h3\.[ \t]*([^\n]+)/\1/T/{scope=push}{tenter=h3}
--_mtable-regex-Cfw2=h2/^h[12]\.[ \t]*([^\n]+)//{scope=pop}{tleave}{_advanceTo=0start}

--_mtable-extend-Cfw2=h3+skip
--_mtable-regex-Cfw2=h3/^h4\.[ \t]*([^\n]+)/\1/f/{scope=push}{tenter=h4}
--_mtable-regex-Cfw2=h3/^h[123]\.[ \t]*([^\n]+)//{scope=pop}{tleave}{_advanceTo=0start}

--_mtable-extend-Cfw2=h4+skip
--_mtable-regex-Cfw2=h4/^h5\.[ \t]*([^\n]+)/\1/i/{scope=push}{tenter=h5}
--_mtable-regex-Cfw2=h4/^h[1234]\.[ \t]*([^\n]+)//{scope=pop}{tleave}{_advanceTo=0start}

--_mtable-extend-Cfw2=h5+skip
--_mtable-regex-Cfw2=h5/^h6\.[ \t]*([^\n]+)/\1/s/{scope=push}{tenter=h6}
--_mtable-regex-Cfw2=h5/^h[12345]\.[ \t]*([^\n]+)//{scope=pop}{tleave}{_advanceTo=0start}

--_mtable-extend-Cfw2=h6+skip
--_mtable-regex-Cfw2=h6/^h[123456]\.[ \t]*([^\n]+)//{scope=pop}{tleave}{_advanceTo=0start}

[jet@living]~/var/ctags% cat /tmp/input.cfw2 
cat /tmp/input.cfw2 
h1. Chapter 1
h2. Subchapter 1.1
h3. Subsubchapter 1.1.1
h2. Subchapter 1.2
h3. Subsubchapter 1.2.1
h3. Subsubchapter 1.2.2
h1. Chapter 2
h2. Subchapter 2.1
[jet@living]~/var/ctags% ./ctags --sort=no -o - --options=/tmp/cfw2.ctags --fields=+K /tmp/input.cfw2 
./ctags --sort=no -o - --options=/tmp/cfw2.ctags --fields=+K /tmp/input.cfw2 
Chapter 1	/tmp/input.cfw2	/^h1. Chapter 1$/;"	h1
Subchapter 1.1	/tmp/input.cfw2	/^h2. Subchapter 1.1$/;"	h2	h1:Chapter 1
Subsubchapter 1.1.1	/tmp/input.cfw2	/^h3. Subsubchapter 1.1.1$/;"	h3	h2:Chapter 1"Subchapter 1.1
Subchapter 1.2	/tmp/input.cfw2	/^h2. Subchapter 1.2$/;"	h2	h1:Chapter 1
Subsubchapter 1.2.1	/tmp/input.cfw2	/^h3. Subsubchapter 1.2.1$/;"	h3	h2:Chapter 1"Subchapter 1.2
Subsubchapter 1.2.2	/tmp/input.cfw2	/^h3. Subsubchapter 1.2.2$/;"	h3	h2:Chapter 1"Subchapter 1.2
Chapter 2	/tmp/input.cfw2	/^h1. Chapter 2$/;"	h1
Subchapter 2.1	/tmp/input.cfw2	/^h2. Subchapter 2.1$/;"	h2	h1:Chapter 2
[jet@living]~/var/ctags% 
```
Full qufalified representation is used in the scope fields.
`"`" is used as separator. If you don't want the representation, open a new issue; we have to add a new option for it.

**Comment by masatake** [comment]
MY TODO: a language flag {FQInScope=no} may be needed.

**Comment by SabbathHex** [comment]
Masatake-san,

Thank you very much for your reply. Your options file combined with the following config for tagbar works wonderfully:

    let g:tagbar_type_confluencewiki = {
            \ 'ctagstype' : 'confluencewiki',
            \ 'ctagsbin' : '/usr/bin/ctags',
            \ 'ctagsargs' : '--sort=no -o - --options=/tmp/confluencewiki.ctags --fields=nksaSmt',
            \ 'kinds' : [
                \ 'o:h1:level one header',
                \ 't:h2:level two header',
                \ 'T:h3:level three header',
                \ 'f:h4:level four header',
                \ 'i:h5:level five header',
                \ 's:h6:level six header',
            \ ],
            \ 'sro' : '"',
            \ 'kind2scope' : {
                \ 'o': 'h1',
                \ 't': 'h2',
                \ 'T': 'h3',
                \ 'f': 'h4',
                \ 'i': 'h5',
                \ 's': 'h6',
            \ }
            \}

![image](https://user-images.githubusercontent.com/9886026/72836430-76afe080-3c41-11ea-9d82-3a36bfcaf03e.png)

I will submit a separate issue for customizing the separator so that it could be some symbol that is very unlikely to be used in a text header, like markdown2ctags's suggested chevron `»`.

**Comment by masatake** [comment]
I would like to understand "separator" you wrote.

Do you mean strings used in scope fields?

It can be customizable. I used '"' in the comment with following option.

```
--_scopesep-Cfw2=*/*:"
```

You can change it to:
```
--_scopesep-Cfw2=*/*:»
```

**Comment by SabbathHex** [comment]
Thank you, I understand now. I will need to review that link more properly.

**Comment by masatake** [comment]
As far as seeing the screenshot, the new option FQInScope is not needed.
