### ISSUE TITLE
C References?

### ISSUE THREAD

**Issue by brho** [universal-ctags/ctags#2404]
hi - 

what's the latest with references in C files to external variables and functions?  

i am using GNU global with it set up to use universal-ctags.  it stopped working recently, perhaps with an update.  i straced it and tried to see how gtags was calling ctags.  i realized i couldn't get ctags to spit out references either.  i built older versions of ctags and wasn't able to make it work either, in the off chance it was a recent change.  

does ctags support generating References other than #include headers?  if not, i'm a little curious how my setup worked at all!  perhaps i had old GTAGS/GRTAGS from before i was using ctags, and global just updated those as best it could for the months i was using gtags+ctags.

*****

The name of the parser: C

The command line you used to run ctags:

```
$ ctags --options=NONE -x --_xformat="%R %-16N %4n %-16F %C" --extras=+r --fields=+r hello.c
```

The content of input file:

```C
#include <stdio.h>

int main(int argc, char **argv)
{
	printf("Hello world from program %s!!\n", argv[0]);
	return 0;
}

```

The tags output you are not satisfied with:

```
D main                3 hello.c          int main(int argc, char **argv)
R stdio.h             1 hello.c          #include <stdio.h>
```

The tags output you expect:

```
Would have liked an R tag for the call to printf.
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(0c4369ec0ffd), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan 24 2020, 12:07:34
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc

```

How do you get ctags binary:

(
built from source
)

**Comment by masatake** [comment]
> does ctags support generating References other than #include headers? 

No. (Not yet)

>  if not, i'm a little curious how my setup worked at all!

AFAK, gtags has a built-in C parser.
