### ISSUE TITLE
Need option: --excmd=combine-matching to keep only matching part of pattern

### ISSUE THREAD

**Issue by amerlyq** [universal-ctags/ctags#2407]
I have extensive cross-reference between large number of mixed docs and source code in different languages. Each reference hash (together with its prefix) is almost globally unique expression, and most likely it always unique inside each file.
Therefore I don't need whole matching line inside pattern -- to reduce tags file size, but I would like to keep pattern nevertheless, to not regenerate tags each time I move lines around in docs.
Moreover, with short unique pattern I will be able to jump directly to it, instead of random/last-known place inside whole matched line.

The command line you used to run ctags:
```bash
ctags --options=NONE -o xtref.tags --recurse --input-encoding=UTF-8 --output-encoding=UTF-8 --langdef=
xtref --map-xtref='(*)' --kinddef-xtref=a,anchor,place --kinddef-xtref=r,reference,jump --regex-xtref=
'/(⌇\S{5,})\s?/\1/a/' --regex-xtref='/(※\S{5,})\s?/\1/r/' --languages=xtref --excmd=combine --exclude=
'.git' --exclude='_build*' --exclude='tags' --exclude='*.tags'
```

The content of input file:
```
REF: git-notes Documentation ⌇9cTnu
```

The tags output you are not satisfied with:
```
⌇9cTnu	tools/git-notes.nou	4;/^REF: Git - git-notes Documentation ⌇9cTnu$/;"	a
```

The tags output you expect:
```
⌇9cTnu	tools/git-notes.nou	4;/⌇9cTnu/;"	a
```

The version of ctags:
```
Universal Ctags 0.0.0(a3c87ab5), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  7 2020, 22:54:55
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
```

How do you get ctags binary: 
* ArchLinux pacman

**Comment by masatake** [comment]
ctags has no perfect way to solve your issue.
I recommend you to use text processors like sed modifying tags as you want after running ctags.

Here is an example how to use xformat:
```
[yamato@slave]~/var/ctags-github% cat /tmp/input.cc                                                                                         
int foo (void)
{
}

int foo (int n)
{
}
[yamato@slave]~/var/ctags-github% u-ctags -x --_xformat='%{name}        %{input};       %{line};/^%{name}/;"       %k' /tmp/input.cc        
foo	/tmp/input.cc;	1;/^foo/;"       f
foo	/tmp/input.cc;	5;/^foo/;"       f
``` 

The output of `-x` option can be customized with `--_xformat option`.
See http://docs.ctags.io/en/latest/news.html#customizing-xref-output for more detail.

The current implementation of `--_xformat` doesn't solve your issue perfectly
because the output can be broken as tags format if a name includes '/'.

```
============================
Introduction of POSIX 
============================


/ as a file name separator
----------------------------


[yamato@slave]~/var/ctags-github% u-ctags -x --_xformat='%{name}        %{input};       %{line};/^%{name}/;"       %k' /tmp/input.rst 
/ as a file name separator	/tmp/input.rst;	6;/^/ as a file name separator/;"       s
Introduction of POSIX 	/tmp/input.rst;	2;/^Introduction of POSIX /;"       c
```

If you want to use `--_xformat` in you "extensive cross-reference", I think I can introduce `%{nameAsPattern}`. With `%{nameAsPattern}`, ctags will be able to make output like:
```
% u-ctags -x --_xformat='%{name}        %{input};       %{line};/^%{nameAsPattern}/;"       %k' /tmp/input.rst 
/ as a file name separator	/tmp/input.rst;	6;/^\/ as a file name separator/;"       s
Introduction of POSIX 	/tmp/input.rst;	2;/^Introduction of POSIX /;"       c
```

I expect implementing `%{nameAsPattern}` is not so hard for me.

**Comment by amerlyq** [comment]
Thanks, appending your (slightly tweaked) suggestions to my command did the trick:
```
... + " --output-format=xref --_xformat='%{name}\t%{input}\t%{line};/%{name}/;\"\t%k'"
```
But yes, literally we have two drawbacks here:
1) I would suggest using some suffix as notion of regex escaping `%{name:r}` -- like ZSH or Perl or now even Python did, to support any field in any position. Similar to conventional `q=double-quote`. But easily implementable `%{nameEscaped}` will do likewise.
2) When redirected to file, we won't have header, and I'm not 100% sure about sorted order (for efficient jumping) -- because this new format being customly tailored isn't `u-tags` compatible, despite able to be opened through nvim. Any way to easily generate header in one pass together with command above?

**Comment by masatake** [comment]
I have more offering. (To show the ourput of following example, I used ctags with **TWO** extra patches.)

--pattern-length-limit accepted a positive integer.
One of the patches extends it to take a negative integer.
It truncates the input line to build a pattern. If a positive integer is given, ctags truncates from the head of input line. If a negative integer is given, the patched ctags truncates from tail.
 
Whether the patches are useful or not.

```
[jet@localhost]~/var/ctags% cat input.html
cat input.html
<html>
  <head>
    <title>How to write a ctags parser for your favorite language</title>
  </head>
  <body>
    <!-- 37 --><h1>Understanding basic concepts in ctags</h1>
    <!-- 17 --><h2>Parser activation</h2>
    <!-- 43 --><h3>file name extensions and file name patterns</h3>
    <!--  8 --><h3>Modeline</h3>
    <!--  7 --><h3>Scoring</h3>
    <!--  4 --><h2>Kind</h2>
    <!--  5 --><h2>Field</h2>
    <!--  6 --><h2>Extras</h2>
    <!-- 11 --> <h2>Psuedo tags</h2>
    <h1></h1>
  </body>
</html>
[jet@localhost]~/var/ctags%  ./ctags -o -  input.html
 ./ctags -o -  input.html
Extras	input.html	/^    <!--  6 --><h2>Extras</;"	i
Field	input.html	/^    <!--  5 --><h2>Field</;"	i
Kind	input.html	/^    <!--  4 --><h2>Kind</;"	i
Modeline	input.html	/^    <!--  8 --><h3>Modeline</;"	j
Parser activation	input.html	/^    <!-- 17 --><h2>Parser activation</;"	i
Psuedo tags	input.html	/^    <!-- 11 --> <h2>Psuedo tags</;"	i
Scoring	input.html	/^    <!--  7 --><h3>Scoring</;"	j
Understanding basic concepts in ctags	input.html	/^    <!-- 37 --><h1>Understanding basic concepts in ctags</;"	h
file name extensions and file name patterns	input.html	/^    <!-- 43 --><h3>file name extensions and file name patterns</;"	j
[jet@localhost]~/var/ctags%  ./ctags -o - --pattern-length-limit=10 input.html
 ./ctags -o - --pattern-length-limit=10 input.html
Extras	input.html	/^    <!--  /;"	i
Field	input.html	/^    <!--  /;"	i
Kind	input.html	/^    <!--  /;"	i
Modeline	input.html	/^    <!--  /;"	j
Parser activation	input.html	/^    <!-- 1/;"	i
Psuedo tags	input.html	/^    <!-- 1/;"	i
Scoring	input.html	/^    <!--  /;"	j
Understanding basic concepts in ctags	input.html	/^    <!-- 3/;"	h
file name extensions and file name patterns	input.html	/^    <!-- 4/;"	j
[jet@localhost]~/var/ctags%  ./ctags -o - --pattern-length-limit=-10 input.html
 ./ctags -o - --pattern-length-limit=-10 input.html
Extras	input.html	/h2>Extras</;"	i
Field	input.html	/<h2>Field</;"	i
Kind	input.html	/><h2>Kind</;"	i
Modeline	input.html	/>Modeline</;"	j
Parser activation	input.html	/ctivation</;"	i
Psuedo tags	input.html	/uedo tags</;"	i
Scoring	input.html	/3>Scoring</;"	j
Understanding basic concepts in ctags	input.html	/ in ctags</;"	h
file name extensions and file name patterns	input.html	/ patterns</;"	j
[jet@localhost]~/var/ctags% 
```

**Comment by amerlyq** [comment]
I can assume the patch on negative `pattern-length-limit` has a strong point of implementation simplicity, does it?

It trades off some expected intuitivity (e.g. my suggestion on `pattern-only` with user-guaranteed uniqueness is easier to reason about). But it provides nice option to have when the only user concern is `tags` file size and he is ready to bear the consequences of non-unique patterns.

**Comment by masatake** [comment]
After thinking, I find both your idea (matching-only) and my idea (limiting the length of pattern from tail) doesn't fit the minor area of ctags.

Do you know latex?

See the following .ctags:

```
--langdef=latex
--langmap=latex:.tex .latex
--regex-latex=/^\\part[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/PART \2/s,part/
```
(Taken from https://git.mehalter.com/mehalter/dotfiles/src/commit/6573629cbc084765fc3da564f93b44993fad2b18/documents/Documents/latex/templates/.ctags)

With this .ctags, ctags emit following output:
```
[jet@localhost]~/var/ctags% cat /tmp/foo.tex 
\part{The history of ctags implementation}
[jet@localhost]~/var/ctags% ./ctags -o - --langdef=latex --langmap='latex:.tex.latex' '--regex-latex=/^\\part[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/PART \2/s,part/' /tmp/foo.tex 
PART The history of ctags implementation	/tmp/foo.tex	/^\\part{The history of ctags implementation}$/;"	s
```

The regex pattern is for picking up 'part' of the file.
The ctags option for latex prepends "PART " to the string captured by regex pattern when emitting.
This is a well-known technique is ctags usage.

What happens if we have --excmd=matching-only?
(Imaginary terminal output)
```
PART The history of ctags implementation	/tmp/foo.tex	/^PART The history of ctags implementation$/;"	s
``` 

From the tags output, your editor cannot find the line. The pattern never appears in the input source file.
An ideal implementation may emit like:
```
PART The history of ctags implementation	/tmp/foo.tex	/^The history of ctags implementation$/;"	s
```

For parsers written in `--regex-<LANG>=..`, we can focus on `\1`, `\2`,... appeared in the option.
Maybe hard but we can make ctags emit patterns really appearing in input files.

However, parsers not written in `--regex-<LANG>=` also emit such crafted tags entry.
```
[jet@localhost]~/var/ctags% cat /tmp/foo.cpp
cat /tmp/foo.cpp
// Taking from http://kaitei.net/cpp/operators/
#include <iostream>

class Point
{
public:
    int x;
    int y;
    Point(int x, int y) : x(x), y(y) { }
    Point operator /* NOISE */+(const Point&rhs);
};
[jet@localhost]~/var/ctags% gcc /tmp/foo.cpp -c
gcc /tmp/foo.cpp -c
[jet@localhost]~/var/ctags% ./ctags -o - --kinds-C++=+p /tmp/foo.cpp
./ctags -o - --kinds-C++=+p /tmp/foo.cpp
Point	/tmp/foo.cpp	/^    Point(/;"	f	class:Point	file:
Point	/tmp/foo.cpp	/^class Point$/;"	c	file:
operator +	/tmp/foo.cpp	/^    Point operator \/* NOISE *\/+(const Point&rhs);$/;"	p	class:Point	typeref:typename:Point	file:
x	/tmp/foo.cpp	/^    int x;/;"	m	class:Point	typeref:typename:int	file:
y	/tmp/foo.cpp	/^    int y;/;"	m	class:Point	typeref:typename:int	file:
```
Look at `operator+`. It is impossible to implement useful --exmd=matching-only without 
modifiying parsers.

**Comment by amerlyq** [comment]
Ah, yes, you have a point for mixed lang.
I usually generate three different `tags` files -- for source code, for html/rst documentation and now for unique cross-refs. Therefore I had no problem with cmdline-wide effects of limiting patterns.

If we wish to truly limit patterns only for some specific `--regex-<LANG>` but generate single `tags` file for all languages -- then providing `\0, \1, \2` is really the only way to go. 

But  at least your suggestion on `--_xformat` and using 3 separate db will do the work for me until then.
