### ISSUE TITLE
Jumping to unanchored regex don't change column position of cursor

### ISSUE THREAD

**Issue by amerlyq** [universal-ctags/ctags#2409]
(In continuation of #2407)

Do you know if `vim/nvim` has some arbitrary treating of regexes from tags file?
When I removed line-ends anchors for regex `/⌇9cTnu/`, and used `:tag ⌇9cTnu` in vim -- it has jumped to correct line, but hasn't changed current cursor column to regex position :(

It's easy to understand, after all vim must only verify that regex is *matching the line* when we tag-jump, not move to that match each time. Especially considering by default tags format matches *whole line only* and any jump would result in always moving cursor to the beginning of line, which would be immesurably irritating. Therefore it keeps absolute column to whatever it was before jump.

BUT! if we mess with lines in file to invalidate tags line numbers, then **first** (and only first) jump will use regex to find tag and correctly moves cursor column on matched position. But it seems vim caches that new tag position line number (w/o column) and don't use regex ever again on next jump to and froth.
 
Are you aware of any discussion going on somewhere on the topic of tag-jumping behavior?
P.S. I understand this question is most likely to garner attention at nvim issue tracker (and I will do that!) but I hope you have more rich context of the problem.

**Comment by masatake** [comment]
Sorry to be late. However, it seems that you are talking about an issue of a client tool like vim side.
