### ISSUE TITLE
C++: Problem with nested templates

### ISSUE THREAD

**Issue by andrejlevkovitch** [universal-ctags/ctags#2433]
The name of the parser: `ctags`

The command line you used to run ctags:

```
$ ctags --options=NONE main.cpp
```

The content of input file:

```c++
template <typename T> struct TestStruct {};

template <typename T> struct TemplateParameterStruct {};

struct ParameterStruct {};

template <> struct TestStruct<ParameterStruct> {};

template <typename P> struct TestStruct<TemplateParameterStruct<P>> {};
```

The tags output you are not satisfied with:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/f4904b13/
ParameterStruct	main.cpp	/^struct ParameterStruct {};$/;"	s	file:
TemplateParameterStruct	main.cpp	/^template <typename T> struct TemplateParameterStruct {};$/;"	s	file:
TestStruct	main.cpp	/^template <> struct TestStruct<ParameterStruct> {};$/;"	s	file:
TestStruct	main.cpp	/^template <typename T> struct TestStruct {};$/;"	s	file:
```

The tags output you expect:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/f4904b13/
ParameterStruct	main.cpp	/^struct ParameterStruct {};$/;"	s	file:
TemplateParameterStruct	main.cpp	/^template <typename T> struct TemplateParameterStruct {};$/;"	s	file:
TestStruct	main.cpp	/^template <> struct TestStruct<ParameterStruct> {};$/;"	s	file:
TestStruct	main.cpp	/^template <typename P> struct TestStruct<TemplateParameterStruct<P> \/**\/> {};$/;"	s	file:
TestStruct	main.cpp	/^template <typename T> struct TestStruct {};$/;"	s	file:
```

The version of ctags:

```
Universal Ctags 0.0.0(f4904b13), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec  9 2019, 18:17:13
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +packcc
```

How do you get ctags binary:
build locally from source (branch `master` from `github`)

Problem, I think, is in dublicate template brackets `>>` which interprets as operator `>>`. If I set space between template brackets `> >` then all works fine.

**Comment by masatake** [comment]
@pragmaware, I'm extending cork queue to support per file symbol table.

https://github.com/universal-ctags/ctags/pull/2427/commits/c4d5064b6f97a57b7b32b7b31df7b69844880415

This one is applied to systemverilog parser.

```
template <typename P> struct TestStruct<TemplateParameterStruct<P>> {};
```

When parsing '<P>>', c++ parser cannot decide whether ">" is part of ">>" shift operator or the end side pair for '<'. However, if we can give a hint that P is a type to c++ parser, c++ parser can throw away the possibility of shift operator.

Am I correct?

In #2427, I introduced only top-level symbol table.
However, fixing this issue, I guess we have to introduce symbol table for each scope.
Currently the symbol table is implemented in hashtable. I would like to introduce rbtree.
I"m looking for good implementation now.

**Comment by masatake** [comment]
...I found c++ parser dosedn't use cork for scope management.

**Comment by masatake** [comment]
Surprisingly, the bug is nothing to do with '>>' shift operator.
I have tried to fix #2435. The real fix may be provided by our parser maintainer for C/C++.

**Comment by pragmaware** [comment]
Surprisingly the termination condition for a template ending with >> was missing.

**Comment by andrejlevkovitch** [comment]
> Surprisingly the termination condition for a template ending with >> was missing.

I think it caused because before `c++11` standard template can not finish by `>>`. Compilers interpreted it as `operator >>`. After `11` standard c++ template can finish on unlimited count `>`. For example:

```c++
std::list<std::vector<std::map<int, std::string>>> listOfVectorOfMap;
```
