### ISSUE TITLE
Can ctags analyze file with user defined parser

### ISSUE THREAD

**Issue by chongchai** [universal-ctags/ctags#2463]
For example, if I have a `.ph` file with c++ code and want to analyze it with c++ parser, can ctags support?

Although writing c/c++ code in `.ph` file is a bad practice, I need it for some reason.

I try to use this command, but it get wrong answer.
```
ctags  --output-format=json --langmap=c:+.inc.def --kinds-c=+plz --fields=+ne -o - test.ph
```

**Comment by chongchai** [comment]
I find it with command
```
ctags  --output-format=json --langmap=c:+.inc.def.ph --kinds-c=+plz --fields=+ne -o - test.ph
```

**Comment by masatake** [comment]
It is for C langnageu. If you want to choose C++ language, the command line should be:

```
ctags  --output-format=json --langmap=C++:+.inc.def.ph --kinds-C++=+plz ...
```
