### ISSUE TITLE
Some problems of readtags options

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2471]
## About `-l`

The usage given by `readtags -h` is :

```
readtags [-ilp] [-n] [-Q EXP] [-s[0|1]] [-t file] [-] [name(s)]
```

But if I do:

``` console
$ readtags -l -Q '(eq? "citre" $name)' -t ./tags
```

then all the tags are listed. However, if I follow the examples given in the [doc](https://docs.ctags.io/en/latest/news.html#examples-of-filter-expressions), and put `-l` at last:

``` console
$ readtags -Q '(eq? "citre" $name)' -t ./tags -l
```

It gives the wanted lines.

Also, `readtags -h` says `-l` list all tags, and `-Q EXP` filters the result, so my understanding is we put `-l` first to list the tags, then followed by `-Q` to filter it. Why this doesn't work?

## About `-e` and `-n`

If I do:

``` console
$ readtags -Q '(prefix? "Concepts" $name)' -t ./tags -le
```

the output is:

```
Concepts        README.md       /^# Concepts$/
```

But with:

```
$ readtags -Q '(prefix? "Concepts" $name)' -t ./tags -el
```

I get the extension fields:

```
Concepts        README.md       /^# Concepts$/;"        kind:chapter
```

Similar things happen to `-n`. My understanding is they are like "switches" and affect `-l` that comes later. But I feel the help message is not clear about this.

## About `-i`

`-i` "performs case-insensitive matching", but it only works when name is given directly, like

``` console
$ readtags -i ./tags Citre
```

This is not enough. It should make `eq?`, `prefix?`, `suffix?` and `substr?`case insensitive, or at least (maybe better) we should have case-insensitive versions of these functions. It's needed for client tools.

## About other arguments

- `-p` "performs partial matching". But from my experiment I think it should be "prefix matching".

**Comment by masatake** [comment]
What we have to do are

- revise  the code,
- improve -h output,
- add readtags(1) man page, and
- add more test cases to Tmain.

When improving readtags, I wonder how seriously we have to think about compatibility.
On Fedora, ctags package doesn't include readtags command.
In Exuberant-ctags, install target of Makefile installs only ctags command and its man page.
So I guess readtags command is not so popular.

**Comment by masatake** [comment]
I didn't check the actual behaviour of readtags. I just revise the help message:
```
Find tag file entries matching specified names.

Usage: 
    ./readtags -h
        Print this help message.
    ./readtags [OPTIONS] ACTION
        Do the specified action.
Actions:
    -l
        List regular tags
    [-] name...
        List regular tags matching the name
        "-" indicates arguments after this as NAME even if they start with -.
    -D
        List pseudo tags
Options:
    -d           Turn on debugging output.
    -e           Include extension fields in output.
    -i           Perform case-insensitive matching.
    -n           Allow print line numbers if -e option is given.
    -p           Perform partial matching.
    -t file      Use specified tag file (default: "tags").
    -s[0|1|2]    Override sort detection of tag file.
    -Q EXP       Filter the result with EXP.

Note that options are acted upon as encountered, so order is significant.
...
```
I introduced the concept "ACTION".
As far as reading the source code, ACTIONS can be specified more than one. For avoiding the confusion, I don't writ about it in the help message. I think even in readtags(1), I don't have to write about it.

**Comment by masatake** [comment]
Is it better to make a pull request to get comments from you?

**Comment by masatake** [comment]
About -p, the result you reported is reproduced here even with readtags of Exuberant-crags.
So I think it is not a bug of code. It is a bug of the help message.
Thank you for reporting.

**Comment by masatake** [comment]
All options don't affect the evaluation of -Q EXP. I should write it in the help message.

**Comment by masatake** [comment]
The behaviour of -n option is very subtle.
ctags stores line numbers to a tags file in two different ways: address field or line field.

```
[yamato@slave ctags-github]$ ./ctags -o - -n main/main.c | grep batch
./ctags -o - -n main/main.c | grep batch
batchMakeTags	main/main.c	335;"	f	language:C	typeref:typename:void	file:
[yamato@slave ctags-github]$ ./ctags -o - --fields=+n main/main.c | grep batch
./ctags -o - --fields=+n main/main.c | grep batch
batchMakeTags	main/main.c	/^static void batchMakeTags (cookedArgs *args, void *user CTAGS_ATTR_UNUSED)$/;"	f	line:335	language:C	typeref:typename:void	file:
```

At least, test cases should verify these aspects.

**Comment by AmaiKinono** [comment]
> I wonder how seriously we have to think about compatibility.

I think the parts I'm concerned about shouldn't break compatibility. I want:

1. readtags to output the whole lines (with extra fields and line number). I don't care about the particular order of the arguments, as long as I can get the whole lines somehow.

2. Case insensitive versions of `eq?`, `prefix?`, `suffix?` and `substr?`. Maybe we could use optional argument instead, like 

``` lisp
(eq? "ctags" "Ctags") -> #f
(eq? "ctags" "Ctags" 'case-insensitive) -> #t
```

> I just revise the help message:

> I introduced the concept "ACTION".

This is much better than the original help message, clears most of my confusion.

> `-Q EXP        Filter the result with EXP.`

We should be precise about what is the "result". Maybe just using "filter the tags" is better.

> As far as reading the source code, ACTIONS can be specified more than one.

Yes, I confirmed that. And I found options actually affect all actions come after it, not just the one following it, which is a bit unconvenient since we can't turn off an option. But that's not a big deal since we should just need one action most of the time, and we can always run readtags twice if we need more actions.

> Is it better to make a pull request to get comments from you?

I think yes. If you need to make a PR anyway, why not now :D
