### ISSUE TITLE
can I get the end line of prototype in C/C++?

### ISSUE THREAD

**Issue by chongchai** [universal-ctags/ctags#2474]
I want to get the end line of  `computeLen` and `foo` in the following code:
```
extern int computeLen(int number,
                      int size,
                      int width);
class Shape 
{
   public:
      void setWidth(int w)
      {
         width = w;
      }
      void foo(int h, int w,
                int g, int k);
   protected:
      int width;
};
```
I use command ` ctags --output-format=json --langmap=c:+.inc.def.ph --kinds-c=+plz --fields=+nie -o - test.cpp` to analyze and get the start line of `computeLen` and `foo`. But I still want to get the end line of them.
Is there any option I can use to get end line info? Or can you add end line information for the prototype kind symbol?

**Comment by masatake** [comment]
We don't provide it.
Implementing it may not be hard. @pragmaware, do you have any comments?

BTW, @chongchai. if possible, I would like to know how you use the end fields of prototypes?

**Comment by chongchai** [comment]
@masatake Actually I want to get  every parameter's scope for prototypes.
Currently  using ctags I can get prototype's start line and get no parameter information.
If get end line, I may caculate parameter's scope with some other text analysis.

If you can provide the parameter information for prototypes, that will be a great help. 
Providing end line for prototypes also helps a lot.

**Comment by masatake** [comment]
How about following output? Isn't it not enough?

```
[jet@living]~/var/ctags% cat /tmp/foo.h
cat /tmp/foo.h
int
main(
     int
     argc,
     char
     **argv)
{
  return 0;
}
[jet@living]~/var/ctags% ./ctags --language-force=C --kinds-C='*' --fields=+Ss -o - /tmp/foo.h
./ctags --language-force=C --kinds-C='*' --fields=+Ss -o - /tmp/foo.h
argc	/tmp/foo.h	/^     argc,$/;"	z	function:main	typeref:typename:int	file:
argv	/tmp/foo.h	/^     **argv)$/;"	z	function:main	typeref:typename:char **	file:
main	/tmp/foo.h	/^main($/;"	f	typeref:typename:int	signature:(int argc,char ** argv)
```

I use --language-force=C because .h is for C++.

**Comment by chongchai** [comment]
`main` function in your example is function not prototype.
But what I want is to get the parameter scope for prototype.

**Comment by masatake** [comment]
> main function in your example is function not prototype.

Oh, sorry. I took mistake.
```
[yamato@slave]~/var/ctags-github% cat /tmp/foo.h
cat /tmp/foo.h

int
main(
     int
     argc,
     char
     **argv)
  ;
[yamato@slave]~/var/ctags-github% ./ctags -o - --language-force=C --kinds-C=+p --fields=+S /tmp/foo.h
./ctags -o - --language-force=C --kinds-C=+p --fields=+S /tmp/foo.h
main	/tmp/foo.h	/^main($/;"	p	language:C	typeref:typename:int	signature:(int argc,char ** argv)
```

From the signature field of main, you can know there are two parameters: argc, and argv.
It scope is main.

Is this not enough?

**Comment by masatake** [comment]
Even if you know the end line of the prototype, you may have to do text processing to retrieve the parameters. Enve with the command line I show in above comment, you may have to parse the signature field. However, I think the command line can reduce your code a bit.

There are more offering:
```
[yamato@slave]~/var/ctags-github% git diff
git diff
diff --git a/parsers/cxx/cxx_parser.c b/parsers/cxx/cxx_parser.c
index 2373e24b..781a329e 100644
--- a/parsers/cxx/cxx_parser.c
+++ b/parsers/cxx/cxx_parser.c
@@ -1446,6 +1446,7 @@ void cxxParserAnalyzeOtherStatement(void)
 	enum CXXScopeType eScopeType = cxxScopeGetType();
 
 	CXXFunctionSignatureInfo oInfo;
+	CXXTypedVariableSet oParamInfo;
 
 	// kinda looks like a function or variable instantiation... maybe
 	if(eScopeType == CXXScopeTypeFunction)
@@ -1471,8 +1472,7 @@ void cxxParserAnalyzeOtherStatement(void)
 
 	// prefer function.
 check_function_signature:
-
-	if(cxxParserLookForFunctionSignature(g_cxx.pTokenChain,&oInfo,NULL))
+	if(cxxParserLookForFunctionSignature(g_cxx.pTokenChain,&oInfo, &oParamInfo))
 	{
 		CXX_DEBUG_PRINT("Found function prototype");
 
@@ -1486,6 +1486,8 @@ check_function_signature:
 			CXX_DEBUG_PRINT("But it has been preceded by the 'friend' keyword: this is not a real prototype");
 		} else {
 			int iScopesPushed = cxxParserEmitFunctionTags(&oInfo,CXXTagKindPROTOTYPE,CXXEmitFunctionTagsPushScopes,NULL);
+			if(cxxTagKindEnabled(CXXTagKindPROTOTYPE) && cxxTagKindEnabled(CXXTagKindPARAMETER))
+				cxxParserEmitFunctionParameterTags(&oParamInfo);
 			while(iScopesPushed > 0)
 			{
 				cxxScopePop();
[yamato@slave]~/var/ctags-github% make -j 9
make -j 9
REPOINFO   main/repoinfo.h
make  all-am
make[1]: Entering directory '/home/yamato/var/ctags-github'
REPOINFO   main/repoinfo.h
  CC       parsers/cxx/libctags_a-cxx_parser.o
  AR       libctags.a
  CCLD     ctags
  CCLD     mini-geany
make[1]: Leaving directory '/home/yamato/var/ctags-github'
[yamato@slave]~/var/ctags-github% ./ctags -o - --language-force=C --kinds-C=+pz --fields=+S /tmp/foo.h
./ctags -o - --language-force=C --kinds-C=+pz --fields=+S /tmp/foo.h
argc	/tmp/foo.h	/^     argc,$/;"	z	language:C	function:main	typeref:typename:int	file:
argv	/tmp/foo.h	/^     **argv)$/;"	z	language:C	function:main	typeref:typename:char **	file:
main	/tmp/foo.h	/^main($/;"	p	language:C	typeref:typename:int	signature:(int argc,char ** argv)
```
With the patch, ctags can list the parameters in the signature of the prototype.
(This patch is not perfect because the scope kind of parameters are wrong. "function" are printed. It should be "prototype".) However, I'm a bit negative introducing this patch. ctags captures names of definitions. I wonder the parameter in the signature in the prototype is a definition? I'm not sure.  
We have extended ctags to capture reference tags.  I wonder the parameter in the signature in the prototype is a reference? I'm not sure. I wonder how we deal with it in ctags.

**Comment by chongchai** [comment]
Thank you for your kindly reply. It really helps me a lot. 

This is my scenario:
Currently I have many parameters and prototypes. For every parameter I have its' line and name information. For every prototype I have its' start line and name info.
I want to know every prototype's parameter.

So my initial purpose is to use ctags to get the end line for prototype. then I can check parameter's scope from line info.

**Comment by masatake** [comment]
I'm not good at English. So I would like to confirm again and again.

> This is my scenario:
> Currently I have many parameters and prototypes. For every parameter I have its' line and name information. For every prototype I have its' start line and name info.
I want to know every prototype's parameter.

Is the signature field not enough for the purpose?
I guess your answer is one of:
A. enough. By analyzing the value of the signature field, I can know individual parameters.
B. not enough but better than before. I would like to avoid analyzing in my tool. I expect ctags does instead of my tool.
C. no. the signature field doesn't help me. What I need is the end field.
D. the other.

I would like to know what is the scope of the parameter.
```
int main (int argc);
```

In this prototype, args is the prototype. args's scope is main.
Am I correct?
If your answer is yes, the tags output:
```
main ... signature:(int argc)
```
looks enough for the purpose.
From the output, you can know there is a parameter, argc. And it is part of main.
Am I wrong?

**Comment by chongchai** [comment]
@masatake My fault for bad description. Thank you for your patience.

> Is the signature field not enough for the purpose?
> I guess your answer is one of:
> A. enough. By analyzing the value of the signature field, I can know individual parameters.
> B. not enough but better than before. I would like to avoid analyzing in my tool. I expect ctags does instead of my tool.
> C. no. the signature field doesn't help me. What I need is the end field.
> D. the other.

I think answer is C. the signature field doesn't help me. What I need is the end field.

<hr>

An detailed example:  

```
int main (int argc,                              //  line 10
              char* argv[]);                     //  line 11

void test(int argc,                             //line 13
               char* argv[]);                    // line 14
```

I get information from current ctags and my internal data source:
```
main   prototype  line 10
argc    line 10
argv    line 11 
test     prototype  line 13
argc    line 13
argv    line 14
```

I want to know whether `argc at line 10` and `argv at line 11` belongs to `main`.
So offering only signature without end line of `main`, I don't know which `argv` belongs to `main`. 

I think these two options may solve my problem:
a. Offering the end line of prototype
b. Offering the paramter and paramter's line of prototype

**Comment by masatake** [comment]
> a. Offering the end line of prototype

I implement this one in #2479.

```
[jet@living]~/var/ctags% ./ctags --fields=+e --kinds-C++=p -o - ./input.h
main	./input.h	/^main$/;"	p	typeref:typename:int	end:8
[jet@living]~/var/ctags% cat -n input.h                                  
     1	int
     2	main
     3	(
     4		int
     5		argc,
     6		char **
     7		argv
     8		);
[jet@living]~/var/ctags% ./ctags --fields=+e --kinds-C++=p -o - ./input.h
main	./input.h	/^main$/;"	p	typeref:typename:int	end:8
```
