### ISSUE TITLE
Ruby: deal with mixin?

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2476]
I don't know what's the exact output I want, but I have some ideas.

Let me explain a bit about mixin in Ruby (however keep in mind I am also new to Ruby). Mixin is a mechanism to "mix" a module into a class. It's done using one of 3 methods: include, prepend and extend.

Let's define a module first:

``` ruby
module X
  def hi
    p "Calling 'hi' in X."
  end
end
```

Include `X` in `A` will make `hi` an instance method of `A`, and `X` will be inserted to the ancestor chain of `A` (just before `A` itself, so methods defined in `A` can override it):

``` ruby
class A
  include X
  def hi
    p "Calling 'hi' in A."
  end
end

a = A.new
a.hi
# => "Calling 'hi' in A."
# A.hi will throw an error.
A.ancestors
=> [A, X, Object, Kernel, BasicObject]
```

Prepend `X` in `B` will make `hi` an instance method of `B`, and `X` will be inserted to the ancestor chain of `B` (after `B` itself, so its methods overrides the ones defined in `B`):

``` ruby
class B
  prepend X
  def hi
    p "Calling 'hi' in B."
  end
end

b = B.new
b.hi
# => "Calling 'hi' in X."
# B.hi will throw an error.
B.ancestors
=> [X, B, Object, Kernel, BasicObject]
```

Extend `X` in `C` will make `hi` a class method of `C` (seems it won't override class methods defined in `C`), and doesn't affect the ancestor chain:

``` ruby
class C
  extend X
  def hi
    p "Calling 'hi' in C."
  end
end

c = C.new
c.hi
# => "Calling 'hi' in C."
C.hi
# => "Calling 'hi' in X."
C.ancestors
# => [C, Object, Kernel, BasicObject]
```

It seems modules can also include variables and classes, but I'm not familiar with that and don't know if it will affect the mixin.

My main concern is to make auto-completion (based on class information) and jumping to definition work. My thoughts are:

- For `A`: generate tags for methods in the module `X` again, but only when they are not overrided by instance methods defined in the class. Their scope should be `class:A`, and line numbers should point to definitions in `X`.

- For `B`: generate tags for methods in the module `X` again, and remove the tags for overrided instance methods in `B`. Their scope should be `class:B`, and line numbers should point to definitions in `X`.

- For `C`: generate tags for methods in the module `X` again, but only when they are not overrided by class methods defined in `C`. Their scope should be `class:C`, and line numbers should point to definitions in `X`.

This may require multi-pass parsing ability.

**Comment by masatake** [comment]
It seems that mixin is done dynamically:
```
class D
  if condition then
     extend Y
  end
end
```
I wonder how we should do. What the parer can do is assuming "condition" is true.

About mixin, I think introducing "mixin:" Ruby specific field is better.

The ideal tags fileI image for the input 
```
A ... class ... mixin:include:X roles:def
X ... module ...mixedIn:clsas:A roles:included
B ... class ... mixin:prepend:X roles:def
X ... module ...mixedIn:clsas:B roles:prepended
C ... class ... mixin:extend:X roldes:def
X ... module ...mixedIn:clsas:C roles:extended
```

**Comment by masatake** [comment]
Can include, prepend, and extend take other than a module name?

**Comment by AmaiKinono** [comment]
> What the parser can do is assuming "condition" is true.

I think this is actually good, since if it's put in an condition statement, then one may also don't know if it's mixed before running it.

> I think introducing "mixin:" Ruby specific field is better.

Yeah, definitely better. I don't know if mixin is a ruby specific thing (so much to learn about OOP), but if other languages also do it, we should have this for them too to make the logic generic and consistent for a client tool.

> Can include, prepend, and extend take other than a module name?

Looked it up in https://ruby-doc.org/core-2.7.0/ ([`include`](https://ruby-doc.org/core-2.7.0/Module.html#method-i-include), [`extend`](https://ruby-doc.org/core-2.7.0/Object.html#method-i-extend), [`prepend`](https://ruby-doc.org/core-2.7.0/Module.html#method-i-prepend)). They all take one or more modules. There are other `prepend`s but they are class/instance methods of Array/Strings.

**Comment by masatake** [comment]
>>    I think introducing "mixin:" Ruby specific field is better.

> Yeah, definitely better. I don't know if mixin is a ruby specific thing (so much to learn about OOP), but if other languages also do it, we should have this for them too to make the logic generic and consistent for a client tool.

I would like to keep the tagEntryInfo data structure small. So I will add the field as a Ruby parser specific field. 

>  Looked it up in https://ruby-doc.org/core-2.7.0/ (include, extend, prepend). They all take one or more modules. There are other prepends but they are class/instance methods of Array/Strings.

Thanks. How do you think about adding the new code for mixin by yourself? I will make a pull request for "mixin:include". You can extend my change in the pull for supporting "extend" and "prepend".
If you know the internal of Ruby parser, you can do as you want. 

The Ruby parser is not so complicated. So extending it is not so hard.
(However, you cannot add rich features to the current code base.)

Just invitation. I will improve Ruby parser anyway. However, I cannot say when.

**Comment by masatake** [comment]
Before trying to solve this issue, we have to study how ripper-tags deals with mixin.

**Comment by AmaiKinono** [comment]
> I would like to keep the tagEntryInfo data structure small. So I will add the field as a Ruby parser specific field.

Well, I think it's the same if in the future we add that field also as "specific field" for other languages that have mixin.

> How do you think about adding the new code for mixin by yourself? I will make a pull request for "mixin:include". You can extend my change in the pull for supporting "extend" and "prepend".

I would like to! However keep in mind I basically know nothing about C, so no promise here.

> Before trying to solve this issue, we have to study how ripper-tags deals with mixin.

Didn't know this tool before. Let me have a look at it.

**Comment by masatake** [comment]
>> I would like to keep the tagEntryInfo data structure small. So I will add the field as a Ruby parser specific field.

> Well, I think it's the same if in the future we add that field also as "specific field" for other languages that have mixin.

No. The language common fields are allocated statically in the data structure.
However, the language (parser) specific structure allocated on demand.
See https://github.com/universal-ctags/ctags/blob/master/main/entry.h#L109 .

.... I have just found I can remove usedParserFields.



>>    How do you think about adding the new code for mixin by yourself? I will make a pull requ>>est for "mixin:include". You can extend my change in the pull for supporting "extend" and "prepend".

> I would like to! However keep in mind I basically know nothing about C, so no promise here.

o.k.

I also look into ripper-tags before coding.

**Comment by AmaiKinono** [comment]
> No. The language common fields are allocated statically in the data structure.

I didn't make it clear. I am thinking in a perspective from a client tool. I think they will be the same for a client tool (since anyway it's just a field that appears in a tags file) except that readtags may not be able to use that field.

**Comment by masatake** [comment]
Oh, I see. You are correct.
(I"m writing about ctags side. What we call tagEntryInfo in ctags is tagEntry in readtags.)

I tried ripper-tags.
```
[root@f7024c2837af /]# cat foo.rb
module X
  def hi
    p "Calling 'hi' in X."
  end
end

class A
  include X
  def hi
    p "Calling 'hi' in A."
  end
end

[root@f7024c2837af /]# ripper-tags -f - foo.rb 
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
A	foo.rb	/^class A$/;"	c
X	foo.rb	/^module X$/;"	m
hi	foo.rb	/^  def hi$/;"	f	class:A
hi	foo.rb	/^  def hi$/;"	f	class:X
```

It sees that it doesn't do nothing special for mixin.
So, we can do as we want:-).

**Comment by masatake** [comment]
I think newly introduced mixin field provides enugh information to implement interesting features in client sides.
