### ISSUE TITLE
C++: std::make_pair not found

### ISSUE THREAD

**Issue by gituser042** [universal-ctags/ctags#2534]
Hi,

just trying to create a tags file for libstdc++. Looks like the std::make_pair function is not found when running ctags on stl_pair.h.

The command line you used to run ctags:

ctags --languages=c++ --langmap=c++:+.tcc. --c++-kinds=+p --fields=+iaS --extras=+q -I "_GLIBCXX_NOEXCEPT _GLIBCXX_USE_NOEXCEPT _GLIBCXX_NOTHROW _GLIBCXX_USE_CONSTEXPR _GLIBCXX_BEGIN_NAMESPACE_CONTAINER _GLIBCXX_END_NAMESPACE_CONTAINER _GLIBCXX_CONSTEXPR _GLIBCXX_NAMESPACE_LDBL _GLIBCXX_BEGIN_NAMESPACE_VERSION _GLIBCXX_END_NAMESPACE_VERSION _GLIBCXX_VISIBILITY+" /usr/include/c++/8/bits/stl_pair.h

The version of ctags:
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May  7 2020, 08:50:04
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc

Trying to find the problem, I think one of the code parts ctags has problem with is:

```c++
using _PCCP = _PCC<true, _T1, _T2>;

      template<typename _U1 = _T1, typename _U2=_T2, typename
	       enable_if<_PCCP::template
			   _ConstructiblePair<_U1, _U2>()
	                 && _PCCP::template
			   _ImplicitlyConvertiblePair<_U1, _U2>(),
                         bool>::type=true>
      constexpr pair(const _T1& __a, const _T2& __b)
      : first(__a), second(__b) { }

       template<typename _U1 = _T1, typename _U2=_T2, typename
		enable_if<_PCCP::template
			    _ConstructiblePair<_U1, _U2>()
	                  && !_PCCP::template
			    _ImplicitlyConvertiblePair<_U1, _U2>(),
                         bool>::type=false>
      explicit constexpr pair(const _T1& __a, const _T2& __b)
      : first(__a), second(__b) { }
```

**Comment by masatake** [comment]
> Trying to find the problem, I think one of the code parts ctags has problem with is:

The parts are still too large for me to understand the issue.
Could you tell me the problem in more details?
(I know only very basic C++.)

The maintainer of C++ parser is absent the days. So we need your help to fix the issue (if I can).

**Comment by gituser042** [comment]
This is the original source code of the file:
https://pastebin.com/Y35ZKc6i
This is the modified code:
https://pastebin.com/wwHXkvVi

As you can see, at the end of the file there is a "make_pair" function. This function is in the std namespace so what I would expect is to have a std::make_pair tag.
I just deleted some lines of the file (see modified code link) to check if ctags has problems with the make_pair function itself. So it turns out when I remove some of those templates e.g.:
```c++
template<typename _U1 = _T1, typename _U2=_T2, typename
	       enable_if<_PCCP::template
			   _ConstructiblePair<_U1, _U2>()
	                 && _PCCP::template
			   _ImplicitlyConvertiblePair<_U1, _U2>(),
                         bool>::type=true>
      constexpr pair(const _T1& __a, const _T2& __b)
      : first(__a), second(__b) { }
```

ctags finds the function:
```
make_pair	stl_pair_modified.h	/^    make_pair(_T1 __x, _T2 __y)$/;"	f	namespace:std	typeref:typename:pair<_T1,_T2>	signature:(_T1 __x,_T2 __y)
make_pair	stl_pair_modified.h	/^    make_pair(_T1&& __x, _T2&& __y)$/;"	f	namespace:std	typeref:typename:pair<typename __decay_and_strip<_T1>::__type,typename __decay_and_strip<_T2>::__type>	signature:(_T1 && __x,_T2 && __y)
std::make_pair	stl_pair_modified.h	/^    make_pair(_T1 __x, _T2 __y)$/;"	f	namespace:std	typeref:typename:pair<_T1,_T2>	signature:(_T1 __x,_T2 __y)
std::make_pair	stl_pair_modified.h	/^    make_pair(_T1&& __x, _T2&& __y)$/;"	f	namespace:std	typeref:typename:pair<typename __decay_and_strip<_T1>::__type,typename __decay_and_strip<_T2>::__type>	signature:(_T1 && __x,_T2 && __y)
```

So my **guess** (as I did not look into the ctags code) is that ctags may have problems with: `_PCCP::template` ???

**Comment by masatake** [comment]
Thank you for the explanation. However, the modified code is still too long to understand what happens.
I got an interest in the deleted code.

```
template<typename _U1 = _T1, typename _U2=_T2, typename
	       enable_if<_PCCP::template
			   _ConstructiblePair<_U1, _U2>()
	                 && _PCCP::template
			   _ImplicitlyConvertiblePair<_U1, _U2>(),
                         bool>::type=true>
      constexpr pair(const _T1& __a, const _T2& __b)
      : first(__a), second(__b) { }
```
I put the deleted code to foo.hpp. And I run ctags:
```
u-ctags -o - --c++-kinds=+p --fields=+iaS /tmp/f.hpp
```

However, I got nothing though I expected ctags made a tag for `pair`.
How do you think about this?
If you expect the same result as mine, I would like to inspect the deleted code more.

We need more simplified input.

I tried to make the deleted code simpler.
```
template<typename _U1 = _T1, typename _U2=_T2, typename
	       enable_if<_PCCP::template
			   _ConstructiblePair<_U1, _U2>(),
                         bool>::type=true>
      constexpr pair(const _T1& __a, const _T2& __b)
      : first(__a), second(__b) { }
```
Do you think this is valid C++ code?
When I run for the code, ctags still emits nothing.

**Comment by gituser042** [comment]
Well I'm not that much into templates but I wold say your code is valid.
Here is what I come up with (copied from the file):
works:
```c++
template<typename _U1, typename _U2>
	pair(const pair<_U1, _U2>& __p)
	: first(__p.first), second(__p.second) { }
```
works:

```c++
template <typename _U1 = _T1,
          typename _U2 = _T2,
          typename enable_if<__and_<
                               __is_implicitly_default_constructible<_U1>,
                               __is_implicitly_default_constructible<_U2>>
                      ::value, bool>::type = true>
 pair()
 : first(), second() { }
 ```
works NOT:
```c++
template<typename _U1, typename
         enable_if<_PCCP::template
                     _MoveCopyPair<true, _U1, _T2>(),
                   bool>::type=true>
 constexpr pair(_U1&& __x, const _T2& __y)
 : first(std::forward<_U1>(__x)), second(__y) { }
```

So I would say the problem is everything with ```::template```:
```c++
_PCCP::template _MoveCopyPair<true, _U1, _T2>()
_PCCP::template _ConstructiblePair<_U1, _U2>()
_PCCP::template _ImplicitlyConvertiblePair<_U1, _U2>()
_PCCP::template _CopyMovePair<false, _T1, _U2>()
_PCCP::template _MoveConstructiblePair<_U1, _U2>()
_PCCP::template _ImplicitlyMoveConvertiblePair<_U1, _U2>()
_PCCFP<_U1, _U2>::template _ConstructiblePair<_U1, _U2>()
_PCCFP<_U1, _U2>::template _ImplicitlyConvertiblePair<_U1, _U2>()
_PCCFP<_U1, _U2>::template _MoveConstructiblePair<_U1, _U2>()
_PCCFP<_U1, _U2>::template _ImplicitlyMoveConvertiblePair<_U1, _U2>()
```

**Comment by masatake** [comment]
Thank you. The input is much shorter.

works:
```
template<typename _U1, typename
         enable_if<_PCCP::templatex
                     _MoveCopyPair<true, _U1, _T2>(),
                   bool>::type=true>
 constexpr pair(_U1&& __x, const _T2& __y)
 : first(std::forward<_U1>(__x)), second(__y) { }
```
though this may be broken as C++ input.
I replaced "template" with "templatex".

As you wrote `_PCCP::template` leads ctags to wrong way.

The c++ parser of ctags may recognize `template` in `_PCCP::template` as C++ keyword.

> Do you know if ctags just stops if there is something wrong? Still wondering why make_pair is found when I remove some code.

I guess ctags doesn't stop parsing. It parsers but entering unexpected input context.

I will inspect more.

**Comment by pragmaware** [comment]
I have a fix for this. Will commit later tonight.

**Comment by masatake** [comment]
THANK YOU!

**Comment by gituser042** [comment]
With the fix applied. I can see the std::make_par function
```
make_pair	/usr/include/c++/8/bits/stl_pair.h	/^    make_pair(_T1 __x, _T2 __y)$/;"	f	namespace:std	typeref:typename:pair<_T1,_T2>	signature:(_T1 __x,_T2 __y)
make_pair	/usr/include/c++/8/bits/stl_pair.h	/^    make_pair(_T1&& __x, _T2&& __y)$/;"	f	namespace:std	typeref:typename:pair<typename __decay_and_strip<_T1>::__type,typename __decay_and_strip<_T2>::__type>	signature:(_T1 && __x,_T2 && __y)
std::make_pair	/usr/include/c++/8/bits/stl_pair.h	/^    make_pair(_T1 __x, _T2 __y)$/;"	f	namespace:std	typeref:typename:pair<_T1,_T2>	signature:(_T1 __x,_T2 __y)
std::make_pair	/usr/include/c++/8/bits/stl_pair.h	/^    make_pair(_T1&& __x, _T2&& __y)$/;"	f	namespace:std	typeref:typename:pair<typename __decay_and_strip<_T1>::__type,typename __decay_and_strip<_T2>::__type>	signature:(_T1 && __x,_T2 && __y)
```

thx
