### ISSUE TITLE
Question: how to handle name and pattern that contain tabs in client tools?

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2541]
Fields in a tags file are splitted by tabs, but the pattern field may also contain tabs, e.g.:

```
ACCESSERRFMT	OLD/lsof.h	/^#define	ACCESSERRFMT	/;"	kind:macro	line:237
```

If a client tool split the whole line by tabs to get the fields, it will misinterpret the pattern field. What's the right thing to do in this situation?

*Edit:* I found the same problem can also happen to the name field. Suppose we have a `tab.md`:

```
# this	contains	tabs
```

Then

```
$ ctags tab.md
$ readtags -l > output
$ emacs output
```

You'll see tabs appear both in the name and pattern. `readtags -E` could escape tabs in the name, but not in the pattern.

**Comment by masatake** [comment]
man tags(5) explains the format of tags file.
libreadtags is based on tags(5). So its implementation may help you.

About readtags, use -E option:
```
[yamato@slave]~/var/ctags-github% readtags -E -l
readtags -E -l
this\tcontains\ttabs	/tmp/foo.md	/^# this	contains	tabs$/
```

**Comment by AmaiKinono** [comment]
Thanks. That's enough information.
