### ISSUE TITLE
[QUESTION] C: "const" in "properties" field

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2545]
About the variable kind, `const` is not stored to `properties` field. Is this expected behavior?

```
$ cat /tmp/bar.c
cat /tmp/bar.c
const int j;
static int k;
$ ./ctags --fields-C='{properties}' -o - /tmp/bar.c
./ctags --fields-C='{properties}' -o - /tmp/bar.c
j	/tmp/bar.c	/^const int j;$/;"	v	language:C	typeref:typename:const int
k	/tmp/bar.c	/^static int k;$/;"	v	language:C	typeref:typename:int	file:	properties:static
```

This question is inspired by https://github.com/geany/geany/issues/1443 .

**Comment by pragmaware** [comment]
Good question. When applied to variables `const` is considered to be part of the type. For example you can't assign a const pointer to a non const pointer variable without a cast. `static`, instead, is a property related to the variable storage.

However, when applied to functions the meaning of both keywords change. A const member function promises to not modify the internal state of the object. A static member function can be called without an instance pointer. In this case we're talking of properties.

**Comment by pragmaware** [comment]
Thinking of it better... we *could* add the const property for const variables. Though it would be a slight duplication of information as I certainly wouldn't remove the const keyword from the type name.

**Comment by masatake** [comment]
> It's not related to the type.

I see.

> Thinking of it better... we could add the const property for const variables. Though it would be a slight duplication of information as I certainly wouldn't remove the const keyword from the type name.

I would like to see the tags output in your thoughts:
```
const int i;
```
How the output is for above input?

**Comment by pragmaware** [comment]
Well, just
```
i   /tmp/bar.c   /^const int i;$/;"	v   language:C  typeref:typename:const int properties:const
```
However I'm not sure. Const can appear in different positions inside a type name. A pointer can be const or the variable it points to can be const... and it's kind-of a different const.... I'd probably leave it as it is. Cone can always figure out constness by looking at the type.

**Comment by masatake** [comment]
Oh, I see. Thank you for replying.

**Comment by masatake** [comment]
I must add this conversation to ctags-parser-cxx.7 man page.
