### ISSUE TITLE
Readtags: handle missing fields in sorter expressions

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2547]
Some fields are not presented in every tag entry. When do sorting based on them, errors will occur:

``` console
$ cd ~/lsof
$ ctags --fields='*' --pseudo_tags='*' -R

# Notice "end:" is not presented in every tags
$ readtags -S '(<> $end &end)' -l > /dev/null
GOT ERROR in SORITING: number-required: <>
...
```
I think we could return 0 in `<>` as long as an argument is `#f`.

**Comment by masatake** [comment]
Yes. This is an expected behaviour.
The data types of the arugments for `<>` must be the same.

```
(<> (or $end $line) (or $end &line))
```
may help you.

Surprisingly, I wrote the rule in the help message of -H sorter:
```
             <>: (<> a b) -> -1|0|1; compare a b. The types of a and b must be the same.
```

**Comment by AmaiKinono** [comment]
I've read that :D, but the thing is people may compare fields that's not presented in every entry.

**Comment by masatake** [comment]
> I've read that :D, but the thing is people may compare fields that's not presented in every entry.

If the field doesn't exist, `$...` and `&...` values are #f. Therefore `or` can be used.

**Comment by AmaiKinono** [comment]
Well, I was actually thinking what if people only want to sort based on the `end:` field, but now I find it actually doesn't make sense to do so.

Feel free to close this issue.

**Comment by AmaiKinono** [comment]
I also notice that although the error occurs, the exit status is still 0. Is this a bug?
