### ISSUE TITLE
Cxx: any way to get the end line of a variable in macro definition

### ISSUE THREAD

**Issue by Lennon925** [universal-ctags/ctags#2558]
Hi I have some code like following:

#define Max_Box_Num  {
    {JOB1, JOB1, 0, 0, JOB1}, {JOB1, JOB1, 0, 0, JOB1},
    {JOB1, JOB1, 0, 0, JOB1}, {JOB1, JOB1, 0, 0, JOB1},
    {JOB1, JOB1, 0, 0, JOB1},
};

Any way to get Max_Box_Num this macro start line and end line? Maybe this issue is similar with #2454

**Comment by masatake** [comment]
It seems that the code is invalid; backslashes at the end of lines are missing. 

```
$ cat foo.h
#define Max_Box_Num { \
{JOB1, JOB1, 0, 0, JOB1}, {JOB1, JOB1, 0, 0, JOB1}, \
{JOB1, JOB1, 0, 0, JOB1}, {JOB1, JOB1, 0, 0, JOB1}, \
{JOB1, JOB1, 0, 0, JOB1}, \
};
$ u-ctags --fields=+ne -o - /tmp/foo.h
Max_Box_Num	/tmp/foo.h	/^#define Max_Box_Num /;"	d	line:1	language:C++	end:5

```

**Comment by Lennon925** [comment]
Thanks~
