### ISSUE TITLE
no tag created for filename when filetype is not recognised. (and running in etags mode)

### ISSUE THREAD

**Issue by koenmeersman** [universal-ctags/ctags#2566]
We noted that ctags is not generating tags on filenames when running in emacs compatibilty mode, and the type of the file is unkown.

Is there a switch to generate for filename-tag for all files given to ctags ? 

*****

The name of the parser:  ? not parser related ? 

The command line you used to run ctags:

```

    touch file_of_unkown_type
    echo file_of_unkown_type | ctags --output-format=etags -L -  && cat TAGS

```

The content of input file:

```
file_of_unkown_type is empty file.
```

The tags output you are not satisfied with:

```
TAGS file is empty

mea@dhws009> ls -l
ls -l
total 0
-rw-r--r--. 1 mea softdev 0 Jun  8 17:19 TAGS
-rw-r--r--. 1 mea softdev 0 Jun  8 17:14 file_of_unkown_type
mea@dhws009> 
```

The tags output you expect:
(gnerated by calling ls * | etags - && cat TAGS)
```
file_of_unkown_type,0
```

The version of ctags:

```
Universal Ctags 1e37c1328a-20200414, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May  4 2020, 01:42:44
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +packcc
```

Version of etags: 

```
etags (GNU Emacs 26.3)
Copyright (C) 2019 Free Software Foundation, Inc.
This program is distributed under the terms in ETAGS.README
```

**Comment by masatake** [comment]
There is no option for the purpose. However, for more than two years, I have thought about this option. It is a good time to implement it. This is not the issue of TAGS output.

Currently ctags processes input files listed in its command line as mutually independent entities.
I think we can improve the quality of parsing if we can consider the relation between input files.
For considering the relation between input files, ctags must recognize the concept "source tree".

How can we represent the "source tree" in ctags?
I'm not sure, but I have two ideas about how to represent a file of which filetype is not recognized in a tags file:

* introducing special language called "unknown":
```
foo.unknown	/tmp/foo.unknown	1;"	kind:file	line:1	language:unknown
```
This tag will be captured only if you give "--language=+unknown" to the ctags command line.

* introducing special language called "filesystem":
```
foo.unknown /tmp/foo.unknown	1;"	kind:unknownFile	line:1	language:filesystem
```
This tag will be captured only if you give "--language=+filesystem" to the ctags command line.

Implementing is the "unknown" language is easy.
However, the "filesystem" is much extensible and may bring us more interesting things.
e.g., The filesystem language can record the existence of a directory like:
```
src /home/yamato/mytool/src	1;"	kind:directory	language:filesystem
```
We can do more:
```
Makefile /home/yamato/mytool/src/Makefile	1;"	kind:buildScript	language:filesystem
```

Maybe there is no contradiction nor conflict between two ideas. So I will implement "unknown" language first, and add a code turning on "--languages=+unknown" automatically when a user gives --output-format=etags. This will be a good study for implementing the "filesystem" language in the future.
