### ISSUE TITLE
Ignore CREATE EXTENSION syntax in SQL

### ISSUE THREAD

**Issue by nobrick** [universal-ctags/ctags#2580]
Sometimes we use [`CREATE EXTENSION`](https://www.postgresql.org/docs/12/sql-createextension.html) to load some module functions in a SQL file, but the parser generates empty tags as long as a file contains this keyword.

This is postgres-specific and may not be a standard syntax. However, any SQL file could contain some dialect keywords related to its specific DB system specs. IMO a better solution would be to ignore parsing `CREATE EXTENSION` and continue parsing the rest instead of outputting no tags at all.

*****
```sh
ctags --options=NONE example.sql
```

The content of input file:

```SQL
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA public;

CREATE TABLE public.foo (
    id bigserial PRIMARY KEY,
);
```

The tags output you are not satisfied with (**Empty when `CREATE EXTENSION` is present**):

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_FILESEP	slash	/slash or backslash/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PATTERN_LENGTH_LIMIT	96	/0 for no limit/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/62f0144/
```

The tags output you expect (**Works when `CREATE EXTENSION` is removed**):

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_FILESEP	slash	/slash or backslash/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PATTERN_LENGTH_LIMIT	96	/0 for no limit/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/62f0144/
foo	t.sql	/^CREATE TABLE public.foo ($/;"	t
id	t.sql	/^    id bigserial PRIMARY KEY,$/;"	E	table:foo
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(62f0144), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun 28 2020, 18:30:06
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames, +packcc
```

**Comment by masatake** [comment]
Thank you. I made a fix for this #2581.

> This is postgres-specific and may not be a standard syntax. However, any SQL file could contain some dialect keywords related to its specific DB system specs. 

I would like to hear your idea more.

My understanding:
Any SQL may have its particular "CREATE FOO" syntaxes. The SQL parser of ctags should ignore it if the parser doesn't know how to handle it. This issue reports the case when FOO = EXTENSION. However, EXTENSION is an example.

Do I understand your original message?

#2581 just handles the "EXTENSION" keyword.

**Comment by masatake** [comment]
sqlite has a syntax for loading an extesion. https://stackoverflow.com/questions/6663124/how-to-load-extensions-into-sqlite

**Comment by nobrick** [comment]
Thank you for the update.

> My understanding:
> Any SQL may have its particular "CREATE FOO" syntaxes. The SQL parser of ctags should ignore it if the parser doesn't know how to handle it. This issue reports the case when FOO = EXTENSION. However, EXTENSION is an example.
>
> Do I understand your original message?

Yes, actually handling CREATE EXTENSION is enough for me. But I agree that errors should be ignored when the SQL parser doesn't know what to do with them. Because there are some minor differences in the syntax of SQL's various implementations, it may be common to encounter non-standard syntax. Ignoring errors may be a better approach than outputting no tags at all.

**Comment by masatake** [comment]
I implemented your idea. Pushed the change to #2581.

**Comment by masatake** [comment]
Ignoring FOO in CREATE FOO is harder than I expected. So I will withdraw the code for it.
I will rework on the suggestion when we get more bug reports about CREATE something.

I will rewind the change and I will merge the change only for ignoring CREATE EXTENSION.
