### ISSUE TITLE
Universal Ctags doesn't generate tags for html

### ISSUE THREAD

**Issue by nerdfiles** [universal-ctags/ctags#2592]
Generates tags for all other files: JS, Python, markdown, etc.

```
Universal Ctags 0.0.0(30cd8e0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 17 2020, 14:12:37
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames, +packcc
```

**Comment by masatake** [comment]
It isn't reproduced:
```
[jet@living]~/var/ctags% cat input.html
cat input.html
<html>
  <body>
    <h1>Understanding basic concepts in ctags</h1>
  </body>
</html>
[jet@living]~/var/ctags% ./ctags --quiet --options=NONE -o - input.html
./ctags --quiet --options=NONE -o - input.html
Understanding basic concepts in ctags	input.html	/^    <h1>Understanding basic concepts in ctags<\/h1>$/;"	h
```
What kind of input do you give to ctags? What kind of command line do you use?

**Comment by nerdfiles** [comment]
Hm. Well, I'm trying to use custom Ionic 5 HTML tags, and I also am assuming a `~/.ctags` file to be used in Vim with Tagbar. So it might be that I'm registering this issue in the wrong repository...

**Comment by masatake** [comment]
> So it might be that I'm registering this issue in the wrong repository...
Do you mean I can close this issue?

**Comment by nerdfiles** [comment]
Is the `~/.ctags` file only a vim assumption? As I understand it, it isn't specified in ctags documentation or help. If so, then yes. I suppose it should be closed. 

But would you have a good guess as to where I can figure out how to interact with the `~/.ctags` file?

**Comment by masatake** [comment]
See https://github.com/universal-ctags/ctags#differences about ~/.ctags.d and ~/.ctags.

**Comment by nerdfiles** [comment]
Thanks!
