### ISSUE TITLE
Readtags: sort by tag names in different ways?

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2599]
If we run 

``` console
$ readtags -S '(<> $name &name)' -p - hi
```

then all tags begin with "hi" are sorted by their names. The behavior is to sort by alphabetical order, but when doing auto-completion, it's preferred to sort by the length of the name first, then by alphabetical order.

In other words, when the user types "hi", he wants a completion list like this:

```
hi-zzz
hi-aaa-some-long-thing
```

rather than the opposite.

I'm not sure if this should be implemented by readtags, since if the client tool could query readtags for multiple times, it needs to remove the duplicates and sort them by itself, so it needs to implement a sorting algorithm anyway. Maybe the actual problem is: what's the purpose of the sorter expressions?

**Comment by masatake** [comment]
length operator is added. With that, you can get the result you want with 
```
-S '(<or> (<> (length $name) (length &name)) (<> $name &name))'
```
I wonder the result of the length operator should be cached.

**Comment by AmaiKinono** [comment]
Thanks! The `length` operator is pretty neat.

About caching: I don't know C, but will counting the length of a string be slower than searching that string in a table?
