### ISSUE TITLE
Struct range is wrong

### ISSUE THREAD

**Issue by Lennon925** [universal-ctags/ctags#2602]
ctags version：ctags-2020-07-22_631690ad-x64

Code in test.c as follow:
```
typedef union {
  struct {
#if (BYTE1 == BYTE2) {
    int reserverd : 1;
  }
#else {
      int tx : 1;
    }
  } bits;
} MAC_CONTROL;
```

when using command "ctags.exe --output-format=json --langmap=c:+.inc --fields=+ne -o - D:\test.c" to parse, the results as follow:

{"_type": "tag", "name": "__anonb35aaf65030a", "path": "D:\\test.c", "pattern": "/^typedef union {$/", "file": true, "line": 1, "kind": "union"}
{"_type": "tag", "name": "__anonb35aaf650408", "path": "D:\\test.c", "pattern": "/^  struct {$/", "file": true, "line": 2, "kind": "struct", "scope": "__anonb35aaf65030a", "scopeKind": "union", "end": 5}
{"_type": "tag", "name": "reserverd", "path": "D:\\test.c", "pattern": "/^    int reserverd : 1;$/", "file": true, "line": 4, "typeref": "typename:int:1", "kind": "member", "scope": "__anonb35aaf65030a::__anonb35aaf650408", "scopeKind": "struct", "end": 4}

the struct range is from line 2 to line 5. It’s wrong.

**Comment by masatake** [comment]
The input is invalid as C code:
```
$ gcc -c /tmp/foo.c 2>/dev/null; echo $?
gcc -c /tmp/foo.c 2>/dev/null; echo $?
1
```
ctags is allowed to emit garbages from garbages.

**Comment by Lennon925** [comment]
> The input is invalid as C code:
> 
> ```
> $ gcc -c /tmp/foo.c 2>/dev/null; echo $?
> gcc -c /tmp/foo.c 2>/dev/null; echo $?
> 1
> ```
> 
> ctags is allowed to emit garbages from garbages.

I can't understand the relationship between your reply and my question.

**Comment by k-takata** [comment]
Your code is not a valid C code. (gcc reports error.)
So, ctags cannot parse it.

**Comment by Lennon925** [comment]
> Your code is not a valid C code. (gcc reports error.)
> So, ctags cannot parse it.

I just give an example. It's obvious there are no definitions of BYTE1 and BYTE2

**Comment by k-takata** [comment]
Please provide a valid example. It's obvious that your example is broken.

```shell
$ gcc foo.c
foo.c:3:22: error: token "{" is not valid in preprocessor expressions
    3 | #if (BYTE1 == BYTE2) {
      |                      ^
foo.c:6:7: warning: extra tokens at end of #else directive [-Wendif-labels]
    6 | #else {
      |       ^
foo.c:9:3: warning: no semicolon at end of struct or union
    9 |   } bits;
      |   ^
foo.c:10:1: error: expected identifier or '(' before '}' token
   10 | } MAC_CONTROL;
      | ^
foo.c:10:3: warning: data definition has no type or storage class
   10 | } MAC_CONTROL;
      |   ^~~~~~~~~~~
foo.c:10:3: warning: type defaults to 'int' in declaration of 'MAC_CONTROL' [-Wimplicit-int]
foo.c:3: error: unterminated #else
    3 | #if (BYTE1 == BYTE2) {
      |
```

**Comment by Lennon925** [comment]
> Please provide a valid example. It's obvious that your example is broken.
> 
> ```shell
> $ gcc foo.c
> foo.c:3:22: error: token "{" is not valid in preprocessor expressions
>     3 | #if (BYTE1 == BYTE2) {
>       |                      ^
> foo.c:6:7: warning: extra tokens at end of #else directive [-Wendif-labels]
>     6 | #else {
>       |       ^
> foo.c:9:3: warning: no semicolon at end of struct or union
>     9 |   } bits;
>       |   ^
> foo.c:10:1: error: expected identifier or '(' before '}' token
>    10 | } MAC_CONTROL;
>       | ^
> foo.c:10:3: warning: data definition has no type or storage class
>    10 | } MAC_CONTROL;
>       |   ^~~~~~~~~~~
> foo.c:10:3: warning: type defaults to 'int' in declaration of 'MAC_CONTROL' [-Wimplicit-int]
> foo.c:3: error: unterminated #else
>     3 | #if (BYTE1 == BYTE2) {
>       |
> ```

Sorry，code should be as follow:

`typedef union {
  struct {
#if (BYTE1 == BYTE2) {
    int reserverd : 1;
  }
#else {
      int tx : 1;
    }
#endif
  } bits;
  int u32;
} MAC_CONTROL;`

**Comment by k-takata** [comment]
Still broken.

```c
#if (BYTE1 == BYTE2) {
```

`{` should not exist in this line.
Also the same for `#else {`.

**Comment by masatake** [comment]
Even if the input is valid as a C source file, ctags cannot handle C preprocessor conditions well.
It is a fundamental limitation.
