### ISSUE TITLE
Extra tags for variables in function signatures?

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2604]
From what I've seen, ctags seems to have a standard format for the `signature` field. For example, Here's a file `signature.c`:

``` c
void func_1(int a, int b) {}
void func_2(int    a,   int  b) {}
void func_3 (int a,
             char *b[]) {}
```

Let's test it:

``` console
$ ctags --fields=S -f- signature.c 
func_1  signature.c     /^void func_1(int a, int b) {}$/;"      signature:(int a,int b)
func_2  signature.c     /^void func_2(int    a,   int  b) {}$/;"        signature:(int a,int b)
func_3  signature.c     /^void func_3 (int a,$/;"       signature:(int a,char * b[])
```

I think this means ctags actually understands the structure of the signature, so maybe it's possible to generate extra tags for variables in the signature.

An obvious benefit would be auto-completing the variable names inside the function. In C, if we could also know the variable is some kind of struct, we could even completing its member.

**Comment by masatake** [comment]
`z/parameter` kind of C parser is for the purpose:
```
[jet@living]~/var/ctags% cat /tmp/foo.c
cat /tmp/foo.c
void func_1(int a, int b) {}
void func_2(int    a,   int  b) {}
void func_3 (int a,
             char *b[]) {}
[jet@living]~/var/ctags% ./ctags --kinds-C=+z -o - /tmp/foo.c
./ctags --kinds-C=+z -o - /tmp/foo.c
a	/tmp/foo.c	/^void func_1(int a, int b) {}$/;"	z	function:func_1	typeref:typename:int	file:
a	/tmp/foo.c	/^void func_2(int    a,   int  b) {}$/;"	z	function:func_2	typeref:typename:int	file:
a	/tmp/foo.c	/^void func_3 (int a,$/;"	z	function:func_3	typeref:typename:int	file:
b	/tmp/foo.c	/^             char *b[]) {}$/;"	z	function:func_3	typeref:typename:char * []	file:
b	/tmp/foo.c	/^void func_1(int a, int b) {}$/;"	z	function:func_1	typeref:typename:int	file:
b	/tmp/foo.c	/^void func_2(int    a,   int  b) {}$/;"	z	function:func_2	typeref:typename:int	file:
func_1	/tmp/foo.c	/^void func_1(int a, int b) {}$/;"	f	typeref:typename:void
func_2	/tmp/foo.c	/^void func_2(int    a,   int  b) {}$/;"	f	typeref:typename:void
func_3	/tmp/foo.c	/^void func_3 (int a,$/;"	f	typeref:typename:void
```

--list-kinds=C may help you to know more about C parser:
```
$ ./ctags --list-kinds-full=C
#LETTER NAME       ENABLED REFONLY NROLES MASTER DESCRIPTION
D       macroparam no      no      0      C      parameters inside macro definitions
L       label      no      no      0      C      goto labels
d       macro      yes     no      1      C      macro definitions
e       enumerator yes     no      0      C      enumerators (values inside an enumeration)
f       function   yes     no      0      C      function definitions
g       enum       yes     no      0      C      enumeration names
h       header     yes     yes     2      C      included header files
l       local      no      no      0      C      local variables
m       member     yes     no      0      C      struct, and union members
p       prototype  no      no      0      C      function prototypes
s       struct     yes     no      0      C      structure names
t       typedef    yes     no      0      C      typedefs
u       union      yes     no      0      C      union names
v       variable   yes     no      0      C      variable definitions
x       externvar  no      no      0      C      external and forward variable declarations
z       parameter  no      no      0      C      function parameters inside function definitions
```

**Comment by AmaiKinono** [comment]
Thanks. I thought it should be some kind of extra tags.

Just some random thoughts:

1. Is the `parameter` kind available whenever `signature` is also available? I didn't find a way to inspect whether `signature` is available for a language quickly.
2. I tried this for python. Python now supports [type hint](https://docs.python.org/3/library/typing.html), which makes the signatures look somewhat like in C. Maybe we could use that for the `typeref` field. I don't know if type hint is widely used in the real world, so maybe this is not worth it.

**Comment by masatake** [comment]
> 1. Is the parameter kind available whenever signature is also available? 

No.  Whether and how they are implemented are up to the parser.

> I didn't find a way to inspect whether signature is available for a language quickly.

There is no good way to know that.  

Conceptually, we can provide such information
via --list-kinds-full or by introducing new option `--info-kind-C=`.

A kind fills a field.
e.g. "function" kind fills its "signature" field.

However, for providing such information, we have to inspect all the existing parsers (after
defining API for declaring relations between a kind and fields.)

> 2. I tried this for python. Python now supports type hint, which makes the signatures look somewhat like in C. Maybe we could use that for the typeref field. I don't know if type hint is widely used in the real world, so maybe this is not worth it.

Could you open an issue for this topic?

**Comment by masatake** [comment]
I think all issues reported here are solved.
