### ISSUE TITLE
Python: generate typeref field for z/parameter tags based on type hint

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2606]
The idea is originally posted in https://github.com/universal-ctags/ctags/issues/2604#issuecomment-666991827.

Since 3.5, Python supports [type hint](https://docs.python.org/3/library/typing.html). An example would be:

``` python
def func(a: str, b: Callable[[int, int], T]) -> T:
    pass
```

This defines a function `func`, its parameter `a` is a string, `b` is a function that eats 2 integers and return a value of type T. `func` also returns a value of type T.

If we generate `z/parameter` tags for this file:

``` console
$ ctags  --kinds-python=+z -f- signature.py
a       signature.py    /^def func(a: str, b: Callable[[int, int], T]) -> T:$/;"        z       function:func   file:
b       signature.py    /^def func(a: str, b: Callable[[int, int], T]) -> T:$/;"        z       function:func   file:
func    signature.py    /^def func(a: str, b: Callable[[int, int], T]) -> T:$/;"        f
```

The `z/parameter` tags have correct names, but the `typeref` field is missing, which could be referred based on the type hint:

```
a       signature.py    /^def func(a: str, b: Callable[[int, int], T]) -> T:$/;"        z       function:func   typeref:typename:str	file:
b       signature.py    /^def func(a: str, b: Callable[[int, int], T]) -> T:$/;"        z       function:func   typeref:typename:Callable[[int, int], T] file:
func    signature.py    /^def func(a: str, b: Callable[[int, int], T]) -> T:$/;"        f
```

I don't know whether this is a good example of expected output, since I'm not sure what's the best way to deal with generic type variables. Maybe the behavior on C++ programs could be a reference.

Btw, does the `file:` field means the tag is in the scope of a file? (I guess it is, based on the manpage.) If so, does it mean that a field with an empty value could still be valid?

**Comment by masatake** [comment]
> I don't know whether this is a good example of expected output, since I'm not sure what's the best way to deal with generic type variables. Maybe the behavior on C++ programs could be a reference.

The example may be good. Without evaluating, ctags cannot recognize generic types.

```
from typing import Callable, TypeVar

T = TypeVar('T')


```

Recognize this is easy. ctags can recognize T easily.
However, if the right side of expression where a type becomes complicated, we need evaluation that we will not do in ctags:
```
...
T = something ()
def func(a: str, b: Callable[[int, int], T]) -> T:
    pass
```

In C++, a generic type is declared in `templated <class T,...>`, so ctags doesn't need evaluation. 
In Python, I think we should not do more; "typeref:typename:Callable[[int, int], T]" may be enough.

**Comment by masatake** [comment]
```
def func2 (a: str) -> "a string":
    return a
```

This is valid python code. In this case, I wonder how the typeref field of func2 should be.

**Comment by masatake** [comment]
```
i = 10
def func3 () -> 3 + i:
    return 0
```

This one is also valid.
I wonder whether we should use "typename" as the 1st value for the typeref field or introduce something different like "typehint".

**Comment by AmaiKinono** [comment]
In my experiment, they are not valid for mypy:

`signature.py`:

``` python
from typing import *

i = 10

def func1() -> 3 + i:
    return 0

def func2(a: str) -> "string":
    return a

func1()
func2("hi")
```

Then:

``` console
$ mypy signature.py
signature.py:5: error: Invalid type comment or annotation
signature.py:8: error: Name 'string' is not defined
Found 2 errors in 1 file (checked 1 source file)
```

Btw, could you comment on this?

> does the `file:` field means the tag is in the scope of a file? (I guess it is, based on the manpage.) If so, does it mean that a field with an empty value could still be valid?

**Comment by AmaiKinono** [comment]
I think another problem is, these 2 programs have the same meaning:

```python
from typing import *

def func(a: Any) -> Any
    pass
```

``` python
import typing as tp

def func(a: tp.Any) -> tp.Any
    pass
```

But it's hard for ctags to generate the same tags file for them.

For the typical usage of a tags file, I think it's not worth it to bother with types other than classes too much, since they don't bring benefits for auto-completion and finding definitions (I have an idea of jumping from the argument in the signature to the definition of the struct/class). You don't even need to `import typing` when using a class name as type hint:

`signature.py`:

``` python
class Foo:
    pass

def func(a: Foo):
    pass

bar = Foo()
baz = 1

func(bar)
func(baz)
```

``` console
$ mypy signature.py
signature.py:24: error: Argument 1 to "func" has incompatible type "int"; expected "Foo"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by masatake** [comment]
> does the file: field means the tag is in the scope of a file? (I guess it is, based on the manpage.) If so, does it mean that a field with an empty value could still be valid?

Valid.
If a tag has "file:", it is defined in a file scope.
If it doesn't have, it is defined with a name that can be referred from the outside of the input file.

Here is an example.

```c
[yamato@control]~% cat /tmp/foo.c
cat /tmp/foo.c
static int f (void) { return 0; }
extern int g (void) { return 0; }
[yamato@control]~% u-ctags --fields=-lt -o - /tmp/foo.c
u-ctags --fields=-lt -o - /tmp/foo.c
f	/tmp/foo.c	/^static int f (void) { return 0; }$/;"	f	file:
g	/tmp/foo.c	/^extern int g (void) { return 0; }$/;"	f
```

I think "file:yes" and "file:no" are better.

**Comment by masatake** [comment]
```
from typing import *

def func(a: Any) -> Any
    pass

import typing as tp

def func(a: tp.Any) -> tp.Any
    pass
```

I have to say recognizing tp.Any and Any are the same is not the job of ctags.
Though there are some exceptions, ctags works in lexical level.
ctags should not hide the information in lexical level. 

u-ctags gives hints to your tool for recognizing tp.Any and Any are the same.

```
[yamato@control]~% cat /tmp/a.py 
cat /tmp/a.py 
from typing import *

def func(a: Any) -> Any
    pass

[yamato@control]~% u-ctags --extras=+r --fields=+r -o - /tmp/a.py 
u-ctags --extras=+r --fields=+r -o - /tmp/a.py 
func	/tmp/a.py	/^def func(a: Any) -> Any$/;"	f	language:Python	roles:def
typing	/tmp/a.py	/^from typing import *$/;"	i	language:Python	roles:namespace
```
```
[yamato@control]~% cat /tmp/b.py 
cat /tmp/b.py 
import typing as tp

def func(a: tp.Any) -> tp.Any
    pass
[yamato@control]~% u-ctags --kinds-Python='*' --extras=+r --fields=+r --fields-Python='*' -o - /tmp/b.py 
u-ctags --kinds-Python='*' --extras=+r --fields=+r --fields-Python='*' -o - /tmp/b.py 
a	/tmp/b.py	/^def func(a: tp.Any) -> tp.Any$/;"	z	language:Python	function:func	file:	roles:def
func	/tmp/b.py	/^def func(a: tp.Any) -> tp.Any$/;"	f	language:Python	roles:def
tp	/tmp/b.py	/^import typing as tp$/;"	I	language:Python	roles:def
typing	/tmp/b.py	/^import typing as tp$/;"	i	language:Python	roles:indirectlyImported
```

Your tool can know what `tp` is. The relation of tp and typing is obviously need, but it is not recorded. 
It seems that I forgot implementing it.
See parsers/python.c:
```c
/* Roles related to `import'
 * ==========================
 * import X              X = (kind:module, role:imported)
 *
 * import X as Y         X = (kind:module, role:indirectlyImported),
 *                       Y = (kind:namespace, [nameref:X])
 *                       ------------------------------------------------
 *                       Don't confuse with namespace role of module kind.
 *
 * from X import *       X = (kind:module,  role:namespace)
 *
 * from X import Y       X = (kind:module,  role:namespace),
 *                       Y = (kind:unknown, role:imported, [scope:X])
 *
 * from X import Y as Z  X = (kind:module,  role:namespace),
 *                       Y = (kind:unknown, role:indirectlyImported, [scope:X])
 *                       Z = (kind:unknown, [nameref:X.Y]) */
```
It seems that I planed to implement a field `nameref:` for recording the relation of tp and typing.

**Comment by AmaiKinono** [comment]
About the `file` field, I read this in tags(5):

> file: Static (local) tag, with a scope of the specified file. When the value is empty, {tagfile} is used.

So It's designed to be empty in exuberant ctags.

I don't think it would ever have a value that's different from the input file, since I've not seen in which language you can define something that's in the scope of another file. If this is true, replacing the value with `yes/no` wouldn't bring any problem (other than incompatibility).

>  The relation of tp and typing is obviously need, but it is not recorded. It seems that I forgot implementing it.

Yes. It's also needed for basic functionalities like auto-completion and finding definitions.

I also tried go. For a line like this:

``` go
import bt "bytes"
```

ctags generates:

```
bt      import.go       /^import bt "bytes"$/;" kind:packageName        line:1  package:bytes
```

which is good. I also tried rust, seems ctags doesn't know `use` in rust. But I'm not familiar with rust (seems it also has something like `include`), so I can't give any suggestions.

> See parsers/python.c

Thanks! This is valuable information for me.

**Comment by masatake** [comment]
> About the `file` field, I read this in tags(5):
> 
> > file: Static (local) tag, with a scope of the specified file. When the value is empty, {tagfile} is used.
> 
> So It's designed to be empty in exuberant ctags.
> 
> I don't think it would ever have a value that's different from the input file, since I've not seen in which language you can define something that's in the scope of another file. If this is true, 

It is true.

> replacing the value with `yes/no` wouldn't bring any problem (other than incompatibility).

I didn't introduce "yes/no" for avoiding the incompatibility.
If I changed file: field as you wrote, I think we don't get much. The consistency of tags output is improved a bit.
If you have a strong reason for "yes/no", please, open a new issue.  For avoiding the incompatibility, I will not change it but I would like to explore another way to solve the issue.

> 
> > The relation of tp and typing is obviously need, but it is not recorded. It seems that I forgot implementing it.
> 
> Yes. It's also needed for basic functionalities like auto-completion and finding definitions.
> 
> I also tried go. For a line like this:
> 
> ```go
> import bt "bytes"
> ```
> 
> ctags generates:
> 
> ```
> bt      import.go       /^import bt "bytes"$/;" kind:packageName        line:1  package:bytes
> ```
> 
> which is good. I also tried rust, seems ctags doesn't know `use` in rust. But I'm not familiar with rust (seems it also has something like `include`), so I can't give any suggestions.

I recognized the importance of tagging "use/include/import/require...". See  https://github.com/universal-ctags/ctags/issues/2428
There are too many in the queue but you can add rust. 

> 
> > See parsers/python.c
> 
> Thanks! This is valuable information for me.

**Comment by masatake** [comment]
@AmaiKinono, when you find time, could you review https://github.com/universal-ctags/ctags/pull/2613/files#diff-ace8fdcd38956865f8b696fd2a0efe6b ?
