### ISSUE TITLE
Hope to add protection when to parse files

### ISSUE THREAD

**Issue by Lennon925** [universal-ctags/ctags#2609]
When I use "ctags.exe -L C:\ctags-2018-12-26_5728abe4-x64\fileList.files --output-format=json --fields=+ne" to parse files in fileList.files，if program has no permission to open aaa.c, the whole parse will be interrupted. bbb.c can't get to be parsed.
I hope program can add some excpetion protections so that when some exceptions occur, other files still be parsed.

fileList.files content:
D:\Projects\aaa.c
D:\Projects\bbb.c

**Comment by masatake** [comment]
Do you think changing the behavior of -L option, skipping the input file with a warning message, fits your purpose?

**Comment by Lennon925** [comment]
> Do you think changing the behavior of -L option, skipping the input file with a warning message, fits your purpose?

I think it's ok.

**Comment by masatake** [comment]
The fix is merged. If you still have the trouble, please, reopen this.
Thank you for reporting.
