### ISSUE TITLE
‘__NR_fstat64’ undeclared && ‘__NR__llseek’ undeclared

### ISSUE THREAD

**Issue by VerdantFish** [universal-ctags/ctags#2615]
when I built ctags in ubuntu12.04 , Errors occured ! I was following the instructions in  ctags/docs/autotools.rst , but when I run "make" , there're 2 errors like this :

-----------------------------------------------------------------------------------

main/seccomp.c: In function ‘installSyscallFilter’:
main/seccomp.c:45:1: error: ‘__NR_fstat64’ undeclared (first use in this function)
main/seccomp.c:45:1: note: each undeclared identifier is reported only once for each function it appears in
main/seccomp.c:50:1: error: ‘__NR__llseek’ undeclared (first use in this function)
make[1]: *** [main/libctags_a-seccomp.o] Error 1
make[1]: Leaving directory `/usr/local/android/ctags'
make: *** [all] Error 2

-----------------------------------------------------------------------------------

Please help，thanks a lot !

**Comment by masatake** [comment]
How about following command line?
```
make clean;./configure --disable-seccomp;make
```
> make[1]: Leaving directory `/usr/local/android/ctags'

This line implies you did something abnormal. You must know what you are doing.

**Comment by VerdantFish** [comment]
Thank you @masatake .

> > make[1]: Leaving directory `/usr/local/android/ctags'
> 
> This line implies you did something abnormal. You must know what you are doing.

I  just only runned commands mentioned in autotools.rst, without doing any other actions. 
I runned those commands again, with param `--disable-seccomp` following `configure` . 
It works now. Thank you again.
