### ISSUE TITLE
pax issue when the UID or GID of the current user is too high (> 2097151)

### ISSUE THREAD

**Issue by TanishBansal** [universal-ctags/ctags#2626]
While trying to build without sudo, pax doesnt support very large UID.

```
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh 
./configure --prefix=$HOME
```

Get the following, 
```
ATTENTION! pax archive volume change required.
Ready for archive volume: 1
Input archive name or "." to quit pax.
Archive name >
```

Any alternative way to build without pax and using sudo( UID for root is 0)

Thanks!

**Comment by masatake** [comment]
It cannot be solved in ctags.

See http://gnu-automake.7480.n7.nabble.com/Question-about-automake-fails-to-pass-the-correct-parameters-to-pax-when-using-large-UID-GID-td7599.html

**Comment by TanishBansal** [comment]
Is there any alternative build system like cmake etc instead of automake?

**Comment by masatake** [comment]
Only automake for posix.

**Comment by masatake** [comment]
It is an issue about the archive format. So I guess changing the building tool form automake to another one may not help us.
https://lists.gnu.org/archive/html/bug-automake/2013-04/msg00016.html
