### ISSUE TITLE
TCL parser thrown off by $ char in regexp statement.

### ISSUE THREAD

**Issue by surmish** [universal-ctags/ctags#2627]
The name of the parser: universal ctags

The command line you used to run ctags: `ctags --options=NONE script.tcl`

The content of input file:

```tcl
proc proc1 {} {
  if {[regexp {[0-9]$} ""]} {
    echo "matched"
  }
}

proc proc2 {} {}
```

The tags output you are not satisfied with:

```
proc1   script.tcl      /^proc proc1 {} {$/;"   p
```

If you notice, `proc2` is missing from the tags file. Removing the `$` character from the regexp fixes the issue. You will notice the following tags once you run the same script without the `$` char.

The tags output you expect:
```
proc1   script.tcl      /^proc proc1 {} {$/;"   p
proc2   script.tcl      /^proc proc2 {} {}$/;"  p
```

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(ba2b8c55), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 21 2020, 18:47:38
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc
```

How do you get ctags binary: Building it locally, via GNU/Linux distribution, as BSD's package,

**Comment by masatake** [comment]
How can we know the `$` is not the prefix of variable?

**Comment by surmish** [comment]
The regular expression is stored within hard quotes `{` and `}`.  
It is not a prefix of a variable because the pattern is ending there.

E.g. Both of the following treat `$` as an anchor character

```TCL
tclsh8.6:> regexp {abc$} "def\$abc"
1
tclsh8.6:> regexp "abc$" "defabc"
1
```

However if the quotes are weak quotes `"` and if `$` is used before some legal variable name pattern then this happens 
```TCL
tclsh8.6:> regexp "$abc" "defabc"
can't read "abc": no such variable
```

**Comment by masatake** [comment]
```
proc proc3 {a} {puts $a}
proc3 "abc"
```
This prints "abc".
It means `$a` within hard quotes { and } is expanded.
How can I understand this?

**Comment by surmish** [comment]
`proc` keyword in TCL has a syntax like which is `proc name args body`
described in detail here: https://www.tcl.tk/man/tcl8.6/TclCmd/proc.htm

Similarly `regexp` keyword also has a syntax like so: `regexp ?switches? exp string ?matchVar? ?subMatchVar subMatchVar ...?`
described in detail here: https://www.tcl.tk/man/tcl8.4/TclCmd/regexp.htm

There is also `regsub` which is slightly different: 
https://www.tcl.tk/man/tcl8.4/TclCmd/regsub.htm

**Comment by masatake** [comment]
My understanding of how the `$` with `{...}` is handled is up to context.

```
source alibrary
$def proc4 {a} {puts $a}
```

In this case, how `$a` is treated?
My understanding is that it is up to how $def is defined in `alibrary`.
Am I wrong?

**Comment by surmish** [comment]
I'm not aware of `alibrary`. Is it from the TCL source?

**Comment by masatake** [comment]
>Is it from the TCL source?
No. Please, assume a user of ctags writes it.  `def` is defined in `alibrary`.
I guess you cannot say how `$a` is handled without inspecting `alibrary`.
Am I wrong?

**Comment by surmish** [comment]
Yes you need to know how `$def` is defined to see how `$a` is treated. 
But `{}` are hard quotes, the evaluation of anything within those braces is up to the downstream code.

**Comment by masatake** [comment]
I would like to make sure.
Here, "the downstream code"  means commands at the head of a statement like $def, proc, regexp, or regsub, don't they?

**Comment by surmish** [comment]
No, I meant the implementation of those keywords.

**Comment by masatake** [comment]
> No, I meant the implementation of those keywords.

So if the keyword is not implemented in the current input file, ctags must find the implementation of keyword to handle `$` correctly. Am I correct?

**Comment by surmish** [comment]
Yes, I think so. `regexp, regsug, proc` are tcl in built keywords.

**Comment by masatake** [comment]
ctags cannot track the implementations.
We need heuristics for deciding how '$' is used. 

``` 
...$a
...$b
...${a}
...${b}
```
These will be variable prefixes.

```
...$|
...$)
```
These will be in regex patterns.

```
...[..$a.]
```
In this case, the heuristic doesn't work well.

If you have any idea to improve the detection, I would like to hear it.

**Comment by masatake** [comment]
I made a pull request based on the idea written in my last comment.
I hope this mitigate this issue.
Could you try #2629 ?

**Comment by surmish** [comment]
This test case fails: 

```tcl
proc proc1 {} {
  expr {[string first "\\" $conn]==0}
}

proc2  {} {}
```

**Comment by masatake** [comment]
I found backslash characters are not handled correctly. I pushed one more change.
I guessed proc2 may be "proc proc2".

**Comment by surmish** [comment]
> I found backslash characters are not handled correctly. I pushed one more change.
> I guessed proc2 may be "proc proc2".

yes, I meant `proc proc2 {} {}`
