### ISSUE TITLE
Parsing bug(?) with ruby classes with comment on line of class declaration

### ISSUE THREAD

**Issue by colinlieberman** [universal-ctags/ctags#2632]
The name of the parser: ruby

The command line you used to run ctags: `ctags --options=NONE test/class_one.rb test/class_two.rb`

The content of input file:

class_one.rb:

```ruby
# frozen_string_literal: true

class MyClass # rubocop:disable Metrics/ClassLength
  def foo
    abc
  end

  def bar
    bar_class = MyOtherClass.new
    bar_class.potatoes
  end

  def baz
    hij
  end

  def bla
    klm
  end

  def shazam
    foo && bar || (baz && bla)
  end

  def bla_bla
    "#{bla} #{bla}"
  end

  def abc
    'abc'
  end

  def defg
    'defg'
  end

  def hij
    'hij'
  end

  def klm
    'klm'
  end
end
```

class_two.rb:

```ruby
# frozen_string_literal: true

class MyOtherClass
  def initialize
    foo = MyClass.new
    foo.bla_bla
  end

  def potatoes
    'potates'
  end
end
```

I know the way I describe this, it will look like the issue is the IDE, but bear with me...

Case 1 (correct): In my IDE (atom), if I trigger 'go to declaration' in class_one.rb on line 10 (`bar_class = MyOtherClass.new`), it correctly takes me to class_two.rb line 3 (`class MyOtherClass`).

Case 2 (correct): If I trigger 'go to declaration' in class_one.rb line 11 (`bar_class.potatoes`), it correctly takes me to class_two.rb line 9 (`def potatoes`).

Case 3 (correct): The same for class_two.rb line 6 (`foo.bla_bla`) taking me to class_one.rb line 25 (`def bla_bla`)

Case 4 (incorrect): This is the same quality of a case as Case 1 - the tag should point to the class declaration. In class_2.rb line 5 (`foo = MyClass.new`), triggering 'go to declaration' does nothing (should go to class_one.rb line 3).

However, if I change class_one.rb to move the comment above the class declaration:

```ruby
# rubocop:disable Metrics/ClassLength
class MyClass
...
```

and rerun ctags, then all 4 cases above function correctly. The diff in the tags files is this:

```
$ diff tags_before_change tags
10c10
< MyClass	test/class_one.rb	/^class MyClass # rubocop:disable Metrics\/ClassLength$/;"	c
---
> MyClass	test/class_one.rb	/^class MyClass$/;"	c
```

I don't know enough about how the tags function to tell you specifically where I think the issue is

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0(c9ebd83), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 24 2020, 12:13:23
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames, +packcc

```

How do you get ctags binary: homebrew

**Comment by masatake** [comment]
I think this is not an issue of ctags.
This is an issue of atom or a tool running on atom.
The diff of tags files you display shows the tags output looks valid.

**Comment by masatake** [comment]
It seems that a tool reading tags file cannot handle '\' in the pattern correctly.

**Comment by colinlieberman** [comment]
Thanks, @masatake , I'll look into that. Changing the / to a - isn't an option: this comment is a directive to a popular [ruby linting tool](https://github.com/rubocop-hq/rubocop)

I'll see if I can get any insight into the tools reading the tags
