### ISSUE TITLE
typedef struct & typeref type issue

### ISSUE THREAD

**Issue by captainlin08** [universal-ctags/ctags#2633]
Hello，
       When I used typedef as a nested definition of a struct, the tag did not generate the typeref type I wanted for a struct member variable that was also defined with typedef. Can ctags support this？Thank you.

The name of the parser:
C

The command line you used to run ctags:

```
ctags --fields=+niazS --kinds-C=+lpxzL --output-format=e-ctags -o - tags.c
```

The content of input file:

```C

 typedef struct _c{
      int h;
      char *i;
      char j[32];
 }c_t;
 
 typedef struct _d{
     int k;
     char *l;
     char m[32];
     c_t n;
 }d_t;

```

The tags output you are not satisfied with:

```
n	tags.c	/^	c_t n;$/;"	kind:m	line:15	struct:_d	typeref:typename:c_t	file:	access:public
...
```

The tags output you expect:

```
n	tags.c	/^	c_t n;$/;"	kind:m	line:15	struct:_d	typeref:struct:_c	file:	access:public
...
```

The version of ctags:

```
[cptl@localhost tags]$ ctags --version
Universal Ctags 0.0.0(36a6dd1), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep  1 2020, 15:28:55
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc

```

**Comment by masatake** [comment]
> Hello，
When I used typedef as a nested definition of a struct, the tag did not generate the typeref type I wanted for a struct member variable that was also defined with typedef. Can ctags support this？

No.

`c_t` is tagged as 
```
c_t	/tmp/input.c	/^}c_t;$/;"	t	language:C	typeref:struct:_c	file:
```

Therefore a tool can know n is typed `struct:_c` with querying tags file recursively.
Such rescursive querying is a job of your tool, not ctags.
