### ISSUE TITLE
Unable to generate tags for files with an extension matching built-in exclusion list

### ISSUE THREAD

**Issue by mvanderkamp** [universal-ctags/ctags#2634]
In `initOptions()` in `main/options.c` there are several built-in exclude options. Sometimes these extensions get used for other types of data though, but as far as I can tell there doesn't seem to be a way to override these default excludes. Am I mistaken? Did I miss something in my search?

If there currently isn't a way to override these excludes, it would be a nice option to have sitting around. Currently I'm just using a version compiled with the relevant lines commented out.

**Comment by masatake** [comment]
See ctags(1) man page.
https://docs.ctags.io/en/latest/man/ctags.1.html#options

`--exclude`, `--list-excludes`, `--exclude-exception` may help you.

**Comment by mvanderkamp** [comment]
Thank you that did the trick! Is that a relatively recent option? I must have been working with an older version of the man page. Sorry I didn't manage to find that on my own!
