### ISSUE TITLE
Javascript: function containing regular expression excluded from "tags"

### ISSUE THREAD

**Issue by mb13** [universal-ctags/ctags#2638]
I'm using ctags for my JavaScript code. Until now I didn't have any issues. But if this

`.replace(/'/g, '')`

is used in a function, then the function and the rest of the file is not tagged in the "tags" file. The problem I think is with the odd number of apostrophes... Vim has also problems with highlighting the tokens

**Comment by masatake** [comment]
Could you show us (a) function(s) that trigger(s) the bug?

**Comment by mb13** [comment]
`function aa() {
	// it will be included in tags
}

function bb() {
	var someString = "a'b";
	// here is the error... everything from this point below will NOT be included in tags
	someString.replace(/'/g, '');
}

function cc() {
	// it will NOT be included in tags
} `

**Comment by masatake** [comment]
Thank you.

**Comment by masatake** [comment]
```
$ cat input.js         
function aa() {
    // it will be included in tags
}

function bb() {
    var someString = "a'b";
    // here is the error... everything from this point below will NOT be included in tags
    someString.replace(/'/g, '');
}

function cc() {
    // it will NOT be included in tags
} 
$ ./ctags -o - input.js
aa	input.js	/^function aa() {$/;"	f
bb	input.js	/^function bb() {$/;"	f
cc	input.js	/^function cc() {$/;"	f
```

The issue is not reproduced.

**Comment by mb13** [comment]
[root@localhost ~]# ctags -o - input.js
    aa	input.js	/^function aa() {$/;"	f
    [root@localhost ~]# ctags --version
    Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
      Compiled: Jul 23 2018, 13:15:51
      Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
      Optional compiled features: +wildcards, +regex

**Comment by k-takata** [comment]
> Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert

You are using Exuberant Ctags, not Universal Ctags.
