### ISSUE TITLE
C/C++：can I make TEST_F to be parsed as a function in google gest framework

### ISSUE THREAD

**Issue by chongchai** [universal-ctags/ctags#2639]
I try to use ctags to parse code written with google gtest framework. Gtest framework can be found at  https://github.com/google/googletest/blob/master/googletest/docs/primer.md.

The sample code like this:
```
TEST_F(TestFixtureName, 1_TestName) {
}

TEST_F(TestFixtureName, 2_TestName) {
  int a = 1;
}

TEST_F(TestFixtureName, 3) {
}
```

I use following command to parse.
```
ctags.exe --output-format=json  --langmap=c:+.inc.def --kinds-c=+plz --fields=+nie -o - D:\code\test.c
```
Result is:
```
{"_type": "tag", "name": "a", "path": "D:\\code\\test.c", "pattern": "/^  int a = 1;$/", "line": 5, "typeref": "typename:int", "kind": "variable", "end": 5}
```

**I want to parse `TEST_F` to be a function and parse  `a`  to be a local variable.**

I also try to use `-D` option with command
`ctags.exe --output-format=json -D TEST_F(test_suite,test_name)=TEST_F() --langmap=c:+.inc.def --kinds-c=+plz --fields=+nie -o - D:\code\test.c`. But it can not work.

**Comment by masatake** [comment]
The way to use -D option looks wrong.
The result  of the definition expansion must be valid C code.

```
[yamato@control]~/var/ctags-github% cat /tmp/bar.c 
cat /tmp/bar.c 
TEST_F(TestFixtureName, 1_TestName) {
}

TEST_F(TestFixtureName, 2_TestName) {
  int a = 1;
}

TEST_F(TestFixtureName, 3) {
}
[yamato@control]~/var/ctags-github% ./ctags -D'TEST_F(a,b)=void a##b(void)' -o - /tmp/bar.c 
./ctags -D'TEST_F(a,b)=void a##b(void)' -o - /tmp/bar.c 
TestFixtureName1_TestName	/tmp/bar.c	/^TEST_F(TestFixtureName, 1_TestName) {$/;"	f	language:C	typeref:typename:void
TestFixtureName2_TestName	/tmp/bar.c	/^TEST_F(TestFixtureName, 2_TestName) {$/;"	f	language:C	typeref:typename:void
TestFixtureName3	/tmp/bar.c	/^TEST_F(TestFixtureName, 3) {$/;"	f	language:C	typeref:typename:void
```

**Comment by masatake** [comment]
I must update the man page.
The usage of -D with parameters is not written.

**Comment by chongchai** [comment]
@masatake Your usage for “-D option“ is right. Using `-D'TEST_F(a,b)=void a##b(void)'` will get `TestFixtureName1_TestName` as function name.
But my requirement may be weird. I want to get TEST_F as function name.  Is there any way?

**Comment by masatake** [comment]
>  But my requirement may be weird. I want to get TEST_F as function name. Is there any way?

Sorry. There is no way to do that. The macro expander of ctags tries to expand `TEST_F` recursively and doesn't stop till it reaches the internal limit. See https://github.com/universal-ctags/ctags/pull/2539 .

This is a bug. However, fixing it is not easy for me.

**Comment by chongchai** [comment]
Got it. Thanks any way.

**Comment by masatake** [comment]
I don't know what kind of client tool that utilizes the output tags file.
However, I think tagging TEST_F as a C function is not a good idea because it is not a function. It is a macro expansion of Gtest.
"It is a macro expansion of Gtest." is a view of C language.
However, it is a definition of a test case in a view of Gtest.
It implies you should write a parser for Gtest instead of expanding the C parser in the wrong way.

I have designed Universal-ctags can handle this situation well.
See my vision: https://docs.ctags.io/en/latest/running-multi-parsers.html . 

```
$ cat gtest.ctags
-D TEST_F(a,b)=void a##b(void)
--langdef=Gtest{base=C}{shared}
--kinddef-Gtest=t,tests,test cases
--_fielddef-Gtest=cfunc,c function name
--fields-Gtest=+{cfunc}
--regex-Gtest=/^TEST_F *\( *([^,]+), *([^)]+) *\).*/TEST_F/t/{_field=cfunc:\1\2}
$ ./ctags -o - --options=gtest.ctags --fields=+l /tmp/foo.c
TEST_F	/tmp/foo.c	/^TEST_F(TestFixtureName, 1_TestName) {$/;"	t	language:Gtest	cfunc:TestFixtureName1_TestName
TEST_F	/tmp/foo.c	/^TEST_F(TestFixtureName, 2_TestName) {$/;"	t	language:Gtest	cfunc:TestFixtureName2_TestName
TEST_F	/tmp/foo.c	/^TEST_F(TestFixtureName, 3) {$/;"	t	language:Gtest	cfunc:TestFixtureName3
TestFixtureName1_TestName	/tmp/foo.c	/^TEST_F(TestFixtureName, 1_TestName) {$/;"	f	language:C	typeref:typename:void
TestFixtureName2_TestName	/tmp/foo.c	/^TEST_F(TestFixtureName, 2_TestName) {$/;"	f	language:C	typeref:typename:void
TestFixtureName3	/tmp/foo.c	/^TEST_F(TestFixtureName, 3) {$/;"	f	language:C	typeref:typename:void
```
