### ISSUE TITLE
sort: write failed: /tmp/sortNpGppi: No space left on device

### ISSUE THREAD

**Issue by tchoutri** [universal-ctags/ctags#2651]
Problem: While generating tags for quite a big project (and excluding dependency folders like node_modules), the sorting process seems to use a /tmp/-based location (which is a tmpfs). Considering that the resulting tag file is around 4GB, I am left with "No space left on device".

How can I force the sorting to take place on my SSD (say, my home directory) rather than in my tmpfs?

---

* The version of ctags:

```
❯ ctags --version                                                                                  
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  1 2020, 00:00:00
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc

```

* How do you get ctags binary: Fedora distribution

**Comment by k-takata** [comment]
How about setting `$TMPDIR` environment variable?

**Comment by tchoutri** [comment]
Oh my god I feel so stupid. Yes, this perfectly works, thank you very much.
