### ISSUE TITLE
ctags: Warning: cannot open input file  : No such file or directory

### ISSUE THREAD

**Issue by diaojunxian** [universal-ctags/ctags#2670]
ctags version
```
Universal Ctags 0.0.0(e852ee0e), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct  7 2020, 06:18:08
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +packcc
```
when command 

```
$ touch /data/ttt.txt
```
then command the `ctags`
```
$ ctags -f "/home/user/tags.tmp" /data/ttt.txt --verbose=yes
```
it returned
```
ctags: Warning: cannot open input file "/data/ttt.txt" : No such file or directory
sorting tag file
system ("sort -u -o '/home/user/tags.tmp' '/home/user/tags.tmp'")
```
but when `mv /data/ttt.txt /home/user/`,then command `ctags`
```
$ ctags -f "/home/user/tags.tmp" /home/user/ttt.txt --verbose=yes
```
it returned
```
sorting tag file
system ("sort -u -o '/home/user/tags.tmp' '/home/user/tags.tmp'")
```
the difference is the /data directory is the mounted hard disk directory.
```
$ ll /data/ttt.txt

-rw-rw-r-- 1 user user 0 10月 22 15:06 /data/ttt.txt

$ ll /home/user/ttt.txt 
-rw-rw-r-- 1 user user 0 10月 22 15:06 /home/user/ttt.txt
```
why to solved the problem?

**Comment by masatake** [comment]
Do you use GNU/Linux?
If yes, could you install strace? then run ctags under strace like:

$ strace -f -y -o /tmp/LOG.strace ctags -f "/home/user/tags.tmp" /data/ttt.txt --verbose=yes

I would like to see /tmp/LOG.strace. LOG.strace may be large, so put it to your gist or send it to me (yamato@redhat.com).

**Comment by diaojunxian** [comment]
sorry, when try the command , the command not had any console log

**Comment by masatake** [comment]
Do you mean /tmp/LOG.strace is empty?

**Comment by diaojunxian** [comment]
yes, and try again, found the command run very slowly.

**Comment by masatake** [comment]
Looks strange. (Running slowly is expected.)
How about
```
$ strace -f -y  -f "/home/user/tags.tmp" /data/ttt.txt --verbose=yes
```

**Comment by masatake** [comment]
Reproduced here.

**Comment by masatake** [comment]
Sorry, what I wrote in the last comment is just my misunderstanding. Ignore it.

**Comment by masatake** [comment]
Could you run the following command and show /tmp/ctags.strace and /tmp/cat.strace?
```
INPUT=/data/ttt.txt 
$ strace -f -y -o /tmp/ctags.strace ctags -f "/home/user/tags.tmp" --verbose=yes $INPUT
$ strace -f -y -o /tmp/cat.strace cat $INPUT
```
I would like you to use gist if the files are large.

**Comment by masatake** [comment]
Please, reopen this when you neeed.
