### ISSUE TITLE
What's the best way of parsing the fields from tagfile/origin tagline for the tools based on ctags

### ISSUE THREAD

**Issue by liuchengxu** [universal-ctags/ctags#2683]
Although ctags already supports the JSON output, the compiled feature `+json` is required and some people does not have this feature, in which case the tools built on ctags like some vim plugins([vista.vim](https://github.com/liuchengxu/vista.vim), [vim-clap](https://github.com/liuchengxu/vim-clap)...) need to parse the fields manually, otherwise they can't work. 

vista.vim is currently using https://github.com/liuchengxu/vista.vim/blob/27889ff58d/autoload/vista/parser/ctags.vim#L91-L134, but not sure it's robust enough. In [this vim-clap PR](https://github.com/liuchengxu/vim-clap/pull/557), we plan to parse the tagfile, hoping to find a good solution for such a parser. Any insights would be appreciated.

See the tips for this task from @masatake in https://github.com/liuchengxu/vim-clap/pull/557#issuecomment-718041196

cc @romgrk

**Comment by masatake** [comment]
We have a parser written in C. I hope it will help to find a better way.

See parseTagLine and parseExtensionFields in [readtags.c](https://github.com/universal-ctags/libreadtags/blob/master/readtags.c).

I read https://github.com/liuchengxu/vista.vim/blob/27889ff58d/autoload/vista/parser/ctags.vim#L91-L134. As fa as `;"` is not included in the pattern, it looks find for me as far as you use u-ctags. I would like to know the detail of ", but not sure it's robust enough".

If you don't use u-ctags, a tab in a field can include `\t`. So parsing will be failed. In such case, ... use u-ctags.

**Comment by AmaiKinono** [comment]
The manpage ctags-client-tools(7) has a "Parse Readtags Output" section. You should be good if using the method provided there.

**Comment by masatake** [comment]
@AmaiKinono, see `--excmd=type` in https://docs.ctags.io/en/latest/man/ctags.1.html#options .
