### ISSUE TITLE
Enable TAG_PROC_CWD by defaut

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2688]
AmaiKinono/citre expects it.

**Comment by masatake** [comment]
If INSIDE_EMACS env is set, adding `--fields=+n` may reduce the bug reports we will receive.

@AmaiKinono, could you give me comments WHEN you get time.

**Comment by AmaiKinono** [comment]
> Enable TAG_PROC_CWD by defaut.

Yes!

> If INSIDE_EMACS env is set, adding `--fields=+n` may reduce the bug reports we will receive.

I'm not very sure on this:

- If the user wants to use a manually generated tags file, then this variable won't do any good to him.

- Some users may only want auto-completion but not jumping to definition. The the `line` field is useless to him. Or let's assume a Emacs client tool only does auto-completion, then its author will say INSIDE_EMACS actually has nothing to do with Emacs, but only "jumping to definiton in Emacs".

- For a complicated client tool that supports specific languages, maybe other fields are also important to it. It should teach its user how to generate a tags file that's good enough. I think we shouldn't try to cover this.
