### ISSUE TITLE
Remove combined pattern field?

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2691]
`--excmd=combine` is added for the request in ~#1890~#1125, to deal with https://github.com/vim/vim/issues/1057.

But at the end, vim didn't take that approach, but utilize `line:` field instead, see <https://github.com/vim/vim/commit/077b9dd3541339a23ade0cc6a23e804ee39312c5>. From what I saw in <https://github.com/vim/vim/blob/master/src/tag.c>, that's still how things work now.

Neovim takes the same approach: <https://github.com/neovim/neovim/blob/643f4a178751df34b27189f7aebea313b17bad3b/src/nvim/tag.c#L2805>.

Combined pattern field also somewhat denies the purpose of using a search pattern: to tolerate certain (actually a wide range of) source file updates. If we start search from the line above or below the tag, this will be easily broken. Personally I don't think it's meaningful.

So, it's safe to remove `--excmd=combine` since even vim doesn't use it, and that would have benefits:

- Keep the pattern field consistent with Exuberant Ctags.
- Client tools on non-vim editors may also wants to support the pattern field. This will make it easier.

**Comment by masatake** [comment]
> --excmd=combine is added for the request in #1890, to deal with vim/vim#1057.

#1890?

#1125 and #1959 are related to this topic. Do I misunderstand?

It seems that the option becomes popular already: e.g. https://github.com/tmm1/ripper-tags/pull/98

**Comment by AmaiKinono** [comment]
Ah yes, It's #1125.

Obviously, ripper tags implements it since u-ctags has it, but still, no client tools are really using it.

**Comment by masatake** [comment]
@blueyed, do you really use `--excmd=combined` option?

**Comment by blueyed** [comment]
@masatake 
No.  I have this commented in my config:
```
# Works great with https://github.com/vim/vim/issues/1057.
# --excmd=combine
# Smaller files.
# But too often offset mismatches.
# --excmd=number
```

**Comment by masatake** [comment]
@blueyed, @mislav, @sshsu, do you have any ideas/commets about causing a trouble when we remove --excmd=combined?

I myself don't want to remove because I think it can make tags file compact comparing with using `line:' fields.

**Comment by AmaiKinono** [comment]
> it can make tags file compact comparing with using `line:' fields.

As long as I know, you don't care about the search pattern, but only the line number. Then `--excmd=number` is better for you.

If you are talking about client tools in Emacs doesn't support `--excmd=number` , well, I will make that happen ;)

**Comment by AmaiKinono** [comment]
@masatake I thought a little bit more on this.

If a client tool could search for the pattern and *find the closest one near the line number given*, no matter it's before of after it, then we could deal with duplicated patterns, and deal with minor code update that doesn't touch the line, at the same time.

I think this makes the best use of both the search pattern and line number, so you are right, it's good to put them together to make it compact.

For such a client tool, `--excmd=combine` is meaningful, but it need to add or minus one on the line number in the pattern field, which is a bit awkward. Yes we know it should behave like this since the pattern field should be an EX command, but that field has never been a valid one (see <https://github.com/AmaiKinono/citre/issues/27#issuecomment-723422727>).

So I'd agree if you keep the combined pattern. Maybe we could talk about changing the number to the actual line number, but it's also good to keep it to resemble an EX command.

**Comment by masatake** [comment]
I will keep the code as is till a serious user reports an issue.

@AmaiKinono, how do you think about adding TAG_OUTPUT_EXCMD pseudo tag?
If TAG_OUTPUT_EXCMD is `combined`, citre can reject the tag file (if you want).

When we fix line numbers in patterns, I will use `combinedV2` as the value for the ptag.

**Comment by AmaiKinono** [comment]
> how do you think about adding TAG_OUTPUT_EXCMD pseudo tag?

It's not bad to have such information. I'll handle all kinds of patterns and the pattern itself could be easily parsed, so I don't have the need, but other client tools may want this.

> When we fix line numbers in patterns, I will use `combinedV2` as the value for the ptag.

There's a problem: Now the pattern itself tells you how to search in a source file. If we keep both `combined` and `combinedV2`, then the pattern is not enough, we need to provide this extra bit of info. It can be handled, but will cause some trouble (e.g. to Citre, this is another `ambiguous information`, so I need to create an extension field `ext-pattern`). I suggest we decide one version to use.

**Comment by masatake** [comment]
> There's a problem: Now the pattern itself tells you how to search in a source file. If we keep both combined and combinedV2, then the pattern is not enough, we need to provide this extra bit of info. It can be handled, but will cause some trouble (e.g. to Citre, this is another "ambiguous information", so I need to create an extension field ext-pattern). I suggest we decide one version to use.

When we move to combinedV2, I will remove the code for combined(v1) from ctags. However, users may have old tags file generated by old u-ctags. In that case you may want to have the way to reject old tags file.
TAG_OUTPUT_EXCMD gives you the hint for rejecting or accepting. Or, of course, you can use TAG_OUTPUT_EXCMD to support both v1 and v2.

**Comment by AmaiKinono** [comment]
I see. That's reasonable.
