### ISSUE TITLE
可以支持vue？

### ISSUE THREAD

**Issue by StephenWu5** [universal-ctags/ctags#2706]
你好，请问支持vue文件吗？它包含了html，css，javascript。

vue文件长这样子。

if you can not see my word, you can use chrome translate.

![image](https://user-images.githubusercontent.com/32475322/99535026-4b259000-29e3-11eb-9f97-2555c70015fc.png)

**Comment by masatake** [comment]
See #1577. I want to support it but I found enough time for working on this topic.
