### ISSUE TITLE
[Bug] Ctags hangs for some seconds, then reports 'Access denied'

### ISSUE THREAD

**Issue by pidgeon777** [universal-ctags/ctags#2725]
When running Ctags, no matter of the arguments, it hangs for about ten seconds, then it reports `Access denied.`:

![image](https://user-images.githubusercontent.com/13739892/100066424-60604b80-2e35-11eb-834e-a39c39cda0ee.png)

I'm running it in two OS, both Windows 10 x64 Pro.

Strangely, this issue occurs only in one of those PCs.

Tested with the latest Ctags x64 release:

https://github.com/universal-ctags/ctags-win32/releases/tag/2020-11-24%2Fp5.9.20201122.0-26-g7b8fb5d0

I also tried some of the other recently released version, and the issue is still present.

**Comment by pidgeon777** [comment]
Also tried to run it as Administrator, the issue persists.

**Comment by k-takata** [comment]
Could you provide a minimal reproducible example?
Or can you execute the debug build on GDB?

**Comment by pidgeon777** [comment]
> Could you provide a minimal reproducible example?

I would do that, but I'm simply doing something like this:

1. Open command prompt.
2. cd to Universal Ctags path.
3. Command: `ctags`, or `ctags -help`, or even `ctags -qweqwe`.

Is there a way to enable some kind of debugging output? For example a log file.

> Or can you execute the debug build on GDB?

I don't think it could be actually possible for me, not having the required tools I suppose. How could I proceed with that, just in case?

**Comment by k-takata** [comment]
> 2. cd to Universal Ctags path.

Does it occur when you cd to an empty directory?

> 3. Command: `ctags`, or `ctags -help`, or even `ctags -qweqwe`.

Hmm, `ctags -help` will normally show `ctags.exe: No files specified. Try "ctags.exe --help".`

> How could I proceed with that, just in case?

If you have installed MSYS2, open `MSYS2 MinGW 64-bit` from Start Menu, then execute `gdb /path/to/ctags.exe`, then execute `run` on GDB.

**Comment by pidgeon777** [comment]
Content of `ctags` folder:

```batch
C:\Work\MEGA\Portable\Universal Ctags>dir
 Il volume nell'unità C non ha etichetta.
 Numero di serie del volume: 28FB-DDF7

 Directory di C:\Work\MEGA\Portable\Universal Ctags

23/11/2020  23:34    <DIR>          .
23/11/2020  23:34    <DIR>          ..
23/11/2020  02:06         3.519.488 ctags.exe
23/11/2020  22:47    <DIR>          docs
23/11/2020  22:47    <DIR>          license
23/11/2020  22:47    <DIR>          man
23/11/2020  02:01             4.725 README.md
23/11/2020  02:06           174.592 readtags.exe
23/11/2020  23:34             1.873 tags
23/11/2020  23:34               163 Test.bat
               5 File      3.700.841 byte
               5 Directory  28.383.137.792 byte disponibili
```

Even <kbd>Ctrl</kbd> + <kbd>C</kbd> doesn't seem to produce any effect (it doesn't interrupt `ctags` execution once it hangs).

Finally I followed your suggestion, here is the output:

```shell
hostuser@HOSTNAME MINGW64 ~
$ gdb /C/Work/MEGA/Portable/Universal\ Ctags/ctags.exe .gnupg/
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from C:/Work/MEGA/Portable/Universal Ctags/ctags.exe...(no debugging symbols found)...done.
"C:\msys64\home\hostuser/.gnupg/" is not a core dump: file format not recognized
(gdb) run
Starting program: C:\Work\MEGA\Portable\Universal Ctags\ctags.exe
Error creating process C:\Work\MEGA\Portable\Universal Ctags\ctags.exe, (error 5).
(gdb)
```

**Comment by pidgeon777** [comment]
I tried 20+ of the previously released Universal Ctags versions.

The very first Universal Ctags version released (back to 2017), this one, works:

https://github.com/universal-ctags/ctags-win32/releases/tag/2017-06-21.2bb585fc

But, starting with the second Universal Ctags release, the following, then not a single release work in my PC:

https://github.com/universal-ctags/ctags-win32/releases/tag/2017-06-22.d87c4725

All of them hangs as described above.

**Comment by masatake** [comment]
@k-takata, I don't know well about Windows but I found an interesting article written in Japanese: https://cs.wingarc.com/ja/kb/000016051 .

**Comment by pidgeon777** [comment]
I had a quick look at that article you posted above, even if I don't know Japanese, and here are some interesting points taken from it:

> At our company, when the target product is installed or uninstalled in the environment where the security software "Virus Buster" of Trend Micro Co., Ltd. is installed, the error dialog "sc.exe: CreateProcess error = 5" is displayed and the product is normally installed.

I can confirm that my issue occurs on my company workstation, and that Trend Micro is enabled, indeed. Maybe it could depend on that?

I'm not sure they'll allow me to whitelist ctags being a non-essential tool (from the company perspective), thus I hope there can be a solution for my issue.

The strange fact is that the first Universal Ctags release I posted above, works, but the following release not. And none of the furtherly released packages from that version onwards.

**Comment by masatake** [comment]
Is there a tool like `ls` on Windows?
We would like to compare the owner and the permission assigned to the two executables.

**Comment by pidgeon777** [comment]
Would it be ok to do that by opening a shell with MSYS or similar? For running the `ls` command.

**Comment by AmaiKinono** [comment]
I think you can right click the file, select properties -> security -> advanced to see the owner and permissions.

**Comment by k-takata** [comment]
No notable changes found between 2017-06-21.2bb585fc and 2017-06-22.d87c4725.
Enabled features are the same, used compilers are the same, and configuration was not changed.

**Comment by masatake** [comment]
> Enabled features are the same, used compilers are the same, and configuration was not changed.

Thank you.
I also confirmed the commits.

**Comment by pidgeon777** [comment]
I renamed ctags.exe file:

- `ctags.first.exe` : first release, the one which works:

![image](https://user-images.githubusercontent.com/13739892/100203814-5dcc2780-2f03-11eb-810c-7c15c71524b5.png)

- `ctags.second.exe` : second release, starting from which the problem persists:

![image](https://user-images.githubusercontent.com/13739892/100203833-6290db80-2f03-11eb-8b4d-448fd7638828.png)

The permissions are the same, but for somewhat reason, it seems that the very second Ctags release introduced some mechanism which is blocked by Trend Micro.

**Comment by pidgeon777** [comment]
The IT guy has been kind enough to do a test for me by adding `ctags.exe` to the Trend Micro whitelist, and that solved the problem.

Still, it would be interesting to know why Trend Micro detected `ctags` as a virus, given that it certainly is not. When starting its execution, while it wasn't whitelisted, it tried to access a server but unfortunately I didn't remember the URL. If I recall correctly there was the *ctags* word in it.

**Comment by masatake** [comment]
> If I recall correctly there was the ctags word in it.

I think this is a secret of your organization; people can write a virus with "ctags" for attacking your organization.

I will not inspect this issue more. 
If you find a way to fix, please, report it to https://github.com/universal-ctags/ctags-win32.
