### ISSUE TITLE
Can we make inputFile tags use search pattern?

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/ctags#2754]
For now the inputFile tags always use line number in the pattern field:

``` console
$ readtags -Ene -l | head -n 1
citre   citre.el        /^(defgroup citre nil$/;"       kind:group      line:38 language:EmacsLisp      roles:def
$ readtags -Ene -Q '(eq? $extras "inputFile")' -l | head -n 1
citre-basic-tools.el    citre-basic-tools.el    1;"     kind:file       line:1  language:EmacsLisp      roles:def       extras:inputFile        end:619
```

If we could assume that all tags in a tags file use the same kind of pattern field, a client tool could cache it (i.e., whether the pattern is number/search pattern, and the search direction), so it doesn't need to infer it on each line. So, maybe use `//;"` (or `/^/;"`) for the pattern field of inputFile tags is a good idea. But it's only good when:

- Exuberant tags doesn't record inputFile tags (so we could do whatever we want).
- We are sure that other extra tags doesn't potentially have this problem, otherwise it'll be better to deal with each line separately.

I'm aware of the `TAG_OUTPUT_EXCMD` ptag, but I'm not sure when will it be `mixed`, and seems it's not very reliable. If we regenerate the tags file using `--excmd=combine`, then:

``` console
$ readtags -Q '(eq? $name "!_TAG_OUTPUT_EXCMD")' -D
!_TAG_OUTPUT_EXCMD      combineV2       /number, pattern, mixed, or combineV2/
$ readtags -Ene -Q '(eq? $extras "inputFile")' -l | head -n 1
citre-basic-tools.el    citre-basic-tools.el    1;"     kind:file       line:1  language:EmacsLisp      roles:def       extras:inputFile        end:619
```

If I believe what this ptag told me, then the pattern field of the file should be like `1;//;"`. Using `--excmd=pattern` is the same.

**Comment by AmaiKinono** [comment]
I found that when `TAG_OUTPUT_EXCMD` is `mixed`, it means that for C macros and Fortran common blocks, line numbers are used as the pattern. And Exuberant Ctags does this. So

> We are sure that other extra tags doesn't potentially have this problem

This can't be done. Although it may be possible that a client tool choose whether to do the optimization based on whether `TAG_OUTPUT_EXCMD` is `mixed`, the implementation will be overly complicated.

So I'll close this issue for now. But if anyone is interested in this topic, please reopen it.

**Comment by masatake** [comment]
`F/file` kind is a wart of ctags. Though I added `epoch:` field to the kind, I think we should not do much with `F/file` kind.

ctags made tags for language objects in input files. input files are not language objects in input files.
I wrote "wart" in this meaning. I repeatedly tried to delete `F/file` from ctags. However, I didn't it because the impact might be too large. Removing `F/file` is just another issue for the maintainer of Galaxy-ctags:-P

If we have much time, I think it is better to introduce a new language called "filesystem" or "fs" to deal with input files.
We can regard input files are language objects in a file system.
The filesystem special parser(?) tags input files and directories in source trees.

When thinking about extending ctags,  imagine the 3 pairs: input source file, command lines, and ideal tags output.

input.tree:
```
$ tree ctags                                                                                                                              
ctags                                                                                                                                                         
├── configure.ac                                                                                                                                              
├── main                                                                                                                                                      
│   ├── ctags.h                                                                                                                                               
│   └── main.c                                                                                                                                                
├── Makefile.am                                                                                                                                               
└── README.md                                                                                                                                                 
```

cmdline: `./ctags -o - --languages=filesystem ---fields=+KlsZ R ctags`

tags output:
```
Makefile.am     ctags/Makefile.am       1;"     buildScript     language:fileSystem     content:Automake        epoch:1607545716        scope:ctags
README.md       ctags/README.md 1;"     document        language:fileSytem      content:Markdown        epoch:1607545748        scope:ctags
configure.ac    ctags/configure.ac      1;"     buildScript     language:fileSystem     content:Autoconf        epoch:1607545721        scope:ctags
ctags.h ctags/main/ctags.h      1;"     programCode     language:fileSystem     content:C++     epoch:1607545721        scope:ctags/main
main.c  ctags/main/main.c       1;"     programCode     language:fileSystem     content:C       epoch:1607545730        scope:ctags/main
main    ctags   1;"     directory       language:fileSystem     scope:ctags
ctags   .       1;"     topDirectory       language:fileSystem     scope:.
tags    ctags/tags      1;"     codeIndex       language:fileSystem     content:tags    epoch:1607545730        scope:ctags
```

By introducing fileSystem parser, we cat put much metadata about input source tree (!= input source file) to a tags file in a natural way. This may need to allow ctags dealing with source trees.
The knowledge about source trees can be used for implementing (and improving) "--update" option and the multip-pass parsing.

I myself don't understand the fileSystem parser enough. I'm still exploring the idea.

**Comment by AmaiKinono** [comment]
> Galaxy-ctags

I'm literally laughing at this!

> ctags made tags for language objects in input files. input files are not language objects in input files.

I think I understand this. `kind` is really not the right concept for this.

> introduce a new language called "filesystem" or "fs"

There's one problem: the `language:` field is not enabled by default (e.g. when using `$ ctags -R`), so it's not easy to tell if a tag is a file. This could cause troubles for auto-completion or go to definition tools. If this is the consideration, maybe using `kind` as an indicator is the only solution (and actually you could even get rid of the `kind` field, then we really can't do anything about it).

> `scope:ctags`

Should this be `scope:directory:ctags` or something like that? I think the `scope` field should always been `scope:scope-kind:scope-name` (see `$readtags -H filter`). And, maybe this field is not really necessary because everything is already in the `input` field.

> This may need to allow ctags dealing with source trees.

I haven't though much on this, but my thought is: To handle source trees, we need reference tags for external modules, and a way to find where are those modules defined. From what I've seen, there are basically 2 kind of designs on this:

1. Languages that have file-level scope uses files as modules. They have rules on where to find these modules, e.g. search in the same directory first, then some path like `PYTHONPATH` or what's specified in the build system. What we have to do is follow their rules, and ask the user to offer paths for searching when necessary.

2. Languages that doesn't have file-level scope, like Ruby or Julia. Modules are defined using a block of code, and not a file, but the language need some way to locate a file to find the module (after all it can't search the whole filesystem). Here's some design I know:

   - I don't know how's the standard modules handled in Ruby, but to use a module from an arbitrary file, you `include` that file, and that takes all the modules in it into current module.
   - In Julia, the standard and installed modules are put in `LOAD_PATH`, and the module and the file have to have the same name to allow Julia to be able to find it. If you want to use a module in an arbitrary file (and they don't need to have the same name), you `include` that file first, then `using` or `import` the module in it. This should be used only in the internal of a package since `include` has the side-effect of actually eval the file, which is different from `include` in Ruby.

   So it is like 1, but added another layer of complexity (of knowing what modules are defined in a file), and we need multi-pass parsing for this. But anyway, for the part of finding the file, we just follow the rules of the languages.

Based on these thinking, I don't think we need `fileSystem` tags to handle source tree. Quite the contrary, that handling source tree could make `fileSystem` more useful: The user could use it to know which are exactly the files that's tagged.

BTW, should we open a new issue to track the discussion?
