### ISSUE TITLE
readtags: `concat` and `regexp-quote` operators

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2824]
I think we need a `regexp-quote` operator.

A client tool may need to build regexp using literal strings, and it needs to make sure the generated regexp does match that string, by wrapping it in this operator.

Emacs and Vim both doesn't use POSIX extended regexp, so the built-in `regexp-quote` in editors is not reliable.

*Edit:* Just found that this may be more complicated than I thought:

- `concat` may be needed too, if we want to "build" a regexp inside readtags.
- We need to remove the limitation that the 1st arg of `regexp->string` must be a string literal (so we can write.

Maybe it's more realistic to figure out how to implement a `regexp-quote` for ERE in the client tool.

_Originally posted by @AmaiKinono in https://github.com/universal-ctags/ctags/issues/2475#issuecomment-765146595_

**Comment by AmaiKinono** [comment]
I have an irrelevant question. Since most (or all) operators in readtags are pure, can we "compile" the expression first and eval those values that can be determined? Otherwise we need to build the same regexp on every line.

**Comment by masatake** [comment]
The current version compiles the pattern when reading the S expression.
To solve this issue, we must change `regexp->string`. If an object other than string literal is given, `regexp->string` must delay the compilation.

**Comment by AmaiKinono** [comment]
By "compile the expression" I mean every subtree of the whole post-processing expression. For example:

``` lisp
(concat "reference" "|" "fileScope")
```

This can be evaluated when reading. But

``` lisp
(concat $name "/")
```

This must be evaled when processing. Then if we use them as regexp:

``` lisp
;; This can be compiled.
(string->regexp (concat "reference" "|" "fileScope"))
;; This can't.
(string->regexp (concat $name "/"))
```

**Comment by masatake** [comment]
https://github.com/universal-ctags/ctags/blob/78621a0acc4fc39639be6bf90c219586229b1903/dsl/dsl.c#L450

**Comment by masatake** [comment]
Try #2836.

I added concat (string-append), regexp-quote, and print-code. 
print-code does the same as print but it works at compile time.

`regex-string` accepts a context variable like $name.
