### ISSUE TITLE
make check failed due to ./misc/units[779]: syntax error: `"$file"' missing expression operator when running on OpenBSD6.8

### ISSUE THREAD

**Issue by leleliu008** [universal-ctags/ctags#2827]
**Running the following code in the terminal on OpenBSD 6.8:**
```
sudo pkg_add git automake-1.16.2

export AUTOCONF_VERSION=2.69
export AUTOMAKE_VERSION=1.16

export CFLAGS='-I/usr/local/include -L/usr/local/lib'

sudo ln -s /usr/local/lib/libiconv.so.* /usr/local/lib/libiconv.so

git clone https://github.com/universal-ctags/ctags
cd ctags
./autogen.sh
./configure
make
make check
```
**the `make check` report following:**
```
REPOINFO   main/repoinfo.h
RUN      tmain
./misc/units[779]: syntax error: `"$file"' missing expression operator
*** Error 1 in /home/vagrant/ctags (Makefile:6070 'tmain': @echo "  RUN      tmain";  if test -n "${ZSH_VERSION+set}"; then set -o SH_WORD_S...)
```

**relevant code:** [click me](https://github.com/universal-ctags/ctags/blob/master/misc/units#L779)

**the reason:** the **OpenBSD sh** not support `[[ a =~ b ]]` feature. 

**the solution:** use POSIX sh code as follow:
```
failure_in_globing() {
    # skip if globing failed, also ignore backup files
    case $1 in
        *\~)  return 0 ;;
        *\**) return 0 ;;
         *)   return 1 ;;
    esac
}
```

**Comment by masatake** [comment]
Just a qusetion. Do you mean OpenBSD sh has `[[` built-in command or OpenBSD has `[[` as a command but the command doesn't have `=~` ?

----

Could you make a pull request (and merge?)

BTW, if python is installable on the environement, I highly recommend you to use misc/units.py instead of misc/units.
misc/units.py executes multiple test cases in parallel.  In some minor reasons, I kept misc/units.

**Comment by leleliu008** [comment]
@masatake Yes, `OpenBSD sh` has `[[` built-in command, but it does't support `=~` operator.

**Comment by masatake** [comment]
> @masatake Yes, OpenBSD sh has [[ built-in command, but it does't support =~ operator.

Finally I understand why I should study python.

**Comment by leleliu008** [comment]
@masatake as we all known, there is no silver bullet. I think we should depend on CI to find problems. I have been testing OpenBSD and NetBSD CI, if finished, I will make a PR.
