### ISSUE TITLE
packcc is not rebuilt automatically (Was: unable to build on ctags on linux)

### ISSUE THREAD

**Issue by carand** [universal-ctags/ctags#2831]
Hello anyone,

It' looks that there is a bug in your build process. I'm unable to build ctags from master branch.
commit 3a88dc2e4d65e64b24612c610d588d0690cb0ca0 (HEAD, origin/master, origin/HEAD, master)

when running make I get the the following error: 
REPOINFO   main/repoinfo.h
PACKCC     peg/varlink.c
packcc: Invalid option '-i'

**Comment by leleliu008** [comment]
@carand  please provide as much information as possible. What's distribution and version of your Linux?

**Comment by ksamborski** [comment]
You have an old compiled packcc binary. 
Please remove it: `rm misc/packcc` and update its sources: `cd misc && ./pull-packcc.sh`
After that it `make` should compile everything again.

**Comment by carand** [comment]
Thanks for help. It works now.

**Comment by carand** [comment]
> @carand please provide as much information as possible. What's distribution and version of your Linux?

Linux Mint 19, 64 bit version

**Comment by masatake** [comment]
Looks strange. I expect all works fine just after doing git pull at the top of the ctags source tree.

**Comment by leleliu008** [comment]
@masatake Yes, I wonder why this happened too. 

I tested on `LinuxMint 19.3 amd64` using following instructions:
```
# automake, autoconf, make, gcc, git are pre-installed

apt install -y pkg-config

git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure
make
```
It worked well!

@carand could you tell us  how to reproduce this issue?

**Comment by ksamborski** [comment]
It happened to me before as well. I had a cloned source tree that wasn't used for a few months and when I updated it using `git pull` it didn't compile (because of the outdated packcc binary).

**Comment by leleliu008** [comment]
run `make clean` before `make` are recommended. but most people don't do this, so our build system can do it to avoid this problem.

**Comment by k-takata** [comment]
We had used git-submodule for misc/packcc/ two years ago, and switched to git-subtree.
That could cause some issues, but not sure this is the case.

**Comment by leleliu008** [comment]
right way to compile `universal-ctags` from github source tree:

```
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure
make

# a few days later
cd ctags
git pull

if [ -f Makefile ] ; then
    make distclean
fi

./autogen.sh
./configure
make


```

**Comment by leleliu008** [comment]
@masatake what do you think about update [How to build and install](https://github.com/universal-ctags/ctags#how-to-build-and-install) block of our `REDME.md` as follows:

To build with `Autotools` (`Autoconf`, `Automake`) on `GNU/Linux`, `macOS`, `FreeBSD`, `OpenBSD`, `NetBSD`, `msys2`, `Windows 10 WSL`

If you **don't have** a local copy of our remote repository on your machine, follow the instructions below: 
```
$ git clone https://github.com/universal-ctags/ctags.git
$ cd ctags
$ ./autogen.sh
$ ./configure --prefix=/where/you/want # defaults to /usr/local
$ make
$ make install # may require extra privileges depending on where to install
```

If you **already have** a local copy of our remote repository on your machine, follow the instructions below: 
```
$ cd ctags
$ git pull
$
$ [ -f Makefile ] && make distclean
$
$ ./autogen.sh
$ ./configure --prefix=/where/you/want # defaults to /usr/local
$ make
$ make install # may require extra privileges depending on where to install
```

**Comment by carand** [comment]
> @masatake Yes, I wonder why this happened too.
> 
> I tested on `LinuxMint 19.3 amd64` using following instructions:
> 
> ```
> # automake, autoconf, make, gcc, git are pre-installed
> 
> apt install -y pkg-config
> 
> git clone https://github.com/universal-ctags/ctags.git
> cd ctags
> ./autogen.sh
> ./configure
> make
> ```
> 
> It worked well!
> 
> @carand could you tell us how to reproduce this issue?
Just checkout an old  commit of this repo and make sure that packcc is is outdated. Then update to newest version. Packcc will be not updated to newest version, if it exists.  Then do: ./autogen.sh && ./configure && make

Unfortunately, I can't   say which commit I checked out before update.  I guess, just remove the Makefile  will not work because the Makefile will  be  generated by autogen.sh and ./configure  Isn't it?  You missing a rule where packcc version is checked if it exist. For my self I work with cmake so I do not can say where you need to add the rule.

Best regards

**Comment by masatake** [comment]
I don't have enough time to work on this topic now.
However, I found the way to reproduce the original issue when hacking R parser.

```
git checkout 25ec6aefd5083ccfcf92f272f2914cfb85028613^
bash autogen.sh
./configure
make
git checkout master
bash autogen.sh
./configure
make
```

I saw:
```
PACKCC     peg/varlink.c
packcc: Invalid option '-i'

Usage: packcc [OPTIONS] [FILE]
Generates a packrat parser for C.

  -o BASENAME  specify a base name of output source and header files
  -d           with debug information
  -h           print this help message and exit
  -v           print the version and exit
```
I remembered I added -i option.

The following change fixed the issue:
```
[jet@living]~/var/ctags-new% git diff                                              
diff --git a/Makefile.am b/Makefile.am
index c0ff70d2..6c4c429a 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -47,7 +47,7 @@ endif
 
 PACKCC = $(top_builddir)/packcc$(BUILD_EXEEXT)
 
-$(PACKCC):
+$(PACKCC): $(top_srcdir)/misc/packcc/packcc.c
        $(CC_FOR_BUILD) $(CFLAGS_FOR_BUILD) $(CPPFLAGS_FOR_BUILD) $(EXTRA_CPPFLAGS_FOR_BUILD) $(LDFLAGS_FOR_BUILD) -o $@ $(top_srcdir)/misc/packcc/packcc.c
 
 if USE_READCMD
```

@leleliu008, how do you think this fix?
I will read the discussion held here later.

**Comment by masatake** [comment]
The change for the document looks improvement. However, I hope we can remove
```
$ [ -f Makefile ] && make distclean
```
from the instructions.
In addition, I think "make installl" should be optional. Actually I don't install it at all. I need e-ctags (installed via yum) to study its behavior.

**Comment by leleliu008** [comment]
@masatake good solution. this will trigger `make` to rebuild `$(PACKCC)` once `$(top_srcdir)/misc/packcc/packcc.c` changed even if `$(PACKCC)` is not changed.

**Comment by masatake** [comment]
@leleliu008, thank you. I will make a pull request.

**Comment by masatake** [comment]
@leleliu008, I thought about your proposal about updating the document.

I would like to reject it two reasons.
1. I don't want us to teach the very basic usage and conept of git to USERS.
2. we lost chances getting bug report like this issue.

This is my idea. @hirooih, how do you think?

**Comment by hirooih** [comment]
I just read this thread.

```
-$(PACKCC):
+$(PACKCC): $(top_srcdir)/misc/packcc/packcc.c
```

This should fix the root cause of this issue.
I think we should not add unnecessary step.

@leleliu008 proposed updating the document before this solution was proposed.
I think he also agrees with us.

**Comment by leleliu008** [comment]
@masatake @hirooih I personally have no objection.
