### ISSUE TITLE
How to index C headers of the project?

### ISSUE THREAD

**Issue by psprint** [universal-ctags/ctags#2832]
I've done many tries and I gave up: I just cannot generate tags for headers in my project other way than:
```
/usr/local/bin/ctags -e -R --c-kinds=+px --fields=+iaS --extra=+q  .
```

I.e.: without selecting `--languages=c`, what means that ctags will interpret all files, Makefiles.in, even READMEs…

My question is: how to parse only C files **and** index also C headers?

**Comment by masatake** [comment]
`.h` is associated to C++ language. You must fix it to fit ctags to your purpose.
Use `--langmap` option like:

```
$ u-ctags --options=NONE -e -R --languages=C --langmap=C:.h.c --kinds-c=+px --fields=+iaS --extras=+q .
```

**Comment by psprint** [comment]
Thanks, this works.

**Comment by masatake** [comment]
An alternative solution is:
```
$ u-ctags --options=NONE -e -R --languages=C,C++ --kinds-c=+px --kinds-c++=+px --fields=+iaS --extras=+q .
```
I guess --kinds-c++=+px is not needed because some kinds of C and C++ are synchronized internally.
