### ISSUE TITLE
Is there a support for fields/extras in Emacs TAGS file format?

### ISSUE THREAD

**Issue by psprint** [universal-ctags/ctags#2854]
I've noted that setting the --fields and --extras options doesn't have any effect for etags output file format. Is there no support for them, e.g.: for the k/K kind field, either one letter or full text? Could such support be added, i.e.: the etags format gracefully extended with it, preserving backwards compatibility (or not, if it will be impossible)?

**Comment by masatake** [comment]
About fields, There is no such concept in TAGS. If you need fields in TAGS output, you must extend the format itself first.
ctags should emit the most of all extra tags even when in TAGS output mode (-e).

```
[jet@living]~/var/ctags-new% cat /tmp/foo.c
cat /tmp/foo.c
struct point {
  int x, y;
};
[jet@living]~/var/ctags-new% ./ctags --extras=+'{qualified}' -e -o - /tmp/foo.c
./ctags --extras=+'{qualified}' -e -o - /tmp/foo.c

/tmp/foo.c,115
struct point {point1,0
  int x, y;x2,15
  int x, y;point::x2,15
  int x, y;y2,15
  int x, y;point::y2,15
[jet@living]~/var/ctags-new% ./ctags --extras=+q -e -o - /tmp/foo.c
./ctags --extras=+q -e -o - /tmp/foo.c

/tmp/foo.c,115
struct point {point1,0
  int x, y;x2,15
  int x, y;point::x2,15
  int x, y;y2,15
  int x, y;point::y2,15
[jet@living]~/var/ctags-new% ./ctags -e -o - /tmp/foo.c
./ctags -e -o - /tmp/foo.c

/tmp/foo.c,63
struct point {point1,0
  int x, y;x2,15
  int x, y;y2,15
```

If you insist using Emacs like me, I recommend you to look into [citre](https://github.com/AmaiKinono/citre), 
an emacs lisp that utilizes tags output, not TAGS output is an option.

**Comment by masatake** [comment]
BTW, you look like a zsh hacker, don't you?
I would like you to visit https://github.com/universal-ctags/ctags/issues/2845 :-)
