### ISSUE TITLE
Tests fails on x86_64-musl

### ISSUE THREAD

**Issue by Eluminae** [universal-ctags/ctags#2879]
Hello there,

I'm trying to package uctags for VoidLinux but I'm stuck on unit tests on the x86_64-musl arch

Here the full log:  [8_Build and check packages.txt](https://github.com/universal-ctags/ctags/files/6011503/8_Build.and.check.packages.txt)

You can find the recipe in this MR : https://github.com/void-linux/void-packages/pull/28885

Is this a known issue ? Or are we using wrong dependencies ?

Thanks a lot :D

**Comment by leleliu008** [comment]
you shoud install [GNU libiconv](https://www.gnu.org/software/libiconv/) rather than using the `musl iconv`, the reason is [here](https://wiki.musl-libc.org/functional-differences-from-glibc.html)

It seems that we can not install `GNU libiconv` via `xbps`, we can install from source, reference instructions as following:
```
curl -LO https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz
tar vxf libiconv-1.16.tar.gz
cd libiconv-1.16
./configure --enable-extra-encodings
make
make install
```

**Comment by ericonr** [comment]
Are encoding such as `cp932` common enough to warrant a dependency on `libiconv`?

**Comment by ericonr** [comment]
Or is the code tailored towards GNU semantics for `iconv` instead of the standardized ones?

**Comment by leleliu008** [comment]
@ericonr whether use `GNU libiconv` depends on what your needs are. If you want to use `cp932` like encoding, the `GNU libiconv` is a good choice, I don't know if exists other library can implements this.

**Comment by leleliu008** [comment]
@ericonr the reason of the failure is invoked `iconv_open("UTF-8", "cp932")`, the `musl iconv` not support `cp932` encoding, but `GNU libiconv` support it, if you want to run `make check`, you should install `GNU libiconv`, if you don't want to install `GNU libiconv`, jut don't run `make check`

**Comment by masatake** [comment]
> Are encoding such as cp932 common enough to warrant a dependency on libiconv?

Yes, common enough in Japan.

**Comment by masatake** [comment]
You can use `./configure --disable-iconv` to turn off the iconv feature.
If the feature is disabled, the test case is automatically skipped.

**Comment by k-takata** [comment]
It seems that musl iconv supports shiftjis:
https://github.com/esmil/musl/blob/194f9cf93da8ae62491b7386edf481ea8565ae4e/src/locale/iconv.c#L48
I think we can use shiftjis instead of cp932.
Our tests may not be affected by the differences between cp932 and shiftjis. (I haven't verified, though.)

**Comment by leleliu008** [comment]
yes, I have confirmed that our test cases passed when using `shiftjis` instead of `cp932`.

**Comment by masatake** [comment]
@k-takata, thank you for the suggestion.
@leleliu008, could you make a pull request based on the modified code at your hand and merge it?
