### ISSUE TITLE
Don't refer to CTAGS end ETAGS environment variables

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2890]
@masatake I think we shouldn't use environment variable to pass default options to ctags command. let's think about following situation:

```sh
ETAGS_OPTIONS="-e"
CTAGS_OPTIONS="-e"
ctags --version
```
In this case, how to determine `etags mode`?

1. If want to use environment variable to pass default options to ctags command. we must tell user which option can be put into the environment variable, because not all options can be put into the environment variable.
2. If the environment variable contains non-option, how to handle this situation? just ignore the non-option or ignore all options in environment variable or trigger an abort?

_Originally posted by @leleliu008 in https://github.com/universal-ctags/ctags/issues/2048#issuecomment-787277423_

**Comment by hirooih** [comment]
I think ctags(1) documents the behavior clearly.

****

-e

> ... Alternatively, if ctags is invoked by a name containing the string “etags” (either by renaming, or creating a link to, the executable), etags mode will be enabled.

ENVIRONMENT VARIABLES

> CTAGS
> If this environment variable exists, it will be expected to contain a set of default options which are read when ctags starts, after the configuration files listed in “FILES”, below, are read, but before any command line options are read.
> ...
> Only options will be read from this variable.
> ...
> ETAGS
> Similar to the CTAGS variable above,....

****

For  Q1:

```
if (ctags is invoked by a name containing the string “etags”) or (the configuration files select etags mode) ;
  ETAGS_OPTIONS is used
else
  CTAGS_OPTIONS is used
```

For Q2:

> Only options will be read from this variable.

Either ignore non-option or trigger an abort.

**Comment by leleliu008** [comment]
![image](https://user-images.githubusercontent.com/3040852/109620084-75572400-7b74-11eb-8729-9b7c75b48f82.png)

I thought `etags mode` was determined by `-e` option when run `ctags`, isn't right?

**Comment by hirooih** [comment]
I did not read #2048 when I commented on this issue.

I agree with @masatake san to rename CTAGS to CTAGS_OPTIONS.

> I thought etags mode was determined by -e option when run ctags, isn't right?

No, it is not as you and I referred ctags(1) document.

> -e
> 

>>  ... Alternatively, if ctags is invoked by a name containing the string “etags” (either by renaming, or creating a link to, the executable), etags mode will be enabled

etags mode is determined by -e option or command name.
If you rename ctags to etags, foo-etags, or etags_bar etc., etags mode is enabled.
