### ISSUE TITLE
[Feature Request] Sort tag with same name via kind priority

### ISSUE THREAD

**Issue by hiberabyss** [universal-ctags/ctags#2922]
For c/c++ function, there usually be two same tags:

* declaration tag known as `p`
* definition tag known as `f`

In most cases, I would like to jump to function definition with `c-]` in vim. However, if the `p` tag is placed before `f` tag, `c-]` will jump to the `p` tag.

Is it possible to place `f` tag before `p` in sorted tag file?

**Comment by masatake** [comment]
Sorting should be done in a client tool, not in ctags.
Did you try readtags? You can use it for sorting tags file.
```
$ cat input.ccat input.c                                                                                                                                                                 
int foo(void);
int foo(void)
{
        return 0;
}
$./ctags --kinds-C=+p input.c
$ { ./readtags -D ; ./readtags -en -S '(<or> (<> $input &input) (if (or (and (eq? $kind "f") (eq? &kind "p")) (and (eq? $kind "p") (eq? &kind "f"))) 1 0))' -l; }
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_EXCMD      mixed   /number, pattern, mixed, or combineV2/
!_TAG_OUTPUT_FILESEP    slash   /slash or backslash/
!_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/                                                                                                                        
!_TAG_PATTERN_LENGTH_LIMIT      96      /0 for no limit/
!_TAG_PROC_CWD  /home/yamato/var/ctags-github/  //
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL       https://ctags.io/       /official site/
!_TAG_PROGRAM_VERSION   5.9.0   /af3051279/
foo     input.c /^int foo(void);$/;"    kind:p  file:   language:C      typeref:typename:int
foo     input.c /^int foo(void)$/;"     kind:f  language:C      typeref:typename:int
$ { ./readtags -D ; ./readtags -en -S '(<or> (<> $input &input) (if (or (and (eq? $kind "f") (eq? &kind "p")) (and (eq? $kind "p") (eq? &kind "f"))) -1 0))' -l; }
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_EXCMD      mixed   /number, pattern, mixed, or combineV2/
!_TAG_OUTPUT_FILESEP    slash   /slash or backslash/
!_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/                                                                                                                        
!_TAG_PATTERN_LENGTH_LIMIT      96      /0 for no limit/
!_TAG_PROC_CWD  /home/yamato/var/ctags-github/  //
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL       https://ctags.io/       /official site/
!_TAG_PROGRAM_VERSION   5.9.0   /af3051279/
foo     input.c /^int foo(void)$/;"     kind:f  language:C      typeref:typename:int
foo     input.c /^int foo(void);$/;"    kind:p  file:   language:C      typeref:typename:int
```

See ctags-clinet-tools(7) man page for more details.

**Comment by hiberabyss** [comment]
> Sorting should be done in a client tool, not in ctags.
> Did you try readtags? You can use it for sorting tags file.
> 
> ```
> $ cat input.ccat input.c                                                                                                                                                                 
> int foo(void);
> int foo(void)
> {
>         return 0;
> }
> $./ctags --kinds-C=+p input.c
> $ { ./readtags -D ; ./readtags -en -S '(<or> (<> $input &input) (if (or (and (eq? $kind "f") (eq? &kind "p")) (and (eq? $kind "p") (eq? &kind "f"))) 1 0))' -l; }
> !_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
> !_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
> !_TAG_OUTPUT_EXCMD      mixed   /number, pattern, mixed, or combineV2/
> !_TAG_OUTPUT_FILESEP    slash   /slash or backslash/
> !_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/                                                                                                                        
> !_TAG_PATTERN_LENGTH_LIMIT      96      /0 for no limit/
> !_TAG_PROC_CWD  /home/yamato/var/ctags-github/  //
> !_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
> !_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
> !_TAG_PROGRAM_URL       https://ctags.io/       /official site/
> !_TAG_PROGRAM_VERSION   5.9.0   /af3051279/
> foo     input.c /^int foo(void);$/;"    kind:p  file:   language:C      typeref:typename:int
> foo     input.c /^int foo(void)$/;"     kind:f  language:C      typeref:typename:int
> $ { ./readtags -D ; ./readtags -en -S '(<or> (<> $input &input) (if (or (and (eq? $kind "f") (eq? &kind "p")) (and (eq? $kind "p") (eq? &kind "f"))) -1 0))' -l; }
> !_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
> !_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
> !_TAG_OUTPUT_EXCMD      mixed   /number, pattern, mixed, or combineV2/
> !_TAG_OUTPUT_FILESEP    slash   /slash or backslash/
> !_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/                                                                                                                        
> !_TAG_PATTERN_LENGTH_LIMIT      96      /0 for no limit/
> !_TAG_PROC_CWD  /home/yamato/var/ctags-github/  //
> !_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
> !_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
> !_TAG_PROGRAM_URL       https://ctags.io/       /official site/
> !_TAG_PROGRAM_VERSION   5.9.0   /af3051279/
> foo     input.c /^int foo(void)$/;"     kind:f  language:C      typeref:typename:int
> foo     input.c /^int foo(void);$/;"    kind:p  file:   language:C      typeref:typename:int
> ```
> 
> See ctags-clinet-tools(7) man page for more details.

Thanks for your reply! I will have a try.

**Comment by masatake** [comment]
I hope readtags may help you.
If you get a trouble, please, reopen this.
