### ISSUE TITLE
BibTeX parser: Please add ':' to isIdentChar()

### ISSUE THREAD

**Issue by berndf** [universal-ctags/ctags#2934]
Hello,

recently gentoo updated to ctags-20210321.0. I've been using BibTeX tag generation for a long time via my own BibTeX.ctags file. Since my BibTeX keys are of the form author:year (one of the more common choices I'd say), the new bibtex parser breaks ctags for me, as isIdentChar() does not allow a colon.

Could you either make IdentChars configurable somehow or include the following simple patch?

```
Index: ctags-p5.9.20210321.0/parsers/bibtex.c
===================================================================
--- ctags-p5.9.20210321.0.orig/parsers/bibtex.c
+++ ctags-p5.9.20210321.0/parsers/bibtex.c
@@ -33,7 +33,7 @@
 #define isType(token,t)		(bool) ((token)->type == (t))
 #define isKeyword(token,k)	(bool) ((token)->keyword == (k))
 #define isIdentChar(c) \
-	(isalpha (c) || isdigit (c) || (c) == '_' || (c) == '-' || (c) == '+')
+	(isalpha (c) || isdigit (c) || (c) == '_' || (c) == '-' || (c) == '+' || (c) == ':')
 
 /*
  *	 DATA DECLARATIONS

```

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 30 2021, 09:48:49
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +sandbox, +packcc
```

How do you get ctags binary:

via gentoo portage

**Comment by masatake** [comment]
Thank you for spotting the issue. I would like to get this as a pull request.
In addition, I would like you to include a test case to the pull request.

Add an entry include `:` to Units/parser-bibtex.r/bib-simple.d/input.bib.
Update Units/parser-bibtex.r/bib-simple.d/expected.tags.

See https://docs.ctags.io/en/latest/testing.html#units-test-facility for more details.

For the commit log, I would like you to use "bibtex: " as the prefix of the header.

**Comment by masatake** [comment]
See #2954.
