### ISSUE TITLE
.ctags at the project root ignored

### ISSUE THREAD

**Issue by terceiro** [universal-ctags/ctags#2939]
Hi. I used exuberant-ctags for a long time, and it supported having a single `.ctags` at the project root. This was very convenient for example to exclude local generated directories. I had `.ctags` files in a lot of my projects.

I recently discovered universal-ctags, and started trying it out, but this breaks my usage on all projects since my `.ctags` files now are ignored. Could we have reading `.ctags` from the current directory available again?

**Comment by masatake** [comment]
No.  The .ctags format used in u-ctags is not compatible with e-ctags. If u-ctags reads $project/.ctags, it may cause troubles.
