### ISSUE TITLE
Feature request: --c-kinds=+c for case labels

### ISSUE THREAD

**Issue by psprint** [universal-ctags/ctags#2945]
The name of the parser:

C

The command line you used to run ctags:

	ctags -e -R --languages=C,Slang --langmap=C:.h.c --c-kinds=+px \
		--extras=-{anonymous} --extras=+r \
		--fields=+S --fields-c=+{macrodef} \
		--pattern-length-limit=250; \

The content of input file:

```C
/* THIS IS AN EXAMPLE */
int
main(void)
{

int enum = Enum_2;

switch(enum);
{
    case Enum_1:
        …
        break;
    case Enum_2
        …
       break;
    … 
    …   
}

}
```
The tags output you are not satisfied with:

```
!_THIS_IS_AN_EXAMPLE

```

The tags output you expect:

```
!_THIS_IS_AN_EXAMPLE
Enum_1	foo.c	/^case Enum_1$/;"	kind:case-label	line:2	language:C	
Enum_2	foo.c	/^case Enum_1$/;"	kind:case-label	line:10	language:C	...
...
```

The version of ctags:

5.9.0(d32c7730)

```
$ ctags --version
Universal Ctags 5.9.0(d32c7730), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan 20 2021, 12:56:25
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +packcc
```

**Comment by masatake** [comment]
Interesting request. However I think it is better not to support the case label though goto label is supported.

Could you tell me the use case?
For showing source code tree?

For 
```
     case Enum_1 + 1:
     ...
        break;
```
, what ctags should tag? `Enum_1 + 1` or `Enum_1`?

`Enum_1` is not defined here. So it is not tagged as a definition tag.
`Enum_1` can be tagged as a reference tag.

**Comment by psprint** [comment]
The source that made this idea is Midnight Commander large functions for handling commands like Edit, Search, etc. – they're implemented as case blocks, see [here](https://github.com/neo-mc/neo-mc/blob/main/src/editor/edit.c#L3535).

```C
     case Enum_1 + 1:
     ...
        break;
```
I think that it should, if it can, tag Enum_1 + i.

**Comment by masatake** [comment]
In such a case, adding patterns to the C parser may be enough.
```
[jet@living]/tmp% cat /tmp/mc.ctags 
--kinddef-C=C,caselabel,case labels
--regex-C=/[ \t]*case[ \t]*([^:]*[^ \t]*)[ \t]*:/\1/C/{exlusive}
--regex-C=/[ \t]*(default)[ \t]*:/\1/C/
[jet@living]/tmp% cat foo.c 
#include "cmd.h"

void
dispatch(int cmd)
{
  switch (cmd) {
  case EDITOR_FILE_OPEN:
    file_open();
    break;
  case EDITOR_EDIT_CUT:
    edit_cut(0);
    break
  case EDITOR_EDIT_CUT + 1:
    edit_cut(1);
    break      
  case EDITOR_EDIT_PASTE:
    edit_paste();
    break;
  default:
    break;
  }
}
[jet@living]/tmp% u-ctags -o - --options=/tmp/mc.ctags foo.c 
EDITOR_EDIT_CUT	foo.c	/^  case EDITOR_EDIT_CUT:$/;"	C
EDITOR_EDIT_CUT + 1	foo.c	/^  case EDITOR_EDIT_CUT + 1:$/;"	C
EDITOR_EDIT_PASTE	foo.c	/^  case EDITOR_EDIT_PASTE:$/;"	C
EDITOR_FILE_OPEN	foo.c	/^  case EDITOR_FILE_OPEN:$/;"	C
default	foo.c	/^  default:$/;"	C
dispatch	foo.c	/^dispatch(int cmd)$/;"	f	typeref:typename:void
[jet@living]/tmp% 
```

See mc.ctags. If you are satisfied with the result, move mc.ctags to ~/.ctags.d. So you don't have to specify `--options=/tmp/mc.ctags` every time you run ctags.

I have a plan to fill scope: fill or tags extracted wth `--regex-C=` patterns.
