### ISSUE TITLE
Can't seem to add a header file extension to default list

### ISSUE THREAD

**Issue by articuluxe** [universal-ctags/ctags#2950]
My c++ project has another header file extension, .ipp
If I specify this extension as augmenting the default, most .hpp files are ignored.  i.e. they are present in the tags output file, but with no entries.

-h=+.ipp.

Even though the man page specifies that starting the -h value with + will add to the defaults.

I have to specify -h=.ipp.hpp. in order for it to work in all cases.
Please note, when it does not work, 2 of my project's .hpp files are still indexed

*****

The name of the parser:

Recent universal ctags compiled from master a month ago.

The command line you used to run ctags:

```
exctags -Re --kinds-c++=+l --extras=-F --tag-relative=no --language-force=c++ -h="+.ipp." -f test-tags source_dir
```

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0(p5.9.20210307.0)
[snip]
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +json, +interactive, +case-insensitive-filenames, +packcc
```

How do you get ctags binary:

(
Building it locally, via GNU/Linux distribution, as BSD's package,
)

**Comment by masatake** [comment]
Thank you. Reproduced.

**Comment by masatake** [comment]
What you specified, 
```
-h="+.ipp."
```
is wrong. This should be:
```
-h "+.ipp."
```
.
