### ISSUE TITLE
Markdown: ctags default markdown excludes headings.

### ISSUE THREAD

**Issue by rickalex21** [universal-ctags/ctags#2965]
Thanks for the continuation of ctags development. I think there may be a problem with the default
regex in markdown. It is skipping a heading that has a code block before it.

My ctags version that I installed with brew.

```sh
Universal Ctags 5.9.0(57e7caed), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Apr 17 2021, 19:23:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +packcc
```

My command.

```sh
ctags --options=NONE -f $code/.tags --languages=markdown  -R $code/
```

The markdown section that is skipped is '### Mline'. This is not the front matter of the
markdown file this was a yaml code block in the markdown file. I was writing a tutorial
on ctags.

~~~markdown

I will be capturing these animal tags with ```--_mtable-regex```.

```yaml
---
title: "Animals"
date: 2021-04-17T14:22:02-05:00
draft: false
tags: ['dog','cat','bear','lion','monkey','tiger','dolphin','elephant','whale']
---
```

### Mline

---

~~~

I fixed the problem by commenting out all the tables with code blocks in [this file.](https://github.com/universal-ctags/ctags/blob/e82e9e07ad4c84ce4d7a1c39080eaabddfaba48a/optlib/markdown.ctags)
I have no use for tagging code blocks, but I'm sure other people use them for?
 I have a lot of code blocks in random files so this would end me up with like 100 ```sh tags.

```sh
--langdef=defaultmd
--map-defaultmd=+.md
--map-defaultmd=+.pdc

# Handle GFM style codeblock in this table.
# https://github.github.com/gfm/#fenced-code-blocks
#--_tabledef-defaultmd=codeblockBacktick
#--_tabledef-defaultmd=codeblockTildes
```

After commenting all the tables, it works fine now I can see the tag 'mline'. So it looks like
there's a regex that needs to be fixed in the default markdown file?

**Comment by masatake** [comment]
The code block detection should have a higher priority than the code for detecting a section.
However, the original code had the wrong order of priorities. After reversing the order, 'Mline` is tagged well.

Could you try the following change and run "make"?

```
diff --git a/optlib/markdown.ctags b/optlib/markdown.ctags
index 4b680ad5d..349dc3e5c 100644
--- a/optlib/markdown.ctags
+++ b/optlib/markdown.ctags
@@ -94,9 +94,9 @@
 
 --_mtable-regex-Markdown=main/^#//{_advanceTo=0start}{tjump=main_sharp}
 --_mtable-extend-Markdown=main+emptyLine
+--_mtable-extend-Markdown=main+code
 --_mtable-regex-Markdown=main/^([^\n]+)[\n]=+[\n]/\1/c/{_field=sectionMarker:=}{scope=push}{tenter=chapter}
 --_mtable-regex-Markdown=main/^([^\n]+)[\n]-+[\n]/\1/s/{_field=sectionMarker:-}{scope=push}{tenter=section}
---_mtable-extend-Markdown=main+code
 --_mtable-extend-Markdown=main+rest
```

I will make a pull request for this change when I find a time.

**Comment by rickalex21** [comment]
Thanks, that works! :)

So, since I don't know how to avoid the error ```language already exists``` what I ended up doing was
applying the patch to ~/.ctags.d/markdownNew.ctags and I changed everything to markdownNew. This
will work for me until the patch is applied and I can reinstall with brew.

```sh
ctags --fields=+n -f $code/.tags --languages=markdownNew -R $code/
```
>I have no use for tagging code blocks, but I'm sure other people use them for?
I have a lot of code blocks in random files so this would end me up with like 100 ```sh tags.

It looks like with this patch the tags for code blocks are gone. Which, for me it's not a big deal because
I would not do this:


~~:tag ```sh~~

**Comment by masatake** [comment]
Even with the patch,  the tags for code blocks are not gone.
However, `--extras={guest}' is needed to extract them.

```
[jet@living]~/var/ctags-github% cat input.md
cat input.md
I will be capturing these animal tags with ```--_mtable-regex```.

```sh
hello()
{
	echo "hello"
}
```

### Mline

---
[jet@living]~/var/ctags-github%  ./ctags -o - --extras=+'{guest}' input.md 
Mline	input.md	/^### Mline$/;"	S
hello	input.md	/^hello()$/;"	f
```

> I don't know how to avoid the error language already exists what I ended up doing was
applying the patch to ~/.ctags.d/markdownNew.ctags and I changed everything to markdownNew. 

What you did was correct.  I have a tip for the situation.
`--_pretend-<NewLang>=<OldLang>` is an option for people reimplementing an existing parser.

You can use the option at the end of markdownNew.ctags:
```
...
--languages=-Markdown
--_pretend-MarkdownNew=Markdown
```

The markdownNew parser works as if it is Markdown parser. See language: field of the following output:
```
[jet@living]~/var/ctags-github% tail -5 markdownnew.ctags
--_mtable-regex-MarkdownNew=codeblockTildes/^[ \t]*~~~~*[ \t]*[\n]//{tleave}{_guest=,,0start}
--_mtable-extend-MarkdownNew=codeblockTildes+rest

--languages=-Markdown
--_pretend-MarkdownNew=Markdown
[jet@living]~/var/ctags-github% ./ctags --options=markdownnew.ctags -o - --extras=+'{guest}' --fields=+'{language}' input.md 
Mline	input.md	/^### Mline$/;"	S	language:Markdown
hello	input.md	/^hello()$/;"	f	language:Sh
```
