### ISSUE TITLE
Markdown: overlapping sections

### ISSUE THREAD

**Issue by cvkbtzx** [universal-ctags/ctags#2991]
The name of the parser:
Markdown

The command line you used to run ctags:

```
$ ctags --options=NONE -f- -n -u --fields=+ZSei ./README.md
```

The content of input file:
https://raw.githubusercontent.com/Erkaman/vulkan_minimal_compute/master/README.md

The tags output you are not satisfied with:

```
Vulkan Minimal Compute	./README.md	1;"	c	end:14
Demo	./README.md	14;"	c	end:26
Building	./README.md	20;"	s	scope:chapter:Demo	end:26
```

* The 1st section "_Vulkan Minimal Compute_" ends at line 14, which overlaps the following one "_Demo_" also starting at line 14.

The tags output you expect:

```
Vulkan Minimal Compute	./README.md	1;"	c	end:13
Demo	./README.md	14;"	c	end:26
Building	./README.md	20;"	s	scope:chapter:Demo	end:26
```

* Expect 1st section "_Vulkan Minimal Compute_" to end at line 13.

The version of ctags:
p5.9.20210502.0

```
$ ctags --version
Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May  2 2021, 21:44:15
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +packcc
```

How do you get ctags binary:
Local build

**Comment by masatake** [comment]
I think it is impossible to fix this in the current ctags.
Arithmetic operators are needed.

**Comment by masatake** [comment]
#2922 fixes the issue.

**Comment by masatake** [comment]
Thank you for reporting. The change for fixing is merged. Please try the latest code.

**Comment by cvkbtzx** [comment]
Hello,
Tested commit bd44a46, issue is now fixed, thanks a lot!
