### ISSUE TITLE
ctags supported features differences between UNIX and Windows

### ISSUE THREAD

**Issue by leleliu008** [universal-ctags/ctags#3005]
1. I find `mk_mvc.mak` doesn't define `READTAGS_DSL` macro,  so `dsl/sorter.h` `dsl/qualifier.h` `dsl/dsl.c` are not used on Windows, I want to known why?

**extra-cmds/readtags-cmd.c:**
```
#ifdef READTAGS_DSL
    #include "dsl/qualifier.h"
    static QCode *Qualifier;

    #include "dsl/sorter.h"
    static SCode *Sorter;
#endif
```

2. there is an executable named `mini-geany` generated on UNIX , but on Windows don't generate it, why? and why don't install it?

**Comment by masatake** [comment]
>1. I find mk_mvc.mak doesn't define READTAGS_DSL macro, so dsl/sorter.h dsl/qualifier.h dsl/dsl.c are not used on Windows, I want to known why?

This is just my mistake. 

> 2. there is an executable named mini-geany generated on UNIX , but on Windows don't generate it, why? and why don't install it?

mini-geany is a test program calling ctags' functions used In [geany](https://github.com/geany/geany). See tlib target in makefiles/testing.mak.

**Comment by leleliu008** [comment]
@masatake Thank you for explaining.
