### ISSUE TITLE
C++: Tags are inconsistently generated for user-defined conversion functions

### ISSUE THREAD

**Issue by hammockt** [universal-ctags/ctags#3019]
Hello,

I am trying to run ctags on some source files that contain user-defined conversion functions.
Unfortunately ctags will inconsistently generate tags for these types of functions.
More documentation about user-defined conversion functions can be found here: https://en.cppreference.com/w/cpp/language/cast_operator
The example for this issue was taken from this link.

*****

The name of the parser: C++

The command line you used to run ctags:

```
$ ctags --options=NONE -f - --fields=-f test.cpp
```

The content of input file:

```C++
struct X {
    //implicit conversion
    operator int() const { return 7; }
 
    // explicit conversion
    explicit operator int*() const { return nullptr; }
 
//   Error: array operator not allowed in conversion-type-id
//   operator int(*)[3]() const { return nullptr; }
    using arr_t = int[3];
    operator arr_t*() const { return nullptr; } // OK if done through typedef
//  operator arr_t () const; // Error: conversion to array not allowed in any case
};
 
int main()
{
    X x;
 
    int n = static_cast<int>(x);   // OK: sets n to 7
    int m = x;                     // OK: sets m to 7
 
    int* p = static_cast<int*>(x);  // OK: sets p to null
//  int* q = x; // Error: no implicit conversion
 
    int (*pa)[3] = x;  // OK
}
```

The tags output you are not satisfied with:

```
X	test.cpp	/^struct X {$/;"	s
arr_t	test.cpp	/^    using arr_t = int[3];$/;"	t	struct:X	typeref:typename:int[3]
main	test.cpp	/^int main()$/;"	f	typeref:typename:int
operator arr_t*	test.cpp	/^    operator arr_t*() const { return nullptr; } \/\/ OK if done through typedef$/;"	f	struct:X
```

The tags output you expect:

```
X	test.cpp	/^struct X {$/;"	s
arr_t	test.cpp	/^    using arr_t = int[3];$/;"	t	struct:X	typeref:typename:int[3]
main	test.cpp	/^int main()$/;"	f	typeref:typename:int
operator arr_t*	test.cpp	/^    operator arr_t*() const { return nullptr; } \/\/ OK if done through typedef$/;"	f	struct:X
operator int	test.cpp	/^    operator int() const { return 7; }$/;"	f	struct:X
operator int*	test.cpp	/^    explicit operator int*() const { return nullptr; }$/;"	f	struct:X
```

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0(63f5d38), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 11 2021, 10:39:20
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc, +optscript
```

How do you get ctags binary:

Building it locally, via GNU/Linux distribution, as BSD's package

**Comment by masatake** [comment]
Sorry to be late. The original author of the C++ parser looks absent.
I will try to fix this issue.

```
struct X {
    operator int() const { return 7; }
};
```

The parser doesn't extract `operator int`.

```
struct X {
    operator inxt() const { return 7; }
};
```

With this input, the parser extracts `operator intx`.

The code doesn't expect the keyword coming after `operator`.

**Comment by hammockt** [comment]
Thanks for the quick response.
If you need any help testing your solution, I would be more than happy to help.

**Comment by masatake** [comment]
Could you try the branch?

```
cd /tmp
git clone https://github.com/universal-ctags/ctags
cd ctags
git checkout -b masatake-c++-built-in-type-as-name-of-operator master
git pull https://github.com/masatake/ctags.git c++-built-in-type-as-name-of-operator
sh ./autogen.sh
./configure
make
./ctags --version
...
...
```

**Comment by hammockt** [comment]
After doing some testing with my original example and some other examples from my code base, I may have discovered a possible issue with your solution.
Consider the following example below:

```
class Buffer
{
    public:
        operator const char*() const { return buffer; }
    private:
        char buffer[1024];
};
```

If I run this with the following ctags command:

```
ctags --options=NONE -f - --fields=-f test2.cpp
```

Then I get the following ctags output:

```
Buffer	test2.cpp	/^class Buffer$/;"	c
buffer	test2.cpp	/^        char buffer[1024];$/;"	m	class:Buffer	typeref:typename:char[1024]
operator constchar*	test2.cpp	/^        operator const char*() const { return buffer; }$/;"	f	class:Buffer
```

Where the possible issue is that the last tag name is "operator constchar*".
The tag name generated by the old Exuberant ctags is "operator const char*".
Should there be a space in this situation?
To me it seems like there should be.

Below is the ctags version that I used for this example:
```
Universal Ctags 5.9.0(40a6330), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 27 2021, 18:29:25
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc, +optscript
```

**Comment by masatake** [comment]
I updated my pull request. Now, `const` and `volatile` are handled well.

**Comment by hammockt** [comment]
Thanks for the fixes.

After testing the last example that I provided and some others, I can no longer reproduce the issue.
It looks like you latest changes are good to go.

**Comment by masatake** [comment]
@hammockt, thank you!
