### ISSUE TITLE
Why aren't C header files included?

### ISSUE THREAD

**Issue by ctrlcctrlv** [universal-ctags/ctags#3041]
Why does this not include files ending in `.h`:

```bash
ctags --languages=Python --languages=+C -R .
```

But this does:

```bash
ctags --languages=Python --languages=+C --languages=+C++ -R .
```

**Comment by masatake** [comment]
ctags has no ability to detect whether a ".h" file is a C source file or C++ source file. Therefore ctags assumes a ".h" file is a C++ source file. You can adjust the assumption with `--map-<LANG>` or `--langmap=` option.

```
$ cat /tmp/foo.h
inline int foo (void) { return 0; }

$ ./ctags --fields=+l --languages=C -o - /tmp/foo.h
<NOTHING>

$ ./ctags --fields=+l --languages=C --map-C++=-.h --map-C=+.h -o - /tmp/foo.h 
foo	/tmp/foo.h	/^inline int foo (void) { return 0; }$/;"	f	language:C	typeref:typename:int

$ ./ctags --fields=+l --languages=C --langmap=C:+.h -o - /tmp/foo.h 
foo	/tmp/foo.h	/^inline int foo (void) { return 0; }$/;"	f	language:C	typeref:typename:int

```

**Comment by ctrlcctrlv** [comment]
That's pretty strange, considering that C++ has the file extension `.hpp`?

**Comment by masatake** [comment]
In https://en.wikipedia.org/wiki/C%2B%2B. .C, .cc, .cpp, .cxx, .c++, .h, .H, .hh, .hpp, .hxx, .h++ are listed.
-- | --

**Comment by masatake** [comment]
I found a C++ .h file in your repository. https://github.com/ctrlcctrlv/kvkbd5/blob/master/src/kbddock.h
