### ISSUE TITLE
Can I strip the C parser out?

### ISSUE THREAD

**Issue by IngwiePhoenix** [universal-ctags/ctags#3043]
Hello!

After experimenting with this for a while, I think I have found what I was looking for... phew, finally.

However, I only need to parse C headers - and C headers only - to retrive the definitions from it.

Is it possible to strip the C parser out to repurpose it for this? Here is what I want to do, basically:

```c
// input in C:
typedef struct MyStruct {
  int aThing;
} MyStruct_t;
MyStruct_t add(MyStruct_t, MyStruct_t);
```
```v
// Output in V:
[typedef] // Needed, so V knows that it's `MyStruct_t` instead of `struct MyStruct_t`
struct C.MyStruct_t {
  aThing int
}
[unsafe] // This tells V that this call "might" be unsafe.
fn C.add(C.MyStruct_t, C.MyStruct_t) C.MyStruct_t
```

So, I just want to save myself from copytyping a gazillion headers just to achieve something small. Hence, I would love to take definitions from a C header and convert them.

Would it be possible to strip the C parser out, and re-use it for this?

Thank you in advance!

**Comment by masatake** [comment]
C: report parameters in a prototype with anonymous tags

input.h
```
MyStruct_t add(MyStruct_t, MyStruct_t);
```
expected.tags
```
anon1 ... typeref:typename:MyStruct_t ...
anon2 ... typeref:typename:MyStruct_t ...
```
This feature helps using tags for code generation as reported in #3043.

**Comment by masatake** [comment]
>  Can I strip the C parser out?

I don't understand the sentence. However, I guess what you want to use ctags as part of a c-heaer-to-vlang translator.

I hope ctags and readtags are suitable for this kind of hacking. I wrote a shell script. Surprisingly, I found a critical limitation in C parser. See #3045. Signature handling requires sed. I would like to remove this limitation in the future.  

c2v.sh:
```bash
#!/bin/bash

CTAGS=u-ctags
READTAGS=readtags
TAGS=$$.tags

# TAB CHARACTER MUST BE HERE.
# TAB CHARACTER MUST BE HERE.
TAB='	' # TAB CHARACTER MUST BE HERE.
# TAB CHARACTER MUST BE HERE.
# TAB CHARACTER MUST BE HERE.

emit_member()
{
	printf "  %s %s\n" "$1" "$2"
}

handle_member()
{
	local name=$1
	local rest=$2
	local tmp
	local typename

	case "$rest" in
		(*typeref:typename:*)
			tmp=${rest#*typeref:typename:}
			typename=${tmp%%${TAB}*}
			emit_member "$name" "$typename"
		;;
	esac
}

emit_members()
{
	local name
	local rest
	local struct=$1
	${READTAGS} -net $TAGS \
				-Q '(and (eq? $kind "member") $scope-kind (eq? $scope-kind "struct") $scope-name (eq? $scope-name "'"$struct"'"))' \
				-l | while read name line; do
		handle_member "$name" "$line"
	done
}

handle_typedef()
{
	local name=$1
	local rest=$2
	local tmp
	local struct

	case "$rest" in
		(*typeref:struct:*)
			echo "[typedef]"
			echo "struct C.${name} {"
			tmp=${rest#*typeref:struct:}
			struct=${tmp%%${TAB}*}
			emit_members $struct
			echo "}"
		;;
	esac
}

# See https://github.com/universal-ctags/ctags/issues/3045
hack_signature()
{
	local signature=$1
	sed -e 's/^(/(,/' -e 's/,/,C./g' -e 's/^(,/(/' <<< "$signature"
}

emit_signature()
{
	local rest=$1
	local signature
	case "$rest" in
		(*signature:*)
			signature=${rest#*signature:}
			signature=${signature%%${TAB}*}
			printf "%s" $(hack_signature "$signature")
			;;
	esac
}

emit_typeref()
{
	local rest=$1
	local typeref
	case "$rest" in
		(*typeref:typename:*)
			typeref=${rest#*typeref:typename:}
			typeref=${typeref%%${TAB}*}
			printf "%s"  C.$typeref
		;;
	esac
}

handle_prototype()
{
	local name=$1
	local rest=$2
	local tmp

	echo "[unsafe]"
	printf "fn C.%s" $name
	emit_signature "$rest"
	printf ' '
	emit_typeref "$rest"
	echo
}

${CTAGS} --sort=no --kinds-C++='*' --fields-C++='*' --fields='*' -o ${TAGS} "$@"
${READTAGS} -net ${TAGS} -l | while read NAME REST; do
	case "$REST" in
		(*kind:typedef*)
			handle_typedef "$NAME" "$REST"
			;;
		(*kind:prototype*)
			handle_prototype "$NAME" "$REST"
	esac
done

rm ${TAGS}
```

An example session:
```
[yamato@control]~/var/ctags-github% cat input.h 
cat input.h 
// input in C:
typedef struct MyStruct {
  int aThing;
} MyStruct_t;
MyStruct_t add(MyStruct_t, MyStruct_t);
[yamato@control]~/var/ctags-github% bash ./c2v.sh input.h
bash ./c2v.sh input.h
[typedef]
struct C.MyStruct_t {
  aThing int
}
[unsafe]
fn C.add(C.MyStruct_t,C.MyStruct_t) C.MyStruct_t
```

If readtags supports "--format" option, we can simplify the script.

**Comment by IngwiePhoenix** [comment]
Okay...THAT was fast. :O 

Basically I want to do exactly this - but in C, so I can compile it into it's own utility or use it as a tiny library. My idea was, that if I was able to single out the C parser, I could use that to generate the V wrapper. Since I don't need any of the other languages like Kotlin, and only C, that would've been really useful. But from reading the automake file, I couldn't spot any means of removing the other parsers and just leaving the C one in.

I am not a native speaker; so maybe my phrasing went some ways there. Trying my best! :)

**Comment by IngwiePhoenix** [comment]
I just ran this script over a couple of obscure headers (homebrew SDKs for consoles) to see the output - and it worked. Wow, I am a little mindblown right now. ^^; So if anything, this script should tide me over for the time being and serve as a base that I could use to get something started. Thanks for that!

**Comment by masatake** [comment]
> I am not a native speaker; so maybe my phrasing went some ways there. Trying my best! :)

Now I understand what you mean. You wanted to reuse the C parser of ctags.
We don't provide the simple way.

When you run "make check", mini-genay command is built. Its source code is at main/mini-geany.c. It tells how to use libctags.
Edit sources.mk and main/parsers_p.h to reduce the parsers that libctags includes.

readtags used in my script is a command using libreadtags. You may want to use libreadtags directly in your C program. See https://github.com/universal-ctags/libreadtags. 

I recommend you to read tags(5), ctags-client-tools(7), and readtags(1) man pages shipped as part of u-ctags if you extend the script.

This issue puts a spotlight on an interesting aspect of u-ctags. Many people assume ctags is for completion in code editing or jumping to the definition.  I will write a blog article about this issue.

During writing the script I found following features are missed:

* tagging parameters in a prototype
* format output option in readtags

If the missing features are implemented, we can make the script simple and eliminate the sed command invocation.

**Comment by IngwiePhoenix** [comment]
Thank you very much for all your assistance!

I would love to read mentioned blog post when you release it. Would you mind telling me where I might find it later?

**Comment by IngwiePhoenix** [comment]
> When you run "make check", mini-genay command is built. Its source code is at main/mini-geany.c. It tells how to use libctags.
> Edit sources.mk and main/parsers_p.h to reduce the parsers that libctags includes.

This should prove useful! I took a look at the mentioned sources. Stripping down the internal parsers should be enough. Now, all that is left, is to learn how to interface with `libctags` and learn how the build is orchestrated.

Ironically, that `parsers_p.h` also showed me that technically, Not even packcc is needed. Good to know, because the language it allows to tag are not very important for me.

Again, thank you very much for your assistance!
