### ISSUE TITLE
[Bug|Question] Conflict caused by FALSE, TRUE macros and bool_tag enum using same name

### ISSUE THREAD

**Issue by XSven** [universal-ctags/ctags#3044]
I need to build Universal Ctags on an AIX 7.2 system using gcc version 8.3.0. During the **make** step I am getting the error

```
In file included from /opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8.3.0/include-fixed/stdio.h:503,
               from ./misc/packcc/src/packcc.c:40:
./misc/packcc/src/packcc.c:94:5: error: expected identifier before numeric constant
   FALSE = 0,
   ^~~~~
```
I have looked into the pre-processed file packcc.i. The indentifier FALSE was replaced with 0. Conclusion: Some header file defines the macros FALSE and TRUE that create a conflict with the enum definition

94 typedef enum bool_tag {
95     FALSE = 0,
96     TRUE
97 } bool_t;

inside packcc.c. I was able to overcome the issue #undef ing the macros just before the enum definition. This obviously isn't a desirable thing to do.

What is the correct course of action for me to take?

**Comment by masatake** [comment]
u-ctags uses https://github.com/arithy/packcc/.
So could you try building packcc cloned from https://github.com/arithy/packcc/ directly?
If you can build the packcc on your platform, this is an issue of u-ctags build-system. So I will try to fix.
If you cannot build the packcc on your platform, I expect packcc developers will take an action.
However, there can be a case that the packcc developers reject taking the action for the platform, reopen this issue again.
I will add a new option `--disable-packcc` option to ./configure of u-ctags. In that case, you cannot use parsers for kotlin and varlink.

When opening an issue at  https://github.com/arithy/packcc/, refer this issue (https://github.com/universal-ctags/ctags/issues/3044). So I can track the discussion at packcc side.

**Comment by masatake** [comment]
As we expect, the fundamental part of this issue is fixed in the packcc repo.
The nest step is "updating the packcc source code in u-ctags".

**Comment by masatake** [comment]
Could you try #3061?

**Comment by XSven** [comment]
It works. Please update universal-ctags:master.

**Comment by masatake** [comment]
Thank you for the confirmation.
