### ISSUE TITLE
ifdef related to fnmatch and regex

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#308]
Our source tree contains fnmatch and regex related source code.
So it is always avaiable. We don't need #ifdefs for them. The #ifdefs just make source code dirty.
Let's remove them.

**Comment by masatake** [comment]
On AppVeyor I found ctags built on cygwin doesn't have regex feature.
It looks strange.

**Comment by k-takata** [comment]
> On AppVeyor I found ctags built on cygwin doesn't have regex feature.

Strange. It is built with [+regex](https://ci.appveyor.com/project/masatake/ctags/branch/master/job/djnkqgyksn94of11#L537), but some tests (option-directory, regex and coproc) are skipped.
It doesn't happen when I run the tests on my local PC. All of them are tested and passed.

**Comment by masatake** [comment]
Maybe it is something to do with newlines in features file.

**Comment by masatake** [comment]
dos2unix is availabke in cygwin on appveyor?

**Comment by k-takata** [comment]
> dos2unix is availabke in cygwin on appveyor?

It wasn't installed. After I installed it, the tests are no more skipped.
I will create a new PR.

**Comment by cweagans** [comment]
Sorry for the noise. Just switching the "Release blocker" tag for the "Initial release" milestone so that everything is tracked in one place.

**Comment by masatake** [comment]
Solved in 6cb18ddb038ae3dde59afa3702447a5bf821ac90.
However, the two bundled libraries should be updated to the latest one.
