### ISSUE TITLE
[infrastructure] Disabling landscape

### ISSUE THREAD

**Issue by b4n** [universal-ctags/ctags#310]
For a few days now @landscape-bot is crapping our PRs about irrelevant code health.  Apparently [landscape is Python only](https://docs.landscape.io/faq.html), and as we don't have any real python sources it's just adding noise to our PRs.
I don't know why landscape has been added, nor who did this, but it's just plain annoying and useless to us.

doing so would close #301 that I opened before realizing landscape was actually useless to us.

**Comment by b4n** [comment]
@carlio thanks.

Any idea why it got added in the first place?

**Comment by carlio** [comment]
@b4n someone with access to the repo added it to Landscape - repositories are checked when someone explicitly adds them. Unfortunately because I turned off the checks I can't tell you who it was as that information is gone!

**Comment by masatake** [comment]
Now disabled. So I close this.
