### ISSUE TITLE
Cannot install without root privileges

### ISSUE THREAD

**Issue by jeremycostanzo** [universal-ctags/ctags#3104]
Hello, I am trying to install universal ctags without root privileges on arch linux.
I cloned the repo and then I executed:
```
./autogen.sh
./configure --prefix=$HOME
make
```
running `make` resulted in the following error:
`/usr/bin/python: can't open file '/usr/bin/rst2man.py': [Errno 13] Permission denied`

Is there an easy way for me to get it working?
I have succesfully installed exuberant ctags but I'd like to use universal ctags.

Thank you

**Comment by leleliu008** [comment]
step1. change the mode of `/usr/bin/rst2man.py`
```
sudo chmod a+x /usr/bin/rst2man.py
```
step2. rerun make comand
```
make
```

**Comment by jeremycostanzo** [comment]
As I said, I don't have admin privileges, so I cannot use `sudo` unfortunately.

I have commented out the lines
1503, 1504, 2038, 2039, 2040, 7097, 7099 and 7101

I could get the package to build I believe, but I don't think that I will have access to the man pages 
(not an issue for me, I wouldn't use it a lot).
Although I think that there should be an easier way to insatall the package without admin rights :)
Thanks for your quick answer though!

**Comment by leleliu008** [comment]
If you can run pip command without root privileges, you can reinstall rst2man.py to user dir.
```
pip install rst2man --user
```
this will install rst2man.py to `$HOME/.local/bin`, so you should add `$HOME/.local/bin` to `PATH` environment.
```
export PATH=$HOME/.local/bin:$PATH
```

**Comment by leleliu008** [comment]
maybe our configure command provide`--disable-manpages` switch is better.

**Comment by jeremycostanzo** [comment]
I couldn't install it :(
```
~/universal-ctags$ pip install --user rst2man
ERROR: Could not find a version that satisfies the requirement rst2man
ERROR: No matching distribution found for rst2man
```
I tried to disable man pages:
`~/universal-ctags$ ./configure --prefix=$HOME --disable-manpages`
But the configure doesn't seem to provide this option:
`configure: WARNING: unrecognized options: --disable-manpages`

**Comment by leleliu008** [comment]
sorry, `rst2man.py` is in `docutils` package

```
pip install --user docutils
```

**Comment by leleliu008** [comment]
you can also try following steps:

step1: change the `configure.ac` following line:
```
AC_PATH_PROGS(RST2MAN, [rst2man rst2man.py rst2man-3 rst2man-3.6 rst2man-3.7 rst2man-3.8 rst2man-3.9], [no])
```
to
```
AC_PATH_PROGS(RST2MAN, [xxxxxxxxxx], [no])
```
step2: reconfig
```
./autogen.sh
./configure --prefix=$HOME
make
```

**Comment by masatake** [comment]
I would like to see `ls -l /usr/bin/rst2man.py`.

**Comment by masatake** [comment]
If the execution bit is not set, it is an issue with your environment.  Instead of opening this issue, I recommend you to report it to your sysadmin.
If you run `make -k`, you can get the executables, ctags, and readtags anyway. You can use them. 
We can introduce --disable-manpages option. However, the situation doesn't change; you, a user, cannot read our great(!) man pages.

**Comment by masatake** [comment]
BTW, I have never used `make install` of ctags.
```
% ls -l ~/bin/u-ctags
lrwxrwxrwx. 1 jet jet 32 Feb 16 03:28 /home/jet/bin/u-ctags -> /home/jet/var/ctags-github/ctags
```
/home/jet/var/ctags-github is a directory cloned from our git repo.

**Comment by leleliu008** [comment]
In general, `C_PATH_PROGS(RST2MAN, [rst2man rst2man.py rst2man-3 rst2man-3.6 rst2man-3.7 rst2man-3.8 rst2man-3.9], [no])` configed command names must be executable, even if one exists in `PATH` but is not executable, it is not assigned to `RST2MAN`

In this case, I think the machine is controlled by admin, and `SELinux` is opend, the non-root usr have no right to access `/usr/bin/rst2man.py`.

**Comment by masatake** [comment]
How about copying /usr/bin/rst2man.py to your ~/bin, and adding ~/bit to PATH after doing chmod u+x ~/bin/rst2man.py?
If SELinux doesn't allow to do so, it is the design of the host system. We should not fight with the design.

**Comment by masatake** [comment]
> In general, C_PATH_PROGS(RST2MAN, [rst2man rst2man.py rst2man-3 rst2man-3.6 rst2man-3.7 rst2man-3.8 rst2man-3.9], [no]) configed command names must be executable, even if one exists in PATH but is not executable, it is not assigned to RST2MAN

I see. Thank you. chmod u+x doesn't make sense.

**Comment by masatake** [comment]
We have got no response from the original reporter for two weeks.
