### ISSUE TITLE
CI: add `out-of-source-build.yml` building test case

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#3122]
@masatake how about add a `out-of-source-build.yml` GitHub Actions workflow?

_Originally posted by @leleliu008 in https://github.com/universal-ctags/ctags/issues/3119#issuecomment-899302590_

e.g.

```
$ cd /tmp
$ mkdir build
$ cd build
$ ~/devel/ctags/configure
$ make
```

**Comment by leleliu008** [comment]
I find `testing-mac.yml` has do the `out-of-source build` [testing-mac.yml#L40-L44](https://github.com/universal-ctags/ctags/blob/master/.github/workflows/testing-mac.yml#L40-L44)

**Comment by masatake** [comment]
Oh, thank you.
