### ISSUE TITLE
Question: how to update files under docs/man?

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#3131]
@hirooih, when I update foo.rst.in file under man directory, what I should do for updating docs/man/foo.rst ?

As far as reading docs/README.md, just `make` is enough.
However, it doesn't work in my environment.

For getting what I want, I have to do `make -C man update-docs`.

**Comment by hirooih** [comment]
I've sent PR #3133 .

***

> For getting what I want, I have to do make -C man update-docs.

Files `docs/man/*`  are used only by Sphinx documents.  `make -C docs html`, etc. generates them.
And `make check-genfile` invoked by `make check`, etc. checks if any of  `docs/man/*` must be committed.

I also thought about modifying the `docs/README.md`, but I chose to fix `Makefile.am`.  I think it is better to show developer that any of  `docs/man/*` is updated.

**Comment by masatake** [comment]
> I've sent PR #3133 .

I see. Thank you.
