### ISSUE TITLE
CI test on Cygwin fails

### ISSUE THREAD

**Issue by hirooih** [universal-ctags/ctags#3137]
During working on #3128 CI test on Cygwin started failing causing segmentation faults.
It also fails on #3134 which changed only `.editorconfig`.

I've updated my local Cygwin environment and reproduce the fail.

**Comment by masatake** [comment]
Is Valgrind available on cygwin?

**Comment by masatake** [comment]
What I really don't want to know is why regcomp needs pthread:-O.

**Comment by hirooih** [comment]
I guess you meant;

> What I really want to know is why regcomp needs pthread:-O.

Me, too!

**Comment by masatake** [comment]
I don't want to know it. It is o.k. for me as far as regcomp works fine.
If regcomp doesn't work, we have to know it. So I don't want to know if possible.
However, the most of all computer programs are broken. So eventually we have to know it whether we want to know it or not.

**Comment by hirooih** [comment]
I see.
Your comment reminds me the similar fail https://github.com/universal-ctags/ctags/pull/3069#issuecomment-861916353.
Similar fix works.

I guess a change related to weak-reference was made in Cygwin upstream.

I've sent PR #3138.

Thanks.

**Comment by hirooih** [comment]
fixed by #3138.
