### ISSUE TITLE
Lua tags always include qualifier

### ISSUE THREAD

**Issue by gpanders** [universal-ctags/ctags#3144]
The name of the parser:

Lua

The command line you used to run ctags:

```
$ ctags --options=NONE --languages=lua -o - test.lua
```

The content of input file:

```lua
local M = {}

function M.say_hello()
  print("Hello world")
end

return M

```

The tags output you are not satisfied with:

```
M.say_hello	test.lua	/^function M.say_hello()$/;"	f
```

The tags output you expect:

```
say_hello	test.lua	/^function M.say_hello()$/;"	f
```

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +json, +interactive, +case-insensitive-filenames, +packcc
```

How do you get ctags binary:

From nixpkgs.

---

The problem with the above is that when I require my test module in another Lua file:

```lua
local test = require('test')

test.say_hello()
```

The `say_hello` function in `test.lua` is not found. Adding functions to a table in Lua and then returning the table at the end of the module is a common pattern in Lua, so the table name itself should not be included (unless `--extras=+q` is used).

Note this is a different issue than https://github.com/universal-ctags/ctags/issues/1798, which is kind of asking for the opposite (ironically).

**Comment by masatake** [comment]
In addition,

```
local M = {}
```

`M` must be tagged.  Is `variable`  proper kind name for `M`?
