### ISSUE TITLE
Import nestlevel.[hc] from geany

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#315]
It is nice. I want it.

Not only just importing, I want to add a variant API specialized to cork.

> extern void nestingLevelsPush(NestingLevels *nls,
	const vString *name, int type);

This is the original version.

> extern void nestingLevelsPushIndex(NestingLevels *nls, int index);

Here INDEX is a value returned from makeTagEntry.

**Comment by ffes** [comment]
I am working in including the reStructuredText parser from Geany. That parser relies on nestlevel, so when it is merged, this issue can be closed as well.

That parser itself needs a bit of work (the search patterns are not very useful ATM), but the PR is coming.

**Comment by b4n** [comment]
Note: this was initially extracted from the Python parser, and then extended to be more generally useful, see:
* geany/geany@95f99f4034bee7fc0b43fa8b23389d1fd1b1e122
* geany/geany@58b5c053bc8314bd58748c83469bd7e4354e9c1e
* geany/geany@14653b1ba28d28a7423e84b2b6e587ea5338ba5b
* geany/geany@7b53cf05aa6dbb5e997066864651b8a2d7ff71af

So when importing this the Python parser should make use of the common code.

**Comment by masatake** [comment]
@ffes, thank you.

Fixing this issue has some impacts.

Making the code gap between geany and ctags is better, of course.
nestlevel can be base of namespace in regex parser: https://sourceforge.net/p/ctags/bugs/362/

I would like to fix a bug reported in https://sourceforge.net/p/ctags/bugs/356/ after importing nestleve.[hc].

**Comment by b4n** [comment]
> I would like to fix a bug reported in https://sourceforge.net/p/ctags/bugs/356/ after importing nestleve.[hc].

I don't think there is much need to wait for the import, it's somewhat unrelated (as python.c already uses it).  Done in #362

**Comment by masatake** [comment]
I found without nestlevel I can implement namespace in regex parser with cork API.
However, separating nestlevel code from python.c and move it to main/ is good idea.
