### ISSUE TITLE
Perl: Labels detected in text

### ISSUE THREAD

**Issue by elextr** [universal-ctags/ctags#3200]
I was checking the import of recent ctags parsers into Geany and I noticed that when I used [this file](https://github.com/geany/geany/blob/master/scripts/fix-alignment.pl) for an example it parsed labels on lines 22, 25, and 29.

I don't known Perl much, but I would not have thought labels could exist inside what looks like text, maybe the ctags Perl expert could comment.

**Comment by masatake** [comment]
Thank you. Reproduced.

```
$ cat ./input.pl
(($argc == 1) or ($argc >= 1 and $opt_write)) or die <<END;
Usage:
$scriptname sourcefile [>outfile]
  Print formatted output to STDOUT or outfile.
  Warning: do not use the same file for outfile.
$scriptname -w sourcefile(s)
  Writes to the file(s) in-place.
  Warning: backup your file(s) first or use clean version control files.
END

sub foo {
    print "hello\n";
}
$ u-ctags -o - input.pl
Usage	input.pl	/^Usage:$/;"	l
Warning	input.pl	/^  Warning: backup your file(s) first or use clean version control files.$/;"	l
Warning	input.pl	/^  Warning: do not use the same file for outfile.$/;"	l
foo	input.pl	/^sub foo {$/;"	s
```

**Comment by masatake** [comment]
heredoc in perl is explained in https://perldoc.perl.org/perlop#%3C%3CEOF .
