### ISSUE TITLE
Warning for c++ 'using' kind

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#3203]
We are now migrating to the new cxx parser in Geany (yeah, finally) and we get warnings for 'U' ('using' kinds) like this:
```
ctags: Warning: definition tag for refonly kind(using) is made: Scintilla
```
I can reproduce this warning with command-line ctags as well with
```
ctags --kinds-all=* some_file_containing_using.cxx
```
I may be wrong but isn't the problem that `ATTACH_ROLES()` is missing here?

https://github.com/universal-ctags/ctags/blob/bddc1ded89c035cdf9a9cc89d6e259947aa7a8c9/parsers/cxx/cxx_tag.c#L79

**Comment by masatake** [comment]
It may be something to do with #1783.
Anyway, the warning is just noise. I will fix it as you wrote.

**Comment by techee** [comment]
Thanks!
