### ISSUE TITLE
Incorrect cython signature when 'z' kind enabled

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#3216]
For the following cython code
```
cdef int int_identity(int i) : return i  
```
processing with `ctags --fields=S --python-kinds=+z` produces
```
int_identity	test.py	/^cdef int int_identity(int i) : return i  $/;"	signature:(inti)
```
(notice the missing space between `int` and `i` in signature) while `ctags --fields=S` produces the correct result with the space:
```
int_identity	test.py	/^cdef int int_identity(int i) : return i  $/;"	signature:(int i)
```

**Comment by masatake** [comment]
Currently, the python parser processes cython input.
It depends on the cdef keyword.

It has limitations. 
```
./src/sage/combinat/partitions.pyx:89:def ZS1_iterator_nk(int n, int k):                                                                                                                      
```
Though `def` is used, the style of the parameter list is that of C language; a type comes first, then a parameter name comes second.
The python parser may capture the type name as a parameter name.

**Comment by masatake** [comment]
@techee, I introduced the change mitigating the issue.
