### ISSUE TITLE
Some questions about ctags output

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#3220]
I would like to drop our code in Geany for parsing ctags files and use the libreadtags library instead in https://github.com/geany/geany/pull/3049. It would be nice to support as many different formats of ctags outputs as possible. I'm not sure how to detect the 's' field (scope without the 'scope' keyword) output in ctags files. I used the keys which were present in the previous parsing code:
```
			if (strcmp(key, "class") == 0 ||
 				strcmp(key, "enum") == 0 ||
 				strcmp(key, "function") == 0 ||
 				strcmp(key, "struct") == 0 ||
 				strcmp(key, "union") == 0)
```
Are those the only keys that can appear before the scope or is this something language-dependent?

My second question is related to tags of anonymous types such as structs, enums etc. The generated name is of the form `__anon<some hash>` which isn't nice for presentation in Geany and we need to rename it to something nicer. Updating anonymous tag's name however means also updating the scope information of all tags that are within the tag's scope. My question is: is it guaranteed that the anonymous tag is generated before the tags that contain this tag's name inside their scope? It seems to be the case for the cxx parser but I'm not sure if we can rely on this or not.

**Comment by masatake** [comment]
> Are those the only keys that can appear before the scope or is this something language-dependent?

In the current implementation of u-ctags, these names never appear before the scope.

In the current implementation of u-ctags, u-ctags prints the parser-specific fields after printing the common fields like `access:`.
However, `tags(5)` man page says nothing about order of fields. So, u-ctags can change the order though I have no such plan.
As a u-ctags maintainer, I recommend you to use `--fields=+Z` option always to print `scope:` prefix. So you don't have to think about order. I also recommend `--fields=+z` and `--fields=+K`.

```
[jet@living]~/var/ctags-github% cat /tmp/foo.c                                     
#define F(X) (X+1)
[jet@living]~/var/ctags-github% u-ctags --kinds-C='*' -o - /tmp/foo.c 
F	/tmp/foo.c	/^#define F(/;"	d	file:
X	/tmp/foo.c	/^#define F(X) (X+1)$/;"	D	macro:F
[jet@living]~/var/ctags-github% u-ctags --fields=+K --kinds-C='*' -o - /tmp/foo.c
F	/tmp/foo.c	/^#define F(/;"	macro	file:
X	/tmp/foo.c	/^#define F(X) (X+1)$/;"	macroparam	macro:F
[jet@living]~/var/ctags-github% u-ctags --fields=+Kz --kinds-C='*' -o - /tmp/foo.c
F	/tmp/foo.c	/^#define F(/;"	kind:macro	file:
X	/tmp/foo.c	/^#define F(X) (X+1)$/;"	kind:macroparam	macro:F
[jet@living]~/var/ctags-github% u-ctags --fields=+KzZ --kinds-C='*' -o - /tmp/foo.c
F	/tmp/foo.c	/^#define F(/;"	kind:macro	file:
X	/tmp/foo.c	/^#define F(X) (X+1)$/;"	kind:macroparam	scope:macro:F
```

The way I recommended may not work well when reading a tags file generated by another tags generator.
In that case, inspect `!_TAG_PROGRAM_NAME` pseudo tag.
```
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
```

> My second question is related to tags of anonymous types such as structs, enums etc. The generated name is of the form __anon<some hash> which isn't nice for presentation in Geany and we need to rename it to something nicer. Updating anonymous tag's name however means also updating the scope information of all tags that are within the tag's scope. My question is: is it guaranteed that the anonymous tag is generated before the tags that contain this tag's name inside their scope? It seems to be the case for the cxx parser but I'm not sure if we can rely on this or not.


It is not guaranteed. u-ctags provides the way to rewrite a tag entry after emitting to parsers.
See https://docs.ctags.io/en/latest/internal.html?highlight=cork#output-tag-stream-1 .

Let's think about an imaginary language (foo) that u-ctags will support in the future:
```
{
   var x
   var y
} record point_start, point_destination
```

This code has similar semantics to the following C program:
```
struct {
  int x;
  int y;
} point_start, point_destination;
```

To represent that `point_start` and `point_destinatin` have the same structure,
the foo parser may make an anonymous tag for the record.
The tags file may be:
```
x    kind:variable    scope:record:__anon_0
y    kind:variable    scope:record:__anon_0
__anon_0 kind:record  extras:anonymous
point_start     kind:variable typeref:record:__anon_0
point_start     kind:variable typeref:record:__anon_1
```

If the name of record is explicitly given:
```
{
   var x
   var y
} Point record point_start, point_destination
```
the tags output will be:
```
x    kind:variable    scope:record:Point
y    kind:variable    scope:record:Point
Point kind:record
point_start     kind:variable typeref:record:Point
point_start     kind:variable typeref:record:Point
```

To help a client tool make such a tag network, @pragmaware suggested introducing `id:` fields in an issue or pull request.
I'm positive about it. I haven't started it yet.

**Comment by techee** [comment]
> In the current implementation of u-ctags, these names never appear before the scope.

I think we don't understand each other here. When you run `ctags --fields=s some_file.cxx`, you get e.g. 
```
Allocate	PlatGTK.cxx	/^std::shared_ptr<Font> Font::Allocate(const FontParameters &fp) {$/;"	class:Font
```
The scope here is prefixed with the `class` key but I think it can be also `enum:`, `function:`, `:union` or `struct:` depending on the type of the tag. My question was if these are all the prefixes that could appear in front of scope for the `s` flag alone or if there are more of them or if this is something language-specific. When `Z` is given, it's clear that that the scope field is the one prefixed with `scope:` but with just `s` it's not so clear how to detect what is the scope in the tags file.

> Let's think about an imaginary language (foo) that u-ctags will support in the future...

This is exactly what I feared but I think we'll risk it for now in Geany as C-like languages seem to work - in the worst case anon tags won't be renamed to anything nice but nothing would break.

**Comment by masatake** [comment]
Thank you for the supplementary explanation. I home I understand your question now.

It is language-specific.

The prefix part appeared in a language `X` tags can be listed with `ctags --list-kinds-full=X`. See the 2nd column.
```
% u-ctags --list-kinds-full=C
#LETTER NAME       ENABLED REFONLY NROLES MASTER DESCRIPTION
D       macroparam no      no      0      C      parameters inside macro definitions
L       label      no      no      0      C      goto labels
d       macro      yes     no      2      C      macro definitions
e       enumerator yes     no      0      C      enumerators (values inside an enumeration)
f       function   yes     no      0      C      function definitions
g       enum       yes     no      0      C      enumeration names
h       header     yes     yes     2      C      included header files
l       local      no      no      0      C      local variables
m       member     yes     no      0      C      struct, and union members
p       prototype  no      no      0      C      function prototypes
s       struct     yes     no      0      C      structure names
t       typedef    yes     no      0      C      typedefs
u       union      yes     no      0      C      union names
v       variable   yes     no      0      C      variable definitions
x       externvar  no      no      0      C      external and forward variable declarations
z       parameter  no      no      0      C      function parameters inside function or prototype definitions
```

Of course, they are the superset. A parameter cannot make a scope, of course.



>    Let's think about an imaginary language (foo) that u-ctags will support in the future...

>> This is exactly what I feared but I think we'll risk it for now in Geany as C-like languages seem to work - in the worst case anon tags won't be renamed to anything nice but nothing would break.

It makes sense.

**Comment by techee** [comment]
> The prefix part appeared in a language X tags can be listed with ctags --list-kinds-full=X. See the 2nd column.

OK, I see, it can be all of the kind names. There just might be a danger some parser defines a kind name that is identical to some of the keys used in the tag files. Imagine you have a parser where one of the kinds is named 'kind', then you could get
```
Allocate	PlatGTK.cxx	/^std::Allocate() {$/;"	kind:kind     kind:Font
```
where the first kind is ctags kind ('z' field) and the second is the prefix of the scope ('s' field). But I guess these problems could be avoided by some unit tests.

**Comment by masatake** [comment]
```
Allocate	PlatGTK.cxx	/^std::Allocate() {$/;"	kind:kind     kind:Font
```

So I recommend you to use `--fields=+Z`. With the option, the output becomes:
```
Allocate	PlatGTK.cxx	/^std::Allocate() {$/;"	kind:kind     scope:kind:Font
```

**Comment by techee** [comment]
@masatake Thanks for your answers!
