### ISSUE TITLE
vim warns "ctags: Language "tex" already defined^@"

### ISSUE THREAD

**Issue by sudoyang** [universal-ctags/ctags#3232]
Hi everyone,

Each time I use vim to open a tex file and I get a warning from vim "ctags: Language "tex" already defined^@". I do not know how to debug this issue. Any suggestions? Appreciated!

Below lists some information about the ctags installed in my Ubuntu 20.04

$ ctags --version
Universal Ctags 5.9.0(c8a429ef), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 10 2021, 15:04:20
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +yaml, +packcc, +optscript

How do you get ctags binary:
I install it from ubuntu 20.04's apt get

**Comment by masatake** [comment]
ctags has a parser for tex already.
I guess one of your configuration files for ctags may define another text parser with `--langdef=tex`, `--langdef=TEX`, or `--langdef=TeX`.

Even if you don't have your own ctags configuration file, a vim plugin you are using can pass the option `--langdef=...` to ctags. It causes the warning message.

**Comment by sudoyang** [comment]
> `langdef=tex`

Thanks!
I found it is due to latex-suite plugin. In the file lmain.vim of latex-suit, there is a line,
		"let Tlist_Ctags_Cmd = s:tex_ctags ." --langdef=tex --langmap=tex:.tex.ltx.latex"
which causes the issue.

Comment the line helps.

Thanks again.

**Comment by masatake** [comment]
Though `--langdef=tex' should not be passed, `--langmap=tex:.tex.ltx.latex` may be useful if you use such file extension for TeX files.

**Comment by sudoyang** [comment]
Now I just remove "--langdef=tex" but keep everything else, which is like "let Tlist_Ctags_Cmd = s:tex_ctags ." --langmap=tex:.tex.ltx.latex". Still works.
