### ISSUE TITLE
cxx: incorrect output of ctags macro assert

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#3279]
For the following code
```
G_STATIC_ASSERT(G_N_ELEMENTS(parser_map) == TM_PARSER_COUNT);
```
`ctags --kinds-C=* test.c` generates
```
G_N_ELEMENTS	test.c	/^G_STATIC_ASSERT(G_N_ELEMENTS(parser_map) == TM_PARSER_COUNT);$/;"	p	typeref:typename:G_STATIC_ASSERT (==TM_PARSER_COUNT)	file:
__anon1dda1bf6010d	test.c	/^G_STATIC_ASSERT(G_N_ELEMENTS(parser_map) == TM_PARSER_COUNT);$/;"	z	prototype:G_N_ELEMENTS	typeref:typename:parser_map	file:
```
(notice the anon tag and the strange `typeref:typename` of the G_N_ELEMENTS tag). When changed to
```
G_STATIC_ASSERT(a==b);
```
the output doesn't contain any tag which I think is the correct output in this case.

**Comment by masatake** [comment]
ctags cannot handle these macros without macro definition. 
ctags just follows the basic rule: garbage in garbage out.
