### ISSUE TITLE
cxx: initializing class instance using {} doesn't produce instance tag

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#3280]
For the following code
```c++
class c {
    int i;
public:
    c( int j ):i(j){}
    int f(){ return i; }
} instance{1};
```
ctags doesn't generate a tag for `instance`. When `instance{1}` is replaced by `instance(1)`, the tag is correctly generated.

**Comment by masatake** [comment]
#3423 may fix this.
However, I found another limit of the parser:
```
class G g{1}, j{2};
class G h{1};
```
g, h, and j are not tagged.
However, i in
```
class C i(2);
```
is tagged well. I will open a new issue based on this comment after merging #3423.
