### ISSUE TITLE
macros.h is not handled as a C++ header file after #3090

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#3286]
When I use a file named `macros.h` as input, it was handled as a C++ header file before #3090.
However, it is handled as RpmMacros after #3090.

Currently the RpmMacros parser uses a pattern `macros.*`, but I think that the condition is too loose.

*****

### The name of the parser:

RpmMacros, C++

### The command line you used to run ctags:

```
$ ctags -o - macros.h
```

### The content of input file:

Any C/C++ header file named `macros.h`.

### The tags output you are not satisfied with:

No useful output as a C++ header file.

### The tags output you expect:

Correctly parsed as a C++ header file.

### The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0(d6255a7a), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan 27 2022, 16:02:37
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +case-insensitive-filenames, +packcc, +optscript
```

### How do you get ctags binary:

Compiled by myself on Cygwin.

**Comment by masatake** [comment]
I'm sorry for the poor mistake.
