### ISSUE TITLE
Ctags json output is wrongly formatted

### ISSUE THREAD

**Issue by NimaAgm** [universal-ctags/ctags#3305]
The name of the parser:C-parser

The command line you used to run ctags:
ctags.exe -R --languages=C  --sort=yes -x --kinds-C=* --file-scope=yes --output-format=json -f tag2.txt

The version of ctags:

 ctags --version
Universal Ctags 5.9.0(p5.9.20220306.0), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar  6 2022, 01:06:23
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +gnulib_regex, +internal-sort, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript, +pcre2

the problem is the format of output json file is wrong and I cant not work with in python it says the formats is wrong and and I checked format in json format checker it was wrong 

sample of json output
[jsontags.txt](https://github.com/universal-ctags/ctags/files/8239063/jsontags.txt)

python error
 raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 93)

**Comment by masatake** [comment]
Sorry for making you confused.
We should use the name of the output format [jsonl](https://www.google.com/search?client=firefox-b-d&q=josnnl) instead of json; though we use the name 'json', the actual data emitted by ctags is jsonl.

**Comment by NimaAgm** [comment]
Thanks I understood. I parsed the information line by line

**Comment by masatake** [comment]
About the "json" output, see https://docs.ctags.io/en/latest/man/ctags-client-tools.7.html#json-output .

**Comment by hawkinchina** [comment]
how to Compile with json supported ?

**Comment by masatake** [comment]
See https://github.com/universal-ctags/ctags/pull/3272.
