### ISSUE TITLE
Splitting c.c into two parsers (c/c++ parser & the parser of the rest)

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#3327]
I have been thinking about how to proceed with the unification of the c.c parser in uctags and Geany and I think it would help, if we could separate the c/c++ part from the rest of the parsers and concentrate only on the non-c/c++ part. I'm not sure if the c/c++ parsers from c.c are still interesting for uctags e.g. for backwards compatibility but they are something we aren't interested in in Geany. I would suggest the following procedure:

1. Create a copy of `c.c`, e.g. called `c-based.c` that will serve as the base of the non-c/c++ parser.
2. Switch ctags to use `c-based.c` for parsing non-c/c++ languages and make sure ctags compiles and unit tests pass.
3. Remove all the definitions at the top of the parser related to other languages than c/c++ from `c.c`, follow compilation errors and remove the related code from the parser until it compiles.
4. Do the inverse of (2) for `c-based.c`, i.e. remove c/c++ parts and continue like in (2).
5. Do some cleanups.

At that point `c.c` would be left with the old parser and would probably not receive any further maintenance since it's superseded with the cxx parser while `c-based.c` would be the maintained parser for the rest of the languages.

I would do the same for Geany (except for keeping `c.c` as we won't need that one) so we would end up with a simplified `c-based.c` that would hopefully be easier to sync.

I haven't checked but is it still possible to use the old c/c++ parser instead of the cxx parser and is this one covered by some unit tests?

@masatake What do you think about this proposal?

**Comment by masatake** [comment]
Nice idea.
The OldC and OldC++ parsers can be still runnable if you pass an option like --languages=+OldC.
However, we don't need the OldC and OldC++ parsers anymore because C and C++ parsers in the cxx directory work very well.

**Comment by techee** [comment]
Closing in favor of #3332
