### ISSUE TITLE
The Lua parser generates an invalid tag name `{__index`

### ISSUE THREAD

**Issue by jubnzv** [universal-ctags/ctags#3346]
The name of the parser: `Lua`

The command line you used to run ctags:

```
$ ctags --options=NONE test.lua
```

The content of input file:

```C
setmetatable(t, {__index=function(self,k) return k end})
```

The tags output you are not satisfied with:

```
{__index	test.lua	/^setmetatable(t, {__index=function(self,k) return k end})$/;"	f
```

The tags output you expect:
The entry for `__index` has not been created. Or, at least, it should have a correct name `__index`, not `{__index`.

The version of ctags:

```
Universal Ctags 5.9.0(2f69ee90), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Apr 12 2022, 20:11:28
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript, +pcre2
```

How do you get ctags binary:
Building it locally, the same problem occurs with the release version.

**Comment by masatake** [comment]
Thank you for reporting.
I made a pull request (#3348) for solving this issue.
