### ISSUE TITLE
"make install" step fails

### ISSUE THREAD

**Issue by stefanhusmann** [universal-ctags/ctags#3359]
I have problems with the "make install" step when compileing ctags under Arch Linux. 
```
The key 2C3E7C7B5554E52E1EED06E6D49A3C26AF2DDCA0 does not exist in your keyring.
```
I do not know whre to get that key from and whose key it is.

**Comment by masatake** [comment]
Could you upload the output of "make install" to your gist?

**Comment by stefanhusmann** [comment]
Found the problem, it was a permission problem.

Sorry for the noise.

**Comment by masatake** [comment]
I see.
