### ISSUE TITLE
patch to fix/hint build failure

### ISSUE THREAD

**Issue by Shane-XB-Qian** [universal-ctags/ctags#3378]
```patch
diff --git a/configure.ac b/configure.ac
index c5eb1c5d..96f3f421 100644
--- a/configure.ac
+++ b/configure.ac
@@ -26,13 +26,13 @@ echo "$program_name, version $program_version"
 uname -mrsv 2>/dev/null
 
 AM_INIT_AUTOMAKE([foreign subdir-objects tar-ustar])
 AM_SILENT_RULES([yes])
 AC_CONFIG_HEADERS([config.h])
 
-m4_ifndef([PKG_CHECK_EXISTS], [m4_fatal([must install pkg-config 0.18 or later before running ./autogen.sh])])
+m4_ifndef([PKG_CHECK_EXISTS], [m4_fatal([must install pkg-config 0.18 or later (or tried to 'rm -f ./aclocal.m4') before running ./autogen.sh])])
 
 AC_CANONICAL_BUILD
 AC_CANONICAL_HOST
 
 case $host in
     *darwin*)
```

* Please Refer #2800 for detail.

```log
Universal Ctags 5.9.0(), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May  8 2022, 12:42:42
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +packcc, +optscript
```

**Comment by masatake** [comment]
I would like to know the condition when the change is needed.
I think it is better that configure doesn't know about autogen.sh.
If the condition allows, doing "rm -f ./aclocal.m4" in autogen.sh can be an alternative solution.

**Comment by Shane-XB-Qian** [comment]
> I would like to know the condition when the change is needed.

you can mock it by `echo '' > ./aclocal.m4`
then build it

> If the condition allows, doing "rm -f ./aclocal.m4" in autogen.sh can be an alternative solution. 

i agree, since it can re-generate, or whatever hint to the user about that perhaps is good also.

-- 
shane.xb.qian

**Comment by leleliu008** [comment]
![unknown_004](https://user-images.githubusercontent.com/3040852/167287652-d90bea1d-2e3d-4855-9ae4-396d0ab7fa63.png)

**Comment by leleliu008** [comment]
fisrt line of `aclocal.m4` file must match following:
```
# generated automatically by aclocal 1.16.5 -*- Autoconf -*-
```

if not match, when you run `autoreconf -f` will not remake `aclocal.m4`, I don't known why this happened, In general, `aclocal.m4` is created by `aclocal`, I new saw other tools can generate it. I never encoutered this issue.

**Comment by masatake** [comment]
@leleliu008 

> I don't known why this happened, In general, aclocal.m4 is created by aclocal, I never saw other tools can generate it. I never encoutered this issue.

Me, too. 
As far as I can remember correctly, this is not the first time to read/write "Please remove your aclocal.m4" on our issue trackers.
I assumed the build environments of reporters were just broken. 
So we didn't take any action.

As @Shane-XB-Qian agreed, putting "rm -f aclocal.m4" at the early stage of autogen.sh can be a rough solution.
I will make a pull request.

In addition, I'm thinking about the weekly or monthly "tar.gz" release that includes a generated configure file.

**Comment by leleliu008** [comment]
@masatake 
> As @Shane-XB-Qian agreed, putting "rm -f aclocal.m4" at the early stage of autogen.sh can be a rough solution.
I will make a pull request.

yes, run `rm -f aclocal.m4` before `autoreconf -vfi` will cause `aclocal.m4` always be regenerated as our expected.

> In addition, I'm thinking about the weekly or monthly "tar.gz" release that includes a generated configure file.

yes, It shall be done. autotools are developer tools which shall not be used by end-users.

**Comment by eli-schwartz** [comment]
> if not match, when you run `autoreconf -f` will not remake `aclocal.m4`, I don't known why this happened, In general, `aclocal.m4` is created by `aclocal`, I never saw other tools can generate it. I never encoutered this issue.


There are people who decide to put their handwritten macros in aclocal.m4, it's very sad as they should very much be using `m4/*` but I guess it would be bad if aclocal went and overwrote that.
