### ISSUE TITLE
autogen.sh does not work under CentOS 7

### ISSUE THREAD

**Issue by markusdd** [universal-ctags/ctags#3396]
I'm using a git repo clone using the latest tag p5.9.20220515.0

I cannot run autogen.sh, it fails complaining ybout pkg-config, but above that it prints that pkg config is present.
I'm lost, I cannot get this build to work on CentOS 7.

pkg-config, autotools, bunutils etc are all installed.

log:
```
 ./autogen.sh 
##################################################################
#                The paths and versions for tools                #
##################################################################
autoreconf is /usr/bin/autoreconf
------------------------------------------------------------------
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
##################################################################
aclocal is /usr/local/bin/aclocal
------------------------------------------------------------------
aclocal (GNU automake) 1.14
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
##################################################################
pkg-config is /usr/bin/pkg-config
------------------------------------------------------------------
0.27.1
##################################################################
autoconf is /usr/bin/autoconf
------------------------------------------------------------------
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
##################################################################
automake is /usr/local/bin/automake
------------------------------------------------------------------
automake (GNU automake) 1.14
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
##################################################################
#                        Generating files                        #
##################################################################
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:32: error: must install pkg-config 0.18 or later before running ./autogen.sh
configure.ac:32: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

```

**Comment by leleliu008** [comment]
how did you install the `automake` package? It seems that you manully installed the `automake` package.  because other tools are located in `/usr/bin/`, only `aclocal` and `automake` command are located in `/usr/local/bin/`.

I guess reinstall `automake` package via `yum` can resolve this problem. if error still there, please show us the result of following command:

```
aclocal --print-ac-dir
ls `aclocal --print-ac-dir`
```

**Comment by leleliu008** [comment]
another easiest solution is `export ACLOCAL_PATH=/usr/share/aclocal`

**Comment by markusdd** [comment]
I frankly cannot explain this. This is inside an nspawn container and I do not recall having compiled any custom software in there which should end up in /usr/local

But thank you for pointing this out, I did not notice bcause I would've never expected this^^

**Comment by masatake** [comment]
The original issue looks solved.
I wonder whether we should add code to detect the mismatch of the installation places to autogen.sh. Maybe it is overengineering.

**Comment by leleliu008** [comment]
@masatake I think we shoud provide ready-to-use configure in our source code released tarball. you mentioned this in https://github.com/universal-ctags/ctags/issues/3378#issuecomment-1120374665

**Comment by masatake** [comment]
> @masatake I think we shoud provide ready-to-use configure in our source code released tarball. you mentioned this in https://github.com/universal-ctags/ctags/issues/3378#issuecomment-1120374665

YES.

**Comment by k-takata** [comment]
The `make dist` command will create such tarball.

**Comment by leleliu008** [comment]
we currently create a new git tag every week via GitHub Actions workflow: https://github.com/universal-ctags/ctags/blob/master/.github/workflows/tagging.yml, it use `misc/git-tag-maybe.sh`, not `make dist`

**Comment by k-takata** [comment]
I think we can run `make dist` after tagging and create a GitHub Release by using [softprops/action-gh-release](https://github.com/softprops/action-gh-release) (or some other actions).

**Comment by leleliu008** [comment]
Do we consider to publish prebuild binary tarball?

**Comment by masatake** [comment]
> Do we consider to publish prebuild binary tarball?

No, I don't think about it at least on GNU/Linux.

**Comment by leleliu008** [comment]
Ok, I got it. I will built a staticly linked prebuild package in my own repo. I find some people do not known how to build a staticly linked ctags.
