### ISSUE TITLE
Homebrew Formula & website

### ISSUE THREAD

**Issue by cweagans** [universal-ctags/ctags#340]
Hello! I just wanted to let you know that I created a Homebrew formula for Mac users that allows them to install Universal Ctags. You can find it here: https://github.com/cweagans/homebrew-universal-ctags

I'd love to move that repo into the universal-ctags organization. If you want to add me to the org, I'll transfer it!

I'd also be interested in helping you guys out with a website, if you're interested. We can use Github Pages for simplicity, and I already own ctags.io, so we could use that for the web address. I helped Neovim with similar tasks and things seem to be running pretty well.

**Comment by cweagans** [comment]
@ffes I think you're the person that I'd need to talk to about this, right?

**Comment by ffes** [comment]
I really like this!
But for now I think it is too early to move your repo to the organization. Not even the main source repo has been moved yet.

I am not a Mac user myself, but I understand that homebrew is a repo for Mac users to get additional Linux(like) tools. And by adding your own tap you can add packages not provided by homebrew (similar to PPA for Ubuntu).

I see there is a formula for exuberant ctags in the homebrew repo.
Is there a change to get them to make the switch to universal? If so, is there any need for us to maintain our own homebrew repo? What would it take to get them to make the switch do you think?

**Comment by ffes** [comment]
And I personally would love to have ctags.io as our URL for our project, but it is not my decision. We have to discuss this with the other regular contributors.

**Comment by cweagans** [comment]
Homebrew is a package manager, yeah. Short term, this tap is probably the right way to go. When Universal Ctags has a 1.0.0 release, then we can submit a PR to the official homebrew repo to change over to Universal Ctags instead. For now, though, this provides an easy way for somebody to get started with Universal Ctags. I don't foresee a lot of maintenance for this tap - it shouldn't change that much as long as the build process stays the same.

Regarding the website, I'd suggest Github Pages for the actual site on ctags.io, and then Read The Docs for any documentation that we want to publish (perhaps on docs.ctags.io)

**Comment by cweagans** [comment]
@ffes The repo has been moved. Would you like to move the Homebrew formula too?

**Comment by cweagans** [comment]
Also, is there a more real-time communication method that contributors are using? IRC or Gitter or Slack or something?

**Comment by blueyed** [comment]
> Also, is there a more real-time communication method that contributors are using? IRC or Gitter or Slack or something?

See https://github.com/universal-ctags/ctags/issues/344#issuecomment-107753545.

I think IRC is fine.  `#ctags` is unused currently.
But we could also use another one.

**Comment by masatake** [comment]
@cweagans, thank you for working this area, but I don't know well about the environment of MacOSX.
As far as I know there is no MacOSX user in our organization. See docs/developers.rst.

We need someone who has interests hacking ctags and uses MacOSX as main working environment.

@cweagans, you are the such person?

**Comment by cweagans** [comment]
@masatake I'm more than happy to maintain the OSX build stuff - that won't be a problem at all. I'm not sure about contributing directly to ctags, as my C skills are not so great. I'm working on learning, but coming from a PHP background, there's quite a few new concepts to master.

**Comment by masatake** [comment]
@cweagans, could you write about your self in docs/developers.rst and send a pull request to us?
@ffes may arrange the other things.

**Comment by vhda** [comment]
Welcome @cweagans :)

**Comment by ffes** [comment]
@cweagans I will send you an invite to join the team. Still have to figure out exactly how the rights works, forgive me in advance the possible delay.

We need to come up with a proper name for your repo.

And would you like to write a docs/osx.rst? It could really help users of OSX and others devs in the team to know special things we need to think about in order to keep ctags as cross platform as possible.

**Comment by cweagans** [comment]
Thanks @vhda and @ffes - looking forward to helping out :)

The name of the repo can change, but it must start with homebrew- to function as a tap.

Happy to write an OS X doc. Nice thing is that it currently compiles on OS X and very few packages don't require anything special for that to happen. If we add OS X to the platform list in Travis, we can fail any PRs that don't build correctly on OS X and we won't run into major problems down the road!

**Comment by ffes** [comment]
OSX is already enabled on Travis-CI.

You should have received the invitation. With it you should be able to transfer the repo. If not, please let know.

**Comment by cweagans** [comment]
I've accepted the invite. Awesome - I'll get it moved tonight!

**Comment by ffes** [comment]
I see the transfer worked. Thanks for the contribution!
I will close this issue.

I will open a new one to discuss the details of your offer of ctags.io (if it still stands :wink:).

**Comment by cweagans** [comment]
Of course :)
