### ISSUE TITLE
XML with infinite recursion in parameters caused memory exhaustion and eventual segfault

### ISSUE THREAD

**Issue by kreynolds** [universal-ctags/ctags#3411]
Running on libxml2-2.9.13 (and probably others) causes a memory leak which consumes 1GB/s on my machine until memory is exhausted, resulting in a segfault.

*****

The command line you used to run ctags:

```
% ctags -R -f TAGS .
```

The content of input file:

Run recursively on [libxml2-2.9.14](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.9.13) without any changes

```

The version of ctags:

```
% ctags --version
Universal Ctags 5.9.0, Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun 12 2022, 01:37:10
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_fnmatch, +gnulib_regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript
```

How do you get ctags binary:

MacOS homebrew

**Comment by masatake** [comment]
Thank you for the reporting and investigation.

I run ctags with [libxml2-2.9.14](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.9.13) as input.

My ctags is built with `--enable-debugging`.
What I got is:

```
$ ./ctags /tmp/libxml2-v2.9.13/test/valid/t9a.xml
ctags: main/lregex.c:3027: makePromiseForAreaSpecifiedWithOffsets: Assertion `startOffset >= startLineOffset' failed.
ctags: main/lregex.c:3027: parsing /tmp/libxml2-v2.9.13/test/valid/t9a.xml:8 as XML
Aborted (core dumped)
```

You may use ctags with `--disable-debugging`. So the assertion was not triggered.
However, a wrong code violating the assertion may cause this issue.

The XML parser has a code detecting the area of DTD in a given input.
The code assumes UNIX style end of line (\n) is used in an input file.
However, t9a.xml uses DOS style end of line (\r\n).
This wrong assumption causes violating the assertion.

After converting the eol style of the input file, ctags runs without core-dumping.

**Comment by masatake** [comment]
I merged the change. If the latest code doesn't fix the issue, please, reopen this.

**Comment by kreynolds** [comment]
Took me a minute to verify as ctags would not build on macOS Monterey and I had to set up a docker container. Looks like it fixed the hang, thanks for the prompt response!
