### ISSUE TITLE
how to understand the error code which ctags returned

### ISSUE THREAD

**Issue by ijpq** [universal-ctags/ctags#3417]
> Universal Ctags 5.9.0(cbdc5c4b), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun 22 2022, 19:50:12
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +packcc, +optscript

i build the ctags from source and using gutentags in vim.

once i open a .cpp in vim, error msg show up: `ctags job failed, returned: 139`

is there any resolution?

**Comment by masatake** [comment]
The number implies the ctags process crashed.
I don't know both vim and gutentags. So for debugging, we need a way to trigger the crash by invoking the ctags command DIRECTLY.

Let's call the .cpp file you opened with vim `input.cpp`.

What happens when you run ctags directly like:
```
$ somewhere/ctags -o - somewhere/input.cpp
```

**Comment by ijpq** [comment]
> 

what the cli returned as follow:
CASE    dnn/src/cuda/norm/opr_impl.cpp  /^#define CASE(/;"      d       file:
Mode    dnn/src/cuda/norm/opr_impl.cpp  /^using Mode = Norm::Mode;$/;"  t       namespace:megdnn::cuda  typeref:typename:Norm::Mode     file:
cb      dnn/src/cuda/norm/opr_impl.cpp  /^#define cb(/;"        d       file:
cuda    dnn/src/cuda/norm/opr_impl.cpp  /^namespace cuda {$/;"  n       namespace:megdnn        file:
dispatch_mode   dnn/src/cuda/norm/opr_impl.cpp  /^void NormForwardImpl::dispatch_mode<Mode::INF_NORM>($/;"      f       class:megdnn::cuda::NormForwardImpl     typeref:typename:void
dispatch_mode   dnn/src/cuda/norm/opr_impl.cpp  /^void NormForwardImpl::dispatch_mode<Mode::NEG_INF_NORM>($/;"  f       class:megdnn::cuda::NormForwardImpl     typeref:typename:void
dispatch_mode   dnn/src/cuda/norm/opr_impl.cpp  /^void NormForwardImpl::dispatch_mode<Mode::P_NORM>($/;"        f       class:megdnn::cuda::NormForwardImpl     typeref:typename:void
exec    dnn/src/cuda/norm/opr_impl.cpp  /^void NormForwardImpl::exec($/;"       f       class:megdnn::cuda::NormForwardImpl     typeref:typename:void
get_workspace_in_bytes  dnn/src/cuda/norm/opr_impl.cpp  /^size_t NormForwardImpl::get_workspace_in_bytes($/;"   f       class:megdnn::cuda::NormForwardImpl     typeref:typename:size_t
megdnn  dnn/src/cuda/norm/opr_impl.cpp  /^namespace megdnn {$/;"        n       file:
p_type  dnn/src/cuda/norm/opr_impl.cpp  /^    typedef dt_float32 p_type;$/;"    t       function:megdnn::cuda::NormForwardImpl::dispatch_mode   typeref:typename:dt_float32     file:

**Comment by masatake** [comment]
In that case, I recommend you to talk to gutentags about what kind of options gutentags passes to ctags.

If you use ctags on GNU/Linux, the strace command may help you.
Do you want to try inspecting with the strace command?

**Comment by ijpq** [comment]
> In that case, I recommend you to talk to gutentags about what kind of options gutentags passes to ctags.
> 
> If you use ctags on GNU/Linux, the strace command may help you. Do you want to try inspecting with the strace command?

i fix some erro bug got a ctags error like that:
```bash
'ctags -f "/home/tangke/.cache/tags/home-tangke-MegBrain-.tags.temp" "--options=/home/tangke/.vim_runtime/my_plugins/vim-gutentags/res/ctags_recursive.options"  --fields=+niazS --extra=+
q --c++-kinds=+px --c-kinds=+px --extras=+q --output-format=e-ctags --exclude=@/home/tangke/.cache/tags/_wildignore.options --exclude=*/MegBrain/third_party/* "/home/tangke/MegBrain"'                            
gutentags: [job stderr]: 'ctags: Warning: --extra option is obsolete; use --extras instead'                                                                                                                        
gutentags: [job stderr]: 'ctags: Warning: cannot open input file "/home/tangke/MegBrain/dnn/expr/cuda_topk/gtest" : No such file or directory'                                                                     
gutentags: [job stderr]: 'ctags: Warning: cannot open input file "/home/tangke/MegBrain/dnn/expr/cuda_bitonic/gtest" : No such file or directory'                                                                  
gutentags: [job stderr]: 'Segmentation fault (core dumped)'
```
** what command or file generate the path `home/tangke/MegBrain/dnn/expr/cuda_bitonic/gtest` **

**Comment by masatake** [comment]
Thank you.

> ** what command or file generate the path home/tangke/MegBrain/dnn/expr/cuda_bitonic/gtest **

As "--options=/home/tangke/.vim_runtime/my_plugins/vim-gutentags/res/ctags_recursive.options" implies, ctags might parsed files under "/home/tangke/MegBrain" recursively. ctags didn't read the `gtest` file as the warning told. So I guess there is another reason for the crash.

```
$ ctags --verbose -f "/home/tangke/.cache/tags/home-tangke-MegBrain-.tags.temp" "--options=/home/tangke/.vim_runtime/my_plugins/vim-gutentags/res/ctags_recursive.options"  --fields=+niazS --extra=+
q --c++-kinds=+px --c-kinds=+px --extras=+q --output-format=e-ctags --exclude=@/home/tangke/.cache/tags/_wildignore.options --exclude='*/MegBrain/third_party/*' "/home/tangke/MegBrain"  > /tmp/ctags-verbose.log 2>&1 
$ grep 'Get file language for\|ignoring'  /tmp/ctags-verbose.log| tail -100
```

(I put quote characters around the argument for --exclude. I guess the characters are needed.)

The command lines are for extracting file names that ctags openes for parsing.
The last file in the output is a suspicious file.

**Comment by masatake** [comment]
Do you know gdb and is it available on your platform?

**Comment by ijpq** [comment]
> Do you know gdb and is it available on your platform?

yes，it is available

**Comment by ijpq** [comment]
> Thank you.
> 
> > ** what command or file generate the path home/tangke/MegBrain/dnn/expr/cuda_bitonic/gtest **
> 
> As "--options=/home/tangke/.vim_runtime/my_plugins/vim-gutentags/res/ctags_recursive.options" implies, ctags might parsed files under "/home/tangke/MegBrain" recursively. ctags didn't read the `gtest` file as the warning told. So I guess there is another reason for the crash.
> 
> ```
> $ ctags --verbose -f "/home/tangke/.cache/tags/home-tangke-MegBrain-.tags.temp" "--options=/home/tangke/.vim_runtime/my_plugins/vim-gutentags/res/ctags_recursive.options"  --fields=+niazS --extra=+
> q --c++-kinds=+px --c-kinds=+px --extras=+q --output-format=e-ctags --exclude=@/home/tangke/.cache/tags/_wildignore.options --exclude='*/MegBrain/third_party/*' "/home/tangke/MegBrain"  > /tmp/ctags-verbose.log 2>&1 
> $ grep 'Get file language for\|ignoring'  /tmp/ctags-verbose.log| tail -100
> ```
> 
> (I put quote characters around the argument for --exclude. I guess the characters are needed.)
> 
> The command lines are for extracting file names that ctags openes for parsing. The last file in the output is a suspicious file.

this cli gets:
```bash
(omit for too long)
OPENING /home/tangke/MegBrain/dnn/src/cuda/cub/agent/agent_scan.cuh as CUDA language file [new]
Get file language for /home/tangke/MegBrain/dnn/src/cuda/cub/agent/agent_radix_sort_downsweep.cuh
        pattern: agent_radix_sort_downsweep.cuh
                #candidates: 1
                        0: CUDA (extension: "cuh")
                #candidates after sorting and filtering: 1
                        0: CUDA (extension: "cuh")
OPENING /home/tangke/MegBrain/dnn/src/cuda/cub/agent/agent_radix_sort_downsweep.cuh as CUDA language file [new]
Segmentation fault (core dumped)
```
there is a segmentation fault which i think is a binary execution problem.

**Comment by masatake** [comment]
The next command line may cause the crash.
```
$ ctags --fields=+niazS --extra=+q --c++-kinds=+px --c-kinds=+px --extras=+q --output-format=e-ctags /home/tangke/MegBrain/dnn/src/cuda/cub/agent/agent_radix_sort_downsweep.cuh
```

Is it possible to put /home/tangke/MegBrain/dnn/src/cuda/cub/agent/agent_radix_sort_downsweep.cuh your gist?

If it is impossible. You have to make a reproducer; make /home/tangke/MegBrain/dnn/src/cuda/cub/agent/agent_radix_sort_downsweep.cuh short and simple as much as possible.

See #3387 as an example of making the test input short and simple.
If the input becomes enough short, I expect the input file can be uploaded.

Good luck!

**Comment by masatake** [comment]
Reproduced with https://raw.githubusercontent.com/NVIDIA/cub/main/cub/agent/agent_radix_sort_downsweep.cuh.

**Comment by masatake** [comment]
Shrinked input reproducing the issue:

```
template <class T>
struct A
{
	S<F>();
};
```

**Comment by masatake** [comment]
This issue is an excellent example of specifying the input causing a crash.

**Comment by masatake** [comment]
I merge the pull request.
If the issue is still reproduced, reopen this issue.
Thank you for taking your time for finding the input causing the crash.

**Comment by ijpq** [comment]
> I merge the pull request. If the issue is still reproduced, reopen this issue. Thank you for taking your time for finding the input causing the crash.


i haven'y had time to read carfully after your previous reply, but it is very appreciate that your patience in reply me in such details.
if there is any problem, i would report a new issue. good luck to u-ctags!
best
