### ISSUE TITLE
Can't get the end line of function for lua language

### ISSUE THREAD

**Issue by bobleer** [universal-ctags/ctags#3420]
```
ctags --fields=+NCEKRSTZaefiklmnoprstxz -u -R -o test.txt test.lua
```

I use the command above to parse a lua file, the `test.txt` includes the start line num without the end line num.

Does ctags not support this feature?
Will ctags support this feature in the future?

**Comment by masatake** [comment]
> Does ctags not support this feature?

The lua parser of ctags doesn't support the feature.

>  Will ctags support this feature in the future?

Yes if someone implements the feature. As far as I know, none is working on it now.

**Comment by masatake** [comment]
I answered the questions.
