### ISSUE TITLE
xcmd: coffeetags is not available

### ISSUE THREAD

**Issue by vhda** [universal-ctags/ctags#343]
ctags complains that coffeetags is not available. In my opinion no warning should be displayed in ctags for a feature that the user is not running.
Would it be possible to update the code such that this warning is only shown if the availability of coffeetags would improve the tags processing of the files being parsed?

**Comment by masatake** [comment]
This is the nth times I heard the complain about the warning of xcmd.
This is the time to fix it.

**Comment by vhda** [comment]
These complains are even plaguing StackOverflow, so it's really important to improve this behavior.
Thanks a lot for the quick fix and excellent work in tests creation!

**Comment by masatake** [comment]
Currently only coffeetags uses the xcmd facility.
I wanted more examples before removing such debugging oriented code.
