### ISSUE TITLE
Update Github repository description

### ISSUE THREAD

**Issue by vhda** [universal-ctags/ctags#346]
The current description "**clone of official ctags repo with obj-c and css patches added**" does not reflect all the new functionality of the project.

**Comment by vhda** [comment]
My 1st proposal: "Fork of Exuberant Ctags with focus on the development of new features".

Currently assigned to @masatake but I expect inputs from everyone :)

**Comment by ffes** [comment]
@vhda good catch :wink:

My proposal for now would be something like "The continuation of exuberant ctags"

**Comment by masatake** [comment]
Could you add following sentence (if it is written correctly) to the page?

> The goal of the project is preparing and maintaining common/unified
space where people interested in making ctags better can work
together.

**Comment by steveno** [comment]
This would be more correct:

The goal of this project is preparing and maintaining a common/unified
space where people interested in making ctags better can work
together.

**Comment by masatake** [comment]
@steveno, thanks.

**Comment by ffes** [comment]
I think this sentence is really nice for the readme (where it is is already), but it is too long as the github description shown above the code tree. I think that is what @vhda is referring to.

**Comment by vhda** [comment]
Yes @ffes that is what I was referring to.
And I would also prefer a shorter sentence.

**Comment by masatake** [comment]
@ffes, I see. 
Changing the name is the primary thing I seriously wanted.Not we got a new name so I don't want more. But I will submit one to learn English:-P

> Actively maintained ctags implementation

**Comment by steveno** [comment]
@vhda @ffes, Something more like this:

> A modern, expanded, and updated fork of ctags.

**Comment by ffes** [comment]
@masatake :+1:

**Comment by cweagans** [comment]
When a decision is made here, please open an issue in the universal-ctags.github.io repository to update the tagline on the website.

**Comment by masatake** [comment]
How about mine?: Actively maintained ctags implementation

It is o.k. to remove "Actively": the maintained ctags implementation.
It is o.k. to replace "the" with "a": a maintained ctags implementation.

You may feel this is conservative or modest comparing with your proposal. 
However, what we have been doing is just maintaining.
And it is what I'm proud of. During contributing many projects randomly I found how important a project is maintained. A project is maintained, so people can contribute to it. If the project is maintained, many projects are forked, as you know. Search "ctags" in github.

I think the most of all existing users just want something maintained ctags.

**Comment by vhda** [comment]
Fair enough. And since this is my preferred proposal up until now you have my :thumbsup:

**Comment by masatake** [comment]
@cweagans, I updated the description line of https://github.com/universal-ctags/universal-ctags.github.io page. Am I correct?

**Comment by ffes** [comment]
I will update the site's tagline and description (both in _config.yml) as well.

**Comment by masatake** [comment]
@ffes, thank you. Please, fix if I did something wrong.

**Comment by ffes** [comment]
@masatake I just updated the description on this repo as well.

**Comment by cweagans** [comment]
@ffes I updated _config.yml. I think we're all set here.

**Comment by cweagans** [comment]
Actually, there's one more change here. Can you change the link to https://ctags.io instead of http://ctags.io ? I know there's a redirect, but we should use the canonical link as much as possible.

**Comment by masatake** [comment]
@cweagans, I did.

**Comment by masatake** [comment]
Can I close this?

**Comment by cweagans** [comment]
The link on the repo description is still pointing to http://ctags.io:  http://take.ms/CaGJv

**Comment by masatake** [comment]
Oh, sorry. I misunderstood. I had changed the link to http://ctags.io. 
I have changed https://ctags.io.
