### ISSUE TITLE
Rake: crash and core dump.

### ISSUE THREAD

**Issue by nachose** [universal-ctags/ctags#3474]
In a big project, so don't know the file that is causing the issue.

I'm in the last commit: [096dc1c](https://github.com/universal-ctags/ctags/commit/096dc1c1337edeff41c3e6600553c3b43bdde131)

the core gives me the following stack trace:

gdb$ bt
#0  0x00000000004618f8 in parseXTask (cp=<optimized out>, xtask=<optimized out>, s=0x5731e0 <rakeSubparser>) at parsers/rake.c:187
#1  lineNotify (s=0x5731e0 <rakeSubparser>, cp=<optimized out>) at parsers/rake.c:222
#2  0x0000000000465227 in notifyLine (cp=<optimized out>) at parsers/ruby.c:960
#3  findRubyTags () at parsers/ruby.c:1156
#4  0x0000000000410aa2 in createTagsForFile (passCount=0x1, language=0x69) at main/parse.c:3757
#5  createTagsWithFallback1 (language=language@entry=0x69, exclusive_subparser=exclusive_subparser@entry=0x0) at main/parse.c:3906
#6  0x0000000000410d06 in runParserInNarrowedInputStream (language=0x69, startLine=0x0, startCharOffset=0x0, endLine=0x0, endCharOffset=0x0, sourceLineOffset=0x0, promise=promise@entry=0x0) at main/parse.c:3976
#7  0x0000000000411c36 in forcePromises () at main/promise.c:177
#8  0x0000000000410db4 in createTagsWithFallback (failureInOpenning=<synthetic pointer>, mtime=0x0, mio=<optimized out>, language=0x61, fileName=0x12c6a70 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb/Rakefile") at main/parse.c:4000
#9  parseMio (fileName=fileName@entry=0x12c6a70 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb/Rakefile", language=language@entry=0x61, mio=<optimized out>, mtime=0x0, useSourceFileTagPath=useSourceFileTagPath@entry=0x1, clientData=clientData@entry=0x0) at main/parse.c:4160
#10 0x0000000000410ecc in parseFileWithMio (fileName=fileName@entry=0x12c6a70 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb/Rakefile", mio=mio@entry=0x0, clientData=clientData@entry=0x0) at main/parse.c:4207
#11 0x0000000000410fc9 in parseFile (fileName=fileName@entry=0x12c6a70 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb/Rakefile") at main/parse.c:4143
#12 0x0000000000403bf8 in createTagsForEntry (entryName=entryName@entry=0x12c6a70 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb/Rakefile") at main/main.c:221
#13 0x0000000000403ab4 in recurseUsingOpendir (dirName=0x11e2110 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb") at main/main.c:115
#14 recurseIntoDirectory (dirName=dirName@entry=0x11e2110 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb") at main/main.c:184
#15 0x0000000000403c50 in createTagsForEntry (entryName=entryName@entry=0x11e2110 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib/rb") at main/main.c:215
#16 0x0000000000403ab4 in recurseUsingOpendir (dirName=0x117e890 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib") at main/main.c:115
#17 recurseIntoDirectory (dirName=dirName@entry=0x117e890 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib") at main/main.c:184
#18 0x0000000000403c50 in createTagsForEntry (entryName=entryName@entry=0x117e890 "/repo/esecjos/primary/epg/3pp/sources/thrift/lib") at main/main.c:215
#19 0x0000000000403ab4 in recurseUsingOpendir (dirName=0x1049700 "/repo/esecjos/primary/epg/3pp/sources/thrift") at main/main.c:115
#20 recurseIntoDirectory (dirName=dirName@entry=0x1049700 "/repo/esecjos/primary/epg/3pp/sources/thrift") at main/main.c:184
#21 0x0000000000403c50 in createTagsForEntry (entryName=entryName@entry=0x1049700 "/repo/esecjos/primary/epg/3pp/sources/thrift") at main/main.c:215
#22 0x0000000000403ab4 in recurseUsingOpendir (dirName=0x1711e20 "/repo/esecjos/primary/epg/3pp/sources") at main/main.c:115
#23 recurseIntoDirectory (dirName=dirName@entry=0x1711e20 "/repo/esecjos/primary/epg/3pp/sources") at main/main.c:184
#24 0x0000000000403c50 in createTagsForEntry (entryName=entryName@entry=0x1711e20 "/repo/esecjos/primary/epg/3pp/sources") at main/main.c:215
#25 0x0000000000403ab4 in recurseUsingOpendir (dirName=0x158ba50 "/repo/esecjos/primary/epg/3pp") at main/main.c:115
#26 recurseIntoDirectory (dirName=dirName@entry=0x158ba50 "/repo/esecjos/primary/epg/3pp") at main/main.c:184
#27 0x0000000000403c50 in createTagsForEntry (entryName=entryName@entry=0x158ba50 "/repo/esecjos/primary/epg/3pp") at main/main.c:215
#28 0x0000000000403ab4 in recurseUsingOpendir (dirName=0x158b820 "/repo/esecjos/primary/epg") at main/main.c:115
#29 recurseIntoDirectory (dirName=dirName@entry=0x158b820 "/repo/esecjos/primary/epg") at main/main.c:184
#30 0x0000000000403c50 in createTagsForEntry (entryName=entryName@entry=0x158b820 "/repo/esecjos/primary/epg") at main/main.c:215
#31 0x0000000000403ab4 in recurseUsingOpendir (dirName=0xfdb6a0 "/repo/esecjos/primary") at main/main.c:115
#32 recurseIntoDirectory (dirName=dirName@entry=0xfdb6a0 "/repo/esecjos/primary") at main/main.c:184
#33 0x0000000000403c50 in createTagsForEntry (entryName=0xfdb6a0 "/repo/esecjos/primary") at main/main.c:215
#34 0x0000000000403f98 in createTagsForArgs (args=0xfdb640) at main/main.c:266
#35 batchMakeTags (args=0xfdb640, user=<optimized out>) at main/main.c:360
#36 0x0000000000404218 in runMainLoop (args=0xfdb640) at main/main.c:332
#37 ctags_cli_main (argc=<optimized out>, argv=0x7ffd3a5a7d30) at main/main.c:586
#38 0x00007f382a6a4555 in __libc_start_main () from /lib64/libc.so.6
#39 0x000000000040392e in _start ()

I avoided the crash doing this a rake.c line 187:

 if(e)
 {
     e->extensionFields.typeRef [0] = eStrdup ("typename");
     e->extensionFields.typeRef [1] = eStrdup (xtask->keyword);
     return r;
 }

but I don't undertand the implications.

Regards.

**Comment by masatake** [comment]
Thank you for reporting.
I reproduced the same crash with:
```
$ cat /tmp/Rakefile 
RSpec::Core::RakeTask.new(:'x')
$ ./ctags -o - /tmp/Rakefile 
zsh: segmentation fault (core dumped)  ./ctags -o - /tmp/Rakefile
```

I will fix this.

**Comment by masatake** [comment]
#3475 may fix this.
