### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by ffes** [universal-ctags/ctags#348]
In #340 @cweagans offered us to use ctags.io (which he owns) to use for our project.
It is quite easy to link a domain name to the github pages placeholder that I have created.
https://help.github.com/articles/adding-a-cname-file-to-your-repository/

I think it is a great URL and I really like the idea.
But how do the others think about this offer?

**Comment by cweagans** [comment]
FWIW: I also offered to build a real website :)

**Comment by blueyed** [comment]
:+1: 

@cweagans 
Thanks, and welcome to the team! :)

**Comment by steveno** [comment]
Sounds good to me :+1:

**Comment by cweagans** [comment]
This is done.
