### ISSUE TITLE
Comments within shell code of markdown fiiles are recognized as chapters

### ISSUE THREAD

**Issue by lpyparmentier** [universal-ctags/ctags#3483]
Hello,

I think the title should be explicit enough. If not I hope that the following image will (`that's it !` shouldn't be a chapter):

![image](https://user-images.githubusercontent.com/64089179/190668067-6cd3d7e7-95b1-4a56-838c-a2389137d914.png)

I've notice this problem by using VI with the plugin preservim which uses universal-ctags to generate the right window, see the related issue: https://github.com/preservim/tagbar/issues/832

The version of ctags:

```
$ ctags --version
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  6 2019, 23:23:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml
```

How do you get ctags binary:

Installed with apt package manager on Ubuntu 20.04.5 LTS

**Comment by masatake** [comment]
Please, don't use a screenshot. 
Copy the source code causing trouble as text.

> I think the title should be explicit enough.

I don't think so.

**Comment by masatake** [comment]
You should use the template for reporting a parser bug.

https://github.com/universal-ctags/ctags/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by masatake** [comment]
Please, reopen this as a new issue with text input, not screenshot.

**Comment by lpyparmentier** [comment]
ok thanks, I'm sorry, I don't know exactly how the plugin is calling the ctags. I have take a look how I can have more debug.

**Comment by masatake** [comment]
What I need is the input text you showed on your text editor.
So I can run ctags with the input.

**Comment by masatake** [comment]
You don't provide the input text.
So I have to do OCR. 

```
$ cat /tmp/foo.md
# Chapter 1

## Subsction

List a file:

```sh
# that's it!
ls
```
$ ./ctags --options=NONE  -o -  /tmp/foo.md 
ctags: Notice: No options will be read from files or environment
Chapter 1	/tmp/foo.md	/^# Chapter 1$/;"	c
Subsction	/tmp/foo.md	/^## Subsction$/;"	s	chapter:Chapter 1
$ 
```

I couldn't reproduce the issue with the latest ctags.

I guess you used older ctags or a file under your ~/.ctags.d is imperfect. --options=NONE as the first argument lets ctags unread options files under ~/.ctags.

**Comment by masatake** [comment]
```
  Compiled: Jan  6 2019, 23:23:29
```

Too old.
