### ISSUE TITLE
Running ctags with --options=.ctags under windows (sf-bug:366)

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#349]
http://sourceforge.net/p/ctags/bugs/366/

Is this reproduce with universal-ctags, too?

@ffes, could you look at this?

**Comment by ffes** [comment]
I guess the reporter of the problem on SF is @vadz

I can confirm that it is a problem on Windows in our repo as well.
Haven't tested it yet under Linux, but I don't think it is platform specific.

.ctags and ctags.cnf both give the error. But ctags.conf doesn't give the error.
Adding --verbose gives a clue.

```
Considering option file /ctags.cnf: not found
Considering option file /etc/ctags.conf: not found
Considering option file /usr/local/etc/ctags.conf: not found
Considering option file C:\cygwin\home\Frank\.ctags: not found
Considering option file C:\cygwin\home\Frank\ctags.cnf: not found
Considering option file .\.ctags: reading...
Considering option file .\ctags.cnf: reading...
Reading initial options from command line
  Option: --options=ctags.cnf
Considering option file ctags.cnf: already considered
ctags.exe: cannot open option file "ctags.cnf" : No error
```

Both filenames that fail are the default filenames already already considered.

In options.c in parseFileOptions() the return value remains false when the file is already considered. 
https://github.com/universal-ctags/ctags/blob/master/main/options.c#L2309
I have will prepare a fix

**Comment by masatake** [comment]
Oh, sorry, it is not platform specific. Feel free to assign to me.

**Comment by masatake** [comment]
Approach:

1. Introduce parseFileOptions(const char* const fileName, bool whetherCheckSameFile);
    This function does the same as current parseFileOptions but calling checkSameFile only if whetherCheckSameFIle is true.

2. Rewrite parseFileOptions
   New parseFileOptions jsut calls paresFileOptions(fileName, TRUE);

3. Modify processOptionFile
    if (!checkSameFile()) parseFileOptions(fileName, FALSE));

Discussion:
   Should we notify to the user that ".ctags is already loaded".

   Loading .ctags of current directory may be unsafe it xcmd is specfined in the .ctags.

   checkSameFile function uses a file static variable named CheckFile. We should not do so.
   Extend stringListHasTest function: boolean stringListHasTest (const stringList *const current, boolean (*test)(const char* s, void *), void *user_data);

**Comment by vhda** [comment]
Why not simply make `parseFileOptions` return TRUE when file is already considered?
If we raise the "already considered" message from verbose to notice, then the user can fix his command call (or script) to avoid this non-optimal configuration. But even if we keep it as verbose, I don't see any real issues with this behavior.

In my opinion it is important to maintain the "local config-> home config -> global config" load order, as it is widely used in software and users may already rely on it in their workflow. Any security considerations should be taken in the xcmd section.
But then again, can you think of a scenario where it wouldn't require root privileges for xcmd to be unsafe?

**Comment by masatake** [comment]
(O.k. Let's forget the xcmd issue here.)
(My approach is not suitable for this situation.)

exuberant ctags stops when a user requets the same config file twice from command line.
I thinks this is meaningful. The order of options are important in ctags, so the requests of user is wrong.
In such case rejecting the request and stopping are not bad.

The problem is that .ctags file is automatically loaded.  A user may specify --options=.ctags if the one doesn't know .ctags is loaded automatically. Is such case, again,  rejecting the option and stopping are o.k. 

 $ ./ctags --options=NONE --options=.ctags

This works fine.

This means our answer for sf-bug:366 is not a bug.

Too complex?

**Comment by masatake** [comment]
Anyway we should remove file static variable in the code.

**Comment by vadz** [comment]
It wouldn't be a problem if this were error _provided_ that the error message is more clear, i.e. just says `configuration file .ctags specified twice` instead of the current confusing `cannot open options file`.

**Comment by masatake** [comment]
I would like to solve this issue by myself. I'm thinking of introducing the mechanism to track the origin of options: cmdline, autoload-file(systemdir, homedir, currentdir,...).
The information of origin will help us print more clear messages as @vadz wrote.

**Comment by vhda** [comment]
I'm still in favor of the KISS principle.
ctags already tracks the already loaded configuration files, so a file is not loaded twice. If we want to increase complexity (and reduce *performance*) we should at least have a functional gain. In this specific case I don't see a gain in telling the user "Hey! We already loaded that file, so why are you trying to load it again?"

What if the user is passing the options file through a script that automatically determines its location depending on `$PWD`? Now assume that only in a few cases the selection algorithm determines that it should load `.ctags`. The user may have to make his script more complex just to be able to run ctags because we are checking something that is not a source of any error in run time for us.

**Comment by ffes** [comment]
The "quick fix" just setting the return value to TRUE does not solve the problem, well at least on Windows.

Something strange happens somewhere at https://github.com/universal-ctags/ctags/blob/master/main/main.c#L182
`ctags --verbose --option=.ctags .` gives a error:
`Warning: cannot open source file "test" : No such file or directory` (test is the name of the directory I am testing in)

Don't have access to Linux machine ATM to test. The _findfirst() where this problem occurs is a Windows specific piece of code.

And `ctags --verbose --option=.ctags *` asserts somewhere in c.c (seems unrelated, but still a problem).

So still investigating.

**Comment by ffes** [comment]
I have created a branch with the easy fix.
https://github.com/ffes/ctags/tree/fix-349

I will test it (hopefully tonight) under Linux, because of the problems described above on Windows. If that test passes, I will create a PR.

**Comment by masatake** [comment]
@ffes, thank you. Look at Tmain, we can test this area like units. It is not integrated with travis but it is useful to share a bug within us.

**Comment by masatake** [comment]
@vadz, @ffes introduced a fix for this issue. Now ctags say nothing when loading the same option(config) file twice: just loading once.

I will work on introducing a facility to prepare better warning as you suggested but I think just loading once is enough for now.
