### ISSUE TITLE
there should be a way to disable the extra that includes anonymous entities

### ISSUE THREAD

**Issue by rick-kilgore** [universal-ctags/ctags#3511]
I don't find it very helpful to have the anonymous entities in my tags list, and when combined with this tools use along with the vim tagbar plugin, the effect is quite annoying.  In some source files, I can barely see my real functions between all the __anonxyzpdq ones (see attached pic).

![ctags-anonymous](https://user-images.githubusercontent.com/4665096/196566188-63cbb290-b9c3-4462-bd6b-d20c51a1cd1b.png)

**Comment by masatake** [comment]
Run ctags with `--extras=-{anonymous}`.
