### ISSUE TITLE
Q: __func__ in msvc

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#3516]
@k-takata I have a question about msvc.

During making a pull request, I found msvc didn't know `__func__`.
`__func__` is part of C99.

`__func__` is so useful for debugging and making useful error messages.
Don't you know any alternative to `__func__` in msvc?

As far as reading 
https://learn.microsoft.com/ja-jp/cpp/preprocessor/predefined-macros?view=msvc-140,
`__func__` is available. Do we use older msvc?

**Comment by k-takata** [comment]
Currently, we support VC++ 2013 or later, and I think we use it on AppVeyor.
VC++ 2015 has better support for C99. I think we can drop support for 2013.

**Comment by k-takata** [comment]
MSVC has `__FUNCTION__`.
https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros

**Comment by masatake** [comment]
Thank you!

**Comment by masatake** [comment]
> I think we can drop support for 2013.

I will reopen this when 2023:-)
