### ISSUE TITLE
ctags for .bib files

### ISSUE THREAD

**Issue by TryerGit** [universal-ctags/ctags#3518]
As suggested [here](https://github.com/universal-ctags/ctags/issues/3515#issuecomment-1287579042), I am breaking the issue into two issues. This issue is for ctags generation of `.bib` files.

The file on which I run ctags is `bibfile.bib`:

`bibfile.bib`:
```tex
@Article{somekeyother,
  title     = {Yet A super awesome paper}
}

@Article{somekey,
  title     = {A super awesome paper}
}

```
On running the (universal) ctags as : `ctags bibfile.bib`, I obtain the following `tags` file:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	//
```

That is, only metadata is obtained, no tags are generated. This tells me that there is no default built-in support in ctags for `.bib` files. Is this correct?

On re-running the above command, this time with the following in place: `~/.ctags.d/bib.ctags` (taken from [this](https://stackoverflow.com/a/8119630/492307) answer):

```
--langdef=bib
--langmap=bib:.bib
--regex-bib=/^@[A-Za-z]+\{([^,]*)/\1/b,bib/

```
I obtain the following `tags` file:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	//
somekey	bibfile.bib	/^@Article{somekey,$/;"	b
somekeyother	bibfile.bib	/^@Article{somekeyother,$/;"	b

```
So, in this case, `somekey` and `somekeyother` are generated as tags.

On running the (exuberant) ctags as : `ctags bibfile.bib`, I obtain the following `tags` file:
```

!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
somekey	bibfile.bib	/^@Article{somekey,$/;"	b
somekeyother	bibfile.bib	/^@Article{somekeyother,$/;"	b
```
It is noted that the only difference between the two `tags` files is in the metadata alone. Both versions (exuberant as well as universal) generate the same actual tags: `somekey` and `somekeyother`.

Could you please clarify that the right way to use universal ctags on `.bib` files is to have a `~/.ctags.d/bib.ctags` file with content as specified above?

Thank you.

**Comment by masatake** [comment]
```
!_TAG_PROGRAM_VERSION	0.0.0
```

This implies you use old u-ctags.

These days, u-ctags reports something like:
```
!_TAG_PROGRAM_VERSION   5.9.0   /5dc6ad1b0/
```

At least 5.9.0 should be printed.

So consider introducing newer version of u-ctags.

The newer u-ctags may have a built-in Bibtex parser.
So you don't need ~/ctags.d/bibtex.ctags anymore.

`--options=NONE` is a useful option that makes ctags not read ~/.ctags.d/*.ctags files.

```
[yamato@dev64]~% cat /tmp/foo.bib                        
@Article{somekeyother,
          title     = {Yet A super awesome paper}
}

@Article{somekey,
          title     = {A super awesome paper}
}
[yamato@dev64]~% ~/bin/ctags --options=NONE -o - /tmp/foo.bib
ctags: Notice: No options will be read from files or environment
somekey /tmp/foo.bib    /^@Article{somekey,$/;" a
```

**Comment by TryerGit** [comment]
> At least 5.9.0 should be printed.

Thank you. I see. Let me try that. I installed it via `sudo apt-get update` and `sudo apt install universal-ctags`

Perhaps I should do a make-build custom install.
