### ISSUE TITLE
Fortran parser: Problem mixing free and fixed form

### ISSUE THREAD

**Issue by mjaj** [universal-ctags/ctags#3529]
Hello,

I ran into another issue with the fortran parser, shown here in a strongly simplified example. I am not sure how far I can reduce this.

I work with 2 fortran files, one in free form, `a.f90`, and one in fixed form, `b.f`.
```
$ cat -n a.f90
     1  subroutine s1
     2  real            :: a,b,c,d
     3  if (a .eq. b .and. &
     4         c. eq. d) then
     5      a=0
     6  endif
     7  end
```
```
$ cat -n b.f
     1        program p1
     2        character*5  s
     3  c
     4        character*5  r
     5        r="abcde"
     6        end
```
Processing the files independently gives expected output:
```
$ ctags --verbose a.f90
....
OPENING a.f90 as Fortran language file [new]
Initialize parser: Fortran
a.f90: not fixed source form; retry as free source form
sorting tag file
```
generates
```
s1      a.f90   /^subroutine s1$/;"     s
```
and 
```
$ ctags --verbose b.f
....
OPENING b.f as Fortran language file [new]
Initialize parser: Fortran
sorting tag file
```
leads to 
```
p1      b.f     /^      program p1$/;"  p
r       b.f     /^      chara/;"        v       program:p1
s       b.f     /^      character*5  s$/;"      v       program:p1
```
However, when I generate the tags together, the output is
```
$ ctags --verbose a.f90 b.f
....
OPENING a.f90 as Fortran language file [new]
Initialize parser: Fortran
a.f90: not fixed source form; retry as free source form
...
OPENING b.f as Fortran language file [new]
b.f: not fixed source form; retry as free source form
sorting tag file
```
with the tags
```
p1      b.f     /^      program p1$/;"  p
s       b.f     /^      character*5  s$/;"      v       program:p1
s1      a.f90   /^subroutine s1$/;"     s
```
The second variable `r` in `b.f` is missing. Note that `b.f` is now not recognized as fixed source form, and presumably the parser is thus confused by the comment sign `c` in the first column.
I get the correct results if I either

- remove the comment sign in `b.f`, or replace it by `!`
- change the order of the files in the call to ctags

This is, however, not a desirable option, working with a large legacy code with files in different formats and styles.

```
$ ctags.exe --version
Universal Ctags 5.9.0(83c1a09), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 11 2022, 03:08:25
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +gnulib_regex, +internal-sort, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript, +pcre2
```
(downloaded from https://github.com/universal-ctags/ctags-win32 )

**Comment by masatake** [comment]
Thank you for reporting.
#3545 may fix this.

BTW, 
```
r       b.f     /^      chara/;"        v       program:p1
```

How do you think about this?
r is extracted well but the pattern looks too short for me.
Do you think this is anther bug?

**Comment by masatake** [comment]
@mjaj, thank you for confirming.
I will fix the shortness more.

**Comment by masatake** [comment]
I opened a new issue #3529 for the unexpected truncation.
#3545 is ready for merge.
