### ISSUE TITLE
autogen.sh doesn't work

### ISSUE THREAD

**Issue by GreenAsFuck** [universal-ctags/ctags#3538]
I'm trying to make install u-tags in my home folder 'cuz i do not have sudo permisssions.
I installed autoconf automake and pkg-config locally.
When I run `autogen.sh`, I get output like this:
```
##################################################################
#                The paths and versions for tools                #
##################################################################
autoreconf is /home/z00665777/.local/bin/autoreconf
------------------------------------------------------------------
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
##################################################################
aclocal is /home/z00665777/.local/bin/aclocal
------------------------------------------------------------------
aclocal (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
##################################################################
pkg-config is /home/z00665777/.local/bin/pkg-config
------------------------------------------------------------------
0.29.2
##################################################################
autoconf is /home/z00665777/.local/bin/autoconf
------------------------------------------------------------------
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
##################################################################
automake is /home/z00665777/.local/bin/automake
------------------------------------------------------------------
automake (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
##################################################################
#                        Generating files                        #
##################################################################
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:32: error: must install pkg-config 0.18 or later before running ./autogen.sh
configure.ac:32: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```
Where did I do wrong?

**Comment by leleliu008** [comment]
running `export ACLOCAL_PATH=/home/z00665777/.local/share/aclocal` will do the trick

**Comment by GreenAsFuck** [comment]
> running `export ACLOCAL_PATH=/home/z00665777/.local/share/aclocal` will do the trick

not working, still the same output

**Comment by GreenAsFuck** [comment]
> > running `export ACLOCAL_PATH=/home/z00665777/.local/share/aclocal` will do the trick
> 
> not working, still the same output

I suspect it's a problem with `pkg-config`, 'cuz after I `make install` it, I can't find a `lib` folder for `pkg-config`

**Comment by leleliu008** [comment]
what's the result of `aclocal --print-ac-dir` ? 
does `$(aclocal --print-ac-dir)/pkg.m4` exist?

**Comment by GreenAsFuck** [comment]
`/home/z00665777/.local/share/aclocal`
and yes it does exist

**Comment by leleliu008** [comment]
In theory, it shouldn't be like that.

To be honest I don't know why this happened.

I you want get more help from us, please provide us further infomation:
1. your os infomation, for instance, `cat /etc/os-release`
2. reproduce steps, details on how to install autotools and pkg-config

If you just want a ready-to-use prebuild binary, you can try https://github.com/leleliu008/test/releases/download/uctags-2022.11.17-linux-x86_64.tar.xz/uctags-2022.11.17-linux-x86_64.tar.xz

**Comment by GreenAsFuck** [comment]
OS info:
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
steps to install `autoconf`:
```
wget http://mirrors.kernel.org/gnu/autoconf/autoconf-2.69.tar.gz
tar -xzvf autoconf-2.69.tar.gz
cd autoconf-2.69
./configure --prefix=/home/z00665777/.local
make 
make install
```

install `automake` just like `autoconf` with `automake-1.16.1.tar.gz`

install `pkg-config` :
```
wget https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
tar -xzvf pkg-config-0.29.2.tar.gz
cd pkg-config-0.29.2
./configure --with-internal-glib --prefix=/home/z00665777/.local
make
make install
```

> In theory, it shouldn't be like that.
> 
> To be honest I don't know why this happened.
> 
> If you want to get more help from us, please provide us further infomation:
> 
> 1. your os infomation, for instance, `cat /etc/os-release`
> 2. reproduce steps, details on how to install autotools and pkg-config
> 
> If you just want a ready-to-use prebuild binary, I built the leaset version for you: https://github.com/leleliu008/test/releases/download/uctags-2022.11.17-linux-x86_64.tar.xz/uctags-2022.11.17-linux-x86_64.tar.xz

thanks a lot, I'll try it.

**Comment by leleliu008** [comment]
I can not reproduce this problem. my reproduce steps as following:

**step1. create a ubuntu-18.04.5 docker container**
```
podman run -it -w /root --name ubuntu-18.04.5 ubuntu:bionic-20210416 bash
```

**Note: following steps run in the ubuntu-18.04.5 docker container**

```
apt -y update
apt -y install sudo wget git make gcc m4

useradd -m -s /bin/bash z00665777
passwd z00665777
echo 'z00665777 ALL=(ALL) ALL' >> /etc/sudoers

su - z00665777
```

```
export PATH="$HOME/.local/bin:$PATH"

wget http://mirrors.kernel.org/gnu/autoconf/autoconf-2.69.tar.gz
tar vxf autoconf-2.69.tar.gz
cd autoconf-2.69
./configure --prefix=/home/z00665777/.local
make
make install

cd

wget http://mirrors.kernel.org/gnu/automake/automake-1.16.1.tar.gz
tar vxf automake-1.16.1.tar.gz
cd automake-1.16.1
./configure --prefix=/home/z00665777/.local
make
make install

cd

wget https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
tar vxf pkg-config-0.29.2.tar.gz
cd pkg-config-0.29.2
./configure --with-internal-glib --prefix=/home/z00665777/.local
make
make install

cd

git clone https://github.com/universal-ctags/ctags
cd ctags
./autogen.sh
```

**Comment by GreenAsFuck** [comment]
> I can not reproduce this problem. my reproduce steps as following:
> 
> **step1. create a ubuntu-18.04.5 docker container**
> 
> ```
> podman run -it -w /root --name ubuntu-18.04.5 ubuntu:bionic-20210416 bash
> ```
> 
> **step2: following steps run in the ubuntu-18.04.5 docker container**
> 
> ```
> apt -y update
> apt -y install sudo wget git make gcc m4
> 
> useradd -m -s /bin/bash z00665777
> passwd z00665777
> echo 'z00665777 ALL=(ALL) ALL' >> /etc/sudoers
> 
> su - z00665777
> ```
> 
> ```
> export PATH="$HOME/.local/bin:$PATH"
> 
> cd
> 
> wget http://mirrors.kernel.org/gnu/autoconf/autoconf-2.69.tar.gz
> tar vxf autoconf-2.69.tar.gz
> cd autoconf-2.69
> ./configure --prefix=/home/z00665777/.local
> make
> make install
> 
> cd
> 
> wget http://mirrors.kernel.org/gnu/automake/automake-1.16.1.tar.gz
> tar vxf automake-1.16.1.tar.gz
> cd automake-1.16.1
> ./configure --prefix=/home/z00665777/.local
> make
> make install
> 
> cd
> 
> wget https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
> tar vxf pkg-config-0.29.2.tar.gz
> cd pkg-config-0.29.2
> ./configure --with-internal-glib --prefix=/home/z00665777/.local
> make
> make install
> 
> cd
> 
> git clone https://github.com/universal-ctags/ctags
> cd ctags
> ./autogen.sh
> ```

I think the prebuild binary is good enough for me right now, and I don't want to spend too much time on this.
Thanks a lot.
I'm closing this issue.

**Comment by zengbs** [comment]
I also have the same issue as @GreenAsFuck.
