### ISSUE TITLE
C++: Output information on `constexpr` and `consteval` functions

### ISSUE THREAD

**Issue by delsner** [universal-ctags/ctags#3539]
Hi!
It seems as if `ctags` currently does not support distinctive tagging of `constexpr` and `consteval` functions (they're merely tagged as regular `function`s).
One possible workaround is to check the `pattern` field for these keywords, but having `ctags` output a (extra) field or property for them would be cleaner. (I personally would prefer adding these keywords to the `properties` field.)
Is there any preliminary or ongoing work on this already?
If not, I might take a stab (and would appreciate any advise for approaching this, as I'm not familiar with the C++ parser).
Thanks!

------------------------------------------------------------------------------------------

The name of the parser: C/C++

The command line you used to run ctags:

```
$ ctags --options=NONE --fields-all="*" --output-format=json const.cpp
```

The content of input file (from [here](https://en.cppreference.com/w/cpp/language/consteval)):

```cpp
// This function might be evaluated at compile-time, if the input
// is known at compile-time. Otherwise, it is executed at run-time.
constexpr unsigned factorial(unsigned n) {
    return n < 2 ? 1 : n * factorial(n - 1);
}

// With consteval we enforce that the function will be evaluated at compile-time.
consteval unsigned combination(unsigned m, unsigned n) {
    return factorial(n) / factorial(m) / factorial(n - m);
}
```

The tags output you are not satisfied with:

```
{"_type": "tag", "name": "combination", "path": "const.cpp", "pattern": "/^consteval unsigned combination(unsigned m, unsigned n) {$/", "language": "C++", "line": 8, "typeref": "typename:consteval unsigned", "kind": "function", "signature": "(unsigned m,unsigned n)", "roles": "def", "end": 10}
{"_type": "tag", "name": "factorial", "path": "const.cpp", "pattern": "/^constexpr unsigned factorial(unsigned n) {$/", "language": "C++", "line": 3, "typeref": "typename:unsigned", "kind": "function", "signature": "(unsigned n)", "roles": "def", "end": 5}
```

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0(7b5c7efa), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 13 2022, 17:12:58
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_fnmatch, +gnulib_regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript
```

How do you get ctags binary:

macosx binary taken from Universal-ctags/homebrew-universal-ctags project

**Comment by masatake** [comment]
Thank you for reporting. Could you write "ideal tags" output?

**Comment by delsner** [comment]
Appended the `properties` field at the end of the JSON which would be populated using that information (as a comma-separated list similar to `static`, `virtual`, `inline`, ...):
```
{"_type": "tag", "name": "combination", "path": "const.cpp", "pattern": "/^consteval unsigned combination(unsigned m, unsigned n) {$/", "language": "C++", "line": 8, "typeref": "typename:consteval unsigned", "kind": "function", "signature": "(unsigned m,unsigned n)", "roles": "def", "end": 10, "properties": "consteval"}
{"_type": "tag", "name": "factorial", "path": "const.cpp", "pattern": "/^constexpr unsigned factorial(unsigned n) {$/", "language": "C++", "line": 3, "typeref": "typename:unsigned", "kind": "function", "signature": "(unsigned n)", "roles": "def", "end": 5, "properties": "constexpr"}
```

**Comment by masatake** [comment]
@delsner I inspected the C++ parser. The original author (and maintainer) has been absent for a year. My knowledge of the parser and C++ language itself is limited. So I cannot give you enough advice.

About `constexpr`, the C++ parser already knows it as a keyword. So putting it into the "properties:" field is not hard. See #3541.

About `consteval`, the C++ parser doesn't know it. As the first step, we must register it as a keyword. After registering, we can do the same as #3541.

> If not, I might take a stab (and would appreciate any advise for approaching this, as I'm not familiar with the C++ parser).

You are welcome.

I would like you to read #3541.
https://docs.ctags.io/en/latest/testing-parser.html
See "Don’t mix whitespace ..." paragraph in https://docs.ctags.io/en/latest/contributions.html#c-language.

**Comment by delsner** [comment]
@masatake great, thanks for the clear advise and your solution for `constexpr` (that was really quick!). 
I'll let you know when I have a draft for the `consteval` extension.
