### ISSUE TITLE
Package universal ctags for as many platforms as possible

### ISSUE THREAD

**Issue by cweagans** [universal-ctags/ctags#354]
Opening this issue mainly as a placeholder, as the website is going to link to it.

To anyone coming here: we already have Homebrew packaging for Mac OS. .deb and .rpm packages would be awesome, and if there's a reliable way to install on Windows, that'd be cool too.

**Comment by ffes** [comment]
For Windows you need to buid ATM. Once we release our first version a prebuild Windows .exe will be provided (in a simple zip file with some documentation). There are not many packaging systems for Windows, but I will investigate that any time soon.

**Comment by mawww** [comment]
Getting packaged in cygwin would be nice, no idea how that works though.

**Comment by ffes** [comment]
I already maintain one cygwin package. I know how it works.

I will contact the current ctags maintainer and ask him to start using universal, or ask to hand over the package to us/me.

**Comment by cweagans** [comment]
When we get closer to a release, I'll look at building Debian packages that people can use. It's unlikely that stable Debian distros are going to switch upstreams for their ctags package.

**Comment by b4n** [comment]
FWIW, I would myself never install a third party Debian package.  If I want a software that isn't packaged, I'd rather build it myself, and possibly install it in a custom location, than use a third party package I don't trust and has the potential of messing up my whole system.

This comes both from an idea of knowing what happens to my system, and experience that it's very common that third party packages are not well tested, and sometimes break unrelated stuff.  And even if it doesn't in the Debian version it's supposed to go in, it's likely to break stuff when people upgrade their box, as this package won't get updated, and would possibly create conflicts.

So IMO, providing binary packages for Linux distros is useless (or worse).  We *could* provide the source for building them (e.g. the *debian/* subdirectory for Debian packages, or the .spec for RPMs, the whatever-is-its-name for Gentoo, etc), but I don't see much use case for binary packages.  And the worse thing is, do anyone of us really know Debian packages, Fedora packages, Gentoo packages, ArchLinux packages?  And if we don't really know what we're doing, then it'll lead to the breakages I mentioned.

**Comment by masatake** [comment]
@b4n, I agree with you as a user of Fedora.

**Comment by cweagans** [comment]
Personally, I wouldn't care about much of anything outside of Debian packages. For the time being, I don't think it's reasonable to expect distros to immediately switch to Universal Ctags from Exuberant Ctags, so we need to have some other way of installing it. I think providing a PPA for Ubuntu and Debian users would be a good idea.

**Comment by vhda** [comment]
It would still be a good idea to start by contacting the current maintainer of the Debian package and discuss this with him. He should be able to at least guide us on the right direction.

**Comment by cweagans** [comment]
:+1:

**Comment by viccuad** [comment]
Hello, 
I intend to happily package universal-ctags for Debian (although getting in contact with the exuberant-ctags maintainer is a good idea).

It would be beneficial to have releases or tags of universal-ctags so it can get packaged more easily. Is there any plans in this aspect?

**Comment by cweagans** [comment]
Another open source project that I'm involved in has been looking into using OpenSuse's Open Build System (OBS) for packaging. The idea is that you write a Specfile (which you'd have to do to package an RPM anyway), upload it, and OBS will take care of building packages for every distro it knows about. That might be a really good way to go for Universal Ctags.

**Comment by Tranquility** [comment]
Hi, I want to package universal-ctags for Gentoo. Are there any plans to tag versions? If so, which visioning scheme will it follow and which will be the first version? Are you continuing the exuberant-ctags version or start fresh?

**Comment by masatake** [comment]
@Tranquility, we don't have any plan yet.
I'll open an issue about it.

**Comment by cweagans** [comment]
Closing this in favor of the other issues for [Debian](https://github.com/universal-ctags/ctags/issues/655), [RHEL](https://github.com/universal-ctags/ctags/issues/656), [Gentoo](https://github.com/universal-ctags/ctags/issues/663), [Mac](https://github.com/universal-ctags/ctags/issues/658), and [Windows](https://github.com/universal-ctags/ctags/issues/660)

**Comment by FilBot3** [comment]
There are COPR repos for Fedora as well for this:
* https://copr.fedorainfracloud.org/coprs/jgoguen/universal-ctags/

An official one would be nice, but meh.

**Comment by westurner** [comment]
> An official [Fedora package] one would be nice, but meh.

From https://github.com/jonathanspw/headscale-rpm/issues/6 just the other day:

> A fedora Koji or COPR RPM build would rebuild with new releases; there's automation to limit time to patch.
> 
> * https://docs.fedoraproject.org/en-US/package-maintainers/New_Package_Process_for_New_Contributors/
>   * https://pagure.io/fedpkg
> * https://docs.fedoraproject.org/en-US/package-maintainers/Package_Maintenance_Guide/#_do_a_local_build_of_the_current_state
> * https://docs.fedoraproject.org/en-US/quick-docs/publish-rpm-on-copr/    
>   * https://github.com/rpm-software-management/tito

https://copr.fedorainfracloud.org/coprs/jgoguen/universal-ctags/package/universal-ctags/ 

https://copr-dist-git.fedorainfracloud.org/cgit/jgoguen/universal-ctags/universal-ctags.git/tree/universal-ctags.spec

**Comment by westurner** [comment]
Anyways, repology has README badges to display which version is the latest repackage for each distro:  https://repology.org/project/distribution/badges

**Comment by westurner** [comment]
From https://github.com/xflux-gui/fluxgui/issues/41#issuecomment-270574454 : 

> * OpenSUSE Build Service builds packages and hosts package repositories for {Fedora, RHEL, Debian, Ubuntu, Arch, OpenSUSE}
>   * Main page: https://build.opensuse.org/
>   * Wiki page: http://en.opensuse.org//openSUSE:Build_Service
>   * https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets
>   * https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto

* Src: https://github.com/openSUSE/open-build-service
* Docs: https://openbuildservice.org/help/manuals/obs-user-guide/
* Docs: https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg#sec.obsbg.uc.newprj New Project
* Docs: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration#sec.obs.obs_scm_ci_workflow_integration.setup.webhooks.how_to_set_up_a_webhook_on_github SCM/CI Workflows > Github Webhook --> OBS
* Docs: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.best-practices.scm_integration#id-1.5.9.4.4 
  ```
  osc add https://github.com/org/repo.git
  ```
* Docs: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats#id-1.5.6.2.6 Supported Build Recipes > RPM
  * [ ] `<package>.spec` file
  * [ ] `changes` file
* Docs: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats#sec.pkgfmt.flatpak Supported Build Recipes > Flatpak
  * [ ] `flatpak.yml` file
* Docs: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats#id-1.5.6.2.7 Supported Build Recipes > DEB
  * [ ] `debian.control`
  * [ ] `debian.rules`
  * [ ] `PACKAGE.dsc`

> * Fedora Copr builds packages and hosts package repositories for {Fedora / EPEL (CentOS, RHEL)}
>   * Homepage: https://copr.fedorainfracloud.org/
>   * Docs: [...]

* Fedora koji RPM build service (Mock) + pagure.io git hosting for RPM package .spec files
  * https://docs.fedoraproject.org/en-US/package-maintainers/Package_Maintenance_Guide/
  * https://docs.fedoraproject.org/en-US/package-maintainers/Using_the_Koji_Build_System/

**Comment by masatake** [comment]
In this repository we will not work on preparing packages.
Eager volunteers can prepare binary packages via their repositories as we have done in
https://github.com/universal-ctags/ctags-win32 and https://github.com/universal-ctags/ctags-nightly-build.

**Comment by leleliu008** [comment]
Starting from today, we will also build commonly used package formats e.g. `deb`,  `rpm`, `pkg.tar.xz`, `apk`, etc. 

These packages are published as GitHub Releases, you could download from https://github.com/universal-ctags/ctags-nightly-build/releases 

These packages are snapshot prebuilt binaries that are built every night, they are not regular releases.
