### ISSUE TITLE
Assertion failed: function makeJsonTag, file parsers/json.c

### ISSUE THREAD

**Issue by marlun** [universal-ctags/ctags#357]
When I run `ctags -R .` on my project I get the following output after maybe just 2 seconds:

```
Assertion failed: (token->scopeKind > TAG_NONE && token->scopeKind < TAG_COUNT), function makeJsonTag, file parsers/json.c, line 128.
Abort trap: 6
```

**Comment by b4n** [comment]
Hum, okay, I see what's happening here: if a name contains a dot (`.`) it will break things:
```JSON
{
  "first.name": "John",
  "last.name": "Doe"
}
```

I'll work on fixing this.
