### ISSUE TITLE
Perl: Incorrectly sees << inside a string as start of a heredoc

### ISSUE THREAD

**Issue by petdance** [universal-ctags/ctags#3588]
The name of the parser:

Perl

The command line you used to run ctags:

```
ctags --options=NONE -f - foo.pl
```

The content of input file:

```Perl
sub foo() {}

my $x = '<<NOT_A_HEREDOC';

sub bar() {}

sub bat() {}
```

The tags output you are not satisfied with:

```
ctags: Notice: No options will be read from files or environment
foo	foo.pl	/^sub foo() {}$/;"	s
```

The tags output you expect:

`bar` and `bat` should be output as well.  If the line with `my $x` is removed, or the `<<` is removed, then ctags puts them out.

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0(50ab7a7), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec  7 2022, 21:48:15
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +packcc, +optscript
```

How do you get ctags binary:

Built locally from master in GitHub repo.

**Comment by masatake** [comment]
Thank you. Reproduced.

**Comment by petdance** [comment]
Thanks. Let me know what I can do to help. I poked at parser/perl.c but didn't see anything obvious to do to address it. I don't know the internals at all.

**Comment by masatake** [comment]
I took much time to find ways to distinguish heredoc starters and shift operators.
@petdance, could you try the latest code?
It may work well with '<<' other than `<<` in `qw/...<< /`.

**Comment by petdance** [comment]
Seems to work fine for me.
