### ISSUE TITLE
Enabling debugging mode, if exists

### ISSUE THREAD

**Issue by psprint** [universal-ctags/ctags#3648]
I wonder if one can somehow trace the different states (`{tenter}`,`{tleave}`) that regex-mtable parser is going through? Some trace output, for example?

**Comment by masatake** [comment]
--verbose is the option for you.

I should introduce a new standalone option for the purpose. However, I cannot find enough time.

**Comment by masatake** [comment]
Does this one help you?
If --verbose helps you, I would like to close this.
