### ISSUE TITLE
Ctags or universal-ctags doesn't work on mac

### ISSUE THREAD

**Issue by MasterSergius** [universal-ctags/ctags#3649]
MacOS: 13.0.1 (22A400), Homebrew 4.0.3

**How it was installed:**
`$ brew install --HEAD universal-ctags/universal-ctags/universal-ctags`

**How it was used**
```sh
$ ctags --list-languages
/Library/Developer/CommandLineTools/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```
or 

```sh
$ ctags -R .
/Library/Developer/CommandLineTools/usr/bin/ctags: illegal option -- R
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```

The same behavior after uninstalling universal-ctags and installing ctags.
Meanwhile, on my Ubuntu machine it works perfectly.

**What steps I took to solve the problem**
I searched through similar issues within this repo, but no one solution works for me

**Comment by masatake** [comment]
See  https://stackoverflow.com/questions/50095559/ctags-error-with-mac.

**Comment by MasterSergius** [comment]
Oh, it turned out, that needed ctags is present in /usr/local/bin. Thanks, @masatake
