### ISSUE TITLE
Bug when building from source

### ISSUE THREAD

**Issue by TheBearodactyl** [universal-ctags/ctags#3650]
Enviroment:
Arch Linux

Steps to reproduce:
```
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure
```

Expected output:
Successful build

Output:
```
checking dependency style of gcc... gcc3
./configure: line 6214: syntax error near unexpected token `newline'
./configure: line 6214: `    '''
```

**Comment by masatake** [comment]
Can I reproduce this with container?
If yes, I would like to know the docker or podman command line for reproducing.
(I'm using Fedora.)

**Comment by TheBearodactyl** [comment]
I don't actually know, i don't know how to use docker or podman lol

**Comment by leleliu008** [comment]
I can't repoduce with the latest docker container.

https://github.com/leleliu008/test/actions/runs/4279113670/jobs/7449499865

Have you ever changed the /bin/sh to other shell or changed SHELL environment variable?

It says that the generated configure file have syntax error.

**Comment by TheBearodactyl** [comment]
i switched to fish a while ago

**Comment by TheBearodactyl** [comment]
> I can't repoduce with the latest docker container.
> 
> https://github.com/leleliu008/test/actions/runs/4279113670/jobs/7449499865
> 
> Have you ever changed the /bin/sh to other shell or changed SHELL environment variable?
> 
> It says that the generated configure file have syntax error.

I tried using bash instead but it still didn't work

**Comment by leleliu008** [comment]
`bash ./configure` this works?

**Comment by TheBearodactyl** [comment]
nope

**Comment by leleliu008** [comment]
Sorry, I don't known how to help you to resolve this problem. I don't think this is a bug, your envionment is broken. you can download prebuild binary from https://github.com/leleliu008/uctags-nightly-build

**Comment by TheBearodactyl** [comment]
> Sorry, I don't known how to help you to resolve this problem. I don't think this is a bug, your envionment is broken. you can download prebuild binary from https://github.com/leleliu008/uctags-nightly-build

found the problem, it wasn't my enviroment. i tried setting the prefix to a custom directory and it worked :D

**Comment by masatake** [comment]
> found the problem, it wasn't my enviroment. i tried setting the prefix to a custom directory and it worked :D

I think I can close this.
