### ISSUE TITLE
Fortran parser: adjust kind

### ISSUE THREAD

**Issue by QingmingHe** [universal-ctags/ctags#371]
The current Fortran kinds are:

``` C
static kindOption FortranKinds [] = {
    { TRUE,  'b', "block data", "block data"},
    { TRUE,  'c', "common",     "common blocks"},
    { TRUE,  'e', "entry",      "entry points"},
    { TRUE,  'f', "function",   "functions"},
    { FALSE, 'i', "interface",  "interface contents, generic names, and operators"},
    { TRUE,  'k', "component",  "type and structure components"},
    { TRUE,  'l', "label",      "labels"},
    { FALSE, 'L', "local",      "local, common block, and namelist variables"},
    { TRUE,  'm', "module",     "modules"},
    { TRUE,  'n', "namelist",   "namelists"},
    { TRUE,  'p', "program",    "programs"},
    { TRUE,  's', "subroutine", "subroutines"},
    { TRUE,  't', "type",       "derived types and structures"},
    { TRUE,  'v', "variable",   "program (global) and module variables"}
};
```

What I want it to be is:
- Unify subroutine and function to function. The subroutines and functions are subprograms in Fortran. The main difference is that function returns something and subroutine returns nothing. Subprogram is function in C and Python:

``` Fortran
subroutine suba(a)
  real a
  ! do something
end

real function funca(a)
  real a
  funca = a
end
```

is

``` C
void suba(float a) {
  /* do something */
}

float funca(float a)
{
  return a;
}
```

or

``` Python
def suba(a):
    # do something
    return None

def funca(a):
    return a
```
- Rename type to class. Fortran type has components (members in C++ and Python) and type bound procedures (method in C++ and Python). To make it consistent with C++ and Python, **class** is a better kind name than **type**.
- Distinguish between procedure as variable and type bound procedures. Procedure as variable is something like function pointer in C. However, type bound procedure is method of type (you can understand as class in other languages). Procedure as variable should be variable or local kind; type bound procedure should be **method kind** (to be added yet).

``` Fortran
type, abstract :: atype
 real a
contains
  procedure, deferred :: suba ! this is type bound procedure (method)
end type atype

procedure(some_procedure_prototype), pointer :: pp ! this is procedure as variable
```

**Comment by ffes** [comment]
It seems a bit strange to do this. Renaming them in ctags just to solve a problem with `tag->extensionFields`, sounds like a strange solution to a problem. But maybe I read your post wrong. If so, sorry.

Having said that, you are the expert on Fortran! So, if this makes sense to a Fortran developer, who am I to object.

But I am no expert on the parsers and `tag->extensionFields`, so I cannot really comment on that. Maybe @masatake or @b4n have a solution for this.

**Comment by QingmingHe** [comment]
Maybe I have expressed in a wrong way. What I want to say is that if ctags recognize type bound procedure as variable. And if in the same time this procedure is **deferred**, ctags will report that the procedure is a **deferred variable** in generated tags file, which really make no sense because variable can not be **deferred** or **implemented** later.
I've remove the last sentence of the original post. Feel sorry for that. I can implement tag.extensionFields.implementation but it may seems strange without distinguish these two kinds of procedures.

**Comment by ffes** [comment]
> @b4n may help here as he has adjusted the kinds in Geany.

In Geany they renamed many kinds of very many languages. Maybe they need it internally for Geany (to build a tree of tags, just guessing), but @b4n knows all about that.

**Comment by b4n** [comment]
> > @b4n may help here as he has adjusted the kinds in Geany.
>
> In Geany they renamed many kinds of very many languages. Maybe they need it internally for Geany (to build a tree of tags, just guessing), but @b4n knows all about that.

Yes, we only do that so we can have a consistent set of types for all languages.  But this also sometimes means we have to lose some language-specific detail because we have to map it to generic types.
BTW, we want to stop doing this at the parser level, and have our own maps of what means what.

The thing here is that CTags reports language-specific kinds, which is great in the sense it allows for any concept a language might have, and so it's possible to use the language-specific knowledge to do specific things.
But for tools wanting to have only one (or almost) logic for all languages (like Geany), one has to map whichever specific kind a language has to some generic concepts.

I don't think CTags should do that itself, or if it did (might be handy for some users, but requires good mappings), it should be optional.

**Comment by b4n** [comment]
> + Unify subroutine and function to function. The subroutines and functions are subprograms in Fortran. The main difference is that function returns something and subroutine returns nothing. Subprogram is function in C and Python:

I don't know Fortran, but if it makes sense why not.  But are those really exactly the same in all respects, but for whether they return something or not?  and then, we have to ask ourselves, may this difference be useful to know?

It might be interesting to see what people using the Fortran parser think about this (or how tools use it).

> + Rename type to class. Fortran type has components (members in C++ and Python) and type bound procedures (method in C++ and Python). To make it consistent with C++ and Python, **class** is a better kind name than **type**.

I don't think this is a good idea.  First, renaming a kind will break compatibility.  Also, as said above, there is no consistency among the different parsers' kind beyond common concepts in various languages.  I mean that if Fortran calls this a type, we probably should too.

If we really want consistency we'd need to rename a lot of things, and they might then become bizarre in some language's perspectives.

> + Distinguish between procedure as variable and type bound procedures. Procedure as variable is something like function pointer in C. However, type bound procedure is method of type (you can understand as class in other languages). Procedure as variable should be variable or local kind; type bound procedure should be **method kind** (to be added yet).

I don't know how those are currently reported, but differencing different things is good indeed.

**Comment by QingmingHe** [comment]
Thanks @b4n 
> It might be interesting to see what people using the Fortran parser think about this (or how tools use it).

Fortran is not a popular language and Fortran-ctags users are less. We may wait quite a while for response from these users. Anyway, this change is not neccessary if we dont want to make kinds of different parsers consistent.

>  I mean that if Fortran calls this a type, we probably should too.

I think i'm persuaded.

> I don't know how those are currently reported, but differencing different things is good indeed.

They are indeed different things. I'll open a PR to add the **method kind**. What about
```C
 { TRUE,  'M', "method",     "type bound procedures"},
```

**Comment by masatake** [comment]
(I'm writing "docs/criteria.rst" based on @b4n's comment.)

**Comment by QingmingHe** [comment]
I've implement the method kind in PR. #382 . Could you help to review the code @masatake

**Comment by masatake** [comment]
Before closing this, I think I should reread the discussion. There can be a case that I should update ctags man pages.

**Comment by masatake** [comment]
I read this. A person who is interested in improving an existing parser must read this.

b4n wrote:
> differencing different things is good indeed.

YES.
