### ISSUE TITLE
Duplicate output of result function name

### ISSUE THREAD

**Issue by 1925381584** [universal-ctags/ctags#3736]
ctags --extras=+q -o - HistoryLineEdit.cpp

I use this command to tag a certain file，But the output contains two versions with and without class names. Is this normal

![image](https://github.com/universal-ctags/ctags/assets/34471672/8dc2917a-bb4f-4702-8c6c-b1c92b457648)

**Comment by masatake** [comment]
Yes. If you need just one of two, use the `--extras=+q` option instead.
With the option, the output contains only "names without class".
There is no way to make the output contain only "names with class".

**Comment by 1925381584** [comment]
Thank you for your reply，but if no way to make the output contain only "names with class",  either what I receive is redundant information, or in the case of multiple classes with functions with the same name, I cannot distinguish. This is not very interesting

**Comment by masatake** [comment]
ctags doesn't provide what you want directly. However, it provides information from which you can synthesize what you want.

foo.cc:
```
class C {
  int i;
};

class D {
  int i;
};
```


output:
```
C	/tmp/foo.cc	/^class C {$/;"	class	file:
D	/tmp/foo.cc	/^class D {$/;"	class	file:
i	/tmp/foo.cc	/^  int i;$/;"	member	scope:class:C	typeref:typename:int	file:
i	/tmp/foo.cc	/^  int i;$/;"	member	scope:class:D	typeref:typename:int	file:
```

See the `scope:` field of `i`.
The field tells you whether an `i` is a member of `class C` or `class D`.

**Comment by 1925381584** [comment]
thanks a lot, you are right. this is a way to distinguish them.
