### ISSUE TITLE
Markdown: tagging a chapter unexpectedly

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#3748]
foo.md:

```
  #included
```
```
$ ~/var/ctags-github/ctags --quiet --options=NONE -o - /tmp/foo.md
#included	/tmp/foo.md	/^  #included$/;"	c
```

              This comment is nothing to do with this pull request.
`#included` at line 15 is tagged as `c`hapter. This may be a bug of the original code.

_Originally posted by @masatake in https://github.com/universal-ctags/ctags/pull/3747#discussion_r1240648900_

**Comment by jiangyinzuo** [comment]
I believe I can fix this bug. :smile:

**Comment by masatake** [comment]
Markdown test:

  # section started from spaces
