### ISSUE TITLE
Last tags are identical?

### ISSUE THREAD

**Issue by catap** [universal-ctags/ctags#3754]
At https://github.com/universal-ctags/ctags/tags I see that last tags are identical.

<img width="331" alt="Screenshot 2023-06-27 at 01 39 17" src="https://github.com/universal-ctags/ctags/assets/37775/74f10de8-0b8e-4a5d-8707-72bba7c3b62e">

**Comment by leleliu008** [comment]
Yeah. We didn't check whether a commit had already been tagged. We just check whether a tag name already exists.

@masatake

https://github.com/universal-ctags/ctags/blob/master/.github/workflows/tagging.yml#L9C34-L10

It looks like someone try to use `USER_NAME` and `USER_EMAIL` to configure git `user.name` and `user.email`, this didn't take effect. We should add following to `misc/git-tag-maybe.sh` :

```bash
git config user.name  "$USER_NAME"
git config user.email "$USER_EMAIL"
```

**Comment by leleliu008** [comment]
interesting, we have checked whether a commit has been tagged. I'm not sure why this happened. I will look into this. Thank you for your report.

**Comment by leleliu008** [comment]
@

It seems that `git describe --tags --exact-match` didn't work as expected. we can use following code to check whether HEAD has been tagged:

```bash
headCommitId="$(git rev-parse HEAD)"

for tagCommitId in $(git for-each-ref 'refs/tags/p*.0' --format='%(objectname)')
do
        if [ "$tagCommitId" = "$headCommitId" ] ; then
                note "do nothing. because $tagCommitId commit has already been tagged."
                exit 0
        fi
done
```

**Comment by k-takata** [comment]
> It seems that `git describe --tags --exact-match` didn't work as expected.

This is because `actions/checkout@v3` doesn't download the tags.

https://github.com/universal-ctags/ctags/actions/runs/5366843501/jobs/9736493025#step:2:10
> fetch-depth: 1

I think we should set `fetch-depth: 0` to download the tags.

**Comment by leleliu008** [comment]
@k-takata Thanks for your hint.

**Comment by masatake** [comment]
@k-takata, @leleliu008 I recognize again that I'm lucky that I run this project with you.
If you are not here, I cannot find any time to write C code; fixing the CI/CD settings may suck up all of my time. Thank you very much.

**Comment by leleliu008** [comment]
@masatake my pleasure.
