### ISSUE TITLE
create annotation tags instead of lightweight tag

### ISSUE THREAD

**Issue by leleliu008** [universal-ctags/ctags#3767]
in the first version of .github/workflows/tagging.yml (https://github.com/universal-ctags/ctags/commit/e9baeff49) 

```
env:
  # Account for creating a tag
  USER_NAME: "Universal-ctags CI"
  USER_EMAIL: "Universal-ctags@users.noreply.github.com"
```

It seems that you want to create annotation tags, beacuse only annotation tag can store metadata including `tagger's name`,  `tagger's email`, `tagged timestamp`, `tagged commit hash`, etc. the lightweight tag store nothing but a commit hash.

Reference: https://git-scm.com/book/en/v2/Git-Basics-Tagging

It is using commiter's name, but actually you want to use `Universal-ctags CI`, right?

There is no account named `Universal-ctags CI`, we can use the name `github-actions`, looks like following

||
|-|
|![4](https://github.com/universal-ctags/ctags/assets/3040852/c55eeb0d-3623-4ca5-b033-9e69e2f22f2b)|

# some screenshots show you what look like now

||
|-|
|![1](https://github.com/universal-ctags/ctags/assets/3040852/8e068aae-6a8a-4833-a5aa-a995dc900012)|
|![2](https://github.com/universal-ctags/ctags/assets/3040852/ef873d2e-a737-4bc0-89a2-34d5ed910d79)|
|![3](https://github.com/universal-ctags/ctags/assets/3040852/2fed9cb9-ef35-4ba5-a339-a279ad89a141)|

# 

If you think current is good enough, I think we should remove the `Universal-ctags CI` and `Universal-ctags@users.noreply.github.com` or add more comments.

**Comment by leleliu008** [comment]
```bash
- run: git config user.name  'Universal-ctags GitHub Actions'
- run: git config user.email 'Universal-ctags@users.noreply.github.com'

- run: git tag -a -m "$(git rev-parse HEAD)" p6.0.20230706.0
- run: git push origin p6.0.20230706.0
```

the `user.name ` doesn't be displayed in github webpages. but it stores in .git database.

![5](https://github.com/universal-ctags/ctags/assets/3040852/f8f3251b-16d1-45f5-8e44-af091960d2c6)

**Comment by masatake** [comment]
I re-read this.
For the snapshot (p6...), the lightweight tag is enough.
For the release (v6...), I will use an annotation tag.

What I should do are:

- [ ] remove the Universal-ctags CI and Universal-ctags@users.noreply.github.com
- [ ] update docs/releasing.rst
