### ISSUE TITLE
AIX compiling from source is failing

### ISSUE THREAD

**Issue by XSven** [universal-ctags/ctags#3807]
operating system: AIX 7.3
compiler: gcc 8.3.0
applied build instructions: [Building with configure (*nix including GNU/Linux)](https://github.com/universal-ctags/ctags/blob/master/docs/autotools.rst#building-with-configure-nix-including-gnulinux)
error when linking:

```
...
gcc -std=gnu99 -Wall   -I/opt/freeware/include/libxml2 -I/opt/freeware/include     -g -O2   -o ctags  main/ctags-cmd.o libctags.a gnulib/libgnu.a -pthread -L/opt/freeware/lib64 -lxml2    -liconv
ld: 0711-317 ERROR: Undefined symbol: ._isnan
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
...
```

solution:

```
LIBS=-lm ./configure 
```

question: any idea how this additional LIBS environment configuration can be avoided?

**Comment by leleliu008** [comment]
@XSven Thank you for your report. It seems that the contributor (https://github.com/universal-ctags/ctags/pull/3746) forgot to check whether `libm` should be linked or not. I have filed a PR (https://github.com/universal-ctags/ctags/pull/3808) to fix this.
