### ISSUE TITLE
Assertion failure in parsers/c.c

### ISSUE THREAD

**Issue by fortran-favors-the-old** [universal-ctags/ctags#386]
Hello,

I tried creating a tags file for the universal-ctags Git repository (commit 15be66e06021a4a97e4396e9df3cbd1984fb2ad3) using the following command pipeline, and I receive the following error message.

    % git ls-files | ctags --tag-relative -L '-' -f '.git/tags'
    ctags: parsers/c.c:1304: findScopeHierarchy: Assertion `(boolean) ((s->blockName)->type == (TOKEN_NAME))' failed.

Strangely enough, there's no error when I change the command as follows.

    % ctags -f '-' 'parsers/c.c'
    ACCESS_COUNT    parsers/c.c     /^      ACCESS_COUNT$/;"        e       enum:eVisibilityType    file:
    ACCESS_DEFAULT  parsers/c.c     /^      ACCESS_DEFAULT,      \/* Java-specific *\/$/;"  e       enum:eVisibilityType    file:
    ACCESS_LOCAL    parsers/c.c     /^      ACCESS_LOCAL,$/;"       e       enum:eVisibilityType    file:
    [...]

Just wanted to let you know.  Thanks for forking Exuberant Ctags and continuing development!

**Comment by masatake** [comment]
Thank you for reporting. 
Some test cases under Units can make ctags stop.
When you call ctags from command line, .ctags at the top directory may be read.
The .ctags lets ctags ignore files under Units directory.

We should fix the behaviour for the test cases. However, what you saw is just side effect of the behaviour.

Following 3 test cases can stop ctags:

-	fuzz-hitting-assertions/d-fha-0
-	fuzz-hitting-assertions/eiffel-fha-0
-	fuzz-hitting-assertions/sql-fha-0

**Comment by masatake** [comment]
BTW, what does your account name mean?
Do you know Fortran?

**Comment by fortran-favors-the-old** [comment]
I do know some Fortran, although I haven't written any in a while.  My user name is a pun on the saying "Fortune favors the bold".

**Comment by masatake** [comment]
Oh, I see. I was looking for a volunteer who knows a langauge which I don't know.

About the issue my explanation makes sense?

**Comment by masatake** [comment]
I close this.
If you still find an issue, reopen this or open another one.

Thank you for reporting.
