### ISSUE TITLE
No release since Dec. 16, 2022 ?

### ISSUE THREAD

**Issue by skywind3000** [universal-ctags/ctags#3873]
If the upstream uctags doesn't create any new release, many package system will stay the last version one year ago,
including:

- win32 release: https://github.com/universal-ctags/ctags-win32
- scoop

**Comment by k-takata** [comment]
Previous discussions: https://github.com/universal-ctags/ctags-win32/issues/38

**Comment by masatake** [comment]
I'm working hard to release 6.1.0.

**Comment by masatake** [comment]
To avoid burning myself out, I reject these requests.
Instead, I will invest my energy in this project for the long term.

**Comment by skywind3000** [comment]
I don't mind if you feel bothering to create any new releases in the near future,
or you will create tags instead of new releases.

Just make some clarification, what is your plan ?

This matters to the downstream projects.
