### ISSUE TITLE
Q: the verison numbers in ctags.rc

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#3893]
@k-takata 

I'm working on releasing v6.1.0.

I have a question about win32/ctags.rc file.

I updated only `"VALUE "FileVersion", "6.0.0.0"` when releasing v6.0.0.

Should I update 
```
VS_VERSION_INFO VERSIONINFO
 FILEVERSION 5,9,0,0
 PRODUCTVERSION 5,9,0,0
```
too?

I can't recover the mistake in v6.0.0.
So I would like to update the file correctly when releasing v6.1.0.

**Comment by k-takata** [comment]
Yes, they should be also updated.

**Comment by masatake** [comment]
Thank you.
