### ISSUE TITLE
Suggestion: add a line about Emacs in the answer to FAQ no. 7

### ISSUE THREAD

**Issue by mandarm** [universal-ctags/ctags#3924]
The detailed answer to [How should I set up tag files for a multi-level directory hierarchy?](https://docs.ctags.io/en/latest/man/ctags-faq.7.html#id12) is mostly Vim-specific.  For now, perhaps a line like the following could be added at the end of item A (The ability of your editor to use multiple tag files):

Emacs can also support multiple tags files. See [Section 29.4.3](https://www.gnu.org/software/emacs/manual/html_node/emacs/Select-Tags-Table.html) of the Emacs manual for details.

Will send a pull request if I manage to put together a more detailed Emacs-specific answer.

**Comment by masatake** [comment]
Yes, please.

**Comment by masatake** [comment]
I'm waiting for your pull request. We must revise FAQ items, not only topics about Emacs but also other items.


However, what I have to do is too obvious to me and my queue overflows already. So I will close this.
