### ISSUE TITLE
ctags-lang-i18nrubygem test fails without yaml support

### ISSUE THREAD

**Issue by nmeum** [universal-ctags/ctags#3928]
Hi, this is just a minor oversight I noticed while upgrading the Alpine Linux ctags package: the test case for the i18nrubygem parser, as defined in its man page fails with ctags-6.1.20240128.0 fails if ctags is compiled without yaml support. The test case is defined here:

https://github.com/universal-ctags/ctags/blob/d376c1350821e4a4bd46e9cc839fc0d5f3cf51b6/man/ctags-lang-i18nrubygem.7.rst.in#L27-L47

The unit tests in `./Units/parser-I18nRubyGem.r/**/features` check for this feature, but for the man page tests it does not seem to be possible to test for ctags feature. Hence, the test failure. The test failure looks as follows:

<details>
<summary>Test failure message</summary>
<pre>
# Failed test case(s)
### input
```
---
ja:
  msg:
    error: エラー
    function: 関数

```
### cmdline
```
--options=NONE -o - --fields=+E input.yaml
```
### expected tags
```
error	input.yaml	/^    error: エラー$/;"	k	keyInMiddle:ja.msg	extras:subparser
function	input.yaml	/^    function: 関数$/;"	k	keyInMiddle:ja.msg	extras:subparser
ja.msg.error	input.yaml	/^    error: エラー$/;"	k	keyInMiddle:ja.msg	extras:subparser,localeful
ja.msg.function	input.yaml	/^    function: 関数$/;"	k	keyInMiddle:ja.msg	extras:subparser,localeful
msg.error	input.yaml	/^    error: エラー$/;"	k	locale:ja	extras:subparser,localeless
msg.function	input.yaml	/^    function: 関数$/;"	k	locale:ja	extras:subparser,localeless

```
### actual tags
```

```
### diff of tag files
```
--- actual.tags	2024-01-29 17:07:00.055259201 +0000
+++ expected.tags	2024-01-29 17:07:00.055259201 +0000
@@ -0,0 +1,6 @@
+error	input.yaml	/^    error: エラー$/;"	k	keyInMiddle:ja.msg	extras:subparser
+function	input.yaml	/^    function: 関数$/;"	k	keyInMiddle:ja.msg	extras:subparser
+ja.msg.error	input.yaml	/^    error: エラー$/;"	k	keyInMiddle:ja.msg	extras:subparser,localeful
+ja.msg.function	input.yaml	/^    function: 関数$/;"	k	keyInMiddle:ja.msg	extras:subparser,localeful
+msg.error	input.yaml	/^    error: エラー$/;"	k	locale:ja	extras:subparser,localeless
+msg.function	input.yaml	/^    function: 関数$/;"	k	locale:ja	extras:subparser,localeless
</pre>
</details>

**Comment by masatake** [comment]
Thank you for tracking down the issue. I'll look into this.
