### ISSUE TITLE
Archived homebrew-universal-ctags 

### ISSUE THREAD

**Issue by KazuakiM** [universal-ctags/ctags#3967]
@masatake 
The homebrew-universal-ctags repository has been archived.
Since it is no longer possible to comment on PRs, this is a report in this repository.
Please check if there seems to be any problem.

Thanks,

https://github.com/universal-ctags/homebrew-universal-ctags/issues/68

**Comment by masatake** [comment]
@KazuakiM Thank you. As far as I know, all documents we maintain are already updated; they refer to https://formulae.brew.sh/formula/universal-ctags .

**Comment by KazuakiM** [comment]
@masatake 
Thanks for the confirmation.
This issue is closed!
