### ISSUE TITLE
Support XDG specification on Windows

### ISSUE THREAD

**Issue by kalocsaibotond** [universal-ctags/ctags#3969]
I am forced to work on windows, but I would like to build a unix-style development environment, without the overhead of WSL, or even Cygwin, MSYS2 (I want to work in PowerShell). For such a proper development environment, universal-ctags is a must.

I want to distinguish the distinguish the separate configuration of my environment via following XDG directory specifications. However, I recently found out that universal-ctags on windows does not look for option files in
- $ENV:XDG_CONFIG_HOME\\ctags\\
- $HOME\\.config\ctags\\
- $HOME\\.ctags.d\\
directories.
So I was forced to put an option file into $HOMEV\\.ctags.d\\ . This however furthers the dotfile creep in the home directory.

Why the XDG directory specification (and $HOME\\.ctags.d\\) is not supported in the peculiar case of universal-ctags? Many modern version of unix-style tools, that are cross-platform, supports XDG (and $HOME\\.ctags.d\\) on Windows as much as reasonably achievable. A good example for that is Neovim .

It should not be much difficulty to implement, right?

**Comment by masatake** [comment]
> It should not be much difficulty to implement, right?

If you think so, you can try:

https://github.com/universal-ctags/ctags/blob/d8331a9c8cc60adf4147ed9bb23bf50349fd0e0c/main/options.c#L3754

**Comment by leleliu008** [comment]
@masatake 

MS Windows users could benefit from honoring `XDG_CONFIG_HOME` environment variable as well. Although some people might thought it is not commonly used on Windows. Actually, some well-known softwares honor this environment variable, as far as I known, `git` honors this environment variable on all platforms including MS Windows. `git` introduce this feature as earlier as 2015 (https://github.com/git/git/commit/ea19289)  . 

Many users host their personal dotfiles on a GitHub repository, they just clone their repository to `XDG_CONFIG_HOME`, if software do not honor this environment variable, they should do more steps.

**Comment by masatake** [comment]
@leleliu008  Thank you for the input. I will accept if one implements the feature and updates our man pages. 
However, I myself will not work on this issue directly because I don't use Windows daily.
I don't have enough knowledge about Windows.

I can prepare more hints about the code choosing .ctags file.

**Comment by masatake** [comment]
https://github.com/universal-ctags/ctags/blob/d8331a9c8cc60adf4147ed9bb23bf50349fd0e0c/main/options.c#L3678 looks similar to https://github.com/git/git/commit/ea19289 .

**Comment by leleliu008** [comment]
Yes, I think this patch will work.

```patch
diff --git a/main/options.c b/main/options.c
index 5318d54c0..71f5c2d5f 100644
--- a/main/options.c
+++ b/main/options.c
@@ -3674,7 +3674,6 @@ static char* prependEnvvar (const char *path, const char* envvar)
 	return full_path;
 }
 
-#ifndef WIN32
 static char *getConfigForXDG (const char *path CTAGS_ATTR_UNUSED,
 							  const char* extra CTAGS_ATTR_UNUSED)
 {
@@ -3684,7 +3683,6 @@ static char *getConfigForXDG (const char *path CTAGS_ATTR_UNUSED,
 
 	return prependEnvvar (".config/ctags", "HOME");
 }
-#endif
 
 #ifdef WIN32
 static char *getConfigAtHomeOnWindows (const char *path,
@@ -3760,14 +3758,12 @@ static struct preloadPathElt preload_path_list [] = {
 		.stage = OptionLoadingStageCustom,
 	},
 #endif
-#ifndef WIN32
 	{
 		.path = NULL,
 		.isDirectory = true,
 		.makePath = getConfigForXDG,
 		.stage = OptionLoadingStageXdg,
 	},
-#endif
 	{
 		.path = ".ctags.d",
 		.isDirectory = true,

```

**Comment by masatake** [comment]
@kalocsaibotond Could you try the change proposed by @leleliu008 ?

**Comment by kalocsaibotond** [comment]
> @kalocsaibotond Could you try the change proposed by @leleliu008 ?

I cloned the repository with your commit and I compiled it with mingw-winlibs. I tried it out and it worked, ctags recognised the option file in ~\\.config\\ctags directory. (I set ~\\.config as my xdg config home).

Thank you for your effort!

When will ctags be released with this hotfix (on scoop)?

**Comment by leleliu008** [comment]
@kalocsaibotond We don't release on scoop. You can download our weekly prebuild archive for Windows  from https://github.com/universal-ctags/ctags-win32/releases/tag/
