### ISSUE TITLE
tagging pascal language does not recognize one-line-comments '//'

### ISSUE THREAD

**Issue by HoTschir** [universal-ctags/ctags#3988]
Modern pascal compilers (like Free Pascal) support inline or one line comments (see https://wiki.freepascal.org/Comments). This is not supported by ctags so far. 

When there is a key name ('function', 'procedure') within this comment, following name will wrongly be tagged (attachment _tagging_test.pas_ and _result file tagging_test.pas.tags_). Tags 'will' and 'end' are wrong.

As an attachment, there is a patch (_ctags_pascal_onelinecomment_fix.diff_) for _pascal.c_ source file, which will solve the problem. Result is seen in file _tagging_test_after_patch.pas.tags_. Neither 'will' nor 'end' is tagged after the patch.

Kindly request you to include the patch in master.

Regards.
[ctags_pascal_onelinecomment.zip](https://github.com/universal-ctags/ctags/files/15058082/ctags_pascal_onelinecomment.zip)

**Comment by masatake** [comment]
Thank you. but...why don't you make a pull request for the change?
