### ISSUE TITLE
build-sys? find the alteranative to xmlLineNumbersDefault

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#4002]
Building ctags on Fedora40, I got the following warnings.

```

../../main/selectors.c:441:9: warning: ‘xmlLineNumbersDefault’ is deprecated [-Wdeprecated-declarations]
  441 |         xmlLineNumbersDefault (1);
      |         ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libxml2/libxml/tree.h:17,
                 from /usr/include/libxml2/libxml/xpath.h:27,
                 from ../../main/lxpath.h:21,
                 from ../../main/parse.h:20,
                 from ../../main/lregex_p.h:25,
                 from ../../main/parse_p.h:17,
                 from ../../main/selectors.c:17:
/usr/include/libxml2/libxml/parser.h:967:17: note: declared here
  967 |                 xmlLineNumbersDefault   (int val);
      |                 ^~~~~~~~~~~~~~~~~~~~~

```

**Comment by leleliu008** [comment]
It is just marked as deprecated and not removed. modern libxml2 API always enables line numbers. https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-parser.html#xmlLineNumbersDefault

**Comment by leleliu008** [comment]
That means we do not need to invoke `xmlLineNumbersDefault` any more with modern libxml2 API. 

It should work fine leave it as is, at least for now.

**Comment by masatake** [comment]
https://stackoverflow.com/questions/40798571/autoconf-detect-deprecated-functions-in-glibc
https://github.com/xiph/rnnoise/blob/master/m4/attributes.m4

**Comment by masatake** [comment]
@leleliu008 I agree with you.
