### ISSUE TITLE
line directive and extra language

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#402]
During previewing 
Units/review-needed.r/line_directives.c.d/input.c
I got a coredump.

```
[yamato@x201]~/var/ctags-github% cat /tmp/input.c 
#line 2 f.f
#define x
[yamato@x201]~/var/ctags-github% ./ctags -o - --fields='+l' --line-directives /tmp/input.c 
ctags: main/parse.c:1279: isLanguageKindEnabled: Assertion `kindOpt = langKindOption (language, kind)' failed.
zsh: abort (core dumped)  ./ctags -o - --fields='+l' --line-directives /tmp/input.c
```

With `#line` directive, ctags changes the values of global variables for input file name and its language. In the above example the language is changed from c to fortran.
Though the values are changed, C parser continues parsing and making a tag.
The kind of a tag created by c parser is verified by comparing with fortran's kind table.
`x` has a kind `d`, macro definition while fortran parser doesn't know `d` .
This gap makes the assertion failure.

I was afraid that a code I introduced ago triggers this assertion. However, it does not.
The exuberant ctags doesn't have the assertion line in its source code.
 As the result it generates a bit strange  tags file.

```
[yamato@x201]~/var/ctags-github% ctags -o - --fields='+l' --line-directives /tmp/input.c 
ctags: Warning: Ignoring non-option in ./.ctags

x	/tmp/f.f	2;"	d	language:Fortran	file:
```

Though the language is Fortran, a kind `d`, which Fortran parser doesn't know, is used.

This is a blocker for moving 
Units/review-needed.r/line_directives.c.d to Units/parser-c.r/.

**Comment by QingmingHe** [comment]
Fortran macro definition is much like that in C (or even the same? Gfortran pre-process Fortran code via **--cpp** option). **d kind** should be supported by ctags but not implemented yet. It's on my schedule...

I've no idea how to implemented yet. Maybe through optlib in the first step? But the output tags is duplicate with **--regex-Fortran** options.
```
qmhe@pu:/tmp$ ~/codes/ctags/ctags -o - --fields='+l' --line-directives --regex-Fortran="/^# *define +([[:alnum:]_]+)/\1/d,definitions/" input.c 
x       f.f     /^#define x$/;" d       language:Fortran
x       f.f     /^#define x$/;" d       language:Fortran        file:
```

**Comment by masatake** [comment]
@QingmingHe, I'm sorry that I made you confused. This one is nothing to do with fortran. I mentioned fortran as an example.

I am writing an another example with an imaginary language.

**Comment by masatake** [comment]
I rewrote this report and marked the original test case with .b(known bug).

https://github.com/universal-ctags/ctags/commit/c502a7b2c7389f03e280703e9188a06bc384a2ef

**Comment by masatake** [comment]
@QingmingHe,

About the output of your trial:
The first x is emitted by your regex of Fortran.
The second one is emitted by C parser.
As I wrote the language is changed during handling #line, both parsers parse the input.

When we introduced the patch I reported c502a7b, just C parser runs because the input file name is input.c.

**Comment by cweagans** [comment]
Sorry for the noise. Just switching the "Release blocker" tag for the "Initial release" milestone so that everything is tracked in one place.

**Comment by masatake** [comment]
ctags should not change the language when a `#line` is found.
In stead of changing the language, capture the file name in `#line` directive as a reference tag.
Its role may be origin or originalFile.
This is not difficult. I can do it after introducing reference  tag and role.

BTW, adding C preprocessor handler to fortan is quite easy.

**Comment by masatake** [comment]
I have found reference tag solves a part of this issue.
Much more work is needed than I expected.
