### ISSUE TITLE
Error using readtags -C on Windows (--canonicalize-input)

### ISSUE THREAD

**Issue by terminatorul** [universal-ctags/ctags#4030]
Universal Ctags 6.1.0 (p6.1 2024-03-03 .0)

```cmd
Echo !_TAG_PROC_CWD  C:/Users/adria_f5m2wqf/Projects/Leroy/  //;^"    extras:pseudo>pseudo_tag.tags
readtags -t pseudo_tag.tags --sorter "(<> $name &name)" -C -l
```

Resulting output:
```
readtags: no !_TAG_PROC_CWD in pseudo_tag.tags
```

```cmd
Echo %ErrorLevel%
1
```

**Comment by terminatorul** [comment]
Sorry, this is actually documented alredy !

Maybe it can be fixed... ?

**Comment by masatake** [comment]
What kind of character did you use between `!_TAG_PROC_CWD` and `C:/Users/adria_f5m2wqf/Projects/Leroy/  //;^`?
What kind of character did you use between `C:/Users/adria_f5m2wqf/Projects/Leroy/  //;^` and `extras:pseudo`?
    
As explained in [tags(5)](https://docs.ctags.io/en/latest/man/tags.5.html), The separators must be tab characters.
