### ISSUE TITLE
Fortran: How to include "$" in variable and function names

### ISSUE THREAD

**Issue by navinp0304** [universal-ctags/ctags#4033]
I want to index some fortran files from old code base . 
The syntax is f77. In the old code base the identifiers are having $ for variable names and functions. 

1. How include "$" in the indentifier ? 
2. Is there a way without modifying source code ? What would be the command.

**Comment by masatake** [comment]
> How include "$" in the identifier ?

With patching this source of ctags:

```
diff --git a/parsers/fortran.c b/parsers/fortran.c
index 1c1175b3f..0f5b582dc 100644
--- a/parsers/fortran.c
+++ b/parsers/fortran.c
@@ -31,7 +31,7 @@
 /*
 *   MACROS
 */
-#define isident(c)              (isalnum(c) || (c) == '_')
+#define isident(c)              (isalnum(c) || (c) == '_' || (c) == '$')
 #define isBlank(c)              (bool) (c == ' ' || c == '\t')
 #define isType(token,t)         (bool) ((token)->type == (t))
 #define isKeyword(token,k)      (bool) ((token)->keyword == (k))
```

> 2. Is there a way without modifying source code ? What would be the command.

There is no way without modifying the source code.

**Comment by masatake** [comment]
If you provide a simple f77 input using `$`, I can extend ctags to support `$` by default. Please let me know if you are interested.

**Comment by navinp0304** [comment]
```
$ cat tmp.f
        function name$()
                integer name$
                name$ = 42
        end function

        function main()
                integer ret$
                ret$=name$()
                print *,ret$
        end function
$ ./a.out 
          42
$ 
```
Yes that works for me.
How do you list the regex supported by function in fortran or C for ctags? Is it possible to print it and how do i extend it ?

**Comment by masatake** [comment]
Based on your input, I made a pull request #4034.

> How do you list the regex supported by function in fortran or C for ctags? Is it possible to print it and how do i extend it ?

They don't use regular expressions at all. So you cannot list.

**Comment by navinp0304** [comment]
Then how do you construct a tag for function in C

**Comment by masatake** [comment]
> Then how do you construct a tag for function in C

Consider the following input as an example:
```
void foo(void) { ... }
```

1. read the input file till finding `{`.
2. if you find `{`, read backward till finding `(`.
3. if you find `(`, read characters satisfying the following condition:  'a' <= character and character <= 'Z' and record the characters to a stack.
4. pick the characters from the stack as a string.
5. write the string as a tag to `tags` file.

If you want to know the details, see files in https://github.com/universal-ctags/ctags/tree/master/parsers/cxx .
