### ISSUE TITLE
Allow comments in .ctags files

### ISSUE THREAD

**Issue by jfelchner** [universal-ctags/ctags#407]
There are a lot of things that an individual developer can do so as not to wait for certain parsing to be added to the official release, but those bits get extremely complicated very quickly unless we can have comments in our `.ctags` files.

I'd recommend the bash standard of `#`.  If it exists at the beginning of the line (or is preceded only by spaces) , or the line is completely blank, that line of the `.ctags` file is ignored by the parser.

As a bonus, it'd be great if we could indent our options an arbitrary number of spaces to help use indention as a visual guide.  I can certainly live without this though.  All I really care about is the comment marker and blank lines.

Thanks for the consideration!

**Comment by ffes** [comment]
I am AFK at the moment so can't test right now, but this is already in universal ctags as far as I know

**Comment by jfelchner** [comment]
@ffes I installed `brew install ctags` on my Mac and have version 5.8.  This may be incorrect.  I did a `brew search ctags` and didn't see a listing for `universal-ctags` anywhere.

I assumed that this was correct because #354 says that there's a Homebrew package.

Maybe I'm just very confused :grinning:

**Comment by ffes** [comment]
Look at the .ctags file in our repo to see the comment in action.

**Comment by jfelchner** [comment]
@ffes sweet.  This is perfect!!  Now if I could just get it on my system :)

**Comment by ffes** [comment]
I don't have a Mac, so I know very little about OSX. But we have a homebrew repo in our organization. I'm sure @cweagans can help you with that. He is the one who contributed that repo.

Universal Ctags is the continuation of Exuberant Ctags. Everything that works in Exuberant should work the same or better in Universal. See the docs directory in this repo for more information, especially the news.rst to see the most important changes.

**Comment by jfelchner** [comment]
@ffes ok awesome.  You guys are incredible.  @cweagans I found the homebrew tap and it looks like it's good to go!  You all rock!

**Comment by jfelchner** [comment]
BTW, any idea when you all are going to get a tagged release for this package?  It'd be great to get this into homebrew proper.

**Comment by ffes** [comment]
We should work to get a feature freeze and an official release any time soon. But we still have to discuss those details.
