### ISSUE TITLE
"ctags: Failure on attempt to read file : Is a directory"

### ISSUE THREAD

**Issue by user202729** [universal-ctags/ctags#4081]
To reproduce:

```
mkdir tags
ctags -R
```

Then ctags will raise a misleading error message:

```
ctags: Failure on attempt to read file : Is a directory
```

Maybe check the condition and change the error message to "the target tags file already exists as a directory, try passing `-o [tags file name]`?"

(in practice, this happens in e.g. [`texstudio` repository](https://github.com/texstudio-org/texstudio) where there's a top-level folder named `tags`)

Version: `Universal Ctags 6.1.0(v6.1.0), Copyright (C) 2015-2023 Universal Ctags Team`

**Comment by masatake** [comment]
Thank you for the suggestion.
I arranged the message as follows:
```
$ ./ctags main/main.c
ctags: "tags" already exists as a directory; I cannot write tag entries there.
Remove the directory or specify a file name with -o <tagfile> option.
```

Is this o.k.?
