### ISSUE TITLE
Allow indentation of options in .ctags files

### ISSUE THREAD

**Issue by jfelchner** [universal-ctags/ctags#409]
This is a continuation of #407 

It'd be nice to be able to add indentation to `.ctags` files for better organization.  Currently if an option is indented, it causes a `ctags: Warning: Ignoring non-option in ./.ctags` warning.

**Comment by masatake** [comment]
Thank you for good idea.

Those who have interests  in implementing this feature, I try to give hints:

1. add 'trimHeaderWhitespace' or something boolean parameter to nextFileLine function in args.c:
    if trimHeaderWhitespace is true, call vStringStripLeading before strcpy:
```
	strcpy (result, vStringValue (vs));
```

2 From nextFileLineSkippingComments, pass TRUE as the second argument when calling nextFileLine.

3. Write Tmain test case.

4. Send a PR. Don't forget "Close #409" to you comment.

Not so difficult.  Any volunteer? We are looking for not only a person who can review parser code but also who has interests core part of ctags.

**Comment by jfelchner** [comment]
@masatake amazing!  Thank you!
