### ISSUE TITLE
Sort call faliure

### ISSUE THREAD

**Issue by kalocsaibotond** [universal-ctags/ctags#4094]
# Universal Ctags sort call faliure
I ran universal ctags on my python project, on Windows 10, Powershell 7.4.5, and I get the following result
```
Input file specified two times.

ctags.exe: cannot sort tag file: system ("sort -u -o tags tags") exited with 1
```
Neverheless, I think I found the issue:
```
PS> Get-Command sort.exe
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     sort.exe                                           10.0.1904… C:\Windows\system32\sort.exe

```
I tried `sort.exe` out separately with `sort.exe -u -o tags tags` and it yields `Input file specified two times.`
This is despite the fact I created a scoop shim for the GNU coreutil sort that lies in the Git for Windows mini unix environment.

It would be nice solution to have a way to override the sort command for windows either through environment variable or through a command line option.

*****

## The name of the parser:
ctags's default (python) parser.

## The command line you used to run ctags:
```
PS> ctags --options=NONE -R
```
though the same occurs with
```
PS> ctags --options=NONE .
```
.

## The content of input file:
Python project files.

## The tags output you are not satisfied with:
The generated tags seems fine, I tried them with Neovim client.

## The tags output you expect:
I get what I expect, though it is unsorted.

## The version of ctags:
```
PS> ctags --version
Universal Ctags 6.1.0, Copyright (C) 2015-2023 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug  6 2024, 16:07:53
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +win32, +wildcards, +regex, +gnulib_regex, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript, +pcre2
```

## How do you get ctags binary:
```
PS> scoop install extras/universal-ctags
```

**Comment by leleliu008** [comment]
It seems that you built it from source not install via scoop, becasue your `Compiled: Aug  6 2024, 16:07:53`  2 month ago,  scoop just down binary from our release as per https://github.com/ScoopInstaller/Extras/blob/master/bucket/universal-ctags.json , our releases for windows disable the external sort https://github.com/universal-ctags/ctags-win32/blob/master/.github/workflows/build-ctags.yaml#L162

**Comment by kalocsaibotond** [comment]
> It seems that you built it from source not install via scoop, becasue your `Compiled: Aug 6 2024, 16:07:53` 2 month ago, scoop just down binary from our release as per https://github.com/ScoopInstaller/Extras/blob/master/bucket/universal-ctags.json , our releases for windows disable the external sort https://github.com/universal-ctags/ctags-win32/blob/master/.github/workflows/build-ctags.yaml#L162

Thank you for your quick response. I think I found the source of interferene:
```
PS> Get-Command ctags
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ctags.exe                                          6.1.0.0    C:\Users\botond.kalocsai\scoop\apps\mingw-winlibs\current\bin\ctags.exe

```
Unfortunately, the mingw-winlibs scoop package also contains a version of universal-ctags that behaves differently, which overrides the proper universal-ctag's shim. Uninstalling mingw-winlibs gives back the access to the proper universal-ctags shim.

**Comment by masatake** [comment]
I don't want to add flexibility to the area.
I took much time to work on https://git.almalinux.org/rpms/ctags/commit/3c370ff3576fbbad5e6e5245942a6f306c773d71.patch .

I don't know the package manager(s?) on Windows.
However, if the "sort" command is unavailable, using --disable-external-sort looks like a simple solution.

**Comment by deplinenoise** [comment]
I ran into this last night, after downloading the nightly x64 windows build.

Steps to reproduce:
1. `mkdir foo`
2. `cd foo`
3. `ctags -R`

Result:
```
P:\dummy>ctags -R
Input file specified two times.

ctags: cannot sort tag file : No error

```

So it seems the behavior out of the box on the official windows binary is to not work.
