### ISSUE TITLE
Unwanted files accidentally committed

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#4098]
It seems that as part of https://github.com/universal-ctags/ctags/commit/693042ec5deed3b0f846c13be7299d022bb3b4eb some files got committed by accident. Namely:
- #vim.c#
- v.c.orig
- possibly cython.c, desktopentry.c

**Comment by techee** [comment]
https://github.com/universal-ctags/ctags/pull/4107 removed `#vim.c#` and `v.c.orig` but  to me it still seems that also `cython.c` and `desktopentry.c` were added by accident in https://github.com/universal-ctags/ctags/commit/693042ec5deed3b0f846c13be7299d022bb3b4eb as these are not contained in any makefile.

(Not 100% sure so not submitting any fix.)

**Comment by masatake** [comment]
You are correct. I will remove them.

**Comment by k-takata** [comment]
It seems that `parsers/args.ctags` was also committed accidentally.
