### ISSUE TITLE
Should ignore .ctags files by default

### ISSUE THREAD

**Issue by jfelchner** [universal-ctags/ctags#410]
Currently if you try to run ctags in a directory that has a `.ctags` file and you have languages set to `all`, it tries to parse the `.ctags` file.  I'm assuming it probably shouldn't do this.

**Comment by masatake** [comment]
universal ctags has ability to do parse .ctags file.
Do you have a strong reason to exclude .ctags?
In stead of just excluding .ctags we can disable the .ctags parser in data/optlib/ctags.ctags.

**Comment by jfelchner** [comment]
@masatake I guess my question is, what is the use case of parsing the `.ctags` file?  If there is one then that's fine, I just couldn't think of one myself.

Thanks for the feedback! :)

**Comment by masatake** [comment]
About our source code tree, it is just for testing .ctags regex based parser.
Generally it is for tagging --langdef.
