### ISSUE TITLE
meson: use benchmark() instead of bench_mark()

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#4100]
The optlib meson parser seems to look for `bench_mark`

https://github.com/universal-ctags/ctags/blob/ecf0c4adcce9853d666590bf2be101f983bad1cf/optlib/meson.ctags#L69

but I only found the `benchmark()` function in the documentation:

https://mesonbuild.com/Reference-manual_functions.html#benchmark

**Comment by masatake** [comment]
Thank you for reporting.
