### ISSUE TITLE
Lisp: Common Lisp OOP/type parsing

### ISSUE THREAD

**Issue by aartaka** [universal-ctags/ctags#4120]
The name of the parser: lisp

The command line you used to run ctags:

```
$ ctags --options=NONE source/*.lisp source/mode/*.lisp libraries/*/*.lisp
```

In the root dir of [Nyxt browser](https://github.com/atlas-engineer/nyxt)

The tags output you are not satisfied with:

```
cursor	libraries/text-buffer/text-buffer.lisp	/^(defclass cursor (cluffer-simple-line::right-sticky-cursor)$/;"	Y
customize-instance	source/user-classes.lisp	/^(defgeneric customize-instance (object &key &allow-other-keys)$/;"	Y
renderer-history-entry	source/renderer/gtk.lisp	/^(defstruct renderer-history-entry$/;"	Y
render-functions	source/mode/macro-edit.lisp	/^(defmethod render-functions ((macro-editor macro-edit-mode))$/;"	Y
prompter:object-attributes	source/mode/hint.lisp	/^(defmethod prompter:object-attributes :around ((element plump:element) (source hint-source))$/;"	Y
```

All of these marked as unknown. More semantic markers won't hurt. Something like `t`/`c`/`s` (type/class/struct) and `m` (method)? I personally prefer `t`/`type` as that's the term Common Lisp docs use for classes and types (not structs, confusingly, but structs are types too!)

```
cursor	libraries/text-buffer/text-buffer.lisp	/^(defclass cursor (cluffer-simple-line::right-sticky-cursor)$/;"	t (or c=class?)
customize-instance	source/user-classes.lisp	/^(defgeneric customize-instance (object &key &allow-other-keys)$/;"	f
renderer-history-entry	source/renderer/gtk.lisp	/^(defstruct renderer-history-entry$/;"	t (or s=struct?)
rememberable-mode-invocation	source/auto-rules.lisp	/^(deftype rememberable-mode-invocation ()$/;"	t
render-functions	source/mode/macro-edit.lisp	/^(defmethod render-functions ((macro-editor macro-edit-mode))$/;"	m
prompter:object-attributes	source/mode/hint.lisp	/^(defmethod prompter:object-attributes :around ((element plump:element) (source hint-source))$/;"	m
```

See [defmethod](https://www.lispworks.com/documentation/HyperSpec/Body/m_defmet.htm), [defgeneric](https://www.lispworks.com/documentation/HyperSpec/Body/m_defgen.htm), [defclass](https://www.lispworks.com/documentation/HyperSpec/Body/m_defcla.htm), [deftype](https://www.lispworks.com/documentation/HyperSpec/Body/m_deftp.htm), and [defstruct](https://www.lispworks.com/documentation/HyperSpec/Body/m_defstr.htm) (notice that the name can be a parenthesized list `(name options ...)`!) for exact parsing BNF.

-----------------------------------------------------

The version of ctags:

```
$ ctags --version
Universal Ctags 6.1.0(p6.1.20241117.0), Copyright (C) 2015-2023 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 18 2024, 17:31:59
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript, +pcre2
```

How do you get ctags binary: via pacman on Arch Linux

**Comment by masatake** [comment]
What do you, lisp hackers, call "something" in defsomething ?

type? kind? category? ...

**Comment by aartaka** [comment]
It's too varied to be nameable—one can define anything. But type is as close as it gets, I guess. It's still confusing, though: data types are also a thing in Lisps.

Why? Do you mean this idea from #4119 with `kind:` etc? I'm not familiar enough with ctags to understand why you need any prefix. Doesn't `f`/`t`/`Y` etc. cut it?

**Comment by aartaka** [comment]
Oh, and a follow-up: you can also add `define-class` for class/type definition—it's a widespread convention present in e.g. Schemes and Common Lisp macro libraries.

And `define-record-type` too for Scheme structs  (is there a need in Scheme-specific parser? Maybe Clojure too? I'm eager to specify it, but I'm not sure I can implement it.)

**Comment by aartaka** [comment]
Oh wait, there already are parsers for Scheme and Clojure, sorry! Should I open separate issues for these?

**Comment by masatake** [comment]
See #4121.
The test cases in #4121 explain what I have done.
https://docs.ctags.io/en/latest/testing-parser.html#id1 explains our test harness.

**Comment by masatake** [comment]
See #519 and #988. You can open issues for the other languages of the Lisp family. However, I will not work on it until there is a Sexp-based meta parser.

**Comment by aartaka** [comment]
Thanks!
