### ISSUE TITLE
$HOME/.ctags file is read but not used

### ISSUE THREAD

**Issue by rdindir** [universal-ctags/ctags#4128]
I am using ctags. I have created a .ctags file in the home directory with this content

--recurse=yes
--exclude=\*/.git/\*
--exclude=\*/node_modules/\*
--exclude=\*/build/\*

When I run ctags with the verbose flag like this **ctags --verbose=yes ./src/** I get this output

____adding (null) pattern: *.class
____adding (null) pattern: *.pyc
____adding (null) pattern: *.pyo
Entering configuration stage: loading file(s) under $XDG_CONFIG_HOME and $HOME/.config
Entering configuration stage: loading file(s) under $HOME
Entering configuration stage: loading file(s) under the current directory
Reading initial options from command line
Entering configuration stage: loading command line
Reading command line arguments
ignoring "./src/" (directory)
sorting tag file
system ("sort -u -o 'tags' 'tags'")

It seems that the --recurse setting in the $HOME/.ctags file is not used

Regards

**Comment by rdindir** [comment]
I tried moving **$HOME/.ctags** to **$HOME/.config/ctags/.ctags**. This did not work.

But what worked is moving **$HOME/.ctags** to **$HOME/.config/ctags/default.ctags**.

Does universal ctags not recognize **$HOME/.config/ctags/.ctags** as a configuration file?

**Comment by masatake** [comment]
See https://docs.ctags.io/en/latest/man/ctags.1.html#preloading-option-files .
Universal Ctags doesn't read $HOME/.ctags.
It is a bug if you observe that Universal Ctags $HOME/.ctags. Please open an issue regarding the behavior.

> Universal ctags does not recognize $HOME/.config/ctags/.ctags as a configuration file. Is that correct?

Yes, it is correct.

**Comment by masatake** [comment]
I answered the question.
