### ISSUE TITLE
javascript: ignoring null tag warnings for jquery 3.6.0

### ISSUE THREAD

**Issue by techee** [universal-ctags/ctags#4134]
When running ctags on https://code.jquery.com/jquery-3.6.0.js, I get the following warnings:
```
ctags: Notice: ignoring null tag in /home/parallels/projects/geany/doc/reference/jquery.js(line: 9299, language: JavaScript)
ctags: Notice: ignoring null tag in /home/parallels/projects/geany/doc/reference/jquery.js(line: 9874, language: JavaScript)
ctags: Notice: ignoring null tag in /home/parallels/projects/geany/doc/reference/jquery.js(line: 10650, language: JavaScript)
```

The code around these lines looks like

<img width="665" alt="Screenshot 2024-11-27 at 11 40 22" src="https://github.com/user-attachments/assets/efb98da4-7ff0-46bc-8a32-75dff5a1bdb5">

<img width="786" alt="Screenshot 2024-11-27 at 11 41 53" src="https://github.com/user-attachments/assets/cbb67ede-afcf-4076-82e5-4831c45a011b">

I haven't investigated more.

**Comment by masatake** [comment]
Solved via merging #4153 and #4152.
