### ISSUE TITLE
Powershell: (bug) herestr breaks ctags functions list.

### ISSUE THREAD

**Issue by ivanmara555** [universal-ctags/ctags#4141]
Hello. I'm using geany editor which uses ctags as index generator of languages objects.

I wrote some powershell code in geany 2.0:
```powershell
function a
{
    $i = 1
    Write-Host $i
}
function b
{
    Write-Host b
}
a
b
pause
```
using ctags to show functions list and see two functions: 
```bash
ivan@hp /mnt/sdb/data/temp $ ctags -x --c-types=f test_ps1_for_bugreport1.ps1 
a                function      1 test_ps1_for_bugreport1.ps1 function a
b                function      6 test_ps1_for_bugreport1.ps1 function b

```
And on left side bar of geany editor see two function:
![1](https://github.com/user-attachments/assets/550b1f36-63c3-45ed-87cc-44d2ca094918)

Suddenly i add some heredoc to function a:
```powershell
function a
{
    $i = 1
    $heredoc =
@"
""" $i
"@
    Write-Host $heredoc
}
function b
{
    Write-Host b
}
a
b
pause
```
using ctags now show only one function a !!!:
```bash
ivan@hp /mnt/sdb/data/temp $ ctags -x --c-types=f test_ps1_for_bugreport2.ps1 
a                function      1 test_ps1_for_bugreport2.ps1 function a
```

and on left side bar in geany only one function a: 
![2](https://github.com/user-attachments/assets/06992f90-54ce-4a72-9c2c-757efe0c4683)

Adding heredoc code breaks ctags function list !!!

I cat use single quote delimiter `@'` and function list will show correctly. But some times i need use double quoted `@"` to use a subexpression as in example above.

some detail here: [The PowerShell Here-String – Preserve text formatting](https://4sysops.com/archives/the-powershell-here-string-preserve-text-formatting/)

original geany bugreport was in https://github.com/geany/geany/issues/4089

**Comment by masatake** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.4#here-strings

**Comment by masatake** [comment]
See #4145.
