### ISSUE TITLE
lua table prefix missing

### ISSUE THREAD

**Issue by Rose1917** [universal-ctags/ctags#4142]
*****

The name of the parser: default lua parser

The command line you used to run ctags:

```
$ ctags -R ./
```

The content of input file:

```lua
function c2s.foo()
    --- foo function entry
end


```

The tags output you are not satisfied with:

```
foo	bin/lobby/foo.lua	/^function c2s.foo()$/;"	f	unknown:c2s
```

The tags output you expect:

```
!_THIS_IS_AN_EXAMPLE
c2s.foo	bin/lobby/foo.lua	/^function c2s.foo()$/;"	f

```

The version of ctags:

```
$ ctags --version
Universal Ctags 6.1.0(270e9bd5f), Copyright (C) 2015-2023 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec  2 2024, 09:31:49
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +packcc, +optscript
```

How do you get ctags binary:

(
Building it locally.
)

**Comment by masatake** [comment]
Could you try `--extras=+q` option?

**Comment by Rose1917** [comment]
> Could you try `--extras=+q` option?

the c2s.foo show up. But the foo still exists

**Comment by Rose1917** [comment]
![image](https://github.com/user-attachments/assets/70df1b28-54a9-4f23-9634-250739a45ebd)

**Comment by Rose1917** [comment]
BTW, how to remove the "unknown"?

**Comment by Rose1917** [comment]
![image](https://github.com/user-attachments/assets/cd7607f4-dd0f-4ade-965a-531b9180539f)

**Comment by masatake** [comment]
Removing `foo` is hard. There is no way.

**Comment by masatake** [comment]
> Use --fields=+s option.

Sorry, this should be `--fields=-s`.
