### ISSUE TITLE
Reporting the current input file name when assertion failure

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#420]
I'm looking for a neat way to print the current input file name when an assertion is made failure.
If you have a good idea or code, please, let me know.

**Comment by vhda** [comment]
Could you please expand on the requirements?
Include an example of the current output and what would be desired.

**Comment by b4n** [comment]
Proposed solution at #427

**Comment by masatake** [comment]
YES! this is what I wanted.

When running a ctags with -R and ctags is aborted because an assertion, I would like to debug.
However, I cannot know which file triggers it. Just I could know the line and file of ctags source code.
Now we can know the name of input file! So we can enjoy more debugging.

We need this now. Could you merge this?

**Comment by b4n** [comment]
> When running a ctags with -R and ctags is aborted because an assertion, I would like to debug.
However, I cannot know which file triggers it. 

You could always run under gdb all the time, the overhead is not very large for normal operation :)
But I'd be nice to get details.

> Could you merge this?

Sure.  Did someone give it a quick look at least? :)

**Comment by masatake** [comment]
Generally I run ctags via variety of shell scripts. So I don't want to setup gdb. 
In addition, a user will not run ctags under gdb; and we will get a bug report from such user.
So your patch is quite important.

I will test tomorrow.

**Comment by masatake** [comment]
I tried and It worked fine.
