### ISSUE TITLE
javascript: parsing two variables separated by a commag

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#422]
```javascript
var x,y;
```

For above input, ctags tags only x.
y is ignored.
This one is registered as Units/js-two-vars.b.

**Comment by masatake** [comment]
How about this one: Units/parser-javascript.r/js-tricky-newlines.b/input.js ?
```
var a = 1
,   b = 1
,   c = 1

let d
,   e
,   f
```

Semicolons are missed but js command accepts the input.
In current ctags code, ctags doesn't record c and f.

**Comment by b4n** [comment]
@masatake I know, hence why I created the test case :)
Though, it's a bit unrelated, the cause of the issue is handling of implicit newlines, not variables itself.  I've a working solution almost ready, I'll polish it and PR it up soon.

**Comment by masatake** [comment]
Oh, I'm sorry. I misunderstood I added the test case. Feel free to close this issue or reuse this one.

**Comment by b4n** [comment]
No problem.  Opened #447 which fixes the test case.
