### ISSUE TITLE
use an external command as a parser

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#43]
Like --regex-<LANG>= option introduce --cmd-<LANG>= option.

Some people wrote their own tag generator for a language they are interested in. 
e.g. https://github.com/lukaszkorecki/CoffeeTags
Good news is that the format of tags file generated by those generators is compatible with format defined at Exuberant Ctags project.

fishman ctags can be onestop unified front end for those generators.
If we use pipe to communicate with external generators, readtags is good place to start.

**Comment by uri** [comment]
@masatake is this still relevant? I'm trying to get this working with coffee tags. I have 

```
--langdef=coffee
--langmap=coffee:.coffee
--coffee-xcmd='coffeetags -R'
--fields='*' --file-scope=yes --extra=+fq '--*-kinds=*
```

In `coffee.ctags` but I'm getting the error 

```
ctags: Unknown option: --coffee-xcmd
```

**Comment by uri** [comment]
Ah, I see it was remove in #1442 😭
