### ISSUE TITLE
Wish: Renaming the executable?

### ISSUE THREAD

**Issue by egarrulo** [universal-ctags/ctags#431]
Would it be possible to change the name of the executable from `ctags` to something else -- like `utags` -- to distinguish Universal Ctags from the original Exuberant Ctags?  There is also a `ctags` program that comes with GNU Emacs that adds to the confusion.

Thanks for your attention.

**Comment by masatake** [comment]
See https://github.com/universal-ctags/ctags/blob/master/docs/building.rst .
