### ISSUE TITLE
How strong us JS support 

### ISSUE THREAD

**Issue by mtangoo** [universal-ctags/ctags#434]
Last time I checked exuberant ctags it had not so great support for Javascript. 
Does this version improve that?

**Comment by masatake** [comment]
Yes, it is improved.

Fixed bugs in our version can be found as test cases at 
https://github.com/universal-ctags/ctags/tree/master/Units/parser-javascript.r

**Comment by mtangoo** [comment]
So it can parse JQuery and Other JS libraries just fine or there are glitches?
I will take a look at it right now!

**Comment by b4n** [comment]
There most likely will be glitches.  Actually, parsing languages as dynamic as JavaScript is virtually impossible without a real complete implementation of the language (e.g. a full interpreter/VM), as many things can change dynamically.  And most "modern" JS libraries heavily rely on this, for example to avoid leaking symbols they often are implemented as a single statement, like `var mylib = (function(){ /* code here */ })()`. At the syntax level, this is only one `mylib` variable, and there is no way to actually know what its value is without actually running the initialization statement (which can contain any code, that's the point) and analyzing the actual resulting object.  Or even worse, think [`jQuery.fn.extend()`](https://api.jquery.com/jquery.fn.extend/): there isn't any way to understand this either (but maybe very specific understanding of these very specific constructs), and worse, it doesn't return anything but modifies an existing object.
If somebody wants truly accurate JavaScript tags, they'll need to use a real interpreter and inspect the resulting stack -- but beware, it can be totally different from one statement to the other.

This said, we now do a pretty decent job most of the time -- and would be happy to try and fix specific issues.

BTW, I have some improvements on the way (ECMA6 template strings and slightly improved support for implicit semicolons in some uncommon cases), will PR on of these days.

**Comment by mtangoo** [comment]
Thanks for in depth explanations. They clear a lot of issues.
But my question was on variables to use in IDE code browser so value isn't my concern at all.
I would like to just be able to parse functions/Variables and know their line number as well as intellisense.

so I only need symbol kind (class, var, func) and its line number. Then for classes, I want to know methods (so that when someone clicks $. I can autocomplete class functions and properties)
Does it work on that?

**Comment by b4n** [comment]
@mtangoo well, it won't probably be perfect in every cases, but yes, it should work fairly well -- and we fix new issues frequently.

Geany uses this parser to provide symbol tree, symbol completion, calltips and "go to symbol" feature.

**Comment by mtangoo** [comment]
great, thanks guys!
