### ISSUE TITLE
Ruby: `class << self` not recognized as block that defines class-level methods

### ISSUE THREAD

**Issue by mislav** [universal-ctags/ctags#455]
This method definition:

```rb
class C
  class << self
    def foo() end
  end
end
```

is not recognized as class-level method definition (`F` kind). Instead, it gets parsed as instance method (`f` kind).

```
$ ctags --version
Universal Ctags Development, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 21 2015, 12:41:18
  Addresses: <dhiebert@users.sourceforge.net>, https://github.com/universal-ctags/ctags
  Optional compiled features: +wildcards, +regex, +debug, +option-directory, +coproc
```

**Comment by masatake** [comment]
(I will convert this to a unit test case. If someone already started to do, let me know here.)

**Comment by masatake** [comment]
@mislav, could you look at #456?

**Comment by b4n** [comment]
@masatake I'm on it, I have a fix for this

**Comment by masatake** [comment]
@b4n, thank you. Please, use the test case I converted from this issue.
