### ISSUE TITLE
Share parsers code with geany

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#459]
Very hot summer in Japan. These days I have studied this issue.

These day we got not a few PR and issues.  Before introducing big changes, especially about coding style, I think we have to solve this. (This should be solved as the first issue when the project  was started but my knowledge was too few.)

Could you look at  https://github.com/universal-ctags/ctags/blob/docs-for-sharing-parsers/docs/how-to-share-parsers.rst ? 

Feel free to fix the rst file.

We would like to agree the approach for sharing.

**Comment by dtikhonov** [comment]
It's very interesting.  I am not familiar with Geany, so I'll have to think about this a bit.

However, what was the issue with converting ctags to a library (issue #63)?  From my, likely uneducated, point of view, this seems like a more straightforward approach.

**Comment by masatake** [comment]
In #63, I'm thinking about providing reusable interface to applications which runs ctags.
It is general purpose.

In this issue, I'm talking only about u-ctags and geany.
The scope is much smaller.

**Comment by ffes** [comment]
I think the most important thing to do would be sync the parsers between the two projects.

Indeed the kind types is an important issue. @b4n wrote in https://github.com/universal-ctags/ctags/pull/267#issuecomment-86929793 that the Geany team want to remove this difference between from their parsers.

Splitting in `common-parsers` and `own-parsers` seem overkill to me, but I may be wrong. Wonder what the others have to say about that.

I am working on the markdown parser ATM, so we are able to tags our own code. I am adding nestlevel to this parser. And I have a personal need to copy (and add nestlevel) the DocBook parser as well.

Our `flex.c` parser and the `actionscript.c` parser of Geany both seems to be parsers for ActionScript.

@QingmingHe has been doing much work to our Fortran parser so he is our expert on the difference between those two parsers.

Question I have is why Geany didn't include all the parsers. Some of them have been in exuberant for a long time. Hopefully @b4n can answer that when he is back.

And the PowerShell parser is only available in Geany as well.

**Comment by masatake** [comment]
> I think the most important thing to do would be sync the parsers between the two projects.
@ffes, though once parsers are synced between two projects, a project modifies a parser,  persons in anothor project must update their parser.

So I think sharing the repository with git submodule is much better. This is the base line of this discussion.
Do you have another option about "sharing"?

**Comment by masatake** [comment]
(Should we do this in wiki?)

**Comment by vhda** [comment]
In my opinion Geany should have a translation layer to convert from our kinds to theirs. Would it be hard to implement this on geany side?

**Comment by masatake** [comment]
For doing translation outside of ctags, geany may need a hashtable or something.
This means looking up is needed for each tag.
If doting it in ctags as expalined in my rst file, looking up is not needed. 

However, I have not studied how geany deals kinds well yet.

Following code taken from tagmanager of geany makes me confused.
```
static kindOption HaskellKinds [] = {
...
    { TRUE, 'c', "macro", "type constructors" },
static kindOption CKinds [] = {
	{ TRUE,  'c', "class",      "classes"},
	{ TRUE,  'd', "macro",      "macro definitions"},
```

BTW, I think translation layer(I called flavour) may be needed in xcmd, too.

**Comment by masatake** [comment]
Too difficult to solve this issue.
