### ISSUE TITLE
main: --version output

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#472]
```
Universal Ctags Development, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 29 2015, 01:19:02
  Addresses: <dhiebert@users.sourceforge.net>, https://ctags.io/
```

I'm afraid Darren receives unexpected bug report about our code.
I also want to add "2015 Universal-ctags orgnazation" to Copyright line.

I wodner how the output format should be.
(Derived from #463)

**Comment by dtikhonov** [comment]
- Does the `-verrsion` output have to have an email address?
- If we list Darren, we should list other people as well.

**Comment by masatake** [comment]
@dtikhonov, thank you. I will remove "Addresses". In stead I put URL field.
The copyright line is originally derived from Exuberant Ctags. I don't want to touch it.
```
Universal Ctags Development, Copyright (C) 2015 Universal-ctags orgnazation
  Compiled: Jul 29 2015, 01:19:02
  URL: <dhiebert@users.sourceforge.net>, https://ctags.io/
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  ...
```
How about this one?

**Comment by ffes** [comment]
I agree with @dtikhonov and remove the email address. The URL should give you all you need.

And mentioning Exuberant is good thing IMHO.

**Comment by vhda** [comment]
Fix "organization".
And I also agree that we should drop the email address.

**Comment by ffes** [comment]
And what about this first line?

```
Universal Ctags Development, Copyright (C) 2015 Universal Ctags Team
```

"Organization" sounds so formal to me...

Does mentioning Exuberant not cause (or maybe it just solves) problems as @k-takata mentioned in #463 https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/scripts/tags.sh#n276

**Comment by vhda** [comment]
:+1:

**Comment by masatake** [comment]
Thank you for comments. 

One more thing. How about tags output?

```
[yamato@x201]~/var/ctags-github% ctags /dev/null
[yamato@x201]~/var/ctags-github% cat tags
cat tags
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
```

How this should be?
My idea is:
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	//
!_TAG_PROGRAM_MAINTAINER	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io	/official site/
!_TAG_PROGRAM_VERSION	Development	//
```

Here I removed the mail address as the same reason above.
I introduced !_TAG_PROGRAM_MAINTAINER.

**Comment by vhda** [comment]
Following the approach suggested by @ffes, why not drop PROGRAM_AUTHOR tag?
Anyone knows how to automatically check if a version tag exists in the current HEAD, or otherwise set the version to the current short SHA commit?

**Comment by masatake** [comment]
@vhda, I think !_TAG_PROGRAM_* is part of stable interface between an application and tags file.
I hope adding something new is allowed but I think we should not remove it. I don't research applications using tags file, but I would like to keep it.
I will make a PR with following format:
```
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team  //
```
> Anyone knows how to automatically check if a version tag exists in the current HEAD, or otherwise set the version to the current short SHA commit?

Many hits are in 
https://github.com/universal-ctags/ctags/pull/222
