### ISSUE TITLE
C++11: enum class/struct not working

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [universal-ctags/ctags#488]
The new `enum class` and `enum struct` are only partially functioning:
- The lasts enumerationvalue is not recognized. (It is recognized when I put a semicolon after it, but that's not allowed in C++.)
- Enum class values are reported as members, and require the +m field. Shouldn't that be '+e' (enum values)? Also, the type name of the enum (EC1 below) is reported as class type instead of enum type.
- enum:type is not working at all for normal enums at the moment.

Screenshot of the unit test (Cxx11enum.cpp.d)
(Lime: recognised type; yellow: enum value; blue: class member)
![Vim screenshot](https://cloud.githubusercontent.com/assets/6233682/9126998/dca32bcc-3cb4-11e5-8885-1d0ccccb2e4e.png)

**Comment by b4n** [comment]
Hum, what version of universal-ctags are you using?  The [expected output in the test case](/universal-ctags/ctags/blob/master/Units/cxx11enum.cpp.d/expected.tags) look both good and corresponding to your expectations to me, and it's definitely what u-ctags outputs.

BTW, your screenshot is not the stock version of [cxx11enum.cpp.d/input.cpp](/universal-ctags/ctags/blob/master/Units/cxx11enum.cpp.d/input.cpp), but also works for me:
```C++
enum A {A_a, A_b, A_c};
enum B:int {B_a, B_b, B_c};
enum class EC1 {EC1_a, EC1_b, EC1_c};
enum class EC2:int {EC2_a, EC2_b, EC2_c};
enum struct ES1 {ES1_a, ES1_b, ES1_c};
enum struct ES2:int {ES2_a, ES2_b, ES2_c};

class Foo {
  enum D:int {a, b, c};
  enum class EC2:unsigned {EC2_a, EC2_b, EC2_c};
  enum struct ES2:int {ES2_a, ES2_b, ES2_c};
  virtual void foo(enum D a);
}
```

**Comment by RagnarGrootKoerkamp** [comment]
After reinstalling it using the method mentioned in the docs, and using a custom prefix, everything works as expected! I think there was a name clash with another ctags program.

(I modified the stock test, to check whether the `:int` would change the behaviour.)

Thanks anyway!
