### ISSUE TITLE
json: "Warning: ignoring null tag"

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#492]
```
[yamato@x201 ctags-github]$ cat null.json
[{"":1}]
[yamato@x201 ctags-github]$ ./ctags -o - null.json  
ctags: Warning: ignoring null tag in null.json
0	null.json	/^[{"":1}]$/;"	o
```

**Comment by b4n** [comment]
hum, ok.  Technically outputting an empty string is the right thing to do AFAICT.  If this is truly invalid for CTags, I guess we just need to skip empty tags.

**Comment by masatake** [comment]
I see. Let's skip empty tags.
I wonder which layer should handle a null tag.
I have reported null tags more than once because it implies something bug (or incompleteness) of parser.
In addition it seems that an empty string as a dict key is acceptable in json.

So just ignoring a null tags in entry.c is a bad idea and it should be handled in json parser.
