### ISSUE TITLE
Some tests fail on MSYS2

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#494]
I have uploaded the results of `make check` on MSYS2.
https://gist.github.com/k-takata/d3ea1ddb3c5c5e186348

Some tests fail because the executable name is shown in the fullpath:

```diff
--- Tmain/alias-for-unknown-language.d/stderr-actual.txt	2015-08-08 16:01:59.918759200 +0900
+++ Tmain/alias-for-unknown-language.d/stderr-expected.txt	2015-07-09 22:37:01.408106900 +0900
@@ -1 +1 @@
-C:\WORK\universal-ctags\ctags.exe: Unknown language "nosuchlang" in "alias-nosuchlang" option
+ctags: Unknown language "nosuchlang" in "alias-nosuchlang" option
```

Some other tests seems to fail with another reason.
E.g. https://gist.github.com/k-takata/d3ea1ddb3c5c5e186348#file-tmain_lregex-list-kinds-d_stderr-diff-txt

Related: #478

**Comment by masatake** [comment]
About the quoted lines, baseFilename in routines.c dones't work as we expected.
@k-takata, can I ask you to look this function more?




Tmain is rather newer test harness than Units. Both mainly I wrote. In Units features (ctags --list-feathres) are tested before running a test case. The features available in the target ctags is compared with features a test case requires. e.g. Units/xcmd-etags.d/features.

In some test cases in Units, this features tesing are conducted. 
In most of all test cases in Units, this features testing is not conducted.

Features causing trouble here will be +wildcards, +regex, +cproc. However, +wildcard, +regex should be available. These two require libregex and libfnmatch. Ctags build system utilizes the bundled library source code when they are not available. Therefore features +wildcard, +regex should be always available.

Anyway I would like to know --list-features output on the environment/platform.

**Comment by masatake** [comment]
BTW, @k-takata, will you have more issues and ideas to improve ctags?
(I guess the answer is yes.)

We want you to work as a member of universal ctags team.
Do you have interest being a member?
Smaller fixing like s/yamoto/yamato/ can be done without sending a PR:-P.

If you have, could you add your name to docs/developers.rst and sending a PR?

**Comment by k-takata** [comment]
> Anyway I would like to know --list-features output on the environment/platform.

You can see the result of `./ctags --version` at here:
https://ci.appveyor.com/project/k-takata/ctags/build/1.0.69/job/8gf0t6sgurclt837#L775

```
Universal Ctags Development, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug  8 2015, 06:48:45
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +multibyte, +debug
 ```

**Comment by masatake** [comment]
...strange. regex is available... Anyway +cproc is not available. It means xcmd related test should be detailed. I will take a look more after implementing .m and .h selectors.

**Comment by k-takata** [comment]
> About the quoted lines, baseFilename in routines.c dones't work as we expected.

Ah, maybe `MSDOS_STYLE_PATH` is not defined.

**Comment by k-takata** [comment]
> If you have, could you add your name to docs/developers.rst and sending a PR?

Thank you for inviting me to the team. I'd like to do it when I have a time.

**Comment by k-takata** [comment]
After defining `MSDOS_STYLE_PATH` forcedly, the first example still fails:

```diff
--- Tmain/alias-for-unknown-language.d/stderr-actual.txt	2015-08-08 21:41:58.017367400 +0900
+++ Tmain/alias-for-unknown-language.d/stderr-expected.txt	2015-07-09 22:37:01.408106900 +0900
@@ -1 +1 @@
-ctags.exe: Unknown language "nosuchlang" in "alias-nosuchlang" option
+ctags: Unknown language "nosuchlang" in "alias-nosuchlang" option
```

We need to cut the extension `.exe`.

**Comment by k-takata** [comment]
I checked the `lregex-accept-reserved-kind.d` case.

When I ran the test case manually:

```
$ ./ctags --quiet --options=NONE -o - --langdef=foo'{fileKind=!}' --regex-foo=/a/\0/F/ ./Tmain/lregex-accept-reserved-kind.d/run.sh
```

I found that the `regexp` parameter of `parseTagRegex()` becomes `A:/0/F/` not `/a/0/F/`. WHAT!?

It was caused by pathname coversion of MSYS2:
http://sourceforge.net/p/msys2/wiki/Porting/#filesystem-namespaces

The following setting is needed for regex tests:

```
export MSYS2_ARG_CONV_EXCL='--regex-foo='
```

After this setting, some xcmd tests still fails:

```
lxcmd-accept-reserved-kind/stderr-compare
lxcmd-backend-not-found/stderr-compare
lxcmd-backend-premature-death/stderr-compare
lxcmd-broken-kind/stderr-compare
lxcmd-disabled-kind/stdout-compare
lxcmd-disabled-kind/stderr-compare
lxcmd-exit-status-override/stdout-compare
lxcmd-exit-status-override/stderr-compare
lxcmd-exit-status-override/exit-compare
lxcmd-list-kinds/stdout-compare
lxcmd-list-kinds/stderr-compare
lxcmd-reject-reserved-kind/stderr-compare
xcmd-dont-run-setgid-executable/stdout-compare
xcmd-dont-run-setgid-executable/stderr-compare
xcmd-dont-run-setuid-executable/stdout-compare
xcmd-dont-run-setuid-executable/stderr-compare
```

**Comment by masatake** [comment]
Does
```
export MSYS2_ARG_CONV_EXCL='--regex-'
```
work expectedly?
A user cannot predict <LANG> part of --regex-<LANG> because <LANG> is defined dynamically.

Does adding --list-regex-languages option help you? With the output of the option, you can build the value for MSYS2_ARG_CONV_EXCL.

BTW, no lang should define/use '/' as a kind letter.

**Comment by k-takata** [comment]
> Does
> 
> export MSYS2_ARG_CONV_EXCL='--regex-'
> 
> work expectedly?

It works!

**Comment by k-takata** [comment]
Maybe we should add `export MSYS2_ARG_CONV_EXCL='--regex-'` in somewhere (misc/units?), when we run `make check` on MSYS2. (Note: `uname -o` returns `Msys` on MSYS2.)

> Anyway +cproc is not available. It means xcmd related test should be detailed.

I want to know where this check is done.

**Comment by masatake** [comment]
> Maybe we should add export MSYS2_ARG_CONV_EXCL='--regex-' in somewhere (misc/units?), when we run make check on MSYS2. (Note: uname -o returns Msys on MSYS2.)
Any parts of test harness and ctags itself refer the variable, MSYS2_ARG_CONV_EXCL. Therefore you can add  MSYS2_ARG_CONV_EXCL='--regex- anywhere you want. misc/units can be good candidate.
Howerver, I wonder how ctags users on msys2 do about MSYS2_ARG_CONV_EXCL. For running ctags under AppVeyor we can use the hack we found. How about normal using? Evenrytime users have to set the environment variable? It sounds very annoying. I want to fix it.
Of course, the primary goal is utilizing AppVeyor. So we can fix it later.



>    Anyway +cproc is not available. It means xcmd related test should be detailed.
I want to know where this check is done.

I will prepare a PR for fixing it.

**Comment by k-takata** [comment]
> Evenrytime users have to set the environment variable? It sounds very annoying. I want to fix it.

MSYS2 has three variations of GCC:

1. `/usr/bin/gcc`: This builds MSYS2 binaries.
2. `/mingw32/bin/gcc`: This builds Win32 native binaries.
3. `/mingw64/bin/gcc`: This builds Win64 native binaries.

If someone wants to run ctags.exe from MSYS2, he should use a binary built for MSYS2 (built with 1.), not Win32/64 native binary (2. or 3.). If he uses MSYS2 binary, he doesn't need to set `MSYS2_ARG_CONV_EXCL`. The pathname conversion only occurs when running a Win32/64 native program form a MSYS2 program (shell).

**Comment by masatake** [comment]
> Anyway +cproc is not available. It means xcmd related test should be detailed.
I want to know where this check is done.

Could you try #512?

**Comment by k-takata** [comment]
Now #512 is merged, I tried MSYS2 on AppVeyor again.

First, I added a commit to set `MSYS2_ARG_CONV_EXCL`:
https://github.com/k-takata/ctags/commit/a9a3a3f297c283ec33127c21c3f316364fe69c91
(I'm not sure this is the best place to set MSYS2_ARG_CONV_EXCL.)

But it fails due to tempfile handling:
https://ci.appveyor.com/project/k-takata/ctags/build/1.0.88/job/1qex0k8woyf2406l#L953

So, I added a commit to fix the tempfile handling:
https://github.com/k-takata/ctags/commit/6b38524db47e1972bc7b3fb2eaef4864d590b934

Now all `Tmain` tests passed, and almost all `Units` tests passed.
https://ci.appveyor.com/project/k-takata/ctags/build/job/su46ydlfj7ppj25j

I will send these two commits as new PRs.

**Comment by k-takata** [comment]
Updated AppVeyor result with #515, #516 and #521:
https://ci.appveyor.com/project/k-takata/ctags/build/1.0.100/job/hhqav7v9oa556j89

Now only 2 tests failed:

```
Summary (see CMDLINE.tmp to reproduce without test harness)
------------------------------------------------------------ 
  #passed:                                470
  #FIXED:                                 0
  #FAILED (unexpected-exit-status):       0
  #FAILED (unexpected-output):            2
	review-needed/bug1777340.java
	review-needed/rojas.h
  #TIMED-OUT (5s)                         0
  #skipped (features):                    25
...
```

It' very strange that regex tests are skipped. E.g.:

```
Testing conflib-simple as coffee                            skipped (required feature "regex" is not available)
```

This doesn't happen when I run the test on my local PC.
(bug1777340.java and rojas.h still fail on my PC.)

**Comment by k-takata** [comment]
> It's very strange that regex tests are skipped.

After installing dos2unix, regex tests are no more skipped.
https://ci.appveyor.com/project/k-takata/ctags/build/1.0.102/job/1vyk0gbr72d3uy7c

**Comment by masatake** [comment]
How about adding something like following code  to misc/units to avoid repeating the same trouble:
```
diff --git a/misc/units b/misc/units
index 6bf98f4..3f1f782 100755
--- a/misc/units
+++ b/misc/units
@@ -1884,6 +1884,9 @@ main ()
 	    return 0
 	    ;;
 	run)
+	    if MSYS2; then
+		check_availability dos2unix
+	    fi
 	    action_run "$@"
 	    return $?
 	    ;;
```

**Comment by k-takata** [comment]
Result of `bug1777340.java.t` (`DIFF.tmp`):

```diff
--- ../Units/review-needed.r/bug1777340.java.t/expected.tags	2015-08-24 01:03:32.139916000 +0900
+++ /c/WORK/universal-ctags/build-mingw/Units/review-needed.r/bug1777340.java.t/FILTERED.tmp	2015-09-03 08:27:13.602174600 +0900
@@ -0,0 +1 @@
+R	input.java	/^    String n() default "ninjas; monkeys!";$/;"	f	interface:bug1777340
```

Result of `rojas.h.t` (`DIFF.tmp`):

```diff
--- ../Units/review-needed.r/rojas.h.t/expected.tags	2015-08-24 01:03:32.745978700 +0900
+++ /c/WORK/universal-ctags/build-mingw/Units/review-needed.r/rojas.h.t/FILTERED.tmp	2015-09-03 08:28:30.403493700 +0900
@@ -1,5 +0,0 @@
-FFunc	input.h	/^typedef uint32 (*FFunc) (const astruct * pP, int n);$/;"	t
-FooBar	input.h	/^typedef void * FooBar;$/;"	t
-astruct	input.h	/^struct astruct$/;"	s
-astruct	input.h	/^typedef struct astruct astruct;$/;"	t	typeref:struct:astruct
-m_member	input.h	/^    int m_member;$/;"	m	struct:astruct
```

**Comment by masatake** [comment]
I found the `R` comes from `STRING_SYMBOL` in read.h.
Still debugging.

**Comment by masatake** [comment]
It seems that isalpha for 338 behaves differently on GNU/Linux and Windows.
(Consider ((char)338) == 'R'.).

@k-takata, Could you try the following on Windows?

On my fedora, isalpha(338) return 0.
How about on your environment?
I guess 1 will be returned.



```
[yamato@x201]/tmp% cat isalpha.c 
#include <stdio.h>
#include <ctype.h>

int
main(void)
{
  int c = 338;
  fprintf(stderr, "%d\n", isalpha(c));
  return 0;
}
[yamato@x201]/tmp% gcc isalpha.c 
gcc isalpha.c 
[yamato@x201]/tmp% ./a.out 
./a.out 
0
```

**Comment by masatake** [comment]
Search `INITIAL TEST: isalpha:` in 
`https://ci.appveyor.com/project/masatake/ctags/build/1.0.34/job/48kbqk0q85r7n0mb`

Associated code for the output is:

https://github.com/universal-ctags/ctags/commit/29ccededfdf470149a2699bc4f80c68f0aef5418

On my Fedora:

```
b% ./ctags -o - Units/review-needed.r/bug1777340.java.t/input.java

./ctags -o - Units/review-needed.r/bug1777340.java.t/input.java
INITIAL TEST: isalpha: 0
```

**Comment by masatake** [comment]
isalpha(2) says:
```
These functions check whether c, which must have the value of an unsigned char or EOF, falls into a  certain
       character  class according to the specified locale. 
```
338 is greater than 256. It is not in the range of unsigned char...

**Comment by k-takata** [comment]
> Could you try the following on Windows?

Bingo! isalpha(338) return 1 on Windows.
Maybe, `isascii(c) && isalpha(c)` will fix the problem.

**Comment by masatake** [comment]
> Maybe, isascii(c) && isalpha(c) will fix the problem.

Thank you. I will make a PR based on your comment...

**Comment by masatake** [comment]
We got it. All tests are passed. 

@k-takata, thank you very much for long time efforts to utilize AppVeyor.
Now we can see how ctags behaves on Windows.

regex feature on cygwin is still disabled. However, we can solve it in the future.
Now we can close this?

**Comment by k-takata** [comment]
:clap: Let's close this.
Please merge #549.
