### ISSUE TITLE
Build and package on MSYS2

### ISSUE THREAD

**Issue by oscarfv** [universal-ctags/ctags#505]
This is related to #354.

I see some people working with MSYS2 here (@k-takata).

Yesterday I compiled `universal-ctags` on MSYS2 with `configure && make` method but the process resulted on an executable with on support for regexs. Once this was activated (invoking configure with `LIBS=-lpcreposix` or something) the executable crashes when it needs to use that functionality (for `--regex-lang=` etc). This is the same problem that Exhuberant Ctags 5.8 has. For 5.8, using the Mingw-specific makefile works.

I wonder if there is a method for building Universal Ctags on MSYS and if somebody plans to package it. I can take care of the later, once we have a solid build process.

**Comment by k-takata** [comment]
> invoking configure with LIBS=-lpcreposix or something

If you want to link with libpcreposix, you must include `pcreposix.h` instead of `regex.h`.
You might think that the function prototype of `regcomp` and `regexec` are same with GNU regex and pcreposix, but GNU regex's `regex_t` and pcreposix's `regex_t` are not compatible.

**Comment by oscarfv** [comment]
@k-takata : thanks for the tips. I submitted a merge request with a tiny change. Once this is merged, I'll submit a PKGBUILD file to MSYS2.

BTW, the failed tests are something to be concerned about, for a user that is switching from Exuberant Ctags to Universal Ctags? I mean, is Universal Ctags ready for replacing Exuberant Ctags? (In the MSYS2 case, specifically)

**Comment by masatake** [comment]
> BTW, the failed tests are something to be concerned about, ...

@oscarfv, which test case you are talking about? I and @k-takata have worked hard to fix such failures on windows via AppVeyor. Could you try the latest code?

**Comment by oscarfv** [comment]
I was thinking of #494, which was closed a few hours ago, not something that I tried.

MSYS2 now has a binary package for `universal-ctags`.

That binary package was created 6 days ago, based on 80256f44b95580c3c03fc517a2d1bd99f884bad3. Do you think it is important to rebuild with the latest code?

**Comment by masatake** [comment]
> That binary package was created 6 days ago, based on 80256f4. Do you think it is important to rebuild with the latest code?

Yes, a minor bug is fixed.

**Comment by oscarfv** [comment]
Thanks, as universal-ctags if built from git on MSYS2, it will be rebuilt rather sooner than later. Requesting a new build for solving a minor bug is not worth the trouble.
