### ISSUE TITLE
make check stores the results always in the srcdir

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags#511]
Even if `configure` was executed in a different directory form the srcdir, `make check` stores the results in the srcdir not in the builddir.
It would be prefer to store the results in the builddir.

Related: #501

**Comment by masatake** [comment]
I would like to know the requirement.

$(builddir) is not found in Makefile.in. Should I define it by myself?

**Comment by masatake** [comment]
Now I may understand the requirement.
Could you try #513? It is for tmain target.

I will work on units target. It takes rather longer  time. units is much more complicated than tmain. sigh.

**Comment by masatake** [comment]
Is this issue solved now?

**Comment by k-takata** [comment]
Yes.
