### ISSUE TITLE
Decrease autoconf minimum required version to 2.59

### ISSUE THREAD

**Issue by vhda** [universal-ctags/ctags#559]
Redhat 5.7 is still very common in engineering grid environments, but it only includes autoconf 2.59. It would be helpful to decrease the minimum requirements to this version in order to simplify the compilation process in this distribution.

**Comment by p-montanus** [comment]
How about p-montanus@29b65cd77e8ad4eb46cb7c70585495413ac27f05?

But I believe, supporting old autoconf is not a good idea, its evil.
autoconf version is mainly developers issue. Porting newer autoconf to RHEL 5.7 is the right way.

**Comment by vhda** [comment]
Can't the functions we're using from >2.59 be replaced with equivalent, even if longer or more confusing, functions from version 2.59? Do we really need to copy all this code?

**Comment by vhda** [comment]
@p-montanus what about something like this https://github.com/vhda/ctags/commit/d1f656185b0bc50d056953be99fb80062b73230f?

**Comment by p-montanus** [comment]
@vhda 
>Do we really need to copy all this code?

Strictly, No.

>what about something like this vhda@d1f6561?

Nice.
Works smoothly, and seems no ploblem.
But I do not prefer introducing ancient autoconf related code into configure.ac.

Sample appending fallback macro handling system with no modification to configure.ac branch:
p-montanus@01dfe09da4f0d3b458b327c3ee6314bc0ee76127

**Comment by vhda** [comment]
@masatake do we really need the MKDIR_P variable?
In the same line we use MKDIR_P we also call `dirname` and we don't need any autoconf support for that.

Otherwise I'll just close this issue. It's not that hard to get a newer version of autoconf installed and no one really complained about this up until now.

**Comment by masatake** [comment]
@vhda, I make a PR.
make tinst says nothing wrong even I removed mkdir_p related code.

**Comment by vhda** [comment]
This was take from autoconf's documentation:

```
Macro: AC_CHECK_HEADERS_ONCE (header-file...)

    For each given system header file header-file in the blank-separated argument list that exists, define HAVE_header-file (in all capitals). This is a once-only variant of AC_CHECK_HEADERS. It generates the checking code at most once, so that configure is smaller and faster; but the checks cannot be conditionalized and are always done once, early during the configure run. Thus, this macro is only safe for checking headers that do not have prerequisites beyond what AC_INCLUDES_DEFAULT provides. 
```

This project is rather small, so I think that the extra checking made by `AC_CHECK_HEADERS` when compared with `AC_CHECK_HEADERS_ONCE` is compensated by the extra level of compatibility with currently available Linux distributions.

@masatake if you agree, I'll create a PR with the above mentioned changes as soon as you merge yours.

**Comment by vhda** [comment]
Pull requests #563 and #566 fix this issue.

**Comment by masatake** [comment]
@vhda, I merged mine and yours. Now is this issue solved?

**Comment by vhda** [comment]
Yes, ctags now compiles cleanly when using autoconf-2.59.
Thanks for your help.

**Comment by vhda** [comment]
Apparently PR #700 reopened this issue.
My knowledge of autotools is very limited, so I'm unable to hack the solution for this, sorry.

**Comment by vhda** [comment]
@masatake is it too hard to fix this given the recent revamp of our autotools usage?

**Comment by masatake** [comment]
I have not looked into this yet.

**Comment by masatake** [comment]
Universal-ctags-6.0.tar.xz will solve this.
