### ISSUE TITLE
Missing License/copyright information

### ISSUE THREAD

**Issue by viccuad** [universal-ctags/ctags#567]
Hello, I'm in the process of packaging universal-ctags for Debian.
In the current form, this project is missing license and copyright information (which is a blocker for redistributing it in any way).

Currently, 
- Some source files have a header stating "Gnu Project License" but no version (eg: main/main.c). I could understand it as GPL1 (or GPL v1+), but I don't know if that's the intent of it.
- Some source files are missing both license and copyright information (eg: main/selectors.c).
- There's no general License.md or similar, stating a license for files in case they don't have a header.

Also, it would be good to have a general Contributors.md contributors list or similar to extract all copyright holders from it.

One solution I can think of as of now is to add a License.md file that states a license for the files unless those have a header, a Contributors.md for all those general files, and make headers containing license and copyright for the files that are under a different license.

Ideally, the best solution would be for every file to have a header (as they can be copied to other projects).

**Comment by masatake** [comment]
(Though I understand the importance, I don't want to increase my work.)
universal ctags is forked from exuberant ctags. As far as I know exuberant ctags ships as part of debian.
So universal ctags should follow exuberant ctags. exuberant ctags doesn't have Contributors.md.

> Some source files have a header stating "Gnu Project License" but no version (eg: main/main.c). I could understand it as GPL1 (or GPL v1+), but I don't know if that's the intent of it.

I don't know it, too. (main.c comes from exuberant ctags.)
However, my understanding is GPL v2+ because COPYING, which also comes from exuberant ctags, 
explains GPLv2. I think tihs interpretation is quite natural.

We have to check new files. I hope we can forget Tmain and Units; they are test cases.

@dtikhonov, could you copyright notice to main/selectors.c?

I'll take more time for this issue later.

**Comment by dtikhonov** [comment]
> @dtikhonov, could you copyright notice to main/selectors.c?

Sure...  What should it say?

**Comment by viccuad** [comment]
I have made pull request #578 fixing this issue. Please, tell my what do you think about it.

> However, my understanding is GPL v2+ because COPYING, which also comes from exuberant ctags, explains GPLv2. I think tihs interpretation is quite natural.

True, it is quite natural. Yet I'm not so sure that is legal enough. I have updated all those headers to include "version 2", that should be accurate enough. 
About COPYING, of course one can use it how it pleases, but on GNU projects it only contains a copy of the licenses, and the headers on the source code provide on which license that source is.

> I hope we can forget Tmain and Units; they are test cases.

>    @dtikhonov:  Sure... What should it say?

I have added you to the copyright notice on main/selectors.c . Please have a look.

**Comment by dtikhonov** [comment]
> I have added you to the copyright notice on main/selectors.c . Please have a look.

Looks good -- thanks!

**Comment by viccuad** [comment]
Ok, I would say the pull request #578 is more in shape now, please let me know what you think.

**Comment by masatake** [comment]
Merge #578.
Is there any critical issue to make a debian package?
BTW, @viccuad, are you working on debsearch?

**Comment by viccuad** [comment]
Thanks for the merge! 

Currently I have a Debian package that works :) , but I would prefer to have #580 fixed before presenting it for review and inclusion in Debian (I haven't decided yet if it will enter Debian Unstable or Debian Experimental, given that we don't have a first release of universal-ctags). 

About debsearch, nope, I'm not working on debsearch :)

**Comment by vhda** [comment]
That is a very important comment.
@masatake we should probably start focusing on releasing our first version.

**Comment by masatake** [comment]
@vhda, I see.
As the first step, I labelled issue I would like to fix before releasing.
In the labelled items, tags file format related issues have higher priority.

**Comment by masatake** [comment]
One more thing. Currently u-ctags is built with -DDEBUG.
This makes ctags very slow.
