### ISSUE TITLE
Add support for Matlab variables

### ISSUE THREAD

**Issue by petobens** [universal-ctags/ctags#570]
After seeing the work done by @vhda in #544, I was wondering if it is possible to add support for Matlab variables. Consider for example the following `foo.m` file:

```matlab
A = magic(4);
R = randn(3,4,5);
```

It would be great if tags were generated for these variable.
Thanks in advance!

**Comment by vhda** [comment]
Please try #571

**Comment by masatake** [comment]
The original issue is solved by the commit.
