### ISSUE TITLE
Missing configure flag for dir naming (/etc/ctags, /usr/share/ctags, /usr/lib/x86_64-linux-gnu/ctags)

### ISSUE THREAD

**Issue by viccuad** [universal-ctags/ctags#580]
I have looked at `configure --help` but I can't seem to find a flag for this. 

Right now, if I install universal-ctags I get (among other things):

/etc/**ctags**/* (optlib, preload and corpora)
/usr/lib/x86_64-linux-gnu/**ctags**/*  (optlib, preload and corpora)
/usr/share/**ctags**/* (optlib, preload and corpora)

It would be useful to have a `configure` flag for changing those ctags dirs into other string (and maybe defaulting to universal-ctags?). 

That would enable universal-ctags to be installed in parallel with other ctags projects, without the possibility of collisions in those directories.

**Comment by p-montanus** [comment]
For discussion, quick-hacked branch created.
p-montanus/ctags@cb2ab8396922da639313fc9ddb18825375465a4a (includes #579 changes)

Add options to configure:
```
--with-pkgdatadir=[DATADIR/ctags]
--with-pkgsysconfdir=[SYSCONFDIR/ctags]
--with-pkglibexecdir=[LIBEXECDIR/ctags]
```

**Comment by masatake** [comment]
@p-montanus, the changes of #579 is merged.

**Comment by p-montanus** [comment]
Thank you for merging #579.
rebased.

**Comment by masatake** [comment]
@viccuad, the names of directories are not sutable.
See #92. Is it o.k.? I want to stablize it but I cannot find time to do it because there are so many critical issues.

**Comment by masatake** [comment]
@p-montanus, why do you say "quick-hacked" about your branch?

**Comment by p-montanus** [comment]
>why do you say "quick-hacked" about your branch?

Due to not well testing at that moment, and not thinking carefully about option names.

**Comment by masatake** [comment]
Oh, I see. You can utilize misc/tinst script for install testing.

**Comment by p-montanus** [comment]
>You can utilize misc/tinst script for install testing.

Thank you for letting me know.
`make tinst` passed.

**Comment by p-montanus** [comment]
revised: p-montanus/ctags@7f261846819b0ec8c5d86246fee993a2260f4666.
configure options are renamed form `--with-pkg*dir` to `--with-ctags-*dir`, and handle `without-*` cases.

If no exception to this specification in a half day, I will create a pull request.
