### ISSUE TITLE
[Proposal] Arrange '-D' cpp macro definitions in Makefile.in

### ISSUE THREAD

**Issue by p-montanus** [universal-ctags/ctags#584]
I propose removing '-D' cpp macro definitions from Makefile.in and define these at suitable places.

all '-D' cpp definitions in Makefile.in are:
```
-Dbool=int
-Dfalse=0
-Dtrue=1
-DCTAGS_COMMIT_ID=0x$(REV)
-DREADTAGS_MAIN
-DDEBUG
-D_GNU_SOURCE
-D__USE_GNU
-DDATADIR=\"$(pkgdatadir)\"
-DPKGCONFDIR=\"$(pkgsysconfdir)\"
-DPKGLIBEXECDIR=\"$(pkglibexecdir)\"
```

* `-Dbool=int`, `-Dfalse=0`, and `-Dtrue=1`: would be defined at config.h with stdbool.h checking, as could conflict stdbool.h.
* `-DCTAGS_COMMIT_ID=0x$(REV)`: would be defined at config.h with git command checking.
* `-DREADTAGS_MAIN`: would be defined in readtags.c, as used by only in readtags.c, and always defined.
* `-DDEBUG`: would be defined via `AC_SUBST([DEBUG_CPPFLAGS])` at configure.ac.
* `-D_GNU_SOURCE` and `-D__USE_GNU`: would be defined via `AC_SUBST([EXTRA_CPPFLAGS])` at configure.ac.
* `-DDATADIR=\"$(pkgdatadir)\"`, `-DPKGCONFDIR=\"$(pkgsysconfdir)\"`, and `-DPKGLIBEXECDIR=\"$(pkglibexecdir)\"`: would be defined at config.h. with renaming `DATADIR` to `PKGDATADIR` and `PKGCONFDIR` to `PKGSYSCONFDIR`, better.

**Comment by b4n** [comment]
> * `-Dbool=int`, `-Dfalse=0`, and `-Dtrue=1`: would be defined at config.h with stdbool.h checking, as could conflict stdbool.h.

Good idea

> * `-DCTAGS_COMMIT_ID=0x$(REV)`: would be defined at config.h with git command checking.

Beware, as we might want this to change between configure calls, as this is not really a build option but tries to reflect the actual state of the code tree.

> * `-DREADTAGS_MAIN`: would be defined in readtags.c, as used by only in readtags.c, and always defined.

If really it'd only used there and never not defined, do we need to even keep the guard depending on this one?

> * `-DDEBUG`: would be defined via `AC_SUBST([DEBUG_CPPFLAGS])` at configure.ac.

makes sense

> * `-D_GNU_SOURCE` and `-D__USE_GNU`: would be defined via `AC_SUBST([EXTRA_CPPFLAGS])` at configure.ac.

I would need to check exactly why/how they are needed, but sounds reasonable.

> * `-DDATADIR=\"$(pkgdatadir)\"`, `-DPKGCONFDIR=\"$(pkgsysconfdir)\"`, and `-DPKGLIBEXECDIR=\"$(pkglibexecdir)\"`: would be defined at config.h. with renaming `DATADIR` to `PKGDATADIR` and `PKGCONFDIR` to `PKGSYSCONFDIR`, better.

I don't think that's a good idea.  GNU standards mandate one can override some basic directories to the last minute running Make; and those commonly expand to `${prefix}/bin`, `${datadir}/ctags` and the like, so would need manual expansion at configure time, which is both subtle, annoying and, again, probably not a great idea.

**Comment by p-montanus** [comment]
Thank you for commenting.

>>* -DCTAGS_COMMIT_ID=0x$(REV): would be defined at config.h with git command checking.

>Beware, as we might want this to change between configure calls, as this is not really a build option >but tries to reflect the actual state of the code tree.

I think, it has a semantic issue, what CTAGS_COMMIT_ID means:
a) means commit-id at the moment, `autoreconf` executed.
b) means commit-id at the moment, `configure` executed.
c) means commit-id at the moment, `options.c` or `entry.c` is compiled.
d) means commit-id at the moment, `make all` executed.
e) means commit-id at the moment, `make dist` executed.
f) means commit-id at the moment, `make` (any target) executed.

c) is current, b) is this proposal.


>>* -DREADTAGS_MAIN: would be defined in readtags.c, as used by only in readtags.c, and always defined.

> If really it'd only used there and never not defined, do we need to even keep the guard depending on this one?

Probably, No.
readtags.c could act as the library source w/o -D, but we does not use it as the library,
and it was compiled as the library only in deleted maintainer.mak.
Keeping the guard is just saving intensions of first author, and our nostalgia.


>>* -D_GNU_SOURCE and -D__USE_GNU: would be defined via AC_SUBST([EXTRA_CPPFLAGS]) at configure.ac.

> I would need to check exactly why/how they are needed, but sounds reasonable.

Indeed.
After I undestand perfectly why/how they are needed, I will add checking.




>>* -DDATADIR=\"$(pkgdatadir)\", -DPKGCONFDIR=\"$(pkgsysconfdir)\", and -DPKGLIBEXECDIR=\"$(pkglibexecdir)\": would be defined at config.h. with renaming DATADIR to PKGDATADIR and PKGCONFDIR to PKGSYSCONFDIR, better.

> I don't think that's a good idea. GNU standards mandate one can override some basic directories to the last minute running Make; and those commonly expand to ${prefix}/bin, ${datadir}/ctags and the like, so would need manual expansion at configure time, which is both subtle, annoying and, again, probably not a great idea.

Yes, it requires some tricks, like this:
```
AC_DEFUN([EXPAND_AC_DIR], [$(eval "$as_echo_n" $(eval "$as_echo_n" "${$1}"))])

AC_CONFIG_COMMANDS_PRE([
    DATADIR=EXPAND_AC_DIR([pkgdatadir])
    AC_DEFINE_UNQUOTED([DATADIR], ["${DATADIR}"])
])
```
I planed to use above, but is it too tricky?
