### ISSUE TITLE
"--" at command line makes ctags crash

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#589]
```
% ./ctags --
./ctags --
ctags: main/options.c:657: getLanguageComponentInOption: Assertion `option && option[0]' failed.
zsh: abort (core dumped)  ./ctags --
```

**Comment by b4n** [comment]
`--` should probably actually be handled as a separator for options and filenames as many other program do.  But that's a separate question.

**Comment by masatake** [comment]
Using -- as separator is good idea.

Any voluntteer? :-) 

Hints:
- Call chain: processLongOption -> parseOption -> parseOptions -> ...
- Don't forget running ctags under valgrind when testing the code imlementing the separator.
  Memory handling in cArg* is a bit complicated.
