### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [universal-ctags/ctags#619]
I would like to point out that identifiers like "[`_KEYWORD_H`](https://github.com/universal-ctags/ctags/blob/0ce38835ebc37f2a5a5340703c121a6bb3a85923/main/keyword.h#L9)" and "[`_READ_H`](https://github.com/universal-ctags/ctags/blob/7bd64c1dce347feeccb2e2398103f03aba50a78b/main/read.h#L9)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by masatake** [comment]
Sure. I'm waiting for your pull request:-P

**Comment by vhda** [comment]
Is there any lint tool available that can verify those rules for us?

**Comment by masatake** [comment]
```
./ctags --language-force=C -x --_xformat='%N' --kinds-C=d -o - --undef=yes main/entry.h | grep '^_'
```
:-P

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/universal-ctags/ctags/commit/5474c2e5b1b5984c706e3fd6a14902c1a9b02686 "Selection of safe include guards").

**Comment by masatake** [comment]
@elfring, thank you for reporting.
