### ISSUE TITLE
Use /var/tmp instead of /tmp

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#637]
On some platforms tmpfs is mounted to /tmp.
When ctags making a large tag file, ctags causes a OOM killer.

**Comment by vladak** [comment]
On the other hand, on some platforms (Solaris), `/var/tmp` is disk storage which might be unwanted.

**Comment by masatake** [comment]
Could you tell me more about the meaning of "unwanted"?

**Comment by vladak** [comment]
Storing on /var/tmp would involve disk activity and would make the files persistent if ctags process goes away for some reason (/tmp on Solaris is wiped out across reboots by its nature).

**Comment by codebrainz** [comment]
@masatake could you give some details about causing kernel to OOM kill ctags. I'm generally interested because I thought it would be extremely rare for a process to fill up RAM and swap space and get killed.

**Comment by masatake** [comment]
@codebrainz, consider a javascript as input which is highly optimized by a tool. The tool rearrange the original javascript more than 10MB into one line. ctags records a pattern for each tag entry.
Such a file can be found in google-chrome as far as I know.

ctags makes incredibly large tags file for the input. Doing sort in an external command, ctags makes a temorary file. If it goes to /tmp on a Fedora PC, OOM-killer is triggered.

However, this is not an issue nowaday because a pattern longer than 128 bytes are truncated by default. I think this pattern truncation is one of the reason to use universal-ctags.  :-P

**Comment by codebrainz** [comment]
@masatake thanks for the details.
