### ISSUE TITLE
introduce sub parser

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#64]
Consider running ctags against a source tree that uses autotools as  its build system.

Which parser should be used for foo.h.in?

Of course C (or objc) parser should be used first of all.
Is it enough?
How about @PACKAGE@ or something in the file?
@FOO@ is place holder used in autotools. I hope these are also tagged by ctags.
I would like to run the second priority parser(sub parser)something "template-of-configure-output".
The sub parser is activated for files globbed "*.in".

Suprisingly ctags has enough ability to run ,multi-path parser. We can use this function to run sub-parser.

**Comment by masatake** [comment]
Now I understand recording @FOO@ is not so good idea. It is not any kind of definition. It is something referenced.

**Comment by b4n** [comment]
> Now I understand recording `@FOO@` is not so good idea. It is not any kind of definition. It is something referenced.

Yes, it's supposed to be replaced with the value of `FOO` (whatever that can be).

**Comment by masatake** [comment]
php+javascript, we have both. But we don't have a combine them.

I can generalize this issue.

```
--- a/parsers/lua.c
+++ b/parsers/lua.c
@@ -34,14 +34,6 @@ static kindOption LuaKinds [] = {
 *   FUNCTION DEFINITIONS
 */
```

1. Diff parser can capture a/parsers/lua.c. 
2. From the file name, ctags can guess lua.c is written in C language.
3. store ` static kindOption LuaKinds [] = {` to somewhere memory stream.
3. run c parser as a subparser on the memory stream.
So we can capture `LuaKinds`. lua.c is the parent of LuaKinds. LuaKinds is the parent of 
`@@ -34,14 +34,6@@.

We don't have a memory stream. We need it.
I have to inspect mio.

**Comment by cweagans** [comment]
Here's another example:

```
<html>
  <head>
    <title>Test page</title>
    <?php
      function my_function() {
        return 'some string';
      }
    ?>
  </head>
  <body>
    <?php echo my_function(); ?>
  </body>
</html>
```

This is really not a good practice for PHP anymore, but it works, so maybe ctags should support it?

Here's another common scenario:

```
<html>
  <head>
    <title>Test page</title>
    <script type="text/javascript">
      function myFunction() {
        alert('myFunction() has been called');
      }
    </script>
  </head>
  <body>
    <p>some text</p>
    <script type="text/javascript">myFunction();</script>
  </body>
</html>
```

This second example is much more common.

I'm not sure that it's absolutely necessary for parsers to handle things differently in either of these scenarios, though. I should just be able to run the PHP parser on the first example and get back what I expect, and the Javascript parser should tolerate the second example. If I have both PHP and Javascript in the same file like that, then I should just be able to run both parsers over the same file and get back something reasonable.

**Comment by masatake** [comment]
Very attractive. This kind of example will defer the release:-P

Currently the most of all parsers keep the state of parsing as file local variables.
This will be a trouble in calling a parser from another parser.
We have to introduce parserInstace data type that keeps the state of parsing.

The state of input stream can be stacked...
...

BTW, when submitting an example, I recommend you to submit an expected tags, too if possible.
So the discussion becomes more fruitful and attractive.

**Comment by cweagans** [comment]
@masatake I'm saying that we shouldn't need to do that. One parser doesn't need to call another parser. We just need to be able to say "Run this set of parsers on this particular file type.", probably through a CLI switch (instead of doing it be default).

I might be a bad developer and have `test.html` with HTML, CSS, Javascript, and PHP all in the same file, so *separately*, I'd want all four of those parsers to run on `test.html`. A parser shouldn't call any of the other parsers. The HTML parser runs on the file, extracts whatever information it can get, and then gives control back. Then, the CSS parser runs on the same file, extracts info, and gives control back. Repeat for all of the parsers that need to be run.

This is definitely not needed for 1.0.0, I think.

**Comment by masatake** [comment]
ctags is used behind opengrok and debian code search. And this is the area I'm interested in.
In this use case, just default command line arguments are used. There is no chance to tune options for input. Many things must be done automatically.

**Comment by masatake** [comment]
Now we have mio.
When `mio_new_mio` is implemented, we can handle a language in a language cleanly.

* php in html
* js in html
* js in php?
* css in html
* asm in C(known as inline)
* here document in shell script
* C in yacc/lex
* javadoc in java
* code-block in rst

If you are interested in working on these area, tell me. I will work on `mio_in_mio`.

**Comment by masatake** [comment]
See #875. Running a specified parser in an area of input can be scheduled. For the feature I will introduce new API set called "promise".

A parser make a promise during paring. For making a promise, the parser specifies the start of the area, the end of the area, and the name of parser which parses the area. 

After the current parser finishes parsing the input, ctags checks the backlog of promises made by the last parser. If there is more than one promise, ctags forces the promises: making a sub stream from the start and end information of the promise and invoking the parser specified with the name in the promise on the sub stream.

**Comment by masatake** [comment]
There is no way to pass data from parent to its children but promise works well.
