### ISSUE TITLE
Bug found in --python-kinds option while generating a tag file

### ISSUE THREAD

**Issue by vhda** [universal-ctags/ctags#648]
_From @yevhen-m on October 29, 2015 10:5_

Hey, I use ctags to generate tag files for python code.
I get an error, if I use --python-kinds=cf option
f stands for 'function' and is a valid python kind

here is a screenshot
![screenshot from 2015-10-28 18 30 45](https://cloud.githubusercontent.com/assets/10185058/10815484/0f795244-7e35-11e5-8fd5-85def6062c88.png)

Will be grateful, if you fix this issue ))

_Copied from original issue: universal-ctags/universal-ctags.github.io#13_

**Comment by vhda** [comment]
_From @masatake on October 29, 2015 11:48_

@yevhen-m, thank you for reporting. However, this is place for reporting an issue about u-ctags web site.
Please, visit https://github.com/universal-ctags/ctags/issues

**Comment by vhda** [comment]
I've used https://github-issue-mover.appspot.com/ to move the issue over.

**Comment by masatake** [comment]
Already spotted the place to be fixed.

**Comment by yevhen-m** [comment]
Thanks, guys, it works now!!
