### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by giuse88** [universal-ctags/ctags#654]
Would really nice and useful to have scala support.

**Comment by vhda** [comment]
Hi @giuse88 

I will try to setup a regular expression parser for Scala using the information available in:
https://leonard.io/blog/2013/04/editing-scala-with-vim/
https://github.com/luben/sctags

Could you please provide some small Scala example code files that would generate tags for all the types mentioned in the above links?

**Comment by masatake** [comment]
See https://github.com/universal-ctags/ctags-xparsers/issues/2

**Comment by tarzanek** [comment]
OpenGrok also uses some patterns to detect scala
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/Ctags.java#L120

(and go and clojure and haskell)

**Comment by masatake** [comment]
Can we use it in GPL v2 or later?

**Comment by tarzanek** [comment]
Opengrok is cddl so ... i don't know, but I'd hope so ...

**Comment by masatake** [comment]
This issue is merged to #1566.
