### ISSUE TITLE
Decide on release schedule/policy

### ISSUE THREAD

**Issue by cweagans** [universal-ctags/ctags#662]
We need to have a consistent release schedule. I suggest releasing once every 6 months, ideally in January and July. This way, the new release will be out soon enough for the Ubuntu maintainers to include it in the release that happens in April and October.

This is, of course, assuming that there will be new things to release every six months. Based on the activity level over the past few months, I'd say that's a very likely thing.

**Comment by cweagans** [comment]
https://github.com/universal-ctags/ctags/issues/661#issuecomment-156140424 is related to this issue.

I don't think we'll have to do RCs going forward. We can just tag new feature/patch releases per the semver standard, which should be pretty quick. I'm happy to take on responsibility for release coordination if that would help.

**Comment by masatake** [comment]
I want you to take the responsibility. How about starting working for release in this December?

**Comment by cweagans** [comment]
Okay, I can do that. @masatake Can you and the other devs go through the release milestone and ensure that the things that are in there are things that actually need to be done? In other words, if there are things that can wait, please remove them from the milestone.

**Comment by masatake** [comment]
@cweagans, I see.
