### ISSUE TITLE
Package for Gentoo

### ISSUE THREAD

**Issue by cweagans** [universal-ctags/ctags#663]
We have issues for [Debian](https://github.com/universal-ctags/ctags/issues/655), [RHEL](https://github.com/universal-ctags/ctags/issues/656), [Mac](https://github.com/universal-ctags/ctags/issues/658), and [Windows](https://github.com/universal-ctags/ctags/issues/660), but nothing for Gentoo. 

@Tranquility was interested in this. Is there some packaging information that needs to go into the ctags repository for you to be able to package for Gentoo? Or does it work some other way?

**Comment by Coacher** [comment]
All you need to do packaging-wise is to provide release tarballs. The ones autogenerated by GitHub will do just fine. See also https://bugs.gentoo.org/show_bug.cgi?id=561074

Gentoo packaging policy also forbids automagic dependencies. Please avoid them. See also: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies

**Comment by cweagans** [comment]
@Coacher That will definitely happen when the Initial Release milestone is complete. The reason I ask about files that go into the repo is that we'll eventually have a `debian` directory in the repo so that we know how that packaging works. I'm wondering if there's anything similar for Gentoo - even if it's just some kind of metadata file or something. Ideally, when we tag a release, we can go through and update the version number in the spec file, in the appveyor build config, in the debian package, in the homebrew formula, and in the gentoo packaging info (if it exists). That way, everyone that's building packages for Universal Ctags only has to clone the repo and run whatever script they'd normally run.

Also note that if you wanted to start testing now, you can use https://github.com/universal-ctags/ctags/archive/master.tar.gz as a target.

If you run into anything that would prevent Universal Ctags from being packaged on Gentoo, please open an issue for each specific problem and reference this one so we can get it resolved before the first stable release.

**Comment by Tranquility** [comment]
I already created a package. I just need to know which version number the first release will have to add it into the official tree.

**Comment by Coacher** [comment]
> The reason I ask about files that go into the repo is that we'll eventually have a debian directory in the repo so that we know how that packaging works. I'm wondering if there's anything similar for Gentoo - even if it's just some kind of metadata file or something.

No. You don't need to include any special metadata in a repo to be 100% Gentoo compatible.

> Ideally, when we tag a release, we can go through and update the version number in the spec file [...] That way, everyone that's building packages for Universal Ctags only has to clone the repo and run whatever script they'd normally run.

In Gentoo versioning info is derived from ebuilds (Gentoo's way to describe a package) written by package maintainers, not from the actual sources. Just choose any suitable, consistent way of versioning and you are ready for Gentoo.

**Comment by cweagans** [comment]
Okay, so it sounds like https://github.com/universal-ctags/ctags/issues/661 is actually the issue that we need to solve for Gentoo, then. I'm pushing for semver, but there should be buy in from the other maintainers.

I'm not sure about any automagic dependencies, so like I said, let us know about those things, and we'll make them more explicit.

**Comment by Coacher** [comment]
> Okay, so it sounds like #661 is actually the issue that we need to solve for Gentoo, then. I'm pushing for semver, but there should be buy in from the other maintainers.

Nice.

> I'm not sure about any automagic dependencies, so like I said, let us know about those things, and we'll make them more explicit.

Sure, once found in Gentoo, these kind of problems are usually reported back upstream. Thank you.

**Comment by blueyed** [comment]
FYI: it's in Arch Linux AUR already: https://aur.archlinux.org/packages/universal-ctags-git/

**Comment by cweagans** [comment]
@blueyed That's good to know, thanks.

Closing, since we don't have to do anything ourselves here. We'll make a release announcement on the website when we tag, so keep an eye out there for updates (https://ctags.io/)
