### ISSUE TITLE
How to test readtags.c?

### ISSUE THREAD

**Issue by ffes** [universal-ctags/ctags#685]
I am running into a problem with readtag.c

I use this in my notepad++ plugin but when run it on this file, it crashes my plugin.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/test/examples/x.cxx

readtags has a problem parsing the "M" tag that gets generated, most likely because of the "\" at the end of the search pattern. Note that this x.cxx file compiles just fine.

I am still struggling to build readtags.exe with any of the Windows compilers. So debugging the exact problem is a bit hard ATM, but I will get there :-)

I want to know if we have a way to test this readtags parser? If not, any thought how we can create proper tests for readtags?

**Comment by ffes** [comment]
I've built the readtags.exe

`ctags x.cxx` generates a tags file.
`readtags -l` gives a "Segmentation fault"

Will continue my investigation tomorrow evening. Will test on Ubuntu tomorrow as well.

**Comment by masatake** [comment]
We can use expected.tags files.

**Comment by masatake** [comment]
Now tmain can pass the path to readtags to run.sh script. So you can test readtags.
Coverages are not considered.
