### ISSUE TITLE
c++ 11 auto as a return type in functions

### ISSUE THREAD

**Issue by WscriChy** [universal-ctags/ctags#693]
When there is a function declaration/definition with auto as a return type ctags fails to recognize it.

**Comment by masatake** [comment]
Could you show a small example input?

**Comment by WscriChy** [comment]
auto process() -> void override;

**Comment by masatake** [comment]
I have to know the context where the example line you showed is used.

I tried following code and gcc -c accepts it.

```
class A
{
  virtual auto process () -> void;
};

class B:A
{
  auto process() -> void override;
};
```

In this case `process` should be tagged?

**Comment by WscriChy** [comment]
Do you see any reasons not to tag it?

**Comment by masatake** [comment]
Sorry, my question was wrong.
I wonder which token should be tagged: auto, process, void and/or override.
I read a boot about C++ and I understand process is the name ctags should capture.
I found more simple one.

```
auto f() -> void;
```
Here `f` should be captured.

**Comment by WscriChy** [comment]
Yes, `process` is the tag and the signature is `auto process()-> void`.

**Comment by masatake** [comment]
@WscriChy, I will try to add the code to tag it.

**Comment by WscriChy** [comment]
Hi @masatake . How is the progress do you need any help?

**Comment by masatake** [comment]
I'm soory but no visible progress. I'm learning c++ now.

**Comment by dawikur** [comment]
Hi @masatake, maybe you need any help with that?

**Comment by masatake** [comment]
@dawikur, we need your help. Could you join the testing and reviewing #824 ?
@pragmaware has rewritten C++ parser of ctags completely. I hope the new parser will solve this issue.

**Comment by pragmaware** [comment]
With the new parser this is easy :)
See https://github.com/pragmaware/ctags/commit/bd4aba3f750ac66115b895d3f56234b5d4f0cd00

**Comment by masatake** [comment]
Could you try the latest code?
The new parser is merge. I hope it fixes this issue.

**Comment by masatake** [comment]
The new C++ parser generates:
```
A	/tmp/foo.cpp	/^class A$/;"	c	file:
process	/tmp/foo.cpp	/^  virtual auto process () -> void;$/;"	p	class:A	typeref:typename:void	file:
B	/tmp/foo.cpp	/^class B:A$/;"	c	file:
process	/tmp/foo.cpp	/^  auto process() -> void override;$/;"	p	class:B	typeref:typename:void override	file:
```
My understanding is that the issue is solved.
If it is not solved yet, please, reopen this.
