### ISSUE TITLE
Failure in check() tests when building on Arch Linux

### ISSUE THREAD

**Issue by Jorick** [universal-ctags/ctags#703]
I'm maintaining an [AUR package for Arch Linux](https://aur.archlinux.org/packages/universal-ctags-git/)

Some users are experiencing failures in the tests run by check()
Output of the failed tests:
http://pastebin.com/3KpBm30u

I can't reproduce the errors on my machine nor in a virtual machine with a minimal Arch install. It doesn't seem to be a dependency problem or a problem with the PKGBUILD file.

**Comment by masatake** [comment]
Thank you for reporting the failures.
I will add feature reporting the detail of failures to the test harness.
Can I ask you to run "make check" again when I implement such feature?

BTW, I'm interested in the following part of output:
```
skipped (feature "coproc" is not available in /tmp/yaourt-tmp-pf/aur-universal-ctags-git/src/ctags/./ctags)
````

I wonder why coproc is not available on your environment.
Disabling explicitly when running configure?

**Comment by Jorick** [comment]
The build() function of the PKGBUILD script is the following:
```
build() {
  cd "${srcdir}/${_gitname}"
  autoreconf -vif
  ./configure --prefix=/usr \
              --libexecdir=/usr/lib \
              --sysconfdir=/etc
```
The flags in ./configure are required according to the Arch Linux package guidelines.

**Comment by 4e6** [comment]
I am able to reproduce the issue, flag `--prefix=/usr` is causing troubles. See attached logs for details:
[universal_ctags_fail.txt](https://github.com/universal-ctags/ctags/files/52735/universal_ctags_fail.txt)
[universal_ctags_success.txt](https://github.com/universal-ctags/ctags/files/52736/universal_ctags_success.txt)

**Comment by 4e6** [comment]
With `git bisect` I located the commit that introduced the issue: 3b32a9d91b50cad1dd89b09469a5cdce9283f9ec
```
# first bad commit: [3b32a9d91b50cad1dd89b09469a5cdce9283f9ec] main: remove tg related code
```
Another thing, `ctags --version` exit with the following message:
```
./ctags --version
ctags: Unknown option: --corpus-ctags
```

**Comment by masatake** [comment]
Installed version may affect on the result on the test. I will inspect this issue more.

**Comment by masatake** [comment]
Two sub issues are reported in this issue.
1. coproc is disabled unexpectedly.
2. tmain fauilure

To solve 2., run tmain with TRAVIS=1 locally.
```
$ make tmain TRAVIS=1
```
The test harness may report the diff of expected results and actual results.

**Comment by masatake** [comment]
My guessing is that after doing "make uninstall" or removing universal-ctags package in your system, make tinst or make check will work.

**Comment by masatake** [comment]
Try #709.

```
Failed tests
============================================================
disable-basic-field/stderr-compare
disable-basic-field/exit-compare
emacs-modeline-downcased-mode/stdout-compare
emacs-modeline-downcased-mode/stderr-compare
lxcmd-reject-specifying-in-dot-ctags/stderr-compare
lxcmd-reject-specifying-in-dot-ctags/exit-compare
nameless-long-option/stderr-compare
omit-long-patterns/stdout-compare
```

I expect other than lxcmd-reject-specifying-in-dot-ctags/stderr-compare and lxcmd-reject-specifying-in-dot-ctags/exit-compare will be fixed. I am locking for the way to fix the two.

**Comment by 4e6** [comment]
Yes, reinstall helped. But the idea that installed version can affect the current build seems somehow wrong to me.

**Comment by masatake** [comment]
@4e6, yes, you are right. In #709 I tried to fix them.

**Comment by Jorick** [comment]
I updated the package and will report back when I get info from the users.

**Comment by masatake** [comment]
With #614,  lxcmd-reject-specifying-in-dot-ctags/stderr-compare and lxcmd-reject-specifying-in-dot-ctags/exit-compare will be fixed. (I hope.)

**Comment by Jorick** [comment]
I received a confirmation that the package compiled without problems, thanks!

**Comment by masatake** [comment]
Thank you for reporting.

**Comment by evaryont** [comment]
I think I'm running into this error again. This is the only test that fails.

```
Testing lxcmd-reject-specifying-in-dot-ctags
------------------------------------------------------------
stdout                                                      passed
stderr                                                      failed (diff: /home/user/tmp/aur/universal-ctags-git/src/ctags/Tmain/lxcmd-reject-specifying-in-dot-ctags.d/stderr-diff.txt)
exit                                                        passed
```

```
--- /home/user/tmp/aur/universal-ctags-git/src/ctags/Tmain/lxcmd-reject-specifying-in-dot-ctags.d/stderr-actual.txt	2017-05-29 23:11:00.959868106 -0700
+++ ./Tmain/lxcmd-reject-specifying-in-dot-ctags.d/stderr-expected.txt	2017-05-29 23:06:01.563208759 -0700
@@ -1,14 +0,0 @@
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "static field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
-ctags: Warning: Don't reuse the kind letter `f' in a language coffee (old: "function", new: "field")
```

Oh, actually, it's some old configuration from an older version that didn't support xcmd in `~/.ctags`. Perhaps `--options=NONE` should be specified to prevent loading the configuration?

**Comment by masatake** [comment]
I know: https://github.com/universal-ctags/ctags/blob/master/Tmain/lxcmd-reject-specifying-in-dot-ctags.d/README

BTW, if you use `f` in as a name of kind in your .ctags, I recommend you not to use it. It is reserved.
In additin, using `f` for both `static field` and `field` is not good idea.
