### ISSUE TITLE
Process Multiple files with xcmd

### ISSUE THREAD

**Issue by bangroot** [universal-ctags/ctags#705]
Some external tag generators may be a bit more heavy-weight, but could lower the burden if they were allowed to process multiple files at once. For instance, I'm currently writing an external tags generator for universal-ctags to get better groovy support. Given that groovy already has AST support, I'm just implementing via a simple groovy script (see [here](https://github.com/bangroot/ctags-castle/blob/master/home/.ctags.d/drivers/groovytags) if you care).

My thought would be that the xcmd configuration could support something like `--xcmdb-groovy=groovytags` to represent that this xcmd supports batch processing (handle multiple file inputs). This way, existing xcmd implementations don't break.

**Comment by masatake** [comment]
This was really important pointing out. Thank you.
However, I removed xcmd feature from u-ctags.
