### ISSUE TITLE
Adding extra fields

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#715]
@b4n wrote in #713 

> BTW, I'd like to add b4n/geany@f481587 to u-ctags too, but currently it doesn't seem possible to report function return type: we don't have varType, and typeRef, while similar, is not really usable (as there is  nothing to put in typeRef[0], and it's required).

> I thought I remembered a discussion about this fields, but I can't seem to find it, so maybe I dreamed it.

**Comment by masatake** [comment]
I have thought about adding more fields. I wrote main/field.[ch] files for the purpose.
However, main/field.[ch] are not enough. tagEntryInfo must be extended for your purpose, as you wrote.

The concept "return type" is so popular among programming languages, so I think we should
add fields for storing it to tagEntryInfo. (If a field is not so popular, we should not extend it. In stead of we should a hashtable to tagEntryInfo. We can store a minor field to the hashtable.)

If you allow me, I would like to exntend tagEntryInfo to store returnType information and submit a PR here. In that case I would like you to review it. After merging my commit you can put your new code derived from  b4n/geany@f481587 on it.

I have more rather minor concerns about adding extra fields. I will write them later.

**Comment by masatake** [comment]
NOTE: Generally we don't have to care about the size of tagEntryInfo; even if it grows there is no impact.
The exception is a parser using cork. Cork keeps copies of all tagEntryInfo captured/created from an input source file to an array. We cannot ignore the size of the array when the number of copies increases.

**Comment by masatake** [comment]
See also #720.

**Comment by masatake** [comment]
Some ideas:

* "returnType:"
* "arity:"
* "entrypoint:" for main functions.
* "nameref:" or "alias:"
* "qufalified: for tags only recorded when `--extra=+q` is given

**Comment by b4n** [comment]
"return type" is nice, but it doesn't cover variable type, in e.g. C's `int foo`.  Actually, `varType` could be used if it allowed the first part (`varType[0]`) to be NULL/not given/whatever when the type is not a reference to a struct/enum/union (or not a known one at least, maybe a typedef).
I'm not sure this would be compatible with the current format though.

**Comment by masatake** [comment]
Introducing two new kinds "unknown" and "builtin" we can reuse the typeref field of tags file.

input.c
```
typedef struct X D;
int a;
struct B b;
C c;
D d;
char e (void);
```

```
a => a ... ;" typeref:builtin:int
b => b...  ;" typeref:struct:B
c => c...   ;" typeref:typedef:C
d => c...   ;" typeref:unknown:D
e => e...   ;" typeref:builtin:char
```

**Comment by pragmaware** [comment]
- The typeref extension fields is currently used only by C/C++ parsers.
- In the current form it's useful only for class/struct/union/enum data types. With other types
  the first part of the type must be "forged" and carries no information
- In C++ the class/struct/enum/union keywords are optional so generally there is no way to figure them out

Proposal:

Let's:
- change `typeref:A:B` format into `type:type_as_it_appears_in_the_sources`
- change the extension field from `char * typeRef[2]` into just `char * type`
- add a --cxx-typeref-compatible flag to make the the tag emitting function
  emulate the old typeref behaviour (by looking for an initial struct/enum/class/union
  keyword or just forging a "typename" in there)

In this way type: can be used for multiple purposes and maybe by other parsers too.

**Comment by masatake** [comment]
(I'm thinking about this....)

**Comment by masatake** [comment]
(I'm not sure I should report following here.)
I don't know well about C++. So I'm trying to find crazy input in C language.

```
float x (int y)
{
  return 0.5;
}

float (*return_x(void))(int)
{
  return x;
}

```

It is not an issue that the current parser doesn't handle `return_x` well because the input is crazy and it is possible that someone who really want to make a tag for it can fix the parser later.

I would like to think about tags output; how the output should be if we have an ideal C parser?
```
return_x	input.c	/^float (*return_x(void))(int)$/;"	kind:function	line:6	language:C	typeref:???	type:???	file:
```

The ability of a parser and file format is diffferent. The both are important. However, the former can be improved later.

**Comment by masatake** [comment]
@b4n, about function return type, how about padding  typeRef[0] with "typename" as proposed by @pragmaware ?
