### ISSUE TITLE
build on solaris 12 fails

### ISSUE THREAD

**Issue by tarzanek** [universal-ctags/ctags#721]
$ gmake
config.status: creating config.h
config.status: config.h is unchanged
[CC] ctags
Undefined                       first referenced
 symbol                             in file
GdbinitParser                       main/parse.o
CtagsParser                         main/parse.o
M4Parser                            main/parse.o
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
Makefile:165: recipe for target 'ctags' failed
gmake: *** [ctags] Error 1

**Comment by tarzanek** [comment]
@masatake it seems https://github.com/universal-ctags/ctags/commit/072b121e42420e20f9a657a3e1361f4d6f8896a0 broke it, can you have a look?

**Comment by tarzanek** [comment]
a Solaris 11.3 VM can be fetched here: 
http://www.oracle.com/technetwork/server-storage/solaris11/downloads/vm-templates-2245495.html

after that do pkg install autogen automake gcc
I did ./autorun.sh
then ./configure ...
and gmake

**Comment by tarzanek** [comment]
(pkg install git
if git won't be on the VM to clone the ws)
tia!
L

**Comment by tarzanek** [comment]
D'OH! 
ok, this was a mismerge it seems (though it's weird since I never touched those files ... )
after 
git checkout optlib/gdbinit.c optlib/m4.c optlib/ctags-optlib.c
gmake started to work again! :)

sorry for the bug, closing now

**Comment by masatake** [comment]
How about "make check" ?

**Comment by tarzanek** [comment]
@masatake 
so gmake worked for me, I tried :
$ gmake check
config.status: creating config.h
config.status: config.h is unchanged
./misc/units[1854]: local: not found [No such file or directory]
./misc/units[1856]: local: not found [No such file or directory]
./misc/units[1857]: local: not found [No such file or directory]
./misc/units[1751]: local: not found [No such file or directory]
./misc/units[1752]: local: not found [No such file or directory]
./misc/units[1753]: local: not found [No such file or directory]
./misc/units[1754]: local: not found [No such file or directory]
./misc/units[1756]: local: not found [No such file or directory]
./misc/units[1757]: local: not found [No such file or directory]
./misc/units[1758]: local: not found [No such file or directory]
./misc/units[1760]: local: not found [No such file or directory]
./misc/units[1761]: local: not found [No such file or directory]
./misc/units[1763]: local: not found [No such file or directory]
./misc/units[1764]: local: not found [No such file or directory]
./misc/units[1765]: local: not found [No such file or directory]
./misc/units[1767]: local: not found [No such file or directory]
makefiles/testing.mak:98: recipe for target 'tmain' failed
gmake: *** [tmain] Error 1

is above expected?

**Comment by b4n** [comment]
@tarzanek no, it looks odd, like your shell doesn't support `local`, which I thought was a POSIX feature.  Should work with `gmake check SHELL=/bin/bash` or alike; but it'd be interesting to know what shell this is and if using `local` really is that unportable (Debian's `dash` supports it though).

**Comment by masatake** [comment]
I really don't want to remove "local". Please, install bash or something rich shell.

**Comment by tarzanek** [comment]
shell is zsh ;)

**Comment by tarzanek** [comment]
after using the gmake check SHELL=/bin/bash
I get still some diff errors (actually plenty of them)
......
Testing xcmd-dont-run-setuid-executable
------------------------------------------------------------
skipped (feature "" is not available in )

Testing xcmd-for-unknown-language
------------------------------------------------------------
stdout                                                      failed (diff: /tank/hudson/universal-ctags/Tmain/xcmd-for-unknown-language.d/stdout-diff.txt)
stderr                                                      failed (diff: /tank/hudson/universal-ctags/Tmain/xcmd-for-unknown-language.d/stderr-diff.txt)
exit                                                        failed (diff: /tank/hudson/universal-ctags/Tmain/xcmd-for-unknown-language.d/exit-diff.txt)
......

and I end up in error anyways 
makefiles/testing.mak:98: recipe for target 'tmain' failed
gmake: *** [tmain] Error 1

I guess try Solaris in that VM, for dev purposes you can keep it. Solaris should be posix for sure (ksh93 should be).
ZSH was a surprise for me ...

**Comment by masatake** [comment]
> Testing xcmd-dont-run-setuid-executable
> ----
> skipped (feature "" is not available in )

Looks strange. An empty string should not be passed to feature verification stage.
Could you tell me the version of bash?

> Testing xcmd-for-unknown-language
> ...

Could you send me(masatake@gmail.com) a tar archive of ctags source directory after running "gmake check SHELL=/bin/bash" ?

(I'm not sure I can receive such large file via gmail.)

**Comment by tarzanek** [comment]
am on
commit 91c0d475c4a7c74e70a37fa472122639fb1d077e
Merge: 1421dfa 9aba9d0
Author: Masatake YAMATO <masatake@gmail.com>
Date:   Fri Feb 19 18:11:35 2016 +0900

    Merge pull request #799 from masatake/fix-797-add-catch-as-keyword
    
    Java: add catch as a keyword

**Comment by tarzanek** [comment]
and now 
./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
/usr/share/aclocal/aalib.m4:12: warning: underquoted definition of AM_PATH_AALIB
/usr/share/aclocal/aalib.m4:12:   run info Automake 'Extending aclocal'
/usr/share/aclocal/aalib.m4:12:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:122: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by tarzanek** [comment]
this used to work ;)
any clues? (the env is still the same, S12, zsh, versions of autotools:
pkg list | grep auto
developer/build/autoconf                          2.69-5.12.0.0.0.92.1       i--
developer/build/autogen                           5.16.2-5.12.0.0.0.92.1     i--
developer/build/automake                          1.15-5.12.0.0.0.92.1       i--
developer/build/automake-111                      1.11.2-5.12.0.0.0.92.1     i--
developer/build/automake-115                      1.15-5.12.0.0.0.92.1       i--
)

**Comment by tarzanek** [comment]
@masatake got any clues what happened? (I didn't follow all the changes in repo for past 2 months)

**Comment by tarzanek** [comment]
OK, my fault
sudo pkg install pkg-config
solved the issue

**Comment by tarzanek** [comment]
I guess we can close this issue, no?

**Comment by tarzanek** [comment]
actually let's close it, if you want to follow up on any other thing @masatake then let's do it in new thread.
tia
L
