### ISSUE TITLE
false positives when --java-kinds=+l used

### ISSUE THREAD

**Issue by tarzanek** [universal-ctags/ctags#722]
Try to get tags with "--java-kinds=+l " from:

```java
/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2008, 2010, Oracle and/or its affiliates. All rights reserved.
 */

package org.opensolaris.opengrok;

import java.util.Date;
import java.util.logging.Formatter;
import java.util.logging.LogRecord;

/**
 * Opengrok logfile formatter
 * Creates a logentry in the logfile on the following format
 * [#|YYYY-MM-DD HH:MM:ss.SSSZ |<loglevel>|<version>|OG|T=<threadnumber>|
 * <Class.method>: <logmessage> |#]
 * @author Jan S Berg
 */
final public class FileLogFormatter extends Formatter {
   
   private final java.text.SimpleDateFormat formatter =
      new java.text.SimpleDateFormat("yyyy-MM-dd' 'HH:mm:ss.SSSZ");
   private static final String lineSeparator = System.
      getProperty("line.separator");
   
   private String ts(Date date) {
      return formatter.format(date);
   }
   
   private String classNameOnly(String name) {
      int index = name.lastIndexOf('.') + 1;
      return name.substring(index);
   }
   
   public String format(LogRecord record) {
      StringBuilder sb = new StringBuilder();
      sb.append("[#|");
      sb.append(ts(new Date(record.getMillis())));
      sb.append(" |");
      String loglevel = record.getLevel().getName();
      sb.append(loglevel);
      sb.append("|");
      sb.append("V");
      sb.append(Info.getVersion());
      sb.append("|OG|");
      sb.append("T=");          
      sb.append(record.getThreadID());
      sb.append("| ");  
      sb.append(classNameOnly(record.getSourceClassName()));
      sb.append('.');
      sb.append(formatMessage(record));
      sb.append(": ");
      sb.append(record.getMessage());
      Throwable thrown = record.getThrown();
      if (null != thrown) {
         sb.append(lineSeparator);
         java.io.ByteArrayOutputStream ba=new java.io.ByteArrayOutputStream();
         thrown.printStackTrace(new java.io.PrintStream(ba, true));
         sb.append(ba.toString());
      }
      sb.append(" |#]");
      sb.append(lineSeparator);
      return sb.toString();
   }
}
```

------
you will end up with more than 3 methods in tags. So local variables are not really usable for java parser. Since it's 2015, it'd be nice if it would be fixed, anyone who knows that parser and can fix it?

**Comment by masatake** [comment]
```
[yamato@x201]~/var/ctags-github% cat Units/parser-java.r/wrong-method-recognition-with-local-kind.b/input.java 
cat Units/parser-java.r/wrong-method-recognition-with-local-kind.b/input.java 
class A {
    void b () {}
    void c () { b (); }
}
[yamato@x201]~/var/ctags-github% git diff |cat
git diff |cat
diff --git a/parsers/c.c b/parsers/c.c
index 8c4a802..0fbe195 100644
--- a/parsers/c.c
+++ b/parsers/c.c
@@ -3244,7 +3244,7 @@ static void tagCheck (statementInfo *const st)
 			{
 				if (st->isPointer)
 					qualifyVariableTag (st, prev2);
-				else
+				else if (!st->inFunction)
 					qualifyFunctionDeclTag (st, prev2);
 			}
 			if (isInputLanguage (Lang_java) && token->type == TOKEN_SEMICOLON && insideEnumBody (st))
[yamato@x201]~/var/ctags-github% ./ctags -o - --sort=no --kinds-java=+l Units/parser-java.r/wrong-method-recognition-with-local-kind.b/input.java 
<nds-java=+l Units/parser-java.r/wrong-method-recognition-with-local-kind.b/input.java 
A	Units/parser-java.r/wrong-method-recognition-with-local-kind.b/input.java	/^class A {$/;"	c
b	Units/parser-java.r/wrong-method-recognition-with-local-kind.b/input.java	/^    void b () {}$/;"	m	class:A
c	Units/parser-java.r/wrong-method-recognition-with-local-kind.b/input.java	/^    void c () { b (); }$/;"	m	class:A
```

**Comment by masatake** [comment]
We cannot fix this well.
parsers/c.c is one the most complicated area of ctags. c, c++, java, c#, D and vera parsers share the code.
A fixing for a parser may break other parsers.

Generally we expect test cases prevent such breaking.  We don't have verified test cases about java.
Under Unites/review-needed.r, there are not a few test cases of java. However, the test cases are not verified yet.

https://github.com/universal-ctags/ctags/issues/361

This situation is applicable to https://github.com/universal-ctags/ctags/issues/693 .
I will slowly verify the test cases. However, it takes. The latest results are https://github.com/universal-ctags/ctags/pull/718 .

**Comment by tarzanek** [comment]
hmm, I have a bad feeling you might need to break the shared code, Java 8 is now somewhere, where c/c++/c# will never be and I think this divergence will be bigger over time, makes no sense to share code anymore imho ...

**Comment by tarzanek** [comment]
also I think support for java8 isn't in, is it?

**Comment by masatake** [comment]
I'm not sure what is the best way. The obvious thing is that I have to understand c.c well and learn C++, C#, D, Java adn Vera to improve one of the parser.  Reviewing the test cases is good way to learn the languages.

**Comment by tarzanek** [comment]
I usually learn languages by reading their specs/docs, e.g. for java it'd be  http://docs.oracle.com/javase/specs/index.html
it gives you nice overview of lexical and semantical analysis
for ctags obviously second part is the key
then a good thing is to look at compilers of those languages, ev. study it the way IDEs do (like Idea, which besides compiling can do ASTs)
ASTs might be a nice way how to get info fast and correct - https://en.wikipedia.org/wiki/Abstract_syntax_tree
or Idea has a tool to build support for any language - http://blog.jetbrains.com/idea/2013/01/how-to-write-custom-language-support-plugins/

**Comment by pragmaware** [comment]
java / C++ / D / Vera / whatever parsers should be split in separate files.
They would become simpler and one would not have to be afrait to break some other language when fixing one of them. As a starting point it's just a matter of copying parsers/c.c N times and adjusting the parser definitions.

**Comment by masatake** [comment]
Splitting is really good?


Rather I'm thinking about introducing "inheritance" in parser implementations.
```
Parser
   ParserForBraceParenOrientedLanguage
     C
     C++
     Java
      ...
```

I think the complexity comes from isInputLanguage.
The use of isInputLanguage can be reduced with per language virtual function table.

**Comment by pragmaware** [comment]
Well... maybe a set of common functions would be useful. But that's harder to do in a single run.
Splitting could be a first step. Then one would try to gather the commons.

The fact is that in its actual state the c.c parser is unmantainable. You can't be sure that
you're fixing things if you don't know all of the languages involved. And even if you know
them you still usually focus on a single language when trying to fix something.

The languages this parser handles are similar at the general level but differ greatly
in the details.

**Comment by masatake** [comment]
@pragmaware, I have a big question; do you have an interest doing splitting by yourself?

**Comment by masatake** [comment]
@tarzanek, could you try the latest master?
(I merged improvements from @pragmaware.)

**Comment by tarzanek** [comment]
@masatake confirming, the tests now work, I can add local variables to java for OpenGrok if universal ctags will be detected!
sweet!
(I will still review @pragmaware code, which pull req was it? )

**Comment by tarzanek** [comment]
I just found https://github.com/universal-ctags/ctags/pulls?q=is%3Apr+author%3Apragmaware+is%3Aclosed
and it looks ok to me ... so in the end no splitting was done?

**Comment by masatake** [comment]
@tarzanek, thank you for testing. I merged @pragmaware' s work ago.
No splitting. Before splitting I would like to do

(1) review all the C/C++/Java/D/C#/Vera test cases under Units/review-needed.r,
(2) change the interface between main and parsers; currently just a language id is passed to a parser.
      I'm thinking about passing a parserDefinition instead of language id.

However, it takes longer time; I have to work on releasing 1.0.0 and implementing xpath meta parser which I need my daily job...

**Comment by tarzanek** [comment]
np, thank you for your hard work @masatake & @pragmaware 
appreciate that people take care about ctags, so they are back from dead
& looking forward to 1.0.0 !
I think OpenGrok will switch immediately (my opengrok test farm is completely on universal ctags for past few months and besides these java kinds all looks well)

**Comment by pragmaware** [comment]
@masatake  About the splitting: I'm working on https://github.com/pragmaware/ctags/tree/new-cpp-parser which is a C/C++ parser written from scratch. Obviously separated from the old one.
It still needs some work/cleanups but it's already generally more correct and foolproof than the old one.
It can even report new kind of data, like "using" statements. Other interesting and possibile additions are termination position of code blocks (so editors know where functions / class names / namespaces end), types of variables, return types of functions etc. Take a look when have some time.

**Comment by masatake** [comment]
Great job.

I strong belive you will accept my invitation to join u-ctags organization as a maintainer of this parser.

Fell free to make a draft PR, so you can utilize u-ctags CI infrastructure.

If possible. please fix #735 in your parser.
I think using kind can be enable by default.
I would like to consider introducing reference tags for callees in a caller.
e.g.
```
int f () { g () ; }
```
Here `g` can be tagged as reference. Its role may be callee and scope is `function:f`.

I also want you to capture parameters of function. New kind parameter can be defined here.

When merging your code we have torchange the prefix `cpp` used in get.c.

> Other interesting and possibile additions are termination position of code blocks
How do you represent it on tags file?
It is not only about C++ but also applicable to the all language.

My idea is introducing language NONE, which is virtual language
```
int foo (void)
{
}
```
->
```
foo input pattern;"  language:C kind:function line:28 ...
foo input pattern;" language:NONE kind:endmarker line:32 ...
```
I'm not sure this is the best.

**Comment by pragmaware** [comment]
> I strong belive you will accept my invitation to join u-ctags organization as a maintainer of this parser.

Agreed :)

Though my parser still needs some work. I will work on it in the weekend.

> If possible. please fix #735 in your parser.

Anonymous structures/classes/enums are already caught by this parser
(not sure if all of them, but the code is supposed to do it).

> I would like to consider introducing reference tags for callees in a caller.

Interesting. I'll think about it.

> I also want you to capture parameters of function. New kind parameter can be defined here

Yep. They're a lot like local variables.

> When merging your code we have torchange the prefix cpp used in get.c.

Hm.. well'that code (in get.c) is cpp specific too, or I'm wrong?

>>Other interesting and possibile additions are termination position of code blocks
> How do you represent it on tags file?

foo   input pattern;"   language:C   kind:function line:28   ends:47
bar   input pattern;"   language:C++ kind:class line:67  ends:145

This requires emitting tags when the scope terminator is found and not when the symbol itself is found but I've been thinking to use the "cork" feature for that.

**Comment by masatake** [comment]
The prefix cpp in  get.c means C preprocessor. It is used in some areas in parsers/*.c.
I will change the prefix the cprepro or something.

> foo input pattern;" language:C kind:function line:28 ends:47
> bar input pattern;" language:C++ kind:class line:67 ends:145

Oh, I see. Looks better than my idea. xtag.h is for you.
@b4n is our parser expert, so he will give some comments.

**Comment by masatake** [comment]
Oh, it seems that you are kde hacker.
Feel free to add code for capturing slots and sockets.

**Comment by b4n** [comment]
> The prefix cpp in get.c means C preprocessor. It is used in some areas in parsers/*.c.
> I will change the prefix the cprepro or something.

I'd rather not, "cpp" is generally accepted to mean "C preprocessor", and C++ use "cxx" in context where both could appear (`CPPFLAGS` vs. `CXXFLAGS`, `CPP` vs. `CXX`, etc.).

> @b4n is our parser expert, so he will give some comments.

I'll try.
On thing right away: it's great thing working on new (or cleaned up would have worked, but whichever) C and C++ parsers, because the current state is basically impossible to maintain.  I'm not certain combining the C and C++ ones is so much of an awesome idea nowadays with the various complex new C++11/14 things though, but if it really works and is not too much of a hassle, maybe.  Just beware that C and C++ have at least a different keyword set: we need not get fooled by a `template` or `class` identifier in C.
Also, I've got one fear: support for macros.  It's technically *impossible* to really correctly parse C or C++ code that uses macros in some subtle ways with the partial knowledge CTags has, and the current C and C++ parser has ages of crazy tweaks to give good results on most inputs.  So I'm afraid here of all the possible breakage due not to incorrect, but different, handling regarding weird input resulting from macros.  BTW, in this area current parser has `isIgnoreToken()` to allow the user to skip some macros that would make too much trouble.
However, I would hope our test suite is a good start not to break stuff, and possibly try parsing the Linux kernel tree, which was a common thing to test e-ctags C parser against.

**Comment by pragmaware** [comment]
OK. I'll switch to cxx prefix then.

As for C/C++ separation I have used the trick from the previous parser: the keywords recognized depend on the language. It's already there but I still have to test it. For now concentrating on C++ as C is a subset of it.

I'll try to add some magic in order to figure out common macro cases (and will take a look at isIgnoreToken to get the good out of it).

**Comment by masatake** [comment]
I have much time to read Java source code. As the result I got some experience as a ctags user.
constructors and destructors kinds may be useful.

**Comment by tarzanek** [comment]
caller callee reference would be lovely!
