### ISSUE TITLE
Makefile.am should not use "transform_name" for drivers

### ISSUE THREAD

**Issue by jonthn** [universal-ctags/ctags#753]
If you use ```--program-prefix``` with the current configure script you end up installing libexec/drivers/${program_prefix}coffeetags instead of libexec/drivers/coffeetags

For example if you use : 
```
./configure --program-prefix=ex
```
it will install libexec/drivers/excoffeetags

A possible fix below that will install the scripts as DATA and it's only required to make the data executable

```
--- Makefile.am.orig	2016-01-06 22:42:10.000000000 +0000
+++ Makefile.am
@@ -57,7 +57,10 @@ man_MANS = ctags.1
 
 if ENABLE_XCMD
 driversdir = $(pkglibexecdir)/drivers
-dist_drivers_SCRIPTS = libexec/drivers/coffeetags
+dist_drivers_DATA = libexec/drivers/coffeetags
+
+install-data-hook:
+	chmod +x $(DESTDIR)$(pkglibexecdir)/drivers/coffeetags
 endif
 
 if INSTALL_ETAGS
```

**Comment by masatake** [comment]
I'm working on this. I found extra bugs during fixing.

**Comment by masatake** [comment]
@jonthn, could you try #762?

When  --program-prefix=ex is given in building ctags, optlib2c generates code which makes ctags refer
/usr/local/libexec/ctags/drivers/excoffeetags.

Installing the coffeetags driver to  /usr/local/libexec/exctags/drivers/coffeetags is better, but I want to keep Makefile.am simple.

**Comment by jonthn** [comment]
@masatake Thanks for working on this. I just gave #762 a try and it solves the issue for me.

**Comment by masatake** [comment]
@jonthn, thank you for testing.
