### ISSUE TITLE
Python parser doesn't output all tags

### ISSUE THREAD

**Issue by m-novikov** [universal-ctags/ctags#763]
After the latest changes to python parser https://github.com/universal-ctags/ctags/pull/751
Parsing file with following contents
```python
def foo():
    var = some1(some2())

def bar():
    pass
```
will not give tags for anything after the line ```var = some1(some2())```
Any signatures that contain inside parenthesis will also break parser
```python
def foo(arg1, arg2=()):
    pass
```
and
```python
var = test(())
```

**Comment by masatake** [comment]
Thank you for reporting this. I will try to fix it.

**Comment by masatake** [comment]
@m-novikov, could you try #764 ?

**Comment by m-novikov** [comment]
It's working.
Found one more thing related to https://github.com/universal-ctags/ctags/pull/751
Function call with keyword arguments
```
foo(
    arg1=1,
    arg2=2
)
```
Will produce following
```
arg1	test.py	/^    arg1=1,$/;"	v
arg2	test.py	/^    arg2=1$/;"	v
```

**Comment by masatake** [comment]
@m-novikov, new bug you found may be reproduced even in ctags befre introducing the change of #751.
In other word it is different bug. #764 I wrote today is for fixing a bug introduced in #751.

Do I make sense?

**Comment by m-novikov** [comment]
Yes, thank you.
I will create new issue on this.

**Comment by masatake** [comment]
@m-novikov, thank you for opening a new issue.
