### ISSUE TITLE
Python mult-iline keyword arguments it tag file

### ISSUE THREAD

**Issue by m-novikov** [universal-ctags/ctags#765]
Follow up to https://github.com/universal-ctags/ctags/issues/750
Function calls with multi-line keyword arguments results in keyword arguments parsed as variables
Given
```Python
foo(
    arg1=1,
    arg2=2
)
def bar():
    pass
```
Getting following tags
```
arg1    test.py /^    arg1=1,$/;"       v
arg2    test.py /^    arg2=1$/;"        v
bar     test.py /^def bar():$/;"        f
```
Expected output is
```
bar     test.py /^def bar():$/;"        f
```

**Comment by masatake** [comment]
Could you try #767 ?

**Comment by m-novikov** [comment]
Yes it's working, thank you.
