### ISSUE TITLE
MSYS support

### ISSUE THREAD

**Issue by adoxa** [universal-ctags/ctags#768]
With the inclusion of `PKG_CHECK_MODULES` (for libxml), autoconf no longer works with MSYS, as `pkg-config` is not supplied (but is available from other sources). MSYS also breaks command line arguments like `/pattern/`, with apparently no way to override it (having to use `//pattern\\` instead), affecting the tests. Is there still an interest in supporting MSYS, or is it time to move on and just use MSYS2?

**Comment by k-takata** [comment]
I consider MSYS1 is almost dead.
If someone still wants to use MSYS1, he should use `mk_mingw.mak`, not Autotools.
In contrast, MSYS2 provides libiconv, jansson, libxml2 and libyaml packages, so it is very easy to enable these features using Autotools on MSYS2.
