### ISSUE TITLE
ctags is unable to recognize less-than sign in templates.

### ISSUE THREAD

**Issue by Shihira** [universal-ctags/ctags#769]
```
void func0() { }
template<int i, bool b = i < 10> void func() { }

void func1() {}
void func2() {}
void func3() {}
void func4() {}
int main() {}
```

It's clear that this piece of code can be compiled with success in a real compiler, but when parsing it using ctags I got an almost empty tag file, namely I lost all functions that follow `func()`:

```
$ ctags -f- test.cc
func0	test.cc	/^void func0() {}$/;"	f
```

**Comment by masatake** [comment]
Thank you for reporting. Could you try  #772?
