### ISSUE TITLE
Using a C++11 style trailing return types with universal-ctags

### ISSUE THREAD

**Issue by hgiesel** [universal-ctags/ctags#771]
I noticed that universal-ctags (like exuberant-ctags) doesn't work with C++11 style trailing return types. Is there a reason for that?

**Comment by masatake** [comment]
Becuase none has not worked on the area.
I'm learning C++-11 but its language spec is too large for me.

**Comment by masatake** [comment]
This is the same as #693?

**Comment by hgiesel** [comment]
The question implies something else, but yes it is. I will close this issue then.
