### ISSUE TITLE
python: ignores tags after (certain) doc quotes 

### ISSUE THREAD

**Issue by blueyed** [universal-ctags/ctags#781]
```
% cat /tmp/t.py
class Foo():
    bar=dedent("""
               baz
               """)


class Bar():
    pass


% ctags -f - /tmp/t.py
Foo	/tmp/t.py	/^class Foo():$/;"	c	language:Python
bar	/tmp/t.py	/^    bar=dedent("""$/;"	v	language:Python	class:Foo
```

`Bar` is missing.

This is possibly related to the code at https://github.com/universal-ctags/ctags/blob/master/parsers/python.c#L1110-L1118 and/or https://github.com/universal-ctags/ctags/blob/master/parsers/python.c#L866.

**Comment by blueyed** [comment]
Submitted a test case at https://github.com/universal-ctags/ctags/pull/784.

**Comment by blueyed** [comment]
@masatake 
Is this on your radar?
Otherwise I will consider looking into it, given that this causes a fair amount of tags to be missed in certain projects.

**Comment by masatake** [comment]
Though I solved the original issue, I didn't make s pull request because I found another bug releated to the area.

Could you look at #869? 
The fix is not clean enough. I think we need more token oriented parser for solving all the issues.
