### ISSUE TITLE
Build problem on OpenBSD

### ISSUE THREAD

**Issue by jockej** [universal-ctags/ctags#794]
I'm trying to build on OpenBSD, but it turns out that all the .c files in the optlib directory are empty, which of course means that linking fails with unresolved dependencies. I think this has something to do with the face that the optlib2c script seems to be a bash-script, and I don't have bash installed (and even if I installed it it wouldn't be /bin/bash but /usr/local/bin/bash).

So I guess somehow the shell command which is supposed to create the .c files from the .ctags files somehow gives empty output, which is then echoed to the .c files creating empty files.

I fixed now it by changing the shebang in misc/optlib2c to !#/usr/local/bin/zsh, but it took me a while to figure this out :)

Maybe there should be a check in ./configure for a reasonably "bashy" shell?

**Comment by masatake** [comment]
optlib2c is run in autogen.sh, which is run before configure is run.
Could you try #795?

**Comment by masatake** [comment]
Sorry, I misunderstood my code. BASH is needed; configure verifies its existence.
```
AC_CHECK_PROGS([BASH], [bash])
if ! test "${BASH+set}" = "set"; then
   AC_MSG_ERROR([bash is needed to run optlib2c translator])
fi
```

**Comment by jockej** [comment]
Well, this is embarrasing... Turns out I have bash installed. But it was installed as /usr/local/bin/bash, so I guess that's why the script failed. So maybe just change the shebang to #!/usr/bin/env or something?

But, well, seems it works with zsh as well :)

Anyway, sorry for my stupidity. It never occurred to me I could have bash installed....

**Comment by jockej** [comment]
change the shebang to #!/usr/bin/env bash of course. But maybe it could be nice to allow those who do not have bash installed but something compatible to build as well. Bash is a pretty massive dependency.

Thanks for your time!

**Comment by masatake** [comment]
Could you try #796?
If bash is not avaiable, pre-translated C code is used for building ctags.
I don't want to debug C code generated by optlib2c interpreted by zsh.

**Comment by jockej** [comment]
I tried it, but I found another problem, which I of course should have found sooner. In OpenBSD there is no seq(1) command. So maybe there should be a check for that as well. This leads me to believe that while I succeeded in building and installing ctags before, the program might not actually be correct... which I guess is worse than just not linking.

**Comment by vhda** [comment]
@masatake I've said this before: why don't we keep the conversion script as an auxiliary script that developers can use while **initially** importing the code to C? After that developers simply maintain the C code, avoiding an extra dependency on bash.

**Comment by masatake** [comment]
I think we should not maintain machine generated files if its original source files are available.
For example we should not maintain configure script. Maintaining configure.ac is better.
I think you agree with me about this point. Should we maintain the configure script to remove the 
extra dependency on autoconf? I don't think so. I don't want to read machine generated files.

The issue may be the extra dependency on bash.  I myself don't care about such build time depedency.
Further more generated C files are in git repository. The issue reported by @jockej just sports the bugs in our build system. I will fix it.

If you accept autotools, there is a way: rewriting optlib2c in perl. Automake uses perl. So adding scripts written in perl to our build-process doesn't add any extra dependency.

There are more reason not to maintain generated code. ctags internal PPI(parser programmer interface) exported from main will be changed rapidly. If there are so many generated C files,
updating them will be hard task.

I would like to do more in optlib2c, so rewriting it in perl is good idea, though I don't know perl.

I will work on rewriting it in perl if an expart of perl helps me. @dtikhonov, can I ask you to review my code?

**Comment by masatake** [comment]
@jockej, I will add seq(1) to the check list. How about other command?
As I wrote I will rewrite optlib2c in perl. I believe you are using autotools for building ctags.
When the new optlib2c is avaiable, we can throw away the check list.
However, I don't know perl so the rewriting will take time.
So I would like to maintain the checklist in configure.ac and autogen.sh in a parallel way.

**Comment by dtikhonov** [comment]
> I will work on rewriting it in perl if an expart of perl helps me. @dtikhonov, can I ask you to review my code?

@masatake , with pleasure.

**Comment by masatake** [comment]
@jockej, Please, try #804.

@dtikhonov, could you look at #804. It generates the same output of bash version.
I would like you to check my code follows "perl way" well or not.

**Comment by dtikhonov** [comment]
> @dtikhonov, could you look at #804. It generates the same output of bash version. I would like you to check my code follows "perl way" well or not.

Looks great, @masatake!  (I did not run it, just read through it.)

Perl is not like some other languages in that it does not have One True Way&trade; -- it's motto is "There Is More Than One Way To Do It."

The only thing I've noticed is superfluous code on lines 39-41, where three subroutines are declared.  Since the subroutines are called with parentheses (on line 100, for example), the subroutine declarations won't do anything and the compiler won't complain if you make a typo.  You can simply remove the declarations.

**Comment by jockej** [comment]
@masatake I tried it. There seems to be a typo in autogen.sh, I'm guessing the condition should be: if verify_oplib2c_requirements on line 12?

If I run autogen.sh as it is it says: can_run_oplib2c not found, and then uses the pre-translated files. However I too the liberty of changing from can_run_optlib2c to verify_optlib2c_requirements and then it runs fine and translates the .ctags files and compiles without problem.

I'm not sure you need to check for perl. Doesn't autmake require it anyway since you don't ship a configure script?

Either way it seems to work now. I tried running 'make check' but every test failed, but this seems to be because the option 'strip-trailing-cr' isn't recognized by OpenBSD diff(1). I will check into it a bit more and maybe open another issue about that.

Thanks for working on this! It's nice to get support for OpenBSD.

**Comment by masatake** [comment]
Thank you both.
I've updatd the pull request based on the comments.

**Comment by jockej** [comment]
I've pulled the new version and tried it. It seems to work just fine :)

**Comment by masatake** [comment]
Thank you for verifying.
