### ISSUE TITLE
Syntax errors in tagXPathTable initializations: ant.c, dbusintrospect.c, glade.c, maven2.c

### ISSUE THREAD

**Issue by acarlson1029** [universal-ctags/ctags#798]
Tried to compile with the latest today and ran into the following issue.

The `tagXpathTable` structs being initialized have a minor syntax error:
```c
static tagXpathTable antXpathProjectTable [] = {
    { "target",
      LXPATH_TABLE_DO_RECUR,
      .recurSpec= {
            antFindTagsUnderTask
        }
    },
    { "property/@name",
      LXPATH_TABLE_DO_MAKE,
      .makeTagSpec = {
            K_PROPERTY, ROLE_INDEX_DEFINITION,
            makeTagWithScope,
      }
    },
    { "import/@file",
      LXPATH_TABLE_DO_MAKE,
      .makeTagSpec = {
            K_IMPORT, R_IMPORT_GENERIC,
            makeTagWithScope,
      }
    },
};
```

Where the struct is defined in `path.h` as
```c
typedef struct sTagXpathTable
{
    const char *const xpath;
    enum  { LXPATH_TABLE_DO_MAKE, LXPATH_TABLE_DO_RECUR } specType;
    union {
        tagXpathMakeTagSpec makeTagSpec;
        tagXpathRecurSpec   recurSpec;
    };
    xmlXPathCompExpr* xpathCompiled;
} tagXpathTable;
```

The third argument here is a union, but the initializers are missing the curly braces.
```c
static tagXpathTable antXpathProjectTable [] = {
    { "target",
      LXPATH_TABLE_DO_RECUR,
      { .recurSpec= {
            antFindTagsUnderTask
        }
      }
    },
    { "property/@name",
      LXPATH_TABLE_DO_MAKE,
      { .makeTagSpec = {
            K_PROPERTY, ROLE_INDEX_DEFINITION,
            makeTagWithScope,
        }
      }
    },
    { "import/@file",
      LXPATH_TABLE_DO_MAKE,
      { .makeTagSpec = {
            K_IMPORT, R_IMPORT_GENERIC,
            makeTagWithScope,
        }
      }
    },
};
```

This affects the following files:
 * ant.c
 * dbusintrospect.c
 * glade.c
 * maven2.c

Patch attached.

[0001-Fix-syntax-errors-when-initializing-union-attributes.txt](https://github.com/universal-ctags/ctags/files/137159/0001-Fix-syntax-errors-when-initializing-union-attributes.txt)

**Comment by masatake** [comment]
Thank you for reporting this.
My understanding is that this is an issue about building ctags, not about runnning ctags.
Am I correct?
(If yes, ), could you tell me the environment where you built ctags.

Can I ask you to make a pull request for 0001-Fix-syntax-errors-when-initializing-union-attributes.txt ?
So I can merge the change easily.

Thank you again.

**Comment by acarlson1029** [comment]
> My understanding is that this is an issue about building ctags, not about running ctags.
Am I correct?

Correct, I encountered this while building.

Let me know what environment info you're looking for. Off the top of my head --
- VM is running CentOS 5.7
- GNU Make 3.81
- autoconf (GNU Autoconf) 2.69
- automake (GNU Automake) 1.15
- gcc (GCC) 4.2.1

**Comment by masatake** [comment]
Thank you.

gcc 4.9.2 accepts the syntax... I wonder the standard used as default syntax in gcc is changed.
I would like to know it because I like my original notation. I should know where/when I can/cannot use it.

**Comment by masatake** [comment]
How about removing 
```
- union {
```
and associated  
```
},
```
?

So the structure definition changed to 
```
typedef struct sTagXpathTable
{
    const char *const xpath;
    enum  { LXPATH_TABLE_DO_MAKE, LXPATH_TABLE_DO_RECUR } specType;
    /* explanation here */
    tagXpathMakeTagSpec makeTagSpec;
    tagXpathRecurSpec   recurSpec;

    xmlXPathCompExpr* xpathCompiled;
} tagXpathTable;
```.

It wastes the memory resource a bit. However, tagXpathTable variables are uesd only limited place.
Do you think this is bad idea?

**Comment by masatake** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Unnamed-Fields.html

**Comment by masatake** [comment]
I thought about this again.
My approach I wrote here was a bit tricky. In stead I will use named union:

```
typedef struct sTagXpathTable
{
    const char *const xpath;
    enum  { LXPATH_TABLE_DO_MAKE, LXPATH_TABLE_DO_RECUR } specType;
    union {
        tagXpathMakeTagSpec makeTag;
        tagXpathRecurSpec   recur;
    } spec;
    xmlXPathCompExpr* xpathCompiled;
} tagXpathTable;
```

**Comment by masatake** [comment]
Fixed by your patch. Thank you.
