### ISSUE TITLE
optlib generates files that won't work in compilation

### ISSUE THREAD

**Issue by tarzanek** [universal-ctags/ctags#800]
hmm, so in the end my env is still weird
S12, same env as in #721 
I do 
./autogen.sh
./configure
gmake
and:
Undefined                       first referenced
 symbol                             in file
GdbinitParser                       main/ctags-parse.o
CtagsParser                         main/ctags-parse.o
M4Parser                            main/ctags-parse.o
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
Makefile:887: recipe for target 'ctags' failed

then I will do:
git checkout optlib/ctags-optlib.c optlib/gdbinit.c optlib/m4.c

and gmake passes ...

**Comment by masatake** [comment]
I'm rewriting optlib2c in perl. 
It will solve these confution.
You may have perl.

**Comment by masatake** [comment]
Please, try #804.

**Comment by tarzanek** [comment]
lovely! all works now! :)
Thank you sir!
