### ISSUE TITLE
SASS/SCSS support

### ISSUE THREAD

**Issue by robertzajda** [universal-ctags/ctags#801]
Hi
Maybe not clean but working solution:
http://geany.robert.dvu.pl/

**Comment by masatake** [comment]
Thank you for introducing the patch.
Howere, there is no copyright information, so we cannot use this in u-ctags.

**Comment by robertzajda** [comment]
This are only some improvements of existing files. So license is the same as before. I made only a note about improvements. If you want to use this patch, just give me a hint what copyright contents are required.

**Comment by masatake** [comment]
??? Are you the author of the patch?
If you are the author, I agree with what you wrote.
If not, I don't agree with you.

**Comment by masatake** [comment]
(I'm concerning about the source of the patch. I really don't want to steal the one's work.)

**Comment by Roy-Orbison** [comment]
Try [this custom parser](https://gist.github.com/Roy-Orbison/71bc81f488f85adaeacfb76a7967eda0).

**Comment by masatake** [comment]
@Roy-Orbison, could you consider to add copyright notice like https://github.com/universal-ctags/ctags/blob/master/optlib/qemuhx.ctags ?

**Comment by Roy-Orbison** [comment]
Done.

**Comment by masatake** [comment]
@Roy-Orbison, thank you.

**Comment by Roy-Orbison** [comment]
I've updated my gist again. For a large codebase, try [twbs/bootstrap's scss](https://github.com/twbs/bootstrap/blob/master/scss/). I haven't included the `selector` kind in my parser.

**Comment by masatake** [comment]
Thank you. I'm trying to merge your code to u-ctags. However, I cannot find much time for a month.

>  I haven't included the selector kind in my parser.

I see. I read your parser and I also think selector kind is not fit to scss parser.

Experimentally, I changed your code like this:
```
--langdef=SCSS
--map-SCSS=+.scss
--kinddef-SCSS=m,mixin,mixins
--kinddef-SCSS=f,function,functions
--kinddef-SCSS=v,variable,variables
--kinddef-SCSS=c,class,classes
--kinddef-SCSS=P,placeholder,placeholder classes
--kinddef-SCSS=i,id,identities
# --kinddef-SCSS=p,pseudo,pseudos
--kinddef-SCSS=z,parameter,function parameters
--_tabledef-SCSS=toplevel
--_tabledef-SCSS=comment
--_tabledef-SCSS=interp
--_tabledef-SCSS=args
--_mtable-regex-SCSS=toplevel/\/\/[^\n]*\n?//
--_mtable-regex-SCSS=toplevel/\/\*//{tenter=comment}
--_mtable-regex-SCSS=toplevel/#\{//{tenter=interp}
--_mtable-regex-SCSS=comment/\*\///{tleave}
--_mtable-regex-SCSS=comment/.//
--_mtable-regex-SCSS=interp/\}//{tleave}
--_mtable-regex-SCSS=interp/.//
--_mtable-regex-SCSS=toplevel/[ \t]([A-Za-z0-9_-]+)[ \t]*:[^\n]*\n?//
--_mtable-regex-SCSS=toplevel/@mixin[ \t]+([A-Za-z0-9_-]+)/\1/m/{tenter=args}
--_mtable-regex-SCSS=toplevel/@function[ \t]+([A-Za-z0-9_-]+)/\1/f/{tenter=args}
--_mtable-regex-SCSS=args/\{//{tleave}
--_mtable-regex-SCSS=args/#\{//{tenter=interp}
--_mtable-regex-SCSS=args/\$([A-Za-z0-9_-]+)/\1/z/
--_mtable-regex-SCSS=args/.//
--_mtable-regex-SCSS=toplevel/@each[ \t]+\$([A-Za-z0-9_-]+)[ \t]in[ \t]+/\1/v/
--_mtable-regex-SCSS=toplevel/@[^\n]+\n?//
--_mtable-regex-SCSS=toplevel/:[^{;]+;\n?//
--_mtable-regex-SCSS=toplevel/:[^\n;{]+\n//
# --_mtable-regex-SCSS=toplevel/::?([A-Za-z0-9_-]+)[ \t]*[,({]/\1/p/
--_mtable-regex-SCSS=toplevel/:[^\n{]+[;{]\n?//
--_mtable-regex-SCSS=toplevel/\$([A-Za-z0-9_-]+)[ \t]*:[^\n]*\n?/\1/v/
--_mtable-regex-SCSS=toplevel/[.]([A-Za-z0-9_-]+)/.\1/c/
--_mtable-regex-SCSS=toplevel/%([A-Za-z0-9_-]+)/%\1/P/
--_mtable-regex-SCSS=toplevel/#([A-Za-z0-9_-]+)/#\1/i/
--_mtable-regex-SCSS=toplevel/.//
```

* `#`, `%`, `.` are included as part of a tag name to align the behavior of scss parser to that of our css parser.
* `P` kind is introduced.
* `z` kind is introduced for capturing parameters of a function.
* pseudo kind is temporary disabled because the css parser doesn't capture the kind separately.

The latest change is not included yes.

**Comment by masatake** [comment]
I made a pull request. See #2191.

**Comment by Roy-Orbison** [comment]
Rather than omit the `pseudos` pattern, you may want to change it to non-capturing:

```
--_mtable-regex-SCSS=toplevel/::?([A-Za-z0-9_-]+)[ \t]*[,({]//
```

**Comment by masatake** [comment]
I have studied more.
I think we should introduce the pseudo kind to the css parser, and also revive the kind in scss parser.

In historical reason of css spec, it seems that using the same pseudo kind for both pseudo-class and pseudo-class and pseudo-element.

I will work on the css parser first. Then I will revise #2191.

**Comment by masatake** [comment]
I have studied further more.
I think we should not introduce the pseudo kind to the css parser.
.class and #id are user defined name. So thye should be tagged with specific kind (class and id).
However, the name of pseudo classes and elements are defined in the spec of css.
Basically, we should make tags for language objects named by USER.
I have already written code for tagging pseudo classes and elements for css parser.
However, I must throw the code away.

...I would like to apply the above rule to ths scss parser, too.
I will follow the advice given in https://github.com/universal-ctags/ctags/issues/801#issuecomment-527263479.

**Comment by masatake** [comment]
The scss parser in the pull request is updated.
It is ready to merge.

**Comment by masatake** [comment]
bootstrap repo is added to codebase.
```
[yamato@slave]~/var/codebase% ./codebase  ctags SCSS                  
version: 6bf55137
features: +wildcards +regex +iconv +debug +option-directory +xpath +json +interactive +sandbox +yaml +aspell +packcc
log: results/6bf55137,SCSS................,..........,time......,default...,2019-09-10-18:57:56.log
tagsoutput: /dev/null
cmdline: + u-ctags --quiet --options=NONE --sort=no --options=profile.d/maps --totals=yes --languages=SCSS -o - -R code/bootstrap
109 files, 9150 lines (235 kB) scanned in 0.1 seconds (3011 kB/s)
2077 tags added to tag file
longest tag line = 111

real	0m0.081s
user	0m0.076s
sys	0m0.005s
+ set +x
```

**Comment by masatake** [comment]
@Roy-Orbison, a parser bsaed on your work is merged. Thank you.
