### ISSUE TITLE
Reconsider backslashs in tag name

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#815]
Related to #582, #787.

There is a confliction about usage of backslash.
PHP uses backslash as a separator in an item in a namespace.
u-ctags uses backslash as an escape character.

Basically this is an issue of upper layer tools, not u-ctags.
u-ctags will provide the information about separators used in tags file via pseudo-tags.
The tools should use it.

Anyway I will ask you what we can do.
Implementing an option is one of the approach: --print-name-no-escaping.
Do you want the option?

Anyway I should write about the escaping clearly in docs/format.rst before releasing 1.0.

**Comment by markwu** [comment]
Finally, I found the root cause. That's why I get double backslash in namesapce and class name.  

I like `--print-name-no-escaping` option, It not only solve the tag name confliction issue, and also add back compatbility for current completion tools.

**Comment by pjkack** [comment]
Will the new option also be applied to the input/source-filename in the tag file? I don't want the double backslashes I'm seeing on Windows due to the following code
`
static int writeCtagsEntry (const tagEntryInfo *const tag)
{
	int length = mio_printf (TagFile.fp, "%s\t%s\t",
			      escapeName (tag, FIELD_NAME),
			      escapeName (tag, FIELD_INPUT_FILE));
`

**Comment by masatake** [comment]
@pjkack,  `renderFieldName` in field.c controls it.

It seems tat `--print-name-no-escaping` and `--print-input-no-escaping` are needed.


I may have to add a pseudotag for the option.
Consider a tags is here. A tool may wonder whether it is generated with `--print-name-no-escaping` or not.

I'm thinking about embedding all options and information about environment where ctags is run as pseudo tags.

**Comment by pjkack** [comment]
@masatake Your proposal sounds good to me. Out of curiosity, what's the reason for escaping by default over keeping the exuberant ctags behavior by default?

**Comment by masatake** [comment]
See https://github.com/universal-ctags/ctags/issues/499
and http://docs.ctags.io/en/latest/format.html#proposal-for-extended-vi-tags-file-format

I have to write how the characters are escaped docs/format.rst.

**Comment by masatake** [comment]
The backslash is introduced for recording a name with a tab character.
If --print-name-no-escaping is given and ctags finds a name with a tab character, what ctags should do?
I think just ignoring such names is enough. How do you think?

About pseudo tag, I'm thinking adding `!_TAG_FILE_ESCAPED`.
I will start implementing. However, comments are really welcome.

**Comment by markwu** [comment]
If you ignored the tab characters, what will be happened when I have a php namespace like:

```
namspace abc\tuv;
```
Will this namespace ignored?

**Comment by masatake** [comment]
No, there is no impact on php.

As far as I can image, only html, rst and tex get the impact.
I'm importing markdown parser from geany. It gets the impact, too.

**Comment by masatake** [comment]
I'm re-reading FORMAT document which defines the tag file format to understand this issue more.

**Comment by masatake** [comment]
I think this should be handled in `--output-format` option.
How a name being escaped should be handled in output-format engine.

**Comment by pjkack** [comment]
Is there any way now to specify that the input file name should not be escaped? Or am I'm still stuck with running my locally modified version where renderFieldInput always just returns f instead of renderEscapedString (f, tag, b).

**Comment by masatake** [comment]
@pjkack, sorry to be late.

Could you tell me the issue about file name?

```
[yamato@x201]~/var/ctags-github% for x in *.c; do echo $x; done        
a\b.c
[yamato@x201]~/var/ctags-github% for x in *.c; do ctags -o - $x; done
ctags: Warning: Ignoring non-option in ./.ctags

foo	a\\b.c	1;"	d	file:
[yamato@x201]~/var/ctags-github% for x in *.c; do u-ctags -o - $x; done
foo	a\\\\b.c	/^#define foo$/;"	d	file:
```

Here ctags means exuberant-crags(e-ctags).  e-ctags injects doubled backslashes.
u-ctags injects quad'ed backslashes.

Do you want e-ctags behavior?

As written in docs/format.rst a file name can be appeared two places in tags file:
```
Use a comment after the {tagaddress} field.  The format would be::

	{tagname}<Tab>{tagfile}<Tab>{tagaddress}[;"<Tab>{tagfield}..]
```

I'm talking about `{tagfile}`. u-ctags should do the same as e-ctags do about `{tagfile}`.
I cannot remember why I introduce the current behavior(inserting quad'ed backslashes).

**Comment by masatake** [comment]
Oh, I'm sorry. I used wrong input file name in the above comment.

```
[yamato@x201]~/var/ctags-github% echo #define foo > 'a\b.c'            
[yamato@x201]~/var/ctags-github% for x in *.c; do u-ctags -o - $x; done
foo	a\\b.c	/^#define foo$/;"	d	file:
[yamato@x201]~/var/ctags-github% for x in *.c; do ctags -o - $x; done 
ctags: Warning: Ignoring non-option in ./.ctags

foo	a\b.c	1;"	d	file:
```

It seems that e-ctags doesn't do put doubled backslashes, though u-ctags does.

**Comment by masatake** [comment]
O.k. I will write my plan here. 

0. escaping newly introduced in u-ctags is enabled only when an extra flag is given in `--output-format` option like:
   ```
   --output-format=ctags{escape=yes}
   ```
2. the default is `escape=no`.

3. an entry not render-able is ignored(not printed) if escape=no flag is given.

4. finally we will update the document.

Implmenting 3. may not be easy. People who don't think so should make a PR:-P.

**Comment by pjkack** [comment]
@masatake Thanks for replying again so quickly. I think your plan sounds good.

I'm on Windows where e-ctags never escape the back slashes in file names, while c-tags currently do.

Here is an example of the current c-tags output:
`renderFieldInput	C:\\Users\\XYZ\\GitHub\\ctags\\main\\field.c	/^static const char *renderFieldInput (const tagEntryInfo *const tag, const char *value CTAGS_ATTR_UNUSED, vString* b)$/;"	f	typeref:typename:const char *	file:	signature:(const tagEntryInfo * const tag,const char * value CTAGS_ATTR_UNUSED,vString * b)`

I think the same example should look like this to conform to the same format as e-tags:
`renderFieldInput	C:\Users\XYZ\GitHub\ctags\main\field.c	/^static const char *renderFieldInput (const tagEntryInfo *const tag, const char *value CTAGS_ATTR_UNUSED, vString* b)$/;"	f	typeref:typename:const char *	file:	signature:(const tagEntryInfo * const tag,const char * value CTAGS_ATTR_UNUSED,vString * b)`

**Comment by masatake** [comment]
Exuberant-compatible output is worked locally.

```
[yamato@master]~/var/ctags-github%  ./ctags --output-format=universal-ctags -o - --extra=+q  Units/parser-php.r/php-full-qualified-tags.d/input.php
__construct	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^    public function __construct() {$/;"	f	class:foo\\bar
bar	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^class bar {$/;"	c	namespace:foo
foo	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^namespace foo;$/;"	n
foo\\bar	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^class bar {$/;"	c	namespace:foo
foo\\bar::__construct	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^    public function __construct() {$/;"	f	class:foo\\bar
[yamato@master]~/var/ctags-github%  ./ctags --output-format=exuberant-ctags -o - --extra=+q  Units/parser-php.r/php-full-qualified-tags.d/input.php
__construct	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^    public function __construct() {$/;"	f	class:foo\\bar
bar	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^class bar {$/;"	c	namespace:foo
foo	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^namespace foo;$/;"	n
foo\bar	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^class bar {$/;"	c	namespace:foo
foo\bar::__construct	Units/parser-php.r/php-full-qualified-tags.d/input.php	/^    public function __construct() {$/;"	f	class:foo\\bar
```

**Comment by masatake** [comment]
File name also handled well.
```
[yamato@master]~/var/ctags-github% echo #define foo > 'a\b.c'
[yamato@master]~/var/ctags-github% for x in *.c; do ./ctags -o - "$x"; done
foo	a\\b.c	/^#define foo$/;"	d	file:
[yamato@master]~/var/ctags-github% for x in *.c; do ./ctags --output-format=exuberant-ctags -o - "$x"; done
foo	a\b.c	/^#define foo$/;"	d	file:
```

**Comment by masatake** [comment]
@markwu, @pjkack, could you try #1209?
I added ``--output-format=e-ctags`` option which you may like.

**Comment by pjkack** [comment]
Thanks, it seems to work fine for me!
