### ISSUE TITLE
Test cases under review-needed.r (language: C++)

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#830]
@pragmaware.
Could you look at #361?

There are 5 test cases about C++ under the /review-needed.r directory.

```
[yamato@x201]~/var/ctags-github/Units/review-needed.r% LC_ALL=C ls -ld *.cpp.*
drwxr-xr-x. 2 yamato yamato 4096 Mar  8 01:54 bug1093123.cpp.t
drwxr-xr-x. 2 yamato yamato 4096 Mar  8 01:54 bug1187505.cpp.t
drwxr-xr-x. 2 yamato yamato 4096 Mar  8 01:54 bug1563476.cpp.t
drwxr-xr-x. 2 yamato yamato 4096 Mar  8 01:54 bug1799343-1.cpp.t
drwxr-xr-x. 2 yamato yamato 4096 Mar  8 01:54 bug1799343-2.cpp.t
drwxr-xr-x. 2 yamato yamato 4096 Mar  8 01:54 bug1924919.cpp.t
```

These test cases must be reviewed and may be modified: adding more options to args.ctags and/or updating expected.tags. I guess there are subtle cases. In that case I would like you to add README for
the test case.

After being reviewed the cases will contribute to improve your new C++ parser.

**Comment by pragmaware** [comment]
Done in the new C++ parser.

**Comment by masatake** [comment]
Thank you. This has been long standing issue. Now I can universal-ctags inherits the great legacy of exuberant-ctags...about C++. Thank you again.
