### ISSUE TITLE
Can't use < in readtags -Q: GOT ERROR in QUALIFYING: number-required: <

### ISSUE THREAD

**Issue by bmag** [universal-ctags/ctags#838]
I'm trying to use `readtags` to browse tags file generated by `ctags`, but I'm not able to use the `<` filter. I've tried running this command:
```sh
readtags -Q '(< 1 2)' -l
```
But I'm receiving this error: `GOT ERROR in QUALIFYING: number-required: <`. The same happens if I try `>`, `<=` or `>=`.

I've built the tags file using the command `ctags --fields=* --extra=* -R .` in a python project. I've installed ctags as per the instructions [here](http://docs.ctags.io/en/latest/autotools.html#building-with-configure-nix-including-gnu-linux).
Let me know if you need more information.

Background: I'm considering writing an emacs front-end for universtal-ctags, so I'm testing what information I can get from `readtags`. I was trying to get the tag corresponding to a line in file, so I thought to use `readtags -en -Q '(<= $line <line>' -l` (where `<line>` is provided by the front-end) and then return the tag with the maximal line number. And then I ran into the bug above.

**Comment by masatake** [comment]
Could you tell me your plan about the front end?

I wrote one and using daily. I have never made it public because I cannot have capacity for driving its development. The most of my time is consumed in ctags development.

My tool is named spelunker.el. It is for code reader, not for developer.

https://gist.github.com/masatake/e0dbc1f8e4a239689cad
https://gist.github.com/masatake/4a5f0edee4d43f3a5f0c

If you are interested in, I will make the document for how to use.
The above is advertisement.

So, look at the bug then.

**Comment by masatake** [comment]
Could you try #839.
Thank you for reporting. As far as I know you are the first user of my filter engine.
Yes, it is designed for emacs.

**Comment by bmag** [comment]
Thank you, I confirm #839 solves the issue for me.

I don't have a plan yet for the front-end. I'm still gathering ideas, so it's sort-of a wish-list for now:
- imenu support
- tree-view of file structure, including tags meta-data (kind, signature, ...)
  - AFAIK it's not possible with etags or gtags, but it seems possible with ctags :smile: 
  - [imenu-list](https://github.com/bmag/imenu-list) (disclaimer: I wrote it) can show tree-view based on imenu, but it doesn't show meta-data
- interactive code/flow browser. The idea is a command that recognizes the tag you're viewing, lists all tags the reference current tag or are referenced by current tag, and lets you jump to one of them. For example, if point is inside a function`foo`, that calls `bar` and `baz` and is called by `tux`, the command will show that `bar` and `baz` are referenced by `foo`, that `tux` references `foo`, and I could jump to `bar`, `baz` or `tux`. If the command remains active after jump, it will be easy to follow code-flow in this manner.
  - requires ctags to store cross-references. As far as I understand ctags does not have this feature :cry: 
  - extending speedbar for ctags is possible as an (inferior?) alternative
- code completion via [company](https://github.com/company-mode/company-mode) back-end or `completion-at-point-functions`.
  - `readtags -p` can be used for simple non-fuzzy completion
- commands for find-definition, find-references (if possible), search tags, etc.

Unfortunately, I don't have time to work on it either, except for sometimes on the weekend maybe. I might work on it seriously during the summer, but I'm not promising anything.

I didn't run spelunker.el, but I think I can figure out how to run it. If you can only explain what the `root` parameter in `spelunker-session` means, I think it will be enough.

**Comment by masatake** [comment]
https://gist.github.com/masatake/8f3cd71368deb82a08c2b16f09319a7c

I introduced `define-spelunker` macro. I wrote usage in short in the comment of the macro.

**Comment by masatake** [comment]
Did you check xref.el bundled to emacs-25.1?
tags file driver must be written.

**Comment by bmag** [comment]
@masatake I've looked at `xref` about a year ago, but I should check it again (when I have time)
