### ISSUE TITLE
Vim hit error e435 because EOL between file and tags file is different.

### ISSUE THREAD

**Issue by blackb1rd** [universal-ctags/ctags#844]
The EOL of code below is "\r\n"

```c
#include <stdio.h>

int foo() {
    int a = 1;
    printf("a = %d\n", a);
}

void main(void) {
    foo();
}
```

and the tags file is generated as a `/^int foo() {$/` without "\r" before character dollar sign($).
```tags
foo /tmp/enum.c /^int foo() {$/;"   f
main    /tmp/enum.c /^void main(void) {$/;" f
```

is it better to generate as a `/^int foo() {\r$/` with "\r" if EOL of file is "\r\n"?
```tags
foo /tmp/enum.c /^int foo() {\r$/;"   f
main    /tmp/enum.c /^void main(void) {\r$/;" f
```

**Comment by masatake** [comment]
Basically I don't think it is better because it breaks compatibility.
The original `Exuberant Ctags` doesn't print `\r`.

```
[jet@living ctags]$ ctags  --version
ctags: Warning: Ignoring non-option in ./.ctags

Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 30 2014, 14:24:51
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
[jet@living ctags]$  hexdump -c input.c 
0000000   #   i   n   c   l   u   d   e       <   s   t   d   i   o   .
0000010   h   >  \r  \n  \r  \n   i   n   t       f   o   o   (   )    
0000020   {  \r  \n                   i   n   t       a       =       1
0000030   ;  \r  \n                   p   r   i   n   t   f   (   "   a
0000040       =       %   d   \   n   "   ,       a   )   ;  \r  \n   }
0000050  \r  \n  \r  \n   v   o   i   d       m   a   i   n   (   v   o
0000060   i   d   )       {  \r  \n                   f   o   o   (   )
0000070   ;  \r  \n   }  \r  \n                                        
0000076
[jet@living ctags]$ ./ctags -o - input.c 
foo	input.c	/^int foo() {$/;"	f
main	input.c	/^void main(void) {$/;"	f
```

**Comment by blackb1rd** [comment]
Well, I found some users report this issue to Vim:
https://groups.google.com/d/msg/vim_dev/IR7P-4HV8LM/F8qs9h32jp4J

and Bram Moolenaar suggests to add <CR> before the $.

**Comment by blackb1rd** [comment]
I may help to do a PR on this issue if you need! :)

**Comment by k-takata** [comment]
> Well, I found some users report this issue to Vim:
> https://groups.google.com/d/msg/vim_dev/IR7P-4HV8LM/F8qs9h32jp4J

As the link shows, it only occurs when CRLF and LF is mixed in one file. It's very unusual case.
If all the EOL are CRLF, Vim can find the tag without the error E435.

**Comment by b4n** [comment]
For mixed line endings, it might be interesting -- but that should be *very* rare.

For any other (sane) file, I don't think it's a good idea at all.  `$` represents the end of the input or line, whatever that is, it's a logical thing, not a synonym for `\n`.  Also, if the editor really can't handle `\r\n` line ends properly, the user would have more serious problems than matching tags.

And as @masatake mentioned, it would be a fairly serious compatibility break, where every tool that currently function properly would have to handle `\r$` in a special way.

**Comment by blackb1rd** [comment]
> For any other (sane) file, I don't think it's a good idea at all. $ represents the end of the input or line, whatever that is, it's a logical thing, not a synonym for \n. Also, if the editor really can't handle \r\n line ends properly, the user would have more serious problems than matching tags.
> 
> And as @masatake mentioned, it would be a fairly serious compatibility break, where every tool that currently function properly would have to handle \r$ in a special way.
> 

I agree. So, the editor shall handle in this case. Closed.
