### ISSUE TITLE
Request for PHP Namespace and Use

### ISSUE THREAD

**Issue by compleatguru** [universal-ctags/ctags#847]
Reference with [PHP Using Namespace](http://php.net/manual/en/language.namespaces.importing.php)

1. CTags is lacking the ability to decipher PHP namespace alias.
   e.g:
   ```php
<?php
namespace frontend\controllers;

use yii\web\Controller as WebController;

class SiteController extends WebController{
}
```
2. CTags is pointing another class.
   e.g:
   ```php
<?php
namespace frontend\controllers;

use yii\web\Controller;

class SiteController extends Controller{
}
?>
```
   But upon navigation, yii\base\Controller was retrieved instead of yii\web\Controller.

Hope that the team can help to address this issue.

Thank you!

**Comment by cweagans** [comment]
Thanks for opening this. I think these are probably separate feature requests, though.

**Comment by b4n** [comment]
> CTags is lacking the ability to decipher PHP namespace alias. […]

Add support for parsing `use` statements in #851.

> CTags is pointing another class.
> […]
> But upon navigation, yii\base\Controller was retrieved instead of yii\web\Controller.

I'm not sure it's CTags job here.  With the added support for reporting aliases, an application will be able to do that itself.

But is it CTags job to try and qualify the names?  I'm not sure.  In one hand it can be nice, and could more or less be possible (well, it wouldn't be trivial, yet possible), but on the other hand CTags historically mostly only reports what's written straight in the code without adding further indirection resolution.  And CTags won't be able to help if the qualified name isn't visible in the file itself, it doesn't have a "workspace" like an IDE can.

**Comment by masatake** [comment]
Mostly I agree with @b4n; adding tan entries about full qualified names is an optional feature of ctags.
As I wrote before somewhere, for some kind of tools full qualified tags are just noise.
For the tools , I introduced `--fields=+E` option.
