### ISSUE TITLE
Test cases under review-needed.r (language: vim) 

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#861]
See #361.

3214129.vim.t  3548393.vim.t  bug3032253.vim.t  bug358.vim.t  bug359.vim.t  simple.vim.t

must be reviewed.

**Comment by dkearns** [comment]
I'll take this.

**Comment by masatake** [comment]
Oh! thank you.

**Comment by masatake** [comment]
Closed with #936.
