### ISSUE TITLE
tags-file generated by TeX parser uses patterns in EX command instead of line numbers

### ISSUE THREAD

**Issue by dirkhas** [universal-ctags/ctags#883]
When generating a tags file using the TeX parser, the generated tags-file contains a search pattern as its EX command instead of a line number, for example`^\\subsection{Summary}$`

~~If~~ When the title is not unique, which is typical for large documents with a certain structure for each chapter or section, the backlinks in the editor will not work.

**Comment by masatake** [comment]
The option ` --excmd=number` is for you.

**Comment by dirkhas** [comment]
That'll teach me to read the whole man page ;) Thanks!

**Comment by masatake** [comment]
I can guess your next question: why double slash is used in the pattern and name.
The first backslash is an escape character for the second backslash.
To record a name having white space, especially tab char, in tags file, universal-ctags introduces backslash escaping.

This is not written in man page, yet. I'm looking for volunteers taking care for updating man page.
