### ISSUE TITLE
Compile on debian distro

### ISSUE THREAD

**Issue by hath995** [universal-ctags/ctags#888]
I have tried to compile this from source on a ubuntu vm and a debian vm. I installed autotools and autoreconf. I errors similar to the following on both systems. 

```
autoreconf2.50: Entering directory `.'
autoreconf2.50: configure.ac: not using Gettext
autoreconf2.50: running: aclocal --force
autoreconf2.50: configure.ac: tracing
autoreconf2.50: configure.ac: not using Libtool
autoreconf2.50: running: /usr/bin/autoconf --force
configure.ac:122: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf2.50: /usr/bin/autoconf failed with exit status: 1
```

```
$ uname -a 
Linux rentlytics 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by b4n** [comment]
WFM just fine on Debian Unstable:
```console
$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:278: installing './compile'
configure.ac:23: installing './config.guess'
configure.ac:23: installing './config.sub'
configure.ac:11: installing './install-sh'
configure.ac:11: installing './missing'
Makefile.am: installing './depcomp'
/usr/share/automake-1.15/am/tags.am: warning: redefinition of 'ctags' ...
/usr/share/automake-1.15/am/program.am: ... 'ctags$(EXEEXT)' previously defined here
Makefile.am:6:   while processing program 'ctags'
autoreconf: Leaving directory `.'
optlib2c: translating optlib/CoffeeScript.ctags to optlib/CoffeeScript.c
optlib2c: translating optlib/ctags-optlib.ctags to optlib/ctags-optlib.c
optlib2c: translating optlib/gdbinit.ctags to optlib/gdbinit.c
optlib2c: translating optlib/m4.ctags to optlib/m4.c
```

With Autoconf 2.69/Automake 1.15.

A real quick look at Autoconf's NEWS might suggest the usage of `AC_DEFINE` at line 122 *might* depend on 2.64 -- but again, I didn't check further or anything.
Note that all current versions of Debian (from oldstable to unstable) have Autoconf 2.69, so I find it kind of odd to see 2.50 here.  What's the actual Autoconf version? (`autoconf --version`)

**Comment by hath995** [comment]
```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
---
Autoconf 2.50 chosen by Debian wrapper script.
For information and tuning advice see autoconf(1).


$ automake --version
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

**Comment by masatake** [comment]
As far as reading your comment "Debian wrapper script" has an issue.
However, our build system doesn't user the script.
How did you launch autoconf2.50 and automake?

As written in README.md, running autogen.sh is the way to build universal-ctags.

**Comment by hath995** [comment]
Yes. That is the command I ran.

**Comment by masatake** [comment]
Could you show me the output of "$autoreconf --version" ?

**Comment by hath995** [comment]
```
vagrant@rl:~/code/ctags$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
---
Autoconf 2.50 chosen by Debian wrapper script.
For information and tuning advice see autoconf(1).
vagrant@rl:~/code/ctags$ ls
aclocal.m4    autogen.sh      config.log  configure.ac  ctags.1.in  docs  fnmatch    libexec  Makefile.am  misc          mk_mvc.mak  optlib   README.md   readtags.h  Tmain  win32
appveyor.yml  autom4te.cache  configure   COPYING       ctags.spec  dsl   gnu_regex  main     makefiles    mk_mingw.mak  old-docs    parsers  readtags.c  source.mak  Units
vagrant@rentlytics:~/code/ctags$ ./autogen.sh
autoreconf2.50: Entering directory `.'
autoreconf2.50: configure.ac: not using Gettext
autoreconf2.50: running: aclocal --force
autoreconf2.50: configure.ac: tracing
autoreconf2.50: configure.ac: not using Libtool
autoreconf2.50: running: /usr/bin/autoconf --force
configure.ac:122: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf2.50: /usr/bin/autoconf failed with exit status: 1
vagrant@rentlytics:~/code/ctags$
```

**Comment by k-takata** [comment]
How about removing ./configure and run ./autogen.sh again?

**Comment by hath995** [comment]
Didn't work, same error.

**Comment by hath995** [comment]
In the error it mentions Libtool. I thought perhaps that it was not installed, and it seems that was correct. I did an apt-get install libtool, but that doesn't seem to change the output either.

```
$ libtool --version
libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by hath995** [comment]
This vm is a vagrant box built around using ubuntu/trusty.

**Comment by k-takata** [comment]
Hmm, then how about running autoreconf 2.69 explicitly?
E.g.:
```
autoreconf2.69 -vfi
./autogen.sh
```

> Autoconf 2.50 chosen by Debian wrapper script.

It's obvious that this is the problem, but I don't know why this happens.

**Comment by hath995** [comment]
Apparently, Debian has a man page for autoconf, which explains some of this behavior. If both Autoconf2.13 and autoconf 2.50 are installed the wrapper script chooses 2.50. I uninstalled both of those versions. Uninstalled and reinstalled 2.69 for good measure. Deleted configure

```
$ autoreconf -vfi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:122: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by masatake** [comment]
Could you show the output of following command line?

`$ /usr/bin/autoconf --verbose --force`

The output will be large. Gist can be used for showing it.

**Comment by hath995** [comment]
https://gist.github.com/hath995/a9fc835bd2eb28ab064caee85f817c3e

**Comment by masatake** [comment]
Could you try following steps?

`1`. mkdir /tmp/x
`2`. put following data as /tmp/x/configure.ac

```
 AC_PREREQ([2.59]) 
 AC_INIT([A],[0.0.0]) 
 AC_DEFINE(X)
 AC_OUTPUT
 ``` 


`3`. cd /tmp/x; autoconf --verbose --force

Do you get the same error?

**Comment by hath995** [comment]
I'm not sure if it errored. Here is the output of 
```
autoconf --verbose --force >> output.txt 2>&1
```
https://gist.github.com/hath995/5b786dac6228eb3c7dc82335dcc46296

**Comment by masatake** [comment]
Looks different. With the short configure.ac, it works fine.

Do you know term "binary search" of computer science?
(I think you may know.)

I guess the line 
```
		AC_DEFINE(AS_TR_CPP([NEED_PROTO_$1]))
```
triggers the error. Before inspecting the line deeply I would like to
get a proof that the line really triggers an error.

The way for the proof is simple: making the original configure.ac
shorten incrementally; and run autoconf every step.
With this way you can find minimum configure.ac that can reproduce the error.

If you don't know the syntax of configure.ac and m4, this is not easy task.

**Comment by hath995** [comment]
Yeah, I'm not familiar with configure.ac or m4. I do understand the concept of binary search. 

I commented out the latter half of the script. When doing so it would show a message like the following. 

```
$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
automake: error: no 'Makefile.am' found for any configure output
automake: Did you forget AC_CONFIG_FILES([Makefile]) in configure.ac?
autoreconf: automake failed with exit status: 1
```

When I uncommented lines https://github.com/universal-ctags/ctags/blob/master/configure.ac#L587-593
Then I got the error
```
$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:122: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by hath995** [comment]
Also commenting or uncommenting lines 122 didn't seem to have any effect.

**Comment by b4n** [comment]
What if you change `AC_PREREQ([2.59])` to `AC_PREREQ([2.64])` in uctags' *configure.ac*?

**Comment by hath995** [comment]
Same error

**Comment by k-takata** [comment]
https://github.com/gnosek/fcgiwrap/issues/9#issuecomment-14940995

> As possibly useful info if anyone else hits the "possibly undefined macro: AC_DEFINE" error.
>
> That AC_DEFINE error (specifically for AC_DEFINE) can be caused by pkg-config not being installed, or at least not found in the search path.


Please try "apt-get install pkg-config".

**Comment by hath995** [comment]
That worked. It is now installed.

**Comment by hath995** [comment]
Thanks for the help!

**Comment by vhda** [comment]
Installing pkg-config did not work for me and I still have the following error:

```
/usr/share/automake-1.14/am/tags.am: warning: redefinition of 'ctags' ...
/usr/share/automake-1.14/am/program.am: ... 'ctags$(EXEEXT)' previously defined here
```

As far as I can see, in automake-1.14 the file /usr/share/automake-1.14/am/tags.am defines the following target:

```makefile
## --------------- ##
## vi-style tags.  ##
## --------------- ##

CTAGS = ctags
.PHONY: CTAGS ctags
if %?SUBDIRS%
AM_RECURSIVE_TARGETS += CTAGS
RECURSIVE_TARGETS += ctags-recursive
ctags: ctags-recursive
else !%?SUBDIRS%
ctags: ctags-am
endif !%?SUBDIRS%

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
## Make sure we have something to run ctags on.
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique
```

So, basically if defines a "ctags" target that conflicts with our program name. Then /usr/share/automake-1.14/am/program.am has the following:

```makefile
%PROGRAM%%EXEEXT%: $(%XPROGRAM%_OBJECTS) $(%XPROGRAM%_DEPENDENCIES) $(EXTRA_%XPROGRAM%_DEPENDENCIES) %DIRSTAMP%
```

That in Unix will be "ctags:". I've also confirmed that if I manually rename bin_PROGRAMS to "uctags" the error disappears.

Anyone knows how to disable reading "tags.am" to avoid this conflict in some automake versions?

**Comment by b4n** [comment]
@vhda it's where I myself got blocked when trying to port to Automake myself, but AFAICT it's not a blocker, just some annoyance.
But no, I don't know how to avoid that and couldn't fine someone knowledgeable yet.

**Comment by vhda** [comment]
Didn't even notice that `configure` was still being created! Thanks for sharing @b4n
