### ISSUE TITLE
Clojure macro and pred fn ( fns with ends with ?) not supported yet? or need extra config?

### ISSUE THREAD

**Issue by oneness** [universal-ctags/ctags#901]
Pulled master and build off of it to install universal ctags. Found that the tags are not there for macros and pred fns. 
Would be happy to do a PR for it if you not supported yet. If supported, any configs to enabled it?

**Comment by masatake** [comment]
No configs.

I'm thinking about using meta S expression parser (see dsl/es-lang-c-stdc99.c) for improving scheme, lisp and clojure. However, I cannot find time for doing it. Any PR is welcome though I cannot promise I will merge it. 

The most important things are "kind choice" and "test cases". Thses two are reusable even if the parser implementation is changed from your to my sexp meta parser.

**Comment by oneness** [comment]
Thanks for your response.  Have you looked into using PEGs? (Parsing
Expression Grammer) to parse lisp family langs?  Lua has a great PEG lib
and called LPEG and could be of some use here.

Kasim Tuman

==========================================

Experience is more about knowing what should be avoided

than what should be done. -- Kasim
============================================

**Comment by masatake** [comment]
I don't know well about PEG but I heard it is good thing.
How can we use it from ctags?  Linking liblua (or something ) to ctags?

**Comment by masatake** [comment]
If you have a protype in lua, with xcmd ctags can utilize it.

**Comment by masatake** [comment]
I wrote some ideas about parsers for lisp family in https://github.com/universal-ctags/ctags/pull/469 .
