### ISSUE TITLE
Tag the releases

### ISSUE THREAD

**Issue by tessiof** [universal-ctags/ctags#909]
The documentation at docs.ctags.io says current release is version 0.3.0, but there is no release tag on github. Why is that?

**Comment by masatake** [comment]
*Currently* the version number of docs and executables are not synchronized. As `ctags --version` shows, the executables side are still version 0.0.0.

```
% ./ctags --version 
./ctags --version 
Universal Ctags 0.0.0(5bcd4cf), Copyright (C) 2015 Universal Ctags Team
...
```

Ideally they should be synchronized.

**Comment by tessiof** [comment]
Ok. Since the executables are still version 0.0.0, there's no release to be tagged.

**Comment by masatake** [comment]
BTW, comments about docs.ctags.io is really welcome.
The document is one of the critical bottle neck for releasing 1.0.0.
