### ISSUE TITLE
 Test cases under review-needed.r (language: Eiffel)

### ISSUE THREAD

**Issue by dkearns** [universal-ctags/ctags#933]
Reviewing old Exuberant Ctags Eiffel tests under review-needed.r.

**Comment by masatake** [comment]
Yes, I know the need of reviewing them.
However, I don't know Eiffel. It seems that you are an Eiffel hacker. Could you help me?

**Comment by masatake** [comment]
#861 is also available:-P.

**Comment by masatake** [comment]
The original report solves this:-P.
