### ISSUE TITLE
Test cases under review-needed.r (language: Java)

### ISSUE THREAD

**Issue by dkearns** [universal-ctags/ctags#940]
I'll take these.

**Comment by masatake** [comment]
FIne!

**Comment by dkearns** [comment]
I'm not sure what to do about Units/review-needed.r/unicode8.java.t.

It's not testing Unicode, the file is Latin 1, and the referenced bug fix on SF seems to indicate that it was probably only designed to catch accented Latin 1 letters.

This also appears to be an undocumented special case for Java and C#?

Should we rename it accented-latin1.java.t?

**Comment by masatake** [comment]
Please, rename it. Add the commets you wrote here to its commit log or extra README in the `*.d` dir.

**Comment by masatake** [comment]
Thank you, again.
