### ISSUE TITLE
Extract more information from C++ files

### ISSUE THREAD

**Issue by LucHermitte** [universal-ctags/ctags#948]
It'd be nice to know when a function is defined inlined (either within a class definition, or anywhere along with the inline keyword).

It's also be nice to extract the new C++11 information and know when a C++ function has been defaulted or deleted (respectively with `=default` and `= delete`).

`final` functions and classes, and `override` n functions may be interesting as well.

Thanks.

**Comment by pragmaware** [comment]
Such informations are already extracted and placed in the "properties" field.
See https://github.com/universal-ctags/ctags/tree/master/Units/parser-cxx.r/properties.cpp.d for an example of usage.

**Comment by pragmaware** [comment]
Let me know if you find a specific property that is missing, I'll try to add it if feasible.

**Comment by LucHermitte** [comment]
This is very nice. I've missed this feature. Thank you for the information. 
Was it already in exuberant ctags, or an addition of universal ctags?

However, `C02(int)` constructor (lines 18-20) should have been recognized as inline. Whilst the `inline` keyword is not specified, the function definition is still inline. See the C++standard §7.1.2/3 _"A function defined within a class definition is an inline function."_ I'll reopen the issue for this case.
Note: lines 25 and 28, `mf05` and `mf06` are explicitly marked inline, and yet, this is not required. (This is mostly a cumbersome style, often a sign of poor knowledge of the language.)

I haven't checked yet whether `noexcept` specification, and inline namespace are also recognized. If this is the case, it could be nice to add them to your unit test.
