### ISSUE TITLE
Build process on MSYS

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#95]
@ffes, I would like to fix the issue you wrote in f-wndows.rst.

I need to see config.status, config.h and the output of make.
I'm not sure these files can be attached to this comment area.
If they cannot, could you send them to me, yamato@redhat.com?

**Comment by ffes** [comment]
Little update:

When I use ``./configure --host=i686-w64-mingw32 --disable-external-sort`` with Cygwin, I can build a native win32 ctags.exe. And I can do ``make units`` as well. Some tests fail. #211 has been opened and the others I have to see why they fail.

With MSYS it build as well when using ``./configure --disable-external-sort`` but ``make units`` does not work because there is no ``timeout`` command.

I still have to try MSYS2. I hope to do that tomorrow. When I know if that works, I can dive into these Cygwin Units test failures.

````
Summary (see CMDLINE.tmp to reproduce without test harness)
------------------------------------------------------------
  #passed:                                392
  #FIXED:                                 0
  #FAILED (unexpected-exit-status):       4
        conflib-simple
        ctags-simple
        mib-simple
        option-corpora-conflicts
  #FAILED (unexpected-output):            3
        bug1777340.java
        php-simple
        simple.php
  #TIMED-OUT (5s)                         0
  #skipped (features):                    3
        conflib-recursive
        xcmd-coffeetags
        xcmd-simple
  #skipped (languages):                   0
  #known-bugs:                            0
````

**Comment by ffes** [comment]
I also tried to build as a Cygwin application. That works as quite well. Only the ``php-simple`` and ``simple.php`` test fail. That is both times in the line with ``täyte`` in it. Have to find out why it fails though.

Know that Cygwin build != native win32 build. See f-windows.rst for details.

**Comment by b4n** [comment]
> That works as quite well. Only the ``php-simple`` and ``simple.php`` test fail. That is both times in the line with ``täyte`` in it. Have to find out why it fails though.

`php-simple` and `simple.php` (which actually are the same), and formerly bug1777340.java (before c9bd2546fb51c9dba49c012eea014dd53dc85f66) are probably the only tests that have non-ASCII output (they are ISO-8859-1), so it probably is an encoding issue of some sort.

**Comment by k-takata** [comment]
Can we close this?

**Comment by cweagans** [comment]
Sorry for the noise. Just switching the "Release blocker" tag for the "Initial release" milestone so that everything is tracked in one place.

**Comment by k-takata** [comment]
I think this has already done. Closing.
