### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by tarzanek** [universal-ctags/ctags#980]
Hi guys,
we use ctags as "daemon" and give it files to parse and consume its stdout, but 
it grows to immense sizes on sources I'd never expect that:
 29478 tarzanek 8789180K 3785920K cpu1     22    0   1:04:12 13.53% ctags/1
8G of mem!
(3G RSS)

We basically pass on whole android sources to ctags run like this:
tarzanek@XXX:/YYY/ZZZ pargs 29478
29478:  /bin/exctags --c-kinds=+l --langmap=clojure:+.cljs --langmap=clojure:+.cljx --j
argv[0]: /bin/exctags
argv[1]: --c-kinds=+l
argv[2]: --langmap=clojure:+.cljs
argv[3]: --langmap=clojure:+.cljx
argv[4]: --java-kinds=+l
argv[5]: --sql-kinds=+l
argv[6]: --Fortran-kinds=+L
argv[7]: --C++-kinds=+l
argv[8]: --file-scope=yes
argv[9]: -u
argv[10]: --filter=yes
argv[11]: --filter-terminator=__ctags_done_with_file__\n
argv[12]: --fields=-anf+iKnS
argv[13]: --excmd=pattern
argv[14]: --langmap=sh:+.kshlib
argv[15]: --langmap=sql:+.plb
argv[16]: --langmap=sql:+.pls
argv[17]: --langmap=sql:+.pld
argv[18]: --langmap=sql:+.pks
argv[19]: --langdef=scala
argv[20]: --langmap=scala:.scala
argv[21]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*class[[:space:]]+([a-zA-Z0-9_]+)/\\4/c,classes/
argv[22]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*object[[:space:]]+([a-zA-Z0-9_]+)/\\4/c,objects/
argv[23]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*case class[[:space:]]+([a-zA-Z0-9_]+)/\\4/c,case classes/
argv[24]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*case object[[:space:]]+([a-zA-Z0-9_]+)/\\4/c,case objects/
argv[25]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*trait[[:space:]]+([a-zA-Z0-9_]+)/\\4/t,traits/
argv[26]: --regex-scala=/^[[:space:]]*type[[:space:]]+([a-zA-Z0-9_]+)/\\1/T,types/
argv[27]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*def[[:space:]]+([a-zA-Z0-9_]+)/\\3/m,methods/
argv[28]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*val[[:space:]]+([a-zA-Z0-9_]+)/\\3/l,constants/
argv[29]: --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*var[[:space:]]+([a-zA-Z0-9_]+)/\\3/l,variables/
argv[30]: --regex-scala=/^[[:space:]]*package[[:space:]]+([a-zA-Z0-9_.]+)/\\1/p,packages/
argv[31]: --langdef=haskell
argv[32]: --langmap=haskell:.hs.hsc
argv[33]: --regex-haskell=/^[[:space:]]*class[[:space:]]+([a-zA-Z0-9_]+)/\\1/c,classes/
argv[34]: --regex-haskell=/^[[:space:]]*data[[:space:]]+([a-zA-Z0-9_]+)/\\1/t,types/
argv[35]: --regex-haskell=/^[[:space:]]*newtype[[:space:]]+([a-zA-Z0-9_]+)/\\1/t,types/
argv[36]: --regex-haskell=/^[[:space:]]*type[[:space:]]+([a-zA-Z0-9_]+)/\\1/t,types/
argv[37]: --regex-haskell=/^([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\\1/f,functions/
argv[38]: --regex-haskell=/[[:space:]]+([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\\1/f,functions/
argv[39]: --regex-haskell=/^(let|where)[[:space:]]+([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\\2/f,functions/
argv[40]: --regex-haskell=/[[:space:]]+(let|where)[[:space:]]+([a-zA-Z0-9_]+).*[[:space:]]+={1}[[:space:]]+/\\2/f,functions/

the file which was processed was:
./android/google/external/chromium_org/v8/test/cctest/gay-precision.cc
(5.8MB file with lots of floats e.g. - https://android.googlesource.com/platform/external/chromium_org/v8/+/android-4.4.1_r1.0.1/test/cctest/gay-precision.cc )
any clues  what is going on?

version is latest:
Universal Ctags 0.0.0(ceb9d87), Copyright (C) 2015 Universal Ctags Team

Thnx
Lubos

**Comment by tarzanek** [comment]
It seems to reproduce one really just needs that .cc file and runs:
./ctags --C++-kinds=+l  ../android/google/external/chromium_org/v8/test/cctest/gay-precision.cc 

and the other file also triggers huge usage android/google/external/chromium_org/v8/test/cctest/gay-shortest.cc  (6MB in size)

**Comment by tarzanek** [comment]
note that ctags 5.9 just work ;)

**Comment by masatake** [comment]
Could you try the version which you can get with git checkout `571821dcc7c81fe2d4c1181dcda81785156d2aaa^` ?
The last `^` is important.

**Comment by tarzanek** [comment]
yep, being on 571821dcc7c81fe2d4c1181dcda81785156d2aaa^ 
is almost instant reply with tags file, no leak at all ...

**Comment by tarzanek** [comment]
@pragmaware @masatake does it mean the limit has to be set?

**Comment by masatake** [comment]
Yes.
@pragmaware, could you set the limit again (with larger value as you want:-).

**Comment by tarzanek** [comment]
alt. we should provide some way for ctag to see that with such a big file the tokens won't fit available memory?
With above files I can easily eat 8GB ... which for a a file which is 6MB in size is definitely a bug imho ...

**Comment by masatake** [comment]
At glance we can shrink CXXToken struct.
1. With bit fields, uInternalScopeAccess and bFollowedBySpace can be merged into one byte,
2. pszWord can be shrunk in some case.

**Comment by pragmaware** [comment]
Hm.. on that file the token chain grows to hundreths of thousands of elements. Beside using a lot of memory it also slows down noticeably as the chain is repeatedly scanned as it grows.

I have optimized the re-scan so now it's pretty fast on that file. I have also reintroduced a large limit on the size of the token chain (16384). Hopefully only very large tables will trigger it...
We can still increase it (even 50000 works fine here). See #982

**Comment by tarzanek** [comment]
thank you sir, as soon as it's merged I can retest on my build farm

**Comment by tarzanek** [comment]
(I should have probably said dziękujemy bardzo piękne  :) )

**Comment by masatake** [comment]
Wow. I thought he was at the same time zone.

**Comment by pragmaware** [comment]
Prosze bardzo :)
(but I guess I should say more like "Není zač")
