### ISSUE TITLE
Class declaration not listed when in .cpp file (C++)

### ISSUE THREAD

**Issue by moshev** [universal-ctags/ctags#984]
Test setup:

    void bar();
    
    struct A {
        int m;
    	void foo();
    };
    
    void A::foo() {
    }
    
    void bar() {
    }

Put these in `test.cpp` and `test.h`, then run `ctags -f - --excmd=number --fields=afilknsSt --extra= --sort=no --append=no --language-force=c++ --c++-kinds=cdefglmnpstuvxz test.cpp` and similar for `test.h`.

When run on test.h, output is

    bar /home/moshev/Projects/tests/test.h      1;"     p       line:1  language:C++    typeref:typename:void   signature:()
    A   /home/moshev/Projects/tests/test.h      3;"     s       line:3  language:C++
    m   /home/moshev/Projects/tests/test.h      4;"     m       line:4  language:C++    struct:A        typeref:typename:int    access:public
    foo /home/moshev/Projects/tests/test.h      5;"     p       line:5  language:C++    struct:A        typeref:typename:void   access:public   signature:()
    foo /home/moshev/Projects/tests/test.h      8;"     f       line:8  language:C++    class:A typeref:typename:void   signature:()
    bar /home/moshev/Projects/tests/test.h      11;"    f       line:11 language:C++    typeref:typename:void   signature:()

but when run on test.cpp, output is

    foo /home/moshev/Projects/tests/test.cpp    8;"     f       line:8  language:C++    class:A typeref:typename:void   signature:()
    bar /home/moshev/Projects/tests/test.cpp    11;"    f       line:11 language:C++    typeref:typename:void   signature:()

Am I missing some option here? Why don't the `struct A` and `void bar` declarations appear in the output?

**Comment by masatake** [comment]
Add  `--extra+F`.

```
./ctags --list-extra                                                                                                                
#LETTER NAME                   ENABLED DESCRIPTION                   
F       fileScope              TRUE    Include tags of file scope    
```

Items in a header file may be referred from the other `*.h` and `*.cpp` files.
So we can say they have wider scope than file.
In other hand prototypes and types in `*.cpp` may NOT be referred from the other files.
So we can say they have file scope.

We don't assume including *.cpp files from *.cpp file.

**Comment by moshev** [comment]
Thanks!
