### ISSUE TITLE
Python parser stops after finding `Class(` in a string

### ISSUE THREAD

**Issue by blueyed** [universal-ctags/ctags#997]
Given the following test.py

```python
class Foo:
    def method(self):
        meh = 'Foo('

class NotFound:
    def notfound(self):
        pass
```

`ctags -f- test.py` results in only this:
```
Foo	test.py	/^class Foo:$/;"	c	language:Python
method	test.py	/^    def method(self):$/;"	m	language:Python	class:Foo
```

That's apparently of the string `Foo(` used in a class method, where `Foo` is the class itself.

I've tried to bisect it, bad it's in there since at least ~1 year ago already (cf9350b).

**Comment by b4n** [comment]
Hum, this isn't present in Geany, but apparently the parser has changed a lot (recently?) so it doesn't really help so much.

**Comment by b4n** [comment]
61ac9e7872a135a6d4485aaf1871f509f6f9736f works (but is almost one year old indeed).

**Comment by b4n** [comment]
bissection gives me 93f3c66536966e47de62dfe17ffb82373a17b2b9 as the first bad commit (5570b0ae1a26d420815c20f5ea97ce5924d3b2c6 being the last good, obviously)

**Comment by masatake** [comment]
I'll work on this in the highest priority. Thank you for reporting.

**Comment by b4n** [comment]
BTW, I believe it's because currently the Python parser doesn't actually understand short string literals, because it used not to do anything too fancy and nothing that was parsed could be a string literal.  But now it tries and deal with continuations, it needs parsing strings more correctly not to break.

**Comment by masatake** [comment]
@b4n Now I understand what you wrote.

**Comment by masatake** [comment]
We should not touch the current parser anymore.
I will introduce glib and write a newPython parser based on it.

**Comment by b4n** [comment]
> I need python parser should be rewritten in token based one.

I started that some (long) time ago, I should be able to dig it up if it can be useful.

> I will introduce glib and write a newPython parser based on it.

Why introducing a GLib dependency would help here?

**Comment by masatake** [comment]
> I started that some (long) time ago, I should be able to dig it up if it can be useful.

Yes! It must be useful.

> Why introducing a GLib dependency would help here?

It is not only for this task. I have wanted to use glib in ctags for long time.
I thought this is good time to introduce glib if I write a new parser for a language having enough complicated syntax from scratch. However, now I know I can start from your token based parser. Thank you.

**Comment by blueyed** [comment]
So you would not say to fix this bug for now? (without a rewrite)

**Comment by masatake** [comment]
@blueyed, no, I don't fix for now. However, I really need python parser in my daily job. So this is still highest prioritized issue. I would like to fix all bugs associated with *.b test cases in this rewritten. The most of all python test cases are reviewed, so we can do rewrite the parser.

**Comment by vhda** [comment]
Since I'm not familiar with glib, @masatake would you be so kind to explain what benefits we expect to obtain from adding a dependency to it?

**Comment by masatake** [comment]
@vhda, matured implementation of variety data structures including  double linked list, single linked list, hash table, automatically growing array. I think all of you love vString. But we have only vString. stringList is useful but we can store only vString to it.  In many places in ctags, you will find automatically growing array implementations.  We had not write them if we have glib.

I recommend you to read some headers of glib. One you know it, you don't want to write code in C without it.

**Comment by codebrainz** [comment]
The problem with GLib is it's quite bloated since it also includes all of GObject, GIO and several other modules that go beyond basic data structures. Why not just write a trivial dynamic array and use it everywhere in Ctags, even for vString? The GSList and GList data structures aren't very useful either, only GQueue provides a decent list interface (has head/tail pointers and length, so getting the length and appending aren't O(n) operations), but since linked lists are so trivial, it would be better to just use ad hoc intrusive lists as needed (or steal the list implementation from the Linux kernel).

**Comment by blueyed** [comment]
@masatake 
I see.  Although I would even try to fix this myself, if I had a few spare hours - but I can see that it's not worth it really when you plan to rewrite it anyway.
Thanks!

**Comment by b4n** [comment]
@blueyed #1003 fixes this:

```console
$ ./ctags -o- /tmp/997.py
Foo	/tmp/997.py	/^class Foo:$/;"	c
NotFound	/tmp/997.py	/^class NotFound:$/;"	c
method	/tmp/997.py	/^    def method(self):$/;"	m	class:Foo
notfound	/tmp/997.py	/^    def notfound(self):$/;"	m	class:NotFound
```
